- checkov/terraform/checks/resource/base_check.py
- checkov/terraform/checks/resource/registry.py
- checkov/terraform/context_parsers/base_parser.py
- checkov/terraform/output/record.py
- checkov/terraform/output/report.py
Redesigned the skip check comment format to the following:
`# checkov:skip:<check-Id>:<suppress-comment>`
- Support an optional suppression comment
- Comment is limited to one skipped check in a line
Illustration:
> Support of suppress comment in skipped checks

- checkov/terraform/checks/resource/aws/SecurityGroupUnrestrictedIngress22.py
- checkov/terraform/checks/resource/aws/SecurityGroupUnrestrictedIngress3389.py
- tests/terraform/runner/resources/example/example.tf
fix #38 referencing a security_group instead of cidr_block in a secuity group rule causes an exception
> fix: security_groups in aws_security_group rule not supported

- Dockerfile
The resulting image can be used by mounting the terraform files at a location and directing checkov to scan that location:
$ docker container run -v /host/path/tf:/tf <image> -d /tf
The entry point can also be overridden to bash for other uses, such as CI commands:
$ docker container run -i -v /host/path/tf:/tf --entrypoint=/bin/bash <image>
> chore(docker): adding a docker file

- checkov/terraform/checks/data/aws/AdminPolicyDocument.py
- tests/terraform/checks/data/aws/test_AdminPolicyDocument.py
aws_iam_policy_document is a `data` entity, not a `resource`
> fix aws_iam_policy_document check type

- checkov/terraform/evaluation/evaluation_methods/const_variable_evaluation.py
variable evaluation operates on file that had been successfully parsed by `hcl2` parser.
> Variable evaluation bugfix

- checkov/terraform/checks/resource/aws/LaunchConfigurationEBSEncryption.py
It is easy to create an `aws_instance` without a specified block device.  Unfortunately, the default block device is not encrypted.
This PR fails CKV_AWS_8 if no block_device is specified.
> Fail CKV_AWS_8 if block_device is not specified

- checkov/terraform/output/record.py
This adds formatting to align the printing of terraform when output to console.
```bash
Check: CKV_AWS_21: "Ensure all data stored in the S3 bucket have versioning enabled"
FAILED for resource: aws_s3_bucket.default
File: /s3:91-102
91 | resource "aws_s3_bucket" "default" {
92 |   bucket = lower(random_id.s3_bucket.b64_url)
93 |   acl    = "private"
94 |
95 |   tags = merge(
96 |     local.default_tags,
97 |     {
98 |       Name        = "GitHub Webhook Listener"
99 |       Environment = "prod"
100 |     }
101 |   )
102 | }
```
```bash
Check: CKV_AWS_21: "Ensure all data stored in the S3 bucket have versioning enabled"
FAILED for resource: aws_s3_bucket.default
File: /s3:91-102
91  | resource "aws_s3_bucket" "default" {
92  |   bucket = lower(random_id.s3_bucket.b64_url)
93  |   acl    = …
```
> [Add] Terraform Code Alignment in console output

- checkov/terraform/models/enums.py
- docs/2.Concepts/Custom Scans.md
This is intented to be used for Stylistic and Convention based checks.
For example underscores vs dashes in terraform entity names.
This might be opinionated but I am currently using custom checks. So this won't impact master
> [Add] enum for convention type checks

- checkov/cloudformation/checks/resource/aws/SecurityGroupUnrestrictedIngress22.py
- checkov/cloudformation/runner.py
fixed the filtering of non-cf template files, and support only primitive values of security group port check
> CloudFormation parsing bugfix

- checkov/terraform/checks/resource/aws/KinesisStreamEncryptionType.py
- tests/terraform/checks/resource/aws/test_KinesisStreamEncryptionType.py
Addresses https://github.com/bridgecrewio/checkov/issues/63. Simple check to see if the value of   encryption_type = "KMS" in the resource aws_kinesis_stream.
> Test for encryption setup for Kinesis stream

- checkov/terraform/checks/resource/gcp/GoogleBigQueryDatasetPublicACL.py
- tests/terraform/checks/resource/gcp/test_GoogleBigQueryDatasetPublicACL.py
First time contributing to Checkov 😄 
I added a new check to ensure that BigQuery datasets are not anonymously or publicly accessible.
https://www.terraform.io/docs/providers/google/r/bigquery_dataset.html#access
The `allowAuthenticatedUsers` _special_group_ works with the APIs, but the `allUsers` doesn't... After trying to add that group via CLI, I noticed that the Terraform statefile contains an `access` block with just the role defined, so I figured it's considered "all users".
The check is then also verifying if there's a user, group, domain or view in the access block.
> Adding check for BigQuery datasets not being anonymously or publicly accessible

- checkov/terraform/checks/resource/gcp/GoogleCloudDNSKeySpecsRSASHA1.py
- checkov/terraform/checks/resource/gcp/GoogleCloudDNSSECEnabled.py
- tests/terraform/checks/resource/gcp/test_GoogleCloudDNSKeySpecsRSASHA1.py
- tests/terraform/checks/resource/gcp/test_GoogleCloudDNSSECEnabled.py
I added a couple of new checks to ensure that DNSSEC is enabled in Cloud DNS and that the RSASHA1 algorithm is not used for the keys.
https://www.terraform.io/docs/providers/google/r/dns_managed_zone.html#state
https://www.terraform.io/docs/providers/google/r/dns_managed_zone.html#algorithm
> Adding DNSSEC checks for Cloud DNS

- HomebrewFormula/checkov.rb
- README.md
This PR adds the ability to install checkov using homebrew on OSX (as requested in #218)
Once merged into master, OSX users should execute:
> $ brew tap bridgecrewio/checkov https://github.com/bridgecrewio/checkov
> $ brew update
> $ brew install checkov
On each release, the formula should be updated to reflect the latest release
> Adding brew package for homebrew (OSX)

- setup.py
updated python-hcl2 package version from 0.2.0 to 0.2.5. 
Solves #223 
> python-hcl2 package version update

- checkov/terraform/checks/resource/aws/LambdaEnvironmentCredentials.py
- tests/terraform/runner/resources/example/example.tf
the tf example for an error (delete_after):
environment {
variables = {
es_endpoint  = var.es_endpoint
index        = 'all'
delete_after = 15
index_format = var.index_format
sns_arn      = var.sns_arn
}
}
> handle environment value as int instead of string.

- checkov/terraform/checks/resource/aws/S3PublicACLRead.py
- checkov/terraform/checks/resource/aws/S3PublicACLWRITE.py
- tests/terraform/checks/resource/aws/test_S3PublicACLRead.py
- tests/terraform/checks/resource/aws/test_S3PublicACLWrite.py
Separate read access and write access as they should be looked at differently - no bucket should have public write access, unlike public read for websites, for example
> Fix ACL checks - separate read and write permissions

- checkov/main.py
The original parameters are singular and for some reason were put in plural form
This should address issue #258 
> Fix typo when verifying usage of check/skip-check

- Pipfile.lock
- checkov/common/models/consts.py
- checkov/main.py
- checkov/terraform/checks/resource/aws/LaunchConfigurationEBSEncryption.py
- checkov/terraform/checks/resource/aws/S3Encryption.py
- checkov/terraform/checks/resource/aws/SQSQueueEncryption.py
- checkov/terraform/checks/resource/base_resource_value_check.py
- Support of hierarchy on `BaseResourceValueCheck` checks, in order to support non-root attribute checks
- Support of multiple expected values
- Support of a default expected value, according to best practices
- Identify attributes which are variable dependant, and mark these resources as `PASSED` under the check
- Incorporation of `CKV_ANY` value,  in the case the check looks for any value for the inspected key
- Conversion of `S3Encryption`, `LaunchConfigurationEBSEncryption` and `SQSQueueEncryption` to implement the  `BaseResourceValueCheck` class
> Base resource value checks enhancements

- checkov/kubernetes/checks/ImagePullPolicyAlways.py
- checkov/kubernetes/checks/ImageTagFixed.py
The image checks fail if the image has a digest (e.g., `repo/image:tag@sha256:12345`), because splitting on `:` returns three values.
This fixes that by removing the digest if it's present.
> Handle digests in image names for image pull checks

- checkov/common/util/banner.py
- checkov/kubernetes/checks/ImageDigest.py
- checkov/terraform/checks/resource/aws/IAMRoleAllowAssumeFromAccount.py
- tests/kubernetes/checks/example_ImageDigest/imageWithTagAndDigest-PASSED.yaml
- tests/kubernetes/checks/example_ImageDigest/job-ImageTagLatest-FAILED.yaml
- tests/kubernetes/checks/example_ImageDigest/kafka-PASSED.yaml
- tests/kubernetes/checks/example_ImageDigest/storm-zookeeper-FAILED.json
- tests/kubernetes/checks/example_ImagePullPolicy/imageWithDigest-PullPolicyAlways-PASSED.yaml
- tests/kubernetes/checks/example_ImageTagFixed/imageWithDigest-PASSED.yaml
- tests/kubernetes/checks/test_ImageDigest.py
- tests/kubernetes/checks/test_ImagePullPolicyAlways.py
- tests/kubernetes/checks/test_ImageTagFixed.py
- tests/terraform/evaluation/test_base_variable_evaluation.py
This PR adds a rule for checking whether a container image is specified with a digest, as is best practice. It ignores whether a tag is present or not, because it technically doesn't matter (the digest will always be used, and the tag will be ignored).
It also adds tests for the fixes in https://github.com/bridgecrewio/checkov/pull/278.
Finally, it also cleans up some tests to eliminate warnings in test output.
> Image digest rule

- checkov/cloudformation/checks/resource/aws/RDSEncryption.py
- checkov/cloudformation/checks/resource/aws/RDSPubliclyAccessible.py
- tests/cloudformation/checks/resource/aws/example_RDSEncryption/RDSEncryption-FAIL.yaml
- tests/cloudformation/checks/resource/aws/example_RDSEncryption/RDSEncryption-FAILED-2.yaml
- tests/cloudformation/checks/resource/aws/example_RDSEncryption/RDSEncryption-PASSED.yaml
- tests/cloudformation/checks/resource/aws/example_RDSPubliclyAccessible/RDSPubliclyAccessible-FAIL.yaml
- tests/cloudformation/checks/resource/aws/example_RDSPubliclyAccessible/RDSPubliclyAccessible-PASSED-2.yaml
- tests/cloudformation/checks/resource/aws/example_RDSPubliclyAccessible/RDSPubliclyAccessible-PASSED.yaml
- tests/cloudformation/checks/resource/aws/test_RDSEncryption.py
- tests/cloudformation/checks/resource/aws/test_RDSPubliclyAccessible.py
Adds equivalent RDS checks for Cloudformation as Terraform has.
> Cloudformation RDS check parity

- README.md
- checkov/kubernetes/checks/DefaultNamespace.py
- checkov/kubernetes/checks/ReadinessProbe.py
- kubernetes/checkov-cronjob.yaml
- kubernetes/checkov-job.yaml
- tests/kubernetes/checks/example_DefaultNamespace/default-k8s-service-and-sa-PASSED2.yaml
- tests/kubernetes/checks/example_LivenessReadiness/pod-from-job.yaml
- tests/kubernetes/checks/test_DefaultNamespace.py
- tests/kubernetes/checks/test_LivenessProbe.py
- tests/kubernetes/checks/test_ReadinessProbe.py
* Updated readme for Kubernetes annotations
* Updated default namespace check to ignore default SA and kubernetes service
* Updated readiness probe to ignore runtime pods launched from jobs/cronjobs
* Updated k8s runtime job/cronjob spec
> Updating Kubernetes checks and runtime resources

- checkov/terraform/checks/resource/aws/PasswordPolicyExpiration.py
- tests/terraform/checks/resource/aws/test_PasswordPolicyExpiration.py
A Terraform configuration like this fails with Checkov 1.0.366:
```hcl
resource "aws_iam_account_password_policy" "default" {
allow_users_to_change_password = true
minimum_password_length        = 16
require_lowercase_characters   = true
require_numbers                = true
require_uppercase_characters   = true
require_symbols                = true
password_reuse_prevention      = 24
max_password_age               = 60
}
```
I had not noticed because my configuration previously used 90 days following CIS but there's a separate issue with the configuration not matching the “within 90 days or less” description (see below).
The logic in this check was previously inverted and would only pass configurations which were outside of the expected range:
```
(Pdb) conf[key][0] = None
(Pdb) p not …
```
> Fix logic in IAM Password Policy Expiration check

- checkov/cloudformation/parser/cfn_json.py
Python porting best practice [___use feature detection instead of version detection___](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection).
> Use feature detection instead of version detection

- checkov/terraform/checks/resource/gcp/GKEUseCosImage.py
- tests/terraform/checks/resource/gcp/test_GKEUseCosImage.py
issue: https://github.com/bridgecrewio/checkov/issues/364
CKV_GCP_22 should not trigger with remove_default_node_pool=true
> CKV_GCP_22 should not trigger with remove_default_node_pool=true

- checkov/terraform/checks/resource/aws/EKSPublicAccess.py
- checkov/terraform/checks/resource/aws/EKSSecretsEncryption.py
- checkov/terraform/checks/resource/aws/PasswordPolicyExpiration.py
- checkov/terraform/checks/resource/aws/PasswordPolicyLength.py
- checkov/terraform/checks/resource/aws/PasswordPolicyLowercaseLetter.py
- checkov/terraform/checks/resource/aws/PasswordPolicyNumber.py
- checkov/terraform/checks/resource/aws/PasswordPolicyReuse.py
- checkov/terraform/checks/resource/aws/PasswordPolicySymbol.py
- checkov/terraform/checks/resource/aws/PasswordPolicyUppercaseLetter.py
- checkov/terraform/checks/resource/gcp/GoogleCloudDNSSECEnabled.py
- checkov/terraform/checks/resource/gcp/GoogleKMSRotationPeriod.py
Converted the following checks to implement `BaseResourceValueCheck`
- aws/EKSPublicAccess.py
- aws/EKSSecretsEncryption.py
- aws/PasswordPolicyExpiration.py
- aws/PasswordPolicyLength.py
- aws/PasswordPolicyLowercaseLetter.py
- aws/PasswordPolicyNumber.py
- aws/PasswordPolicyReuse.py
- aws/PasswordPolicySymbol.py
- aws/PasswordPolicyUppercaseLetter.py
- gcp/GoogleCloudDNSSECEnabled.py
- gcp/GoogleKMSRotationPeriod.py
> conversion of BaseResourceAttributeValue checks

- checkov/serverless/parsers/context_parser.py
- checkov/serverless/parsers/parser.py
- checkov/serverless/runner.py
- tests/serverless/checks/aws/example_S3PublicACLRead/S3PublicACLRead-FAILED/serverless.yml
- tests/serverless/checks/aws/example_S3PublicACLRead/S3PublicACLRead-PASSED/serverless.yml
- tests/serverless/checks/aws/test_S3PublicACLRead.py
- Unit test CF sub-template found in serverless files
- Support the direct provider name syntax, infer the provider type in context parser
> Serverless sub-cf template unit test

- .github/workflows/build.yml
- .github/workflows/coverage.yml
Github actions creates commit messages that makes it hard to track release changes. instead we will use the HEAD branch last commit as a message to make it easy tracking each release change
> edit git releases message

- checkov/terraform/checks/resource/azure/StorageAccountLoggingQueueServiceEnabled.py
- tests/terraform/checks/resource/azure/test_StorageAccountLoggingQueueServiceEnabled.py
I'm checking my Azure Storage account with Ckeckov.
The account kind is *BlobStorage*, the rule *CKV_AZURE_33* should not apply in this case.
```hcl
resource "azurerm_storage_account" "ingestion" {
#checkov:skip=CKV_AZURE_3:skip for bug test
#checkov:skip=CKV_AZURE_35:skip for bug test
name                     = "stocheckov"
resource_group_name      = "rg-checkov-test"
location                 = "checkov"
account_kind             = "BlobStorage"
account_tier             = "Standard"
account_replication_type = "LRS"
}
```
```
checkov -d . --framework terraform --output cli --quiet
| (__| | | |  __/ (__|   < (_) \ V /
\___|_| |_|\___|\___|_|\_\___/ \_/
by bridgecrew.io | version: 1.0.397
terraform …
```
> CKV_AZURE_33 queue logging and account kind

- tests/common/test_platform_integration.py
Found with an outbound firewall notification, tests were reaching out to test.com. Using `.invalid` on the host name prevents a lookup and the test doesn't seem to care if the connect succeeds or not.
> Change test host name to prevent bogus connections to test.com

- checkov/terraform/checks/resource/aws/AbsSecurityGroupUnrestrictedIngress.py
- tests/terraform/checks/resource/aws/test_SecurityGroupUnrestrictedIngress22.py
This PR makes two main changes:
1. 
Modify the AWS SG ingress check to work for ingress rules specified within the aws_security_group resource as well as standalone aws_security_group_rule resources. It also modifies the return values to UNKNOWN for SGs that do not define any ingress blocks, to prevent the root SG object from passing the check even if its separate rule fails the check.
For example, the following resources will result in one FAIL check and zero PASS:
```
resource "aws_security_group" "bar-sg" {
name   = "sg-bar"
vpc_id = aws_vpc.main.id
}
resource "aws_security_group_rule" "ingress" {
type              = "ingress"
from_port         = 22
to_port           = 22
protocol          = "tcp"
cidr_blocks       = ["192.168.0.0/16", "0.0.0.0/0"]
security_group_id = …
```
> add check for aws_security_group_rule resource

- checkov/kubernetes/checks/AllowPrivilegeEscalation.py
- checkov/kubernetes/checks/AllowedCapabilities.py
- checkov/kubernetes/checks/AllowedCapabilitiesSysAdmin.py
- checkov/kubernetes/checks/CPULimits.py
- checkov/kubernetes/checks/CPURequests.py
- checkov/kubernetes/checks/ContainerSecurityContext.py
- checkov/kubernetes/checks/DropCapabilities.py
- checkov/kubernetes/checks/HostPort.py
- checkov/kubernetes/checks/ImageDigest.py
- checkov/kubernetes/checks/ImagePullPolicyAlways.py
- checkov/kubernetes/checks/ImageTagFixed.py
- checkov/kubernetes/checks/KubernetesDashboard.py
- checkov/kubernetes/checks/LivenessProbe.py
- checkov/kubernetes/checks/MemoryLimits.py
- checkov/kubernetes/checks/MemoryRequests.py
- checkov/kubernetes/checks/MinimizeCapabilities.py
- checkov/kubernetes/checks/PrivilegedContainers.py
- checkov/kubernetes/checks/ReadOnlyFilesystem.py
- checkov/kubernetes/checks/ReadinessProbe.py
- checkov/kubernetes/checks/Secrets.py
- checkov/kubernetes/checks/Tiller.py
- checkov/kubernetes/runner.py
- checkov/terraform/context_parsers/base_parser.py
- checkov/terraform/context_parsers/parsers/provider_context_parser.py
- tests/terraform/runner/resources/many_providers/main.tf
- tests/terraform/runner/test_runner.py
This PR adds:
1. Uniqueness to kubernetes resources.
2. Uses provider aliases for uniqueness in terraform providers through the context parser.
> Make IDs of k8s and terraform providers unique

- checkov/terraform/checks/data/aws/StarActionPolicyDocument.py
- checkov/terraform/checks/resource/aws/IAMAdminPolicyDocument.py
- checkov/terraform/checks/resource/aws/IAMStarActionPolicyDocument.py
- tests/terraform/checks/resource/aws/test_IAMAdminPolicyDocument.py
- tests/terraform/checks/resource/aws/test_IAMStarActionPolicyDocument.py
Scan all statements of an IAM policy document, instead of only the first one
Resolves #443
> support multiple statements IAM policies

- docs/documentation.md
`Introduction/Getting%20Started.md` does not have a redirect setup to `Introduction/Getting%20Started.html`.  Changed link to point directly to html.
> Update broken link in documentation.md

- checkov/kubernetes/checks/Tiller.py
- checkov/kubernetes/checks/TillerDeploymentListener.py
- checkov/kubernetes/checks/TillerService.py
- tests/kubernetes/checks/example_TillerDeploymentListener/nginx-deployment-UNKNOWN.yaml
- tests/kubernetes/checks/example_TillerDeploymentListener/tiller-deployment_FAILED.json
- tests/kubernetes/checks/example_TillerDeploymentListener/tiller-deployment_FAILED_WRONGARG.yaml
- tests/kubernetes/checks/example_TillerDeploymentListener/tiller-deployment_PASSED_LOCALHOST.json
- tests/kubernetes/checks/example_TillerDeploymentListener/tiller-deployment_PASSED_LOOPBACK.json
- tests/kubernetes/checks/example_TillerService/tiller-services.yaml
- tests/kubernetes/checks/test_TillerDeploymentListener.py
- tests/kubernetes/checks/test_TillerService.py
This adds two checks for limiting the exposure of a Tiller deployment when using Helm v2:
1. Make sure there is not a service
2. Make sure the deployment only listens on localhost. This still allows authenticated client connections to be proxied in, but prevents requests from within the cluster.
Taken from: https://engineering.bitnami.com/articles/helm-security.html
> add checks for tiller server config

- checkov/runner_filter.py
- tests/common/test_runner_filter.py
This PR allows the `-c` flag to work with external checks.
> allow external checks to be set using -c

- checkov/main.py
Fixes the validation that makes sure the repo-id has a slash. It got skipped before, causing the creation of invalid "integrations" in BC.
> fix skipped repo-id format check

- checkov/terraform/checks/resource/aws/SQSPolicy.py
- tests/terraform/checks/resource/aws/test_SQSPolicy.py
CKV_AWS_72 was created to fix issue #179 however, currently matches `principal` not `action`.
This PR corrects that mistake!
> Correct CKV_AWS_72 to match Action not Principal

- checkov/terraform/checks/resource/azure/StorageAccountMinimumTlsVersion.py
- tests/terraform/checks/resource/azure/test_StorageAccountMinimumTlsVersion.py
Add new scan rule to make sure storage accounts use the latest TLS version.
Reference: https://docs.microsoft.com/en-us/azure/storage/common/transport-layer-security-configure-minimum-version?tabs=portal
> CKV_AZURE_44 Enforce a minimum required version of Transport Layer Security (TLS) for requests to a storage account

- checkov/terraform/checks/resource/aws/APIGatewayAccessLogging.py
- tests/terraform/checks/resource/aws/test_APIGatewayAccessLogging.py
Closes #186
this may be simplified to check just for `access_log_settings` but checking `destination_arn` argument under `access_log_settings` seems more future proof
> Add API Gateway access logs check

- .github/exclude-patterns.txt
- checkov/common/util/secrets.py
- checkov/terraform/checks/resource/aws/EC2Credentials.py
- checkov/terraform/checks/resource/aws/LambdaEnvironmentCredentials.py
- tests/unit/test_secrets.py
This PR reworks the secrets regexes (currently only used for EC2 / Lambda secrets) to be more extensible for use in other checks (e.g., Azure or GCP).
It adds an extended list of regexes taken from git-secrets, and provides a mechanism for this list to be expanded without any changes to checks themselves.
It also adds some categories to the regexes, so that if desired, a particular check can only use a certain list (e.g., AWS only).
The existing EC2 and Lambda checks will continue to only check AWS values, so this should not change any existing check results.
> refactor secrets regexes to be more expandable

- checkov/terraform/checks/module/base_module_check.py
- tests/terraform/runner/test_runner.py
There is only one way to use `supported_resources` and that is setting it to `['module']`. To reduce confusion when using the base class, it is now deprecated and set automatically.
> Make supported_resources deprecated

- checkov/common/util/docs_generator.py
In the list of all checks module checks where not included. (Currently there are no such checks and until the `--list` option will mind `--external-checks-dir` there probably won't be any in the future.)
> Include module checks in get_checks() result

- checkov/main.py
- docs/1.Introduction/Getting Started.md
Removed "can be repeated" for `-d` / `--directory` options from docs and CLI help.
> Doc update for issue #561

- checkov/serverless/parsers/parser.py
Wrapped replacing `altered_value` with try/except to prevent trying to perform `altered_value.replace(match[0], source_value)` when `source_value` is not a string.
> Fix TypeError when replacing string in serverless

- checkov/terraform/checks/resource/aws/RedshitClusterPubliclyAvailable.py
- tests/terraform/checks/resource/aws/test_RedshiftClusterPubliclyAccessible.py
Hi,
I based this on the `RDSPubliclyAccessible.py` check but there is one issue that I cannot understand. When it comes to `redshift_cluster` documentation states that `publicly_available` is set to true by default. So I would like to make sure that if someone creates a reasource and does not specify this option Checkov should still fail, as the cluster will be available publicly. 
Based on the `RDSPubliclyAccessible.py` tests, it should fail the check, but I'm probably missing something.
Closes https://github.com/bridgecrewio/checkov/issues/162
> Add new check: Redshift cluster should not be publicly available [terraform]

- checkov/cloudformation/checks/resource/aws/ALBListenerHTTPS.py
- checkov/terraform/checks/resource/aws/EC2PublicIP.py
- checkov/terraform/checks/resource/aws/IMDSv1Disabled.py
- tests/terraform/checks/resource/aws/test_EC2PublicIP.py
From @0xdabbad00's [AWS Security Maturity Roadmap](https://summitroute.com/downloads/aws_security_maturity_roadmap-Summit_Route.pdf):
```
Resources such as EC2s and S3 buckets should not be publicly accessible, but instead should have an ELB or
CloudFront in front them. This has a number of benefits including being able to make use of AWS Shield
(DDoS protection), AWS WAF, and a more standardized means of logging access. This has operations
improvements such as an ability to scale and reduced latency.
```
> Check for ec2 instances with public IPs

- checkov/cloudformation/checks/resource/aws/S3PublicACLRead.py
- checkov/terraform/checks/resource/aws/S3PublicACLRead.py
- tests/cloudformation/checks/resource/aws/test_S3BlockPublicACLs.py
- tests/terraform/checks/resource/aws/test_S3PublicACLRead.py
> Add authenticated-read to set of "public" ACL values for s3 buckets

- checkov/terraform/checks/resource/azure/NSGRulePortAccessRestricted.py
Converting the protocol input to uppercase for `TCP` equality.
Here are some scan results used against the same code provided in the issue #601 
1. Failing scans 
```
terraform scan results:
Passed checks: 0, Failed checks: 2, Skipped checks: 0
Check: CKV_AZURE_9: "Ensure that RDP access is restricted from the internet"
FAILED for resource: azurerm_network_security_group.network_security_group
File: /main.tf:22-50
Guide: https://docs.bridgecrew.io/docs/bc_azr_networking_2
22 | resource "azurerm_network_security_group" "network_security_group" {
23 |   name                = "${var.location_shortcode}-${var.application_name}-nsg"
24 |   location            = …
```
> Fixes CKV_AZURE_9 & CKV_AZURE_10 - Scan fails if protocol value doesn't match TCP

- Dockerfile
Followed some best practices for dockerfiles and improved the size (around 17MB on my machine) and it also should be better in terms of layers and caching them.
> Decrease docker image size and improve cache

- checkov/terraform/runner.py
1. Scan the tf_definitions once to identify all the values that should be replaced with `true` or `false`
2. If context is given, don't recompute variables in the tf_definitions - it should already have been computed.
This turned a repo that took over 16 minutes (960 seconds) to less than 7 minutes (409 seconds)
> Improve performance of terraform scanning

- checkov/terraform/checks/resource/aws/ElasticsearchNodeToNodeEncryption.py
- tests/terraform/checks/resource/aws/test_ElasticsearchNodeToNodeEncryption.py
Fix ElasticsearchNodeToNodeEncryption check - wrong access to instance_count and node_to_node_encryption
> Fix ElasticsearchNodeToNodeEncryption check

- checkov/terraform/checks/resource/gcp/GKEPublicControlPlane.py
Handle a case where cidr_block_conf's value is a string (local block).
> Edge case handling in CKV_GCP_18

- checkov/terraform/checks/resource/aws/DocDBTLS.py
- tests/terraform/checks/resource/aws/test_DocDBTLS.py
Hello, first time adding a check to this project but i've tried to follow the helper documentation and i've found it very useful thus far!
This change is the terraform check implementation and unit tests for ensuring DocumentDB does not have in-flight encryption disabled.
Issue: https://github.com/bridgecrewio/checkov/issues/165
As mentioned in the issue the DocDB default is to have tls enabled, so in this check we just need to check that an explicit disable is not found for the configuration.
Provider doc for the configuration: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster_parameter_group
The type was a bit confusing for me so I verified through the provider code to ensure it was a Type Set and I used the hcl2 library to ensure that the test …
> check - test - Document DB Encryption in transit not disabled - Terraform

- checkov/kubernetes/checks/DockerSocketVolume.py
Check that spec["volumes"] is not None
> Improve CKV_K8S_27

- checkov/terraform/checks/resource/aws/S3ProtectAgainstPolicyLockout.py
- tests/terraform/checks/resource/aws/test_S3ProtectAgainstPolicyLockout.py
Suggestion based on this thread: https://twitter.com/0xdabbad00/status/1319065946770661376
Check that a resource policy is not causing a "Deny" to all principals, locking all non-root users out of the bucket.
Requirements needing the root user credentials to be available to undo a fix should be limited/removed at buildtime where possible. 
Requesting review from @nimrodkor and validation of usecase & test examples by https://twitter.com/0xdabbad00 
> Prevent S3 lockouts, tests for S3:* DENY resource policies.

- checkov/terraform/checks/resource/aws/IAMAdminPolicyDocument.py
- checkov/terraform/checks/resource/aws/IAMStarActionPolicyDocument.py
- checkov/terraform/checks/resource/aws/S3AllowsAnyPrincipal.py
Statement may not always be a list.
Checks in this PR found via simple `grep -r "for statement in policy_block" .` 
> Fix checks not using force_list() when looping on policy_block['statement']

- checkov/cloudformation/checks/resource/aws/DocDBEncryption.py
- tests/cloudformation/checks/resource/aws/example_DocDBEncryption/DocDBEncryption-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_DocDBEncryption/DocDBEncryption-PASSED.yaml
- tests/cloudformation/checks/resource/aws/test_DocDBEncryption.py
Hello,
First CF check I have added so I've tried to replicate based on some other similar checks.
To close issue https://github.com/bridgecrewio/checkov/issues/130 (see comments there).
This check corresponds with this terraform check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/DocDBEncryption.py and so I have replicated the type and description.
Notice that there are not many fields in the provided positive and negative tests data but this is because there are no required fields -  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html
2 more fields were added to test data based on CF lint failure from GH actions feedback.
**License**
By submitting this pull request, I confirm that my contribution is …
> added check and tests for docdb encryption for cloudformation

- checkov/cloudformation/checks/resource/aws/ALBListenerHTTPS.py
- checkov/terraform/checks/resource/aws/ALBListenerHTTPS.py
- tests/cloudformation/checks/resource/aws/example_ALBListener/ALBListenerHTTPS-PASSED-TCP.yaml
- tests/cloudformation/checks/resource/aws/example_ALBListener/ALBListenerHTTPS-PASSED-TCP_UDP.yaml
- tests/cloudformation/checks/resource/aws/example_ALBListener/ALBListenerHTTPS-PASSED-UDP.yaml
- tests/cloudformation/checks/resource/aws/test_ALBListenerHTTPS.py
- tests/terraform/checks/resource/aws/test_ALBListenerHTTPS.py
Closes #424 
CloudFormation config may need to be verified too - I haven't worked with it before (I'm more of a TF dude).
I wanted to add protocols to exclude from the check, as opposed to only checking for `HTTP` so that we don't miss any new protocols supported by the ALB. If new protocols supported by ALB are added then we would miss them in this check.
> Exclude NLBs from CKV_AWS_2 HTTPS check

- checkov/common/bridgecrew/platform_integration.py
- checkov/common/bridgecrew/platform_key.py
- checkov/common/runners/runner_registry.py
- checkov/main.py
- checkov/terraform/context_parsers/base_parser.py
- tests/terraform/context_parsers/mock_tf_files/mock.tf
- tests/terraform/context_parsers/test_base_parser.py
1. Turn BcPlatformIntegration into a singelton imported from anywhere
2. Ingest the new `idMapping` field to allow suppression by BC IDs
> Support suppressions by Bridgecrew IDs as well as Checkov IDs

- checkov/terraform/checks/resource/azure/NSGRulePortAccessRestricted.py
- tests/terraform/checks/resource/azure/test_NSGRuleRDPAccessRestricted.py
This PR adds some flexibility in parsing components of security group rules for Azure. Values like "internet" / "Internet", "allow" / "Allow" all seem to work when creating a resource via Terraform.
Also checks for "*" in the protocol.
(Note: we may need to update a lot of checks for case insensitivity, which Azure seems to be flexible about)
> Add case insensitivity to Azure SG rule values

- checkov/terraform/checks/resource/gcp/GoogleCloudSqlDatabasePublicallyAccessible.py
- tests/terraform/checks/resource/gcp/test_GoogleCloudSqlDatabasePublicallyAccessible.py
- tests/terraform/checks/resource/gcp/test_GoogleCloudSqlDatabasePublicallyAccessible/main.tf
The GCP SQL instance publicly accessible check was incorrect. It did not correctly handle the list of authorized networks. It also did not handle all possible ways in which this could be defined. The tests were not correct, so I rewrote those too.
> Fix GCP SQL Public check

- checkov/terraform/checks/resource/aws/DocDBEncryption.py
Currently, checkov checks both the DocDB cluster and its instances for `storage_encrypted = true`. However, `storage_encrypted` is only an attribute of `aws_docdb_cluster`, not `aws_docdb_cluster_instance`.
> Only check cluster for DocDB encryption on Terraform

- checkov/kubernetes/runner.py
Skip k8 scanning on files that contains malformed metadata and kind properties
> Non-string k8 properties protection

- checkov/cloudformation/checks/resource/aws/KMSKeyWildCardPrincipal.py
- tests/cloudformation/checks/resource/aws/example_KMSKeyWildCardPrincipal/KMSKeyWildCardPrincipal-FAILED-AWS-Wildcard.yaml
- tests/cloudformation/checks/resource/aws/example_KMSKeyWildCardPrincipal/KMSKeyWildCardPrincipal-FAILED-Wildcard.yaml
- tests/cloudformation/checks/resource/aws/example_KMSKeyWildCardPrincipal/KMSKeyWildCardPrincipal-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_KMSKeyWildCardPrincipal/KMSKeyWildCardPrincipal-PASSED.yaml
- tests/cloudformation/checks/resource/aws/test_KMSKeyWildCardPrincipal.py
Hi everyone,
I implemented this check as I believe this should be a security best practice - not to allow wildcard principal on KMS Key policies.
This check tackles both cases with `"Principal": "*"` and `"Principal": {"AWS": "*"}` which should be considered dangerous, and tests are handling both implementations.
More information can be found on the AWS documentation here:
https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html
> CloudFormation Check - KMS key policy wildcard principal

- docs/4.Integrations/gitlab.md
I have prepared a GitLab CI file that aligns with GitLab AutoDevOps a bit better as well as collects the junit output into the built-in Junit results display.
You could have your results placed in the GitLab Security Findings Consoles and Merge Requests, if you were able to provide an additional JSON output in the following documented format for security specific integrations: https://docs.gitlab.com/ee/user/application_security/sast/#reports-json-format
FYI I am a GitLab Solutions Architect and enjoy making CI CD extensions for it - let me know if there are any other ways I can help.
> Report results, Align with AutoDevOps

- checkov/terraform/parser.py
Removed resolved path pattern from module sources to avoid not finding the real module path.
> Fix local module loading

- checkov/terraform/module_loading/content.py
- checkov/terraform/module_loading/loaders/git_loader.py
- checkov/terraform/module_loading/registry.py
Created a cache for failed external modules clone urls to avoid trying to clone them multiple times.
> Cache failed external modules

- checkov/terraform/checks/resource/gcp/GoogleCloudDNSSECEnabled.py
- tests/terraform/checks/resource/gcp/test_GoogleCloudDNSSECEnabled.py
- tests/terraform/checks/resource/gcp/test_GoogleCloudDNSSECEnabled/main.tf
The GCP DNS managed zone resource only allows the DNS SEC to be enabled on public zones. This PR updates the check to skip private zones.
> update GCP DNSSEC check to skip private zones

- checkov/common/runners/runner_registry.py
- checkov/terraform/checks/resource/gcp/GoogleCloudDNSSECEnabled.py
- tests/terraform/checks/resource/gcp/test_GoogleCloudDNSSECEnabled.py
- tests/terraform/checks/resource/gcp/test_GoogleCloudDNSSECEnabled/main.tf
This PR fixes JUnit XML output when there are results for multiple reports (e.g., Terraform and CFN). Previously, it would print multiple distinct outputs, resulting in an invalid XML file.
> Combine junit reports

- checkov/terraform/plan_parser.py
- checkov/terraform/plan_runner.py
Fixes parsing json (e.g., for CFN), which crashes when it gets to the TF Plan runner.
> handle when json file is not a plan

- checkov/cloudformation/context_parser.py
- tests/cloudformation/parser/cfn_newline_at_end.yaml
- tests/cloudformation/parser/cfn_nonewline_at_end.yaml
- tests/cloudformation/parser/test_cfn_yaml.py
This PR changes the file line range to include the resource name in the output for CFN yaml files.
Before:
```
11 |     Type: 'AWS::S3::Bucket'
12 |     Properties:
13 |       BucketName: 'hello'
```
After:
```
10 |   MyBucket:
11 |     Type: 'AWS::S3::Bucket'
12 |     Properties:
13 |       BucketName: 'hello'
```
It also handles the case when there is not a newline at the end of a file, which caused the last line of a resource to be truncated.
It *also* handles blank lines between resources.
Finally, it adds tests for these cases.
> handle off-by-one errors in CFN line range calculation

- .github/dependabot.yml
This allows dependabot to check github actions weekly and submit PRs with version bumps.
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot
> Allow dependabot to check github actions weekly

- checkov/terraform/checks/resource/aws/MSKClusterEncryption.py
- checkov/terraform/checks/resource/aws/MSKClusterLogging.py
- tests/terraform/checks/resource/aws/test_MSKClusterEncryption.py
- tests/terraform/checks/resource/aws/test_MSKClusterLogging.py
We have had to customize these checks for our environment so I figured I would send them back upstream.
The objects for MSK are nested one level further than is currently being read in the checks.  Here are some examples of the objects as checkov sees them:
cloudwatch_logging: 
```
{'cloudwatch_logs': [{'enabled': [True], 'log_group': ['${aws_cloudwatch_log_group.msk[0].name}']}]}
```
encryption:
```
{'encryption_at_rest_kms_key_arn': ['${var.kms_key_id == "" ? module.kms.arn : var.kms_key_id}'], 'encryption_in_transit': [{'client_broker': ['TLS'], 'in_cluster': [True]}]}
```
As you can see from the data objects above, we need an additional `[0]` in order for the values to be compared properly
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> MSK checks not pulling in nested values correctly

- kubernetes/run_checkov.sh
> Explicitly scan only k8s when running with k8s docker

- README.md
- checkov/runner_filter.py
- tests/common/test_runner_filter.py
Add the ability to skip check using a pattern. (eg --skip-check CKV_AWS* to skip all aws check).
You can also use a deny list (--skip-check ) like before but with wildcards now like this --skip-check CKV_AWS*,CKV_AZURE*
> skip check using pattern (wildcards)

- checkov/terraform/checks/resource/azure/StorageAccountName.py
- tests/terraform/checks/resource/azure/test_StorageAccountName.py
check for the name field to exist, in case an empty configuration is scanned
> Handle empty azure storage configuration

- checkov/terraform/plan_parser.py
- tests/terraform/runner/resources/plan_data_resource_partial_values/tfplan.json
- tests/terraform/runner/test_plan_runner.py
Hello again,
Hopefully this will conclude the journey I have been on this week which has raised and fixed:
https://github.com/bridgecrewio/checkov/pull/760
https://github.com/bridgecrewio/checkov/pull/768
For context I am debugging so that I can include terraform plan-time scanning into a pipeline. I am working on a _big_ complex set of terraform which includes many versioned child modules at one level and makes use of the aws, helm and kubernetes providers.
**Root Cause Description**
In rare circumstances a data resource with partial values in the plan could cause false negatives. 
Often 'data' does not even appear in the *_modules[x].resouces field within planned_values and is not scanned as expected.
It can occur when tf module B depends on tf module A.
And tf module A creates a …
> fix - tfplan - rare - data block with partial values scanned to cause false negatives

- checkov/terraform/checks/data/aws/StarActionPolicyDocument.py
- checkov/terraform/checks/resource/aws/IAMStarActionPolicyDocument.py
- tests/terraform/checks/resource/aws/test_IAMStarActionPolicyDocument.py
IAM Action can be specified as a string and not a list - which means the `in` operator would search for * in a string instead of a list, missing the entire point of the check. Using force_list fixes this
> Fix IAM star action check - handle strings

- Pipfile.lock
- checkov/terraform/module_loading/loaders/local_path_loader.py
- checkov/terraform/module_loading/loaders/registry_loader.py
- checkov/terraform/parser.py
- tests/terraform/module_loading/test_registry.py
I've ran into many failures while trying to load modules with an absolute path. I'm getting this error:
```
Unable to load module (source="/path/to/module" version="latest"): Invalid URL '/path/to/module': No schema supplied. Perhaps you meant http:///path/to/module/versions?
```
This should fix it
@robeden @rotemavni Would love your feedback!
> Handle paths starting with / as local

- Pipfile.lock
bump python-hcl2 to fix https://github.com/bridgecrewio/checkov/issues/781
> bump python-hcl2 

- checkov/main.py
> :tada: Have checkov be callable from Python

- checkov/kubernetes/checks/ImageTagFixed.py
- tests/kubernetes/checks/example_ImageTagFixed/imageWithTagAndDigest-PASSED.yaml
- tests/kubernetes/checks/test_ImageTagFixed.py
Check CKV_K8S_14 (image tag should not be latest or blank) fails when a digest is specified without a tag (which is a valid way to specify it). This PR updates the check to pass if a digest is present.
> Pass image tag check if digest is present

- checkov/cloudformation/checks/resource/aws/CloudtrailMultiRegion.py
- tests/cloudformation/checks/resource/aws/example_CloudtrailMultiRegion/CloudtrailMultiRegion-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_CloudtrailMultiRegion/CloudtrailMultiRegion-PASSED.yaml
- tests/cloudformation/checks/resource/aws/test_CloudtrailMultiRegion.py
Hello,
After some terraform plan related stuff last week I am back  to my quest of slowly aligning Cloudformation with Terraform checks 🙂.
This change adds in the cloudtrail multi region check.
Cloudformation Cloudtrail doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html
Terraform Check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/CloudtrailMultiRegion.py
**License**
> check - cf - cloudtrail multi region to correspond with tf

- checkov/common/output/report.py
- checkov/terraform/runner.py
- tests/terraform/runner/resources/invalid_terraform_syntax/bad_tf_1.tf
- tests/terraform/runner/resources/invalid_terraform_syntax/bad_tf_2.tf
- tests/terraform/runner/test_runner.py
Handles Terraform parsing files when using `-f`. It already worked correctly at the directory level.
Also makes `report.parsing_errors` a map so that it stores the files and the error message.
Finally, adds them to the console output (previously only available with `-o json`). @schosterbarak maybe you intentionally left this out. I think we should show it. But another option would be to add a message like "use -o json to see the parsing errors", like this:
```
terraform scan results:
Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 2 (use -o json to view all parsing errors)
```
> Handle tf file parsing errors

- checkov/terraform/checks/resource/aws/CodeBuildProjectEncryption.py
Hey,
Whilst looking at tf / cf I found that this check had the class named incorrectly.
**License**
> Fix - Minor - Class name for TF CodeBuildProjectEncryption check incorrect

- checkov/terraform/checks/resource/gcp/GoogleComputeProjectOSLogin.py
- tests/terraform/checks/resource/gcp/test_GoogleComputeProjectOSLogin.py
fix CKV_GCP_33 reports a false positive `true` vs `"TRUE"` #790
> fix CKV_GCP_33 reports a false positive `true` vs `"TRUE"` #790

- checkov/terraform/checks/resource/azure/KeyvaultRecoveryEnabled.py
- tests/terraform/checks/resource/azure/test_KeyVaultRecoveryEnabled.py
As per https://docs.microsoft.com/en-us/azure/key-vault/general/soft-delete-change, the attribute will no longer have any effect on new Key Vaults.
Furthermore, soft_delete_enabled now defaults to true as per the provider breaking changes: https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v2.42.0.
> Handle cases when soft_delete_enabled is not set or is false

- checkov/terraform/checks/resource/aws/IAMPolicyAttachedToGroupOrRoles.py
Fix for #802 
`users` is null if there is no user in aws_iam_policy_attachment
```
sample output from terraform json
{
86               "address": "module.aws_cloudtrail.aws_iam_policy_attachment.main",
87               "mode": "managed",
88               "type": "aws_iam_policy_attachment",
89               "name": "main",
90               "provider_name": "registry.terraform.io/hashicorp/aws",
91               "schema_version": 0,
92               "values": {
93                 "groups": null,
94                 "name": "cloudtrail-cloudwatch-logs-policy-attachment",
95                 "roles": [
96                   "cloudtrail-cloudwatch-logs-role"
97                 ], …
```
> null check for IAM users in policy attach

- README.md
Changes some examples to use full param strings (-d -> --directory) for clarity.
Also suggests a workaround to potential issues caused by `docker run -t`.
> Add full param strings to examples

- checkov/terraform/parser.py
- tests/terraform/parser/resources/parser_scenarios/json_807/cdk.tf.json
- tests/terraform/parser/resources/parser_scenarios/json_807/expected.json
- tests/terraform/parser/test_parser_scenarios.py
> Avoid `_clean_bad_definitions` when loading json files

- checkov/common/output/record.py
- checkov/common/output/report.py
- checkov/common/runners/runner_registry.py
- checkov/main.py
- docs/1.Introduction/Getting Started.md
- tests/terraform/runner/test_runner.py
Otherwise, there's just too much stuff with the code blocks
Here's what it looks like:
> Add compact CLI output option

- checkov/common/bridgecrew/integration_features/features/fixes_integration.py
Skips fixes for frameworks where it is not supported.
This also limits errors in large k8s clusters, where each yaml file (deployments, services, etc) is very big.
> only call fixes API for supported frameworks

- checkov/terraform/checks/resource/aws/AppLoadBalancerTLS12.py
- tests/terraform/checks/resource/aws/test_AppLoadBalancerTLS12.py
This check examines an ALB listener, if it's using HTTPS it checks that it is using a policy that mandates the use of TLS 1.2.
Thats means policies starting:
ELBSecurityPolicy-FS-1-2 or ELBSecurityPolicy-TLS-1-2
See the policies here: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html
> Check Listener is using TLS 1.2

- checkov/terraform/parser.py
- checkov/terraform/parser_var_blocks.py
- tests/terraform/parser/resources/parser_scenarios/merge_function_unresolved_var/expected.json
- tests/terraform/parser/resources/parser_scenarios/merge_function_unresolved_var/main.tf
- tests/terraform/parser/resources/parser_scenarios/variable_defaults_separate_files/eval.json
- tests/terraform/parser/resources/parser_scenarios/variable_defaults_separate_files/expected.json
- tests/terraform/parser/resources/parser_scenarios/variable_defaults_separate_files/main.tf
- tests/terraform/parser/resources/parser_scenarios/variable_defaults_separate_files/variables.tf
- tests/terraform/parser/test_hcl2_load_assumptions.py
- tests/terraform/parser/test_parser_internals.py
- tests/terraform/parser/test_parser_scenarios.py
- tests/terraform/parser/test_parser_var_blocks.py
This is a fix for #816 which reworks the main logic which pulls out variables from a value (`find_var_blocks`). The new logic allows nested evaluations, returning the various pieces in order. In a nutshell, this allows outer evals to still occur even if inner ones don't. See the large comment in `process_items_helper` for more info.
In addition, that logic was pulled out of `parser.py`, into `parser_var_blocks.py`... just for organizational purposes.
Fixes: #816
> Allow nested, unresolved variables

- checkov/terraform/checks/resource/base_resource_check.py
- checkov/terraform/checks/resource/base_resource_negative_value_check.py
- checkov/terraform/checks/resource/base_resource_value_check.py
- tests/terraform/checks/resource/aws/test_S3Encryption.py
Checkov will take the dynamic content and inject that into the resource configuration
> add basic handling in dynamic values for terraform resources

- .github/exclude-patterns.txt
- checkov/cloudformation/checks/resource/aws/EC2Credentials.py
- checkov/terraform/checks/resource/aws/EC2Credentials.py
- tests/cloudformation/checks/resource/aws/example_EC2Credentials/EC2Credentials-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_EC2Credentials/EC2Credentials-PASSED.yaml
- tests/cloudformation/checks/resource/aws/test_EC2Credentials.py
Hello 🙂 
Implementing this check as already done for terraform.
I have used the same key test data as is already in-use in the terraform check to verify the same outcome.
Also changed minor typo so that text is the same for both terraform and clloudformation checks.
Terraform Check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/EC2Credentials.py
CloudFormation Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
Examples of CF UserData (to verify formatting): https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-ec2.html
https://gist.github.com/jeffbrl/abfd84d8d8586495632ba9b8489322e2
https://stackoverflow.com/questions/48197526/using-userdata-in-cloudformation
**License**
By …
> CF - Check - CKV_AWS_46 - EC2Credentials

- checkov/cloudformation/checks/resource/aws/EC2PublicIP.py
- tests/cloudformation/checks/resource/aws/example_EC2PublicIP/EC2PublicIP-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_EC2PublicIP/EC2PublicIP-PASSED.yaml
- tests/cloudformation/checks/resource/aws/example_EC2PublicIP/EC2PublicIP-UNKNOWN.yaml
- tests/cloudformation/checks/resource/aws/test_EC2PublicIP.py
Hello,
Implementing check for EC2 Public IP in CloudFormation as done in Terraform.
Terraform Check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/EC2PublicIP.py
CloudFormation Docs: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-network-iface-embedded.html#aws-properties-ec2-network-iface-embedded-associatepubip
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-networkinterface.html
Note (for if you take a closer look at the test data):
It is odd how they have chose to …
> CF - Check - CKV_AWS_88

- checkov/serverless/runner.py
- tests/serverless/runner/resources/serverless.yml
* Added to the serverless runner a check to validate that the resource_id is not None. 
If it is None there is no need to scan it.
* Added a malformed resource to the `serverless.yml` in the tests resources to make sure there is no exception thrown when it exists in the file and the tests still pass.
> Avoid parsing serverless resources that don't have 'Type'

- checkov/terraform/parser.py
- tests/terraform/parser/test_parser_scenarios.py
We don't support .tf.json yet, as it has a different structure than the output of hcl2 lib. Removing it from scanned file extensions until we add support for it
> Skip .tf.json files until they are truly supported

- checkov/cloudformation/checks/resource/aws/EKSNodeGroupRemoteAccess.py
- tests/cloudformation/checks/resource/aws/example_EKSNodeGroupRemoteAccess/EKSNodeGroupRemoteAccess-FAILED.yml
- tests/cloudformation/checks/resource/aws/example_EKSNodeGroupRemoteAccess/EKSNodeGroupRemoteAccess-PASSED.yml
- tests/cloudformation/checks/resource/aws/test_EKSNodeGroupRemoteAccess.py
Hello 🙂 
Check for CF as already done for Terraform.
TF Check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/EKSNodeGroupRemoteAccess.py
CF Docs:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-nodegroup.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-nodegroup-remoteaccess.html
**License**
> CF - Check -  ckv_aws_100 as done in TF

- checkov/common/bridgecrew/platform_integration.py
Avoid using '.' as basename for repo_id, to prevent bad paths resolution.
> Rename repo_id in platform_integration

- .github/workflows/build.yml
- .github/workflows/pr-test.yml
- checkov/common/output/report.py
- checkov/common/runners/runner_registry.py
- integration_tests/test_checkov_json_report.py
Functioning `--quiet` option for `-o json`requested in #704. Fixes #704 
Looking at #774 for callable unit test and passing in cli params for tests.
> Functioning --quiet for -o json.

- checkov/terraform/checks/resource/aws/AppLoadBalancerTLS12.py
- tests/terraform/checks/resource/aws/test_AppLoadBalancerTLS12.py
With PR #838 `checkov` is now raising a false positive for the `CKV_AWS_103` check, because also NLBs can have a TLS certificate and apply a security policy.
```
Check: CKV_AWS_103: "Ensure that load balancer is using TLS 1.2"
FAILED for resource: aws_lb_listener.https
File: /../../modules/example/network.tf:54-65
54 | resource "aws_lb_listener" "https" {
55 |   load_balancer_arn = aws_lb.this.arn
56 |   protocol          = "TLS"
57 |   port              = "443"
58 |   ssl_policy        = "ELBSecurityPolicy-FS-1-2-Res-2019-08"
59 |   certificate_arn   = module.certificate.arn
60 | 
61 |   default_action {
62 |     type             = "forward"
63 |     target_group_arn = …
```
> Fix NLB TLS 1.2 issue

- checkov/terraform/parser.py
- tests/terraform/parser/resources/parser_scenarios/tfvars/expected.json
- tests/terraform/parser/resources/parser_scenarios/tfvars/main.tf
- tests/terraform/parser/resources/parser_scenarios/tfvars/terraform.tfvars
This avoids a problem where map data in `.tfvars` files is improperly removed. Note, there are still some resolution issues with tfvars files which will be addressed in subsequent work... but this avoids explosions.
Fixes: #868
> Avoid attempting to clean data from tfvars

- checkov/terraform/checks/resource/azure/SQLServerAuditPolicyRetentionPeriod.py
- tests/terraform/checks/resource/azure/test_SQLServerAuditPolicyRetentionPeriod.py
The location of the audit policy for sql server is now a separate resource- there's an Azure policy that checks that the retention policy is 90 days or more, this is that check for the new resource.
> Ensure retention is 90 days or greater

- checkov/terraform/checks/resource/gcp/CloudStorageLogging.py
- tests/terraform/checks/resource/gcp/test_CloudStorageLogging.py
Ensure that Accesslogging is enabled for cloud storage buckets. There are similar tests for s3, this implements same for gcp.
> Check for logging on google cloud storage

- checkov/terraform/checks/resource/gcp/CloudStorageSelfLogging.py
- tests/terraform/checks/resource/gcp/test_CloudStorageSelfLogging.py
If you set up logging for your bucket GREAT! But set up logging and then set it itself, FAIL.
Thats what this check does is make sure you dont fudge a logging requirement by logging to self.
> GCP Cloud Storage: A bucket shouldn't log to itself

- checkov/terraform/checks/resource/azure/MariaDBSSLEnforcementEnabled.py
- tests/terraform/checks/resource/azure/test_MariaDBSSLEnforcementEnabled.py
To ensure you create you Mariadb Server SSL enabled.
Partially addresses https://github.com/bridgecrewio/checkov/issues/432
> Adding check for TF for ssl on maria server creation

- checkov/cloudformation/checks/resource/aws/ELBAccessLogs.py
- tests/cloudformation/checks/resource/aws/example_ELBAccessLogs/ELBAccessLogs-FAILED.yml
- tests/cloudformation/checks/resource/aws/example_ELBAccessLogs/ELBAccessLogs-PASSED.yml
- tests/cloudformation/checks/resource/aws/test_ELBAccessLogs.py
Hello,
Congrats all on the recent news! :)
Implementing this check as already done in TF. Able to use ValueCheck in this case because in CF world when AccessLoggingPolicy exists then Enabled is a required field and does not have a default value. So it must always be true or false.
TF Check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/ELBAccessLogs.py
CF Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb-accessloggingpolicy.html
**License**
> CF - Check - ELBAccessLogs

- checkov/terraform/checks/resource/aws/IAMAdminPolicyDocument.py
- tests/terraform/checks/resource/aws/example_IAMAdminPolicyDocument/iam.tf
- tests/terraform/checks/resource/aws/test_IAMAdminPolicyDocument.py
Previously, this check failed when action and resource were a string containing *. For example, the following statement failed:
```
{
"Action": "s3:PutObject*",
"Effect": "Allow",
"Resource": "arn:aws:s3:::b1/*",
"Sid": ""
}
```
This PR updates the logic to only fail when a statement contains both an action and a resource that equal `*`.
> fix AWS_62 to check only for actual action/resource=*

- checkov/terraform/checks/resource/azure/AzureScaleSetPassword.py
- tests/terraform/checks/resource/azure/test_AzureScaleSetPassword.py
This test ensures that you opt for not using password auth on your scalesets. That is all.
addressed https://github.com/bridgecrewio/checkov/issues/428
> linuxscaleset should not set passwords

- checkov/terraform/checks/resource/azure/MariaDBPublicAccessDisabled.py
- tests/terraform/checks/resource/azure/test_MariaDBPublicAccessDisabled.py
Default behaviour is for mariadbs to be public. This is a rule to stop that and make it private
> Maria DB server - Make sure public access is disabled

- Pipfile.lock
- checkov/terraform/parser.py
- tests/terraform/parser/resources/malformed_outputs/main.tf
- tests/terraform/parser/resources/parser_scenarios/ternaries/expected.json
- tests/terraform/parser/resources/parser_scenarios/ternaries/main.tf
- tests/terraform/parser/test_parser_modules.py
Handle malformed blocks (e.g. without a valid unicode identifier) gracefully, by excluding them from the parser output
> Malformed blocks handling

- Pipfile.lock
- tests/terraform/parser/resources/parser_scenarios/ternaries/expected.json
- tests/terraform/parser/resources/parser_scenarios/ternaries/main.tf
> update python-hcl2 to handle ternaries new line

- checkov/terraform/checks/resource/aws/EKSNodeGroupRemoteAccess.py
- tests/terraform/checks/resource/aws/test_EKSNodeGroupRemoteAccess.py
Hello,
Raising this to fix an edge case issue that I am seeing.
When the `aws_eks_node_group`  `remote_access` block is omitted then the check should pass.
All of the tests check the cases you would expect and it is all fine. However, when you omit this and run a terraform plan then the json ends up outputting the resource as `"remote_access": []". This ultimately causes the check to error out and crash.
Because it is an empty list, the `conf["remote_access"][0].keys()` throws an error because there is no list item which is a dict and so there you can not call `.keys()`.
It is not caught in tests because it is an issue in how terraform is setting an odd (and not possible to predict?) default when it goes from HCL to the json representation. It should be not there or even perhaps [{ }] …
> Check - Bug - EKSNode - TFPlan

- .github/workflows/pr-test.yml
- checkov/common/output/record.py
- checkov/common/runners/runner_registry.py
- checkov/common/util/runner_dependency_handler.py
- checkov/helm/base_registry.py
- checkov/helm/registry.py
- checkov/helm/runner.py
- checkov/kubernetes/runner.py
- checkov/main.py
- checkov/runner_filter.py
- integration_tests/test_checkov_json_report.py
**HELMv3 (Kubernetes templating) support for Checkov.**
HELM is written in go, however has a simple `helm template` function to produce a non-k8s (local only) rendering of the templates into kubernetes manifests which we can pass to the existing k8s runner.
- Also passing the chart name, to the runner as a new arg, which defaults to none. 
- When writing out the report items, the k8s_runner also now adds the chart to the `Record` object if the k8s_runner was called with a chart name. (Discussion point: There are no other runner specific fields in the `Record` object, but ideally want to surface this information for future use with the output).
On top of this, as the helm binary has no python-friendly bindings, so we're using  p.subprocess to exec out, which leads to external dependancies. …
> Helm v3 support and deps checking for external binaries.

- checkov/terraform/checks/resource/aws/EKSNodeGroupRemoteAccess.py
- tests/terraform/runner/resources/unexpected/eks_node_group_remote_access.json
- tests/terraform/runner/resources/unexpected/unexpected.md
- tests/terraform/runner/test_plan_runner.py
Hello,
I've explained the issue I was facing yesterday with https://github.com/bridgecrewio/checkov/pull/910
Checking that the (assumed) list had no items for some reason did not fix the problem.
This is the same issue as https://github.com/bridgecrewio/checkov/issues/876
This method does fix the issue (tested with local build):
**Before**
```
File "/usr/local/lib/python3.8/site-packages/checkov/terraform/checks/resource/aws/EKSNodeGroupRemoteAccess.py", line 17, in scan_resource_conf
if "ec2_ssh_key" in conf["remote_access"][0].keys() and not 'source_security_group_ids' in conf["remote_access"][0].keys():
File "/usr/local/lib/python3.8/site-packages/checkov/terraform/context_parsers/tf_plan/node.py", line 202, in __getattr__
raise TemplateAttributeError('%s.%s is invalid' % …
```
> TF - EKSNode Check - Attempt 2

- checkov/terraform/checks/resource/azure/MySQLPublicAccessDisabled.py
- tests/terraform/checks/resource/azure/test_MySQLPublicAccessDisabled.py
By default the dbs are created public. Not a great option. This checks and errors if its is.
> MySQLPublicAccessDisabled - dont default to public

- checkov/terraform/checks/resource/aws/DocDBAuditLogs.py
- tests/terraform/checks/resource/aws/test_DocDBAuditLogs.py
> A check for auditlogs being enabled on docdb via parameter groups

- checkov/common/output/record.py
- checkov/terraform/runner.py
- tests/terraform/runner/resources/module_failure_reporting_772/main.tf
- tests/terraform/runner/resources/module_failure_reporting_772/module/module.tf
- tests/terraform/runner/test_runner.py
This records the full path for resources loaded from modules. For example, `module.test_module.aws_s3_bucket.inside` rather than simply `aws_s3_bucket.inside` to indicate that the bucket (named `inside`) was loaded from the module `test_module`. In addition the "Caller File" has been added to record output for both json and textual output.
Sample output can be seen [here](https://github.com/bridgecrewio/checkov/issues/772#issuecomment-785427909)
Fixes: #772
> Provide more detail for context of resource loaded from modules

- checkov/common/util/banner.py
Some windows users report repeatable crashes due to an unknown char for the arrow we were using in the "update available" output, debugging was done to work out if this was a version specific or colorama specific thing, however no specific commit/history item was found. 
Best thing for stability for these users is to remove the offending char.
> remove funky char in update string causing crashes in windows installs.

- checkov/terraform/checks/resource/gcp/CloudStorageLogging.py
- checkov/terraform/checks/resource/gcp/CloudStorageSelfLogging.py
when logging on a GCP bucket is disabled there is no logging key in the TF hcl
> fixes #899

- checkov/cloudformation/checks/resource/aws/ElasticsearchDomainEnforceHTTPS.py
- tests/cloudformation/checks/resource/aws/example_ElasticsearchDomainEnforceHTTPS/ElasticsearchDomainEnforceHTTPS-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_ElasticsearchDomainEnforceHTTPS/ElasticsearchDomainEnforceHTTPS-PASSED.yaml
- tests/cloudformation/checks/resource/aws/test_ElasticsearchDomainEnforceHTTPS.py
Hello,
Implementing this check as already done in Terraform.
Terraform check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/ElasticsearchDomainEnforceHTTPS.py
CF Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-domainendpointoptions.html
**License**
> CF - Check - ES Domain HTTPS

- checkov/terraform/parser.py
- checkov/terraform/parser_utils.py
- integration_tests/test_checkov_json_report.py
- tests/terraform/parser/resources/parser_scenarios/module_output_reference/bucket/bucket.tf
- tests/terraform/parser/resources/parser_scenarios/module_output_reference/common/common.tf
- tests/terraform/parser/resources/parser_scenarios/module_output_reference/expected.json
- tests/terraform/parser/resources/parser_scenarios/module_output_reference/main.tf
- tests/terraform/parser/test_parser_scenarios.py
- tests/terraform/parser/test_parser_var_blocks.py
This fixes a resolution problem where module data dependencies didn't previously work. For example (from the new `module_output_reference` parser scenario):
```
module "common" {
source = "./common"
}
module "bucket" {
source = "./bucket"
tags = module.common.tags
}
```
Previously, both modules would attempt to load in the same pass, before variable resolution, which means that the reference to "module.common.tags" would slip into the data for the "bucket" module. This would not be resolvable, so the broken reference would be all it would ever see.
This change recognizes that the data is unresolved and so delays loading of the "bucket" module. So now, "common" is loaded, then variables are resolved, then in the next pass "bucket" is loaded... this time with resolved tag data.
By …
> Better handling of module data dependencies

- checkov/terraform/plan_runner.py
Hello,
We had some issues running Checkov on a Terraform plan which did not have a `.json` file extension, the additional debug logging would have helped us diagnose the issue. 
Many Thanks,
Tyler Allen.
> Adding additional debug logging to TF Plan Runner

- checkov/terraform/plan_runner.py
Hello,
I noticed today during some testing that the previous PR throws an error as {root} does not exist on file runners, sorry about that. 
Many Thanks,
Tyler Allen.
> Fixing debug logging to TF Plan Runner

- checkov/cloudformation/checks/resource/aws/ElasticsearchDomainLogging.py
- tests/cloudformation/checks/resource/aws/example_ElasticsearchDomainLogging/ElasticsearchDomainLogging-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_ElasticsearchDomainLogging/ElasticsearchDomainLogging-PASSED.yaml
- tests/cloudformation/checks/resource/aws/test_ElasticsearchDomainLogging.py
Hello,
Implementing this check as already done for tf.
TF Check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/ElasticsearchDomainLogging.py
CF Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-logpublishingoption.html
**License**
> CF - Check - ES Logging

- checkov/terraform/checks/resource/aws/EBSDefaultEncryption.py
- tests/terraform/checks/resource/aws/example_EBSDefaultEncryption/main.tf
- tests/terraform/checks/resource/aws/test_EBSDefaultEncryption.py
Implements 2.2.1 of the issue #853.
Pretty easy check, it just checks, if the resource is used and not set to `false`.
> Add CKV_AWS_106 check for aws_ebs_encryption_by_default

- checkov/common/goget/github/get_git.py
fix for #994 
debug outputs 
I added following prints to see parse result in my local env.
URL tag:
Tag is here
```
checkov  -d .  --download-external-modules true
URL tag: <re.Match object; span=(54, 70), match='?ref=tags/0.19.2'>
Tag is here 0.19.2
Cloning branch: 0.19.2 Clone dir: /Users/ismail/dev/terraform-aws-vpc-flow-logs-s3-bucket/.external_modules/git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2
URL tag: <re.Match object; span=(54, 69), match='?ref=tag/0.19.2'>
Tag is here 0.19.2
Cloning branch: 0.19.2 Clone dir: /Users/ismail/dev/terraform-aws-vpc-flow-logs-s3-bucket/.external_modules/git::https://github.com/cloudposse/terraform-null-label. …
```
> update git URL regex to match tag/tags

- checkov/kubernetes/checks/Seccomp.py
- tests/kubernetes/checks/example_Seccomp/cronjob-seccomp-PASSED.yaml
- tests/kubernetes/checks/test_Seccomp.py
In [get_skipped_checks](https://github.com/bridgecrewio/checkov/blob/f2268666d1b45655d98514d5bd7663e5238b3a65/checkov/kubernetes/runner.py#L232), the root-level `metadata["annotations"]` is transformed into a list.  This is later assumed to be a list in the Seccomp check.  However, annotations that appear at other levels of the tree may not be a list.
This ensures that `metadata["annotations"]`, wherever it might be, is a list.
> Update Seccomp check to work on non-list annotations

- checkov/terraform/checks/resource/aws/SSMSessionManagerDocumentEncryption.py
- tests/terraform/checks/resource/aws/example_SSMSessionManagerDocumentEncryption/main.tf
- tests/terraform/checks/resource/aws/test_SSMSessionManagerDocument.py
Adds the encryption in transit part of issue #192. I think it is better to have to different checks, this one and an other for checking if logging is enabled and encrypted, or should it be then 3 checks?
> Add CKV_AWS_112 check for aws_ssm_document session type

- checkov/terraform/checks/resource/aws/AbsSecurityGroupUnrestrictedIngress.py
added validation in check `AbsSecurityGroupUnrestrictedIngress` to make sure there is no illegal access to `ipv6_cidr_blocks`[0] when it is empty.
> Fix illegal index access in check AbsSecurityGroupUnrestrictedIngress

- checkov/logging_init.py
- checkov/terraform/plan_runner.py
- checkov/terraform/runner.py
The root logger always defaults to WARNING level. 
setting export LOG_LEVEL=debug was not displaying any debug message. Added 
Set the LOG_LEVEL with logging.getLogger().setLevel(LOG_LEVEL)
to make it work.
> Fix logging 

- checkov/terraform/checks/resource/azure/StorageAccountName.py
re.match returns an object or None so we have to check if the object is not None
> The check for Storage Account naming rules produced a false positive

- Dockerfile
If the image is based on Alpine instead of ubuntu the image size drops from 325 to 182 MB. Faster downloads and response for the vscode integration.
> Reduce the Docker image size

- .github/workflows/build.yml
- .github/workflows/pr-test.yml
Adding matrix testing for python versions as discussed in #745.
Should successful tests will allow us to move Pipfile from:
```
[requires]
python_version = "3.7"
```
to
```
[requires]
python_version => "3.7"
Giving more flexibility.
```
> Matrix tests for python 3.7, 3.8, 3.9, artifacts left on 3.7 for now

- checkov/terraform/checks/data/aws/IAMCredentialsExposure.py
- tests/terraform/checks/data/aws/test_CloudSplainingCredentialsExposure.py
There's not really a good way to constrain the AWS `ecr:GetAuthorizationToken` action by resource. The API just returns a token for use with e.g., Docker but the only argument it takes (and could use for constraint context) is deprecated (https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_GetAuthorizationToken.html#API_GetAuthorizationToken_RequestSyntax) and not usually passed by recent clients. The repo constraints are applied over other actions made via subsequent requests using the token.
This patch allows IAM policy statements like the following to pass without throwing `CKV_AWS_107` (credential exposure):
```
statement {
actions = [ …
```
> Allows resource=* for ecr:GetAuthorizationToken

- checkov/cloudformation/checks/resource/BaseCloudsplainingIAMCheck.py
- tests/cloudformation/checks/resource/aws/cloudsplaining/IAMPolicyAttachedToGroupOrRoles-FAILED.yml
- tests/cloudformation/checks/resource/aws/cloudsplaining/IAMPolicyAttachedToGroupOrRoles-PASSED.yml
- tests/cloudformation/checks/resource/aws/test_IAMPermissionsManagement.py
Hello,
Whilst going through my CloudFormation coverage checks I see we have implemented Cloudsplaining which looks like it can play a larger role for IAM checks in CF and TF and across all ways of embedding policies. I think this is great work to get the integration working!
This is just addressing the TODO to extend to ManagedIAMPolicies and is an initial start in the area of extending this wider.
**License**
> CF - Extend Cloudsplaining to ManagedIAMPolicy

- Dockerfile
In #1022 the image size went from 325MB to 182MB by switching from Debian to Alpine. 
I was able to reduce this even further to 165MB by disabling the caches of the APK and Pip installs. 
17MB is not as big of a reduction as the 143MB from #1022, but still it should make the download/usage a little faster. 😄
> Further reduce Docker image size

- checkov/cloudformation/checks/resource/aws/EKSSecretsEncryption.py
- checkov/kubernetes/base_spec_check.py
- checkov/kubernetes/checks/DockerSocketVolume.py
- checkov/kubernetes/checks/PodSecurityContext.py
- checkov/kubernetes/checks/RootContainers.py
- checkov/kubernetes/checks/RootContainersHighUID.py
- checkov/kubernetes/checks/Seccomp.py
- checkov/kubernetes/checks/ServiceAccountTokens.py
- checkov/kubernetes/checks/ShareHostIPC.py
- checkov/kubernetes/checks/ShareHostPID.py
- checkov/kubernetes/checks/SharedHostNetworkNamespace.py
- checkov/kubernetes/checks/WildcardRoles.py
- checkov/kubernetes/runner.py
- checkov/serverless/runner.py
- tests/cloudformation/checks/resource/aws/example_EKSSecretEncryption/EKSSecretEncryption-FAILED.yml
- tests/cloudformation/checks/resource/aws/example_EKSSecretEncryption/EKSSecretEncryption-PASSED.yml
- tests/cloudformation/checks/resource/aws/test_EKSSecretEncryption.py
- tests/graph/terraform/graph_builder/graph_components/test_blocks.py
- tests/kubernetes/checks/example_WildcardRoles/role-passed-2.yaml
- tests/kubernetes/checks/test_WildcardRoles.py
1. Fixed cloudformation `CKV_AWS_58` - there access to conf was list-like rather than dict-like. Added UT as well.
2. Handled multiple cases in K8 where specs elements existed as `None` which caused errors while trying to access nested elements. Handled it by implementing `get_inner_spec` method in `base_spec_check`.
3. Fixed serveless runner accessing `cf_sub_template['Resources'].items()` when `cf_sub_template['Resources']` doesn't exists.
> Various checks fixes

- checkov/terraform/graph_builder/graph_components/blocks.py
- tests/graph/terraform/graph_builder/graph_components/test_blocks.py
When `nested_attributes` are a list, check that the current key is within the size of the list before accessing that index.
> Fix update_inner_attribute index error

- checkov/kubernetes/checks/DockerSocketVolume.py
Used `v.get("hostPath")` to validate `hostPath` exists and that it is not None.
> DockerSocketVolume check if "hostPath" in volumes is not None

- checkov/cloudformation/checks/resource/aws/LambdaEnvironmentCredentials.py
- checkov/terraform/checks/resource/aws/LambdaEnvironmentCredentials.py
The following regex  hits aws kms key id and creates FP for AWS resources.
_secrets_regexes = {
'azure': [
"(\"|')?([0-9A-Fa-f]{4}-){4}[0-9A-Fa-f]{12}(\"|')?",  # client_secret
"(\"|')?[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}(\"|')?", # client_id and many other forms of IDs
environment": [
{
"variables": {
"kms_key_id": "arn:aws:kms:eu-west-1:123456789:key/c0baad75-d0d3-24e3-95d1-1e4e38a44c4a"
> check  AWS secrets in Lambda env variable only for AWS and GENERAL regex

- checkov/dockerfile/checks/MaintainerExists.py
- tests/dockerfile/checks/test_MaintainerExists.py
Happy to see Docker support by checkov. Also happy to help here with some best or worst practice 😄 
I'm still seeing from time to time the usage of the infamous `MAINTAINER` instruction. I hope someday it will be removed completely.
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
> Add CKV_DOCKER_6 check for existence of MAINTAINER

- checkov/dockerfile/checks/RootUser.py
- tests/dockerfile/checks/test_RootUser.py
Quite often you need to use the `USER root` instruction to install packages or change permissions. Therefore the last `USER` instruction should not be root to make the container start with a non root user by default.
> Add CKV_DOCKER_8 check for last USER being root

- checkov/dockerfile/checks/MaintainerExists.py
- checkov/dockerfile/checks/RootUser.py
- tests/dockerfile/checks/example_MaintainerExists/failure/Dockerfile
- tests/dockerfile/checks/example_RootUser/failure/Dockerfile
- tests/dockerfile/checks/example_RootUser/success/Dockerfile
- tests/dockerfile/checks/test_MaintainerExists.py
- tests/dockerfile/checks/test_RootUser.py
Fixes #1101.
After realizing how the checks were tested I changed my to use the same way as the terraform checks to really let the parse through the runner.
The Maintainer check looks quite silly, this is because of the runner functionality. When `supported_instructions` is set to something other than `*`, he will just send the chosen instruction to the `scan_entity_conf()` method. Therefore there is no need to check anything and I can directly return the `FAILED` status 😄
> Fix Docker checks CKV_DOCKER_6,CKV_DOCKER_8

- checkov/common/bridgecrew/integration_features/base_integration_feature.py
- checkov/common/bridgecrew/platform_integration.py
- checkov/main.py
- checkov/terraform/context_parsers/base_parser.py
- docs/2.Basics/CLI Command Reference.md
- tests/common/test_platform_integration.py
Software (like GlobalProtect) generates 'ignore self signed certificate in certificate chain' errors when executing bridgecrew; and/or bridgecrew might be installed into a Python without any CA certificates.
This commit allows users to specify a CA bundle (including the 'Palo Alto Networks Inc Root CA' used by GlobalProtect, for example) via a --ca-certificate argument or a BC_CA_BUNDLE environment variable.
Hint: To generate a CA bundle, copy the CA bundle provided by the certifi module (locate via 'python -m certifi') and, if applicable, append other CA certificates (including the 'Palo Alto Networks Inc Root CA' used by GlobalProtect, for example).
This commit also replaces the global http variable with a self.http instance variable (representing a urllib3.ProxyManager or …
> allow the user to specify a CA bundle when running bridgecrew

- checkov/dockerfile/checks/ReferenceLatestTag.py
- tests/dockerfile/checks/test_ReferenceLatestTag.py
It is always recommended to use a non latest version tag for your base image or multi stage builds, because of typical nature of the latest tag being used for the most up-to-date version, which can result in a major version upgrade.
Using a versioned tag makes also the build more reliable and consistent.
> Add CKV_DOCKER_7 check for latest version tag reference

- checkov/terraform/checks/resource/aws/ALBDropHttpHeaders.py
- tests/terraform/checks/resource/aws/example_ALBDropHttpHeaders/main.tf
- tests/terraform/checks/resource/aws/test_ALBDropHttpHeaders.py
The check sadly had missing square brackets, that's why it reported incorrectly for network load balancers. The tests were also incorrect so I fixed and changed them to use the runner instead.
> Fix CKV_AWS_131 check for network load balancers

- checkov/common/bridgecrew/platform_integration.py
Replace all backslash created by os.path.join on windows with forward slash.
> Set correct file path for BC cli s3 file upload

- checkov/terraform/checks/resource/aws/AutoScalingTagging.py
- tests/terraform/checks/resource/aws/example_AutoScalingTagging/main.tf
- tests/terraform/checks/resource/aws/test_AutoScalingTagging.py
Tag are used differently in this resource and should pass attribute to launch configs for tagging
> add new tag check for autoscaling groups only

- checkov/common/output/graph_record.py
- checkov/common/output/record.py
`GraphRecord` objects invoke the super `Record` constructor by unpacking `Record`'s properties and passing them as params. The `Record` constructor calculates a file's path relative to the root / working directory, which allows it to match up files with the platform for calculating suppressions. To do this, it uses the absolute path that gets passed into the constructor and stores the result in `repo_file_path`.
However, it does not store the absolute path. This means that for `GraphRecord` objects, there is no known absolute path available. So it passes in `repo_file_path`. This results in calculating a relative path to `repo_file_path` (e.g., `/file.tf` ) from the file being sanned (`<working dir>/file.tf`), which results in a path that looks like `'/../../../../../../storage.tf'`. But …
> Fix file paths for calculating fixes when there are graph records

- checkov/terraform/checks/resource/aws/DynamodbRecovery.py
Terraformer exports Dynamo point_in_time_recovery.enabled as a string, `'true'`, and not a boolean. This breaks the check.
We need to update Terraformer for this, but this is the fastest workaround. The check is valid, because Terraformer allows this value to be a string.
> allow boolean or string for Dynamo point in time recovery

- checkov/terraform/checks/resource/aws/ALBDropHttpHeaders.py
- checkov/terraform/checks/resource/aws/ELBv2AccessLogs.py
- tests/terraform/checks/resource/aws/example_ALBDropHttpHeaders/main.tf
- tests/terraform/checks/resource/aws/example_ELBv2AccessLogs/main.tf
- tests/terraform/checks/resource/aws/test_ELBv2AccessLogs.py
AWS Gateway Load Balancers are very similar to NLBs that's why there are no HTTP headers to drop and they don't support logging at all.
https://docs.aws.amazon.com/elasticloadbalancing/latest/gateway/monitoring.html
_However, the Gateway Load Balancer does not generate access logs since it is a transparent layer 3 load balancer that does not terminate flows._
> Fix lb checks for gateway lb

- checkov/terraform/checks/resource/aws/KubernetesSecretsEncryptedUsingCMK.py
- checkov/terraform/checks/resource/aws/LBDeletionProtection.py
- checkov/terraform/checks/resource/aws/SecretManagerSecretEncrypted.py
- checkov/terraform/checks/resource/azure/NSGRulePortAccessRestricted.py
- checkov/terraform/checks/resource/azure/SQLServerNoPublicAccess.py
- checkov/terraform/checks/resource/gcp/GoogleComputeDefaultServiceAccount.py
- checkov/terraform/checks/resource/gcp/GoogleComputeDefaultServiceAccountFullAccess.py
- checkov/terraform/checks/resource/gcp/GoogleProjectAdminServiceAccount.py
- tests/arm/runner/test_runner.py
- tests/cloudformation/runner/test_runner.py
- tests/dockerfile/test_runner.py
- tests/kubernetes/runner/test_runner.py
- tests/serverless/runner/test_runner.py
- tests/terraform/checks/resource/aws/example_KubernetesSecretsEncryptedUsingCMK/main.tf
- tests/terraform/checks/resource/aws/example_LBDeletionProtection/main.tf
- tests/terraform/checks/resource/aws/example_SecretManagerSecretEncrypted/main.tf
- tests/terraform/checks/resource/aws/test_KubernetesSecretsEncryptedUsingCMK.py
- tests/terraform/checks/resource/aws/test_LBDeletionProtection.py
- tests/terraform/checks/resource/aws/test_SecretManagerSecretEncrypted.py
- tests/terraform/runner/test_plan_runner.py
- tests/terraform/runner/test_runner.py
During work on a new check I realized there was a gab between the last check number and the previous one, which actually surprised me, because there is a test which tries to prevent it. After further investigation, I found the culprit and I even discovered that one of the checks imported the wrong parent check class. Therefore I added a test, which checks, to prevent future mistakes. And the test even found two other miss configured checks 💪 
I also adjusted the check `KubernetesSecretsEncryptedUsingCMK` to return an `UNKNOWN` result, if the encryption config is pointing to an other resource, which at the moment is not possible, because the only possible value is `secrets`.
> Fix wrong check imports and add test to prevent future mistakes

- checkov/kubernetes/checks/KubeControllerManagerBlockProfiles.py
- checkov/kubernetes/checks/KubeControllerManagerTerminatedPods.py
Currently checkov will fail if `command` is on your pod, even if it is not set to `kube-controller-manager`.  This PR will tell these checks to not fail unless the command contains `kube-controller-manager`.
> Don't fail if command is set

- checkov/arm/checks/resource/NSGRulePortAccessRestricted.py
- checkov/common/bridgecrew/platform_integration.py
- checkov/common/output/report.py
- checkov/serverless/base_registry.py
- checkov/serverless/parsers/parser.py
- checkov/terraform/checks/resource/gcp/AbsGoogleIAMMemberDefaultServiceAccount.py
- checkov/terraform/variable_rendering/evaluate_terraform.py
- checkov/terraform/variable_rendering/safe_eval_functions.py
- tests/common/checks/test_base_check.py
- tests/common/checks/test_base_check_registry.py
- tests/common/test_platform_integration.py
- tests/graph/terraform/variable_rendering/test_string_evaluation.py
- tests/terraform/checks/resource/test_base_resource_value_check.py
I added the possibility to parse `jsonencode` functions, which will be helpful to create checks, when users use this function instead of text blocks.
I also fixed couple of deprecation warnings, one is still popping up, but I can't figure out where it comes from 😞
> Add jsonencode parsing

- checkov/terraform/checks/resource/aws/AbsSecurityGroupUnrestrictedIngress.py
We saw the following error when executing Checkov on https://github.com/terraform-aws-modules/terraform-aws-eks
```
ERROR:checkov.terraform.checks.resource.aws.SecurityGroupUnrestrictedIngress3389:Failed to run check: Ensure no security groups allow ingress from 0.0.0.0:0 to port 3389 for configuration: {'cidr_blocks': [None], 'description': ['Allow workers pods to receive communication from the cluster control plane.'], 'from_port': [1025], 'ipv6_cidr_blocks': [None], 'prefix_list_ids': [None], 'protocol': ['tcp'], 'self': [False], 'to_port': [65535], 'type': ['ingress'], 'start_line': [853], 'end_line': [863]} at file: /tf/tfplan.json
2021-04-26 09:33:04,809 [MainThread  ] [ERROR]  Failed to run check: Ensure no security groups allow ingress from 0.0.0.0:0 to port 3389 for …
```
> Fix `NoneType` error for empty ipv6_cidr_blocks

- checkov/terraform/checks/resource/base_resource_check.py
- checkov/terraform/variable_rendering/evaluate_terraform.py
- tests/graph/terraform/runner/test_graph_builder.py
- tests/terraform/checks/example_WildcardEntities/main.tf
- tests/terraform/checks/resource/test_base_resource_check.py
Fixes #1078.
It was a pretty interesting issue. The first problem was that the `input_str` in `evaluate_conditional_expression` was surrounded with `${}`. After fixing that, I realized that `checkov` doesn't care, when a resource is actually not deployed `count = 0`, which is in general ok, but result in a lot of false positive, when third party modules are used.
I also added type hints for code parts I touched, will do so for other parts, when I have to fix something :)
> Ignore resources with a count of zero

- checkov/terraform/checks/resource/aws/LBCrossZone.py
- tests/terraform/checks/resource/aws/example_LBCrossZone/main.tf
- tests/terraform/checks/resource/aws/test_LBCrossZone.py
- tests/terraform/runner/test_runner.py
Cross-zone load balancing is disabled by default for Network and Gateway load balancers. For Application LB is enabled by default and can't be changed.
> Add CKV_AWS_152 check for cross-zone load balancing

- checkov/kubernetes/checks/PeerClientCertAuthTrue.py
Issue: Scan fails with exception on check `CKV_K8S_121`
Version: 2.0.88
Reproduce: scanned this file
```yml
apiVersion: v1
kind: Pod
metadata:
annotations:
scheduler.alpha.kubernetes.io/critical-pod: ""
creationTimestamp: null
labels:
component: etcd
tier: control-plane
name: etcd
namespace: kube-system
spec:
containers:
- command:
- etcd
image: k8s.gcr.io/etcd-amd64:3.2.18
imagePullPolicy: IfNotPresent
livenessProbe:
exec:
command:
- /bin/sh
- -ec
- ETCDCTL_API=3 etcdctl --endpoints=https://[192.168.22.9]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt
--cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key
get foo
failureThreshold: 8
initialDelaySeconds: 15
timeoutSeconds: 15
name: etcd-should-fail
resources: {}
volumeMounts:
- …
```
> fix(CKV_K8S_121): prevent exception when args don't exist

- checkov/terraform/variable_rendering/renderer.py
When using `str(string_val)` that contains `\`, the operation duplicates it. 
This fix will prevent from this duplication to occur.
> Improve string evaluation in variable rendering

- checkov/cloudformation/checks/resource/aws/NeptuneClusterLogging.py
- tests/cloudformation/checks/resource/aws/example_NeptuneClusterLogging/NeptuneClusterLogging-FAILED.yml
- tests/cloudformation/checks/resource/aws/example_NeptuneClusterLogging/NeptuneClusterLogging-PASSED.yml
- tests/cloudformation/checks/resource/aws/test_NeptuneClusterLogging.py
This check already exists for Terraform, so I also implemented it for CloudFormation. I also wanted to add `CKV_AWS_102`, but you can't create a public accessible Neptune Cluster via CloudFormation.
> Add CKV_AWS_101 check to cloudformation

- .github/workflows/build.yml
Hi,
We're using checkov quite a lot to check our Terraform configurations. It's great to see this repository getting a lot of releases and updates we hugely benefit from it!
However it is quite cumbersome to embed any version apart from `latest` in our deployment pipeline templates due to the high release cadence on the docker images. I've, naively, tried to update the Github actions here to additionally update not only the `latest` tag but create another tag with just the major version, this could be used to pull the latest release inside of a given major version.
I'm not quite sure with the tagging strategy but this script will of course break if the semver versioning I've seen sometimes is broken in the tags so it might not fit the repository entirely, happy to take suggestions on what …
> Add a major version image that is stable for the docker images

- checkov/cloudformation/checks/resource/aws/DocDBAuditLogs.py
- tests/cloudformation/checks/resource/aws/example_DocDBAuditLogs/DocDBAuditLogs-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_DocDBAuditLogs/DocDBAuditLogs-PASSED.yaml
- tests/cloudformation/checks/resource/aws/example_DocDBEncryption/DocDBEncryption-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_DocDBEncryption/DocDBEncryption-PASSED.yaml
- tests/cloudformation/checks/resource/aws/example_DocDBLogging/DocDBLogging-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_DocDBLogging/DocDBLogging-PASSED.yaml
- tests/cloudformation/checks/resource/aws/example_DocDBTLS/DocDBTLS-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_DocDBTLS/DocDBTLS-PASSED.yaml
- tests/cloudformation/checks/resource/aws/test_DocDBAuditLogs.py
- tests/cloudformation/checks/resource/aws/test_DocDBEncryption.py
- tests/cloudformation/checks/resource/aws/test_DocDBLogging.py
- tests/cloudformation/checks/resource/aws/test_DocDBTLS.py
Implement `CKV_AWS_104` check equivalent for CloudFormation.
I also added tests for passed/failed resources to the other DocDB check tests to make clear, what should pass or fail.
> Add docdb audit log check

- checkov/arm/checks/resource/SQLServerNoPublicAccess.py
- checkov/terraform/checks/resource/azure/SQLServerNoPublicAccess.py
- tests/arm/checks/resource/example_SQLServerNoPublicAccess/sqlServerNoPublicAccess-TDE-FAILED.json
- tests/arm/checks/resource/example_SQLServerNoPublicAccess/sqlServerNoPublicAccess-TDE-PASSED.json
- tests/terraform/checks/resource/azure/test_SQLServerNoPublicAccess.py
See https://docs.bridgecrew.io/docs/bc_azr_networking_4#fix---buildtime.
Without this change, the rule CKV_AZURE_11 erroneously flags a firewall rule that allows access _only_ from Azure internal services as allowing access from the entire Internet.
> Make SQL firewall rule congruent with documentation

- checkov/terraform/checks/resource/azure/KeyVaultEnablesFirewallRulesSettings.py
- tests/terraform/checks/resource/azure/test_KeyVaultEnablesFirewallRulesSettings.py
Hello,
I noticed this rule changed recently (it made no sense before). However, this rule is not working properly. It expects a "deny". However, azurerm expects "Deny". If "deny" is given to azurerm it will fail.
I'm not sure if there is anything else I should update. Please bring it to my attention and I will make the changes.
> [CKV_AZURE_109] Update KeyVaultEnablesFirewallRulesSettings.py to expect a properly formated value

- checkov/terraform/checks/data/base_check.py
- tests/graph/terraform/runner/test_graph_builder.py
- tests/terraform/checks/data/test_base_data_check.py
Fixes partially #1068.
Since the data sources have a different base check, I also added here the possibility to ignore data sources with `count = 0`
> Ignore data sources with a count of zero

- checkov/cloudformation/checks/resource/BaseCloudsplainingIAMCheck.py
- checkov/cloudformation/checks/utils/iam_cloudformation_document_to_policy_converter.py
- checkov/common/graph/graph_builder/graph_components/attribute_names.py
- checkov/common/graph/graph_builder/graph_components/edge.py
- checkov/terraform/checks/provider/aws/__init__.py
- checkov/terraform/checks/provider/aws/credentials.py
- checkov/terraform/checks/provider/base_check.py
- checkov/terraform/checks/provider/base_registry.py
- checkov/terraform/checks/provider/linode/__init__.py
- checkov/terraform/checks/provider/linode/credentials.py
- checkov/terraform/checks/utils/dependency_path_handler.py
- checkov/terraform/checks/utils/iam_terraform_document_to_policy_converter.py
- checkov/terraform/checks/utils/utils.py
- checkov/terraform/graph_builder/graph_components/attribute_names.py
- checkov/terraform/graph_builder/local_graph.py
- mypy.ini
- tests/graph/terraform/graph_builder/test_local_graph.py
Next batch of type hints, this time for `terrafom.checks.provider` and `terrafom.checks.utils`.
I also moved `convert_cloudformation_conf_to_iam_policy.py` to the cloudformation code base, which is probably the correct place to have it 😉 
Other than that, I also renamed `CustomAttributes` to `CustomTerraformAttributes` in the terraform code base to better differentiate the difference between the original one and the subclass.
> Add type hints to terraform utils and provider

- checkov/terraform/checks/resource/aws/RedshiftInEc2ClassicMode.py
- tests/terraform/checks/resource/aws/example_RedshiftInEc2ClassicMode/main.tf
- tests/terraform/checks/resource/aws/test_RedshiftInEc2ClassicMode.py
new check for redshift that checks that the cluster is created within a VPC.
addressing one of these failures https://github.com/iacsecurity/tool-compare
> add check redshift should be in vpc

- checkov/cloudformation/checks/resource/aws/IAMRoleAllowsPublicAssume.py
- tests/cloudformation/checks/resource/aws/example_IAMRoleAllowsPublicAssume/FAILED-2.yml
- tests/cloudformation/checks/resource/aws/example_IAMRoleAllowsPublicAssume/PASSED-2.yml
- tests/cloudformation/checks/resource/aws/test_IAMRoleAllowsPublicAssume.py
In cloudformation `IAMRoleAllowsPublicAssume`, handle a case where the assume_role_policy_doc is a json statement
> Support json statements in cfn IAMRoleAllowsPublicAssume

- checkov/terraform/plan_parser.py
- tests/terraform/runner/resources/plan_with_resource_reference/tfplan.json
- tests/terraform/runner/test_plan_runner.py
Fixes #1148. I tried to be as cautious as possible, so if there is no `configuration` block or anything else nested, then just ignore it. And I also added type hints inside the file 😄
> Add missing references to the Terraform plan parsing

- checkov/terraform/checks/resource/aws/ElasticsearchDomainNodeToNodeEncryption.py
- tests/terraform/checks/resource/aws/example_ElasticsearchDomainNodeToNodeEncryption/main.tf
- tests/terraform/checks/resource/aws/test_ElasticsearchDomainNodeToNodeEncryption.py
Ensure that node to node communication is encrypted - is not by default.
Addresses missing checks as tested here: https://github.com/iacsecurity/tool-compare
> Check: elasticsearch has node to node encrypted coms

- checkov/terraform/checks/graph_checks/aws/IAMUserHasNoConsoleAccess.yaml
- tests/graph/terraform/checks/resources/IAMUserHasNoConsoleAccess/expected.yaml
- tests/graph/terraform/checks/resources/IAMUserHasNoConsoleAccess/main.tf
- tests/graph/terraform/checks/test_yaml_policies.py
This check is looking for IAM users, who have console access, which is usually discouraged and instead something like AWS SSO or SAML should be used to manage human user access to AWS.
> Add CKV2_AWS_22 check to find IAM users with console access

- checkov/terraform/variable_rendering/evaluate_terraform.py
- checkov/terraform/variable_rendering/safe_eval_functions.py
- tests/graph/terraform/variable_rendering/test_string_evaluation.py
In the variable rendering process we are trying to evaluate strings which might contain terraform function calls or python expressions.
In order to make sure the call to python's `eval` function is as safe as possible without losing the ability to evaluate terraform functions we can use the `compile` function to generate a code object, and check if that code object contains any names that are within python's builtin names (containing `__`).
If such a name exists, the string is not evaluated and a custom `BuiltinError` is raised.
Added unit tests to check some interesting cases.
> Restrict string eval() calls in variable rendering

- .github/workflows/pr-test.yml
- checkov/terraform/variable_rendering/evaluate_terraform.py
- checkov/terraform/variable_rendering/safe_eval_functions.py
- tests/graph/terraform/variable_rendering/test_string_evaluation.py
In terraform variable rendering, replaced looking for builtin names with looking for `__` substring. 
Added some more UTs for this use case.
> Avoid evaluation strings with double underscores in var rendering

- checkov/terraform/variable_rendering/evaluate_terraform.py
- checkov/terraform/variable_rendering/safe_eval_functions.py
- tests/graph/terraform/variable_rendering/test_string_evaluation.py
Replaced throwing and exception in case of `__` is in an evaluated string with logging a warning and returning the origin string.
> Replace string evaluation exception with warning

- checkov/terraform/checks/resource/aws/S3BucketObjectLock.py
- tests/graph/terraform/runner/test_graph_builder.py
- tests/terraform/checks/resource/aws/example_S3BucketObjectLock/main.tf
- tests/terraform/checks/resource/aws/test_S3BucketObjectLock.py
Fixes #1208. There is a high chance that also other checks have a similar problem. Sometimes configuration can be either written as an object or block. I also took a look into lark parser, but I don't think it is a good idea to change the logic there.
> Incorporate block reference in CKV_AWS_143 check

- checkov/terraform/checks_infra/solvers/attribute_solvers/equals_attribute_solver.py
- tests/graph/terraform/checks/resources/ALBRedirectsHTTPToHTTPS/expected.yaml
- tests/graph/terraform/checks/resources/ALBRedirectsHTTPToHTTPS/main.tf
This PR handles type conversion for Equals (and NotEquals) graph checks. For example, the HTTP -> HTTPS redirect check fails if you specify the port as an int. But this is valid in TF.
@rotemavni does this need to be updated somewhere in the platform?
> do equals comparisons as strings

- checkov/terraform/checks/resource/aws/IAMStarActionPolicyDocument.py
Upon testing the following resource:
```hcl
resource "aws_iam_policy" "policy" {
name        = "my_policy-${var.aws_account_id}"
path        = "/"
description = "My test policy"
policy = <<EOF
{
"Version": "2012-10-17",
"Statement": [
{
"Action": [
"*"
],
"Effect": "Allow",
"Resource": "arn:aws:iam::${var.aws_account_id}:role/admin"
}
]
}
EOF
}
```
Checkov 2.x returns a false positive because it fails to parse the IAM policy properly. This is due to https://github.com/bridgecrewio/checkov/commit/44100303db08412b9ad28505d59de8b21aff2c30 as of Checkov 2.0 which changes the `conf` to a dict, in turn breaking the `json.loads` here in this check.
> fix ckv_aws_63 to handle conf dict properly

- checkov/arm/runner.py
- checkov/cloudformation/runner.py
- checkov/common/bridgecrew/platform_integration.py
- checkov/common/runners/base_runner.py
- checkov/dockerfile/runner.py
- checkov/helm/runner.py
- checkov/kubernetes/runner.py
- checkov/main.py
- checkov/runner_filter.py
- checkov/serverless/runner.py
- checkov/terraform/graph_manager.py
- checkov/terraform/parser.py
- checkov/terraform/runner.py
- tests/common/runners/test_base_runner.py
In platform-integration, added a function that calls for the repository settings and look for excluded paths. 
Added the excluded path as another member to the runner filter and use it to match paths in `filter_ignored_directories` function. 
This also prevents persisting the excluded paths to s3.
> Skip scanning excluded paths in platform integration

- checkov/cloudformation/context_parser.py
- tests/cloudformation/parser/cfn_with_ref.yaml
- tests/cloudformation/parser/test_cfn_yaml.py
This PR fixes CFN param replacement. It would copy in the line numbers of the parameter dict entry. The result was that the resource lines would range from the start of the param to the end of the resource.
@tronxd I think there might be nuances between CFN and JSON parsing that need to be handled here. I am not sure. Please take a look.
> do not copy line numbers during param replacement

- checkov/cloudformation/checks/resource/aws/TimestreamDatabaseKMSKey.py
- checkov/terraform/checks/resource/aws/TimestreamDatabaseKMSKey.py
- tests/cloudformation/checks/resource/aws/example_TimestreamDatabaseKMSKey/TimestreamDatabaseKMSKey-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_TimestreamDatabaseKMSKey/TimestreamDatabaseKMSKey-PASSED.yaml
- tests/cloudformation/checks/resource/aws/test_TimestreamDatabaseKMSKey.py
- tests/terraform/checks/resource/aws/example_TimestreamDatabaseKMSKey/main.tf
- tests/terraform/checks/resource/aws/test_TimestreamDatabaseKMSKey.py
Terraform support for Timestream came out quite recently and of course you can encrypt it with your own KMS key 😉 and I also added the same check as an CloudFormation check, why not 😄
> Add CKV_AWS_160 check for Timestream DB KMS encryption

- checkov/logging_init.py
- checkov/terraform/context_parsers/base_parser.py
- checkov/terraform/parser.py
- checkov/terraform/variable_rendering/evaluate_terraform.py
1. Avoid double logging for no reason
2. Filter optional comment lines to reduce number of calls to re.match()
3. Use direct access instead of dpath.search inside the context to reduce run time
4. Handle case of non-str in evaluated_string_parts to succeed in joining to new string
> Improve collect skip comments performance

- checkov/terraform/checks/resource/azure/StorageAccountDisablePublicAccess.py
https://docs.bridgecrew.io/docs/ensure-that-storage-accounts-disallow-public-access, the “Ensure that storage accounts disallow public access” should flag on allow_blob_public_access = true, NOT enable_https_traffic_only.  You can see that the below 2 issues are flagging on the same line.
attribute checko was wrong and of the wrong type. not sure how the test passed.
> fix:Check neg on attribute allow_blob_public_access for Azure storage account

- checkov/terraform/checks/graph_checks/aws/AutoScalingEnableOnDynamoDBTables.yaml
- tests/graph/terraform/checks/resources/AutoScalingEnableOnDynamoDBTables/expected.yaml
- tests/graph/terraform/checks/resources/AutoScalingEnableOnDynamoDBTables/main.tf
Fixes #1251 
the check now only considers autoscaling related to DynamoDB tables, which will not raise false positives related to other non DynamoDB tables. I also changed the flagging to be connected with the DynamoDB table and not `aws_appautoscaling_policy`. Additionally a DynamoDB table which is provisioned with `billing_mode = "PAY_PER_REQUEST"` will pass the check too, because it has already autoscaling embedded in it 😉
> fix CKV2_AWS_16 check to only consider DynamoDB tables

- checkov/cloudformation/checks/resource/aws/RDSClusterIAMAuthentication.py
- checkov/cloudformation/checks/resource/aws/RDSIAMAuthentication.py
- checkov/terraform/checks/resource/aws/RDSClusterIAMAuthentication.py
- checkov/terraform/checks/resource/aws/RDSIAMAuthentication.py
- tests/cloudformation/checks/resource/aws/example_RDSClusterIAMAuthentication/RDSClusterIAMAuthentication-FAIL.yaml
- tests/cloudformation/checks/resource/aws/example_RDSClusterIAMAuthentication/RDSClusterIAMAuthentication-PASSED.yaml
- tests/cloudformation/checks/resource/aws/example_RDSIAMAuthentication/RDSIAMAuthentication-FAIL.yaml
- tests/cloudformation/checks/resource/aws/example_RDSIAMAuthentication/RDSIAMAuthentication-PASSED.yaml
- tests/cloudformation/checks/resource/aws/example_RDSIAMAuthentication/RDSIAMAuthentication-UNKNOWN.yaml
- tests/cloudformation/checks/resource/aws/test_RDSClusterIAMAuthentication.py
- tests/cloudformation/checks/resource/aws/test_RDSIAMAuthentication.py
- tests/cloudformation/parser/test_cfn_yaml.py
- tests/terraform/checks/resource/aws/example_RDSClusterIAMAuthentication/main.tf
- tests/terraform/checks/resource/aws/example_RDSIAMAuthentication/main.tf
- tests/terraform/checks/resource/aws/test_RDSClusterIAMAuthentication.py
- tests/terraform/checks/resource/aws/test_RDSIAMAuthentication.py
I first tried to put both checks into the same, but the handling is quite awkward, so I split them into two. In general it is recommended to use IAM authentication for RDS databases and cluster, because you don't need to inject the password anymore and have to temporarily invoke a session to connect to the database.
> Add rds iam auth check

- checkov/cloudformation/checks/resource/aws/ECRImageScanning.py
- checkov/terraform/checks/resource/aws/ECRImageScanning.py
- tests/cloudformation/checks/resource/aws/example_ECRImageScanning/FAILED.yml
- tests/cloudformation/checks/resource/aws/example_ECRImageScanning/PASSED.yml
- tests/cloudformation/checks/resource/aws/test_ECRImageScanning.py
Hello,
Implementing this check as already done for Terraform. There was a placeholder because a previous version of CloudFormation did not include this functionality.
* Resolved Check ID conflict. Made sure TF and CF check for this could both live with the same ID.
TF Check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/ECRImageScanning.py
CF Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecr-repository-imagescanningconfiguration.html
**License**
> CF - Check - ECRImageScanning

- checkov/terraform/checks/graph_checks/aws/EIPAllocatedToVPCAttachedEC2.yaml
- tests/graph/terraform/checks/resources/EIPAllocatedToVPCAttachedEC2/expected.yaml
- tests/graph/terraform/checks/resources/EIPAllocatedToVPCAttachedEC2/main.tf
I'm not sure, if the name of the check `Ensure that all EIP addresses allocated to a VPC are attached to EC2 instances` is still accurate, because now it also checks if the EIP is attached to NAT Gateway.
> Fix CKV2_AWS_19 check to incorporate NAT Gateways

- checkov/terraform/checks/resource/aws/KMSRotation.py
- tests/terraform/checks/resource/aws/example_KMSRotation/main.tf
- tests/terraform/checks/resource/aws/test_KMSRotation.py
Fixes KMS rotation to only check for rotation on symmetric keys
https://docs.aws.amazon.com/kms/latest/developerguide/symm-asymm-concepts.html#asymmetric-cmks
> only check for rotation on symmetric keys

- checkov/common/bridgecrew/platform_integration.py
- checkov/common/runners/runner_registry.py
- checkov/main.py
Due to fixing some of the oddities in the onboarding, the multiple sources of where a bc_api_key could be retrieved from AND the multiple ways a repo_id could be either passed in or defaulted to made it difficult to track what it would be when and where.
Added functions to bc_integration to make that decision early in main.
Also when using the cli with out a github integration the flow was going down a custom path.  Getting the above correct should mean it always uses the same paths regardless for file or directory specified scan.  
This is just adding and commenting out.  If it works consistently there is a bunch of stuff in bc_integration that can be striped out.
This needs a new test in the workflow but I cannot add a secret in order to test the api_key part so I'll submit a new PR …
> added normalisation of api-key and repo-id for file and dir scan

- checkov/terraform/checks/resource/aws/AbsSecurityGroupUnrestrictedIngress.py
- tests/terraform/checks/resource/aws/test_SecurityGroupUnrestrictedIngress22.py
Handles the port checks when you specify `0` for both from_port and to_port.
> handle case when from_port and to_port are both 0 (all ports)

- checkov/common/output/report.py
- tests/common/runner_registry/test_runner_registry.py
Adds a count of the total unique resources in each scan report (outputs in JSON only).
> add resource count to json output

- checkov/common/bridgecrew/wrapper.py
- checkov/common/util/json_utils.py
This google module produced a JSON serialization error when running with platform integration and --download-external-modules.
https://github.com/terraform-google-modules/terraform-google-service-accounts
This is because it has sets in the definition, which don't get serialized to JSON.
This PR adds a JSON encoder to convert them to lists first.
> serialize set as list for json

- checkov/common/bridgecrew/platform_integration.py
Fixes an issue where os.path.join was used to construct a URL, which broke on windows.
> use / in URL, not OS native path

- checkov/terraform/checks/resource/aws/TransferServerIsPublic.py
- tests/terraform/checks/resource/aws/example_TransferServerIsPublic/main.tf
- tests/terraform/checks/resource/aws/test_TransferServerIsPublic.py
https://aws.amazon.com/premiumsupport/knowledge-center/aws-sftp-endpoint-type/
> Adding a rule to detect if an AWS Transfer Server is public

- checkov/common/bridgecrew/platform_integration.py
- checkov/main.py
Fixes the logic to filter out which directories to upload to use the same logic that filters out directories to scan (this will include the hardcoded defaults like node_modules and .terraform). Ultimately, this ensures that we only upload what we scan.
> Fix skip directory upload logic

- checkov/terraform/checks/resource/aws/ElasticsearchNodeToNodeEncryption.py
- tests/terraform/checks/resource/aws/example_ElasticsearchNodeToNodeEncryption/main.tf
- tests/terraform/checks/resource/aws/test_ElasticsearchNodeToNodeEncryption.py
Fixed the check to support old HCL syntax.
The check didn't support 
`something = { ... }`
but did support
`something { ... }`
> fixed n2n enc check to support old hcl

- checkov/common/bridgecrew/integration_features/features/fixes_integration.py
Pass `check_type` to remediations API, in order to get the right fixes
> feat(remediations): pass check type to remediations API

- Pipfile
- checkov/terraform/checks/resource/aws/GlacierVaultAnyPrincipal.py
- checkov/terraform/checks/resource/aws/SNSTopicPolicyAnyPrincipal.py
- checkov/terraform/checks/resource/aws/SQSQueuePolicyAnyPrincipal.py
- setup.py
- tests/terraform/checks/resource/aws/example_GlacierVaultAnyPrincipal/main.tf
- tests/terraform/checks/resource/aws/example_SNSTopicPolicyAnyPrincipal/main.tf
- tests/terraform/checks/resource/aws/example_SQSQueuePolicyAnyPrincipal/main.tf
- tests/terraform/checks/resource/aws/test_GlacierVaultAnyPrincipal.py
- tests/terraform/checks/resource/aws/test_SNSTopicPolicyAnyPrincipal.py
- tests/terraform/checks/resource/aws/test_SQSQueuePolicyAnyPrincipal.py
This PR introduces three new checks:
* CKV_AWS_167 - Ensure Glacier Vault access policy is not public by only allowing specific services or principals to access it
* CKV_AWS_168 - Ensure SQS queue policy is not public by only allowing specific services or principals to access it
* CKV_AWS_169 - Ensure SNS topic policy is not public by only allowing specific services or principals to access it
These checks use Netflix's [policyuniverse](https://github.com/Netflix-Skunkworks/policyuniverse) to parse IAM and resource policies. I recommend using this for all future checks that deal with these policies, as it's as easy as calling `policy.is_internet_accessible()`.
> Adding 3 new checks for * principals in Glacier Vaults, SNS Topic Policies, and SQS Queue Policies

- checkov/terraform/checks/resource/aws/SQSQueuePolicyAnyPrincipal.py
- tests/terraform/checks/resource/aws/example_SQSQueuePolicyAnyPrincipal/main.tf
Support a case where there is no json policy available to avoid throwing an exception.
> Support un-rendered policy in SQSQueuePolicyAnyPrincipal

- checkov/terraform/checks/resource/aws/GlacierVaultAnyPrincipal.py
- checkov/terraform/checks/utils/utils.py
@ac-square I expanded the check to support a case where the policy document attribute value is a runtime-rendered json file which terraform load
> Bugfix - Handle interpolation syntax when using policyuniverse

- checkov/main.py
- checkov/runner_filter.py
- tests/common/test_runner_filter.py
- tests/terraform/runner/test_runner.py
Treats externally loaded checks like all other checks in the `--check` flag. This changes the previous default behavior, in which all external checks would always run (unless skipped with `--skip-check`), even if they were not included in `--check`.
As discussed in [this issue](https://github.com/bridgecrewio/checkov/issues/466), some users rely on this old default behavior to ensure that any external checks added to a repo always get run, without modifying the `--check` list. To preserve this behavior, this change also introduces a new flag: `--run-all-external-checks`
> include external checks in --check flag

- Pipfile.lock
- checkov/terraform/plan_runner.py
- checkov/terraform/runner.py
- tests/terraform/runner/extra_yaml_checks/test_tag.yaml
- tests/terraform/runner/test_plan_runner.py
- tests/terraform/runner/test_runner.py
I'm using the terraform runner for most of the heavylifting, + leveraged the `build_graph_from_tf_definitions` to generate the graph.
Had to override the `get_entity_context_and_evaluations` from the tf runner - and that's basically it.
Resolves #1270
> Enable running graph checks on plan files

- checkov/cloudformation/checks/resource/aws/RedshiftClusterLogging.py
- checkov/cloudformation/checks/resource/aws/RedshiftClusterPubliclyAccessible.py
- checkov/cloudformation/checks/resource/aws/RedshiftInEc2ClassicMode.py
- checkov/cloudformation/checks/resource/base_resource_negative_value_check.py
- tests/cloudformation/checks/resource/aws/example_RedshiftClusterLogging/RedshiftClusterLogging-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_RedshiftClusterLogging/RedshiftClusterLogging-PASSED.yaml
- tests/cloudformation/checks/resource/aws/example_RedshiftClusterPubliclyAccessible/RedshiftClusterPubliclyAccessible-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_RedshiftClusterPubliclyAccessible/RedshiftClusterPubliclyAccessible-PASSED.yaml
- tests/cloudformation/checks/resource/aws/example_RedshiftInEc2ClassicMode/RedshiftInEc2ClassicMode-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_RedshiftInEc2ClassicMode/RedshiftInEc2ClassicMode-PASSED.yaml
- tests/cloudformation/checks/resource/aws/test_RedshiftClusterLogging.py
- tests/cloudformation/checks/resource/aws/test_RedshiftClusterPubliclyAccessible.py
- tests/cloudformation/checks/resource/aws/test_RedshiftInEc2ClassicMode.py
AWS recently added the possibility to set logging for Redshift cluster via CloudFormation, the Terraform check existed already. I also added some other missing Redshift checks to CloudFormation.
> Add cfn redshift logging check

- checkov/secrets/runner.py
This PR addresses a bug where running checkov like so `checkov -d path/to/iac -c <any-check>` also displays secret scanning related checks. 
This was also reported in #1363 
This also addresses issues with printing code blocks correctly for secret scanning.
Before this change code blocks for secret scanning were blank.
```
Check: CKV_SECRET_19: "Hex High Entropy String"
FAILED for resource: fc24931058dd40abe8e4719cc5d9be508c7e2585
File: /terraform/azure/sql.tf:15-16
Guide: https://docs.bridgecrew.io/docs/git_secrets_19
15 |
```
After this change:
```
Check: CKV_SECRET_19: "Hex High Entropy String"
FAILED for resource: fc24931058dd40abe8e4719cc5d9be508c7e2585
File: …
```
> Filter out appropriate check_ids from report based on config.checks

- checkov/common/runners/base_runner.py
- checkov/secrets/plugins/entropy_keyword_combinator.py
- checkov/secrets/runner.py
- tests/secrets/resources/terraform_failed/main.tf
- tests/secrets/test_plugin.py
- tests/secrets/test_runner.py
detect-secret's plugins require you to create a `analyze_string`, but this specific plugin needs to leverage the logic in the underlying plugins' `analyze_line`. Changed implementation accordingly.
> Fix entropy-keyword plugin to use analyze_line

- checkov/arm/base_registry.py
- checkov/cloudformation/checks/resource/base_registry.py
- checkov/dockerfile/base_registry.py
- checkov/helm/base_registry.py
- checkov/terraform/checks/data/base_registry.py
- checkov/terraform/checks/resource/base_registry.py
- kubernetes/Dockerfile
I found a couple more, compared to #1342. 
https://github.com/hadolint/hadolint checks for the missing `rm -rf /var/lib/apt/lists/*` instruction. `checkov` doesn't do that. The Dockerfile also misses a tag, instead of the implied `latest`.
> Python empty init

- checkov/cloudformation/cfn_utils.py
- checkov/common/models/consts.py
- tests/cloudformation/utils/file_formats/test2.yaml
- tests/cloudformation/utils/test_cfn_utils.py
There was a problem in the calculation of the start and end line of CFN definitions.
in yaml file - the end line was the last line before the next definition (including an empty line or comments).
for resources in yaml file - the start line was the line above the "Type" line, even if it was a comment or empty line.
in json file - the start and end lines were the line above the correct line.
I fixed the line numbers in the build_definitions_context function in cfn_utils file and added or fixed tests to check the correct values.
> Fix start and end line numbers of CFN definitions.

- checkov/common/checks_infra/registry.py
- tests/terraform/runner/test_runner.py
Fixes an issue that prevented platform custom policies from being saved in the registry, which prevented them from running.
> use a singleton registry per check type

- checkov/common/bridgecrew/bc_source.py
- checkov/common/bridgecrew/image_scanning/docker_image_scanning_integration.py
- checkov/common/bridgecrew/platform_integration.py
- checkov/common/util/http_utils.py
- checkov/main.py
- tests/common/test_platform_integration.py
This PR fixes an annoyance where using `--list` with an API key (which will download custom policies from the platform) still requires a repo-id, even though it will not be used.
It also refactors the logic for how different BC_SOURCE values affect the behavior to make it a little more generic. This refactor was required to make this change work (otherwise, with the platform integration, the repo-id was required to set up S3 credentials, but those creds wouldn't get used).
> Relax argument requirements when using --list

- checkov/terraform/graph_builder/local_graph.py
- checkov/terraform/graph_builder/utils.py
Two improvements that impact building edges for large graphs:
1. Removed deepcopy from attribute_has_nested_attributes
2. Use cache for modules paths
> Improve terraform graph building runtime

- checkov/terraform/checks/graph_checks/aws/Route53ARecordAttachedResource.yaml
- tests/terraform/graph/checks/resources/Route53ARecordAttachedResource/expected.yaml
- tests/terraform/graph/checks/resources/Route53ARecordAttachedResource/main.tf
Some brave folks still putting instances directly public.
> Route53 check was missing aws_instance

- checkov/cloudformation/graph_builder/graph_to_definitions.py
- checkov/cloudformation/graph_builder/local_graph.py
* Use empty dictionary when "Properties" doesn't exist in resource
* Get the correct resource name when the vertex block name contains more than one dot
> Cloudformation graph bugfixes

- checkov/common/bridgecrew/platform_integration.py
- tests/common/test_platform_integration.py
When `get_checkov_mapping_metadata`  works properly it sets the value of `self.ckv_to_bc_id_mapping` to be the mapping.
When the method cannot be executed it needs to set self.ckv_to_bc_id_mapping = {} rather than return `{}` because that return value is not used.
> Fix response of get_checkov_mapping_metadata()

- checkov/cloudformation/runner.py
- tests/cloudformation/runner/test_runner.py
There are 2 reasons for this change:
1. The CFN runner used the ContextParser instance because it needed the non static method `extract_cf_resource_code_lines` of this class but it doesn't use it anymore (after a recent refactor), it uses only static methods
2. When invoking the `run` method of the CFN runner with external `context`, `breadcrumbs` and `definitions`, the `definitions_raw` is not calculated, and then checkov crashes for `self.definitions_raw[cf_file]` of `                cf_context_parser = ContextParser(cf_file, definition, self.definitions_raw[cf_file])
`
> Remove ContextParser instance from CFN runner

- checkov/common/output/record.py
- checkov/common/output/report.py
- checkov/terraform/runner.py
- tests/terraform/runner/resources/duplicate_violations/modules/main.tf
- tests/terraform/runner/resources/duplicate_violations/src/main1.tf
- tests/terraform/runner/resources/duplicate_violations/src/main2.tf
- tests/terraform/runner/test_runner.py
When having multiple modules calling the same module we create a vertex for each module. 
This can lead to having duplicate records for the same resource in the scan report.
Added a dedup function that verifies we don't have more than one record with the same:
* check id
* resource
* file path
* lines
> Remove duplicate records for the same resource

- checkov/terraform/checks/resource/aws/EMRClusterKerberosAttributes.py
- tests/terraform/checks/resource/aws/test_EMRClusterKerberosAttributes.py
I've modified the check to give a skip for all EMR clusters rather than a pass. And changed the name of the check to reflect what it is actual is about. Should it check that all required parameters are checked not just realm? 
Will need to change docs if you pass this change.
> Kerberos check was giving all EMR cluster a passed check

- checkov/cloudformation/checks/resource/aws/TransferServerIsPublic.py
- tests/cloudformation/checks/resource/aws/example_TransferServerIsPublic/FAIL.yaml
- tests/cloudformation/checks/resource/aws/example_TransferServerIsPublic/PASS.yaml
- tests/cloudformation/checks/resource/aws/test_TransferServerIsPublic.py
Hello,
CF check for this as already done for TF.
TF Check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/TransferServerIsPublic.py
CF Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-server.html
**License**
> CF - Check - TransferServerIsPublic

- checkov/terraform/checks/resource/aws/EMRClusterIsEncryptedKMS.py
- tests/terraform/checks/resource/aws/example_EMRClusterIsEncryptedKMS/main.tf
- tests/terraform/checks/resource/aws/test_EMRClusterIsEncryptedKMS.py
This check emr data for S3 is encrypted with a KMS key of type SSE-KMS.
Partially addresses #1424
> Check that EMR security config uses KMS for S3EncryptionConfiguration #1424

- checkov/cloudformation/checks/resource/aws/QLDBLedgerPermissionsMode.py
- checkov/cloudformation/checks/resource/base_resource_value_check.py
- checkov/terraform/checks/resource/aws/QLDBLedgerPermissionsMode.py
- tests/cloudformation/checks/resource/aws/example_QLDBLedgerPermissionsMode/FAIL.yaml
- tests/cloudformation/checks/resource/aws/example_QLDBLedgerPermissionsMode/PASS.yaml
- tests/cloudformation/checks/resource/aws/test_QLDBLedgerPermissionsMode.py
- tests/terraform/checks/resource/aws/example_QLDBLedgerPermissionsMode/main.tf
- tests/terraform/checks/resource/aws/test_QLDBLedgerPermissionsMode.py
A bit background can be found here https://docs.aws.amazon.com/qldb/latest/developerguide/getting-started-standard-mode.html.
The possibility to change the permissions mode via Terraform was released today, which I included a few days ago, my first Terraform Provider PR 😄
> add check CKV_AWS_170 for QLDB permissions mode

- checkov/common/output/report.py
- tests/common/runner_registry/test_runner_registry_plan_enrichment.py
The loop in handle_skipped_checks removes items from a list while
iterating over it. In some situations, this causes skip annotations to
be ignored (findings are reported as failures anyway).
Fix #1456
> Fix loop in handle_skipped_checks

- docs/4.Integrations/GitLab CLI.md
In the hosted gitlab.com having a variable for allow_failure fails the CI Lint. Also remove the junit file when the output mode is text.
> GitLab ci example allow_failure can not be a var

- checkov/terraform/module_loading/loaders/git_loader.py
- This PR adds support for cloning external modules which use a "Generic Git Repository" format with `ssh:` 
- https://www.terraform.io/docs/language/modules/sources.html#generic-git-repository
- External module destination path is changed for windows so that it excludes "reserved windows characters"
- https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions
> Add support for ssh git clone. Use valid windows filenames

- checkov/terraform/module_loading/loaders/git_loader.py
This PR changes os.uname() to os.name in the git_loader.py class, since that method is not supported on windows. 
https://stackoverflow.com/questions/36250558/error-no-module-named-os-uname-under-python-2-7
> change os.uname to os.name

- checkov/cloudformation/cfn_utils.py
- checkov/cloudformation/runner.py
- tests/cloudformation/graph/graph_builder/test_local_graph.py
- tests/cloudformation/runner/test_runner.py
- tests/cloudformation/test_graph_manager.py
- tests/cloudformation/utils/test_cfn_utils.py
The purpose of this PR is to align the CFN graph block file path with TF graph block file path, because as it works right now, the TF block holds the absolute path and the CFN block holds the shorter path
> Align graphs blocks paths

- checkov/terraform/module_loading/loaders/git_loader.py
- checkov/terraform/module_loading/registry.py
This PR refactors the name of the directory in which external module sources are cloned on Windows. In the case of windows, instead of using the raw source string for building the destination path, a hash of the source is used instead for avoiding issues with reserved characters.
> Refactor windows folder names for saving external modules

- checkov/terraform/checks/graph_checks/azure/StorageContainerActivityLogsNotPublic.yaml
- tests/terraform/graph/checks/resources/StorageContainerActivityLogsNotPublic/expected.yaml
- tests/terraform/graph/checks/resources/StorageContainerActivityLogsNotPublic/main.tf
CKV2_AZURE_8 fails if "azurerm_monitor_activity_log_alert.enabled=true" is explicitly set.
This PR fixes the check and adds an additional unit test for the specific use case.
> Fix wrong evaluation of CKV2_AZURE_8 if azurerm_monitor_activity_log_alert.enabled=true

- checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
- tests/common/integration_features/test_suppressions_integration.py
Changes the suppression logic to understand suppressions from the platform that are applied to CLI run results (with the `bcorg_` prefix).
So now, suppressing `githuborg/repo` (the real github integration) or `bcorg_githuborg/repo` (a CLI run result) in the platform will apply to checkov runs with `--repo-id githuborg/repo`.
> understand platform suppressions with bcorg_ prefix

- checkov/terraform/checks/resource/aws/CodeBuildProjectEncryption.py
- tests/terraform/checks/resource/aws/example_CodeBuildProjectEncryption/main.tf
- tests/terraform/checks/resource/aws/test_CodeBuildEncrypted.py
- tests/terraform/checks/resource/aws/test_CodeBuildProjectEncryption.py
Codebuild encryption was failing if any value was set not just when it was disabled
Fixes #1458
> fix false positive on codebuild project encryption for #1458

- Dockerfile
The Checkov Dockerfile is currently running with default root privileges. It is good practice to user a non-root adds an extra layer of security. 
> [docker docs](https://docs.docker.com/engine/security/#linux-kernel-capabilities) & [bitnami blog](https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html) on dockerfile security
```console
$ docker run -it --entrypoint sh bridgecrew/checkov:2.0.348 
/ # id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
```
This is the container after my changes have been applied 
```console
$ docker run -it --entrypoint sh pandoraholladay/git-checkov
/ $ id
uid=1000(checkov) gid=1000(checkov) groups=1000(checkov)
/ $ ls -la
total 84
/ $ …
```
> Update Dockerfile to run as a non-root user 

- checkov/cloudformation/graph_manager.py
- checkov/cloudformation/parser/__init__.py
- checkov/cloudformation/runner.py
1. In some cases the template is not a dict so it crashes for template.get
2. In some cases the file path does not exist in the definitions object
> CFN Runner crashes for non dict template file and file paths that are missing in the definitions object

- checkov/common/output/graph_record.py
Fixes a missing param in GraphRecord that caused some bc_id values to not get passed into records
> Fix missing BC IDs in graph checks

- checkov/cloudformation/graph_builder/graph_components/block_types.py
- checkov/cloudformation/graph_builder/local_graph.py
1. When the resource in the `DependsOn` attribute is missing, CFN crashed, so I changed it to safe extraction
2. Removed unused ENUM (created a duplication in the new file `cfn_keyword` in PR #1498)
> CFN Graph creation crashes due to DependsOn resource missing

- checkov/arm/checks/resource/NSGRulePortAccessRestricted.py
- checkov/common/checks_infra/solvers/attribute_solvers/contains_attribute_solver.py
When running YAML checks, we might use the `contains` operator. 
If the attribute value being searched is not iterable, i.e not in `[str, list, set, dict]`, we won't be able to run the `in` operator on it.
This added condition protects us from attempting to run on different types.
> Fix contains attribute solver

- checkov/terraform/checks/graph_checks/aws/ALBProtectedByWAF.yaml
- tests/terraform/graph/checks/resources/ALBProtectedByWAF/expected.yaml
- tests/terraform/graph/checks/resources/ALBProtectedByWAF/main.tf
Fix/Improvement of _Check public alb has waf_  #1434. Added support for checking if ALB is associated to a _aws_wafv2_web_acl_association_ which is the latest version of AWS WAF. 
1. Added support for aws_wafv2_web_acl_association to CKV2_AWS_28 / Terraform
2. Updated tests
3. Updated expected results
cc @JamesWoolfenden @rotemavni 
> Fix/Improvement to CKV2_AWS_28

- checkov/common/output/record.py
- checkov/common/util/file_utils.py
Fixes the value for `repo_file_path` on Windows to always be a unix path. This value is never used for actual filesystem operations; it's only used to match suppressions with the platform.
> make the path used for suppressions a unix path always

- checkov/terraform/graph_builder/graph_components/module.py
- checkov/terraform/graph_builder/local_graph.py
- checkov/terraform/parser.py
- tests/terraform/parser/resources/double_slash.tf
- tests/terraform/parser/test_module.py
Apparently, hcl2 lib loads **from file** strings with `\\` as `\\\\`, while it does not do that for strings. This handles it
> Handle double slashes from hcl2 gracefully

- .github/workflows/pr-test.yml
- checkov/cloudformation/checks/resource/aws/LambdaDLQConfigured.py
- checkov/cloudformation/checks/resource/base_resource_check.py
- checkov/cloudformation/checks/resource/base_resource_negative_value_check.py
- checkov/common/checks/base_check.py
- tests/cloudformation/checks/resource/aws/example_LambdaDLQConfigured/FAIL.yaml
- tests/cloudformation/checks/resource/aws/example_LambdaDLQConfigured/PASS.yaml
- tests/cloudformation/checks/resource/aws/example_LambdaEnvironmentCredentials/FAIL.yaml
- tests/cloudformation/checks/resource/aws/example_LambdaEnvironmentCredentials/PASS.yaml
- tests/cloudformation/checks/resource/aws/test_LambdaDLQConfigured.py
This check already existed for Terraform and I also cleaned up the tests for the check `LambdaEnvironmentCredentials` to reflect the newer way of testing.
Other than that I also adjusted the type hints for the BaseCheck classes and I probably will rework them later again, because the `@multi_signature` decorator is still a mystery for me to type hint it correctly 😵
> Add lambda dlq check

- checkov/terraform/checks/resource/aws/LambdaEnvironmentEncryptionSettings.py
- tests/terraform/checks/resource/aws/example_LambdaEnvironmentEncryptionSettings/main.tf
- tests/terraform/checks/resource/aws/test_LambdaEnvironmentEncryptionSettings.py
Environmental variables for lambdas are supposed to be encrypted, this checks for that. 
Also if there no env vars theyre shouldn't be a key set, this also checks for that.
> aws lambda terraform - checks encryption settings for env vars

- checkov/common/runners/runner_registry.py
- checkov/main.py
- Treated the --output arg the same way as --external-checks-dir with multiple values accepted. Still defaults to cli. 
- Moved the junitxml print to the last action undertaken in the print function as it seemed to lag behind the other formats.
- Used '---OUTPUT DELIMITER---' as the delimiter between output types. I have not been able to find a better alternative but feel free to make the delimited whatever you all please.
> Added functionality for multiple output formats

- checkov/cloudformation/graph_builder/local_graph.py
- checkov/cloudformation/graph_builder/variable_rendering/renderer.py
1. checkov crashes while rendering Fn::Sub value which is a list and not a string. For now, skip values of list type
2. changed `logging.info` to `debug` level in some places
> Prevent checkov crash when rendering Fn::Sub

- checkov/terraform/checks/graph_checks/azure/VAconfiguredToSendReports.yaml
- checkov/terraform/checks/graph_checks/azure/VAconfiguredToSendReportsToAdmins.yaml
- checkov/terraform/checks/graph_checks/azure/VAsetPeriodicScansOnSQL.yaml
- tests/terraform/graph/checks/resources/VAconfiguredToSendReports/expected.yaml
- tests/terraform/graph/checks/resources/VAconfiguredToSendReports/main.tf
- tests/terraform/graph/checks/resources/VAconfiguredToSendReportsToAdmins/expected.yaml
- tests/terraform/graph/checks/resources/VAconfiguredToSendReportsToAdmins/main.tf
- tests/terraform/graph/checks/resources/VAsetPeriodicScansOnSQL/expected.yaml
- tests/terraform/graph/checks/resources/VAsetPeriodicScansOnSQL/main.tf
Several improvements for the checks: CKV2_AZURE_3, CKV2_AZURE_4 and CKV2_AZURE_5.
- The checks didn't consider the Terraform resource `azurerm_mssql_server`. Therefore the checks failed for anyone configuring a vulnerability assessment using the (modern) `azurerm_mssql_server`-resource.
- The checks reported an error on the `azurerm_mssql_server_security_alert_policy`-resource, instead of the `azurerm_mssql_server_vulnerability_assessment `-resource (#1446  #1447 )
- The check CKV2_AZURE_4 error message didn't match the actual check (#1561 )
> Fix Terraform Sql Server Vulnerability Assessment (VA) Checks

- checkov/common/bridgecrew/integration_features/base_integration_feature.py
- checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py
- checkov/common/bridgecrew/integration_features/features/fixes_integration.py
- checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
- tests/common/integration_features/test_custom_policies_integration.py
- tests/common/integration_features/test_fixes_integration.py
- tests/common/integration_features/test_suppressions_integration.py
This PR handles errors caused when the integration feature registry is run. An example of this would be, if an API token gets an error response while fetching custom policies from the platform, checkov will still complete the scan without erroring out.
> Fail gracefully on BC integration feature errors

- checkov/common/output/report.py
- tests/common/output/test_sarif_report.py
Closes #1521.
This PR adds some logic to ensure the rules in the rules array are unique, which is required by the SARIF schema. It also adds a unit test to validate the change. The test checks to see that a case where two records have the same rule is handled properly. If you add the test to the current master branch it fails; with the logic changes to report.py in this PR it passes.
> Fixes Github upload sarif results failure

- checkov/terraform/graph_builder/variable_rendering/safe_eval_functions.py
- tests/terraform/graph/variable_rendering/test_string_evaluation.py
When evaluating strings, the eval method encodes and decodes strings with unicode.
This may cause generating a null value `\u0000`. 
This PR removes this null value.
> Remove unwanted encoding to unicode null value `\u0000`

- checkov/terraform/parser.py
- tests/terraform/graph/variable_rendering/test_render_scenario.py
- tests/terraform/parser/resources/parser_scenarios/tfvars/expected.json
- tests/terraform/parser/resources/parser_scenarios/tfvars/main.tf
- tests/terraform/parser/resources/parser_scenarios/tfvars/other3.tfvars
Fixes an issue with the new `--var-file` arg where they might not be processed in the correct order, depending on the order that `os.scandir` returns files.
> handle unspecified os.scandir order with --var-file

- checkov/cloudformation/checks/resource/aws/LaunchConfigurationEBSEncryption.py
- checkov/terraform/checks/resource/gcp/GoogleComputeDefaultServiceAccountFullAccess.py
- tests/cloudformation/checks/resource/aws/example_LaunchConfigurationEBSEncryption/LaunchConfigurationEBSEncryption-UNKNOWN.yml
Fixed two checks:
**Cloudformation `CKV_AWS_8`:**
Handled a case where the value of `BlockDeviceMappings` is not a dictionary, for example - an If function.
**Terraform `CKV_GCP_31`:**
Handled the case where `scopes` is an empty array.
> Fixes to `CKV_GCP_31` and `CKV_AWS_8`

- checkov/cloudformation/runner.py
- tests/cloudformation/graph/graph_builder/resources/variable_rendering/render_params/yaml/test.yaml
- tests/cloudformation/runner/test_runner.py
If breadcrumbs exist for a resource, convert the record to be `GraphRecord` and add the relevant breadcrumbs to it.
> Add breadcrumbs to Cloudformation report

- Pipfile
- Pipfile.lock
- checkov/common/bridgecrew/image_scanning/docker_image_scanning_integration.py
- checkov/common/bridgecrew/integration_features/base_integration_feature.py
- checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py
- checkov/common/bridgecrew/integration_features/features/fixes_integration.py
- checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
- checkov/common/bridgecrew/platform_integration.py
- checkov/main.py
- docs/2.Basics/Visualizing Checkov Output.md
- setup.py
- tests/common/test_platform_integration.py
This PR adds support for PC customers. It leverages the access key and secret key (inputted as `ACCESS_KEY::SECRET_KEY`, authenticates with prisma and leverages the temp token for the next calls.
> Support PC tokens in checkov

- checkov/secrets/runner.py
- tests/secrets/test_runner.py
Updates the secrets runner to get BC check IDs from the platform (which doesn't happen normally due to how secrets checks are loaded)
The runner also needs to be updated to use BC check IDs for suppressions, but that will be a new PR.
> add bc check ID for secrets results

- checkov/secrets/runner.py
Allows --check, --skip-check to work with BC_IDs for secrets checks
> handle bc ids in --check, etc

- checkov/common/output/report.py
Fixes #1599.
This PR removes the prepended '/' from the record filepath in the SARIF results. By doing so, I hope to avoid a double slash in the filepath, which I believe may be causing file previews not to display in Github's code scanning results.
> strips leading slash from record filepath

- checkov/main.py
Removes the stacktrace that is printed when checkov is stopped by a keyboard interrupt.
> Remove traceback on keyboard interrupt

- .github/workflows/build.yml
- checkov/arm/runner.py
- checkov/cloudformation/runner.py
- checkov/common/output/report.py
- checkov/dockerfile/runner.py
- checkov/helm/runner.py
- checkov/kubernetes/runner.py
- checkov/secrets/runner.py
- checkov/serverless/runner.py
- checkov/terraform/runner.py
- tests/common/runner_registry/test_runner_registry.py
Updates the resource counting logic to be supplied by the runners. This ensures that graph runners (TF, CFN) count all resources. Other runners will count resources the same way (i.e., resources that are scanned by a policy).
> Resource counting all resources

- checkov/common/graph/checks_infra/solvers/base_solver.py
- checkov/terraform/checks/resource/azure/AppServiceUsedAzureFiles.py
- checkov/terraform/checks/resource/azure/MySQLTreatDetectionEnabled.py
- checkov/terraform/checks/resource/azure/PostgresSQLTreatDetectionEnabled.py
- checkov/terraform/checks/resource/gcp/GoogleComupteBlockProjectSSH.py
- checkov/terraform/graph_builder/graph_components/module.py
- checkov/terraform/graph_builder/local_graph.py
- checkov/terraform/graph_builder/variable_rendering/renderer.py
- checkov/terraform/parser.py
- checkov/terraform/runner.py
Relates #1589 
I still didn't figure out, why the scans became so much slower like described in the issue, but I did some profiling on the project, while scanning one of my Terraform projects.
I started with following
and finished with this 🙂 (profiling slows the run down dramatically, without it takes ~ 8 sec)
Taking a look on the worst methods (top 10), I started with this
and finished with this 💪 
For the `<listcomp>` and `fnmatchcase` I will create a separate PR, which will dramatically reduce it usage, it is related to usgae of the `cloudsplaining` lib.
After improving `resource_type_pred` I got following time
It looks like `resource_type` is not present so often, so it …
> Improve performance

- docs/3.Custom Policies/YAML Custom Policies.md
This adds newer operators to the docs, or ones that weren't originally there on checkov 2.0's release but were missed in the docs. 
- Regex was added in #1604 
- gt, gte, lt, lte was added in #1618 
- Any and Within was added in #1023
> docs: Add missing operators

- checkov/common/checks/base_check.py
- checkov/terraform/checks/data/BaseCloudsplainingIAMCheck.py
- tests/terraform/checks/data/aws/example_AdminPolicyDocument/main.tf
- tests/terraform/checks/data/aws/example_CloudSplainingCredentialsExposure/main.tf
- tests/terraform/checks/data/aws/example_CloudSplainingDataExfiltration/main.tf
- tests/terraform/checks/data/aws/example_CloudSplainingPrivilegeEscalation/main.tf
- tests/terraform/checks/data/aws/example_CloudsplainingPermissionsManagement/main.tf
- tests/terraform/checks/data/aws/example_StarActionPolicyDocument/main.tf
- tests/terraform/checks/data/aws/test_AdminPolicyDocument.py
- tests/terraform/checks/data/aws/test_CloudSplainingCredentialsExposure.py
- tests/terraform/checks/data/aws/test_CloudSplainingDataExfiltration.py
- tests/terraform/checks/data/aws/test_CloudSplainingPrivilegeEscalation.py
- tests/terraform/checks/data/aws/test_CloudsplainingIAMWrite.py
- tests/terraform/checks/data/aws/test_CloudsplainingPermissionsManagement.py
- tests/terraform/checks/data/aws/test_StarActionPolicyDocument.py
Relates #1589 and follow up to #1626
Starting from my previous improvement I could shave of more time 🚀 
And this changed of course the top 10 of the worst methods
The usage of `<listcomp>` and `fnmatchcase` dropped massively and therefore resulted in the performance boost. This improvement will be more impactful in setups with a lot of IAM data resource checks.
> Improve cloudsplaining usage

- checkov/common/util/docs_generator.py
Removed duplicate `check_type` in secrets docs generator.
> Removed duplicate data in docs generator

- checkov/cloudformation/checks/resource/aws/LambdaEnvironmentEncryptionSettings.py
- tests/cloudformation/checks/resource/aws/example_LambdaEnvironmentEncryptionSettings/FAIL.yaml
- tests/cloudformation/checks/resource/aws/example_LambdaEnvironmentEncryptionSettings/PASS.yaml
- tests/cloudformation/checks/resource/aws/test_LambdaEnvironmentEncryptionSettings.py
Hello,
Added CF check as done for TF.
No special case where kms key without env vars causes a problem like with Terraform.
**CF Docs**: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
**Terraform Check**: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/LambdaEnvironmentEncryptionSettings.py
**License**
> CF - Check - LambdaEnvironmentEncryptionSettings

- checkov/cloudformation/cfn_utils.py
- tests/cloudformation/runner/test_runner.py
Fixes an issue where certain types of tf files attempt to get parsed by the CFN parser and return a parsing error (they used to be silently skipped until the recent parser error handling updates)
> skip non-CF file endings with --file

- checkov/terraform/runner.py
- tests/terraform/runner/resources/module_skip/another/module/module-3/module.tf
- tests/terraform/runner/resources/module_skip/another/module/module.tf
- tests/terraform/runner/resources/module_skip/main.tf
- tests/terraform/runner/resources/module_skip/module/module.tf
- tests/terraform/runner/test_runner.py
Hi,
This is a potential solution #777.
I found that the `skipped_checks` property is already set on all entity types, i.e. modules, resources, etc.
So, I did not need to change the parse algorithm specifically for modules.
From here, I considered 2 potential solutions:
1. Push the skipped checks from one layer down to the next
2. When processing a resource, look up the graph to find other skip checks.
I implemented option 1 as it seemed simple and logical.
Note: This implementation will push skipped checks from a module to all entity types - modules, data, resources and provider.
Looking forward to your feedback.
> feat: skip rules when defined in a module

- checkov/terraform/runner.py
This PR is a performance improvement on pushing skipped checks to nested entities.
If there are 0 `skipped_checks`, it will not iterate over existing entities.
> fix: do not push skipped_checks if there are 0

- .github/workflows/pr-test.yml
- checkov/terraform/parser.py
- tests/terraform/runner/resources/unbalanced_eval_brackets/main.tf
- tests/terraform/runner/test_runner.py
Fixes issue #822 
In some cases when a TF file is malformed, the hcl2 parser hangs "forever" and therefore checkov hangs too. This solution puts the parsing method in a child process under a 60 seconds timeframe.
1. If the parsing succeeds before the time is up, the process is finished and closed automatically (as usual)
2. If the parsing fails before the time is up, the process is finished and closed automatically, the file is added to the "parsing error" dict (as usual)
3. If the parsing isn't finished under the 60 seconds cap, the process will be killed and the file will be added to the "parsing error" dict
> Timeout TF file parsing when stuck

- checkov/terraform/plan_parser.py
- tests/terraform/parser/resources/plan_tags_variety/tags.tf
- tests/terraform/parser/resources/plan_tags_variety/tfplan.json
- tests/terraform/parser/test_plan_parser.py
There are essentially two changes in this PR
1 - add some sanity checks to make sure we don't try to work on dict's when they are str's. I made it work but someone more familiar with it definitely needs a closer look. Prevents fatal exceptions when parsing terraform plans it doesn't like (ASG w/ tags in my case)
2 - encapsulate Tags in an extra [] for a certain code path. This fixes a problem I observed where Tags specified on an aws_autoscaling_group were returned as a [[{}]] by terraform's parser and [{}] by terraform_plan's parser. This makes them both [[{}]]. 
This change works for me with some reasonable testing. Note, I added a partial test case for #1 but not for #2. The existing test case hurt my brain too much to try and fully emulate.
> Fix plan parser edge case and tag processing

- checkov/terraform/checks/resource/aws/SecurityGroupRuleDescription.py
- tests/terraform/checks/resource/aws/test_SecurityGroupRuleDescription.py
This PR addresses an issue where `aws_security_group_rule` resources without a description would pass CKV_AWS_23. 
For example, prior to this PR this would pass:
```
resource "aws_security_group_rule" "example" {
type = "ingress"
from_port = 3389
to_port = 3389
protocol = "tcp"
cidr_blocks = "0.0.0.0/0"
security_group_id = "sg-123456"
}
```
Going forward, only resources that have descriptions for the "Group", "Ingress" and "Egress" blocks will pass this check as indicated in the docs - https://docs.bridgecrew.io/docs/networking_31
> Fix TF check for CKV_AWS_23

- checkov/runner_filter.py
- checkov/secrets/runner.py
- tests/common/test_runner_filter.py
- tests/secrets/test_runner.py
This PR adds support for wildcarding in the `--check` configuration option.  This is very similar in implementation to: https://github.com/bridgecrewio/checkov/pull/1649 and the original `--skip-check` wildcarding implementation in https://github.com/bridgecrewio/checkov/pull/750.  
There appears to be some code divergence between secrets and other frameworks.  After discovering that when fixing https://github.com/bridgecrewio/checkov/pull/1649 I have addressed both in this PR for `--check` support.
On master (not running any checks because the wildcard does not match anything explicitly):
```
/checkov --directory jvgiac --check 'CKV_AWS*'                                   Py checkov-bBv59Y8z
| (__| …
```
> Allow wildcard for checks

- checkov/terraform/parser.py
Replaced Queue with Pipe as we've found problems in some environments not supporting shared memories
> Replace Queue with Pipe

- checkov/common/output/report.py
- tests/common/output/test_get_exit_code.py
This PR adds support for wildcarding in the `--soft-fail-on` flag.  
On master:
```
checkov --directory jvgiac --check 'CKV_AWS_3' --soft-fail-on 'CKV_AWS*'
| (__| | | |  __/ (__|   < (_) \ V /
\___|_| |_|\___|\___|_|\_\___/ \_/
By bridgecrew.io | version: 2.0.438
cloudformation scan results:
Passed checks: 0, Failed checks: 1, Skipped checks: 0
Check: CKV_AWS_3: "Ensure all data stored in the EBS is securely encrypted"
FAILED for resource: AWS::EC2::Volume.Ebs1
File: /PASS.json:3-7
Guide: https://docs.bridgecrew.io/docs/general_3-encrypt-eps-volume
3 |     "Ebs1": {
4 |       "Type": "AWS::EC2::Volume",
5 |       "Properties": {
6 |       }
7 |     }
❯ echo $? …
```
> Support wildcarding in --soft-fail-on list

- checkov/secrets/runner.py
- tests/secrets/test_runner.py
Fixes https://github.com/bridgecrewio/checkov/issues/1641
This PR removes the secrets-only filtering / suppression logic that was in place, replacing it with a call to the common `RunnerFilter.should_run_check` determination logic.
On `master`:
```
checkov --directory jvgiac --framework secrets --skip-check 'CKV_SECRET_*'                                                              Py checkov-bBv59Y8z
| (__| | | |  __/ (__|   < (_) \ V /
\___|_| |_|\___|\___|_|\_\___/ \_/
By bridgecrew.io | version: 2.0.438
secrets scan results:
Passed checks: 0, Failed checks: 1, Skipped checks: 0
Check: CKV_SECRET_2: "AWS Access Key"
FAILED for resource: 25910f981e85ca04baf359199dd0bd4a3ae738b6
File: …
```
> Skip check wildcard not honored for secrets

- checkov/terraform/checks/resource/azure/CutsomRoleDefinitionSubscriptionOwner.py
Used dictionary `get` to fetch `permissions/[0]/actions/[0]`.
> Support malformed permissions in CKV_AZURE_39

- checkov/cloudformation/graph_builder/graph_components/blocks.py
- tests/cloudformation/graph/graph_builder/test_blocks.py
Handle attributes that are originally composed with a dot, like in the provided test case `app.kubernetes.io/name`. 
> Fix attribute updates for attributes with dots

- checkov/cloudformation/checks/resource/aws/IAMAdminPolicyDocument.py
- checkov/secrets/runner.py
- tests/cloudformation/checks/resource/aws/example_IAMRoleAllowAssumeFromAccount/example_IAMRoleAllowAssumeFromAccount-PASSED-2.yml
Fixed small bugs:
1. In `secrets/runner.py` - validate that a string split is valid before accessing it.
2. Validate `policy_block` is dict in `IAMAdminPolicyDocument`
3. Fixed cfn lint error in test file
> Small bugs fixes secrets + IAMAdminPolicyDocument

- checkov/cloudformation/checks/resource/aws/IAMAdminPolicyDocument.py
- checkov/cloudformation/checks/resource/aws/IAMStarActionPolicyDocument.py
- checkov/cloudformation/graph_builder/variable_rendering/renderer.py
1. renderer.py - val_to_eval must be a dict but in some cases it is not (and should be skipped in order to prevent exceptions)
2. IAMAdminPolicyDocument.py - In some cases the policy is not evaluated so 'PolicyDocument' is not a key of the policy
3. IAMStarActionPolicyDocument.py - Same case as item 2 + policy_block variable might be a string representing a dict so we transform it into a dict first
> Fixes for CFN Policies checks & edges creation

- checkov/terraform/checks/resource/azure/NetworkInterfacePublicIPAddressId.py
- tests/terraform/checks/resource/azure/test_NetworkInterfacePublicIPAddressId.py
This PR fixes a bug when CKV_AZURE_119 fails and the `public_ip_address_id` is null.
However the check should pass because no public interface is configured.
> CKV_AZURE_119: fix: public ip is not configured when public_ip_address_id is null

- checkov/terraform/graph_builder/local_graph.py
- checkov/terraform/graph_manager.py
- checkov/terraform/module_loading/content.py
- checkov/terraform/module_loading/loader.py
- checkov/terraform/module_loading/loaders/bitbucket_loader.py
- checkov/terraform/module_loading/loaders/git_loader.py
- checkov/terraform/module_loading/loaders/github_loader.py
- checkov/terraform/module_loading/loaders/local_path_loader.py
- checkov/terraform/module_loading/loaders/registry_loader.py
- checkov/terraform/module_loading/loaders/versions_parser.py
- checkov/terraform/module_loading/registry.py
- checkov/terraform/parser.py
- tests/terraform/graph/db_connector/test_networkx_connector.py
- tests/terraform/graph/graph_builder/test_local_graph.py
- tests/terraform/graph/graph_builder/test_terraform_graph_parser.py
- tests/terraform/module_loading/loaders/test_local_path_loader.py
- tests/terraform/module_loading/test_registry.py
- tests/terraform/parser/resources/registry_security_group/registry_security_group.tf
- tests/terraform/parser/resources/registry_security_group_inner_module/main.tf
- tests/terraform/parser/test_parser_modules.py
The biggest change I did was to restructure on where to clone the module repositories. Instead of just using one folder for the best suitable version of module, now each module version, which is used will get its own folder and be checked. The result is something like this:
```shell
github.com/terraform-aws-modules/terraform-aws-security-group/v3.18.0
github.com/terraform-aws-modules/terraform-aws-security-group/v4.0.0
github.com/terraform-aws-modules/terraform-aws-security-group/HEAD
```
the `HEAD` version of a module is the latest commit on the default branch.
Module references with SSH should also work, but I will add some tests to make sure it really works 😄
> refactor external module loading

- checkov/dockerfile/parser.py
- checkov/dockerfile/runner.py
- tests/dockerfile/resources/name_variations/.Dockerfile
- tests/dockerfile/resources/name_variations/Dockerfile.prod
- tests/dockerfile/resources/name_variations/prod.dockerfile
- tests/dockerfile/test_runner.py
This PR addresses: #1262
It is very common for organizations to use variations of `Dockerfile` for their Docker files, especially with the advent of mono repositories. Such alternative names could include:
- `Dockerfile.prod`
- `Dockerfile.Product1`
- `dev.Dockerfile`
- `team1.product.dockerfile`
Furthermore, the VS Code plugin for Docker has also long recognized these patterns as valid Docker files and provided syntax highlighting: microsoft/vscode-docker#1908.
For this reason, it seems reasonable for Checkov to include these variations of names when scanning for Dockerfiles to analyze. This PR changes the behavior of the Docker runner to use the following regular expression for detecting Dockerfiles:
```regex
^(?:.+\.)?[Dd]ockerfile(?:\..+)?$
```
A unit test was added to ensure that the …
> Support name variations for Dockerfiles

- checkov/cloudformation/checks/resource/aws/IAMAdminPolicyDocument.py
- checkov/cloudformation/checks/resource/aws/IAMStarActionPolicyDocument.py
- checkov/cloudformation/parser/__init__.py
- tests/cloudformation/checks/resource/aws/example_IAMAdminPolicyDocument/iam_role.unknown.yaml
- tests/cloudformation/checks/resource/aws/example_IAMStarActionPolicyDocument/iam_role.unknown.yaml
Added validation in `IAMStarActionPolicyDocument` and `IAMAdminPolicyDocument` for accessing only dict policies and not strings.
> Check if policy is dict before accessing it

- integration_tests/prepare_data.sh
- integration_tests/test_checkov_cli_integration_report.py
Update `prepare_data.sh` to run checkov with bc-api-key only for `ubuntu-latest`
Update `integration_tests/test_checkov_cli_integration_report.py` tests to validate report only for ubuntu os.
> run bc-api-key tests only for ubuntu os

- checkov/common/bridgecrew/image_scanning/docker_image_scanning_integration.py
Used get instead of dict access when getting vulnerabilities.
> Avoid errors in image scanning report

- checkov/terraform/checks/graph_checks/aws/SGAttachedToResource.yaml
- tests/terraform/graph/checks/resources/SGAttachedToResource/expected.yaml
- tests/terraform/graph/checks/resources/SGAttachedToResource/main.tf
Add AWS Codestar Connections Hosts to the list of resource types checked to confirm if a Security Group is attached and not orphaned
> Add Codestar Connections Hosts to SG connection check for CKV2_AWS_5

- checkov/common/parallelizer/parallel_runner.py
- checkov/kubernetes/runner.py
- checkov/secrets/runner.py
- checkov/terraform/checks/resource/azure/CutsomRoleDefinitionSubscriptionOwner.py
Fixed a number of different bugs:
1. General multiprocessing - pass on EOF errors on yield when running a multiprocess function.
2. Secrets - added a safe running function to catch errors in scanning without causing run timeouts.
3. K8s - Fixed warning message to use correct param.
4. Terraform - unrelated bugfix in check.
> Multiprocessing bug fixes

- checkov/common/bridgecrew/image_scanning/image_scanner.py
Update twistlock CLI args, the recommended way to handle args is as a string, when shell=True, Thanks @gruebel 
> Update twistlock cli args usage

- checkov/common/graph/checks_infra/base_check.py
- checkov/common/graph/checks_infra/registry.py
- tests/cloudformation/graph/checks/resources/LambdaFunction/expected.yaml
- tests/cloudformation/graph/checks/resources/SagemakerNotebookEncryption/expected.yaml
- tests/cloudformation/graph/checks/test_yaml_policies.py
Add evaluated keys to graph check result, the evaluated key will be the check attribute (if exist), wrapped in list.
Expend `test_yaml_policies` tests to check the evaluated_keys in the report.
> add evaluated keys to graph check results

- checkov/kubernetes/checks/CPULimits.py
- checkov/kubernetes/checks/MemoryLimits.py
Supported a case where `conf["resources"]["limits"]` is None to avoid failures for `CKV_K8S_11` and `CKV_K8S_13`.
> Handle None limits for k8s checks

- checkov/common/output/report.py
- checkov/common/runners/runner_registry.py
This PR changes the behavior of the sarif output flag as follows:
1. Running `checkov -d xxx -o sarif` will print the CLI output to the console. 
2. A file `results.sarif` will be created in the directory where checkov is called. 
3. Default error level for every rule in the SARIF output is `error`. However, for results, level will depend on the outcome of the check. `error` for `CheckResult.FAILED` and `warning` for `CheckResult.SKIPPED`
Note that the SARIF output will not have `PASSED` checks but the console output will.  
Fixes: https://github.com/bridgecrewio/bridgecrew-action/issues/24
> Write sarif to results.sarif

- checkov/common/output/report.py
- checkov/common/runners/runner_registry.py
- checkov/common/util/banner.py
- checkov/main.py
- tests/common/output/test_cyclonedx_report.py
- tests/common/output/test_sarif_report.py
- tests/common/runner_registry/test_runner_registry.py
- tests/common/runner_registry/test_runner_registry_plan_enrichment.py
This PR adds the ability to use the right `tool` and `informationUri` in the SARIF output for `checkov` and `bridgecrew-py`
> Add tool name for sarif output

- checkov/common/runners/runner_registry.py
- checkov/main.py
- tests/common/output/test_cyclonedx_report.py
- tests/common/runner_registry/test_runner_registry.py
- tests/common/runner_registry/test_runner_registry_plan_enrichment.py
Removed the added `tool` argument in the `RunnerRegistry` constructor, and passed it directly to the print function.
> Use tool only for report prints

- checkov/common/runners/runner_registry.py
This PR fixes the following problem:
If we run checkov with `--framework terraform_plan` the previous runners would include both `terraform_plan` and `terraform` because 
`runner.check_type='terraform' in self.runner_filter.framework='terraform_plan'`.
> Select correct runner for --framework terraform_plan

- checkov/terraform/checks/graph_checks/aws/WAF2HasLogs.yaml
- tests/terraform/graph/checks/resources/WAF2HasLogs/expected.yaml
- tests/terraform/graph/checks/resources/WAF2HasLogs/main.tf
- tests/terraform/graph/checks/test_yaml_policies.py
WAF2 works differently from WAF/WAFRegional in that its logging config is a separate logging resource, so this check needs to be a graph check.
> ensure WAF2 has logs

- docs/4.Integrations/Terraform Scanning.md
The example in the Terraform Plan section didn't have an example showing the use of `jq` which is actually pretty important when scanning plan files. Also, there was a broken example image which I replaced with a code snippet which I felt was better than nothing.
> expanding terraform plan example

- checkov/cloudformation/checks/resource/aws/SecretManagerSecretEncrypted.py
- checkov/terraform/checks/resource/aws/SecretManagerSecretEncrypted.py
- tests/cloudformation/checks/resource/aws/example_SecretManagerSecretEncrypted/FAIL.yaml
- tests/cloudformation/checks/resource/aws/example_SecretManagerSecretEncrypted/PASS.yaml
- tests/cloudformation/checks/resource/aws/test_SecretManagerSecretEncrypted.py
Hello,
I'm back to slowly trying to catch the CF checks up with TF.
Tried to follow latest conventions but just lemme know if need to change anything.
TF Check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/SecretManagerSecretEncrypted.py
TF Doc: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret
CF Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html
If you see i'm instead checking if the field matches the pattern `"aws/"` instead of `"alias/aws/"` because I am under the impression that if you miss out the 'alias' part CF / TF / the AWS CLI still infer that it should use aws/* KMS Key.
I could be wrong but I figured this was a safer bet because …
> CF - Check - SecretManagerSecretEncrypted

- tests/common/utils/test_prompt.py
Changed to `pytest` syntax and incorporated the usage of `tmp_path` for the creation of the check files.
> adjust prompt tests to use tmp_path

- checkov/terraform/graph_builder/variable_rendering/renderer.py
The rendering can cause very, very long strings to get created. Most of them are not useful so it's a waste of time to try and evaluate them - this sets a configurable limit (with a friendly log message)
> Set max length of 10,000 characters for terraform statement evaluation

- checkov/kubernetes/checks/NginxIngressCVE202125742Alias.py
- checkov/kubernetes/checks/NginxIngressCVE202125742AllSnippets.py
- checkov/kubernetes/checks/NginxIngressCVE202125742Lua.py
- tests/kubernetes/checks/example_NginxIngressCVE202125742/annotation1-FAILED.yaml
- tests/kubernetes/checks/example_NginxIngressCVE202125742/annotation2-nollua-PASSESONEFAILSONE.yaml
- tests/kubernetes/checks/example_NginxIngressCVE202125742/annotation3-alias.yaml
- tests/kubernetes/checks/example_NginxIngressCVE202125742/noannotations-PASSED.yaml
- tests/kubernetes/checks/test_NginxIngressCVE202125742Alias.py
- tests/kubernetes/checks/test_NginxIngressCVE202125742AllSnippets.py
- tests/kubernetes/checks/test_NginxIngressCVE202125742Lua.py
This PR Contains two new Kubernetes checks based on detecting CVE-2021-25742.
(More details on the CVE Here: https://github.com/kubernetes/ingress-nginx/issues/7837).
The first check fails if there are annotations containing configuration snippets **AND** it looks like those snippets contain lua-related directives or access the kubernetes.io secrets/config paths.
The second check is wider, and will fail if there are any annotations related to nginx configuration snippets.
This gives users a choice, as conversations in https://github.com/kubernetes/ingress-nginx/issues/7837 suggest that fully blocking snippets in annotations works well, but for others they need snippets and just want to block lua script directives.
A user could chose which they need by either `--skip-checks CKV_K8S_152` or …
> Add checks for NGINX Ingress CVE-2021-25742

- checkov/common/bridgecrew/platform_integration.py
- checkov/common/util/http_utils.py
- checkov/main.py
- tests/common/utils/test_utils.py
Adds some better error handling and messaging around auth errors, which are causing users a lot of trouble in the beta.
Also trims a trailing slash off the Prisma API URL, which causes 404s.
> Auth error handling

- checkov/terraform/module_loading/loaders/github_loader.py
The current approach works for terraform modules on Github, publicly accessible
using the HTTPS scheme. This change also adds support for private Github repositories,
accessible using the SSH scheme.
https://www.terraform.io/docs/language/modules/sources.html#github
> Add terraform github ssh module loader

- checkov/terraform/checks/graph_checks/gcp/ServiceAccountHasGCPmanagedKey.yaml
- tests/terraform/graph/checks/resources/ServiceAccountHasGCPmanagedKey/expected.yaml
- tests/terraform/graph/checks/resources/ServiceAccountHasGCPmanagedKey/main.tf
Fix for https://github.com/bridgecrewio/checkov/issues/1416.
As mentioned in issue above, it's indeed the case that Google does not recommend using service account keys if possible. However looking at the code I am wondering if the checks are looking for [user-managed service account keys](https://cloud.google.com/iam/docs/service-accounts#user-managed_keys). Either way, they should be avoided.
> CKV2_GCP3: Reverse test logic for GCP service account key check

- checkov/terraform/checks/resource/gcp/GoogleCloudSqlBackupConfiguration.py
- tests/terraform/checks/resource/gcp/test_GoogleCloudSqlBackupConfiguration.py
Solves the false positive mentioned in https://github.com/bridgecrewio/checkov/issues/727.
The `master_instance_name` attribute is used to [point the replica to a master instance](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#master_instance_name). So the existence of this attribute means the current resource is a replica.
This PR adds a little check that checks if the attribute exists and passes it if it does.
> CKV_GCP_14: Add check that ignores Cloud SQL replica instances

- .github/workflows/pr-test.yml
- .gitignore
- performance_tests/pytest.ini
- performance_tests/test_checkov_performance.py
- Use `pytest-benchmark` plugin to evaluate execution times of different IaC runners on known benchmarks.
- Performance tests will fail if they deviate by a configurable percecnt from the maximum duration of the tested branch against the data. 
- Thresholds are set according to current execution on the data.
> Performance tests

- checkov/terraform/checks/graph_checks/aws/Route53ARecordAttachedResource.yaml
The following fails `CKV2_AWS_23` as `aws_db_instance` isn't in the `connected_resource_types` list
```
resource "aws_route53_record" "rds" {
zone_id = data.aws_route53_zone.default.zone_id
name    = "myrecord"
type    = "A"
alias {
name                   = aws_db_instance.rds.address
zone_id                = aws_db_instance.rds.hosted_zone_id
evaluate_target_health = false
}
}
```
> Adding aws_db_instance connect resource type

- tests/terraform/parser/test_parser_modules.py
the cache is used for all the tests and therefore fills up with data from other tests.
> clear module_content_cache before the test

- Dockerfile
some of the `asyncio` packages use C extension and therefore need extra wheels for different OS. Not every package offers Alpine flavoured wheels, therefore they need to be build, like `cffi`.
> fix missing wheel files for alpine Docker build

- checkov/kubernetes/checks/resource/k8s/NginxIngressCVE202125742Lua.py
- tests/kubernetes/checks/example_NginxIngressCVE202125742/annotation1-FAILED.yaml
Changed the regex check for the lua check from re.match to re.search as the snippets are multiline.  It worked for the test because it's a single line snippet.  I'll change the test shortly as well.  
> changed re.match to re.search

- checkov/terraform/checks/graph_checks/aws/CloudFrontHasSecurityHeadersPolicy.yaml
- tests/terraform/graph/checks/resources/CloudFrontHasSecurityHeadersPolicy/expected.yaml
- tests/terraform/graph/checks/resources/CloudFrontHasSecurityHeadersPolicy/main.tf
- tests/terraform/graph/checks/test_yaml_policies.py
I used AWS example as a great base for creating the custom CloudFront response header policy, but was a bit more strict regards to the `override` 👮 
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/creating-response-headers-policies.html
> add CKV2_AWS_32 for CloudFront security header

- checkov/terraform/plan_runner.py
- tests/terraform/runner/test_plan_runner.py
no need to check for graph, if there is no Terraform plan file 😄
> skip graph scan for tf plans, if not exists

- checkov/cloudformation/checks/resource/base_resource_value_check.py
- checkov/terraform/checks/resource/aws/SQSQueueEncryption.py
- checkov/terraform/checks/resource/base_resource_check.py
- checkov/terraform/checks/resource/base_resource_negative_value_check.py
- checkov/terraform/checks/resource/base_resource_value_check.py
- checkov/terraform/graph_builder/graph_components/module.py
- checkov/terraform/parser_functions.py
- tests/cloudformation/checks/resource/aws/example_SQSQueueEncryption/test_SQSQueueEncryption-FAILED2.yml
- tests/cloudformation/checks/resource/aws/test_SQSQueueEncryption.py
- tests/terraform/checks/resource/aws/test_SQSQueueEncryption.py
- tests/terraform/graph/graph_builder/test_graph_builder.py
- tests/terraform/graph/resources/dynamic_lambda_function/lambda.tf
This PR has two improvements:
**Stop identifying empty strings as ANY_VALUE**
Until now, if a check had `ANY_VALUE` as the expected value, if the value is `""` the check passed, while it should have failed.
I added a validation that if the value is a string and it is empty, fail the check.
Added tests for it, under `test_SQSQueueEncryption`.
**Add terraform dynamic blocks to the graph vertices**
I extracted `handle_dynamic_values` from `base_resource_check` to `parser_functions` and use it when creating the resources graph vertices.
Added a test for it in `test_graph_builder`
> Empty strings as ANY_VALUE + Handle dynamic blocks

- checkov/terraform/checks/resource/oci/IAMPasswordLength.py
- tests/terraform/checks/resource/oci/example_IAMPasswordLength/main.tf
- tests/terraform/checks/resource/oci/test_IAMPasswordLength.py
Addresses #1969
Looks to see that the policy is set to 14 or more.
> port of prisma check OCI IAM password policy for local (non-federated) users does not have minimum 14 characters 

- checkov/cloudformation/checks/resource/aws/GlueSecurityConfiguration.py
- tests/cloudformation/checks/resource/aws/example_GlueSecurityConfiguration/GlueSecurityConfiguration-PASSED.yml
- tests/cloudformation/checks/resource/aws/test_GlueSecurityConfiguration.py
> fix GlueSecurityConfiguration check to not throw an exception if S3Encryptions is not a list

- checkov/terraform/checks/resource/oci/IAMPasswordLength.py
check if minimum_password_length attribute is int before compere it
> fix in IAMPasswordLength check

- checkov/terraform/module_loading/module_finder.py
- tests/terraform/module_loading/test_tf_module_finder.py
update module loader to wait for all modules loading when running parallel
> fix in module loader

- checkov/common/parallelizer/parallel_runner.py
- checkov/terraform/module_loading/module_finder.py
Change run_parallel default value in loading external modules to false because of runtime errors
> remove parallelize from external modules

- checkov/terraform/context_parsers/parsers/provider_context_parser.py
return False for `_is_block_signature` function in `ProviderContextParser` if the terraform file isn't valid
> add try-catch block for hcl2.loads failure in ProviderContextParser

- checkov/terraform/checks/resource/azure/AzureInstanceExtensions.py
- tests/terraform/checks/resource/azure/example_AzureInstanceExtensions/main.tf
- tests/terraform/checks/resource/azure/test_AzureInstanceExtensions.py
Fixes #2022 
Resource `azurerm_virtual_machine` is actually a deprecated resource and their specific flavours `windows` and `linux` should be used instead. I also adjusted the tests to newer syntax.
> fix CKV_AZURE_50 to check the correct resources

- README.md
- checkov/common/runners/runner_registry.py
- checkov/common/util/docs_generator.py
- checkov/main.py
- checkov/runner_filter.py
- tests/terraform/util/test_doc_generator.py
- tests/test_runner_filter.py
Fixes #1996 
Added the possibility to specify multiple frameworks (+ skipping them) to the CLI via the existing flags. Due to the nature of the used `choices` parameter those framework have to be inputed with a space in between.
```shell
$ checkov --framework terraform kubernetes -d .
$ checkov --skip-framework secrets terraform_plan -d .
```
I also checked and already existing config files will still work, so no breaking change to be expected 😅
> adjust framework and skip-framework CLI parameter to handlemultiple entries

- checkov/common/runners/runner_registry.py
Fixes #1995 
From my point of view this makes more sense, to align the CLI output behaviour to the others. What could happen before, if someone used more than one output and had more than one framework finding issues, then an output delimiter was added between those frameworks. If this is the intended behaviour then I can adjust the code to reflect it, but feels weird to actually do it like this.
> handle CLI report output as the others

- checkov/terraform/checks/graph_checks/aws/PostgresRDSHasQueryLoggingEnabled.yaml
Replaces #1784 
The possible values according to [tf docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#engine):
`aurora, aurora-mysql, aurora-postgresql`. So filtering on aurora-postgresql
CC: @acdha
> Restore postgres engine filter for CKV2_AWS_27

- checkov/terraform/checks/resource/aws/GlueDataCatalogEncryption.py
Updates the expected key for the case when the `return_connection_password_encrypted` attribute exists, but is false (previously it would return the parent key).
> fix inspected key when the value is explicitly false

- .github/exclude-patterns.txt
- checkov/common/runners/runner_registry.py
- checkov/common/util/json_utils.py
- checkov/terraform/parser.py
- tests/common/utils/test_json_utils.py
from 3 `JSONEncoders` make 1 😄 
there was no real elegant way to write a `pytest` test, which checks, that no exception was raised. Happy for some suggestion, except using `try ... except ...` 😄
> consolidate custom json encoder

- checkov/arm/checks/resource/AKSDashboardDisabled.py
This PR addresses the issues described by #1765 for the ARM AKSDashboardDisabled check.
> Fix aks dashboard disabled

- checkov/terraform/module_loading/loaders/git_loader.py
- tests/terraform/module_loading/test_registry.py
This also removes a duplicated test function and adds tests for modules
that are loaded via ssh in general.
> Fix loading of module sources without explicit ssh://

- checkov/terraform/checks/resource/aws/DynamoDBTablesEncrypted.py
In some cases the SSE is not a dict and thus we receive an exception for get method that doesn't exist
> Fixed SSE validation

- checkov/common/output/graph_record.py
- checkov/common/output/record.py
- checkov/common/output/report.py
- checkov/terraform/plan_parser.py
- checkov/terraform/plan_runner.py
- checkov/terraform/runner.py
- tests/common/runner_registry/plan_module_skip_for_enrichment/mod_ref/main.tf
- tests/common/runner_registry/plan_module_skip_for_enrichment/tf/main.tf
- tests/common/runner_registry/plan_module_skip_for_enrichment/tf/tfplan.json
- tests/common/runner_registry/test_runner_registry_plan_enrichment.py
Fixes https://github.com/bridgecrewio/checkov/issues/2047 by saving the resource address in a TF plan run and then using that address to look up suppressions for the module during the enrichment phase.
I could think of one alternative approach to this that seemed like a little less of a hack, but was also probably overkill. That approach would be to replace this line with logic to repeat the entire parsing and graph building logic and reconstruct the entire module structure from scratch. Then use the logic introduced in that PR I reference in the issue to push suppressions down to the resources in the same way.
However, that seemed like overkill, and avoiding unnecessarily …
> Handle module suppression enrichments

- checkov/terraform/checks/resource/aws/SQSQueuePolicyAnyPrincipal.py
- tests/terraform/checks/resource/aws/example_SQSQueuePolicyAnyPrincipal/main.tf
- tests/terraform/checks/resource/aws/test_SQSQueuePolicyAnyPrincipal.py
Updates the public SQS queue policy to work on both queue_policy and queue resources
> check embedded policy on aws_sqs_queue

- checkov/main.py
Check that if a repo-id is not composed of `<non empty string>/<non empty string>`, throw a parsing error.
> Verify repo-id format

- checkov/kubernetes/checks/resource/k8s/ApiServerServiceAccountKeyFile.py
> Fix ApiServerServiceAccountKeyFile.py regex to avoid backtracking

- checkov/kubernetes/graph_builder/local_graph.py
Ran into a situation where the metadata was `None`. Then, this:
```python
metadata = d.get('metadata', {})  # metadata is None, not {}
```
This handles it
> Handle None metadata by definition gracefully for k8s graph

- checkov/terraform/checks/resource/azure/StorageAccountName.py
- tests/terraform/checks/resource/azure/example_StorageAccountName/main.tf
- tests/terraform/checks/resource/azure/test_StorageAccountName.py
Fixes #741 
If we can't evaluate the typical references, we should just ignore it and flag it as `UNKNOWN`.
> adjust CKV_AZURE_43 to ignore names, if they could not be evaluated

- checkov/cloudformation/parser/__init__.py
- checkov/cloudformation/parser/cfn_yaml.py
- tests/cloudformation/parser/test_cfn_json.py
- tests/cloudformation/parser/tfplan.json
Fixes #1887, #1903, #2046, #1257
Looking at the PR #2085 by @njgibbon it kept me thinking. Why not go a bit deeper and intercept the original error and that's what I did. But I agree we should dive a bit deeper in identifying, which kind of file we have and not blindly try to parse it.
Additionally I changed the file loading for CFN files, which results in ~40% speed increase 🚀
> skip Null value errors for CFN templates

- checkov/terraform/graph_builder/variable_rendering/safe_eval_functions.py
Replace the warning of `got a substring with double underscore, which is not allowed` with `debug`.
Resolves https://github.com/bridgecrewio/checkov/issues/2082
> Convert double underscore warning to debug

- checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py
- checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
Fixes 2 platform integrations that did not use the Prisma auth token when fetching data.
> use prisma auth token for fetching data

- checkov/arm/base_resource_check.py
- checkov/arm/base_resource_value_check.py
- checkov/arm/checks/resource/MariaDBSSLEnforcementEnabled.py
- checkov/arm/checks/resource/MySQLServerSSLEnforcementEnabled.py
- checkov/arm/checks/resource/PostgreSQLServerSSLEnforcementEnabled.py
- checkov/common/util/data_structures_utils.py
- tests/arm/checks/resource/example_MariaDBSSLEnforcementEnabled/FAILED.json
- tests/arm/checks/resource/example_MariaDBSSLEnforcementEnabled/FAILED_2.json
- tests/arm/checks/resource/example_MariaDBSSLEnforcementEnabled/PASSED.json
- tests/arm/checks/resource/test_MariaDBSSLEnforcementEnabled.py
- tests/common/utils/test_data_structures_utils.py
Fixes #432 
- added the missing `CKV_AZURE_47` check for ARM
- fixed the `BaseResourceValueCheck` class for ARM and without using `dpath`
- also adjusted `CKV_AZURE_28` & `CKV_AZURE_28` to use the `BaseResourceValueCheck` class
- adjusted `find_in_dict()` to also handle index search and couple of exception more gracefully
> Fix arm base resource value check

- checkov/terraform/checks/resource/aws/CloudfrontDistributionEncryption.py
handle a missing required field in CloudFront Distribution gracefully
> fix issue with missing viewer_protocol_policy

- checkov/terraform/module_loading/module_finder.py
The log warning is confusing - for external modules, it says "Failed to download module" even though it never tries.
[While some may count this as a failure](https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/baby-yoda-old-yoda-1574103229.jpg?crop=0.486xw:0.973xh;0.514xw,0&resize=480:*), we should be more clear.
> Clarify log message when module download is skipped and download-external-modules is false

- checkov/common/bridgecrew/integration_features/features/fixes_integration.py
This fixes an issue where the absolute path to read the file to send to the fixes API was being incorrectly calculated on Windows, which made the fixes logic not work
Example scan file path: `d:\Dev\bridgecrew\terragoat\terraform\aws\s3.tf`
File path that the fixes logic tries to read: `d:\\Dev\\bridgecrew\\terragoat\\Dev\\bridgecrew\\terragoat\\terraform\\aws\\s3.tf`
Calculating abs path isn't necessary here anyways, as each record already has it.
> Fixes - use the record absolute file path instead of recalculating it

- checkov/terraform/module_loading/loaders/versions_parser.py
- tests/terraform/module_loading/loaders/test_version_parser.py
Not 100% sure, but this should fix one of the regex issues... I hope 😄
> fix inefficient version regex

- checkov/terraform/checks/resource/gcp/GoogleComputeBlockProjectSSH.py
- checkov/terraform/checks/resource/gcp/GoogleComputeDefaultServiceAccount.py
- checkov/terraform/checks/resource/gcp/GoogleComputeDefaultServiceAccountFullAccess.py
- checkov/terraform/checks/resource/gcp/GoogleComputeExternalIP.py
- checkov/terraform/checks/resource/gcp/GoogleComputeIPForward.py
- checkov/terraform/checks/resource/gcp/GoogleComputeInstanceOSLogin.py
- checkov/terraform/checks/resource/gcp/GoogleComputeSerialPorts.py
- checkov/terraform/checks/resource/gcp/GoogleComputeShieldedVM.py
- tests/terraform/checks/resource/gcp/test_GoogleComputeBlockProjectSSH.py
- tests/terraform/checks/resource/gcp/test_GoogleComputeDefaultServiceAccount.py
- tests/terraform/checks/resource/gcp/test_GoogleComputeDefaultServiceAccountFullAccess.py
- tests/terraform/checks/resource/gcp/test_GoogleComputeExternalIP.py
- tests/terraform/checks/resource/gcp/test_GoogleComputeIPForward.py
- tests/terraform/checks/resource/gcp/test_GoogleComputeInstanceOSLogin.py
- tests/terraform/checks/resource/gcp/test_GoogleComputeSerialPorts.py
- tests/terraform/checks/resource/gcp/test_GoogleComputeShieldedVM.py
Adds support for `google_compute_instance_template` and `google_compute_instance_from_template` to checks for `google_compute_instance`.
> Add instance_template and instance_from_template to supported resources

- checkov/arm/parser/cfn_yaml.py
- checkov/cloudformation/parser/__init__.py
- checkov/cloudformation/parser/cfn_yaml.py
- checkov/kubernetes/parser/k8_json.py
- checkov/kubernetes/parser/k8_yaml.py
- checkov/serverless/parsers/parser.py
- tests/arm/parser/examples/json/mariadb.json
- tests/arm/parser/examples/json/normal.json
- tests/arm/parser/test_cfn_yaml.py
- tests/kubernetes/parser/examples/json/mongo-pod.json
- tests/kubernetes/parser/examples/json/normal.json
- tests/kubernetes/parser/examples/yaml/busybox.yaml
- tests/kubernetes/parser/examples/yaml/normal.yaml
- tests/kubernetes/parser/test_k8_json.py
- tests/kubernetes/parser/test_k8_yaml.py
I added for ARM, K8s JSON + YAML, CFN and SLS a content check before the parsing start, which stops them for blindingly trying to parse everything, especially painful, when the repo has a lot of non IaC JSON files.
@njgibbon you will be probably also interested in this 😉
> skip parsing file when wrong content

- checkov/common/parsers/json/__init__.py
This can happen when reading a file with different or invalid byte marks. The exception is not handled and the runner crashes.
> Handle UnicodeDecodeError in JSON parser

- checkov/terraform/module_loading/loaders/registry_loader.py
Hello 🙂,
Often you need to do `os.path.join` so that paths work regardless of underlying Operating System.
However, URL / FQDN are platform agnostic and always use `/`. So, just a little oversight here.
**Fixes**
* https://github.com/bridgecrewio/checkov/issues/2098
**License**
> Fix - External TF Registry Downloads on Windows

- checkov/terraform/checks/graph_checks/azure/CognitiveServicesCustomerManagedKey.yaml
- checkov/terraform/checks/resource/azure/CognitiveServicesDisablesPublicNetwork.py
- tests/terraform/checks/resource/azure/test_CognitiveServicesDisablesPublicNetwork.py
- tests/terraform/graph/checks/resources/AzureCognitiveServicesCustomerManagedKey/expected.yaml
- tests/terraform/graph/checks/resources/AzureCognitiveServicesCustomerManagedKey/main.tf
These two policies are based on this resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account
And are based on the checks for other similar services.
> Added two checks for Azure Cognitive Services

- checkov/terraform/module_loading/loaders/git_loader.py
- tests/terraform/module_loading/test_registry.py
Resolves https://github.com/bridgecrewio/checkov/issues/2136
This fix prevents the module source `git::ssh://git@github.com/<<org>>>/<<repo>>...`
To become the following command: `git clone -v --depth=1 ssh://github.com/<<org>>>/<<repo>>` 
and enforce it to be the following: `git clone -v --depth=1 ssh://git@github.com/<<org>>>/<<repo>>`
> Fix loading git modules with git@github.com

- checkov/terraform/checks/resource/azure/AppGatewayWAFACLCVE202144228.py
- tests/terraform/checks/resource/azure/example_AppGatewayWAFACLCVE202144228/main.tf
- tests/terraform/checks/resource/azure/test_AppGatewayWAFACLCVE202144228.py
added a check to look for the log4shell mitigation in the Azure Application Gateway firewall.
> add CKV_AZURE_134 to check for log4shell prevention in Application Gateway WAF

- checkov/kubernetes/checks/resource/k8s/TillerService.py
- checkov/kubernetes/graph_builder/local_graph.py
- checkov/kubernetes/kubernetes_utils.py
* Ensure metadata object is a dictionary
* TillerService check - Ensure `labels` and `spec` attributes are dictionaries 
> K8 graph creation and check safeguards

- checkov/terraform/checks/resource/aws/EBSDefaultEncryption.py
- checkov/terraform/checks/resource/aws/IAMPolicyAttachedToGroupOrRoles.py
- checkov/terraform/checks/resource/base_resource_negative_value_check.py
- checkov/terraform/checks/resource/base_resource_value_check.py
- tests/terraform/checks/resource/aws/example_EBSDefaultEncryption/main.tf
- tests/terraform/checks/resource/aws/example_IAMPolicyAttachedToGroupOrRoles/iam.tf
- tests/terraform/checks/resource/aws/test_EBSDefaultEncryption.py
- tests/terraform/checks/resource/aws/test_IAMPolicyAttachedToGroupOrRoles.py
Originally I wanted to migrate a check to  use `BaseResourceNegativeValueCheck`, but then I realized that the current `BaseResourceValueCheck` and `BaseResourceNegativeValueCheck` handle the usage of `null` values incorrectly, which is quite common in Terraform plans, but can also be used in normal template.
> add Terraform attribute null case behaviour

- checkov/common/bridgecrew/platform_integration.py
- checkov/terraform/context_parsers/base_parser.py
- tests/terraform/context_parsers/test_base_parser.py
Fixes #1146 
The issue was that we messed up the computation of the end line number of a resource, if a closing curly bracket is placed before an opening one, this can happen when the Terraform `merge()` function is used. This fix makes it slower, but I also extracted the computation of the `filtered_line_numbers` so it is only done once and this saves much more time, then the extra `count()` computation 💪 also improved some other smaller parts, which result in faster context parsing.
> fix computation of end line number

- checkov/terraform/checks/resource/azure/AKSApiServerAuthorizedIpRanges.py
- checkov/terraform/checks/resource/base_resource_value_check.py
- checkov/terraform/checks/resource/gcp/GoogleSubnetworkLoggingEnabled.py
- tests/terraform/checks/resource/azure/example_AKSApiServerAuthorizedIpRanges/main.tf
- tests/terraform/checks/resource/azure/test_AKSApiServerAuthorizedIpRanges.py
- tests/terraform/checks/resource/gcp/example_GoogleSubnetworkLoggingEnabled/main.tf
- tests/terraform/checks/resource/gcp/test_GoogleSubnetworkLoggingEnabled.py
- tests/terraform/runner/test_plan_runner.py
Fixes #1339
- adjusted the evaluation of empty lists to be a missing block, which is very typical in TF plan <- will result in much more checks to flag resources to be not complaint, had to adjust one TF plan test, which flagged 7 resources not being complaint against a check
- adjusted `CKV_GCP_26` to ignore `INTERNAL_HTTPS_LOAD_BALANCER` subnets
- adjusted `CKV_AZURE_6` tests to better syntax and one test was incorrect, because you can pass an empty list for `api_server_authorized_ip_ranges`, which is the same as removing the property
> fix incorrect handling of empty lists in TF plan

- .github/workflows/codeql-analysis.yml
- checkov/common/checks/base_check.py
- checkov/terraform/checks/provider/base_check.py
- checkov/terraform/checks/provider/linode/__init__.py
- checkov/terraform/checks/provider/linode/credentials.py
- docs/6.Contribution/Contribute New Terraform Provider.md
- tests/terraform/checks/provider/aws/test_credentials.py
- tests/terraform/checks/provider/bridgecrew/test_credentials.py
- tests/terraform/checks/provider/linode/test_credentials.py
- tests/terraform/checks/provider/oci/test_credentials.py
- tests/terraform/checks/provider/openstack/test_credentials.py
When I checked PR #2135 I realized that our docs are quite old for adding a new Provider check, so I adjusted them and migrated all the provider tests to use the `hcl2` syntax.
> adjust provider tests and docs

- docs/6.Contribution/Contribute New Terraform Provider.md
Whilst using the documentation, I thought it would be easier for future contributors if the example code blocks were directly adjacent to their descriptions, so this change just reorders the code blocks and brings the provider init next to its description, leaving the consts code block next to its description.
Before:
After:
> Docs update, small reordering change

- checkov/dockerfile/base_registry.py
- tests/dockerfile/resources/wildcard_skip/Dockerfile
- tests/dockerfile/test_runner.py
Fixes an issue where a skip applied to one line would also skip "wildcard" or checks that look for missing instructions. Example:
```
>> cat Dockerfile
#checkov:skip=CKV_DOCKER_1: I like port 22
EXPOSE 22
>> ckv -f Dockerfile
| (__| | | |  __/ (__|   < (_) \ V /
\___|_| |_|\___|\___|_|\_\___/ \_/
By bridgecrew.io | version: 2.0.704
Update available 2.0.704 -> 2.0.707
Run pip3 install -U checkov to update
dockerfile scan results:
Passed checks: 0, Failed checks: 0, Skipped checks: 3
Check: CKV_DOCKER_1: "Ensure port 22 is not exposed"
SKIPPED for resource: Dockerfile.
Suppress comment: …
```
> fix skips of wildcard checks when another skip is present

- checkov/common/bridgecrew/platform_errors.py
- checkov/common/bridgecrew/platform_integration.py
- checkov/main.py
Catches an issue that can occur if the backend config for assuming the S3 upload role fails, indicating an issue with the Bridgecrew backend itself.
The error message in the S3 role response is:
```
User: arn:aws:sts::___:assumed-role/bc-integrations-api-prod/bc-integrations-api-prod is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::___:role/upload-files-to-scanners-bucket-prod-___
```
This is not caught in the error handling, and results in an infinite loop.
This PR fixes that, and also adds a little extra logging to help catch it and instruct the user on next steps (for any auth error). And, while we're at it, it explicitly handles SSL errors.
> Improve API error handling

- checkov/kubernetes/graph_builder/local_graph.py
- kubernetes/Dockerfile
- kubernetes/run_checkov.sh
From what I can gather the ownerReferences filter was there only (needs double checking) for the cronjob implementation of checkov.   I've submitted a different PR to this one to locally remove k8s objects with this metadata as part of the job as opposed to being baked into checkov.  
The positive by-product of removing this filter will be that the new checkov admission controller can then properly scan child components during a UPDATE of k8s resources.
> Remove ownerReferences filter from scan

- kubernetes/checkov-job.yaml
The current values used by the Kubernetes Job causes `OOMKilled` error. Doubling the size request and limit memory avoids it.
> Increase K8s job's memory

- checkov/cloudformation/checks/resource/aws/CloudFrontTLS12.py
- checkov/terraform/checks/resource/aws/CloudfrontTLS12.py
> Fix get_expected_value for CloudFrontTLS12.py

- checkov/terraform/checks/resource/azure/AppServiceDotnetFrameworkVersion.py
- tests/terraform/checks/resource/azure/test_AppServiceDotnetFrameworkVersion.py
Currently .NET 6.0 is the latest LTS version, therefore CKV_AZURE_80 should expect a dotnet_framework_version of v6.0.
Fixes #2209
> CKV_AZURE_80 - Update expected dotnet_framework_version to v6.0

- checkov/terraform/checks/resource/azure/NSGRulePortAccessRestricted.py
- checkov/terraform/checks/resource/azure/NSGRuleRDPAccessRestricted.py
- checkov/terraform/checks/resource/azure/NSGRuleSSHAccessRestricted.py
- checkov/terraform/checks/resource/azure/NSGRuleUDPAccessRestricted.py
- tests/terraform/checks/resource/azure/example_NSGRuleRDPAccessRestricted/main.tf
- tests/terraform/checks/resource/azure/example_NSGRuleSSHAccessRestricted/main.tf
- tests/terraform/checks/resource/azure/test_NSGRuleRDPAccessRestricted.py
- tests/terraform/checks/resource/azure/test_NSGRuleSSHAccessRestricted.py
- tests/terraform/checks/resource/azure/test_NSGRuleUDPAccessRestricted.py
- tests/terraform/graph/checks/resources/Route53ARecordAttachedResource/expected.yaml
- tests/terraform/graph/checks/resources/Route53ARecordAttachedResource/main.tf
Fixes #2211
I had to extend the `if` clause to differentiate between `destination_port_range` vs `destination_port_ranges` and `source_address_prefix` vs `source_address_prefixes`. You can only set either one of it.
Also changed the tests to the better syntax and added a ElasticBeanstalk test, because I tested something and this wasn't tested before.
> extend Azure NSG checks to handle ranges and prefixes

- checkov/terraform/checks/provider/panos/credentials.py
- tests/terraform/checks/provider/panos/resources/api_key/fail1.tf
- tests/terraform/checks/provider/panos/resources/api_key/fail2.tf
- tests/terraform/checks/provider/panos/resources/api_key/pass.tf
- tests/terraform/checks/provider/panos/resources/api_key/variables.tf
- tests/terraform/checks/provider/panos/test_credentials.py
Handle non-string api_keys for terraform panos provider.
> fixed non-string api keys

- checkov/cloudformation/graph_builder/graph_components/blocks.py
- checkov/cloudformation/graph_builder/local_graph.py
- checkov/common/graph/graph_builder/graph_components/blocks.py
- checkov/common/graph/graph_builder/local_graph.py
- tests/cloudformation/graph/graph_builder/resources/sam/template.yaml
- tests/cloudformation/graph/graph_builder/test_local_graph.py
Fixes #2228
Added an extra flag `transform_step` to indicate that the attribute change resulted from a CloudFormation `Transform` and skip a recursive update, because this would result otherwise in transforming the values for an `if` condition.
> fix SAM Globals issue with conditions

- checkov/terraform/checks/resource/aws/SecretManagerSecretEncrypted.py
- tests/terraform/checks/resource/aws/example_SecretManagerSecretEncrypted/tfplan.json
- tests/terraform/checks/resource/aws/test_SecretManagerSecretEncrypted.py
Fixes issue https://github.com/bridgecrewio/checkov/issues/2238
When creating a plan file with a `aws_secretsmanager_secret` resource that does not specify `kms_key_id`, the run would get an execption.
> Fix CKV_AWS_149 for terraform_plan

- checkov/terraform/checks/resource/aws/DBInstanceBackupRetentionPeriod.py
- checkov/terraform/checks/resource/aws/PasswordPolicyExpiration.py
- checkov/terraform/checks/resource/aws/PasswordPolicyLength.py
- checkov/terraform/checks/resource/aws/PasswordPolicyReuse.py
- checkov/terraform/checks/resource/base_resource_check.py
- checkov/terraform/checks/resource/base_resource_value_check.py
- tests/terraform/checks/resource/aws/example_DBInstanceBackupRetentionPeriod/main.tf
- tests/terraform/checks/resource/aws/test_DBInstanceBackupRetentionPeriod.py
- tests/terraform/checks/resource/aws/test_PasswordPolicyReuse.py
- tests/terraform/checks/test_base_resource_check.py
- tests/terraform/runner/test_runner.py
A lot of checks return failures if they encounter an unrendered variable. This also means that our fix engine suggests fixes for them (e.g., change `enabled = var.versioning` to `enabled = true`), which is rarely actually correct.
This PR puts some basic logic in place to check for obvious cases of unrendered variables, and updates some checks to use it. This will be the basis for future more comprehensive changes, and is based on specific feedback from one user who raised it.
> add generic check for unrendered variable and update some checks to return UNKNOWN

- checkov/terraform/checks/resource/azure/StorageAccountMinimumTlsVersion.py
A user reported an issue that this check was giving a false negative (i.e., passing) when they had a var with a default value of `null`, i.e.:
```
variable "tls" {
type = string
default = null
}
resource "azurerm_storage_account" "example" {
min_tls_version = var.tls
}
```
This is because our variable rendering logic does not handle default values of `null`, so the `scan_resource_conf` method was getting `min_tls_version = 'var.tls'` and passing the check. This is a quick fix for that issue while we work on the actual variable rendering issue.
Note that there was a UT checking for TLS 1.3 as a future proofing thing, so I just added that in here for good measure even though it's not supported yet.
By submitting this pull request, I confirm that my contribution is made under the terms of …
> explicitly check TLS types

- Pipfile
- Pipfile.lock
- setup.py
This PR resolves dependency resolution conflicts when checkov is used with cfn-lint.
> Change jsonschema version to compatible release

- checkov/terraform/checks/resource/gcp/GoogleComputeExternalIP.py
- tests/terraform/checks/resource/gcp/example_GoogleComputeExternalIP/main.tf
- tests/terraform/checks/resource/gcp/test_GoogleComputeExternalIP.py
Access_config lies inside a network_config block, it may have worked like this at one time- it doesnt now.
> GoogleComputeExternalIP - This check looked for the wrong place

- checkov/common/graph/graph_builder/graph_components/attribute_names.py
- checkov/common/graph/graph_builder/graph_components/blocks.py
- checkov/terraform/graph_builder/local_graph.py
- tests/terraform/graph/graph_builder/test_local_graph.py
Adjusted the `block_dirs_to_modules` creation to make `source_module` less ambiguous, optimally there should be only one reference now.
> fix source_module assignment for multi module references

- Pipfile
- Pipfile.lock
- checkov/kustomize/runner.py
- setup.py
Fixes #2268 
don't know why, but I had to add a `noqa` comment inside the kustomize code, because `flake8` complaint about it. locally it has no issue 🤷
> set min version for prettytable

- checkov/kustomize/runner.py
Small change to correct a bug in base vs overlay handling in the Kustomize framework.
> [Kustomize Support] Correct incorrect codepath bug for certain bases

- checkov/main.py
- docs/2.Basics/CLI Command Reference.md
Correct the environment variable used to specify a custom CA certificate bundle.
> correct the environment variable used to specify a custom CA certificate bundle

- checkov/main.py
- docs/2.Basics/CLI Command Reference.md
The [] brackets by the output implied you could do a list of outputs (-o [sarif,cli]), but the real way to have multiple outputs is multiple flags (-o sarif -o cli)
> Update output description

- checkov/common/graph/graph_builder/graph_components/blocks.py
- checkov/terraform/context_parsers/parsers/provider_context_parser.py
- checkov/terraform/graph_builder/graph_components/module.py
- tests/terraform/runner/resources/many_providers/main.tf
- tests/terraform/runner/test_runner.py
in case a provider is written as a one-liner `checkov` crashes when outputting the result.
> fix broken output when provider block is a one-liner

- checkov/cloudformation/checks/resource/aws/SecurityGroupRuleDescription.py
Without the parenthesis, the `or` condition would still run even if `rule` is not a dict. This fixes it
> Fix and/or order in SecurityGroupRuleDescription.py

- .github/workflows/build.yml
- .github/workflows/pr-test.yml
MacOS builds are failing due to 403. https://github.com/Azure/setup-helm/issues/59
> revert setup-helm GH Action to v1 for now

- checkov/common/bridgecrew/platform_integration.py
- checkov/common/util/http_utils.py
- checkov/common/vcs/base_vcs_dal.py
Extracted the `User-Agent` from the `SIGNUP_HEADER` and created a method in `http_utils` that retrieve this header.
Then we can merge existing headers with this `User-Agent` header.
> Add user agent to HTTP requests headers

- .github/workflows/build.yml
- .github/workflows/coverage.yaml
- .github/workflows/pipenv-update.yml
- .github/workflows/pr-test.yml
replace the outdated pipenv action by just installing it manually, looks like that installing `pipenv` changed with new Win Server version 2022. Other actions in the marketplace are doing the same, so I don't see any need to use them at the moment.
> remove pipenv version

- checkov/terraform/checks/graph_checks/aws/ALBProtectedByWAF.yaml
- tests/terraform/graph/checks/resources/ALBProtectedByWAF/expected.yaml
- tests/terraform/graph/checks/resources/ALBProtectedByWAF/main.tf
Fixes #2326 
NLBs and Gateway LBs can't have a WAF associated with.
> let CKV2_AWS_28 pass when nlb or gateway lb

- checkov/common/parsers/json/decoder.py
We created a custom wrapper for DecodeError, and this line doesn't pass the correct params for the our wrapper
Fixes #2332
> Fix bad DecodeError instance creation

- checkov/terraform/checks/resource/azure/PostgreSQLFlexiServerGeoBackupEnabled.py
- tests/terraform/checks/resource/azure/example_PostgreSQLFlexiServerGeoBackupEnabled/main.tf
- tests/terraform/checks/resource/azure/test_PostgreSQLFlexiServerGeoBackupEnabled.py
Hello,
Implementing check for Azure PostgreSQL FlexiServer GeoBackup Enabled in terraform.
Terraform Docs:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server
Note:
If we have not pass the "geo_redundant_backup_enabled" argument in terraform then the check fails, as by default it will not provide backup facility.
If we have pass the "geo_redundant_backup_enabled" argument in terraform with value "false" in terraform template then the check fails, means we have turned off the backup facility.
If we have pass the "geo_redundant_backup_enabled" argument in terraform with value "true" in terraform template then the check passed, means we have turned on the backup facility.
License
By submitting this pull request, I confirm that my …
> AZURE TF Check - CKV_AZURE_136

- checkov/terraform/graph_builder/local_graph.py
Fixes #2288
This somehow happens, when a relative recursive path is used for a module and also other external modules are used, which were not downloaded. Had to debug it via the good old way of adding `print` statements into the installed lib 🙈 😄 that's why I didn't add any test.
> adjust module dep number assignment

- checkov/common/output/report.py
- checkov/terraform/plan_parser.py
- checkov/terraform/plan_runner.py
- tests/terraform/runner/resources/plan_with_resource_reference/tfplan_graph.json
- tests/terraform/runner/test_plan_runner.py
Fixes #2327
I added an extra attribute for the references, which are only available in a TF plan. This is then leveraged for the graph checks to make the connection. The previous approach only added missing attributes and now it will add a reference if available.
> Add tf plan ref

- checkov/github/dal.py
There was a redundant `/` in the github api endpoint for branch protection and it always return 404
> Fix branch protection endpoint

- docs/4.Integrations/GitLab CI.md
The colored example does not generate a junit xml file. Uploading the artifact will fail for this pipeline.
> Fix colored example

- checkov/terraform/checks/resource/gcp/GoogleCloudMySqlLocalInfileOff.py
- checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogCheckpoints.py
- checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogConnection.py
- checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogDisconnection.py
- checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogLockWaits.py
- checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogMinDuration.py
- checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogMinMessage.py
- checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogTemp.py
- checkov/terraform/checks/resource/gcp/GoogleCloudSqlServerContainedDBAuthentication.py
- checkov/terraform/checks/resource/gcp/GoogleCloudSqlServerCrossDBOwnershipChaining.py
Ensure `database_version` attribute is string before inspecting it
> Ensure database_version attribute is a string

- checkov/common/bridgecrew/platform_integration.py
- checkov/common/bridgecrew/vulnerability_scanning/integrations/docker_image_scanning.py
- checkov/common/bridgecrew/vulnerability_scanning/integrations/package_scanning.py
- checkov/sca_package/output.py
- checkov/sca_package/runner.py
- tests/common/bridgecrew/vulnerability_scanning/conftest.py
- tests/common/bridgecrew/vulnerability_scanning/integrations/test_package_scanning.py
- tests/sca_package/test_runner.py
- add extra info to the SCA report
- add flag to enable scanning of `package.json` even, if the lock file exists
> add extra info to the report and add flag to enable package.json scan

- checkov/terraform/checks/resource/azure/AKSApiServerAuthorizedIpRanges.py
- tests/terraform/checks/resource/azure/example_AKSApiServerAuthorizedIpRanges/main.tf
- tests/terraform/checks/resource/azure/test_AKSApiServerAuthorizedIpRanges.py
The api_server_authorized_ip_ranges can and should only be set if private_cluster_enabled is false. Azure won't allow setting the api_server_authorized_ip_ranges if the cluster is private.
*This is my first experience with writing a policy, any notes or approvements are welcome!*
> Only validate api_server_authorized_ip_ranges if cluster is not private

- checkov/common/bridgecrew/platform_integration.py
- checkov/common/runners/base_runner.py
- checkov/main.py
Enabled persisting external modules using an optional param `included_paths` for the `filter_ignored_paths` method, and add the external modules dir to it when persisting the repository.
> Persist external modules file with to bridgecrew integration

- checkov/github/dal.py
Set the github org name by setting the `GITHUB_ORG` environment variable.
> Set Github org using env variable

- checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
- tests/common/integration_features/test_suppressions_integration.py
I became worried that our logic for matching --repo-id with platform suppressions did not properly account for Prisma org names (all numeric). There is no issue, but I added some tests to cover it and did a small refactor so that we do not recompile a regex repeatedly.
> add tests covering Prisma integrations

- checkov/common/bridgecrew/vulnerability_scanning/integrations/docker_image_scanning.py
- checkov/common/bridgecrew/vulnerability_scanning/integrations/package_scanning.py
- tests/common/bridgecrew/vulnerability_scanning/integrations/test_package_scanning.py
Streamlined the SCA output to use camelCase for the CICD block
> adjust CICD details output to use camelCase

- checkov/terraform/checks/resource/__init__.py
- checkov/terraform/checks/resource/panos/InterfaceMgmtProfileNoHTTP.py
- checkov/terraform/checks/resource/panos/__init__.py
- tests/terraform/checks/resource/panos/example_InterfaceMgmtProfileNoHTTP/main.tf
- tests/terraform/checks/resource/panos/test_InterfaceMgmtProfileNoHTTP.py
First resource check for PAN-OS Terraform provider. Ensures that plain-text HTTP is not enabled for managing PAN-OS firewalls, we only want to see HTTPS being used for firewall management.
> PAN-OS resource check for http in mgmt profile

- checkov/terraform/checks/resource/gcp/GoogleComputeFirewallUnrestrictedIngress3306.py
- tests/terraform/checks/resource/gcp/example_GoogleComputeFirewallUnrestrictedIngress3306/main.tf
- tests/terraform/checks/resource/gcp/test_GoogleComputeFirewallUnrestrictedIngress3306.py
This PR adds a new GCP terraform check for unrestricted mysql firewall rules. Basically, any firewall rule with an `allow` block that has `"0.0.0.0/0"` in its `source_ranges`. 
For ingress rules, one of `source_ranges`, `source_tags` or `source_service_accounts` is required per the tf [docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_firewall#source_ranges). 
The only tests that failed locally are unrelated to this PR:
```
=============================== short test summary info =========================================
FAILED tests/kustomize/test_runner.py::TestRunnerValid::test_record_relative_path_with_direct_oberlay - TypeError: …
```
> CKV_GCP_88 - Unrestricted mysql fw

- checkov/terraform/checks/resource/gcp/VertexAIPrivateInstance.py
- tests/terraform/checks/resource/gcp/example_VertexAIPrivateInstance/main.tf
- tests/terraform/checks/resource/gcp/test_VertexAIPrivateInstance.py
This PR adds a new GCP check for public Vertex AI instances. These instances are the underlining compute that powers the notebooks and are __by default public__. 
The check logic and tests accounts for three scenarios:
- If the `no_public_ip` setting does not exist - Fail
- If the `no_public_ip` setting exists but is set to `false` - Fail
- If the `no_public_ip` setting exists and is set to `true` - Pass
> CKV_GCP_89 - Public vertex ai notebook check

- checkov/common/bridgecrew/vulnerability_scanning/integrations/docker_image_scanning.py
- checkov/terraform/checks/resource/aws/LaunchConfigurationEBSEncryption.py
- tests/common/bridgecrew/vulnerability_scanning/integrations/test_docker_image_scanning.py
- tests/terraform/checks/resource/aws/example_LaunchConfigurationEBSEncryption/main.tf
- tests/terraform/checks/resource/aws/test_LaunchConfigurationEBSEncryption.py
Fixed an issue in CKV_AWS_8, when using the old way of defining a block and it is empty by default
> fix CKV_AWS_8

- checkov/terraform/checks/resource/gcp/DataflowPrivateJob.py
- tests/terraform/checks/resource/gcp/example_DataflowPrivateJob/main.tf
- tests/terraform/checks/resource/gcp/test_DataflowPrivateJob.py
This PR adds a check for private dataflow jobs. By default Dataflow jobs in GCP are made public (aka the compute instances have public IPs.)
This check looks for 3 scenarios:
- If `ip_configuration` does not exist - Fail
- If `ip_configuration` exists but is set to `WORKER_IP_PUBLIC` - Fail
- If `ip_configuration`exists but is set to `WORKER_IP_PRIVATE` - PASS
> CKV_GCP_94 - GCP Private dataflow job check

- checkov/terraform/checks/resource/azure/AKSLocalAdminDisabled.py
- tests/terraform/checks/resource/azure/example_AKSLocalAdminDisabled/main.tf
- tests/terraform/checks/resource/azure/test_AKSLocalAdminDisabled.py
Custom Policy id: CKV_AZURE_141
Custom Policy name: Ensure AKS local admin account is disabled
Custom Policy IaC type: terraform
Custom Policy type and provider: azurerm
IaC configuration documentation (If available): https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#local_account_disabled
Any additional information that would help other members to better understand the check: 
Per MS doc, "Even when enabling RBAC or Azure Active Directory integration, --admin access still exists, essentially as a non-auditable backdoor option." -- https://docs.microsoft.com/en-us/azure/aks/managed-aad#disable-local-accounts
> add terraform azure check AKSLocalAdminDisabled

- checkov/terraform/checks/resource/gcp/MemorystoreForRedisAuthEnabled.py
- tests/terraform/checks/resource/gcp/example_MemorystoreForRedisAuthEnabled/main.tf
- tests/terraform/checks/resource/gcp/test_MemorystoreForRedisAuthEnabled.py
This PR adds a GCP terraform check for "Ensure Memorystore for Redis has AUTH enabled". The AUTH configuration for Memorystore for redis is not enabled by default, but when enabled, "incoming client connections must authenticate in order to connect". We generally recommend this feature be enabled to limit who/what can connect to redis databases.
This check accounts for 3 scenarios:
- If `auth_enabled` does not exist - FAIL
- If `auth_enabled` exists but is set to `false` - FAIL
- If `auth_enabled` exists but is set to `true` - PASS
You can read more about the AUTH feature [here](https://cloud.google.com/memorystore/docs/redis/auth-overview)
> CKV_GCP_95 - Ensure Memorystore for Redis has AUTH enabled

- Pipfile
- Pipfile.lock
- setup.py
> cap bc-python-hcl2 package version to 0.3.28

- Pipfile
- Pipfile.lock
- setup.py
Bumping the parser package after reverting the changes in bc-python-hcl2 so the parser keeps wrapping attributes in lists (as it was before).
> bump bc-pyhton-hcl2 to 0.3.30

- checkov/cloudformation/checks/resource/aws/ECRPolicy.py
- checkov/cloudformation/graph_builder/variable_rendering/renderer.py
cfn variable rendering - check that all the values from the `values_list` are string before using them in `join` and getting exceptions.
ECRPolicy check - fix edge-case of properties are from NoneType and then `AttributeError` are thrown for getting the `properties.keys`
> Fix bugs in cfn variable rendering and ECRPolicy check

- checkov/terraform/checks/resource/azure/MLCCLADisabled.py
- tests/terraform/checks/resource/azure/example_MLCCLADisabled/MLCCLADisabled.tf
- tests/terraform/checks/resource/azure/test_MLCCLADisabled.py
Custom Policy ID: CKV_AZURE_142
Custom Policy name: Ensure Machine Learning Compute Cluster Local Authentication is disabled
Custom Policy IaC type: Terraform
Custom Policy type and provider: AzureRM
IaC configuration documentation (If available): https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/machine_learning_compute_cluster#local_auth_enabled
Sample Terraform configuration file: N/A
Any additional information that would help other members to better understand the check: 
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-setup-authentication
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-attach-compute-clust …
> Ensure Machine Learning Compute Cluster Local Authentication is disabled

- checkov/cloudformation/graph_builder/variable_rendering/renderer.py
go over a copy of the vertex attribute for not getting runtime error of changing the dictionary size during iteration.
> fix in cfn variable renderring

- checkov/common/graph/graph_builder/graph_components/blocks.py
- checkov/terraform/graph_builder/graph_components/blocks.py
- tests/terraform/graph/checks_infra/attribute_solvers/within_solver/WildcardWithin.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/within_solver/test_solver.py
- tests/terraform/graph/resources/array_test/main.tf
Fixes an issue where the following HCL:
`arr = ["abc"]`
does not get considered as an array for the purposes of graph attribute building. We want it to come away with two attributes:
`arr = ['abc']` and
`arr.0 = 'abc'`, but the `.#` keys do not get added like they do when the array is length 2+.
The test I added tests a specific type of policy case, but also implicitly tests this functionality. Before this change, the `pass1` resource would fail the test policy.
> do not strip arrays of length 1 twice

- README.md
The `--rm` switch to docker run cleans up the ephemeral container after its run. Otherwise _spent_ containers are left behind -- which are not reused. This does not impact the container image download/cache.
> docker run ephemeral container automatic cleanup

- checkov/terraform/checks/graph_checks/aws/Route53ARecordAttachedResource.yaml
- tests/terraform/graph/checks/resources/Route53ARecordAttachedResource/expected.yaml
- tests/terraform/graph/checks/resources/Route53ARecordAttachedResource/main.tf
Currently, the filter only checks for aws_lb and aws_elb. But aws_alb is a correct resource name as well as it's an alias for aws_lb
> Fix Route53 filter to include aws_alb as well

- checkov/terraform/checks/resource/aws/AppLoadBalancerTLS12.py
- tests/terraform/checks/resource/aws/example_AppLoadBalancerTLS12/main.tf
- tests/terraform/checks/resource/aws/test_AppLoadBalancerTLS12.py
Fixes #2441 this can happen when using the Terraform plan runner, so I I mimicked it by adding an empty `redirect` block.
> check if redirect block is a dict

- checkov/terraform/checks/graph_checks/gcp/GCPContainerRegistryReposAreNotPubliclyAccessible.yaml
- tests/terraform/graph/checks/resources/GCPContainerRegistryReposAreNotPubliclyAccessible/expected.yaml
- tests/terraform/graph/checks/resources/GCPContainerRegistryReposAreNotPubliclyAccessible/main.tf
- tests/terraform/graph/checks/test_yaml_policies.py
This PR is a new graph check for GCP [Container Registry repositories](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_registry).
This is a good scenario for a graph check in checkov. Container registry terraform resources themselves only support two keys `location` and `project`. The way to make them public is via a GCS bucket IAM resource like `google_storage_bucket_iam_member`, but if we only check for that resource, it would technically be a GCS public bucket check.
I think it's important to keep them separate so that the remediation guidance walks through the risks of public container registries. With a graph check, we can …
> CKV2_GCP_9 - Ensure that Container Registry repositories are not anonymously or publicly accessible

- checkov/kubernetes/parser/k8_yaml.py
- tests/kubernetes/parser/examples/yaml/helm.yaml
- tests/kubernetes/parser/examples/yaml/helm2.yaml
- tests/kubernetes/parser/test_k8_yaml.py
Prevents HELM template files which have not gone through the HELM runner being picked up directly by the kubernetes runner.
Previously this would cause the kubernetes runner to fail at a yaml.loads due to {{- HELM variable/markup syntax within the files.
> Exclude raw HELM templates from Kubernetes runner

- checkov/terraform/checks/resource/panos/PolicyLogForwarding.py
- tests/terraform/checks/resource/panos/example_PolicyLogForwarding/main.tf
- tests/terraform/checks/resource/panos/test_PolicyLogForwarding.py
A resource check for PAN-OS Terraform provider for security policy rules. This one ensures that security policy rules have a log forwarding profile enabled, such that logs are collected at Panorama and/or an external logging server. Log forwarding can be set in two different resource types, both are covered by this check.
> PAN-OS resource check for log forwarding profiles

- tests/terraform/checks/resource/gcp/test_ArtifactRegistryPrivateRepo.py
Looks like I missed the word `Test` in the unit test class. It doesn't affect the tests passing but it's more of a stylistic thing.
> Missing "Test" in unit test

- checkov/terraform/checks/resource/gcp/GCPCloudRunPrivateService.py
- tests/terraform/checks/resource/gcp/example_GCPCloudRunPrivateService/main.tf
- tests/terraform/checks/resource/gcp/test_GCPCloudRunPrivateService.py
This PR adds a new checkov check for public Cloud Run services. Ideally Cloud Run services would not be exposed for unauthenticated access and instead a loud balancer would be used.
> CKV_GCP_102 - Ensure that GCP Cloud Run services are not anonymously or publicly accessible

- checkov/common/bridgecrew/integration_features/features/policy_metadata_integration.py
In `_handle_customer_run_config()`, custom policies are stored in `run_config['customPolicies']` instead of in `run_config['policyMetadata']`.
This PR adds guidelines for custom policies to `self.check_metadata` in the same way that `_handle_public_metadata()` adds guidelines to `self.check_metadata` resulting in those guidelines being displayed in the output of the `checkov` command.
Addresses: https://github.com/bridgecrewio/checkov/issues/2433
> display guidelines for custom policies

- checkov/common/bridgecrew/platform_integration.py
- checkov/main.py
Prior to this pull request:
API URLs were setup in both `__init__()` and `setup_bridgecrew_credentials()`
(as `setup_bridgecrew_credentials()` is where/when parameters are first available)
This introduced the potential for a URL to be setup in one but not the other.
Specifically, `guidelines_api_url` was recently overlooked in `setup_bridgecrew_credentials()`,
resulting in `Failed to get the guidelines from` warnings when using Prisma Cloud Code Security.
With this pull request:
`setup_api_urls()` consolidates url setup (aka dry)
`self.bc_api_url` is used to store the default api url for the Bridgecrew platform
This pull request also updates the cli help with a consistent reference for "Prisma Cloud Access Keys".
By submitting this pull request, I confirm that my contribution is made …
> consolidate url setup

- checkov/terraform/checks/resource/azure/MLComputeClusterMinNodes.py
- tests/terraform/checks/resource/azure/example_MLComputeClusterMinNodes/main.tf
- tests/terraform/checks/resource/azure/test_MLComputeClusterMinNodes.py
Custom Policy id - CKV_AZURE_150
Custom Policy name - "Ensure Machine Learning Compute Cluster Minimum Nodes Set To 0"
Custom Policy IaC type - terraform
Custom Policy type and provider - azurerm
IaC configuration documentation (If available) - https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/machine_learning_compute_cluster#min_node_count
Any additional information that would help other members to better understand the check - https://docs.microsoft.com/en-us/azure/machine-learning/concept-vulnerability-management#compute-clusters
Per MS doc, if min nodes is set to 0 then not only is it a cost-saving configuration but it also allows the VMs in …
> add tf azure check for ensuring ml cluster min nodes set to 0

- checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py
- tests/terraform/graph/checks_infra/attribute_solvers/exists_solver/TagEnvironmentExistsAll.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/exists_solver/test_solver.py
In case we have an empty list of resource types, we will apply attribute queries on all the `resource` vertices in the graph.
> Support empty resource types for YAML queries

- checkov/terraform/checks/resource/aws/AbsNACLUnrestrictedIngress.py
- tests/terraform/checks/resource/aws/example_NetworkACLUnrestrictedIngress3389/main.tf
Support the case when ports are written as strings instead of integers, which causes exception when trying to compare the port ranges.
> Fix types comparison in AbsNACLUnrestrictedIngress check

- checkov/common/bridgecrew/integration_features/features/fixes_integration.py
- checkov/common/bridgecrew/integration_features/features/policy_metadata_integration.py
Fixes an issue where custom policy IDs were getting sent to the fixes API as None, resulting in an error
> fix metadata mapping for custom policies

- checkov/terraform/checks/resource/aws/AbsNACLUnrestrictedIngress.py
- tests/terraform/checks/resource/aws/example_NetworkACLUnrestrictedIngress20/main.tf
- tests/terraform/checks/resource/aws/example_NetworkACLUnrestrictedIngress21/main.tf
- tests/terraform/checks/resource/aws/example_NetworkACLUnrestrictedIngress22/main.tf
- tests/terraform/checks/resource/aws/example_NetworkACLUnrestrictedIngress3389/main.tf
- tests/terraform/checks/resource/aws/test_NetworkACLUnrestrictedIngress20.py
- tests/terraform/checks/resource/aws/test_NetworkACLUnrestrictedIngress21.py
- tests/terraform/checks/resource/aws/test_NetworkACLUnrestrictedIngress22.py
- tests/terraform/checks/resource/aws/test_NetworkACLUnrestrictedIngress3389.py
Fixes #2542 
when `protocol` allows everything then from and to port don't need to be set.
> fix NACL checks

- Pipfile
- Pipfile.lock
- setup.py
Pinned the `hcl2` version to make upgrades more controllable.
> pin bc-python-hcl2 version

- checkov/terraform/checks/resource/aws/AbsNACLUnrestrictedIngress.py
- tests/terraform/checks/resource/aws/example_NetworkACLUnrestrictedIngress3389/main.tf
Handled cases where input for AbsNACLUnrestrictedIngress check can be different - 
1. No ports exist
2. ingress is an array.
> Fix AbsNACLUnrestrictedIngress check

- checkov/kubernetes/checks/resource/base_container_check.py
- checkov/terraform/checks/resource/aws/AbsNACLUnrestrictedIngress.py
- tests/kubernetes/checks/example_AllowedCapabilitiesSysAdmin/pod-FAILED2.yaml
- tests/kubernetes/checks/test_AllowedCapabilitiesSysAdmin.py
- tests/terraform/checks/resource/aws/example_NetworkACLUnrestrictedIngress3389/main.tf
- tests/terraform/checks/resource/aws/example_NetworkACLUnrestrictedIngress3389/variables.tf
- tests/terraform/checks/resource/aws/test_NetworkACLUnrestrictedIngress3389.py
1. Support k8s yaml with no containers.
2. Support invalid ports (from un-rendered variables)
> Fix checks edge cases

- checkov/terraform/checks/resource/gcp/DataprocPublicIpCluster.py
- tests/terraform/checks/resource/gcp/example_DataprocPublicIpCluster/main.tf
- tests/terraform/checks/resource/gcp/test_DataprocPublicIpCluster.py
This PR adds a new Checkov check for Public IP Dataproc clusters. By default Dataproc clusters have public IPs.
> CKV_GCP_103 - Ensure Dataproc Clusters do not have public IPs

- checkov/kubernetes/checks/resource/k8s/RootContainers.py
- checkov/kubernetes/checks/resource/k8s/RootContainersHighUID.py
- tests/kubernetes/checks/example_RootContainers/rootContainersFAILED.yaml
- tests/kubernetes/checks/example_RootContainersHighUID/rootContainersHighUIDFAILED.yaml
- tests/kubernetes/checks/test_RootContainers.py
- tests/kubernetes/checks/test_RootContainersHighUID.py
Validate that the runAsUser attribute is an integer before comparing it to a number.
> Kubernetes RootContainers validate runAsUser is an integer

- Pipfile
- Pipfile.lock
- checkov/arm/checks/resource/NSGRulePortAccessRestricted.py
- checkov/common/checks/base_check_registry.py
- checkov/common/output/record.py
- tests/terraform/graph/variable_rendering/expected_data.py
- tests/terraform/parser/test_hcl2_load_assumptions.py
- bumped the `hcl2` version to latest one and adjusted some tests, the new output looks better I would say 😄 
- I also limited the `networkx` version, so the newest release won't be picked up, because they officially don't support Python 3.7 anymore
- some other minor adjustments, which I stumbled upon
> bump hcl2 version

- checkov/main.py
Removes an argument warning message that got added during the early portion of severities enhancements, that is actually incorrect.
> remove unneeded and incorrect warning

- checkov/common/graph/graph_builder/graph_components/blocks.py
- tests/cloudformation/graph/graph_builder/resources/sam/template.yaml
- tests/cloudformation/graph/graph_builder/test_local_graph.py
needed to move the block, because otherwise we will have an attribute named `self` in the `dict`, which results in an error in `networkx`
> move self attribute logic before inner attribute

- checkov/terraform/checks/resource/panos/NetworkIPsecProtocols.py
- tests/terraform/checks/resource/panos/example_NetworkIPsecProtocols/main.tf
- tests/terraform/checks/resource/panos/test_NetworkIPsecProtocols.py
A resource check for PAN-OS Terraform provider to ensure use of secure protocols for IPsec VPNs. It can be configured in two different resource types, both are covered by this check.
> PAN-OS resource check for IPsec protocols

- github_action_resources/checkov-problem-matcher-softfail.json
When having a failed check, modify the severity from warning to error.
> Modify severity of problemMatcher

- checkov/terraform/checks/resource/panos/ZoneProtectionProfile.py
- tests/terraform/checks/resource/panos/example_ZoneProtectionProfile/main.tf
- tests/terraform/checks/resource/panos/test_ZoneProtectionProfile.py
A resource check for PAN-OS Terraform provider to ensure Zone Protection Profiles are configured for each zone. This can be configured in two different resource types, both are covered by this check.
> Panos zone protection

- checkov/terraform/parser.py
No need to create a string here and then put it back into an exception. This resulted in a casting error of a `lark` parser exception.
> remove string cast of exception

- checkov/terraform/checks/resource/panos/ZoneUserIDIncludeACL.py
- tests/terraform/checks/resource/panos/example_ZoneUserIDIncludeACL/main.tf
- tests/terraform/checks/resource/panos/test_ZoneUserIDIncludeACL.py
Another check for PAN-OS. If User-ID is enabled for a zone (it is optional), an "include ACL" should be defined to provide the scope for source IP addresses used within User-ID. This can be configured in "panos_zone" or "panos_panorama_zone" resources. Both resource types are covered by this check.
> PAN-OS check for User-ID IncludeACL in Zones

- checkov/cloudformation/checks/resource/aws/ECRPolicy.py
- checkov/common/models/consts.py
- checkov/serverless/parsers/parser.py
- checkov/serverless/runner.py
- tests/serverless/runner/resources/serverless.yaml
- added a bit of code to skip `file` reference in a resource block
```yaml
resources:
Resources: ${file(./serverless.${opt:stage}.yml)} 
```
- also moved the `DEFAULT_VAR_PATTERN` to the `common` module, because I somehow had circular dependency
> skip SLS sub resource if it is a file reference

- checkov/terraform/checks/resource/alicloud/AbsSecurityGroupUnrestrictedIngress.py
refactor the check and handle edge case of wrong `port_range` values
> fix in AbsSecurityGroupUnrestrictedIngress check

- checkov/terraform/checks/resource/azure/AKSRbacEnabled.py
- tests/terraform/checks/resource/azure/test_AKSRbacEnabled.py
Recently, azurerm [2.99.0](https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v2.99.0) was published, which, in preparation for 3.0, brought some syntax changes, one of which is listed below:
***
"Data Source: `azurerm_kubernetes_cluster` - deprecated the `role_based_access_control` block in favour of `azure_active_directory_role_based_access_control` and `role_based_access_control_enabled` properties (https://github.com/hashicorp/terraform-provider-azurerm/issues/15584)"
***
This PR adds support for `role_based_access_control_enabled`.
Closes #2649
> feat: add support for terraform AKS role_based_access_control_enabled

- checkov/terraform/checks/resource/kubernetes/TillerService.py
- tests/terraform/checks/resource/kubernetes/example_TillerService/main.tf
Handle the case where the labels are not dictionary, to avoid throwing exceptions
> Fix non-dict labels in TillerService

- checkov/terraform/checks/resource/oci/AbsSecurityListUnrestrictedIngress.py
- checkov/terraform/checks/resource/oci/SecurityListUnrestrictedIngress22.py
- checkov/terraform/checks/resource/oci/SecurityListUnrestrictedIngress3389.py
- tests/terraform/checks/resource/oci/example_SecurityListUnrestrictedIngress22/main.tf
- tests/terraform/checks/resource/oci/example_SecurityListUnrestrictedIngress3389/main.tf
- tests/terraform/checks/resource/oci/test_SecurityListUnrestrictedIngress22.py
- tests/terraform/checks/resource/oci/test_SecurityListUnrestrictedIngress3389.py
Added security list checks, that allow unrestricted ingress access to port 3389 and 22
Resolves #1975, resolves #1974
> Added Oci security list checks

- checkov/logging_init.py
- checkov/main.py
Hey all, hope you're well!
Just looking at some issues to pick something up and found that there are some `INFO` logs leaking into CLI output by default.
I've found that this is due to how the logger is initialised and we need to ensure that it is done before anything else has an opportunity to run where we would like it to inherit the logging.
I am not an expert with any of this stuff so please guide me if you'd like another implementation to get the job done! For example, could import it as before and just run `init()` before some of the other imports.
Better User Experience with the cleaner CLI output and also users are less likely to raise an issue because they are being confused with DEBUG logs in the CLI output where they are not representing a functional problem - meaning less …
> Fix - Logging Init

- checkov/common/checks_infra/solvers/attribute_solvers/equals_attribute_solver.py
- tests/common/integration_features/test_custom_policies_integration.py
- tests/terraform/graph/checks_infra/attribute_solvers/equals_solver/BooleanString.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/equals_solver/test_solver.py
- tests/terraform/graph/resources/boolean_test/main.tf
Fixes an issue where custom policies with a condition like `== "false"` would fail against a Terraform attribute like `= false` due to case sensitivity in Python booleans.
> handle boolean values in graph equals check

- checkov/kubernetes/checks/resource/k8s/Seccomp.py
RIght now, if the block:
```
securityContext:
seccompProfile:
type:RunTimeDefault
```
is added to a Job, and checkov runs against this job, it will still report CKV_K8S_31 as FAILED.
In this file it is obvious that if instead, we add the annotation `seccomp.security.alpha.kubernetes.io/pod`, then checkov will not report CKV_K8S_31 as FAILED. However, this annotation is deprecated as per Kubernetes documentation: https://kubernetes.io/docs/tutorials/security/seccomp/#create-a-pod-with-a-seccomp-profile-for-syscall-auditing
So, since Job follows the spec order of Deployment, I have added it next to Deployment and StatefulSet. I have also added DaemonSet and ReplicaSet.
> Missing Job from CKV_K8S_31

- checkov/terraform/checks/resource/gcp/ArtifactRegistryPrivateRepo.py
- checkov/terraform/checks/resource/gcp/BigQueryPrivateTable.py
- checkov/terraform/checks/resource/gcp/DataprocPrivateCluster.py
- checkov/terraform/checks/resource/gcp/GCPCloudRunPrivateService.py
- checkov/terraform/checks/resource/gcp/PubSubPrivateTopic.py
Checkov will fail on some of the "check public" resource checks in GCP due to us not performing a safety check before diving into our evaluation logic. We ran into a specific scenario where nested modules broke some of checkov's checks due to:
```
TypeError: 'NoneType' object is not subscriptable
```
aka we were not checking to see if the key exists before assigning it to a variable. I didn't think this was possible since these resource keys are required, but there are scenarios where it could happen.
> Checkov breaks with nested modules

- checkov/common/checks_infra/registry.py
- checkov/runner_filter.py
- checkov/terraform/parser.py
- checkov/terraform/runner.py
Fixes #2717
I also lowered the log level for some log messages, `debug` should be more than enough 🙂
> fix freeze of checkov when TF parsing fails

- checkov/terraform/checks/resource/oci/SecurityGroupsIngressStatelessSecurityRules.py
- tests/terraform/checks/resource/oci/example_SecurityGroupsIngressStatelessSecurityRules/main.tf
- tests/terraform/checks/resource/oci/test_SecurityGroupsIngressStatelessSecurityRules.py
resolved #1972
added check to ensure OCI Network Security Groups (NSG) has stateless security rules
> Ensure security group has stateless ingress security rules

- checkov/arm/base_registry.py
- checkov/arm/runner.py
- checkov/terraform/checks/resource/alicloud/PasswordPolicyMaxLogin.py
handle the case when `type` is not in arm resource
fix edge-case in PasswordPolicyMaxLogin check
> fix in arm runner and registry

- Pipfile
- Pipfile.lock
- setup.py
Fixes #2771
Fixes #2756
The tests are in the different repos of the parsers.
> upgrade hcl2 and pycep parsers

- checkov/helm/runner.py
If the k8s runner raises an exception for a helm chart, then the exception handler is guaranteed to crash the overall checkov run:
* `shutil.move(target_dir, save_error_dir)` moves the `target_dir` `TemporaryDirectory` to another place
* When `target_dir` gets automatically cleaned up, Checkov crashes due to the resulting `No such file or directory` error
It seems like (based on the TODO on line 226) that there is more work that might happen to do something with this failed result, so for now I just commented out the whole second temp dir.
> remove unneeded move operation in helm error handler

- checkov/kubernetes/checks/resource/base_rbac_check.py
- checkov/kubernetes/checks/resource/k8s/RbacApproveCertificateSigningRequests.py
- checkov/kubernetes/checks/resource/k8s/RbacControlWebhooks.py
- tests/kubernetes/checks/example_RbacApproveCertificateSigningRequests/clusterrole-failed-1.yaml
- tests/kubernetes/checks/example_RbacApproveCertificateSigningRequests/clusterrole-failed-2.yaml
- tests/kubernetes/checks/example_RbacApproveCertificateSigningRequests/clusterrole-failed-3.yaml
- tests/kubernetes/checks/example_RbacApproveCertificateSigningRequests/clusterrole-passed-1.yaml
- tests/kubernetes/checks/example_RbacApproveCertificateSigningRequests/clusterrole-passed-2.yaml
- tests/kubernetes/checks/example_RbacControlWebhooks/clusterrole-failed-1.yaml
- tests/kubernetes/checks/example_RbacControlWebhooks/clusterrole-failed-2.yaml
- tests/kubernetes/checks/example_RbacControlWebhooks/clusterrole-passed-1.yaml
- tests/kubernetes/checks/example_RbacControlWebhooks/clusterrole-passed-2.yaml
- tests/kubernetes/checks/test_RbacApproveCertificateSigningRequests.py
- tests/kubernetes/checks/test_RbacControlWebhooks.py
- Added `base_rbac_check` as a baseline for evaluating k8s Roles & ClusterRoles for excessive RBAC permissions
- Added CKV_K8S_155: Minimize ClusterRoles that grant control over validating or mutating admission webhook 
- Added CKV_K8S_156: Minimize ClusterRoles that grant permissions to approve CertificateSigningRequests
> Add base_rbac_check for k8s along with CKV_K8S_155 & CKV_K8S_156

- checkov/secrets/runner.py
> Reduce secret scanning runner's MAX_FILE_SIZE to 5mb

- checkov/kustomize/runner.py
Refactor kustomize `run` function to use -
1) `run_kustomize_to_k8s`
2) `get_k8s_target_foler_path`, `get_kustomize_metadata`
also fix a bug with `overlay_name` metadata
> refactor kustomize runner

- checkov/terraform/checks/resource/aws/RDSPostgreSQLLogFDWExtension.py
- tests/terraform/checks/resource/aws/example_RDSPostgreSQLLogFDWExtension/main.tf
- tests/terraform/checks/resource/aws/test_RDSPostgreSQLLogFDWExtension.py
Recently AWS published a security warning for their RDS PostgreSQL flavours to mitigate an exploit by leveraging `log_fdw` extension https://aws.amazon.com/security/security-bulletins/AWS-2022-004/
the 250th AWS Terraform check 🚀 next goal 500 🍻
> add RDS PostgreSQL version check to mitigate log_fdw exploit

- checkov/terraform/checks/resource/aws/RDSPostgreSQLLogFDWExtension.py
- tests/terraform/checks/resource/aws/example_RDSPostgreSQLLogFDWExtension/main.tf
- tests/terraform/checks/resource/aws/test_RDSPostgreSQLLogFDWExtension.py
Handled a case where `engine_version` is not in `major.minor.bugfix` format.
> RDSPostgreSQLLogFDWExtension handle versions without bugfix

- checkov/bicep/runner.py
- checkov/cloudformation/checks/resource/aws/IAMAdminPolicyDocument.py
- checkov/cloudformation/checks/resource/aws/IAMStarActionPolicyDocument.py
- checkov/cloudformation/runner.py
- checkov/common/graph/graph_builder/utils.py
- checkov/common/runners/base_runner.py
- checkov/kubernetes/runner.py
- checkov/main.py
- tests/cloudformation/checks/resource/aws/example_IAMAdminPolicyDocument/iam_role.unknown.yaml
- tests/cloudformation/checks/resource/aws/example_IAMStarActionPolicyDocument/iam_role.unknown.yaml
- moved the env var `CHECKOV_CREATE_GRAPH` to the `BaseRunner`
- implemented graph creation skips for CFN and K8s runners (TF needs extra work, need to test it more)
- changed the `calculate_hash` to directly use the `str` conversion of the objects passed in, instead of `json.dump` them, which is much faster and the hash will still be reliable, but of course it is now different compared to the one before -> resulted in a reducing the scan time for my test repo by 30 seconds 🚀
> add graph creation skip to K8s and CFN runners

- .cfnlintrc
- checkov/cloudformation/checks/resource/base_resource_value_check.py
- tests/cloudformation/checks/resource/aws/example_ECRImageScanning/FAILED.yml
- tests/cloudformation/checks/resource/aws/example_ECRImageScanning/PASSED.yml
- tests/cloudformation/checks/resource/aws/test_ECRImageScanning.py
- tests/cloudformation/graph/checks/test_yaml_policies.py
Fixes an issue when checking CFN templates with boolean values as a string, i.e. `ScanOnPush: "true"`
Also fixes an issue with an unrelated graph check test where the check failed to load. I am not sure how this got through, as tests failed on `master` for me.
> Fix CFN bool case sensitivity

- README.md
- checkov/common/output/record.py
Resolve #2805 by using the `termcolor.py` existing setting of  `ANSI_COLORS_DISABLED`
> Document and enable monchrome console output

- admissioncontroller/whorf.py
- performance_tests/test_checkov_performance.py
Hello,
I have saw @gruebel slowly making way through the linting and this is to try to help with that.
This change handles all pep8 rules for any python outside of the main `./checkov` and `./tests` directory.
1 unused import, mainly whitespace and newlines.
I only did a minor refactor for the line-length limits. I have been a bit more DRY with one output message and otherwise have used a nice way for creating f strings in a pythonic multi-line way which I learned about through doing this.
e.g
```
foo = "foo"
bar = "bar"
new_string = (
f'{foo}/'
f'{bar}'
)
print(new_string)
```
**License**
> Flake8 - All Rules followed Outside of Checkov and Tests

- tests/common/integration_features/test_custom_policies_integration.py
- tests/common/output/test_junit_report.py
- tests/kubernetes/test_base_registry.py
- tests/terraform/checks/module/registry/example_external_dir/extra_checks/ModuleCheck.py
- tests/terraform/checks/module/registry/test_registry.py
- tests/terraform/checks/resource/aws/test_LambdaXrayEnabled.py
- tests/terraform/checks/resource/aws/test_MWAAWorkerLogsEnabled.py
- tests/terraform/runner/test_plan_runner.py
- tests/terraform/runner/test_runner.py
Hello,
Continuing with linting. Focus on Flake8 F class errors - which are mainly unused imports.
This changes all code under `./tests` to restrict the amount of file changes per PR.
**Care**
When doing this you need to be careful that fixing lint errors doesn't accidentally break something.
In 2 files I have removed an unused import but there was a note in the import section saying not to remove some imports because they prevent a circular dependency. I couldn't see how this specific unused import could be required in the test but just need to be careful on that.
There were added in: https://github.com/bridgecrewio/checkov/pull/2394
e.g https://github.com/bridgecrewio/checkov/blob/master/tests/terraform/runner/test_runner.py - not clear how the unused import prevents a cycle or which …
> Flake8 - Unused imports removed under tests directory

- checkov/arm/runner.py
- checkov/bicep/runner.py
- checkov/cloudformation/runner.py
- checkov/common/runners/base_runner.py
- checkov/common/runners/object_runner.py
- checkov/common/runners/runner_registry.py
- checkov/dockerfile/runner.py
- checkov/helm/runner.py
- checkov/json_doc/runner.py
- checkov/kubernetes/runner.py
- checkov/kustomize/runner.py
- checkov/main.py
- checkov/openapi/runner.py
- checkov/sca_image/runner.py
- checkov/sca_package/runner.py
- checkov/serverless/runner.py
- checkov/terraform/plan_runner.py
- checkov/terraform/runner.py
- checkov/yaml_doc/runner.py
- tests/common/runner_registry/test_runner_registry.py
- tests/common/runners/test_base_runner.py
When scanning files (not directories), only run the frameworks that are relevant for the file type.
Note: In most cases, runner declare their supported files in the `super().__init__` call to `BaseRunner`. In some cases, runners have to override what gets set by their parent class. For example, Helm uses the K8s runner, but only looks for `Chart.yaml`.
> Detect relevant frameworks with --file

- checkov/terraform/checks/graph_checks/aws/APIProtectedByWAF.yaml
- tests/terraform/graph/checks/resources/APIProtectedByWAF/expected.yaml
- tests/terraform/graph/checks/resources/APIProtectedByWAF/main.tf
Currently only the `REGIONAL` type of API Gateway can pass `CKV2_AWS_29`. I added the `EDGE` type as well.
> Ensure API Gateway EDGE is protected by WAF

- checkov/sca_image/runner.py
failure on saving to cache won't throw an exception and the flow will move on
> allowing scan results post request to fail and continue

- checkov/common/bridgecrew/vulnerability_scanning/image_scanner.py
- checkov/sca_package/scanner.py
- tests/sca_package/test_scanner.py
> Revert removal of async from run_scan and catch FileExistsError

- checkov/sca_package/scanner.py
We were returning the results for the repo for the generated file we scanned, not for the original file we actually scanned
> Fix repository path from api

- checkov/terraform/checks/resource/gcp/GKEEnableShieldedNodes.py
- tests/terraform/checks/resource/gcp/test_GKEEnableShieldedNodes.py
- tests/terraform/checks/resource/gcp/test_GKEEnableShieldedNodes/main.tf
Fix for #2341 
Not sure if there should be a check that the correct GCP provider is being used, or the assumption is that the latest is being used?
> GKE nodes shielded by default in v4.0.0

- checkov/common/images/image_referencer.py
- checkov/github_actions/runner.py
- checkov/sca_image/runner.py
Now image name and line numbers are printed alongside the sha. 
Thanks @eurogig for suggesting it to improve developer experience
```sh 
_               _              
| (__| | | |  __/ (__|   < (_) \ V / 
\___|_| |_|\___|\___|_|\_\___/ \_/  
By bridgecrew.io | version: 2.0.1100 
sca_image scan results:
Passed checks: 0, Failed checks: 1061, Skipped checks: 0
//Users/barak/Documents/dev/bridgecrew/checkov3/integration_tests/example_workflow_file/.github/workflows/vulnerable_container.yaml (node:14.1 lines:18-26 (sha256:a511eb5c14))
┌────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┐
│ Total CVEs: 681    │ critical: 48       │ high: 200 …
```
> add image details to cli output

- checkov/sca_image/runner.py
- tests/sca_image/conftest.py
- tests/sca_image/examples/.github/workflows/vulnerable_container.yaml
- tests/sca_image/test_runner.py
- tests/sca_image/utils.py
Added ut that checks that the image reference flow is triggering the image scanning flow calls.
Moved uploading to cache to a separate function.
> ut to check image reference flow is triggering image scan flow calls

- checkov/cloudformation/graph_builder/variable_rendering/renderer.py
- checkov/terraform/runner.py
extract _extract_vertices_block_name_map once to avoid performance issues.
> Improve CFN variable rendering runtime

- checkov/common/util/http_utils.py
- checkov/sca_package/scanner.py
since the content encoding was set to `json`, but no json was sent, it results in an error.
> change request body for scan endpoint

- checkov/common/bridgecrew/platform_integration.py
- tests/common/test_platform_integration.py
Uses the `module` parameter of the run config endpoint to get the appropriate policy set based on token type.
The platform side of this is also live.
> Pass module to platform for policy filtering

- checkov/cloudformation/checks/resource/aws/ALBListenerTLS12.py
- tests/cloudformation/checks/resource/aws/example_ALBListenerTLS12/ALBListenerTLS1.2-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_ALBListenerTLS12/ALBListenerTLS1.2-PASSED.yaml
- tests/cloudformation/checks/resource/aws/test_ALBListenerTLS12.py
Fixes: #2928
Signed-off-by: Andreas Kohn (Framer) <andreas.kohn@framer.com>
> Allow using TLS 1.3 policies with NLBs

- checkov/kubernetes/checks/resource/base_rbac_check.py
- tests/kubernetes/checks/example_RbacApproveCertificateSigningRequests/clusterrole-failed-2.yaml
K8s RBAC doesn't consider `*/*` as a wildcard, only `*` or `*/<subresource>` (source: https://github.com/kubernetes/kubernetes/blob/acb85012ba9c5e9f723971ef706f396d9629e93e/pkg/apis/rbac/types.go#L45)
Don't check for  `*/*`.
> Remove incorrect RBAC wildcard

- checkov/bicep/runner.py
Strip `file_path` attribute in bicep report from root folder
> fixed file_path for bicep report

- checkov/kubernetes/checks/resource/base_root_container_check.py
- checkov/kubernetes/checks/resource/k8s/RootContainers.py
- checkov/kubernetes/checks/resource/k8s/RootContainersHighUID.py
- tests/kubernetes/checks/example_RootContainersHighUID/rootContainersHighUIDFAILED.yaml
- tests/kubernetes/checks/test_RootContainersHighUID.py
- Refactor `RootContainersHighUUID` and `RootContainers` to inherit from the same base class to avoid code duplication
- Safeguard against malformed `securityContext` attribute
> K8 root container checks refactor and safeguard

- checkov/bitbucket_pipelines/runner.py
- checkov/common/images/image_referencer.py
- checkov/github_actions/runner.py
- checkov/gitlab_ci/runner.py
- tests/sca_image/test_runner.py
inspect if image sha exists locally. if not then pull. 
we should add a rest API call to check if the sha exists for the name remotely on the server.
> improve image referencer pull performance

- checkov/kubernetes/checks/resource/k8s/DefaultServiceAccountBinding.py
- checkov/terraform/checks/resource/azure/DataFactoryUsesGitRepository.py
- checkov/terraform/checks/resource/github/BranchProtectionReviewNumTwo.py
- checkov/terraform/checks/resource/gitlab/RequireTwoApprovalsToMerge.py
- checkov/terraform/checks/resource/oci/AbsSecurityGroupUnrestrictedIngress.py
- checkov/terraform/checks/resource/oci/AbsSecurityListUnrestrictedIngress.py
Use force_int on checks that compare numbers, protect against empty list in a K8 check
> Type safety in integer-comparing checks 

- checkov/terraform/checks/resource/aws/DLMScheduleCrossRegionEncryption.py
- checkov/terraform/checks/resource/aws/DLMScheduleCrossRegionEncryptionWithCMK.py
- checkov/terraform/checks/resource/kubernetes/AllowedCapabilities.py
- checkov/terraform/checks/resource/kubernetes/AllowedCapabilitiesSysAdmin.py
- checkov/terraform/checks/resource/kubernetes/ContainerSecurityContext.py
- checkov/terraform/checks/resource/kubernetes/ImagePullPolicyAlways.py
- checkov/terraform/checks/resource/kubernetes/ImageTagFixed.py
- checkov/terraform/checks/resource/kubernetes/LivenessProbe.py
- checkov/terraform/checks/resource/kubernetes/MinimiseCapabilities.py
- checkov/terraform/checks/resource/kubernetes/PrivilegedContainerPSP.py
- checkov/terraform/checks/resource/kubernetes/ReadinessProbe.py
- checkov/terraform/checks/resource/kubernetes/ReadonlyRootFilesystem.py
- tests/terraform/checks/resource/aws/example_DLMScheduleCrossRegionEncryption/main.tf
- tests/terraform/checks/resource/aws/example_DLMScheduleCrossRegionEncryptionWithCMK/main.tf
- Type safety for spec extraction of multiple k8 checks, 
- Enumerate multiple `cross_region_copy_rule instead` of only checking the first one
> Multiple K8 checks type safety, aws_dlm_lifecycle_policy enhancement 

- .cfnlintrc
- checkov/cloudformation/checks/resource/aws/ALBDropHttpHeaders.py
- checkov/cloudformation/checks/resource/aws/ELBv2AccessLogs.py
- checkov/cloudformation/checks/resource/aws/RedShiftSSL.py
- tests/cloudformation/checks/resource/aws/example_ALBDropHttpHeaders/FAIL.yaml
- tests/cloudformation/checks/resource/aws/example_ALBDropHttpHeaders/PASS.yaml
- tests/cloudformation/checks/resource/aws/example_ELBv2AccessLogs/ELBv2AccessLogs-FAILED.yml
- tests/cloudformation/checks/resource/aws/example_ELBv2AccessLogs/ELBv2AccessLogs-PASSED.yml
- tests/cloudformation/checks/resource/aws/example_RedShiftSSL/RedShiftSSL-FAILED.yaml
- tests/cloudformation/checks/resource/aws/example_RedShiftSSL/RedShiftSSL-PASSED.yaml
- tests/cloudformation/checks/resource/aws/test_ALBDropHttpHeaders.py
- tests/cloudformation/checks/resource/aws/test_ELBv2AccessLogs.py
- tests/cloudformation/checks/resource/aws/test_RedShiftSSL.py
Fixes 3 checks that only look for boolean values as strings, and fail if you provide an actual boolean (e.g., `attribute: true` instead of `attribute: "true"`)
> Fix CFN boolean as string checks

- checkov/cloudformation/parser/cfn_yaml.py
- checkov/terraform/context_parsers/tf_plan/__init__.py
- tests/terraform/parser/test_plan_parser.py
- tests/terraform/runner/test_plan_runner.py
Leverage `cfn_yaml` parser to load a terraform plan file, in order to correctly compute resources line numbers.
> Plan file parsing revision

- checkov/bicep/graph_builder/local_graph.py
- checkov/bicep/graph_builder/variable_rendering/renderer.py
- checkov/bicep/utils.py
- checkov/cloudformation/graph_builder/graph_components/blocks.py
- checkov/common/graph/graph_builder/graph_components/blocks.py
- checkov/terraform/graph_builder/graph_components/blocks.py
- tests/bicep/graph/graph_builder/examples/mixed/main.bicep
- tests/bicep/graph/graph_builder/examples/variable/main.bicep
- tests/bicep/graph/graph_builder/test_renderer.py
- tests/bicep/test_graph_manager.py
Added support for `var` element rendering in Bicep + chain rendering also works (ex. `param` -> `var` -> `resource`). I moved the `update_inner_attribute()` method from Terraform to common, because it perfectly works with Bicep, but somehow it doesn't with `CloudFormation`, need extra investigation, which I didn't want to invest for this PR 😄 Also added some missing type hints.
> support var element rendering in Bicep

- checkov/sca_image/runner.py
Add identifier to result file to avoid collisions when running async docker images
> Add identifier to docker scan result file 

- checkov/terraform/checks/resource/aws/LambdaFunctionURLAuth.py
- tests/terraform/checks/resource/aws/example_LambdaFunctionURLAuth/main.tf
- tests/terraform/checks/resource/aws/test_LambdaFunctionURLAuth.py
Added a new check that lambda functions URL AuthType is not NONE:
The `authorization_type` is a required field and the options are `NONE` or `AWS_IAM `.
AWS link: [Here](https://aws.amazon.com/blogs/aws/announcing-aws-lambda-function-urls-built-in-https-endpoints-for-single-function-microservices/)
Terraform link: [Here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function_url)
> Added a new check for lambda functions URL AuthType

- integration_tests/test_checkov_ext_module_cloning.py
Fixes: 
https://github.com/bridgecrewio/checkov/runs/6592927302?check_suite_focus=true
> run api key test only on python3.7 ubuntu

- checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
- tests/common/integration_features/test_suppressions_integration.py
Fixes one of those "wow, I can't believe it was in here for this long" issues where platform suppressions did not get applied to passed checks (only failed checks).
> Apply platform suppressions to passed checks

- .github/workflows/build.yml
- .github/workflows/coverage.yaml
- .github/workflows/pipenv-update.yml
We want to add a branch protection rule for master branch, that requires a minimal amount of reviewers on every PR and restricts who can push to the branch.
Adding that would break some of the current github actions workflows, since they would try to push to master without the right permissions.
The PR implements checking out to the code with a PAT that has permissions to push to master, in every job that runs `git commit` or `git push`.
> Support branch protection rules

- checkov/helm/runner.py
- tests/helm/test_runner.py
assign K8sHelmRunner check_type after calling the Kubernetes runner init function.
> fix K8sHelmRunner check_type

- .github/PULL_REQUEST_TEMPLATE.md
I added a more descriptive pull request template. This will really lighten the load on the PM team, especially for new policies.
There is no Issues UI dropdown equivalent. You can link to templates ([example](https://github.com/kenji-miyake/test-pr-template/blob/main/.github/PULL_REQUEST_TEMPLATE.md)), but I liked this option better.
> Add details to default PR template

- checkov/common/output/report.py
- checkov/common/util/consts.py
- tests/common/output/test_get_exit_code.py
By customer request, adds a mechanism to hard-fail the run if there is a file with a parsing error. It uses an environment variable, as this is a fairly niche requirement.
> add environment variable to hard fail on parsing errors

- checkov/terraform/checks/resource/azure/AKSUsesAzurePoliciesAddon.py
- tests/terraform/checks/resource/azure/test_AKSUsesAzurePoliciesAddon.py
fixes #3006 
Unfortunately, I couldn't find the place to update the docs at https://docs.bridgecrew.io/docs/ensure-that-aks-uses-azure-policies-add-on. If someone can point me to the corresponding place, I will also update the docs.
> fix CKV_AZURE_116 to reflect changes in v2.97.0 of Terraform Azure provider

- checkov/terraform/plan_utils.py
use realpath function instead of abspath function for saving a file path when calculating definitions
> fix in plan_utils

- .cfnlintrc
- checkov/cloudformation/cfn_utils.py
- checkov/cloudformation/checks/resource/BaseCloudsplainingIAMCheck.py
- checkov/cloudformation/checks/resource/aws/IAMStarActionPolicyDocument.py
- checkov/cloudformation/graph_builder/utils.py
- checkov/cloudformation/graph_builder/variable_rendering/renderer.py
- checkov/cloudformation/parser/cfn_yaml.py
- tests/cloudformation/checks/resource/aws/example_IAMStarActionPolicyDocument/cfn_bad_iam_pass.yaml
- tests/cloudformation/checks/resource/aws/test_IAMStarActionPolicyDocument.py
- tests/cloudformation/parser/cfn_bad_iam.yaml
- tests/cloudformation/parser/cfn_bad_name.yaml
- tests/cloudformation/parser/cfn_with_ref_bad.yaml
- tests/cloudformation/parser/test_cfn_yaml.py
Catching some malformed CFN templates, using resources in https://github.com/aws-cloudformation/cfn-lint.
Identified issues:
1. Resource name with a `.` in its name.
2. Policy documents with invalid statement.
3. !Ref of a list object
4. Evaluating getatt when one of the elements is a list
1-2. Identify these cases as malformed and set it as parsing error.
3-4. Make sure we don't fail variable rendering because of it.
> Find malformed CFN YAML templates

- checkov/cloudformation/parser/__init__.py
Handling a bug in cloudformation parser, when trying to parse a malformed file with resources not being a dictionary.
> Fix accessing non dictionary CFN resources

- checkov/common/output/baseline.py
- checkov/main.py
- docs/2.Basics/CLI Command Reference.md
added boolean flag `--output-baseline-as-skipped` to output skipped checks due to baseline in the results report.
Fixes [#1502](https://github.com/bridgecrewio/checkov/issues/1502)
> output baseline skipped in results

- checkov/helm/runner.py
- checkov/kubernetes/runner.py
in order to create one graph in helm runner - call Kubernetes runner once for all the chart dirs.
remove `helmChart` unused parameter.
> create one graph in helm runner

- checkov/common/bridgecrew/vulnerability_scanning/integrations/twistcli.py
When using static imports, we didn't allow overriding the image scanning URLs according to the command argument, only via the `BC_API_URL` env var
We support overriding the default platform URL via env var and via command arg, but the vuln scanning only leveraged the former due to static importing. This allows overriding it via command arg.
> When specifying API URL via arg, leverage it in vuln scanning

- checkov/bicep/parser.py
Instead of logging an error when bicep parsing failed, log a warning.
> Convert Bicep parsing error to warning

- checkov/common/output/report.py
- checkov/runner_filter.py
- tests/common/output/test_get_exit_code.py
- tests/common/test_runner_filter.py
Makes the severity values for the check/skip-check and soft/hard-fail-on flags case-insensitive.
> Make severity filters case-insensiive

- checkov/common/bridgecrew/platform_integration.py
- checkov/common/vcs/base_vcs_dal.py
This PR allow mappings and guidelines to be downloaded behind proxies requiring authentication.
Otherwise :
```
2022-06-07 14:36:01,903 [MainThread  ] [WARNI]  Failed to get the checkov mappings and guidelines from https://www.bridgecrew.cloud/api/v1/guidelines
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 700, in urlopen
self._prepare_proxy(conn)
File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _prepare_proxy
conn.connect()
File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 369, in connect
self._tunnel()
File "/usr/local/lib/python3.7/http/client.py", line 931, in _tunnel
message.strip()))
OSError: Tunnel connection failed: 407 Proxy Authentication Required …
```
> Add proxy authentication headers

- tests/cloudformation/test_graph_manager.py
Makes the `skip` argument a regex, since that is the expected format (not a glob).
The test fails on my computer, because it skips all paths matching `skip*`, which includes anything under my home directory (`/Users/mikeurbanski/`) 💯
> make the skip pattern a regex, not a glob

- checkov/openapi/checks/resource/v2/SecurityRequirement.py
fixes a broken swagger file, if `paths` is set, but without any content
> check if paths is really a dict

- checkov/kubernetes/checks/resource/base_container_check.py
- checkov/openapi/checks/resource/v3/CleartextOverUnencryptedChannel.py
- checkov/terraform/graph_builder/graph_components/module.py
- tests/openapi/checks/resource/v3/example_CleartextCredsOverUnencryptedChannel/pass2.yaml
- tests/openapi/checks/resource/v3/test_CleartextCredsOverUnencryptedChannel.py
fixes in base_container_check and CleartextOverUnencryptedChannel checks
handle the case of terraform provider attributes are not a dict
> fixes in checks

- checkov/kubernetes/checks/resource/k8s/Seccomp.py
- tests/kubernetes/checks/example_Seccomp/cronjob-seccomp-securityContext-PASSED.yaml
- tests/kubernetes/checks/test_Seccomp.py
CKV_K8S_31
Enables specifying the `seccompProfile` nested in a CronJob template spec, as opposed to only looking at metadata annotations.
> Handle securityContext specified within cronjob template spec

- checkov/common/output/report.py
When using `github_failed_only` format, the table does not say which check the table corresponds to and also it prints the table even though there are no failed checks.
E.g.:
```
checkov -d .       --output github_failed_only --soft-fail                                         
2022-06-14 15:47:33,410 [MainThread  ] [WARNI]  Failed to download module git::https://githubstage.mmm.com/DSC/terraform-aws-sonarqube-dcg-393.git?ref=v1.3.0:None
| check_id   | file   | resource   | check_name   | guideline   |
|------------|--------|------------|--------------|-------------|
---
```
This small PR will first see if the check results are populated before creating a table and will …
> Minor fix for output format github_failed_only

- checkov/common/checks_infra/checks_parser.py
- checkov/common/checks_infra/solvers/attribute_solvers/__init__.py
- checkov/common/checks_infra/solvers/attribute_solvers/jsonpath_equals_attribute_solver.py
- checkov/common/checks_infra/solvers/attribute_solvers/jsonpath_not_exists_attribute_solver.py
- checkov/common/graph/checks_infra/enums.py
- docs/3.Custom Policies/YAML Custom Policies.md
- tests/terraform/graph/checks_infra/attribute_solvers/jsonpath_not_exists_solver/AzureSecureRule.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/jsonpath_not_exists_solver/CkSshPortOpenForAll.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/jsonpath_not_exists_solver/PublicDBSG.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/jsonpath_not_exists_solver/example.tf
- tests/terraform/graph/checks_infra/attribute_solvers/jsonpath_not_exists_solver/example.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/jsonpath_not_exists_solver/test_solver.py
Adds the `jsonpath_not_exists` operator as the inverse to `jsonpath_exists`. This required overriding `JsonpathEqualsSolver.get_operation`, which does not delegate to the `_get_operation` method if it can't find the attribute. This caused every evaluation result to return `False`.
I think that the path to `_get_operation` is not actually going to occur. But I am not sure why the jsonpathequals class has the `if self.attributes` check, so I maintained that logic.
> Add jsonpath_not_exists operator

- checkov/helm/runner.py
- tests/helm/runner/resources/infrastructure/helm-tiller/pwnchart/Chart.yaml
Allows first-letter capitalization for the attributes we read from `Chart.yaml`. There seem to be mixed messages on whether this is allowed, but the [docs](https://docs.helm.sh/docs/chart_template_guide/builtin_objects/) do reference them in caps at one point, and I have a customer with a working chart with caps, so we should handle it.
> Allow 'Name' and 'Version' (with caps) in Chart.yaml

- checkov/common/runners/runner_registry.py
- checkov/main.py
- tests/test_main.py
- the framework flags had no relevance on limiting runners, when used with `outer_registry`
> consider framework flags when used with outer_registry

- checkov/common/checks_infra/checks_parser.py
- checkov/common/checks_infra/solvers/complex_solvers/__init__.py
- checkov/common/checks_infra/solvers/complex_solvers/not_solver.py
- checkov/common/graph/checks_infra/enums.py
- docs/3.Custom Policies/Examples.md
- docs/3.Custom Policies/YAML Custom Policies.md
- tests/terraform/graph/checks_infra/complex_solvers/not_solver/BucketsWithDevEnvAndPrivateACL.yaml
- tests/terraform/graph/checks_infra/complex_solvers/not_solver/NotWithNestedDict.yaml
- tests/terraform/graph/checks_infra/complex_solvers/not_solver/NotWithNestedList.yaml
- tests/terraform/graph/checks_infra/complex_solvers/not_solver/test_solver.py
Adds `not` as a possible complex solver (can appear at the same place as `and` and `or`). It will invert the sub-solver. It requires exactly one sub-solver. It will accept a list, like `and` and `or` today, but requires it to have exactly 1 element.
Even though we have a `not_` variant of every operator, there is at least one case where this is insufficient to express any policy by applying DeMorgan's law. That is when you want to do operations over an array.
For example, given the following resource:
```
resource "aws_security_group" "sg" {
ingress {
cidr_blocks = ["0.0.0.0/0"]
}
ingress {
cidr_blocks = ["192.168.1.0/24"]
}
}
```
If you write a policy that says …
> add 'not' complex solver

- checkov/common/bridgecrew/vulnerability_scanning/image_scanner.py
- checkov/sca_package/scanner.py
checkov have problem to scan some files, so in that cases we will try to scan with twistcli on the code repo itself.
> Scan directly with twistcli when checkov can't like gradle files

- .flake8
- checkov/helm/runner.py
- checkov/kubernetes/checks/resource/base_rbac_check.py
- checkov/kubernetes/kubernetes_utils.py
- checkov/kubernetes/runner.py
- flake8_plugins/flake8_class_attributes_plugin/flake8_class_attributes/class_members_errors.py
- flake8_plugins/flake8_class_attributes_plugin/tests/test_files/class_special_attributes_pass.py
- flake8_plugins/flake8_class_attributes_plugin/tests/test_handler.py
- tests/common/runner_registry/test_runner_registry.py
- reused the `K8_POSSIBLE_ENDINGS` constant as `file_extensions` so JSON files are supported again
- enabled flake8 for K8s and adjusted out plugin to skip/pass `__slots__` as acceptable class attribute
Fixes #3150
> leverage K8_POSSIBLE_ENDINGS as file_extensions value

- checkov/cloudformation/checks/resource/aws/LambdaEnvironmentEncryptionSettings.py
Handle scan failure due to invalid structure
https://redlock.atlassian.net/browse/BCE-7216
> handle invalid structure in LambdaEnvironmentEncryptionSettings

- checkov/terraform/checks/resource/azure/AKSLoggingEnabled.py
Support AKSLoggingEnabled to use base resource value check in case the azure provider is version 2.x
> AKSLoggingEnabled BaseResourceValueCheck in case the Azure provider is v2 syntax

- checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py
- checkov/common/checks_infra/checks_parser.py
- tests/common/checks/test_graph_check_loading.py
- tests/common/integration_features/test_custom_policies_integration.py
Fixes an issue where CKV2 checks were having the `bc_id` populated, which made them appear to be platform checks, even if they do not appear in the platform. This breaks the functionality where running with an API key should only include platform checks by default.
> Do not populate BC ID on local graph checks

- checkov/common/checks_infra/solvers/attribute_solvers/equals_attribute_solver.py
- tests/terraform/graph/checks_infra/attribute_solvers/equals_solver/Complex.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/equals_solver/test_solver.py
- tests/terraform/graph/resources/complex/main.tf
Explicitly handles comparisons for `list` and `dict` types in the `equals` operator. Previously, it would compare the string values, which generally worked for lists and some dicts, but not in all cases.
> explicitly handle lists and dicts in equals operator

- checkov/common/bridgecrew/platform_integration.py
- checkov/main.py
- tests/common/test_platform_integration.py
Addresses an issue that is uncommon but frustrating for everyone (user and support) when it happens - an API key that is malformed, either because of a fatfinger issue or an issue with CI/CD variables. We have some basic validation today, but this takes it up a level or two.
BC API keys are UUIDv4s.
Prisma access keys are also UUIDv4s, and secret keys are base64 encoded strings.
> add more explicit API key format validation

- checkov/terraform/checks/provider/aws/credentials.py
- checkov/terraform/checks/resource/gcp/GoogleComputeBlockProjectSSH.py
- checkov/terraform/checks/resource/gcp/GoogleComputeInstanceOSLogin.py
- checkov/terraform/checks/resource/gcp/GoogleComputeSerialPorts.py
- assert google_compute_instance metadata value is dict before accessing it
- assert provider access keys value is string before matching it to a regex
> Google compute instance and AWS provider credentials type assertion

- README.md
- checkov/common/runners/runner_registry.py
Fixed exception when running scans with csv output and output-file-path flag
e.g:
checkov -d .   -o csv --output-file-path /tmp
> fix exporting csv results with output-file-path

- checkov/terraform/parser.py
remove printing the exception trace for terraform parsing errors
> remove exception trace printing

- checkov/common/bridgecrew/integration_features/features/fixes_integration.py
- checkov/common/util/http_utils.py
Changes the fixes integration logic to use urllib3 instead of requests, so that SSL is properly handled.
- [X ] My code follows the style guidelines of this project
> use urllib3 for fixes integration

- checkov/common/runners/runner_registry.py
Skip saving CSV file output (and handle other incompatible types) as it produces 3 files and not 1 and handled differently
> ignore csv output flow for a single file

- docs/3.Custom Policies/YAML Custom Policies.md
> Fix typo in copy-pastable code examples

- Pipfile
- Pipfile.lock
- setup.py
- it looks like pyston-lite doesn't play nice with Mac M1, so I limited to Intel CPUs
- also upper caped CycloneDX lib to properly test v3, when it comes out
> limit pyston to Intel CPU and upper cap cyclonedx for now

- checkov/sca_package/scanner.py
It seems that if some files were scanned successfully and others were not, we failed to scan them locally because we tried to send asyncio a dict as a future. This fixes it
> Fix running locally sca package scan if only some files succeeded

- checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py
Fixes an issue where cloned OOTB policies had a severity value of type string, instead of the Severities dataclass, causing a property error later on.
> use severity enum for cloned policy

- checkov/kustomize/runner.py
fix edge case in `run_kustomize_to_k8s` - not throw an error if there is no 'type' attribute in kustomize folder data
> fix edge case in kustomize runner

- checkov/common/bridgecrew/vulnerability_scanning/image_scanner.py
- checkov/common/bridgecrew/vulnerability_scanning/integrations/twistcli.py
- checkov/common/util/http_utils.py
using request_wrapper in [image_scanner](get_scan_results_from_cache)
the request_wrapper basically perform the method 'requests.request' and adding retries if possible and required
Fixes # (issue) 
fixing unexpected connection issues when performing http-requests by adding retry mechanims
> using request_wrapper in [image_scanner](get_scan_results_from_cache)

- checkov/common/output/csv.py
- tests/common/output/test_bom_report.py
Added function that returns csv format as string.
> return csv format as string

- checkov/terraform/checks/resource/kubernetes/SeccompPSP.py
Hello!
I've found an issue that only happens for Terraform Plan Scanning.
When you create a terraform kubernetes resource and you do not include `metadata.annotations` (because you don't want to add any annotations) then the tfplan unhelpfully represents this as existing with the `null` **value** instead of either not existing or being an empty map (`{}`). There might be a good reason that I just don't understand atm.
```
"metadata":[
{
"annotations":null,
"labels":null,
"name":"terraform-example"
}
]
```
This causes checks to crash that try to read `annotations` if there is no explicit  `annotations` set only for TF Plan.
I don't think there is a great way to consistently test for odd things like this at the moment. I don't think it's clear when / where terraform plan will add these null …
> Fix - TFPlan Crash - Terraform - K8s - Check - SeccompPSP

- checkov/common/checks_infra/solvers/attribute_solvers/length_greater_than_or_equal_attribute_solver.py
- checkov/common/checks_infra/solvers/attribute_solvers/length_less_than_attribute_solver.py
- checkov/common/checks_infra/solvers/attribute_solvers/length_less_than_or_equal_attribute_solver.py
In response to a good observation by @ankon here: https://github.com/bridgecrewio/checkov/pull/3192
I changed the length based operators logic to be more explicit, in addition fixed some typos.
> fix: fixed the length operators logic to be explicit

- checkov/kustomize/runner.py
skip record creation in case a kustomize file path is missing
> fix-kustomize-missing-file-path

- checkov/kubernetes/checks/resource/k8s/ApiServerEtcdCaFile.py
- tests/kubernetes/checks/example_ApiServerEtcdCaFile/example_ApiServerEtcdCaFile-PASSED.yaml
- The parameter `--etcd-cafile` in the `ApiServerEtcdCaFile.py` has an extra hyphen. So raising a PR with the correct parameter.
- Kubernetes Check #  `CKV_K8S_108`
-   `--etcd-ca-file` to `--etcd-cafile`
- [kube-apiserver](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/)
> Update --etcd-cafile in ApiServerEtcdCaFile check (CKV_K8S_108)

- checkov/terraform/module_loading/loaders/github_access_token_loader.py
- tests/terraform/module_loading/test_registry.py
This PR modifies how a user needs to set up private module scanning while using Github modules. Github is a particular case here because of the unique format for module sources - https://www.terraform.io/language/modules/sources#github
Changes: 
- If checkov discovers a GITHUB_PAT, that token will be used for all modules that have a Github source (assuming previous loaders fail). 
- This will include generic format sources -> git::ssh, git::https and Github format sources -> github.com..., git@github.com...
> Fix ssh source pat clone

- checkov/terraform/checks/resource/aws/AppFlowConnectorProfileUsesCMK.py
- checkov/terraform/checks/resource/aws/AppFlowUsesCMK.py
- checkov/terraform/checks/resource/aws/DBSnapshotCopyUsesCMK.py
- checkov/terraform/checks/resource/aws/KendraIndexSSEUsesCMK.py
- checkov/terraform/checks/resource/aws/KeyspacesTableUsesCMK.py
- tests/terraform/checks/resource/aws/example_AppFlowConnectorProfileUsesCMK/main.tf
- tests/terraform/checks/resource/aws/example_AppFlowUsesCMK/main.tf
- tests/terraform/checks/resource/aws/example_DBSnapshotCopyUsesCMK/main.tf
- tests/terraform/checks/resource/aws/example_KendraIndexSSEUsesCMK/main.tf
- tests/terraform/checks/resource/aws/example_KeyspacesTableUsesCMK/main.tf
- tests/terraform/checks/resource/aws/test_AppFlowConnectorProfileUsesCMK.py
- tests/terraform/checks/resource/aws/test_AppFlowUsesCMK.py
- tests/terraform/checks/resource/aws/test_DBSnapshotCopyUsesCMK.py
- tests/terraform/checks/resource/aws/test_KendraIndexSSEUsesCMK.py
- tests/terraform/checks/resource/aws/test_KeyspacesTableUsesCMK.py
A number of new AWS resources have been published, a few can use CMKs. these checks ensure that you do.
New checks for:
262 aws_kendra_index (#24920) -encryption block 
263 aws_appflow_flow (#24017) -customer managed kms key 
264 aws_appflow_connector_profile (#23892)  -customer managed kms key
265 aws_keyspaces_table (#24351) encryption_specification and CMK
266 aws_db_snapshot_copy (#9886) kms key id is set
> new AWS resources new CMK checks

- checkov/terraform/checks/resource/aws/SNSTopicPolicyAnyPrincipal.py
- tests/terraform/checks/resource/aws/example_SNSTopicPolicyAnyPrincipal/main.tf
Fixed an issue where `SNSTopicPolicyAnyPrincipal` check failed on - 
`AttributeError: 'str' object has no attribute 'items'`
> Fix SNSTopicPolicyAnyPrincipal check
