checkov/terraform/context_parsers/registry.py
tests/terraform/context_parsers/mock_context_parser.py
tests/terraform/context_parsers/mock_tf_files/mock.tf
tests/terraform/context_parsers/test_base_parser.py
tests/terraform/context_parsers/test_parser_registry.py

context parser registry and base parser unit tests

context parser registry and base parser unit tests

---

checkov/terraform/checks/resource/gcp/GoogleCloudSqlDatabaseRequireSsl.py
checkov/terraform/checks/resource/gcp/GoogleContainerClusterDisableLegacyAuth.py
checkov/terraform/checks/resource/gcp/GoogleContainerClusterMonitoringEnabled.py
checkov/terraform/checks/resource/gcp/GoogleContainerNodePoolAutoRepairEnabled.py
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlDatabaseRequireSsl.py
tests/terraform/checks/resource/gcp/test_GoogleContainerClusterDisableLegacyAuth.py
tests/terraform/checks/resource/gcp/test_GoogleContainerClusterMonitoringEnabled.py
tests/terraform/checks/resource/gcp/test_GoogleContainerNodePoolAutoRepairEnabled.py
tests/terraform/checks/resource/gcp/test_GoogleContainerNodePoolAutoUpgradeEnabled.py
tests/terraform/runner/resources/example/example.tf

Add a GCP checks 6-9

---

bin/checkov
checkov/terraform/checks/resource/gcp/GoogleCloudSqlDatabasePublicallyAccessible.py
checkov/terraform/checks/resource/gcp/GoogleContainerClusterClientCertificateEnabled.py
checkov/terraform/checks/resource/gcp/GoogleContainerClusterNetworkPolicyEnabled.py
checkov/terraform/checks/resource/gcp/GoogleContainerNodePoolAutoUpgradeEnabled.py
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlDatabasePublicallyAccessible.py
tests/terraform/checks/resource/gcp/test_GoogleContainerClusterClientCertificateEnabled.py
tests/terraform/checks/resource/gcp/test_GoogleContainerClusterNetworkPolicyEnabled.py

Added the following GCP Checks: 
* Cloud SQL DB Publically Accessible
* GKE Cluster Client Cert Enabled
* GKE Cluster Network Policy Enabled
* GKE Node Pool Auto Upgrade Enabled

Adding 4 GCP checks

---

Pipfile
Pipfile.lock
bin/checkov
checkov/terraform/checks/resource/registry.py
checkov/terraform/runner.py
tests/terraform/checks/resource/test_registry.py

This allows users to pass directories paths on the command line to load user-defined checks.
As I am not a seasoned Python developer, there is two things to take care of :
* Should I commit Pipfile and Pipfile.lock given the changes
* I may need help regarding tests

Implement loadable external checks

---

Pipfile.lock
checkov/terraform/checks/resource/aws/PasswordPolicyExpiration.py
checkov/terraform/checks/resource/aws/PasswordPolicyLength.py
checkov/terraform/checks/resource/aws/PasswordPolicyLowercaseLetter.py
checkov/terraform/checks/resource/aws/PasswordPolicyNumber.py
checkov/terraform/checks/resource/aws/PasswordPolicyReuse.py
checkov/terraform/checks/resource/aws/PasswordPolicySymbol.py
checkov/terraform/checks/resource/aws/PasswordPolicyUppercaseLetter.py
tests/terraform/checks/resource/aws/test_PasswordPolicyExpiration.py
tests/terraform/checks/resource/aws/test_PasswordPolicyLength.py
tests/terraform/checks/resource/aws/test_PasswordPolicyLowercaseLetter.py
tests/terraform/checks/resource/aws/test_PasswordPolicyNumber.py
tests/terraform/checks/resource/aws/test_PasswordPolicyReuse.py
tests/terraform/checks/resource/aws/test_PasswordPolicySymbol.py
tests/terraform/checks/resource/aws/test_PasswordPolicyUppercaseLetter.py
tests/terraform/runner/resources/example/example.tf

Fix issue reported at https://github.com/bridgecrewio/checkov/issues/28

fix password policy checks

---

checkov/terraform/output/record.py

handle: https://github.com/bridgecrewio/checkov/issues/34

Add check id to cli output

---

bin/checkov
checkov/terraform/parser.py
checkov/terraform/runner.py
tests/terraform/runner/test_runner.py

request: https://github.com/bridgecrewio/checkov/issues/31

add cli switch to inspect specific file

---

checkov/terraform/checks/resource/aws/ElasticacheReplicationGroupEncryptionAtRest.py
checkov/terraform/checks/resource/aws/ElasticacheReplicationGroupEncryptionAtTransit.py
checkov/terraform/checks/resource/aws/ElasticacheReplicationGroupEncryptionAtTransitAuthToken.py
tests/terraform/checks/resource/aws/test_ElasticacheReplicationGroupEncryptionAtRest.py
tests/terraform/checks/resource/aws/test_ElasticacheReplicationGroupEncryptionAtTransit.py
tests/terraform/checks/resource/aws/test_ElasticacheReplicationGroupEncryptionAtTransitAuthToken.py
tests/terraform/runner/resources/example/example.tf

request: https://github.com/bridgecrewio/checkov/issues/43

add check: encryption features for AWS Elasticache Replication Group enabled

---

.coveragerc
bin/checkov
checkov/main.py
checkov/terraform/runner.py
tests/terraform/runner/test_runner.py

support multiple file input like
`checkov --file /user/tf/example.tf --file /user/tf/example/main.tf
`
as asked at https://github.com/bridgecrewio/checkov/issues/68

enable repeating on --file option

---

checkov/terraform/checks/resource/aws/ECRImageScanning.py
checkov/terraform/checks/resource/aws/ECRPolicy.py
tests/terraform/checks/resource/aws/test_ECRImageScanning.py
tests/terraform/checks/resource/aws/test_ECRPolicy.py
tests/terraform/runner/resources/example/example.tf

Handle: https://github.com/bridgecrewio/checkov/issues/58 and https://github.com/bridgecrewio/checkov/issues/57
By adding checks:
1. Ensure ECR policy is not set to public
2. Ensure ECR image scanning on push is enabled

add ecr related checks

---

checkov/terraform/checks/resource/aws/CloudfrontDistributionEncryption.py
tests/terraform/checks/resource/aws/test_CloudfrontDistributionEncryption.py
tests/terraform/runner/resources/example/example.tf

Handle https://github.com/bridgecrewio/checkov/issues/27

add cloudfront https check

---

checkov/terraform/checks/resource/aws/CloudfrontDistributionEncryption.py
checkov/terraform/checks/resource/aws/CloudtrailEncryption.py
checkov/terraform/checks/resource/aws/CloudtrailLogValidation.py
tests/terraform/checks/resource/aws/test_CloudfrontDistributionEncryption.py
tests/terraform/checks/resource/aws/test_CloudtrailEncryption.py
tests/terraform/checks/resource/aws/test_CloudtrailLogValidation.py
tests/terraform/runner/resources/example/example.tf

- Ensure CloudTrail log file validation is enabled https://github.com/bridgecrewio/checkov/issues/26
- Ensure CloudTrail logs are encrypted at rest using KMS CMKs https://github.com/bridgecrewio/checkov/issues/25

Add cloudtrail checks

---

checkov/main.py
docs/_config.yml
docs/search.html

fixed https://github.com/bridgecrewio/checkov/issues/77

add version flag

---

checkov/terraform/checks/resource/aws/EKSControlPlaneLogging.py
checkov/terraform/checks/resource/aws/EKSPublicAccess.py
checkov/terraform/checks/resource/aws/EKSPublicAccessCIDR.py
tests/terraform/checks/resource/aws/test_EKSControlPlaneLogging.py
tests/terraform/checks/resource/aws/test_EKSPublicAccess.py
tests/terraform/checks/resource/aws/test_EKSPublicAccessCIDR.py

Added the following Checks: 
* Ensure control plane logging enabled for all log types
* Check that EKS API public access is disabled
* If EKS public access enabled, ensure the API is not open to 0.0.0.0/0

Add 3 EKS checks

---

Pipfile
Pipfile.lock
checkov/terraform/checks/resource/gcp/GoogleCloudSqlBackupConfiguration.py
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlBackupConfiguration.py

fix https://github.com/bridgecrewio/checkov/issues/85

add gcp cloudsql backup check

---

checkov/terraform/checks/resource/aws/IAMPolicyAttachedToGroupOrRoles.py
tests/terraform/checks/resource/aws/test_IAMPolicyAttachedToGroupOrRoles.py
tests/terraform/runner/resources/example/example.tf

fix: https://github.com/bridgecrewio/checkov/issues/56

add check: Ensure IAM policies are attached only to groups or roles

---

README.md

The updated docker command didn't work for me.  Also, changing to -t instead of -i allows colorful output.

Fix docker readme

---

checkov/terraform/checks/resource/gcp/GoogleCloudSqlDatabaseRequireSsl.py
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlDatabaseRequireSsl.py

Fixes issue 100: https://github.com/bridgecrewio/checkov/issues/100

Fix GCP cloudSQL check failing

---

checkov/terraform/evaluation/evaluation_methods/const_variable_evaluation.py
checkov/terraform/output/record.py
checkov/terraform/runner.py
tests/terraform/evaluation/test_const_variable_evaluation.py

Fixed a bug in variable evaluations where the regex to match a variable in source code lines was incorrectly set.

Variable evaluations bugfixes

---

Pipfile.lock
checkov/terraform/checks/resource/BaseResourceBooleanValueCheck.py
checkov/terraform/checks/resource/BaseResourceValueCheck.py
checkov/terraform/checks/resource/aws/CloudtrailLogValidation.py
checkov/terraform/checks/resource/aws/DynamodbRecovery.py
checkov/terraform/checks/resource/aws/EBSEncryption.py
checkov/terraform/checks/resource/aws/EBSSnapshotEncryption.py
checkov/terraform/checks/resource/aws/ECRImageScanning.py
checkov/terraform/checks/resource/aws/ElasticacheReplicationGroupEncryptionAtRest.py
checkov/terraform/checks/resource/aws/ElasticacheReplicationGroupEncryptionAtTransit.py
checkov/terraform/checks/resource/aws/ElasticsearchEncryption.py
checkov/terraform/checks/resource/aws/KMSRotation.py
checkov/terraform/checks/resource/aws/RDSEncryption.py
checkov/terraform/checks/resource/aws/S3Versioning.py
tests/terraform/checks/resource/aws/test_KMSRotation.py
tests/terraform/runner/resources/example/example.tf

unifty boolean checks

---

checkov/cloudformation/runner.py

bugfix on specific files run

---

checkov/common/runners/runner_registry.py

empty report bugfix

---

checkov/terraform/checks/provider/__init__.py
checkov/terraform/checks/provider/aws/__init__.py
checkov/terraform/checks/provider/aws/credentials.py
checkov/terraform/checks/provider/base_check.py
checkov/terraform/checks/provider/base_registry.py
checkov/terraform/checks/provider/registry.py
checkov/terraform/context_parsers/base_parser.py
checkov/terraform/context_parsers/parsers/provider_context_parser.py
checkov/terraform/runner.py
docs/2.Concepts/Credentials Scans.md
tests/terraform/checks/provider/aws/test_credentials.py
tests/terraform/runner/resources/example/example.tf

scan for aws secrets defined in provider blocks:
https://github.com/bridgecrewio/checkov/issues/123
see the new added guide: https://github.com/bridgecrewio/checkov/blob/92496942d17a5c3ffb2ec87b79629e330dcd6448/docs/2.Concepts/Credentials%20Scans.md

add aws credentials scans

---

checkov/terraform/evaluation/evaluation_methods/const_variable_evaluation.py

Fixed variable evaluation's assignment regex

variable evaluation assignment regex bugfix

---

checkov/terraform/parser.py
checkov/terraform/runner.py

Refactored parsing code, fixed relative path issues and json output on -f output option.
Solves #133 and #134 

File parsing bugfixes

---

checkov/common/runners/runner_registry.py

don't print banner on json and junitxml outputs

---

checkov/terraform/checks/provider/aws/credentials.py
checkov/terraform/checks/resource/aws/LambdaEnvironmentCredentials.py
checkov/terraform/checks/utils/consts.py
tests/terraform/checks/resource/aws/test_LambdaEnvironmentCredentials.py

look for aws access keys in lambda environment variables

detect secrets in lambda environment variables

---

checkov/terraform/checks/provider/aws/credentials.py
checkov/terraform/checks/resource/aws/LambdaEnvironmentCredentials.py
checkov/terraform/checks/utils/consts.py
docs/3.Scans/Credentials Scans.md
tests/terraform/checks/resource/aws/test_LambdaEnvironmentCredentials.py

Detect secrets lambda environment

---

checkov/common/models/enums.py
checkov/terraform/checks/provider/aws/credentials.py
checkov/terraform/checks/resource/aws/EC2Credentials.py
checkov/terraform/checks/resource/aws/LambdaEnvironmentCredentials.py
docs/3.Scans/Credentials Scans.md
tests/terraform/checks/resource/aws/test_EC2Credentials.py
tests/terraform/runner/resources/example/example.tf

check credentials in ec2 userdata

---

tests/terraform/runner/test_runner.py

Resolves #206 by making sure we actually don't

Add tests for validation of check IDs

---

Pipfile.lock
checkov/main.py

Related to #115 , still no support for recursive

Support directory as a repetitive parameter

---

checkov/terraform/checks/data/aws/StarActionPolicyDocument.py
tests/terraform/checks/data/aws/test_StarActionPolicyDocument.py
tests/terraform/runner/resources/example/example.tf

Add check for policies which allow the action "*"

---

checkov/terraform/checks/data/aws/AdminPolicyDocument.py
checkov/terraform/checks/data/aws/StarActionPolicyDocument.py
tests/terraform/checks/data/aws/test_AdminPolicyDocument.py
tests/terraform/checks/data/aws/test_StarActionPolicyDocument.py

Move to Admin category + take into account the statement's effect + iterate through all the statements in the policy document

Minor fixes to AdminPolicyDocument check

---

checkov/terraform/checks/data/aws/AdminPolicyDocument.py
checkov/terraform/checks/data/aws/StarActionPolicyDocument.py
tests/terraform/runner/resources/example/example.tf

Skip not_action statements as they do not give permissions

---

checkov/terraform/checks/data/aws/AdminPolicyDocument.py
checkov/terraform/checks/data/aws/StarActionPolicyDocument.py
tests/terraform/runner/resources/example/example.tf

Make effect optional

---

checkov/main.py

fix -f flag

---

checkov/terraform/context_parsers/base_parser.py

- Cached parsed code lines, to be reused if available
- Improved whitespace trailing ops performance
Profiling analysis:
Before we may observe a bottleneck in the code line computation (too many function calls)
After optimization the bottleneck doesn't longer exist: 

Context parser optimization 

---

checkov/terraform/context_parsers/registry.py
checkov/terraform/parser.py
checkov/terraform/runner.py
tests/terraform/runner/resources/hcl_0.11/main.tf
tests/terraform/runner/test_runner.py

- Evaluate HCL v0.11 boolean expressions to True and False values
- Support running for multiple repositories as a library

HCL v0.11 boolean expressions support

---

checkov/terraform/checks/resource/aws/LambdaEnvironmentCredentials.py
tests/terraform/checks/resource/aws/test_LambdaEnvironmentCredentials.py
tests/terraform/runner/resources/example/example.tf

bug fix - Lambda variable string

---

setup.py

add boto3 as a dependency to published package

---

checkov/terraform/checks/resource/aws/SecurityGroupUnrestrictedIngress22.py
tests/terraform/runner/resources/example/example.tf

handle ingress as map instead of block

---

checkov/terraform/checks/resource/aws/S3Encryption.py
checkov/terraform/checks/resource/base_resource_value_check.py
tests/terraform/runner/resources/example/example.tf

handling s3 bucket maps instead of blocks

---

checkov/terraform/parser.py
checkov/terraform/runner.py

- Redesign hcl2 parsing to be more efficient and readable 
- Avoid scanning already-scanned modules to avoid infinite recursive calls
Thanks to @arielkru 

HCL2 parsing improvements 

---

checkov/cloudformation/runner.py
checkov/common/bridgecrew/platform_integration.py
checkov/common/checks/base_check_registry.py
checkov/common/runners/base_runner.py
checkov/common/runners/runner_registry.py
checkov/main.py
checkov/runner_filter.py
checkov/terraform/runner.py
docs/1.Introduction/Getting Started.md
tests/cloudformation/checks/resource/aws/test_ALBListenerHTTPS.py
tests/cloudformation/checks/resource/aws/test_CloudfrontDistributionEncryption.py
tests/cloudformation/checks/resource/aws/test_CloudtrailEncryption.py
tests/cloudformation/checks/resource/aws/test_CloudtrailLogValidation.py
tests/cloudformation/checks/resource/aws/test_DynamodbRecovery.py
tests/cloudformation/checks/resource/aws/test_EBSEncryption.py
tests/cloudformation/checks/resource/aws/test_ECRPolicy.py
tests/cloudformation/checks/resource/aws/test_ElasticacheReplicationGroupEncryptionAtRest.py
tests/cloudformation/checks/resource/aws/test_ElasticacheReplicationGroupEncryptionAtTransit.py
tests/cloudformation/checks/resource/aws/test_ElasticacheReplicationGroupEncryptionAtTransitAuthToken.py
tests/cloudformation/checks/resource/aws/test_ElastisearchEncryption.py
tests/cloudformation/checks/resource/aws/test_ElastisearchNodeToNodeEncryption.py
tests/cloudformation/checks/resource/aws/test_SecurityGroupRuleDescription.py
tests/cloudformation/checks/resource/aws/test_SecurityGroupUnrestrictedIngress22.py
tests/cloudformation/parser/test_cfn_json.py
tests/terraform/runner/test_runner.py

Add ability to filter a specific check or framework for checkov.
New flags where added: 
To run specific check
`checkov --check CKV_AWS_1`
To run multiple checks
`checkov --check CKV_AWS_1 --check CKV_AWS_2`
To run specific IaC framework:
`checkov --framework terraform`

add ability to execute a single check or multiple selected checks

---

checkov/main.py

validate repo-id

---

README.md
checkov/cloudformation/runner.py
checkov/common/checks/base_check_registry.py
checkov/common/runners/runner_registry.py
checkov/main.py
checkov/runner_filter.py
checkov/terraform/runner.py
docs/1.Introduction/Getting Started.md
docs/2.Concepts/Suppressions.md
tests/terraform/runner/test_runner.py

support --skip-check flag

---

checkov/terraform/checks/resource/aws/IAMRoleAllowsPublicAssume.py
checkov/terraform/checks/resource/aws/IAMRoleAttachedToService.py
tests/terraform/checks/resource/aws/test_IAMRoleAttachedToService.py
tests/terraform/runner/resources/example/example.tf

New check/iam role policy attached to service

---

checkov/terraform/checks/resource/aws/IAMAdminPolicyDocument.py
checkov/terraform/checks/resource/aws/IAMStarActionPolicyDocument.py
tests/terraform/checks/resource/aws/test_IAMAdminPolicyDocument.py
tests/terraform/checks/resource/aws/test_IAMStarActionPolicyDocument.py
tests/terraform/runner/resources/example/example.tf

Check additions/handle iam policy json

---

checkov/cloudformation/checks/resource/aws/S3AccessLogs.py
checkov/cloudformation/checks/resource/aws/S3Encryption.py
checkov/cloudformation/checks/resource/aws/S3PublicACLRead.py
checkov/cloudformation/checks/resource/aws/S3PublicACLWrite.py
checkov/cloudformation/checks/resource/aws/S3Versioning.py
tests/cloudformation/checks/resource/aws/S3Templates/ExampleS3.yaml
tests/cloudformation/checks/resource/aws/test_S3AccessLogs.py
tests/cloudformation/checks/resource/aws/test_S3Encryption.py
tests/cloudformation/checks/resource/aws/test_S3PublicACLRead.py
tests/cloudformation/checks/resource/aws/test_S3PublicACLWrite.py
tests/cloudformation/checks/resource/aws/test_S3Versioning.py
tests/cloudformation/parser/success.json

Add 5 S3 checks over CF

---

checkov/terraform/checks/resource/aws/AbsSecurityGroupUnrestrictedIngress.py
checkov/terraform/checks/resource/aws/SecurityGroupUnrestrictedIngress22.py
checkov/terraform/checks/resource/aws/SecurityGroupUnrestrictedIngress3389.py
tests/terraform/checks/resource/aws/test_SecurityGroupUnrestrictedIngress22.py

Also, refactor SG rules check to base class and add hcl2 test cases.
Resolved #264 

Handle list of ingress rules

---

checkov/common/output/report.py
checkov/common/runners/runner_registry.py
checkov/common/util/banner.py
checkov/main.py
docs/1.Introduction/Getting Started.md
tests/terraform/runner/test_runner.py

reduce the amount of printed cli output by showing only failed checks 
handle: https://github.com/bridgecrewio/checkov/pull/273

add quiet flag to reduce cli noise

---

checkov/cloudformation/checks/resource/aws/S3AccessLogs.py
checkov/cloudformation/checks/resource/aws/S3Encryption.py
checkov/cloudformation/checks/resource/aws/S3PublicACLRead.py
checkov/cloudformation/checks/resource/aws/S3PublicACLWrite.py
checkov/cloudformation/checks/resource/aws/S3Versioning.py
tests/cloudformation/checks/resource/aws/S3Templates/ExampleS3.yaml
tests/cloudformation/checks/resource/aws/test_S3AccessLogs.py
tests/cloudformation/checks/resource/aws/test_S3Encryption.py
tests/cloudformation/checks/resource/aws/test_S3PublicACLRead.py
tests/cloudformation/checks/resource/aws/test_S3PublicACLWrite.py
tests/cloudformation/checks/resource/aws/test_S3Versioning.py

Handle case of no Properties for S3 bucket

---

checkov/kubernetes/parser/parser.py
checkov/terraform/checks/resource/gcp/GoogleCloudSqlDatabasePublicallyAccessible.py
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlDatabasePublicallyAccessible.py

Fix GCP & K8 parsing

---

checkov/cloudformation/checks/resource/aws/S3Encryption.py
tests/cloudformation/checks/resource/aws/S3Templates/ExampleS3.yaml
tests/cloudformation/checks/resource/aws/test_S3Encryption.py

Support BucketEncryption conf in addition to ServerSideEncryptionRule

---

tests/terraform/runner/resources/example/example.tf

Fix resource names - no whitespace

---

checkov/common/models/consts.py
checkov/kubernetes/checks/ImagePullPolicyAlways.py
checkov/kubernetes/checks/ImageTagFixed.py
tests/kubernetes/checks/example_ImageDigest/kafka-withrepo-PASSED.yaml
tests/kubernetes/checks/example_ImagePullPolicy/kafka-PullPolicyAlways-PASSED.yaml
tests/kubernetes/checks/example_ImageTagFixed/kafka-ImageWithRepo-PASSED.yaml
tests/kubernetes/checks/test_ImageDigest.py
tests/kubernetes/checks/test_ImagePullPolicyAlways.py
tests/kubernetes/checks/test_ImageTagFixed.py

Parse docker image name to to extract the image name and tag via a best practice regex

Docker image name parsing

---

checkov/cloudformation/checks/resource/aws/RedshiftClusterEncryption.py
checkov/terraform/checks/resource/aws/RedshiftClusterEncryption.py
tests/cloudformation/checks/resource/aws/example_RedshiftClusterEncryption/RedshiftClusterEncryption-FAILED-2.yaml
tests/cloudformation/checks/resource/aws/example_RedshiftClusterEncryption/RedshiftClusterEncryption-FAILED.yaml
tests/cloudformation/checks/resource/aws/example_RedshiftClusterEncryption/RedshiftClusterEncryption-PASSED.yaml
tests/cloudformation/checks/resource/aws/test_RedshiftClusterEncryption.py
tests/terraform/checks/resource/aws/test_RedshiftClusterEncryption.py

Add Redshift cluster encryption check

---

checkov/terraform/checks/resource/azure/AKSApiServerAuthorizedIpRanges.py
checkov/terraform/checks/resource/azure/AKSNetworkPolicy.py
checkov/terraform/checks/resource/azure/AKSRbacEnabled.py
checkov/terraform/checks/resource/azure/StorageAccountsTransportEncryption.py

Refactor Azure checks to inherit from BaseResourceValueCheck

---

checkov/cloudformation/checks/resource/aws/ECSClusterContainerInsights.py
checkov/terraform/checks/resource/aws/ECSClusterContainerInsights.py
tests/cloudformation/checks/resource/aws/example_ECSClusterContainerInsights/ECSClusterContainerInsights-FAILED-2.yaml
tests/cloudformation/checks/resource/aws/example_ECSClusterContainerInsights/ECSClusterContainerInsights-FAILED.yaml
tests/cloudformation/checks/resource/aws/example_ECSClusterContainerInsights/ECSClusterContainerInsights-PASSED.yaml
tests/cloudformation/checks/resource/aws/test_ECSClusterContainerInsights.py
tests/terraform/checks/resource/aws/test_ECSClusterContainerInsights.py

Add ECS cluster container insights check

---

checkov/cloudformation/runner.py
tests/cloudformation/parser/skip.yaml
tests/cloudformation/parser/test_cfn_yaml.py

Closes #234. Kinda winged this one, but it could serve as a decent starting point towards Cloudformation comment check suppression. I'm very open to feedback.

Add Cloudformation resource check skip via comment

---

tests/terraform/checks/resource/gcp/test_GKEAliasIpEnabled.py

Hi,
I will be demoing this to my team to encourage us contributing and using this as a base for our GCP terraform PR checks. One minor nitpick thing I noticed is that test data is presented directly as a dict, and I'd prefer to have raw terraform code to contrast back to - especially if there's any syntax or provider changes. I've added an example to this PR, what do you think?
---

feat: Using raw .tf data in tests

---

checkov/terraform/checks/resource/aws/SNSTopicEncryption.py

converted SNS encryption check to implement BaseResourceValueCheck

SNS encryption check conversion 

---

checkov/terraform/checks/resource/aws/ElasticsearchNodeToNodeEncryption.py

fix https://github.com/bridgecrewio/checkov/issues/295

fix es instance_count check

---

checkov/terraform/checks/resource/gcp/GKEAliasIpEnabled.py
checkov/terraform/checks/resource/gcp/GKEClientCertificateEnabled.py
checkov/terraform/checks/resource/gcp/GKEClusterLogging.py
checkov/terraform/checks/resource/gcp/GKEMasterAuthorizedNetworksEnabled.py
checkov/terraform/checks/resource/gcp/GKENetworkPolicyEnabled.py
checkov/terraform/checks/resource/gcp/GKENodePoolAutoRepairEnabled.py
checkov/terraform/checks/resource/gcp/GKENodePoolAutoUpgradeEnabled.py
checkov/terraform/checks/resource/gcp/GKEPodSecurityPolicyEnabled.py
checkov/terraform/checks/resource/gcp/GKEPrivateClusterConfig.py
checkov/terraform/checks/resource/gcp/GoogleCloudSqlBackupConfiguration.py
checkov/terraform/checks/resource/gcp/GoogleCloudSqlDatabaseRequireSsl.py
checkov/terraform/checks/resource/gcp/GoogleProjectDefaultNetwork.py
checkov/terraform/checks/resource/gcp/GoogleStorageBucketEncryption.py
checkov/terraform/checks/resource/gcp/GoogleStorageBucketNotPublic.py
checkov/terraform/checks/resource/gcp/GoogleStorageBucketUniformAccess.py
checkov/terraform/checks/resource/gcp/GoogleSubnetworkLoggingEnabled.py
tests/terraform/checks/resource/gcp/test_GoogleStorageBucketNotPublic.py
tests/terraform/checks/resource/gcp/test_GoogleStorageBucketUniformAccess.py
tests/terraform/runner/resources/example/example.tf

Gcp new checks/storage

---

checkov/terraform/checks/resource/gcp/GoogleComputeBootDiskEncryption.py
checkov/terraform/checks/resource/gcp/GoogleComputeDefaultServiceAccount.py
checkov/terraform/checks/resource/gcp/GoogleComputeDefaultServiceAccountFullAccess.py
checkov/terraform/checks/resource/gcp/GoogleComputeDiskEncryption.py
checkov/terraform/checks/resource/gcp/GoogleComputeExternalIP.py
checkov/terraform/checks/resource/gcp/GoogleComputeIPForward.py
checkov/terraform/checks/resource/gcp/GoogleComputeInstanceOSLogin.py
checkov/terraform/checks/resource/gcp/GoogleComputeProjectOSLogin.py
checkov/terraform/checks/resource/gcp/GoogleComputeSerialPorts.py
checkov/terraform/checks/resource/gcp/GoogleComputeShieldedVM.py
checkov/terraform/checks/resource/gcp/GoogleComupteBlockProjectSSH.py
tests/terraform/checks/resource/gcp/test_GoogleComputeBlockProjectSSH.py
tests/terraform/checks/resource/gcp/test_GoogleComputeBootDiskEncryption.py
tests/terraform/checks/resource/gcp/test_GoogleComputeDefaultServiceAccount.py
tests/terraform/checks/resource/gcp/test_GoogleComputeDefaultServiceAccountFullAccess.py
tests/terraform/checks/resource/gcp/test_GoogleComputeDiskEncryption.py
tests/terraform/checks/resource/gcp/test_GoogleComputeExternalIP.py
tests/terraform/checks/resource/gcp/test_GoogleComputeIPForward.py
tests/terraform/checks/resource/gcp/test_GoogleComputeInstanceOSLogin.py
tests/terraform/checks/resource/gcp/test_GoogleComputeProjectOSLogin.py
tests/terraform/checks/resource/gcp/test_GoogleComputeSerialPorts.py
tests/terraform/checks/resource/gcp/test_GoogleComputeShieldedVM.py
tests/terraform/runner/resources/example/example.tf

gcp new checks/virtual machines

---

README.md
checkov/cloudformation/runner.py
checkov/common/bridgecrew/platform_integration.py
checkov/common/bridgecrew/wrapper.py
checkov/logging_init.py
checkov/main.py

enable exposure of logs by environment variable `LOGGING_LEVEL`

---

checkov/common/runners/runner_registry.py

fix https://github.com/bridgecrewio/checkov/issues/198

enable merging multiple frameworks to 1 json array

---

checkov/terraform/checks/resource/gcp/GoogleKMSRotationPeriod.py
checkov/terraform/checks/resource/gcp/GoogleProjectAdminServiceAccount.py
checkov/terraform/checks/resource/gcp/GoogleRoleServiceAccountUser.py
tests/terraform/checks/resource/gcp/test_GoogleKMSKeyRotationPeriod.py
tests/terraform/checks/resource/gcp/test_GoogleProjectAdminServiceAccount.py
tests/terraform/checks/resource/gcp/test_GoogleRoleServiceAccountUser.py
tests/terraform/runner/resources/example/example.tf

Gcp new check/iam

---

checkov/terraform/checks/resource/base_resource_value_check.py

Make variable dependant if the string contains a reference to var / local

---

checkov/terraform/checks/resource/base_resource_value_check.py

Reverts bridgecrewio/checkov#310

Revert "Make variable dependant if the string contains a reference to var / local"

---

checkov/kubernetes/runner.py

Ignore CustomResourceDefinition in containers resource scan

---

checkov/terraform/checks/resource/gcp/GoogleComputeFirewallUnrestrictedIngress22.py
checkov/terraform/checks/resource/gcp/GoogleComputeFirewallUnrestrictedIngress3389.py
tests/terraform/checks/resource/gcp/test_TestGoogleComputeFirewallUnrestrictedIngress3389.py

gcp_issue/checks_fix

---

checkov/terraform/evaluation/evaluation_methods/const_variable_evaluation.py

Do not fail on unsupported, complex variable evaluations

---

checkov/kubernetes/base_registry.py
checkov/kubernetes/runner.py
tests/kubernetes/checks/test_AllowPrivilegeEscalationPSP.py

skip-check support for k8

---

checkov/common/runners/runner_registry.py

output a json list only when more then one framework exists

---

checkov/kubernetes/runner.py

handle cases where metadata is not in entity conf

---

checkov/terraform/checks/resource/gcp/GKEUseCosImage.py
tests/terraform/checks/resource/gcp/test_GKEUseCosImage.py

Fixes https://github.com/bridgecrewio/checkov/issues/328

GKE Image Type COS  Check Case insensitive

---

checkov/common/checks/base_check_registry.py
checkov/kubernetes/base_registry.py
checkov/main.py
docs/1.Introduction/Getting Started.md
docs/2.Concepts/Suppressions.md
docs/4.Integrations/Jenkins.md
tests/kubernetes/checks/example_ShareHost/jenkinsDeployment-PASSED.yaml
tests/terraform/runner/test_runner.py

Language adjustment

---

.bandit
.github/workflows/security.yaml
Pipfile
README.md
checkov/cloudformation/parser/cfn_yaml.py
checkov/terraform/checks/resource/aws/IAMAdminPolicyDocument.py
checkov/terraform/checks/resource/aws/IAMRoleAllowAssumeFromAccount.py
checkov/terraform/checks/resource/aws/IAMRoleAllowsPublicAssume.py
checkov/terraform/checks/resource/aws/IAMStarActionPolicyDocument.py
checkov/terraform/checks/utils/consts.py

add security build job

---

checkov/cloudformation/runner.py

Skip "Resources" which aren't CFN resources

---

checkov/terraform/checks/resource/azure/SecurityCenterContactEmailAlert.py
checkov/terraform/checks/resource/azure/SecurityCenterContactEmailAlertAdmins.py
checkov/terraform/checks/resource/azure/SecurityCenterContactPhone.py
checkov/terraform/checks/resource/azure/SecurityCenterStandardPricing.py
tests/terraform/checks/resource/azure/test_SecurityCenterContactPhone.py
tests/terraform/checks/resource/azure/test_SecurityCenterEmailAlert.py
tests/terraform/checks/resource/azure/test_SecurityCenterEmailAlertAdmins.py
tests/terraform/checks/resource/azure/test_SecurityCenterStandardPricing.py
tests/terraform/runner/resources/example/example.tf

Azure checks/security center

---

checkov/cloudformation/checks/resource/aws/EBSEncryption.py
checkov/terraform/checks/resource/aws/APIGatewayAuthorization.py
checkov/terraform/checks/resource/aws/EBSEncryption.py
checkov/terraform/checks/resource/aws/EBSSnapshotEncryption.py
checkov/terraform/checks/resource/aws/IAMPolicyAttachedToGroupOrRoles.py
checkov/terraform/checks/resource/aws/LaunchConfigurationEBSEncryption.py
checkov/terraform/checks/resource/azure/AppServiceHTTPSOnly.py
checkov/terraform/checks/resource/azure/AppServiceHttps20Enabled.py
checkov/terraform/checks/resource/azure/AppServieClientCertificate.py
checkov/terraform/checks/resource/azure/AppServieIdentity.py
checkov/terraform/checks/resource/azure/NSGRuleRDPAccessRestricted.py
checkov/terraform/checks/resource/azure/NetworkWatcherFlowLogEnabled.py
checkov/terraform/checks/resource/azure/SQLServerNoPublicAccess.py

Many minor fixes to different checks

---

checkov/terraform/checks/resource/aws/CloudtrailEncryption.py

base resource value implementation

---

checkov/terraform/checks/resource/azure/NSGRulePortAccessRestricted.py
tests/terraform/checks/resource/azure/test_NSGRuleRDPAccessRestricted.py

Add support for network security groups as well as rules

---

checkov/terraform/checks/resource/azure/AppServiceHttps20Enabled.py
checkov/terraform/checks/resource/azure/MySQLServerSSLEnforcementEnabled.py
checkov/terraform/checks/resource/azure/PostgreSQLServerConnectionThrottlingEnabled.py
checkov/terraform/checks/resource/azure/PostgreSQLServerLogCheckpointsEnabled.py
checkov/terraform/checks/resource/azure/PostgreSQLServerLogConnectionsEnabled.py
checkov/terraform/checks/resource/azure/PostgreSQLServerSSLEnforcementEnabled.py
checkov/terraform/checks/resource/azure/SQLServerAuditingEnabled.py
checkov/terraform/checks/resource/azure/SQLServerAuditingRetention90Days.py
checkov/terraform/checks/resource/azure/SQLServerEmailAlertsEnabled.py
checkov/terraform/checks/resource/azure/SQLServerEmailAlertsToAdminsEnabled.py
checkov/terraform/checks/resource/azure/SQLServerThreatDetectionTypes.py
tests/terraform/checks/resource/azure/test_MySQLServerSSLEnforcementEnabled.py
tests/terraform/checks/resource/azure/test_PostgreSQLServerConnectionThrottlingEnabled.py
tests/terraform/checks/resource/azure/test_PostgreSQLServerLogCheckpointEnabled.py
tests/terraform/checks/resource/azure/test_PostgreSQLServerLogConnectionsEnabled.py
tests/terraform/checks/resource/azure/test_PostgreSQLServerSSLEnforcementEnabled.py
tests/terraform/checks/resource/azure/test_SQLServerAuditingEnabled.py
tests/terraform/checks/resource/azure/test_SQLServerAuditingRetention90Days.py
tests/terraform/checks/resource/azure/test_SQLServerEmailAlertsEnabled.py
tests/terraform/checks/resource/azure/test_SQLServerEmailAlertsToAdminsEnabled.py
tests/terraform/checks/resource/azure/test_SQLServerThreatDetectionTypes.py
tests/terraform/runner/resources/example/example.tf

Azure checks/database

---

checkov/terraform/checks/resource/gcp/AbsGoogleComputeFirewallUnrestrictedIngress.py
checkov/terraform/checks/resource/gcp/GoogleComputeFirewallUnrestrictedIngress22.py
checkov/terraform/checks/resource/gcp/GoogleComputeFirewallUnrestrictedIngress3389.py
tests/terraform/checks/resource/gcp/test_TestGoogleComputeFirewallUnrestrictedIngress22.py

Consolidate Google Firewall port checking and add case of vars

---

checkov/cloudformation/checks/resource/aws/cloudwatchLogGroupRetention.py
checkov/terraform/checks/resource/aws/cloudwatchLogGroupRetention.py
tests/cloudformation/checks/resource/aws/example_cloudwatchLogGroupRetention/example_cloudwatchLogGroupRetention-FAILED.json
tests/cloudformation/checks/resource/aws/example_cloudwatchLogGroupRetention/example_cloudwatchLogGroupRetention-FAILED.yaml
tests/cloudformation/checks/resource/aws/example_cloudwatchLogGroupRetention/example_cloudwatchLogGroupRetention-SUCCESS.json
tests/cloudformation/checks/resource/aws/example_cloudwatchLogGroupRetention/example_cloudwatchLogGroupRetention-SUCCESS.yaml
tests/cloudformation/checks/resource/aws/test_CloudwatchLogGroupRetention.py
tests/terraform/checks/resource/aws/test_CloudwatchLogGroupRetention.py

Thanks for the help! First time contributor here :)

#182 Ensure cloudwatchLogGroups specify retention

---

checkov/terraform/checks/resource/azure/MonitorLogProfileCategories.py
checkov/terraform/checks/resource/azure/MonitorLogProfileRetentionDays.py
checkov/terraform/checks/resource/azure/StorageAccountAzureServicesAccessEnabled.py
checkov/terraform/checks/resource/azure/StorageAccountDefaultNetworkAccessDeny.py
checkov/terraform/checks/resource/azure/StorageAccountLoggingQueueServiceEnabled.py
checkov/terraform/checks/resource/azure/StorageBlobServiceContainerPrivateAccess.py
tests/terraform/checks/resource/azure/test_MonitorLogProfileCategories.py
tests/terraform/checks/resource/azure/test_MonitorLogProfileRetentionDays.py
tests/terraform/checks/resource/azure/test_StorageAccountAzureServicesAccessEnabled.py
tests/terraform/checks/resource/azure/test_StorageAccountDefaultNetworkAccessDeny.py
tests/terraform/checks/resource/azure/test_StorageAccountLoggingQueueServiceEnabled.py
tests/terraform/checks/resource/azure/test_StorageBlobServiceContainerPrivateAccess.py
tests/terraform/runner/resources/example/example.tf

Azure checks/storage accounts & logging

---

checkov/terraform/checks/resource/azure/CutsomRoleDefinitionSubscriptionOwner.py
checkov/terraform/checks/resource/azure/KeyExpirationDate.py
checkov/terraform/checks/resource/azure/KeyvaultRecoveryEnabled.py
checkov/terraform/checks/resource/azure/SecretExpirationDate.py
tests/terraform/checks/resource/azure/test_CustomRoleDefinitionSubscriptionOwner.py
tests/terraform/checks/resource/azure/test_KeyExpirationDate.py
tests/terraform/checks/resource/azure/test_KeyVaultRecoveryEnabled.py
tests/terraform/checks/resource/azure/test_SecretExpirationDate.py
tests/terraform/runner/resources/example/example.tf

azure checks - iam & general

---

checkov/kubernetes/checks/ImageDigest.py
checkov/kubernetes/checks/ImagePullPolicyAlways.py
checkov/kubernetes/checks/ImageTagFixed.py
checkov/kubernetes/checks/KubernetesDashboard.py
checkov/kubernetes/checks/Tiller.py
checkov/kubernetes/parser/parser.py

fix k8 checks

---

checkov/terraform/checks/resource/azure/NetworkWatcherFlowLogPeriod.py
checkov/terraform/checks/resource/azure/StorageAccountAzureServicesAccessEnabled.py
tests/terraform/checks/resource/azure/test_NetworkWatcherFlowLogPeriod.py
tests/terraform/checks/resource/azure/test_StorageAccountAzureServicesAccessEnabled.py

CKV_AZURE_36 - fix

---

checkov/terraform/checks/resource/aws/SecurityGroupRuleDescription.py
tests/terraform/checks/resource/aws/test_SecurityGroupRuleDescription.py

Fix SG description check for terraform

---

checkov/terraform/checks/resource/aws/SecurityGroupRuleDescription.py
tests/terraform/checks/resource/aws/test_SecurityGroupRuleDescription.py

Reverts bridgecrewio/checkov#352

Revert "Fix SG description check for terraform"

---

checkov/terraform/checks/resource/azure/AzureInstancePassword.py
checkov/terraform/checks/resource/azure/PostgreSQLServerSSLEnforcementEnabled.py
checkov/terraform/checks/resource/azure/SecurityCenterContactEmailAlert.py
checkov/terraform/checks/resource/azure/SecurityCenterContactEmailAlertAdmins.py
checkov/terraform/checks/resource/azure/SecurityCenterContactPhone.py

Minor fixes to azure checks

---

README.md
checkov/cloudformation/runner.py
checkov/common/runners/base_runner.py
checkov/kubernetes/parser/parser.py
checkov/kubernetes/runner.py
checkov/terraform/parser.py

Ignore node_modules , .terraform and .serverless directories when parsing files

ignore common private directories

---

checkov/cloudformation/checks/resource/aws/SecurityGroupRuleDescription.py

Skip check if rule is not a dict

---

checkov/terraform/checks/resource/aws/SecurityGroupRuleDescription.py
tests/terraform/checks/resource/aws/test_SecurityGroupRuleDescription.py

fix issue https://github.com/bridgecrewio/checkov/issues/365

---

checkov/terraform/checks/resource/aws/CloudtrailMultiRegion.py
tests/terraform/checks/resource/aws/test_CloudtrailMultiRegion.py

add cloudtrail multi region validation
https://github.com/bridgecrewio/checkov/issues/362

add cloudtrail multi region validation

---

checkov/terraform/checks/resource/aws/RDSPubliclyAccessible.py
checkov/terraform/checks/resource/aws/S3PublicACLRead.py
checkov/terraform/checks/resource/aws/S3PublicACLWRITE.py
checkov/terraform/checks/resource/base_resource_negative_value_check.py
checkov/terraform/checks/resource/gcp/GKEDisableLegacyAuth.py
checkov/terraform/checks/resource/gcp/GoogleComputeExternalIP.py
checkov/terraform/checks/resource/gcp/GoogleComputeIPForward.py
checkov/terraform/checks/resource/gcp/GoogleComputeInstanceOSLogin.py
checkov/terraform/checks/resource/gcp/GoogleComputeSerialPorts.py
tests/terraform/checks/resource/gcp/test_GoogleComputeInstanceOSLogin.py

- Modified checks in gcp and aws to implement BaseResourceNegativeValueCheck instead of BaseResourceCheck
- Overridden the abstract methods when needed
- Added one more test case in test_GoogleComputeInstanceOSLogin.py

Created base_resource_negative_value_check.py

---

checkov/cloudformation/runner.py

verify parsed resource is a CFN resource

---

Pipfile
Pipfile.lock
setup.py

Update pyyaml to version 5.3.1 for security fix

---

checkov/kubernetes/checks/Seccomp.py

K8 Seccomp - ensure annotations is a dictionary 

---

checkov/terraform/checks/resource/aws/ALBListenerHTTPS.py

See #380 for more information.

:bug: Fix false-positive due to missing TLS check

---

checkov/terraform/checks/resource/gcp/GoogleComupteBlockProjectSSH.py

updated get_inspected_key path for CKV_GCP_32

---

checkov/terraform/checks/resource/gcp/GKEUseCosImage.py
tests/terraform/checks/resource/gcp/test_GKEUseCosImage.py

Check google_cluster_node_pools instead of the clusters for COS images

---

Pipfile.lock
checkov/kubernetes/runner.py

Fix k8s scan for malformed manifest (no metadata)

---

SECURITY.md

Initially discussed underer https://github.com/bridgecrewio/checkov/pull/396
** Edited by @nimrodkor 
Resolves #395

Adding SECURITY.MD

---

checkov/terraform/checks/resource/aws/LaunchConfigurationEBSEncryption.py
tests/terraform/checks/resource/aws/test_LaunchConfigurationEBSEncryption.py

following to the conversation in #392

CKV_AWS_8 - handle dynamic blocks

---

Pipfile.lock
checkov/common/bridgecrew/platform_integration.py
checkov/main.py
tests/common/test_platform_integration.py

Add the type for CI/CD.
The default value is still `cli`, in case it can be override by using orbs/github actions

WIP Add CI/CD type to PUT method

---

Pipfile.lock
checkov/common/bridgecrew/platform_integration.py
checkov/main.py
tests/common/test_platform_integration.py

Reverts bridgecrewio/checkov#399

Revert "WIP Add CI/CD type to PUT method"

---

docs/4.Integrations/gitlab.md

Add colored output example to gitlab.md

---

checkov/common/bridgecrew/platform_integration.py
tests/common/test_platform_integration.py

Fix guidelines URLs & add tests

---

checkov/common/output/record.py

Add styling to guidelines output

---

checkov/arm/__init__.py
checkov/arm/base_registry.py
checkov/arm/base_resource_check.py
checkov/arm/base_resource_value_check.py
checkov/arm/checks/StorageAccountsTransportEncryption.py
checkov/arm/checks/__init__.py
checkov/arm/context_parser.py
checkov/arm/registry.py
checkov/arm/runner.py
checkov/common/util/docs_generator.py
checkov/main.py
tests/arm/checks/example_StorageAccountsTransportEncryption/notes.txt
tests/arm/checks/example_StorageAccountsTransportEncryption/storageAccount-FAILED.json
tests/arm/checks/example_StorageAccountsTransportEncryption/storageAccount-FAILED2.json
tests/arm/checks/example_StorageAccountsTransportEncryption/storageAccount-PASSED.json
tests/arm/checks/example_StorageAccountsTransportEncryption/storageAccount-PASSED2.json
tests/arm/checks/example_StorageAccountsTransportEncryption/storageAccount-PASSED3.json
tests/arm/checks/example_StorageAccountsTransportEncryption/storageAccount-SKIPPED.json
tests/arm/checks/example_StorageAccountsTransportEncryption/storageAccount-SKIPPED2.json
tests/arm/checks/example_StorageAccountsTransportEncryption/storageAccount-SKIPPED3.json
tests/arm/checks/test_StorageAccountsTransportEncryption.py
tests/arm/test_scanner_registry.py

Add ARM Template Scanner

---

README.md
checkov/terraform/parser.py

Remove extra `open` call when falling to HCL1, README update

---

checkov/terraform/context_parsers/parsers/locals_context_parser.py
checkov/terraform/context_parsers/parsers/variable_context_parser.py

Validate enrichment block is a dictionary.
Handle: https://github.com/bridgecrewio/checkov/issues/414

add enrich protection

---

README.md
checkov/main.py

allow skipping guidelines api

---

checkov/terraform/checks/resource/azure/SQLServerAuditingRetention90Days.py
checkov/terraform/checks/resource/gcp/GoogleComputeDefaultServiceAccountFullAccess.py

Handle string instead of dict in 2 checks

---

checkov/arm/checks/StorageAccountsTransportEncryption.py
tests/arm/checks/example_StorageAccountsTransportEncryption/storageAccount-SKIPPED.json
tests/arm/checks/example_StorageAccountsTransportEncryption/storageAccount-SKIPPED2.json
tests/arm/checks/example_StorageAccountsTransportEncryption/storageAccount-SKIPPED3.json

Reuse Azure IDs for ARM templates

---

setup.py

https://github.com/bridgecrewio/checkov/issues/381

Bumping PyYaml

---

checkov/arm/context_parser.py
checkov/cloudformation/runner.py
checkov/terraform/evaluation/evaluation_methods/const_variable_evaluation.py

Handle assignment bug, unnamed variables, non-existent params

---

checkov/arm/checks/AKSApiServerAuthorizedIpRanges.py
checkov/arm/checks/AKSDashboardDisabled.py
checkov/arm/context_parser.py
checkov/arm/parser/__init__.py
checkov/arm/parser/cfn_json.py
checkov/arm/parser/cfn_yaml.py
checkov/arm/parser/node.py
checkov/arm/runner.py
tests/arm/checks/example_AKSApiServerAuthorizedIpRanges/aks-authIPRanges-preview-FAILED.json
tests/arm/checks/example_AKSApiServerAuthorizedIpRanges/aks-authIPRanges-preview-PASSED.json
tests/arm/checks/example_AKSApiServerAuthorizedIpRanges/aks-authIPRanges-supported-FAILED-2.json
tests/arm/checks/example_AKSApiServerAuthorizedIpRanges/aks-authIPRanges-supported-FAILED.json
tests/arm/checks/example_AKSApiServerAuthorizedIpRanges/aks-authIPRanges-supported-PASSED.json
tests/arm/checks/example_AKSApiServerAuthorizedIpRanges/aks-authIPRanges-unsupported-FAILED.json
tests/arm/checks/example_AKSDashboardDisabled/AKSDashboardDisabled-FAILED.json
tests/arm/checks/example_AKSDashboardDisabled/AKSDashboardDisabled-FAILED2.json
tests/arm/checks/example_AKSDashboardDisabled/AKSDashboardDisabled-FAILED3.json
tests/arm/checks/example_AKSDashboardDisabled/AKSDashboardDisabled-PASSED.json
tests/arm/checks/test_AKSApiServerAuthorizedIpRanges.py
tests/arm/checks/test_AKSDashboardDisabled.py

Fix template output to include last line
Correct parser to allow for null values
Add 2 additional checks

ARM Scanning Updates

---

checkov/common/bridgecrew/platform_integration.py
checkov/terraform/context_parsers/registry.py
tests/common/test_platform_integration.py

re add bc_source

---

checkov/common/output/report.py
checkov/terraform/checks/resource/gcp/AbsGoogleComputeFirewallUnrestrictedIngress.py
checkov/terraform/checks/resource/gcp/GKEMonitoringEnabled.py
checkov/terraform/checks/resource/gcp/GoogleCloudSqlBackupConfiguration.py
checkov/terraform/checks/resource/gcp/GoogleCloudSqlDatabasePublicallyAccessible.py
checkov/terraform/checks/resource/gcp/GoogleComputeDiskEncryption.py
checkov/terraform/checks/resource/gcp/GoogleComputeFirewallUnrestrictedIngress22.py
checkov/terraform/checks/resource/gcp/GoogleComputeFirewallUnrestrictedIngress3389.py
checkov/terraform/checks/resource/gcp/GoogleComputeProjectOSLogin.py
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlDatabasePublicallyAccessible.py
tests/terraform/checks/resource/gcp/test_TestGoogleComputeFirewallUnrestrictedIngress22.py
tests/terraform/checks/resource/gcp/test_TestGoogleComputeFirewallUnrestrictedIngress3389.py

1. Fixed handling of port ranges for `google_compute_firewall`
2. Refactor `GKEMonitoringEnabled` to a `BaseResourceNegativeValueCheck`
3. Fix `authorized_networks` on SQL databases to handle the possible list correctly
4. Refactor `GoogleComputeDiskEncryption` to a `BaseResourceValueCheck`
Also, adding the guideline to the github output

bugfix/Multiple GCP bugs

---

checkov/arm/checks/AKSLoggingEnabled.py
checkov/arm/checks/AKSNetworkPolicy.py
checkov/arm/checks/AKSRbacEnabled.py
checkov/arm/checks/AzureInstancePassword.py
checkov/arm/checks/AzureManagedDiscEncryption.py
tests/arm/checks/example_AKSLoggingEnabled/AKSLoggingEnabled-FAILED2.json
tests/arm/checks/example_AKSLoggingEnabled/aksLoggingEnabled-FAILED.json
tests/arm/checks/example_AKSLoggingEnabled/aksLoggingEnabled-PASSED.json
tests/arm/checks/example_AKSNetworkPolicy/aksNetworkPolicy-FAILED.json
tests/arm/checks/example_AKSNetworkPolicy/aksNetworkPolicy-FAILED2.json
tests/arm/checks/example_AKSNetworkPolicy/aksNetworkPolicy-FAILED3.json
tests/arm/checks/example_AKSNetworkPolicy/aksNetworkPolicy-PASSED.json
tests/arm/checks/example_AKSRbacEnabled/aksEnableRbac-FAILED.json
tests/arm/checks/example_AKSRbacEnabled/aksEnableRbac-FAILED2.json
tests/arm/checks/example_AKSRbacEnabled/aksEnableRbac-PASSED.json
tests/arm/checks/example_AzureInstancePassword/azureInstancePassword-FAILED.json
tests/arm/checks/example_AzureInstancePassword/azureInstancePassword-PASSED.json
tests/arm/checks/example_AzureInstancePassword/azureInstancePassword-PASSED2.json
tests/arm/checks/example_AzureManagedDiscEncryption/azureManagedDiscEncryption-FAILED.json
tests/arm/checks/example_AzureManagedDiscEncryption/azureManagedDiscEncryption-PASSED.json
tests/arm/checks/test_AKSLoggingEnabled.py
tests/arm/checks/test_AKSNetworkPolicy.py
tests/arm/checks/test_AKSRbacEnabled.py
tests/arm/checks/test_AzureInstancePassword.py
tests/arm/checks/test_AzureManagedDiscEncryption.py

Add 5 ARM checks

---

checkov/terraform/checks/resource/gcp/AbsGoogleComputeFirewallUnrestrictedIngress.py
tests/terraform/checks/resource/gcp/test_TestGoogleComputeFirewallUnrestrictedIngress22.py

Handle GCP firewall ports as int as well

---

checkov/arm/checks/SQLServerAuditingEnabled.py
checkov/arm/checks/SQLServerAuditingRetention90Days.py
checkov/arm/checks/SQLServerEmailAlertsEnabled.py
checkov/arm/checks/SQLServerEmailAlertsToAdminsEnabled.py
checkov/arm/checks/SQLServerNoPublicAccess.py
checkov/arm/checks/SQLServerThreatDetectionTypes.py
tests/arm/checks/example_SQLServerAuditingEnabled/sqlServerAuditingEnabled-PASSED.json
tests/arm/checks/example_SQLServerAuditingEnabled/sqlServerAuditingEnabled-TDE-FAILED.json
tests/arm/checks/example_SQLServerAuditingRetention90Days/sqlServerAuditingRetention90Days-FAILED2.json
tests/arm/checks/example_SQLServerAuditingRetention90Days/sqlServerAuditingRetention90Days-FAILED3.json
tests/arm/checks/example_SQLServerAuditingRetention90Days/sqlServerAuditingRetention90Days-PASSED.json
tests/arm/checks/example_SQLServerAuditingRetention90Days/sqlServerAuditingRetention90Days-TDE-FAILED.json
tests/arm/checks/example_SQLServerEmailAlertsEnabled/sqlServerEmailAlertsEnabled-FAILED.json
tests/arm/checks/example_SQLServerEmailAlertsEnabled/sqlServerEmailAlertsEnabled-PASSED.json
tests/arm/checks/example_SQLServerEmailAlertsToAdminsEnabled/sqlServerEmailAlertsToAdminsEnabled-FAILED.json
tests/arm/checks/example_SQLServerEmailAlertsToAdminsEnabled/sqlServerEmailAlertsToAdminsEnabled-PASSED.json
tests/arm/checks/example_SQLServerNoPublicAccess/sqlServerNoPublicAccess-TDE-FAILED.json
tests/arm/checks/example_SQLServerNoPublicAccess/sqlServerNoPublicAccess-TDE-PASSED.json
tests/arm/checks/example_SQLServerThreatDetectionTypes/sqlServerThreatDetectionTypes-FAILED.json
tests/arm/checks/example_SQLServerThreatDetectionTypes/sqlServerThreatDetectionTypes-PASSED.json
tests/arm/checks/example_SQLServerThreatDetectionTypes/sqlServerThreatDetectionTypes-PASSED2.json
tests/arm/checks/test_SQLServerAuditingEnabled.py
tests/arm/checks/test_SQLServerAuditingRetention90Days.py
tests/arm/checks/test_SQLServerEmailAlertsEnabled.py
tests/arm/checks/test_SQLServerEmailAlertsToAdminsEnabled.py
tests/arm/checks/test_SQLServerNoPublicAccess.py
tests/arm/checks/test_SQLServerThreatDetectionTypes.py

Adding ARM SQL Server Checks

---

checkov/terraform/checks/resource/aws/RedshiftClusterEncryption.py
tests/terraform/checks/resource/aws/test_RedshiftClusterEncryption.py

Fix Terraform Redshift Cluster Encryption Check

---

checkov/arm/checks/AppServiceIdentity.py
checkov/arm/checks/CustomRoleDefinitionSubscriptionOwner.py
checkov/arm/checks/StorageAccountAzureServicesAccessEnabled.py
checkov/arm/checks/StorageAccountDefaultNetworkAccessDeny.py
checkov/arm/checks/StorageAccountLoggingQueueServiceEnabled.py
checkov/arm/runner.py
tests/arm/checks/example_AppServiceIdentity/appServiceIdentity-FAILED.json
tests/arm/checks/example_AppServiceIdentity/appServiceIdentity-PASSED.json
tests/arm/checks/example_AppServiceIdentity/appServiceIdentity-PASSED2.json
tests/arm/checks/example_CustomRoleDefinitionSubscriptionOwner/example_customRoleDefinitionSubscriptionOwner-FAILED.json
tests/arm/checks/example_CustomRoleDefinitionSubscriptionOwner/example_customRoleDefinitionSubscriptionOwner-PASSED.json
tests/arm/checks/example_StorageAccountAzureServicesAccessEnabled/storageAccountAzureServicesAccessEnabled-FAILED.json
tests/arm/checks/example_StorageAccountAzureServicesAccessEnabled/storageAccountAzureServicesAccessEnabled-FAILED2.json
tests/arm/checks/example_StorageAccountAzureServicesAccessEnabled/storageAccountAzureServicesAccessEnabled-PASSED.json
tests/arm/checks/example_StorageAccountAzureServicesAccessEnabled/storageAccountAzureServicesAccessEnabled-PASSED2.json
tests/arm/checks/example_StorageAccountDefaultNetworkAccessDeny/storageAccountDefaultNetworkAccessDeny-FAILED.json
tests/arm/checks/example_StorageAccountDefaultNetworkAccessDeny/storageAccountDefaultNetworkAccessDeny-FAILED2.json
tests/arm/checks/example_StorageAccountDefaultNetworkAccessDeny/storageAccountDefaultNetworkAccessDeny-PASSED.json
tests/arm/checks/example_StorageAccountDefaultNetworkAccessDeny/storageAccountDefaultNetworkAccessDeny-PASSED2.json
tests/arm/checks/example_StorageAccountLoggingQueueServiceEnabled/exampleStorageAccountLoggingQueueServiceEnabled-Failed.json
tests/arm/checks/example_StorageAccountLoggingQueueServiceEnabled/exampleStorageAccountLoggingQueueServiceEnabled-Failed2.json
tests/arm/checks/example_StorageAccountLoggingQueueServiceEnabled/exampleStorageAccountLoggingQueueServiceEnabled-PASSED.json
tests/arm/checks/test_AppServiceIdentity.py
tests/arm/checks/test_CustomRoleDefinitionSubscriptionOwner.py
tests/arm/checks/test_StorageAccountAzureServicesAccessEnabled.py
tests/arm/checks/test_StorageAccountDefaultNetworkAccessDeny.py
tests/arm/checks/test_StorageAccountLoggingQueueServiceEnabled.py

Minor ARM runner update and add 5 new ARM checks

---

checkov/arm/checks/AppServiceAuthentication.py
checkov/arm/checks/AppServiceClientCertificate.py
checkov/arm/checks/AppServiceHTTPSOnly.py
checkov/arm/checks/AppServiceHttps20Enabled.py
checkov/arm/checks/AppServiceMinTLSVersion.py
tests/arm/checks/example_AppServiceAuthentication/appServiceAuthentication-FAILED.json
tests/arm/checks/example_AppServiceAuthentication/appServiceAuthentication-PASSED.json
tests/arm/checks/example_AppServiceAuthentication/appServiceAuthentication-PASSED2.json
tests/arm/checks/example_AppServiceClientCertificate/appServiceClientCertificate-FAILED.json
tests/arm/checks/example_AppServiceClientCertificate/appServiceClientCertificate-FAILED2.json
tests/arm/checks/example_AppServiceClientCertificate/appServiceClientCertificate-PASSED.json
tests/arm/checks/example_AppServiceClientCertificate/appServiceClientCertificate-PASSED2.json
tests/arm/checks/example_AppServiceHTTPSOnly/appServiceHTTPSOnly-FAILED.json
tests/arm/checks/example_AppServiceHTTPSOnly/appServiceHTTPSOnly-FAILED2.json
tests/arm/checks/example_AppServiceHTTPSOnly/appServiceHTTPSOnly-PASSED.json
tests/arm/checks/example_AppServiceHTTPSOnly/appServiceHTTPSOnly-PASSED2.json
tests/arm/checks/example_AppServiceHttps20Enabled/appServiceHttps20Enabled-FAILED.json
tests/arm/checks/example_AppServiceHttps20Enabled/appServiceHttps20Enabled-FAILED2.json
tests/arm/checks/example_AppServiceHttps20Enabled/appServiceHttps20Enabled-PASSED.json
tests/arm/checks/example_AppServiceMinTLSVersion/appServiceMinTLSVersion-FAILED.json
tests/arm/checks/example_AppServiceMinTLSVersion/appServiceMinTLSVersion-FAILED2.json
tests/arm/checks/example_AppServiceMinTLSVersion/appServiceMinTLSVersion-PASSED.json
tests/arm/checks/test_AppServiceAuthentication.py
tests/arm/checks/test_AppServiceClientCertificate.py
tests/arm/checks/test_AppServiceHTTPSOnly.py
tests/arm/checks/test_AppServiceHttps20Enabled.py
tests/arm/checks/test_AppServiceMinTLSVersion.py

Add 5 additional ARM checks

---

checkov/terraform/context_parsers/parsers/provider_context_parser.py
checkov/terraform/runner.py

Skip non-provider lines and do not change aliases

---

checkov/arm/parser/__init__.py

Validate ARM templates by using required keys

---

checkov/arm/parser/__init__.py

Verify template is not None before checking its fields

---

CONTRIBUTING.md
Pipfile
Pipfile.lock
checkov/common/goget/base_getter.py
checkov/common/goget/github/get_git.py
checkov/main.py
docs/2.Concepts/Custom Policies.md
docs/2.Concepts/Sharing Policies.md
setup.py
tests/common/goget/local_getter.py
tests/common/goget/test_goget_base.py

ability to load external checks from github repo

Policies sharing / Enable loading external checks from git

---

Dockerfile
kubernetes/Dockerfile

handle https://github.com/bridgecrewio/checkov/issues/460

add git to docker files

---

checkov/kubernetes/base_registry.py
checkov/kubernetes/runner.py

Updating Kubernetes Registry to allow black/whitelist by namespace

---

README.md

Updating readme for checks/skip-checks and kubernetes namespaces

---

checkov/common/bridgecrew/platform_integration.py

Change url

---

checkov/terraform/checks/resource/aws/IAMRoleAllowsPublicAssume.py
tests/terraform/checks/resource/aws/test_IAMRoleAllowsPublicAssume.py

Scan CKV_AWS_60 through all the statements

---

checkov/terraform/checks/resource/aws/MQBrokerNotPubliclyExposed.py
tests/terraform/checks/resource/aws/test_MQBrokerNotPubliclyExposed.py

----
Hi 👋 excited to put up my first checkov PR, hope I followed [all the guidelines](https://www.checkov.io/1.Introduction/Policies.html)!
This address issue https://github.com/bridgecrewio/checkov/issues/171.
How I got the next id:  `git grep -h -i -P -o ckv_aws_\(\\d+\) | sort | uniq`
Test plan: `pipenv run python -m coverage run -m pytest tests/terraform/checks/resource/aws`

171: add check for MQ Broker not publicly exposed

---

README.md

Fix README typo: “Terrafrom”

---

checkov/terraform/checks/module/base_module_check.py
checkov/terraform/checks/module/base_registry.py
checkov/terraform/checks/module/registry.py
checkov/terraform/context_parsers/parsers/module_context_parser.py
checkov/terraform/runner.py
tests/terraform/checks/module/registry/example_external_dir/extra_checks/ModuleCheck.py
tests/terraform/checks/module/registry/test_registry.py
tests/terraform/runner/resources/example/example.tf
tests/terraform/runner/resources/valid_tf_only_module_usage/example.tf
tests/terraform/runner/test_runner.py

This is my solution to #480.
I tested it locally using the check for which i requested the feature.

Enable checks for terraform module calls

---

checkov/common/bridgecrew/platform_integration.py

Add retry mechanism to platform integration

---

checkov/terraform/checks/resource/aws/IAMRoleAllowsPublicAssume.py
checkov/terraform/checks/resource/aws/S3AllowsAnyPrincipal.py
tests/terraform/checks/resource/aws/test_IAMRoleAllowsPublicAssume.py
tests/terraform/checks/resource/aws/test_S3AllowsAnyPrincipal.py

Adds checks for S3 policies and IAM assume role policies for statements allowing any principal.

Add any principal check

---

checkov/common/bridgecrew/platform_integration.py

Add web proxy support using https_proxy environment variable

---

checkov/common/checks/base_check_registry.py
checkov/common/output/report.py

`collections.defaultdict` provides an elegant way to initialise the value for a key on the fly.

Use defaultdict

---

checkov/terraform/checks/resource/azure/NSGRulePortAccessRestricted.py

Fix NSGRulePortAccessRestricted crashing on a terraform dynamic block

---

checkov/runner_filter.py
tests/common/test_runner_filter.py

Reverts bridgecrewio/checkov#502

Revert "allow external checks to be set using -c"

---

checkov/terraform/checks/resource/aws/SQSPolicy.py
tests/terraform/checks/resource/aws/test_SQSPolicy.py

Proposed fix for #179 check for ANY(*) principals in SQS Policy

---

checkov/serverless/parsers/parser.py
checkov/serverless/runner.py

Validate the CF sub template to be a dictionary (not referenced by a file)

SLS CF sub template bugfix

---

checkov/terraform/checks/resource/aws/RedshiftClusterLogging.py
tests/terraform/checks/resource/aws/test_RedshiftClusterLogging.py

Proposed fix for #173 - Check for AWS Redshift cluster logging enabled. 

---

checkov/terraform/checks/resource/aws/LaunchConfigurationEBSEncryption.py
tests/terraform/checks/resource/aws/test_LaunchConfigurationEBSEncryption.py

Tests and extra check to ensure no false negative on optional/missing TF block. 
See #496 

Increased test coverage and fix for #496

---

checkov/terraform/checks/resource/aws/DocDBEncryption.py
tests/terraform/checks/resource/aws/test_DocDBEncryption.py

Add DocDb encryption check check

---

checkov/terraform/checks/resource/aws/APIGatewayXray.py
tests/terraform/checks/resource/aws/test_APIGatewayXray.py

Add API GW Xray check

---

checkov/terraform/checks/resource/aws/GlobalAcceleratorAcceleratorFlowLogs.py
tests/terraform/checks/resource/aws/test_GlobalAcceleratorAcceleratorFlowLogs.py

Add global accelerator flow logs check

---

checkov/terraform/checks/resource/aws/AthenaDatabaseEncryption.py
tests/terraform/checks/resource/aws/test_AthenaDatabaseEncryption.py

Add Athena Database encryption check

---

checkov/terraform/checks/resource/aws/CodeBuildProjectEncryption.py
tests/terraform/checks/resource/aws/test_CodeBuildProjectEncryption.py

Add codebuild project encryption check

---

checkov/serverless/parsers/parser.py

fix access to index out of range for empty string

fix string index out of range error

---

checkov/common/goget/github/get_git.py

Delay error until used if not able to load.
Fixes: #533

Handle git not being present

---

checkov/common/runners/runner_registry.py
checkov/terraform/checks/resource/aws/LaunchConfigurationEBSEncryption.py
checkov/terraform/checks/resource/aws/SecurityGroupRuleDescription.py
tests/terraform/checks/resource/aws/test_LaunchConfigurationEBSEncryption.py

Fix false positive in LaunchConfigurationEBSEncryption (issue #532)

---

checkov/terraform/checks/resource/aws/IMDSv1Disabled.py
tests/terraform/checks/resource/aws/test_IMDSv1Disabled.py

Solves #152, for Terraform only.

:tada: Add IMDSv1 Disabled check

---

checkov/terraform/checks/resource/aws/MSKClusterEncryption.py
tests/terraform/checks/resource/aws/test_MSKClusterEncryption.py

Add MSK encryption check

---

checkov/common/runners/runner_registry.py
checkov/main.py

enable upstream runner

---

checkov/terraform/checks/resource/aws/MSKClusterLogging.py
tests/terraform/checks/resource/aws/test_MSKClusterLogging.py

Add msk logging check

---

checkov/arm/base_resource_check.py
checkov/cloudformation/checks/resource/base_resource_check.py
checkov/common/checks/base_check.py
checkov/kubernetes/base_spec_check.py
checkov/serverless/checks/base_function_check.py
checkov/terraform/checks/data/base_check.py
checkov/terraform/checks/provider/base_check.py
checkov/terraform/checks/resource/base_resource_check.py

See this conversation https://github.com/bridgecrewio/checkov/pull/487#discussion_r483925418

Provider should get the provider type

---

checkov/terraform/checks/resource/aws/APIGatewayAccessLogging.py

Add APIGW v2  access log check

---

checkov/terraform/checks/resource/aws/ElasticsearchDomainEnforceHTTPS.py
tests/terraform/checks/resource/aws/test_ElasticsearchDomainEnforceHTTPS.py

Add Elasticsearch HTTPS check

---

Pipfile.lock
checkov/arm/base_resource_value_check.py

Allows  overriding result in cases attribute doesn't exist for `BaseResourceValueCheck`

Allow passing if required attribute isn't set

---

checkov/terraform/checks/resource/aws/ElasticsearchDomainLogging.py
tests/terraform/checks/resource/aws/test_ElasticsearchDomainLogging.py

Add Elasticsearch Logging check

---

checkov/terraform/checks/resource/base_resource_value_check.py

Allow passing if required attribute isn't set for terraform

---

checkov/terraform/checks/resource/base_resource_value_check.py

Fail if attribute was found and value is not as expected

---

checkov/terraform/checks/resource/aws/AthenaWorkgroupConfiguration.py
tests/terraform/checks/resource/aws/test_AthenaWorkgroupConfiguration.py

Add Athena Workgroup config check

---

checkov/terraform/checks/resource/aws/CloudfrontDistributionLogging.py
tests/terraform/checks/resource/aws/test_CloudfrontDistributionLogging.py

Add Cloudfront logging check

---

checkov/terraform/checks/resource/gcp/GoogleCloudMySqlLocalInfileOff.py
checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogCheckpoints.py
checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogConnection.py
checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogDisconnection.py
checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogLockWaits.py
checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogMinDuration.py
checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogMinMessage.py
checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogTemp.py
checkov/terraform/checks/resource/gcp/GoogleCloudSqlServerContainedDBAuthentication.py
checkov/terraform/checks/resource/gcp/GoogleCloudSqlServerCrossDBOwnershipChaining.py
checkov/terraform/checks/resource/gcp/GoogleCloudSqlServerNoPublicIP.py
tests/terraform/checks/resource/gcp/test_GoogleCloudMySqlLocalInfileOff.py
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogCheckpoints.py
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogConnection.py
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogDisconnection.py
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogLockWaits.py
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogMinDuration.py
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogMinMessage.py
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogTemp.py
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlServerContainedDBAuthentication.py
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlServerCrossDBOwnershipChaining.py
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlServerNoPublicIP.py
tests/terraform/runner/resources/example/example.tf

Additional gcp cloud sql checks

---

checkov/terraform/checks/resource/gcp/GoogleCloudMySqlLocalInfileOff.py
checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogCheckpoints.py
checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogConnection.py
checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogDisconnection.py
checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogLockWaits.py
checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogMinDuration.py
checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogMinMessage.py
checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogTemp.py
checkov/terraform/checks/resource/gcp/GoogleCloudSqlServerContainedDBAuthentication.py
checkov/terraform/checks/resource/gcp/GoogleCloudSqlServerCrossDBOwnershipChaining.py
checkov/terraform/checks/resource/gcp/GoogleCloudSqlServerNoPublicIP.py
tests/terraform/checks/resource/gcp/test_GoogleCloudMySqlLocalInfileOff.py
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogCheckpoints.py
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogConnection.py
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogDisconnection.py
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogLockWaits.py
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogMinDuration.py
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogMinMessage.py
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogTemp.py
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlServerContainedDBAuthentication.py
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlServerCrossDBOwnershipChaining.py
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlServerNoPublicIP.py
tests/terraform/runner/resources/example/example.tf

11 new GCP Cloud SQL checks

---

checkov/arm/runner.py
checkov/cloudformation/runner.py
checkov/common/runners/base_runner.py
checkov/common/runners/runner_registry.py
checkov/kubernetes/runner.py
checkov/serverless/runner.py
checkov/terraform/context_parsers/base_parser.py
checkov/terraform/context_parsers/registry.py
checkov/terraform/runner.py

* Optional flag to disable collection of skip checks comments

Optional flag of collect skip comments

---

checkov/serverless/runner.py

Validate item is a dict

---

README.md
setup.py

add docs on supported python version to fix: https://github.com/bridgecrewio/checkov/issues/575

update docs python version

---

checkov/serverless/parsers/context_parser.py

A couple random attributes that should be copied from provider to function.

Additional attributes enriched from provider

---

Pipfile.lock
setup.py
tests/terraform/runner/resources/valid_tf_only_passed_checks/example.tf

closes https://github.com/bridgecrewio/checkov/issues/579

bump bc-python-hcl2

---

checkov/terraform/checks/resource/gcp/GoogleStorageBucketUniformAccess.py
tests/terraform/checks/resource/gcp/test_GoogleStorageBucketUniformAccess.py

ISSUE-589 fix for check CKV_GCP_29

---

Pipfile.lock
setup.py

Bump urllib3 version to 1.25.10

---

checkov/cloudformation/runner.py

Run __contains__ only if instance of dict_node

---

checkov/arm/parser/__init__.py

Avoid iterating through bad ARM files

---

Pipfile
Pipfile.lock
checkov/common/bridgecrew/platform_integration.py
checkov/common/util/banner.py
checkov/common/version_manager.py
checkov/main.py
setup.py

inspired by the flow of sls framework.

add version checker and enable signup

---

checkov/cloudformation/runner.py

Ensure valid cf templates are parsed

---

checkov/terraform/checks/resource/azure/NSGRulePortAccessRestricted.py
tests/terraform/checks/resource/azure/test_NSGRuleSSHAccessRestricted.py

Handle case where NSG rule is not a dict

---

checkov/terraform/runner.py

Minor performance improvement & added logging

---

checkov/terraform/checks/resource/aws/CodeBuildProjectEncryption.py
checkov/terraform/checks/resource/aws/EC2PublicIP.py
checkov/terraform/checks/resource/azure/NSGRulePortAccessRestricted.py
checkov/terraform/runner.py

Fix 3 parsing errors in checks

---

checkov/common/util/dict_utils.py
checkov/terraform/runner.py

Access inner dict directly instead of dpath.search

---

checkov/terraform/checks/resource/aws/DMSReplicationInstancePubliclyAccessible.py
tests/terraform/checks/resource/aws/test_DMSReplicationInstancePubliclyAccessible.py

This is my first contribution to the project.
Closes #163

Add DMS publicly accessible check

---

checkov/terraform/checks/resource/aws/ELBAccessLogs.py
checkov/terraform/checks/resource/aws/ELBv2AccessLogs.py
tests/terraform/checks/resource/aws/test_ELBAccessLogs.py
tests/terraform/checks/resource/aws/test_ELBv2AccessLogs.py

Add ELB access logs enabled check

---

checkov/terraform/checks/resource/aws/DocDBTLS.py
checkov/terraform/checks/resource/aws/ELBv2AccessLogs.py
tests/terraform/runner/resources/valid_tf_only_passed_checks/example.tf

1. Fix DocDBTLS to handle input maps
2. Refactor ELBv2AccessLogs to be `BaseResourceValueCheck`

Minor parsing fixes

---

checkov/cloudformation/checks/resource/aws/IAMRoleAllowAssumeFromAccount.py
tests/cloudformation/checks/resource/aws/example_IAMRoleAllowAssumeFromAccount/example_IAMRoleAllowAssumeFromAccount-FAILED.yml
tests/cloudformation/checks/resource/aws/example_IAMRoleAllowAssumeFromAccount/example_IAMRoleAllowAssumeFromAccount-PASSED.yml
tests/cloudformation/checks/resource/aws/test_IAMRoleAllowAssumeFromAccount.py

CKV_AWS_61 CFN implementation

---

checkov/cloudformation/checks/resource/aws/IAMRoleAllowAssumeFromAccount.py

fix parsing

---

checkov/terraform/runner.py

Evaluate variables on tf_definitions if context is not created

---

checkov/terraform/context_parsers/parsers/variable_context_parser.py

Add multiple variables to definitions context

---

checkov/terraform/context_parsers/base_parser.py

Do not iterate over bc_id_mapping if it is None

---

checkov/terraform/checks/resource/aws/GlueDataCatalogEncryption.py
tests/terraform/checks/resource/aws/test_GlueDataCatalogEncryption.py

add Glue catalog encryption check

---

README.md

relates to https://github.com/Homebrew/homebrew-core/pull/64401

docs: update brew install/upgrade instruction

---

.github/workflows/homebrew.yml

Follow up of #659, a repo token and homebrew-core would be needed.
cc @schosterbarak @nimrodkor

workflows: release to homebrew

---

.github/workflows/build.yml
.github/workflows/homebrew.yml

Revert homebrew workflow changes

---

checkov/arm/parser/cfn_yaml.py

Avoid crashing if key is not an str

---

docs/2.Concepts/Evaluate Terraform Plan.md

Minor spelling and corrections to plan scanning

---

checkov/terraform/checks/resource/aws/CodeBuildProjectEncryption.py
checkov/terraform/parser.py
tests/terraform/parser/resources/parser_scenarios/count_eval/main.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/fabric-net-firewall/main.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/fabric-net-firewall/outputs.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/fabric-net-firewall/variables.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/fabric-net-svpc-access/main.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/fabric-net-svpc-access/outputs.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/fabric-net-svpc-access/variables.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/network-peering/main.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/network-peering/outputs.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/network-peering/variables.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/routes-beta/main.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/routes-beta/outputs.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/routes-beta/variables.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/routes/main.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/routes/outputs.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/routes/variables.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/subnets-beta/main.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/subnets-beta/outputs.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/subnets-beta/variables.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/subnets/main.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/subnets/outputs.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/subnets/variables.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/vpc/main.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/vpc/outputs.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/modules/vpc/variables.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/outputs.tf
tests/terraform/parser/resources/parser_scenarios/count_eval/variables.tf
tests/terraform/parser/test_parser_scenarios.py

Avoid parser crashes on count.index

---

HomebrewFormula/checkov.rb
Pipfile
Pipfile.lock
setup.py

Add `packaging` to required packages.
Resolves #685

Fixed packaging problem

---

checkov/common/bridgecrew/platform_integration.py

Update dashboard integration flow and provide better feedback & support URL

---

checkov/terraform/plan_parser.py

Fix bug in plan hclifying

---

checkov/arm/context_parser.py

Fix failure in ARM templates #2

---

checkov/terraform/plan_parser.py
tests/terraform/runner/resources/plan_with_child_modules/tfplan.json
tests/terraform/runner/test_plan_runner.py

add child modules scanning. fix https://github.com/bridgecrewio/checkov/issues/691

add child module scanning for terraform plan analysis

---

checkov/terraform/plan_runner.py
tests/terraform/runner/test_plan_runner.py

If root folder is specified, scan the plan file that is expected in that folder

---

tests/terraform/module_loading/test_registry.py
tests/terraform/parser/resources/failing_module_address/registry_security_group.tf
tests/terraform/parser/test_parser_modules.py

Added tests for external module caching

---

checkov/kubernetes/checks/Seccomp.py
checkov/terraform/checks/resource/aws/ALBListenerHTTPS.py
tests/kubernetes/checks/example_Seccomp/pod-seccomp-PASSED3.yaml
tests/kubernetes/checks/test_Seccomp.py
tests/terraform/checks/resource/aws/test_ALBListenerHTTPS.py

Update ALB listener HTTPS and Seccomp checks

---

.github/workflows/security.yaml
checkov/arm/checks/NSGRulePortAccessRestricted.py
checkov/arm/checks/SQLServerNoPublicAccess.py
checkov/cloudformation/checks/resource/aws/AbsSecurityGroupUnrestrictedIngress.py
checkov/serverless/parsers/parser.py
checkov/serverless/runner.py
checkov/terraform/checks/resource/aws/EKSPublicAccessCIDR.py
checkov/terraform/checks/resource/azure/NSGRulePortAccessRestricted.py
checkov/terraform/checks/resource/azure/SQLServerNoPublicAccess.py
checkov/terraform/checks/resource/gcp/AbsGoogleComputeFirewallUnrestrictedIngress.py
checkov/terraform/checks/resource/gcp/GKEPublicControlPlane.py

fix security github action

---

checkov/cloudformation/checks/resource/aws/SNSTopicEncryption.py
checkov/cloudformation/checks/resource/aws/SQSQueueEncryption.py

Cfn checks refactor

---

checkov/cloudformation/checks/resource/aws/CloudwatchLogGroupEncryption.py
checkov/terraform/checks/resource/aws/CloudwatchLogGroupEncryption.py
tests/cloudformation/checks/resource/aws/example_CloudwatchLogGroupEncryption/CloudwatchLogGroupEncryption.json
tests/cloudformation/checks/resource/aws/example_CloudwatchLogGroupEncryption/CloudwatchLogGroupEncryption.yaml
tests/cloudformation/checks/resource/aws/test_CloudwatchLogGroupEncryption.py
tests/terraform/checks/resource/aws/example_CloudwatchLogGroupEncryption/cloudwatch.tf
tests/terraform/checks/resource/aws/test_CloudwatchLogGroupEncryption.py

Adds TF and CFN checks for cloudwatch log group encryption.

Add cloudwatch log encryption check

---

checkov/terraform/checks/resource/aws/AbsSecurityGroupUnrestrictedIngress.py
checkov/terraform/plan_parser.py

fix plan parsing for security groups coming from modules

---

checkov/terraform/checks/resource/aws/AuroraEncryption.py
tests/terraform/checks/resource/aws/test_AuroraEncryption.py

Terraform check for Aurora Encryption.
Issue: https://github.com/bridgecrewio/checkov/issues/139
Terraform docs: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#storage_encrypted
Note the details around whether Aurora Serverless is being used: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.how-it-works.html#aurora-serverless.snapshots
@nimrodkor  - Another one where there is an exception but otherwise just perform the check as a ValueCheck.  I should have sorted out my forkflow now so all of my commits aren't listed with each PR aswell 👍 .
**License**

check - tf - aurora encryption - CKV_AWS_96

---

checkov/terraform/checks/resource/aws/MSKClusterEncryption.py
tests/terraform/checks/resource/aws/test_MSKClusterEncryption.py

"_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._"
Confirmed that:
- Regression tests failed prior to fix
- Regression tests pass after the fix
See #747 for background

Fix false positive for MSK cluster encryption (closes #747)

---

checkov/terraform/checks/resource/aws/IAMRoleAllowAssumeFromAccount.py
checkov/terraform/checks/resource/aws/IAMRoleAllowsPublicAssume.py
tests/terraform/checks/resource/aws/test_IAMRoleAllowAssumeFromAccount.py
tests/terraform/checks/resource/aws/test_IAMRoleAllowsPublicAssume.py

Check for empty IAM role policies in scanned configuration

empty IAM role policies

---

checkov/cloudformation/checks/resource/aws/IAMRoleAllowAssumeFromAccount.py
tests/cloudformation/checks/resource/aws/example_IAMRoleAllowAssumeFromAccount/example_IAMRoleAllowAssumeFromAccount-PASSED-2.yml
tests/cloudformation/checks/resource/aws/test_IAMRoleAllowAssumeFromAccount.py

handle a case where the IAM role policy is a string and not a dict

IAMRoleAllowAssumeFromAccount CF check to handle string policies

---

checkov/terraform/checks/resource/aws/SagemakerEndpointConfigurationEncryption.py
checkov/terraform/checks/resource/aws/SagemakerNotebookEncryption.py
tests/terraform/checks/resource/aws/test_SagemakerEndpoinConfigurationEncryption.py
tests/terraform/checks/resource/aws/test_SagemakerNotebookEncryption.py

Add Sagemaker endpoint config encryption check

---

checkov/terraform/checks/resource/aws/ECSTaskDefinitionEFSVolumeEncryption.py
tests/terraform/checks/resource/aws/test_ECSTaskDefinitionEFSVolumeEncryption.py

Add ECS task definition EFS volume encryption in transit check

---

checkov/terraform/checks/resource/aws/EKSNodeGroupRemoteAccess.py
tests/terraform/checks/resource/aws/test_EKSNodeGroupRemoteAccess.py

EKS node group remote access check

---

Pipfile.lock
checkov/kubernetes/checks/CPULimits.py
checkov/kubernetes/checks/CPURequests.py
checkov/kubernetes/checks/MemoryLimits.py
checkov/kubernetes/checks/MemoryRequests.py
tests/kubernetes/checks/example_Requests_Limits/cronjob-request-limit-1FAILED.yaml
tests/kubernetes/checks/test_CPULimits.py
tests/kubernetes/checks/test_CPURequests.py
tests/kubernetes/checks/test_MemoryLimits.py
tests/kubernetes/checks/test_MemoryRequests.py

add check if exist 'resources'

---

.github/exclude-patterns.txt
checkov/terraform/plan_parser.py
tests/terraform/parser/resources/plan_tags/tfplan.json
tests/terraform/parser/test_plan_parser.py

Handle `tags` dictionary to be parsed accordingly to `hcl2` parser output

plan file parser tags handling

---

checkov/terraform/checks/resource/aws/CloudfrontDistributionEncryption.py

renamed key `ordered_cache_behaviour` to `ordered_cache_behavior`

Fixed typo in check CloudfrontDistributionEncryption

---

checkov/cloudformation/checks/resource/aws/CodeBuildProjectEncryption.py
tests/cloudformation/checks/resource/aws/example_CodeBuildProjectEncryption/CodeBuildProjectEncryption-FAILED.yaml
tests/cloudformation/checks/resource/aws/example_CodeBuildProjectEncryption/CodeBuildProjectEncryption-PASSED.yaml
tests/cloudformation/checks/resource/aws/test_CodeBuildProjectEncryption.py

Hey 🙂,
Bringing another CF check inline with TF.
Terraform check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/CodeBuildProjectEncryption.py
CloudFormation CodeBuild Project Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html
**License**

Check - CF - CodeBuildProjectEncryption inline withTF

---

README.md

Added requirements section
Added how to scan terraform plan in json
Added notes for Python 3.6 issues.
Please  feel free to edit for typo and  better expression

update requirements and usage

---

checkov/terraform/checks/resource/aws/NeptuneClusterLogging.py
tests/terraform/checks/resource/aws/test_NeptuneClusterLogging.py
tests/terraform/runner/test_plan_runner.py

Neptune Cluster Logging check

---

checkov/terraform/checks/resource/aws/EC2Credentials.py
checkov/terraform/checks/resource/aws/LambdaEnvironmentCredentials.py

BCS-79 Make the check titles more general, as they can triggered on more than just AWS secrets

---

checkov/common/bridgecrew/integration_features/features/fixes_integration.py

skip checkov checks that don't exist in the platform

---

checkov/common/bridgecrew/integration_features/features/fixes_integration.py
checkov/terraform/runner.py

fix local modules path

---

.github/workflows/build.yml
.github/workflows/pr-test.yml
integration_tests/test_checkov_json_report.py

handle https://github.com/bridgecrewio/checkov/issues/821

add multi suppression integration test

---

checkov/terraform/checks/resource/aws/AppLoadBalancerTLS12.py
tests/terraform/checks/resource/aws/test_AppLoadBalancerTLS12.py

fixes https://github.com/bridgecrewio/checkov/issues/837

allow port 80 in case of redirect

---

checkov/terraform/checks/resource/aws/ECSTaskDefinitionEFSVolumeEncryption.py

ECSTaskDefinitionEFSVolumeEncryption- fix spelling typo

---

.github/workflows/homebrew.yml
checkov/common/bridgecrew/integration_features/features/fixes_integration.py

add debug log for fixes response

---

checkov/terraform/checks/resource/aws/AbsSecurityGroupUnrestrictedIngress.py
checkov/terraform/checks/resource/aws/SecurityGroupRuleDescription.py

Add square brackets around indices in evaluated_keys paths

---

checkov/cloudformation/checks/resource/aws/ECSTaskDefinitionEFSVolumeEncryption.py
tests/cloudformation/checks/resource/aws/example_ECSTaskDefinitionEFSVolumeEncryption/ECSTaskDefinitionEFSVolumeEncryption-FAILED.yaml
tests/cloudformation/checks/resource/aws/example_ECSTaskDefinitionEFSVolumeEncryption/ECSTaskDefinitionEFSVolumeEncryption-PASSED.yaml
tests/cloudformation/checks/resource/aws/test_ECSTaskDefinitionEFSVolumeEncryption.py

Hello,
Implementing this check as already done for TF.
Terraform Check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/ECSTaskDefinitionEFSVolumeEncryption.py
CF Docs:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-volumes.html#cfn-ecs-taskdefinition-volume-efsvolumeconfiguration
**License**

CF - Check - ECS Task Def EFS Vol Encryption as in TF

---

checkov/terraform/checks/resource/azure/AKSApiServerAuthorizedIpRanges.py
tests/terraform/checks/resource/azure/test_AKSApiServerAuthorizedIpRanges.py

Fix tf check for AKSApiServerAuthorizedIpRanges

---

docs/4.Integrations/github-actions.md

The docs on GHA were out of date and pointed to my own repos and GHA and no the checkov official one

update docs to reflect current state and official GHA

---

checkov/terraform/checks/resource/aws/NeptuneClusterLogging.py
tests/terraform/checks/resource/aws/test_NeptuneClusterLogging.py

Fix CKV_AWS_101 - should pass sometimes

---

checkov/common/checks/base_check_registry.py
checkov/terraform/tag_providers/__init__.py
tests/terraform/runner/resources/malformed_857/main.tf
tests/terraform/runner/test_runner.py

Handle malformed input case

---

checkov/terraform/parser.py
tests/terraform/parser/resources/parser_scenarios/tfvars/expected.json
tests/terraform/parser/resources/parser_scenarios/tfvars/main.tf

Additional fixes to resolving indexed values, follow-up to #869

---

checkov/terraform/parser.py
tests/terraform/parser/resources/parser_scenarios/merge_function/expected.json
tests/terraform/parser/resources/parser_scenarios/merge_function/main.tf

Prevent str conversion of dict containing string with var substitution

---

Pipfile.lock
tests/terraform/parser/resources/parser_scenarios/colon/colon.tf
tests/terraform/parser/resources/parser_scenarios/colon/expected.json
tests/terraform/parser/test_parser_scenarios.py

fixes: https://github.com/bridgecrewio/checkov/issues/872

fix colon parsing

---

checkov/common/bridgecrew/platform_integration.py
tests/common/test_platform_integration.py

fix: https://github.com/bridgecrewio/checkov/issues/759

enable skipping mapping api call using BC_SKIP_MAPPING

---

Pipfile.lock
tests/terraform/parser/resources/parser_scenarios/ternaries/expected.json
tests/terraform/parser/resources/parser_scenarios/ternaries/main.tf

Reverts bridgecrewio/checkov#894

Revert "update python-hcl2 to handle ternaries new line"

---

checkov/kubernetes/checks/Seccomp.py
checkov/kubernetes/checks/SeccompPSP.py
checkov/kubernetes/runner.py
tests/kubernetes/runner/list_annotation/example.yaml
tests/kubernetes/runner/test_runner.py

Handle list-form metadata annotations for K8 configurations
Added UT

Handle list-form metadata annotations for K8 configurations

---

checkov/terraform/checks/resource/azure/AzureInstanceExtensions.py
tests/terraform/checks/resource/azure/test_AzureInstanceExtensions.py

Check VM instance extensions are not enabled

---

README.md

Ubuntu 18.04 installation guide

---

checkov/terraform/checks/resource/azure/AzureInstanceExtensions.py
checkov/terraform/checks/resource/azure/DiskEncryption.py
tests/terraform/checks/resource/azure/test_DiskEncryption.py

Also refactor the VM extensions into a `BaseResourceValueCheck`

Add Azure Disk Encryption Check

---

checkov/terraform/checks/resource/azure/MSSQLServerMinTLSVersion.py
tests/terraform/checks/resource/azure/test_MSSQLServerMinTLSVersion.py

Check that MSSqlServer uses TLS 1.2

Check for TLS 1.2

---

checkov/cloudformation/checks/resource/aws/ELBv2AccessLogs.py
tests/cloudformation/checks/resource/aws/example_ELBv2AccessLogs/ELBv2AccessLogs-FAILED.yml
tests/cloudformation/checks/resource/aws/example_ELBv2AccessLogs/ELBv2AccessLogs-PASSED.yml
tests/cloudformation/checks/resource/aws/test_ELBv2AccessLogs.py

Hello,
Implementing this check for CF as already done for TF.
Terraform: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/ELBv2AccessLogs.py
CF Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-loadbalancer-loadbalancerattributes.html
**License**

Check - CF - ELBv2AccessLogs

---

checkov/cloudformation/context_parser.py
tests/cloudformation/file_formats/json_with_space/test_json_with_space.json
tests/cloudformation/file_formats/json_with_tabs/test_json_with_tabs.json
tests/cloudformation/file_formats/test_json_with_space.py
tests/cloudformation/file_formats/test_json_with_tabs.py
tests/cloudformation/file_formats/test_yaml.py
tests/cloudformation/file_formats/yaml/test_yaml.yaml

See https://github.com/bridgecrewio/checkov/issues/904 for more details.

Fix issue running checkov on cloudformation + json + tabs (#904)

---

.github/workflows/build.yml

Update build.yml CI to match changes in pr-check CI

---

.github/workflows/build.yml

update build.yml to reflect changes to integration tests in test-pr

---

checkov/kubernetes/checks/Seccomp.py
tests/kubernetes/checks/example_Seccomp/pod-seccomp-FAILED2.yaml
tests/kubernetes/checks/test_Seccomp.py

SecComp k8 check fix

---

checkov/terraform/checks/resource/azure/MySQLServerMinTLSVersion.py
tests/terraform/checks/resource/azure/test_MySQLServerMinTLSVersion.py

For MYSQLSever check than min tls is 1.2

---

checkov/terraform/context_parsers/tf_plan/__init__.py

handle generic JSON error thrown when file is empty

---

checkov/terraform/checks/resource/azure/AzureManagedDiscEncryption.py
tests/terraform/checks/resource/azure/test_AzureManagedDiscEncryption.py

Addressed issue  https://github.com/bridgecrewio/checkov/issues/897

Ensure managed disk test also fails if not set #897

---

checkov/terraform/parser.py
checkov/terraform/parser_functions.py
checkov/terraform/parser_utils.py
tests/terraform/parser/resources/parser_scenarios/bogus_function/expected.json
tests/terraform/parser/resources/parser_scenarios/bogus_function/main.tf
tests/terraform/parser/resources/parser_scenarios/concat_function/expected.json
tests/terraform/parser/resources/parser_scenarios/concat_function/main.tf
tests/terraform/parser/test_parser_internals.py
tests/terraform/parser/test_parser_scenarios.py
tests/terraform/parser/test_parser_var_blocks.py

In addition, function handling has been reworked to be more concise and allow easier addition of new functions.
Note there are quite a few lines changed here, but most is just moving code around.

Support for the TF `concat` function

---

checkov/terraform/parser.py

Avoid None-type reference

---

checkov/terraform/parser_functions.py
checkov/terraform/parser_utils.py
tests/terraform/parser/resources/parser_scenarios/concat_function/expected.json
tests/terraform/parser/resources/parser_scenarios/concat_function/main.tf
tests/terraform/parser/resources/parser_scenarios/map_function/expected.json
tests/terraform/parser/resources/parser_scenarios/map_function/main.tf
tests/terraform/parser/test_parser_scenarios.py

Implementation of `map` function

---

Pipfile
Pipfile.lock
checkov/common/output/report.py
setup.py
tests/terraform/runner/extra_checks/S3EnvironmentCheck.py
tests/terraform/runner/resources/extra_check_test/s3.tf
tests/terraform/runner/test_runner.py

should fix https://github.com/bridgecrewio/checkov/issues/944

Add extra check test and bump packages

---

checkov/terraform/runner.py

Protection against None reference

---

checkov/terraform/checks/resource/aws/RedShiftSSL.py
tests/terraform/checks/resource/aws/test_RedShiftSSL.py

For Redshit clusters ensure that ssl is on - set it a param group

---

checkov/kubernetes/checks/AllowedCapabilities.py
checkov/kubernetes/checks/AllowedCapabilitiesSysAdmin.py
checkov/terraform/checks/resource/gcp/GoogleComputeDefaultServiceAccount.py
checkov/terraform/checks/resource/gcp/GoogleComputeDefaultServiceAccountFullAccess.py
checkov/terraform/context_parsers/parsers/locals_context_parser.py
checkov/terraform/parser.py
tests/kubernetes/checks/example_AllowedCapabilities/cassandra-FAILED.yaml
tests/kubernetes/checks/test_AllowedCapabilities.py
tests/terraform/checks/resource/gcp/test_GoogleComputeDefaultServiceAccountFullAccess.py
tests/terraform/context_parsers/test_locals_parser.py
tests/terraform/evaluation/resources/locals_evaluation/main.tf

Fix K8s failures, locals failures and GCP instance failures

---

checkov/cloudformation/checks/resource/aws/APIGatewayAuthorization.py
checkov/terraform/checks/resource/aws/APIGatewayAuthorization.py
tests/cloudformation/checks/resource/aws/example_APIGatewayAuthorization/APIGatewayAuthorization-FAILED.yaml
tests/cloudformation/checks/resource/aws/example_APIGatewayAuthorization/APIGatewayAuthorization-PASSED.yaml
tests/cloudformation/checks/resource/aws/test_APIGatewayAuthorization.py
tests/terraform/checks/resource/aws/test_APIGatewayAuthorization.py

fixes #960
NB: I couldn't figure out how to build it all **so this will need testing.** 

fixes #960 allow api key auth

---

checkov/kubernetes/checks/DropCapabilities.py
checkov/kubernetes/checks/MinimizeCapabilities.py
tests/kubernetes/checks/example_DropCapabilities/pod-drop-NET_RAW-capabilities-FAILED-MISSING.yaml
tests/kubernetes/checks/test_DropCapabilities.py
tests/kubernetes/checks/test_MinimizeCapabilities.py

Handle empty capabilities block

---

CONTRIBUTING.md

Add details on writing tests for checks

---

checkov/terraform/checks/resource/aws/AppLoadBalancerTLS12.py
tests/terraform/checks/resource/aws/example_AppLoadBalancerTLS12/main.tf
tests/terraform/checks/resource/aws/test_AppLoadBalancerTLS12.py

Fixes #966
I also changed the tests to the new syntax, I hope that's how it should be :)

Ignore TLS check for TCP, UDP and TCP_UDP protocol

---

checkov/cloudformation/checks/resource/aws/IAMCredentialsExposure.py
checkov/cloudformation/checks/resource/aws/IAMDataExfiltration.py
checkov/cloudformation/checks/resource/aws/IAMPermissionsManagement.py
checkov/cloudformation/checks/resource/aws/IAMPrivilegeEscalation.py
checkov/cloudformation/checks/resource/aws/IAMWriteAccess.py
checkov/terraform/checks/data/aws/IAMCredentialsExposure.py
checkov/terraform/checks/data/aws/IAMDataExfiltration.py
checkov/terraform/checks/data/aws/IAMPermissionsManagement.py
checkov/terraform/checks/data/aws/IAMPrivilegeEscalation.py
checkov/terraform/checks/data/aws/IAMWriteAccess.py
checkov/terraform/checks/utils/iam_cloudformation_document_to_policy_converter.py
tests/terraform/checks/data/aws/test_CloudSplainingCredentialsExposure.py
tests/terraform/checks/data/aws/test_CloudSplainingDataExfiltration.py
tests/terraform/checks/data/aws/test_CloudSplainingPrivilegeEscalation.py

fix #985 and cloudsplaining typo

fix 985 and cloudsplaining typo

---

checkov/cloudformation/checks/resource/BaseCloudsplainingIAMCheck.py
checkov/terraform/checks/data/BaseCloudsplainingIAMCheck.py

handle bad templates

---

checkov/cloudformation/checks/resource/aws/AbsSecurityGroupUnrestrictedIngress.py
checkov/terraform/checks/resource/aws/AbsSecurityGroupUnrestrictedIngress.py
tests/cloudformation/checks/resource/aws/example_SecurityGroupUnrestrictedIngress22/SecurityGroupUnrestrictedIngress22-FAILED-3.yaml
tests/cloudformation/checks/resource/aws/test_SecurityGroupUnrestrictedIngress22.py
tests/terraform/checks/resource/aws/test_SecurityGroupUnrestrictedIngress22.py

Check ipv6 cidr blocks

---

checkov/logging_init.py

Log to stderr instead of stdout

---

checkov/terraform/checks/utils/iam_terraform_document_to_policy_converter.py

related to: https://github.com/bridgecrewio/checkov/issues/1000
another fix is required to close the issue:  https://github.com/salesforce/cloudsplaining/pull/166

fix terraform iam policy converter

---

checkov/terraform/checks/resource/aws/RedShiftSSL.py
tests/terraform/checks/resource/aws/example_RedShiftSSL/main.tf
tests/terraform/checks/resource/aws/test_RedShiftSSL.py

The old method of testing checks was passing that which should fail. Revised.

flawed test and check failure

---

.github/stale.yml

activating stalebot with initial 6mo/14 days config

---

Pipfile
Pipfile.lock
setup.py
tests/terraform/checks/data/aws/test_CloudSplainingCredentialsExposure.py

fix https://github.com/bridgecrewio/checkov/issues/1000
and fix https://github.com/bridgecrewio/checkov/issues/990

bump cloudsplaining version

---

checkov/cloudformation/checks/resource/aws/GlueSecurityConfiguration.py
tests/cloudformation/checks/resource/aws/example_GlueSecurityConfiguration/GlueSecurityConfiguration-FAILED.yml
tests/cloudformation/checks/resource/aws/example_GlueSecurityConfiguration/GlueSecurityConfiguration-PASSED.yml
tests/cloudformation/checks/resource/aws/test_GlueSecurityConfiguration.py

Hello,
Creating this check for CloudFormation as already done for Terraform.
Terraform check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/GlueSecurityConfiguration.py
CF Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-securityconfiguration.html
**License**

CF - Check - GlueSecurityConfiguration

---

Pipfile
Pipfile.lock
checkov/terraform/parser.py
checkov/terraform/runner.py
setup.py

small perf enhancement

---

README.md

Update README for multiple skips

---

checkov/terraform/graph_builder/local_graph.py

Improve performance by reducing edge duplications

---

docs/1.Welcome/Feature Descriptions.md
docs/1.Welcome/Quick Start.md
docs/1.Welcome/Terms and Concepts.md
docs/1.Welcome/What is Checkov.md
docs/2.Basics/Reviewing Scan Results.md
docs/3.Custom Policies/Custom Policies Overview.md
docs/3.Custom Policies/Python Custom Policies.md
docs/3.Custom Policies/Sharing Custom Policies.md
docs/3.Custom Policies/YAML Custom Policies.md
docs/4.Integrations/Pre-Commit.md
docs/6.Contribution/Contribute Python-Based Policies.md
docs/6.Contribution/Contribute YAML-based Policies.md
docs/6.Contribution/Contribution Overview.md

Fix links docs

---

checkov/dockerfile/runner.py

skip non-dockerfiles with -f

---

checkov/terraform/checks/utils/utils.py
checkov/terraform/checks_infra/registry.py
checkov/terraform/plan_runner.py
tests/graph/terraform/graph_builder/test_local_graph.py
tests/graph/terraform/utils/test_utils.py

Capture calls to python and avoid running them

---

checkov/arm/runner.py
checkov/cloudformation/runner.py
checkov/dockerfile/runner.py
checkov/helm/runner.py
checkov/kubernetes/runner.py
checkov/serverless/runner.py
checkov/terraform/runner.py
tests/terraform/runner/test_runner.py

Remove runner filters param when calling load_external_checks

---

checkov/terraform/checks/resource/azure/AKSUsesAzurePoliciesAddon.py
tests/terraform/checks/resource/azure/test_AKSUsesAzurePoliciesAddon.py

CKV_AZURE_116: Fix Azure Policies check location

---

checkov/terraform/checks/resource/azure/NetworkWatcherFlowLogPeriod.py
tests/terraform/checks/resource/azure/test_NetworkWatcherFlowLogPeriod.py

Allow 0 for Network Watcher Flow Logs retention days

---

checkov/dockerfile/runner.py
tests/dockerfile/test_runner.py

Fixes #1057 . Very simple fix :)

Fix single file handling for docker runner

---

checkov/terraform/graph_builder/graph_components/blocks.py
tests/graph/terraform/graph_builder/graph_components/test_blocks.py

Run recursive update_inner_attribute only for lists and dicts

---

CONTRIBUTING.md
checkov/terraform/checks/resource/aws/VPCDefaultNetwork.py
tests/terraform/checks/resource/aws/test_VPCDefault.py
tests/terraform/checks/resource/aws/test_VPCDefaultNetwork.py

Original is #1031 , this has the fixed check ID.
Resolves #1034 , closes #1031
Thanks @ebrucucen!

Default VPC check with a fixed ID

---

checkov/terraform/checks/resource/aws/DynamoDBTablesEncrypted.py

Fixes #1085. I also adjusted the check category, which was incorrect before.

Adjust check name to reflect the usage of KMS

---

checkov/terraform/checks/resource/azure/CutsomRoleDefinitionSubscriptionOwner.py
checkov/terraform/checks/resource/azure/MonitorLogProfileCategories.py
checkov/terraform/checks/resource/azure/MonitorLogProfileRetentionDays.py
checkov/terraform/graph_builder/local_graph.py
tests/terraform/checks/resource/azure/test_CustomRoleDefinitionSubscriptionOwner.py
tests/terraform/checks/resource/azure/test_MonitorLogProfileCategories.py
tests/terraform/checks/resource/azure/test_MonitorLogProfileRetentionDays.py

Support '.' in resource name correctly

---

checkov/terraform/checks/resource/azure/KeyVaultEnablesFirewallRulesSettings.py
tests/terraform/checks/resource/azure/test_KeyVaultEnablesFirewallRulesSettings.py

Fix key vault ACL check name & implementation

---

checkov/common/runners/runner_registry.py
checkov/helm/runner.py
checkov/main.py
checkov/terraform/parser.py

Resolve issue #530, and a bug I found when resolving it. (See commit messages for more details.)

Replace exit calls with return (be callable from python)

---

checkov/terraform/graph_builder/graph_components/blocks.py

Break circular dependency

---

checkov/dockerfile/checks/ReferenceLatestTag.py
tests/dockerfile/checks/example_AddExists/failure/Dockerfile
tests/dockerfile/checks/example_HealthcheckExists/failure/Dockerfile
tests/dockerfile/checks/example_HealthcheckExists/success/Dockerfile
tests/dockerfile/checks/example_ReferenceLatestTag/failure_default_version_tag/Dockerfile
tests/dockerfile/checks/example_ReferenceLatestTag/failure_latest_version_tag/Dockerfile
tests/dockerfile/checks/example_ReferenceLatestTag/success/Dockerfile
tests/dockerfile/checks/example_ReferenceLatestTag/success_multi_stage/Dockerfile
tests/dockerfile/checks/example_UpdateNotAlone/failure/Dockerfile
tests/dockerfile/checks/example_UpdateNotAlone/success/Dockerfile
tests/dockerfile/checks/example_UserExists/failure/Dockerfile
tests/dockerfile/checks/example_UserExists/success/Dockerfile
tests/dockerfile/checks/test_AddExists.py
tests/dockerfile/checks/test_HealthcheckExists.py
tests/dockerfile/checks/test_ReferenceLatestTag.py
tests/dockerfile/checks/test_UpdateNotAlone.py
tests/dockerfile/checks/test_UserExists.py

Sorry for the inconvenience. My new check had the same problem, as the previous one, because of the way I tested them. I fixed it and also changed all the Docker tests to actually use the runner now. So for anyone else who will add a new check, he won't do the same mistake as I did 🙈

Refactor docker tests

---

bin/checkov
checkov/main.py

Exits using the code returned from `run`
https://github.com/bridgecrewio/checkov/issues/1111

Exit code fix

---

checkov/arm/checks/resource/StorageAccountAzureServicesAccessEnabled.py
tests/arm/checks/resource/example_StorageAccountAzureServicesAccessEnabled/storageAccountAzureServicesAccessEnabled-VARIABLE.json

Handle non-int value gracefully

---

checkov/cloudformation/checks/resource/aws/IMDSv1Disabled.py
tests/cloudformation/checks/resource/aws/example_IMDSv1Disabled/FAILED.yml
tests/cloudformation/checks/resource/aws/example_IMDSv1Disabled/PASSED.yml
tests/cloudformation/checks/resource/aws/test_IMDSv1Disabled.py

Hello,
Adding this check for cf as already implemented in tf:
TF Check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/IMDSv1Disabled.py
CF Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-metadataoptions.html
**License**

CF - Check - IMDSv1 Disabled

---

checkov/terraform/checks/resource/aws/ElasticCacheAutomaticBackup.py
tests/graph/terraform/graph_builder/test_graph_builder.py
tests/graph/terraform/resources/modules/registry_security_group_inner_module/main.tf
tests/terraform/checks/resource/aws/example_ElasticCacheAutomaticBackup/main.tf
tests/terraform/checks/resource/aws/test_ElasticCacheAutomaticBackup.py

Fixes #1129
I also changed the style of the test.

Fix CKV_AWS_134 check for memcached

---

checkov/terraform/checks/resource/azure/AKSUsesDiskEncryptionSet.py
tests/graph/terraform/graph_builder/test_graph_builder.py
tests/graph/terraform/resources/modules/registry_security_group_inner_module/main.tf
tests/terraform/checks/resource/azure/test_AKSUsesDiskEncryptionSet.py

Change negative approach to positive approach

Fix AKS uses disk encryption set check

---

setup.py

List Python 3.8, 3.9 in setup.py

---

checkov/common/checks/base_check.py
checkov/common/checks/base_check_registry.py
checkov/common/util/type_forcers.py
checkov/runner_filter.py
checkov/terraform/checks/resource/base_registry.py
checkov/terraform/checks/resource/base_resource_check.py
checkov/terraform/checks/resource/base_resource_negative_value_check.py
checkov/terraform/checks/resource/base_resource_value_check.py
mypy.ini
tests/terraform/checks/resource/aws/test_DynamoDBTablesEncrypted.py
tests/terraform/runner/extra_checks/S3EnvironmentCheck.py
tests/terraform/runner/test_runner.py

Step by step I will go through the code and add type hints to make it easier to understand what the methods are actually doing. I didn't want to create a huge PR with a lot of changes at once to make it easier to review it :)

Add type hints to Terraform base checks

---

checkov/terraform/checks_infra/checks_parser.py
checkov/terraform/checks_infra/solvers/attribute_solvers/contains_attribute_solver.py
tests/graph/terraform/checks_infra/attribute_solvers/contains_solver/TagIncludes.yaml
tests/graph/terraform/checks_infra/attribute_solvers/contains_solver/test_solver.py
tests/graph/terraform/resources/tag_includes/main.tf

Allow attribute contains to handle dicts and more

---

checkov/cloudformation/checks/resource/aws/IAMRoleAllowsPublicAssume.py
tests/cloudformation/checks/resource/aws/example_IAMRoleAllowsPublicAssume/FAILED.yml
tests/cloudformation/checks/resource/aws/example_IAMRoleAllowsPublicAssume/PASSED.yml
tests/cloudformation/checks/resource/aws/test_IAMRoleAllowsPublicAssume.py

Hello,
Implementing this check as already done for terraform.
Terraform check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/IAMRoleAllowsPublicAssume.py
CF Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
IAM Assume Role Policy Doc: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html
**License**

Check - CF - IAM Role Public Assume

---

checkov/terraform/checks_infra/registry.py

Attempts to fix 2 issues: #1162 & #1163

Fix graph registry loading by using os.path.expanduser

---

.github/workflows/build.yml
.github/workflows/pr-test.yml
Manifest.in
checkov/terraform/checks_infra/registry.py
integration_tests/test_checkov_json_report.py
setup.py

Include yaml checks in package + add IT

---

checkov/terraform/checks/graph_checks/aws/EIPAllocatedToVPCAttachedEC2.yaml
tests/graph/terraform/checks/resources/EIPAllocatedToVPCAttachedEC2/expected.yaml
tests/graph/terraform/checks/resources/EIPAllocatedToVPCAttachedEC2/main.tf

Fixes #1175 First time to write a YAML check, hope it is the right way to do it 😄

Fix CKV2_AWS_19 check to consider aws_eip_association

---

checkov/terraform/checks/resource/aws/AthenaWorkgroupEncryption.py
checkov/terraform/checks/resource/aws/CloudwatchLogGroupKMSKey.py
tests/terraform/checks/resource/aws/example_AthenaWorkgroupEncryption/main.tf
tests/terraform/checks/resource/aws/example_CloudwatchLogGroupKMSKey/main.tf
tests/terraform/checks/resource/aws/test_AthenaWorkgroupEncryption.py
tests/terraform/checks/resource/aws/test_CloudwatchLogGroupKMSKey.py

new rules: Cloudwatch Log Group Encryption and  AthenaWorkgroupEncryption check

---

checkov/common/multi_signature.py
checkov/common/util/type_forcers.py
checkov/terraform/checks/data/BaseCloudsplainingIAMCheck.py
checkov/terraform/checks/data/aws/AdminPolicyDocument.py
checkov/terraform/checks/data/aws/IAMCredentialsExposure.py
checkov/terraform/checks/data/aws/IAMDataExfiltration.py
checkov/terraform/checks/data/aws/IAMPermissionsManagement.py
checkov/terraform/checks/data/aws/IAMPrivilegeEscalation.py
checkov/terraform/checks/data/aws/IAMWriteAccess.py
checkov/terraform/checks/data/aws/StarActionPolicyDocument.py
checkov/terraform/checks/data/aws/__init__.py
checkov/terraform/checks/data/base_check.py
checkov/terraform/checks/data/base_registry.py
checkov/terraform/checks/module/base_module_check.py
checkov/terraform/checks/module/base_registry.py
mypy.ini

Next batch of type hints 😄 
I also improved the code in some parts, hope it is ok.

Add type hints to terraform.checks.data

---

INTHEWILD.md

NJG - In The Wild

---

bin/checkov

Suppress syntax warnings

---

checkov/terraform/checks/resource/gcp/GKESecureBootforShieldedNodes.py

This update resolves a KeyError I experienced using Checkov
```
checkov --version
2.0.131
checkov -f checkov/test_GKEEnsureIntegrityMonitoring/main.tf
```
> ERROR:checkov.terraform.checks.resource.gcp.GKESecureBootforShieldedNodes:Failed to run check: Ensure Secure Boot for Shielded GKE Nodes is Enabled for configuration: {'addons_config': [{'http_load_balancing': [{'disabled': ['var.http_load_balancing_disabled']}], 'network_policy_config': [{'disabled': ['var.network_policy_config_disabled']}]}], 'initial_node_count': [1], 'ip_allocation_policy': [{'cluster_ipv4_cidr_block': ['var.ip_allocation_policy["cluster_ipv4_cidr_block"]'], 'cluster_secondary_range_name': …

Fix CKV_GCP_68 KeyError

---

INTHEWILD.md

Add Steamhaus as user

---

.github/workflows/build.yml

Fixed integration tests in build workflow

---

checkov/common/graph/checks_infra/registry.py

Fix skip checks functionality for CKV2 checks

---

INTHEWILD.md

We use Checkov too

---

checkov/terraform/checks/graph_checks/aws/EC2hasVPC.yaml
tests/graph/terraform/checks/resources/EC2hasVPC/expected.yaml
tests/graph/terraform/checks/resources/EC2hasVPC/main.tf

Fixes #1205 I added two other scenarios for this check and changed the filer to point to the `aws_instance` resource, which makes more sense here.

Add different possibilities to check CKV2_AWS_17

---

INTHEWILD.md

Added myself (Madhu Akula) to INTHEWILD.md

---

checkov/terraform/checks/graph_checks/aws/SGAttachedToResource.yaml
tests/graph/terraform/checks/resources/SGAttachedToResource/expected.yaml
tests/graph/terraform/checks/resources/SGAttachedToResource/main.tf

Fixes #1219. I also added couple more, which I stumbled upon 😄

Add missing resources to SG check CKV2_AWS_5

---

tests/terraform/checks/resource/aws/test_IAMStarActionPolicyDocument.py

Fix CKV_AWS_63 UT

---

checkov/cloudformation/checks/resource/aws/RedShiftSSL.py
checkov/cloudformation/checks/resource/aws/RedshiftClusterEncryption.py
tests/cloudformation/checks/resource/aws/example_RedShiftSSL/RedShiftSSL-FAILED.yaml
tests/cloudformation/checks/resource/aws/example_RedShiftSSL/RedShiftSSL-PASSED.yaml
tests/cloudformation/checks/resource/aws/example_RedshiftClusterEncryption/RedshiftClusterEncryption-FAILED-2.yaml
tests/cloudformation/checks/resource/aws/example_RedshiftClusterEncryption/RedshiftClusterEncryption-FAILED.yaml
tests/cloudformation/checks/resource/aws/example_RedshiftClusterEncryption/RedshiftClusterEncryption-PASSED.yaml
tests/cloudformation/checks/resource/aws/test_RedShiftSSL.py

I added the already existing Terraform check also to CloudFormation and changed tests of Redshift encryption to incorporate the checking of the resources.

Add Redshift SSL check CKV_AWS_105 to CloudFormation

---

checkov/terraform/checks/graph_checks/aws/GuardDutyIsEnabled.yaml

fix typo in CKV2_AWS_3

---

checkov/terraform/checks/graph_checks/aws/VPCHasRestrictedSG.yaml
tests/graph/terraform/checks/resources/VPCHasRestrictedSG/expected.yaml
tests/graph/terraform/checks/resources/VPCHasRestrictedSG/main.tf
tests/graph/terraform/checks/test_yaml_policies.py

Ensure connectivity is actually denied

Ensure every default SG denies all networking

---

checkov/terraform/context_parsers/base_parser.py
tests/terraform/evaluation/resources/default_evaluation/variables.tf

Handle no space between word and '{'

---

checkov/common/util/type_forcers.py
checkov/terraform/checks/utils/utils.py
checkov/terraform/evaluation/base_variable_evaluation.py
checkov/terraform/graph_builder/graph_components/blocks.py
checkov/terraform/graph_builder/local_graph.py
checkov/terraform/parser_functions.py
checkov/terraform/tag_providers/__init__.py
checkov/terraform/tag_providers/aws.py
checkov/terraform/tag_providers/azure.py
checkov/terraform/tag_providers/gcp.py
checkov/terraform/variable_rendering/evaluate_terraform.py
checkov/terraform/variable_rendering/renderer.py
checkov/terraform/variable_rendering/safe_eval_functions.py

Next batch of type hints, I hope I added the correct types to the parameters 🙈

Add type hints to terraform evaluation

---

checkov/terraform/checks/resource/azure/StorageAccountAzureServicesAccessEnabled.py

Fix Azure SA services access check

---

checkov/terraform/context_parsers/base_parser.py
checkov/terraform/graph_builder/local_graph.py
tests/terraform/evaluation/resources/default_evaluation/variables.tf

Fix context parsing in case of missing spaces around "

---

checkov/terraform/context_parsers/base_parser.py
checkov/terraform/runner.py

If context not found, log & continue

---

checkov/common/util/type_forcers.py
checkov/terraform/checks/resource/aws/IAMAdminPolicyDocument.py
checkov/terraform/checks/resource/aws/IAMRoleAllowAssumeFromAccount.py
checkov/terraform/checks/resource/aws/IAMRoleAllowsPublicAssume.py
checkov/terraform/checks/resource/aws/IAMStarActionPolicyDocument.py
tests/terraform/checks/resource/aws/test_IAMStarActionPolicyDocument.py

Centralize IAM policy parsing

---

checkov/terraform/graph_builder/local_graph.py
checkov/terraform/variable_rendering/renderer.py
tests/graph/terraform/graph_builder/test_graph_builder.py
tests/graph/terraform/resources/module_rendering/example/modules/mock/main.tf
tests/graph/terraform/resources/module_rendering/example/modules/second-mock/main.tf
tests/graph/terraform/resources/module_rendering/example/stacks/s1/main.tf
tests/graph/terraform/resources/module_rendering/example/stacks/s2/main.tf
tests/graph/terraform/resources/variable_rendering/render_nested_modules/main.tf
tests/graph/terraform/runner/test_graph_builder.py
tests/graph/terraform/variable_rendering/test_renderer.py
tests/terraform/checks/resource/aws/test_CloudfrontDistributionLogging.py

Fix bug where some values weren't rendered randomly (depending on order of edges and vertices created)

Module rendering fixes

---

checkov/terraform/graph_builder/local_graph.py
checkov/terraform/variable_rendering/renderer.py
tests/graph/terraform/graph_builder/test_graph_builder.py
tests/graph/terraform/resources/module_rendering/example/modules/mock/main.tf
tests/graph/terraform/resources/module_rendering/example/modules/second-mock/main.tf
tests/graph/terraform/resources/module_rendering/example/stacks/s1/main.tf
tests/graph/terraform/resources/module_rendering/example/stacks/s2/main.tf
tests/graph/terraform/resources/variable_rendering/render_nested_modules/main.tf
tests/graph/terraform/runner/test_graph_builder.py
tests/graph/terraform/variable_rendering/test_renderer.py
tests/terraform/checks/resource/aws/test_CloudfrontDistributionLogging.py

Reverts bridgecrewio/checkov#1254

Revert "Module rendering fixes"

---

checkov/common/bridgecrew/platform_integration.py
checkov/common/runners/runner_registry.py
checkov/main.py

Added onboarding text changes to the script.
Also fixed the creation of the bc_integration class to make it a singleton.

Onboarding update

---

checkov/main.py

remove bc_integration arg

---

checkov/common/bridgecrew/image_scanning/docker_image_scanning_integration.py
checkov/common/bridgecrew/image_scanning/image_scanner.py

**Changes**
- Support CVEs that doesn't have publish date
- Remove twistcli after running

Support CVEs that doesn't have publish date

---

checkov/terraform/checks/data/aws/StarActionPolicyDocument.py
checkov/terraform/graph_builder/local_graph.py
checkov/terraform/variable_rendering/renderer.py
tests/graph/terraform/graph_builder/test_graph_builder.py
tests/graph/terraform/resources/module_rendering/example/modules/mock/main.tf
tests/graph/terraform/resources/module_rendering/example/modules/second-mock/main.tf
tests/graph/terraform/resources/module_rendering/example/stacks/s1/main.tf
tests/graph/terraform/resources/module_rendering/example/stacks/s2/main.tf
tests/graph/terraform/resources/variable_rendering/render_nested_modules/main.tf
tests/graph/terraform/runner/test_graph_builder.py
tests/graph/terraform/variable_rendering/test_renderer.py
tests/terraform/checks/data/aws/test_StarActionPolicyDocument.py
tests/terraform/checks/resource/aws/test_CloudfrontDistributionLogging.py

Fix unhandled operators in iam policy and apply fix to rendering

---

checkov/serverless/checks/function/aws/AWSCredentials.py

Handle case where function env is a string (SLS)

---

.github/workflows/build.yml

Updating the build workflow with integration tests introduced in #1248

Generate checkov_config_report_terragoat.json in build workflow

---

checkov/kubernetes/checks/ApiServerEncryptionProviders.py
checkov/kubernetes/checks/ApiServerEtcdCaFile.py
checkov/kubernetes/checks/ApiServerkubeletCertificateAuthority.py
checkov/kubernetes/checks/EtcdPeerFiles.py
checkov/kubernetes/checks/KubeletReadOnlyPort.py
checkov/kubernetes/checks/KubernetesDashboard.py
checkov/kubernetes/checks/Tiller.py
checkov/kubernetes/checks/k8s_check_utils.py

Handle null k8s commands gracefully

---

checkov/common/bridgecrew/image_scanning/docker_image_scanning_integration.py

**Changes**
- Support image scanning that don't find vulnerabilities

Support image scanning that don't find vulnerabilities

---

checkov/common/bridgecrew/image_scanning/docker_image_scanning_integration.py

Fix parse published date from Twistlock CLI

---

checkov/common/bridgecrew/platform_integration.py
checkov/main.py

In case checkov is used as follows - 
```
checkov -f ../goat/terragoat/terraform/aws/s3.tf -f ~/dev/goat/terragoat/terraform/azure/sql.tf --bc-api-key <hush-hush> --repo-id try_bridgecrew/terragoat
```
We will only persist the specific files to the platform.

Persist only specific files -f is used.

---

.github/workflows/build.yml
.github/workflows/pr-test.yml
checkov/common/output/report.py
integration_tests/test_checkov_junit_report.py
tests/common/output/test_junit_report.py

Some items inspired by #1059 
- Replaces`to_xml_string`
- Include `CheckId` in the check_name
- Add record file_path and file_line_range in the failure outputs if available
- Convert to fstrings
- Added tests

Enrich junit report and add tests

---

checkov/secrets/runner.py

Fix secret scanning iter method

---

checkov/terraform/checks/resource/aws/BackupVaultEncrypted.py
tests/terraform/checks/resource/aws/example_BackupVaultEncrypted/main.tf
tests/terraform/checks/resource/aws/test_BackupVaultEncrypted.py

Adding a rule to detect if an AWS Backup Vault has server-side encryption enabled

---

.github/workflows/build.yml
.github/workflows/pr-test.yml
.github/workflows/security.yaml
checkov/terraform/checks/resource/aws/BackupVaultEncrypted.py
checkov/terraform/checks/resource/aws/DynamoDBGlobalTableRecovery.py
tests/terraform/runner/test_runner.py

Run GHA using self-hosted runners

---

checkov/secrets/runner.py

fix secrets filepath and resource ID

---

checkov/secrets/runner.py
tests/secrets/resources/terraform_failed/main.tf
tests/secrets/test_runner.py

Create exactly 1 record per secret

---

checkov/common/output/report.py
checkov/terraform/checks/resource/base_resource_value_check.py
tests/common/runner_registry/plan_with_tf_modules_for_enrichment/log_group/main.tf
tests/common/runner_registry/plan_with_tf_modules_for_enrichment/main.tf
tests/common/runner_registry/plan_with_tf_modules_for_enrichment/providers.tf
tests/common/runner_registry/plan_with_tf_modules_for_enrichment/tfplan.json
tests/common/runner_registry/test_runner_registry_plan_enrichment.py
tests/terraform/runner/test_plan_runner.py

Fixes #1302 
I also fixed an issue in `base_resource_value_check.py`, which only happens in a Terraform plan, because the value can be `[None]` and therefore it is results in a passed check.

add local modules enrichment to tf plan

---

checkov/secrets/runner.py
tests/secrets/test_runner.py

Will be reintroduced later, once we are able to make them more relevant

Skip entropies and secret keyword as they are noisy for now

---

checkov/terraform/checks/resource/azure/DataFactoryUsesGitRepository.py
tests/terraform/checks/resource/azure/example_DataFactoryUsesGitRepository/main.tf
tests/terraform/checks/resource/azure/test_DataFactoryUsesGitRepository.py

Fixes #1143 
I also changed the tests to the new format.

adjust CKV_AZURE_103 check to consider VSTS config

---

checkov/common/output/baseline.py
checkov/common/output/report.py
checkov/common/runners/runner_registry.py
checkov/main.py

This is the first of 2 parts that will allow checkov users to create a baseline of violations, and then get alerted only on the delta between the baseline findings and the findings found on the specified work dir.
There's a TODO for implementing the parsing of the file to the object, to help the second part of this feature.

Support --create-baseline flag

---

checkov/secrets/runner.py

Thanks @KevinHock for the comments!

Secret scanning runner code refactor

---

.gitignore
checkov/common/output/baseline.py
checkov/common/output/report.py
checkov/common/runners/runner_registry.py
checkov/main.py

Adds the `--baseline` option to use baseline file analysis 
Only new failed/pass checks with respect to the baseline are reported

Baseline analysis

---

checkov/main.py

Baseline print reports fix

---

README.md
checkov/cloudformation/checks/resource/aws/BackupVaultEncrypted.py
tests/cloudformation/checks/resource/aws/example_BackupVaultEncrypted/FAIL.yaml
tests/cloudformation/checks/resource/aws/example_BackupVaultEncrypted/PASS.yaml
tests/cloudformation/checks/resource/aws/test_BackupVaultEncrypted.py

Hello,
CF check for this as in TF.
TF Check: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/BackupVaultEncrypted.py
CF Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-backup-backupvault.html
Also, readme.md section typo.
**License**

CF - Check - BackupVaultEncrypted

---

.github/workflows/pr-test.yml
checkov/common/bridgecrew/image_scanning/image_scanner.py
checkov/main.py

Create repo when docker image scanning

---

Dockerfile
setup.py

Hello,
* Dockerfile **down** to 3.7 to hopefully fully resolve https://github.com/bridgecrewio/checkov/pull/745 - Please see my latest comment on that issue for reasoning!
* V. minor change to a metadata link whilst investigating this stuff.
**License**

Dockerfile to Python 3.7

---

checkov/kubernetes/base_registry.py
checkov/terraform/checks/module/base_registry.py
checkov/terraform/checks/provider/base_registry.py
checkov/terraform/checks/resource/gcp/AbsGoogleImpersonationRoles.py

Removed redundant __init__ overridden methods.

---

Dockerfile
github_action_resources/checkov-problem-matcher-softfail.json
github_action_resources/checkov-problem-matcher.json
github_action_resources/entrypoint.sh

Merge Github Actions into dockerfile

---

checkov/dockerfile/runner.py

Fixes dockerfile line number parsing to show correct output lines

fix dockerfile line off-by-one issues

---

.github/workflows/build.yml
.github/workflows/pr-test.yml
checkov/common/bridgecrew/image_scanning/docker_image_scanning_integration.py
checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py
checkov/common/bridgecrew/integration_features/features/fixes_integration.py
checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
checkov/common/runners/runner_registry.py
checkov/common/util/data_structures_utils.py
checkov/common/util/http_utils.py
checkov/main.py
checkov/secrets/plugins/entropy_keyword_combinator.py
checkov/secrets/runner.py
checkov/terraform/runner.py
integration_tests/test_checkov_json_report.py
tests/common/utils/test_utils.py
tests/secrets/test_runner.py

* Implement detect-secret `BasePlugin` and re-use standard `detect-secrets` to create a less noisy entropy/keyword detector
* Some refactoring and de-camelcasing
* Enable secret scanning by default

Combined entropy-keyword secret scanning

---

checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py

Fixes an issue preventing `all` resource_type policies pulled from the platform APIs from being executed

pull scope/provider from platform policy

---

kubernetes/run_checkov.sh

checkov should honor arguments passed in kubernetes
Resolves #1329

resolve bridgecrewio/checkov#1329

---

checkov/cloudformation/checks/resource/aws/ECRPolicy.py
tests/cloudformation/checks/resource/aws/example_ECRPolicy/ECRPolicy_passed.json
tests/cloudformation/checks/resource/aws/test_ECRPolicy.py

handle ECR policy as string

---

checkov/terraform/module_loading/loaders/local_path_loader.py
tests/terraform/module_loading/test_registry.py

Remove support from local module with abs path as it isn't supported

---

checkov/terraform/checks/graph_checks/aws/Route53ARecordAttachedResource.yaml
tests/terraform/graph/checks/resources/Route53ARecordAttachedResource/expected.yaml
tests/terraform/graph/checks/resources/Route53ARecordAttachedResource/main.tf

fix filter to see only A records

---

checkov/cloudformation/checks/graph_checks/aws/MSKClusterLogging.yaml
checkov/cloudformation/checks/graph_checks/aws/SagemakerNotebookEncryption.yaml
checkov/cloudformation/graph_builder/graph_components/blocks.py
checkov/common/graph/graph_builder/graph_components/blocks.py
checkov/terraform/checks/resource/aws/SagemakerNotebookEncryption.py
checkov/terraform/graph_builder/graph_components/blocks.py
tests/cloudformation/graph/checks/resources/MSKClusterLogging/expected.yaml
tests/cloudformation/graph/checks/resources/MSKClusterLogging/template.yaml
tests/cloudformation/graph/checks/resources/SagemakerNotebookEncryption/expected.yaml
tests/cloudformation/graph/checks/resources/SagemakerNotebookEncryption/template.yaml
tests/cloudformation/graph/checks/test_yaml_policies.py
tests/cloudformation/graph/graph_builder/test_local_graph.py
tests/terraform/graph/graph_builder/graph_components/test_blocks.py

Created two CFN yaml checks:
* MSKClusterLogging: Ensure MSK Cluster logging is enabled
* SagemakerNotebookEncryption: Ensure all data stored in the Sagemaker Notebook is securely encrypted at rest
Created also infrastructure to test yaml policies using the CloudformationGraphManager.

Enable running yaml on graph checks

---

checkov/terraform/checks/graph_checks/aws/EIPAllocatedToVPCAttachedEC2.yaml
tests/terraform/graph/checks/resources/EIPAllocatedToVPCAttachedEC2/expected.yaml
tests/terraform/graph/checks/resources/EIPAllocatedToVPCAttachedEC2/main.tf

Add support for instance id being supplied by data or module reference.

adddata and module support - fixes #1206

---

checkov/terraform/checks/graph_checks/aws/Route53ARecordAttachedResource.yaml
tests/terraform/graph/checks/resources/Route53ARecordAttachedResource/expected.yaml
tests/terraform/graph/checks/resources/Route53ARecordAttachedResource/main.tf

Edge case where a data source is used to provide the ip address.
Fixes #1373

add support for data sources fixes #1373

---

checkov/kubernetes/checks/DropCapabilities.py
checkov/kubernetes/checks/MinimizeCapabilities.py
tests/kubernetes/checks/example_DropCapabilities/pod-drop-all-capabilities-PASSED2.yaml
tests/kubernetes/checks/test_DropCapabilities.py
tests/kubernetes/checks/test_MinimizeCapabilities.py

Fixes https://github.com/bridgecrewio/checkov/issues/1021

Fix issue in CKV_K8S_28 and CKV_K8S_37

---

checkov/cloudformation/checks/resource/aws/WorkspaceRootVolumeEncrypted.py
checkov/cloudformation/checks/resource/aws/WorkspaceUserVolumeEncrypted.py
tests/cloudformation/checks/resource/aws/example_WorkspaceRootVolumeEncrypted/FAIL.yaml
tests/cloudformation/checks/resource/aws/example_WorkspaceRootVolumeEncrypted/PASS.yaml
tests/cloudformation/checks/resource/aws/example_WorkspaceUserVolumeEncrypted/FAIL.yaml
tests/cloudformation/checks/resource/aws/example_WorkspaceUserVolumeEncrypted/PASS.yaml
tests/cloudformation/checks/resource/aws/test_WorkspaceRootVolumeEncrypted.py
tests/cloudformation/checks/resource/aws/test_WorkspaceUserVolumeEncrypted.py

Hello,
Adding checks for workspaces for CF as done for TF.
CF Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-workspaces-workspace.html
TF Checks:
* https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/WorkspaceRootVolumeEncrypted.py
* https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/WorkspaceUserVolumeEncrypted.py
**License**

CF - Checks - WorkSpaces

---

checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py

Parse only custom BC policies to run alongside built in checkov checks

---

checkov/common/output/report.py

Added the guideline to the message result for junitxml so that it shows up in AWS and CircleCI processed results etc.
Fixes #1351

Added guideline to result message for junitxml

---

docs/2.Basics/Handling Variables.md

Error in value of variable for pass use case

---

checkov/terraform/parser.py
tests/terraform/graph/graph_builder/test_terraform_graph_parser.py

Improve cleanup of non native types from tf parser

---

INTHEWILD.md

Adding Royal Vopak N.V.

---

checkov/terraform/parser.py

Convert a set to a list when decoding TF configurations

---

checkov/common/checks_infra/solvers/attribute_solvers/contains_attribute_solver.py

Safely load an attribute with json.loads if attribute is of str instance in contains_attribute

Safely load an attribute with json.loads if attribute is of str instance

---

Dockerfile

Build helm3 binary into Docker image

---

checkov/cloudformation/runner.py
checkov/terraform/graph_builder/local_graph.py
tests/terraform/graph/graph_builder/test_local_graph.py
tests/terraform/graph/resources/modules/same_var_names/main.tf
tests/terraform/graph/resources/modules/same_var_names/module1/main.tf
tests/terraform/graph/resources/modules/same_var_names/module1/variables.tf
tests/terraform/graph/resources/modules/same_var_names/module2/main.tf
tests/terraform/graph/resources/modules/same_var_names/module2/variables.tf
tests/terraform/graph/resources/modules/same_var_names/submodule1/variables.tf
tests/terraform/graph/resources/modules/same_var_names/submodule2/variables.tf
tests/terraform/graph/resources/modules/same_var_names/variables.tf

Also, moving cfn context building into "build only if not given from external source" `if`

Fix module->variable eval to select correct source variable

---

checkov/cloudformation/checks/resource/aws/ALBListenerHTTPS.py
checkov/terraform/graph_builder/local_graph.py

Handle missing prop in ALBListenerHTTPS.py and handle NIE gracefully

---

checkov/cloudformation/cfn_utils.py
checkov/cloudformation/checks/resource/base_registry.py
checkov/cloudformation/context_parser.py
checkov/cloudformation/graph_builder/graph_components/block_types.py
checkov/cloudformation/graph_builder/graph_components/blocks.py
checkov/cloudformation/graph_builder/local_graph.py
checkov/cloudformation/graph_manager.py
checkov/cloudformation/parser/__init__.py
checkov/cloudformation/runner.py
checkov/common/checks/base_check.py
checkov/common/checks/base_check_registry.py
checkov/common/graph/graph_builder/graph_components/blocks.py
checkov/common/graph/graph_builder/local_graph.py
checkov/common/runners/base_runner.py
checkov/common/typing.py
checkov/terraform/graph_builder/graph_components/block_types.py

I hope I didn't miss anything after rebasing and reworking a couple of things after the newly introduced changes.

clean up CFN graph logic; add type hints

---

checkov/cloudformation/checks/resource/aws/VPCEndpointAcceptanceConfigured.py
tests/cloudformation/checks/resource/aws/example_VPCEndpointAcceptanceConfigured/FAIL.yaml
tests/cloudformation/checks/resource/aws/example_VPCEndpointAcceptanceConfigured/PASS.yaml
tests/cloudformation/checks/resource/aws/test_VPCEndpointAcceptanceConfigured.py

Hello,
Check for CF as done for TF.
* TF - https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/VPCEndpointAcceptanceConfigured.py
* CF Doc - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html
**License**

CF - Check - VPCEndpointAcceptanceConfiguration

---

Pipfile
Pipfile.lock
checkov/cloudformation/graph_builder/graph_to_definitions.py
checkov/cloudformation/runner.py

1. Fixed CFN graph to be created only if context or definitions or breadcrumbs are none
2. Line range and code for each resource are fetched using the definition context

CFN line range and code fetched with definitions context

---

Pipfile.lock

bump pipenv packages
- Auto-generated by [pipenv-update github action](.github/workflows/pipenv-update.yml)

[AUTO-PR] Update pipenv packages

---

docs/1.Welcome/What is Checkov.md

Fix typo in What is Checkov.md

---

checkov/terraform/checks/graph_checks/aws/PostgresRDSHasQueryLoggingEnabled.yaml
tests/terraform/graph/checks/resources/PostgresRDSHasQueryLoggingEnabled/expected.yaml
tests/terraform/graph/checks/resources/PostgresRDSHasQueryLoggingEnabled/main.tf
tests/terraform/graph/checks/test_yaml_policies.py

Postgres RDS has Query Logging enabled

---

checkov/common/graph/graph_builder/graph_components/attribute_names.py

Added attributes attribute to attribute_names

---

checkov/common/bridgecrew/platform_integration.py

Convert sequential call to persisting repository files to a concurrent call.

Persist repository files concurrently to Bridgecrew

---

checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py

Change the run function in BaseAttributeSolver to use threads in order to make it faster.

Use threads for running the BaseAttributeSolver.

---

.github/workflows/build.yml

Two tests. One -d and one -f to test with bc_api_key

Added tests for bc-api-key

---

checkov/terraform/checks/graph_checks/aws/SGAttachedToResource.yaml
tests/terraform/graph/checks/resources/SGAttachedToResource/expected.yaml
tests/terraform/graph/checks/resources/SGAttachedToResource/main.tf

addresses https://github.com/bridgecrewio/checkov/issues/1438

Add emr coverage to CKV2_AWS_5  fix for #1438

---

Pipfile.lock
checkov/terraform/variable_rendering/renderer.py

Handle unhashable evaluated values

---

checkov/terraform/checks/resource/aws/EMRClusterKerberosAttributes.py
tests/terraform/checks/resource/aws/test_EMRClusterKerberosAttributes.py

fix default response for CVK_AWS_114

---

checkov/cloudformation/graph_builder/graph_components/block_types.py
checkov/cloudformation/graph_builder/graph_to_definitions.py
checkov/cloudformation/graph_builder/local_graph.py
tests/cloudformation/graph/graph_builder/test_local_graph.py
tests/cloudformation/test_graph_manager.py

Add Parameter, Output and Condition nodes to CFN graph

---

checkov/cloudformation/graph_builder/local_graph.py
tests/cloudformation/graph/graph_builder/test_local_graph.py
tests/cloudformation/test_graph_manager.py

Add mappings nodes to cfn graph & minor refactor

---

.github/workflows/build.yml
.github/workflows/pr-test.yml
integration_tests/prepare_data.sh
integration_tests/test_checkov_cli_integration_report.py

add api key integration test

---

checkov/kubernetes/runner.py
checkov/terraform/parser.py

Handle key errors in malformed templates gracefully

---

checkov/common/bridgecrew/bc_source.py

add kubernetesWorkloads as a source

---

checkov/cloudformation/cfn_utils.py
checkov/kubernetes/runner.py

Handle potential ValueError exceptions of malformed YAML files

Handle potential ValueError exceptions of malformed YAML files

---

checkov/terraform/checks/graph_checks/aws/PostgresRDSHasQueryLoggingEnabled.yaml
tests/terraform/graph/checks/resources/PostgresRDSHasQueryLoggingEnabled/expected.yaml
tests/terraform/graph/checks/resources/PostgresRDSHasQueryLoggingEnabled/main.tf

correctly filters out anything that isnt postgres on rds logging check

---

.github/workflows/build.yml
checkov/common/util/docs_generator.py

add secrets to list command

---

.github/workflows/pr-test.yml
checkov/common/bridgecrew/platform_integration.py
integration_tests/prepare_data.sh
integration_tests/test_checkov_cli_integration_report.py

Fix Integration Tests consistency

---

checkov/cloudformation/checks/resource/aws/QLDBLedgerDeletionProtection.py
checkov/terraform/checks/resource/aws/QLDBLedgerDeletionProtection.py
tests/cloudformation/checks/resource/aws/example_QLDBLedgerDeletionProtection/FAIL.yaml
tests/cloudformation/checks/resource/aws/example_QLDBLedgerDeletionProtection/PASS.yaml
tests/cloudformation/checks/resource/aws/test_QLDBLedgerDeletionProtection.py
tests/terraform/checks/resource/aws/example_QLDBLedgerDeletionProtection/main.tf
tests/terraform/checks/resource/aws/test_QLDBLedgerDeletionProtection.py

Deletion protection is enabled by default, so this checks, that no one disabled it 🙂

add check CKV_AWS_172 for QLDB deletion protection

---

checkov/arm/runner.py

Check if ARM resource is dictionary

---

checkov/cloudformation/checks/resource/base_resource_value_check.py

Add evaluated keys impl. to CFN base_resource_value_check.py

---

checkov/cloudformation/checks/resource/aws/IAMRoleAllowAssumeFromAccount.py

remove duplications from check

---

checkov/cloudformation/cfn_utils.py
checkov/cloudformation/context_parser.py
checkov/cloudformation/graph_builder/graph_components/block_types.py
checkov/cloudformation/graph_builder/graph_to_definitions.py
checkov/cloudformation/graph_builder/local_graph.py
checkov/cloudformation/graph_manager.py
checkov/cloudformation/runner.py
tests/cloudformation/graph/graph_builder/test_local_graph.py
tests/cloudformation/test_graph_manager.py

Re-add Ref vertices

---

Dockerfile

Reverts bridgecrewio/checkov#1499
Breaks the github action, see #1503 
Will require more investigation before implementing

Revert "Update Dockerfile to run as a non-root user "

---

checkov/terraform/checks/graph_checks/aws/SGAttachedToResource.yaml
tests/terraform/graph/checks/resources/SGAttachedToResource/expected.yaml
tests/terraform/graph/checks/resources/SGAttachedToResource/main.tf

Fix CKV2_AWS_5 to for SGs attached to aws_cloudwatch_event_target

---

docs/4.Integrations/GitLab CLI.md

[doc/gitlab] add spaces to gitlab-ci.yml examples

---

Pipfile.lock
checkov/terraform/checks/graph_checks/aws/SubnetHasACL.yaml
tests/terraform/graph/checks/resources/SubnetHasACL/expected.yaml
tests/terraform/graph/checks/resources/SubnetHasACL/main.tf

VPC has a NACL by default, no need to fail if no NACL was manually defined

---

Pipfile
checkov/common/bridgecrew/image_scanning/image_scanner.py
setup.py

Optional skipping flag for docker image name extraction

Optional skipping flag for docker image name extraction

---

checkov/common/bridgecrew/image_scanning/image_scanner.py

Refactor Docker image scanner class

---

checkov/common/runners/runner_registry.py
checkov/main.py

Reverts bridgecrewio/checkov#1544
Seems to break the behavior when using an API key

Revert "Added functionality for multiple output formats"

---

checkov/common/runners/runner_registry.py
checkov/main.py

Reverts bridgecrewio/checkov#1554

Re-add "Added functionality for multiple output formats"

---

checkov/arm/checks/resource/CosmosDBDisableAccessKeyWrite.py
checkov/terraform/checks/resource/azure/CosmosDBDisableAccessKeyWrite.py
tests/arm/checks/resource/example_CosmosDBDisableAccessKeyWrite/CosmosDBDisableAccessKeyWrite-FAILED.json
tests/arm/checks/resource/example_CosmosDBDisableAccessKeyWrite/CosmosDBDisableAccessKeyWrite-PASSED.json
tests/arm/checks/resource/test_CosmosDBDisableAccessKeyWrite.py
tests/terraform/checks/resource/azure/test_CosmosDBDisableAccessKeyWrite.py

Add Cosmosdb checks

---

README.md
checkov/common/graph/graph_builder/utils.py
checkov/common/runners/base_runner.py

this should fix: https://github.com/bridgecrewio/checkov/issues/1312

move hidden dir to: IGNORED_DIRECTORIES_ENV

---

checkov/cloudformation/checks/resource/aws/DynamoDBTablesEncrypted.py
tests/cloudformation/checks/resource/aws/example_DynamoDBTablesEncrypted/FAILED.yaml
tests/cloudformation/checks/resource/aws/example_DynamoDBTablesEncrypted/PASSED.yaml
tests/cloudformation/checks/resource/aws/test_DynamoDBTablesEncrypted.py

Hello,
Adding this check for CF as done for TF.
CF Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-ssespecification.html
TF: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/DynamoDBTablesEncrypted.py
**License**

Check - CF - DynamoDBTablesEncrypted

---

checkov/terraform/checks/resource/azure/NSGRuleUDPAccessRestricted.py
tests/terraform/checks/resource/azure/test_NSGRuleUDPAccessRestricted.py

Azure NSG UPD rule check - ensure parsed rules are dictionaries

---

github_action_resources/entrypoint.sh

quote args in entrypoint command

---

checkov/common/runners/runner_registry.py

Fixes #1580 
Also added missing type hints 🙂

fix multi framework output

---

checkov/common/runners/runner_registry.py
checkov/main.py
docs/2.Basics/CLI Command Reference.md
tests/common/runner_registry/test_runner_registry_plan_enrichment.py

Re-opening from #1597 after rebasing from master per @schosterbarak's request.
This aims to address what I referred to in my comment at the end of #560 , wishing to enable multiple enrichment source directories.
The unit tests pass, please let me know if I need to do anything else, thanks!

Multiple enrichment sources

---

checkov/common/models/consts.py
checkov/terraform/checks/provider/__init__.py
checkov/terraform/checks/provider/bridgecrew/__init__.py
checkov/terraform/checks/provider/bridgecrew/credentials.py
tests/terraform/checks/provider/bridgecrew/test_credentials.py

new provider checks for bridgecrew

---

checkov/serverless/parsers/context_parser.py
tests/serverless/checks/test_check_types.py
tests/serverless/runner/resources/serverless.yaml
tests/serverless/runner/test_runner.py

Handle type mismatch gracefully for provider and func attributes

---

checkov/terraform/checks/graph_checks/aws/EIPAllocatedToVPCAttachedEC2.yaml
tests/terraform/graph/checks/resources/EIPAllocatedToVPCAttachedEC2/expected.yaml
tests/terraform/graph/checks/resources/EIPAllocatedToVPCAttachedEC2/main.tf

Addresses https://github.com/bridgecrewio/checkov/issues/1631

add aws_transfer_server to connected EIP list

---

checkov/terraform/graph_manager.py
checkov/terraform/parser.py
checkov/terraform/runner.py

fix missing external_modules_download_path argument

---

checkov/kubernetes/checks/PodSecurityContext.py
checkov/kubernetes/checks/RootContainers.py
checkov/kubernetes/checks/RootContainersHighUID.py

Get security context gracefully

---

checkov/cloudformation/checks/resource/BaseCloudsplainingIAMCheck.py
checkov/cloudformation/checks/resource/aws/IAMAdminPolicyDocument.py
tests/cloudformation/checks/resource/aws/example_IAMAdminPolicyDocument/iam_policy.fail.json
tests/cloudformation/checks/resource/aws/example_IAMAdminPolicyDocument/iam_policy.pass.json
tests/cloudformation/checks/resource/aws/test_IAMAdminPolicyDocument.py

Replication CKV_AWS_63 but target Cloudformation

CKV_AWS_63 for CFN

---

checkov/terraform/checks/resource/aws/IAMStarActionPolicyDocument.py
tests/terraform/checks/resource/aws/test_IAMStarActionPolicyDocument.py

add support for checking sso inline policy for CKV_AWS_63

---

checkov/terraform/checks/resource/aws/IAMAdminPolicyDocument.py
tests/terraform/checks/resource/aws/example_IAMAdminPolicyDocument/iam.tf
tests/terraform/checks/resource/aws/test_IAMAdminPolicyDocument.py

Add SSO inline policies to admin check CKV_AWS_62

---

checkov/secrets/plugins/entropy_keyword_combinator.py
checkov/secrets/runner.py
tests/secrets/test_plugin.py

Fixes #1603 
I defined the entropy limit as a constant to reference it in the test.

lower entropy keyword limit to 3

---

tests/cloudformation/checks/resource/aws/example_IAMRoleAllowAssumeFromAccount/example_IAMRoleAllowAssumeFromAccount-PASSED-2.yml

Fix cfn-lint

---

checkov/terraform/checks/provider/oci/__init__.py
checkov/terraform/checks/provider/oci/credentials.py
tests/terraform/checks/provider/oci/test_credentials.py

I put in a very simple provider check to kick this off.

add oracle cloud support to checkov

---

checkov/common/runners/runner_registry.py
checkov/main.py

Stop printing banner when passing `quiet` as CLI parameter

---

checkov/terraform/checks/resource/linode/user_email_set.py
checkov/terraform/checks/resource/linode/user_username_set.py
tests/terraform/checks/resource/linode/test_user_email_set.py
tests/terraform/checks/resource/linode/test_user_username_set.py

Required for the linode_user resource

Adding linode user and email scan checks

---

checkov/terraform/checks/resource/github/WebhookInsecureSsl.py
checkov/terraform/checks/resource/linode/firewall_inbound_policy.py
checkov/terraform/checks/resource/linode/firewall_outbound_policy.py
tests/terraform/checks/resource/github/test_WebhookInsecureSsl.py
tests/terraform/checks/resource/linode/test_firewall_inbound_policy.py
tests/terraform/checks/resource/linode/test_firewall_outbound_policy.py

Linode Firewall Inbound/Outbound default rules

---

docs/2.Basics/Reviewing Scan Results.md

Added reference to Markdown output format

---

checkov/terraform/checks/resource/aws/SQSQueuePolicyAnyPrincipal.py

Safeguard IAM policy parsing in SQS policy check

---

checkov/cloudformation/graph_builder/variable_rendering/renderer.py
tests/cloudformation/graph/graph_builder/resources/variable_rendering/render_if/json/test.json
tests/cloudformation/graph/graph_builder/resources/variable_rendering/render_if/yaml/test.yaml
tests/cloudformation/graph/graph_builder/test_render.py

I believe the documentation in the code should help understand the implementation and the changes.
Most of it can be found in the method `_evaluate_if_connection` and thus should explain the changes in the invoker method `evaluate_vertex_attribute_from_edge`. 
Feel free to ask any questions if needed!

Evaluate CFN Fn::If for Graph Rendering

---

.github/workflows/build.yml

Updated path for GHA update-bridgecrew-projects

---

kubernetes/Dockerfile

Inserted a line in Dockerfile, confirming the working directory.

Added working directory command in dockerfile

---

checkov/common/runners/runner_registry.py

Set tool as a RunnerRegistry member

---

checkov/terraform/checks/resource/aws/APIGatewayCacheEnable.py
tests/terraform/checks/resource/aws/example_APIGatewayCacheEnable/main.tf
tests/terraform/checks/resource/aws/test_APIGatewayCacheEnable.py

This check failed to target the correct resource, ive refactored to make it correct

CKV_AWS_120 make check actually work against stage

---

checkov/dockerfile/checks/ReferenceLatestTag.py
tests/dockerfile/checks/example_ReferenceLatestTag/success_multi_stage_capital/Dockerfile
tests/dockerfile/checks/test_ReferenceLatestTag.py

multi stage builds work as intended.

Ignore capitalization in the FROM line for Docker latest check

---

.github/workflows/build.yml
.github/workflows/pipenv-update.yml
.github/workflows/pr-test.yml

pin pipenv version till issues are resolved

---

checkov/cloudformation/parser/__init__.py
checkov/terraform/graph_builder/graph_components/module.py

Handle YML ValueError and malformed TF attributes 

Handle YML ValueError and malformed TF attributes 

---

checkov/common/graph/checks_infra/base_check.py
tests/cloudformation/graph/checks/resources/ALBRedirectHTTPtoHTTPS/expected.yaml
tests/cloudformation/graph/checks/resources/MSKClusterLogging/expected.yaml
tests/cloudformation/graph/checks/test_yaml_policies.py

defining evaluated keys for complex graph checks by returning the sub_checks evaluated keys if exists

defining evaluated keys for complex graph checks

---

checkov/terraform/checks/resource/gcp/GKEMetadataServerisEnabled.py
tests/terraform/checks/resource/gcp/test_GKEMetadataServerisEnabled.py
tests/terraform/checks/resource/gcp/test_GKEMetadataServerisEnabled/main.tf

Fix for https://github.com/bridgecrewio/checkov/issues/1777.

Edit CKV_GCP_69 to support both types of workload_metadata_config

---

checkov/cloudformation/context_parser.py

The looking-inside nested implementation only added bad data

Fix CFN resources line parsing in sls templates

---

checkov/common/bridgecrew/bc_source.py

Add CodeBuild as BCSourceType

---

checkov/common/checks/base_check.py
checkov/common/checks/base_check_registry.py
checkov/common/checks_infra/registry.py

Handle windows paths in external dir loading

---

checkov/terraform/checks/resource/aws/GlacierVaultAnyPrincipal.py

Handle json string correctly in GlacierVaultAnyPrincipal.py

---

checkov/terraform/checks/resource/aws/DBInstanceLogging.py

Replace /[0]/[0] with manual yet consistent check for attribute (DBInstanceLogging)

---

checkov/terraform/checks/resource/oci/SecurityListIngress.py
tests/terraform/checks/resource/oci/example_SecurityListIngress/main.tf
tests/terraform/checks/resource/oci/test_SecurityListIngress.py

new check - OCI Ensure VCN has an inbound security list #1980

---

checkov/common/output/record.py
tests/common/output/test_record.py

Fixes #1949 
Also removed possible recursion paths.

fix rel path with different windows drive

---

checkov/common/checks_infra/checks_parser.py
checkov/common/graph/checks_infra/base_check.py

Add category parsing to base graph check

---

docs/4.Integrations/Helm.md

Added information about scanning both charts automatically through auto-detection of `Chart.yaml` files and also howto scan resultant kubernetes manifests using your own helm values files.

Updated HELM documentation

---

checkov/terraform/checks/resource/aws/LambdaEnvironmentEncryptionSettings.py
tests/terraform/checks/resource/aws/example_LambdaEnvironmentEncryptionSettings/main.tf
tests/terraform/checks/resource/aws/test_LambdaEnvironmentEncryptionSettings.py

fix for empty string- empty but no kms key id has been actually added

---

checkov/kubernetes/checks/resource/k8s/HostPort.py
tests/kubernetes/checks/example_HostPort/nginx-app-PASSED.yaml
tests/kubernetes/checks/test_HostPort.py

fix HostPort check to not throw an exception if ports is null

---

checkov/common/runners/runner_registry.py

fix for JSON output TypeError, issue #1948

---

checkov/terraform/checks/resource/aws/LambdaEnvironmentCredentials.py
tests/terraform/checks/resource/aws/example_LambdaEnvironmentCredentials/main.tf
tests/terraform/checks/resource/aws/test_LambdaEnvironmentCredentials.py

Also changed the related test to use the "new" syntax.

adjust evaluated_keys for CKV_AWS_45

---

docs/3.Custom Policies/Python Custom Policies.md

Added two points to the python custom policies contribution guidelines:
1. Adding `evaluated_keys` to a new resource check.
2. How to implement `BaseResourceValueCheck` and `BaseResourceNegativeValueCheck`

Guidelines addition for creating python custom policies

---

checkov/terraform/parser.py

Supply an optional modules content cache as an argument

Optional external modules content cache

---

checkov/cloudformation/checks/resource/aws/EC2Credentials.py

Remove unnecessary quotes of evaluated key

---

checkov/terraform/checks/resource/aws/S3Versioning.py
tests/terraform/checks/resource/aws/example_S3versioning/main.tf
tests/terraform/checks/resource/aws/test_S3Versioning.py

debugging for client - refactored to new way for clarity

---

checkov/terraform/checks/provider/__init__.py
checkov/terraform/checks/provider/openstack/__init__.py
checkov/terraform/checks/provider/openstack/credentials.py
checkov/terraform/checks/resource/__init__.py
checkov/terraform/checks/resource/openstack/AbsSecurityGroupUnrestrictedIngress.py
checkov/terraform/checks/resource/openstack/SecurityGroupUnrestrictedIngress22.py
checkov/terraform/checks/resource/openstack/SecurityGroupUnrestrictedIngress3389.py
checkov/terraform/checks/resource/openstack/__init__.py
tests/terraform/checks/provider/openstack/test_credentials.py
tests/terraform/checks/resource/openstack/test_SecurityGroupUnrestrictedIngress22.py
tests/terraform/checks/resource/openstack/test_SecurityGroupUnrestrictedIngress3389.py

This PR adds support for openstack and closes #1103.

Add support for openstack provider (#1103)

---

checkov/terraform/checks/provider/__init__.py

Add missing import for OCI provider

---

checkov/arm/checks/resource/AKSDashboardDisabled.py

Add proper dict checks to ensure get() success.

Fix AKSDashboardDisabled check - Add proper dict checks to ensure get() success

---

checkov/cloudformation/cfn_utils.py
checkov/kubernetes/kubernetes_utils.py
checkov/kubernetes/runner.py

Adjust k8s graph

---

.github/workflows/build.yml
.github/workflows/coverage.yaml
checkov/common/util/docs_generator.py
tests/common/utils/test_docs_generator.py

1. Move coverage to a weekly job (runs on Sundays) to avoid waiting for coverage in build pipelines (takes ~3 times as long).
2. Remove unnecessary changes in docs due to resource types not being ordered.

Build pipeline improvements

---

checkov/serverless/runner.py

added ability to use environment variable to poplulate SLS_FILE_MASK see Issue #1904

---

docs/2.Basics/Visualizing Checkov Output.md

This PR completes #1950 and adds the env variable to the docs.
Thanks @nmrad-91 !

Update docs to expose SLS_FILE_MASK env variable

---

checkov/cloudformation/cfn_utils.py
checkov/cloudformation/runner.py
tests/cloudformation/utils/test_cfn_utils.py

Adjust cfn's build_definitions_context arguments

---

checkov/common/bridgecrew/bc_source.py
tests/common/test_platform_integration.py

Added Jenkins and CircleCI as sources

---

checkov/terraform/checks/resource/openstack/ComputeInstanceAdminPassword.py
tests/terraform/checks/resource/openstack/example_ComputeInstanceAdminPassword/main.tf
tests/terraform/checks/resource/openstack/test_ComputeInstanceAdminPassword.py

add openstack check for admin password on instances

---

checkov/common/bridgecrew/platform_integration.py

accelerate file uploads when using api token in checkov in around 10 seconds at least :)

busy wait for checkov file upload

---

checkov/terraform/graph_builder/utils.py
checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py

Apply max render length to evaluate_terraform.py

---

checkov/terraform/checks/resource/openstack/FirewallRuleSetDestinationIP.py
tests/terraform/checks/resource/openstack/example_FirewallRuleSetDestinationIP/main.tf
tests/terraform/checks/resource/openstack/test_FirewallRuleSetDestinationIP.py

openstack Check to see if firewall rule has destination defined

---

checkov/terraform/checks/resource/__init__.py
checkov/terraform/checks/resource/digitalocean/SpacesBucketVersioning.py
checkov/terraform/checks/resource/digitalocean/__init__.py
tests/terraform/checks/resource/digitalocean/example_SpaceBucketVersioning/main.tf
tests/terraform/checks/resource/digitalocean/test_SpaceBucketVersioning.py

1st digital Ocean check

---

checkov/terraform/checks/resource/digitalocean/DropletSSHKeys.py
tests/terraform/checks/resource/digitalocean/example_DropletSSHKeys/main.tf
tests/terraform/checks/resource/digitalocean/test_DropletSSHKeys.py

test for any value for the attribute SSH_key

---

checkov/terraform/checks/resource/digitalocean/SpacesBucketPublicRead.py
tests/terraform/checks/resource/digitalocean/example_SpaceBucketPublicRead/main.tf
tests/terraform/checks/resource/digitalocean/test_SpaceBucketPublicRead.py

DIO: check that a bucket is not public

---

checkov/terraform/checks/resource/digitalocean/FirewallIngressOpen.py
tests/terraform/checks/resource/digitalocean/example_FirewallIngressOpen/main.tf
tests/terraform/checks/resource/digitalocean/test_FirewallIngressOpen.py

check that firewall rule is not open to world

---

docs/4.Integrations/GitLab CLI.md
setup.py

Hello,
Just doing a bit of _GitHub Gardening_. This stuff just sticks out to me aha.
I've made the outstanding changes from 3 open Doc Typo PRs (2 were already handled actually) made by @shreemaan-abhishek. Unfortunately I can not credit him with changes because his checkov fork has been deleted.
Also added the metadata change by @cclauss where he has been credited properly as I merged into my branch.
This can be used instead of:
* https://github.com/bridgecrewio/checkov/pull/2081
* https://github.com/bridgecrewio/checkov/pull/1729
* https://github.com/bridgecrewio/checkov/pull/1731
* https://github.com/bridgecrewio/checkov/pull/1734
And so these PRs can all be closed.
And can close these issues:
* https://github.com/bridgecrewio/checkov/issues/1728
* …

Combine small changes

---

Dockerfile
kubernetes/Dockerfile

docker: use py3.10 for base image

---

checkov/cloudformation/checks/resource/aws/WAFACLCVE202144228.py
checkov/terraform/checks/resource/aws/WAFACLCVE202144228.py
tests/cloudformation/checks/resource/aws/example_WAFACLCVE202144228/FAILED.yaml
tests/cloudformation/checks/resource/aws/example_WAFACLCVE202144228/PASSED.yaml
tests/cloudformation/checks/resource/aws/test_WAFACLCVE202144228.py
tests/terraform/checks/resource/aws/example_WAFACLCVE202144228/main.tf
tests/terraform/checks/resource/aws/test_WAFACLCVE202144228.py

add CKV_AWS_192 to mitigate CVE-2021-44228

---

checkov/terraform/checks/resource/azure/StorageAccountName.py
tests/terraform/checks/resource/azure/example_StorageAccountName/main.tf
tests/terraform/checks/resource/azure/test_StorageAccountName.py

fix storage account name existing of numbers

---

checkov/terraform/checks/resource/aws/WAFACLCVE202144228.py
tests/terraform/checks/resource/aws/example_WAFACLCVE202144228/main.tf
tests/terraform/checks/resource/aws/test_WAFACLCVE202144228.py

Fixes #2093 
I made it more robust in general and the Terraform plan behaviour is weird here, that's why I added the comment.

fix CKV_AWS_192 for Terraform plan runs

---

.github/workflows/build.yml

Return reuse of commit message from head instead of irrelevant messages

---

checkov/common/goget/github/get_git.py
checkov/terraform/parser.py
tests/terraform/parser/resources/local_module/main.tf
tests/terraform/parser/resources/local_module/module/main.tf
tests/terraform/parser/test_parser_modules.py

- adjusted git to just do a shallow clone
- added a parsed file "cache", so modules are not parsed several times

Optimize module loading

---

checkov/terraform/checks/resource/gcp/GoogleKMSRotationPeriod.py
tests/terraform/checks/resource/gcp/example_GoogleKMSRotationPeriod/main.tf
tests/terraform/checks/resource/gcp/test_GoogleKMSKeyRotationPeriod.py

make CKV_GCP_43 more robust to an empty value

---

checkov/arm/checks/resource/AKSLoggingEnabled.py
checkov/arm/checks/resource/AppServiceHttps20Enabled.py
checkov/arm/checks/resource/AppServiceMinTLSVersion.py
checkov/arm/checks/resource/AzureInstancePassword.py

There is definitely more work needed to go through the other ARM checks, I just fixed the one, which used `.get()` to access the next key-value pair.

check ARM values to be a dict before accessing

---

checkov/terraform/checks/resource/gcp/CloudStorageSelfLogging.py

fix error when GCP bucket name is missing

---

checkov/arm/checks/resource/AzureInstancePassword.py
checkov/arm/checks/resource/AzureScaleSetPassword.py
tests/arm/checks/resource/example_AzureInstancePassword/FAILED.json
tests/arm/checks/resource/example_AzureInstancePassword/PASSED.json
tests/arm/checks/resource/example_AzureInstancePassword/UNKNOWN.json
tests/arm/checks/resource/example_AzureScaleSetPassword/FAILED.json
tests/arm/checks/resource/example_AzureScaleSetPassword/PASSED.json
tests/arm/checks/resource/example_AzureScaleSetPassword/UNKNOWN.json
tests/arm/checks/resource/test_AzureScaleSetPassword.py

Fixes #428
Add missing ARM check and also migrated `CKV_AZURE_1` to a `BaseResourceValueCheck`.

add CKV_AZURE_49 for ARM

---

checkov/terraform/checks/resource/azure/FrontDoorWAFACLCVE202144228.py
tests/terraform/checks/resource/azure/example_FrontDoorWAFACLCVE202144228/main.tf
tests/terraform/checks/resource/azure/test_FrontDoorWAFACLCVE202144228.py

I divided the last 3 `if`s to make it easier to read and understand. I'm aware you can put them all together, but the check is already complex enough 😄

add CKV_AZURE_133 to check for log4shell prevention in Front Door WAF

---

checkov/cloudformation/checks/resource/aws/AppSyncFieldLevelLogs.py
checkov/cloudformation/checks/resource/aws/AppSyncLogging.py
checkov/cloudformation/checks/resource/base_resource_check.py
checkov/cloudformation/checks/resource/base_resource_value_check.py
checkov/common/checks/base_check.py
checkov/terraform/checks/graph_checks/aws/AppSyncProtectedByWAF.yaml
checkov/terraform/checks/resource/aws/AppSyncFieldLevelLogs.py
checkov/terraform/checks/resource/aws/AppSyncLogging.py
checkov/terraform/checks/resource/base_resource_check.py
checkov/terraform/checks/resource/base_resource_value_check.py
tests/cloudformation/checks/resource/aws/example_AppSyncFieldLevelLogs/template.yaml
tests/cloudformation/checks/resource/aws/example_AppSyncLogging/template.yaml
tests/cloudformation/checks/resource/aws/test_AppSyncFieldLevelLogs.py
tests/cloudformation/checks/resource/aws/test_AppSyncLogging.py
tests/terraform/checks/resource/aws/example_AppSyncFieldLevelLogs/main.tf
tests/terraform/checks/resource/aws/example_AppSyncLogging/main.tf
tests/terraform/checks/resource/aws/test_AppSyncFieldLevelLogs.py
tests/terraform/checks/resource/aws/test_AppSyncLogging.py
tests/terraform/graph/checks/resources/AppSyncProtectedByWAF/expected.yaml
tests/terraform/graph/checks/resources/AppSyncProtectedByWAF/main.tf
tests/terraform/graph/checks/test_yaml_policies.py

Added 2 Terraform & CFN checks connected to AppSync Logging & 1 Terraform AppSync connected to WAF

Add appsync checks

---

checkov/kubernetes/runner.py

fix paths in k8s graph report

---

checkov/terraform/checks/resource/gcp/CloudArmorWAFACLCVE202144228.py
tests/terraform/checks/resource/gcp/example_CloudArmorWAFACLCVE202144228/main.tf
tests/terraform/checks/resource/gcp/test_CloudArmorWAFACLCVE202144228.py

add CKV_GCP_73 to check for log4shell prevention in Cloud Armor

---

checkov/common/checks_infra/solvers/complex_solvers/and_solver.py
checkov/common/checks_infra/solvers/complex_solvers/or_solver.py
checkov/common/checks_infra/solvers/connections_solvers/and_connection_solver.py
checkov/common/graph/checks_infra/registry.py
tests/common/runner_registry/test_runner_registry_plan_enrichment.py

Run graph checks in parallel to improve performance

---

checkov/terraform/parser.py

What we should be doing - parsing the directories in parallel, not the files

Tf parse files sequentially - but dirs in parallel

---

checkov/kubernetes/runner.py

Fix Kubernetes runner report to contain the file abs path of each resource.

fix resource path in Kubernetes runner report

---

checkov/kubernetes/kubernetes_utils.py
tests/kubernetes/graph/test_graph_manager.py
tests/kubernetes/runner/test_runner.py

Removed slicing of k8s path

---

checkov/terraform/checks/resource/gcp/GKEMetadataServerIsEnabled.py
tests/terraform/checks/resource/gcp/test_GKEMetadataServerIsEnabled.py
tests/terraform/checks/resource/gcp/test_GKEMetadataServerisEnabled/main.tf

Fix GKEMetadataServerIsEnabled.py to handle metadata as list

---

checkov/serverless/runner.py

Fixes #934 
this part was the problem
```python
if not cf_sub_template.get('Resources'):
continue
```
it ended the iteration of the loop prematurely.

fix premature SLS scan end

---

checkov/terraform/checks/resource/aws/CloudfrontTLS12.py
tests/terraform/checks/resource/aws/example_CloudfrontTLS12/main.tf
tests/terraform/checks/resource/aws/test_CloudFrontTLS12.py

Fixes #2063
This will resolve Issue 2063 CKV_AWS_174 incorrect reporting. @nimrodkor: Can you please check the code. I also have a doubt, if **cloudfront_default_certificate** condition is required at all?

Fix issue 2063 - CKV_AWS_174 incorrect reporting

---

.github/workflows/codeql-analysis.yml
checkov/main.py
checkov/terraform/checks/resource/azure/AKSDashboardDisabled.py

Fix crash in tf kubernetes dashboard check

---

Pipfile.lock
checkov/common/bridgecrew/vulnerability_scanning/integrations/package_scanning.py
tests/common/bridgecrew/vulnerability_scanning/conftest.py
tests/common/bridgecrew/vulnerability_scanning/integrations/test_package_scanning.py

Added packages to Twistcli report

---

checkov/common/bridgecrew/vulnerability_scanning/integrations/twistcli.py

log image scanning report payload in case of HTTPError

---

checkov/helm/runner.py
checkov/main.py
docs/4.Integrations/Helm.md

allow using the `--var-file` option with Helm (as well as currently supported TF) frameworks, see documentation update in the commit for more detail.

Helm values file support

---

checkov/cloudformation/checks/resource/aws/LambdaEnvironmentCredentials.py

CKV_AWS_45 ensure variables section is key-value pairs

---

checkov/main.py

Add environment variable for check and skip-check

---

INTHEWILD.md

Reverting to myself. By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Removing from INTHEWILD

---

checkov/terraform/module_loading/registry.py

Reduce log level of a caching message to debug

---

docs/2.Basics/CLI Command Reference.md

The CLI Command Reference doc was a bit out of date - have updated it based on the output of the help command.

Update CLI Command Reference to match implementation

---

checkov/github/base_github_branch_security.py
checkov/github/checks/disallow_force_pushes.py
checkov/github/checks/rerquire_signatures.py
checkov/github/dal.py
checkov/github/schemas/branch_protection.py
checkov/github/schemas/org_security.py
tests/github/resources/github_conf/repo/branch_protection.json
tests/github/test_runner.py

add more github repository rules around branch protectioni

add more branch protection checks in checkov

---

checkov/kubernetes/runner.py
tests/kubernetes/runner/test_runner.py

Fix k8s file_path

---

checkov/cloudformation/checks/resource/aws/GlueSecurityConfigurationEnabled.py
checkov/cloudformation/runner.py
checkov/terraform/checks/graph_checks/aws/SGAttachedToResource.yaml
checkov/terraform/checks/resource/aws/GlueSecurityConfigurationEnabled.py
tests/cloudformation/checks/resource/aws/example_GlueSecurityConfigurationEnabled/FAIL.yaml
tests/cloudformation/checks/resource/aws/example_GlueSecurityConfigurationEnabled/PASS.yaml
tests/cloudformation/checks/resource/aws/test_GlueSecurityConfigurationEnabled.py
tests/terraform/checks/resource/aws/example_GlueSecurityConfigurationEnabled/main.tf
tests/terraform/checks/resource/aws/test_GlueSecurityConfigurationEnabled.py
tests/terraform/graph/checks/resources/SGAttachedToResource/expected.yaml
tests/terraform/graph/checks/resources/SGAttachedToResource/main.tf

Fixes #170
Added the check for Terraform and CloudFormation and also adjusted the Security Group attachment check to look out for a Glue dev endpoint.

Add glue security conf check

---

.github/workflows/build.yml
checkov/common/util/docs_generator.py
checkov/common/vcs/base_vcs_dal.py
checkov/common/vcs/vcs_schema.py
checkov/github/dal.py
checkov/github/schemas/branch_protection.py
checkov/github/schemas/org_security.py
checkov/gitlab/__init__.py
checkov/gitlab/base_gitlab_configuration_check.py
checkov/gitlab/checks/__init__.py
checkov/gitlab/checks/merge_requests_approvals.py
checkov/gitlab/checks/two_factor_authentication.py
checkov/gitlab/dal.py
checkov/gitlab/registry.py
checkov/gitlab/runner.py
checkov/gitlab/schemas/groups.py
checkov/gitlab/schemas/project_approvals.py
checkov/main.py
tests/gitlab/resources/gitlab_conf/fail/groups.json
tests/gitlab/resources/gitlab_conf/fail/merge_request_approval_conf.json
tests/gitlab/resources/gitlab_conf/pass/groups.json
tests/gitlab/resources/gitlab_conf/pass/merge_request_approval_conf.json
tests/gitlab/test_runner.py
tests/terraform/util/test_doc_generator.py
tests/test_runner_filter.py

Draft for gitlab runner. 
TODO:
Docs (example, how to contribute, policy list) - will be a separate PR

Add gitlab runner

---

checkov/gitlab/dal.py
docs/6.Contribution/Contribute New GitHub Policies.md
docs/6.Contribution/Contribute New Gitlab Policies.md
docs/7.Scan Examples/Gitlab.md

add gitlab runner docs

---

checkov/github/dal.py
tests/github/test_runner.py

fix github env for branch

---

checkov/cloudformation/cfn_utils.py
checkov/cloudformation/context_parser.py
checkov/cloudformation/graph_builder/graph_components/blocks.py
checkov/cloudformation/graph_builder/graph_to_definitions.py
checkov/cloudformation/graph_builder/local_graph.py
checkov/cloudformation/runner.py
docs/2.Basics/Suppressing and Skipping Policies.md
tests/cloudformation/utils/file_formats/test.yaml
tests/cloudformation/utils/test_cfn_utils.py

Fixes #2194
Fixes #1931
Extended the graph to also store the CloudFormation `Metadata` and added the possibility to actually add the skip comment that section. Added an example to the docs.

support check suppression via CFN Metadata

---

checkov/terraform/checks/resource/aws/ElasticacheHasSecurityGroup.py
tests/terraform/checks/resource/aws/example_ElasticacheHasSecurityGroup/main.tf
tests/terraform/checks/resource/aws/test_ElasticCacheHasSecurityGroup.py

No such groups should not exist

check to ensure no aws_elasticache_security_group exist

---

checkov/terraform/checks/resource/aws/MQBrokerAuditLogging.py
tests/terraform/checks/resource/aws/example_MQBrokerAuditLogging/main.tf
tests/terraform/checks/resource/aws/test_MQBrokerAuditLogging.py

add check for mq audit logging

---

checkov/terraform/checks/graph_checks/aws/AWSSSMParametershouldbeEncrypted.yaml
tests/terraform/graph/checks/resources/AWSSSMParametershouldbeEncrypted/expected.yaml
tests/terraform/graph/checks/resources/AWSSSMParametershouldbeEncrypted/main.tf
tests/terraform/graph/checks/test_yaml_policies.py

**PC Policy ID** - 926b7056-6a39-4885-a806-8e4cf958fced
**Compliance Standard** - APRA (CPS 234) Information Security-CPS234-15, APRA (CPS 234) Information Security-CPS234-16, APRA (CPS 234) Information Security-CPS234-17, APRA (CPS 234) Information Security-CPS234-21, APRA (CPS 234) Information Security-CPS234-23, APRA (CPS 234) Information Security-CPS234-27, APRA (CPS 234) Information Security-CPS234-34, Brazilian Data Protection Law (LGPD)-Article 49, CCPA 2018-1798.150(a)(1), CSA CCM v.4.0.1-CEK-03, CSA CCM v.4.0.1-DSP-10, CSA CCM v.4.0.1-UEM-11, Copy of CCPA 2018-1-1798.150(a)(1), Copy of CCPA 2018-1798.150(a)(1), Copy of CCPA 2018555-1798.150(a)(1), Copy2 of CCPA …

PC-policy-team-build-once || AWS SSM Parameter should be Encrypted

---

docs/2.Basics/CLI Command Reference.md

fix: small typo in docs

---

checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogConnection.py
tests/terraform/checks/resource/gcp/example_GoogleCloudPostgreSqlLogConnection/main.tf
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogConnection.py

We were getting postgres passes against mysql dbs.

Postgres Db test wrong test wrong db 

---

checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogCheckpoints.py
tests/terraform/checks/resource/gcp/example_GoogleCloudPostgreSqlLogCheckpoints/main.tf
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogCheckpoints.py

A Postgres check was passing on other dbs

---

checkov/common/output/report.py

refactoring code with List Comprehension which is more pythonic, concise and efficient; how do you think this change which has practical value？

refactoring code with List Comprehension

---

setup.py

add jinja2 template files to package

---

checkov/terraform/checks/resource/aws/SQSPolicy.py
tests/terraform/checks/resource/aws/example_SQSPolicy/main.tf
tests/terraform/checks/resource/aws/test_SQSPolicy.py

False positives were reported.

SQSPolicy did not work - reduce false positives

---

checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogMinDuration.py
tests/terraform/checks/resource/gcp/example_CloudPostgreSqlLogMinDuration/main.tf
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogMinDuration.py

Made no sense passing this rule for SQLServer - set to unknown now

Do no automatically pass non postgres dbs

---

checkov/terraform/checks/resource/gcp/GoogleCloudSqlServerNoPublicIP.py
tests/terraform/checks/resource/gcp/example_CloudSQLServerNoPublicIP/main.tf
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlServerNoPublicIP.py

This check was supposed to only target SQLServer which makes no sense. Can target all dbs.

sql server shouldnt be public

---

checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogMinMessage.py
tests/terraform/checks/resource/gcp/example_CloudPostgreSQLLogMinMessage/main.tf
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogMinMessage.py

CKV_GCP_55 dont report pass for all dbs - just compliant PostGreSQL

---

checkov/terraform/checks/resource/gcp/GoogleCloudSqlServerCrossDBOwnershipChaining.py
tests/terraform/checks/resource/gcp/example_CloudSQLServerCrossDBOwnershipChaining/main.tf
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlServerCrossDBOwnershipChaining.py

Should only pass or fail SQLServer Dbs

---

checkov/terraform/checks/resource/gcp/GoogleCloudSqlDatabasePubliclyAccessible.py
tests/terraform/checks/resource/gcp/example_GoogleCloudSqlDatabasePubliclyAccessible/main.tf
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlDatabasePublicallyAccessible.py

Fix failing to find public networks

---

admissioncontroller/Dockerfile
checkov/common/bridgecrew/bc_source.py

add admission controller as additional bc_source

---

checkov/common/util/data_structures_utils.py
checkov/main.py
checkov/runner_filter.py
checkov/sca_package/output.py
checkov/sca_package/runner.py
tests/sca_package/test_output.py

Implement cve skip by package name and severity

---

checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogLockWaits.py
tests/terraform/checks/resource/gcp/example_CloudPostgreSqlLogLockWaits/main.tf
tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogLockWaits.py

CKV_GCP_54 dont pass for all other dbs

---

checkov/terraform/checks/resource/gcp/GoogleCloudSqlServerContainedDBAuthentication.py
tests/terraform/checks/resource/gcp/example_CloudSQLServerContainerDBAuthentication/main.tf
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlServerContainedDBAuthentication.py

CKV_GCP_59 Should only pass or fail on SQLServers

---

checkov/kubernetes/checks/resource/k8s/ApiServerBasicAuthFile.py
checkov/kubernetes/checks/resource/k8s/ApiServerRequestTimeout.py
checkov/kubernetes/checks/resource/k8s/ApiServerSecurePort.py
checkov/kubernetes/checks/resource/k8s/EtcdAutoTls.py
checkov/kubernetes/checks/resource/k8s/EtcdClientCertAuth.py
tests/kubernetes/checks/example_ApiServerSecurePort/api-server-secure-port-FAILED.yaml
tests/kubernetes/checks/example_ApiServerSecurePort/api-server-secure-port-PASSED_2.yaml
tests/kubernetes/checks/test_ApiServerSecurePort.py

fixes an issue with an empty command

fix issue with empty command

---

checkov/kubernetes/graph_builder/local_graph.py
checkov/kubernetes/kubernetes_utils.py
tests/kubernetes/checks/example_DockerSocketVolume/scope-2PASSED-1FAILED.yaml

seems like you can have null values in a K8s List object 🤷

remove null entries in K8s List

---

tests/terraform/checks/resource/gcp/example_GoogleComputeProjectOSLogin/main.tf
tests/terraform/checks/resource/gcp/test_GoogleComputeProjectOSLogin.py

factor: added item metadata case to help #1017

---

checkov/terraform/checks/resource/github/RepositoryEnableVulnerabilityAlerts.py
tests/terraform/checks/resource/github/example_RepositoryEnableVulnerabilityAlerts/main.tf
tests/terraform/checks/resource/github/test_RepositoryVulnerabilityAlerts.py

Github - Ensure vulnerability alerts are enabled

---

checkov/terraform/checks/resource/github/SecretsEncrypted.py
tests/terraform/checks/resource/github/example_SecretsEncrypted/main.tf
tests/terraform/checks/resource/github/test_SecretsEncrypted.py

github actions: check secrets encrypted

---

checkov/terraform/checks/resource/azure/VMCredsInCustomData.py
tests/terraform/checks/resource/azure/example_VMCredsInCustomData/main.tf
tests/terraform/checks/resource/azure/test_VMCredsInCustomData.py

a TF plan issue, because it returns an empty list.

fix TF plan issue with CKV_AZURE_45

---

checkov/terraform/checks/resource/aws/ImagebuilderDistributionConfigurationEncryptedWithCMK.py
tests/terraform/checks/resource/aws/example_ImagebuilderDistributionConfigurationEncryptedWithCMK/main.tf
tests/terraform/checks/resource/aws/test_ImagebuilderDistributionConfigurationEncryptedWithCMK.py

Imagebuilder ensure amis are made encrypted

---

checkov/terraform/checks/resource/aws/MemoryDBEncryptionWithCMK.py
tests/terraform/checks/resource/aws/example_ImagebuilderImageRecipeEBSEncrypted/main.tf
tests/terraform/checks/resource/aws/example_MemoryDBEncryptionWithCMK/main.tf
tests/terraform/checks/resource/aws/test_MemoryDBEncryptionWithCMK.py

MemoryDB is encrypted at rest

---

checkov/terraform/checks/resource/github/RepositoryEnableVulnerabilityAlerts.py
tests/terraform/checks/resource/github/example_RepositoryEnableVulnerabilityAlerts/main.tf
tests/terraform/checks/resource/github/test_RepositoryVulnerabilityAlerts.py

CKV_GIT_3 should not be triggered on archived repositories

---

checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py
checkov/common/checks_infra/solvers/connections_solvers/and_connection_solver.py
checkov/common/checks_infra/solvers/connections_solvers/base_connection_solver.py
performance_tests/test_checkov_performance.py
tests/terraform/graph/checks_infra/connection_solvers/connection_exist_solver/test_solver.py

improved graph checks runtime by reducing the graph to the targeted resources 🚀

optimize graph checks

---

checkov/sca_package/scanner.py

Avoiding crashing when using Pycharm's-debugger on multiprocessing by using the env-variable "PYCHARM_HOSTED".
when "PYCHARM_HOSTED" is set and equal to "1", the scans are run in sequence

Avoiding crashing when using Pycharm's-debugger on multiprocessing.

---

Dockerfile
checkov/common/bridgecrew/vulnerability_scanning/image_scanner.py
checkov/common/bridgecrew/vulnerability_scanning/package_scanner.py

Wrap paths with quotes to handle special chars in path

---

checkov/terraform/checks/resource/aws/FSXOpenZFSFileSystemEncryptedWithCMK.py
tests/terraform/checks/resource/aws/example_FSXOpenZFSFileSystemEncryptedWithCMK/main.tf
tests/terraform/checks/resource/aws/test_FSXOpenZFSFileSystemEncryptedWithCMK.py

fsx openzfs file system is encrypted

---

checkov/terraform/checks/resource/base_resource_negative_value_check.py
tests/terraform/checks/resource/aws/example_IAMPolicyAttachedToGroupOrRoles/iam.tf
tests/terraform/checks/resource/aws/test_IAMPolicyAttachedToGroupOrRoles.py

Fixes #2318 
I added this in the past to the `BaseResourceValueCheck` and now it is time to treat its friend 😄

add empty check to the negative value check

---

checkov/common/comment/enum.py
tests/common/utils/test_utils.py

Fixes https://github.com/bridgecrewio/checkov/issues/2329

handle custom policies in skip comments

---

checkov/terraform/checks/resource/aws/APIGatewayDomainNameTLS.py
tests/terraform/checks/resource/aws/example_APIGatewayDomainNameTLS/main.tf
tests/terraform/checks/resource/aws/test_APIGatewayDomainNameTLS.py

api gateway domain uses TLS 1.2

---

checkov/terraform/checks/resource/azure/AzureManagedDiskEncryption.py
tests/terraform/checks/resource/azure/example_AzureManagedDiskEncryption/main.tf
tests/terraform/checks/resource/azure/example_VMCredsInCustomData/main.tf
tests/terraform/checks/resource/azure/test_AzureManagedDiscEncryption.py

fix bool test crash  for CKV_AZURE_2

---

checkov/terraform/checks/resource/gcp/GKEBasicAuth.py
tests/terraform/checks/resource/gcp/example_GKEBasicAuth/main.tf
tests/terraform/checks/resource/gcp/test_GKEBasicAuth.py

fix CKV_GCP_19 Was crashing if username=''

---

.github/workflows/build.yml
.github/workflows/pr-test.yml

This time I also add a comment 😄

remove helm action version

---

checkov/terraform/checks/resource/aws/MQBrokerVersion.py
tests/terraform/checks/resource/aws/example_MQBrokerVersion/main.tf
tests/terraform/checks/resource/aws/test_MQBrokerVersion.py

Ensure MQ broker is using latest version 

---

checkov/terraform/checks/resource/aws/IMDSv1Disabled.py
tests/terraform/checks/resource/aws/example_IMDSv1Disabled/main.tf
tests/terraform/checks/resource/aws/test_IMDSv1Disabled.py

Also refactored the checks to the new format

Extend IMDSv1 check to launch configurations

---

admissioncontroller/README.md

Fix setup link

---

checkov/terraform/checks/resource/aws/BatchJobIsNotPrivileged.py
tests/terraform/checks/resource/aws/example_BatchJobIsNotPrivileged/main.tf
tests/terraform/checks/resource/aws/test_BatchJobIsNotPrivileged.py

Batch job does not describe a privileged container

---

Dockerfile

- Enables kustomize output for docker users
- Enables kustomize output for GHA users

Move Kustomize into path. Enabling Kustomize output

---

checkov/terraform/checks/graph_checks/aws/APIProtectedByWAF.yaml
tests/terraform/graph/checks/resources/APIProtectedByWAF/expected.yaml
tests/terraform/graph/checks/resources/APIProtectedByWAF/main.tf

Adds support for aws_wafv2_web_acl_association in CKV2_AWS_29

---

checkov/terraform/checks/resource/aws/BatchJobIsNotPrivileged.py
tests/terraform/checks/resource/aws/example_BatchJobIsNotPrivileged/main.tf

fix for #2370

---

checkov/kubernetes/checks/resource/k8s/ImagePullPolicyAlways.py
checkov/terraform/checks/resource/aws/BatchJobIsNotPrivileged.py

In case of an invalid image name, return unknown result

ImagePullPolicy k8 check invalid image name

---

checkov/terraform/checks/resource/aws/ECRImageScanning.py
checkov/terraform/checks/resource/aws/ELBPolicyUsesSecureProtocols.py
tests/terraform/checks/resource/aws/example_ELBPolicyUsesSecureProtocols/main.tf
tests/terraform/checks/resource/aws/test_ELBPolicyUsesSecureProtocols.py

Policy protocol should be tls 1.2

---

checkov/common/bridgecrew/platform_integration.py
checkov/common/models/consts.py

This PR fixes a bug where dockerfiles are not saved to the platform for rendering the scan result on the projects page.

add dockerfile to upload

---

checkov/terraform/checks/resource/gcp/GoogleSubnetworkPrivateGoogleEnabled.py
tests/terraform/checks/resource/gcp/example_GoogleSubnetworkPrivateGoogleEnabled/main.tf
tests/terraform/checks/resource/gcp/test_GoogleSubnetworkPrivateGoogleEnabled.py

Check private google access enabled

---

checkov/terraform/checks/resource/gcp/CloudSqlMajorVersion.py
tests/terraform/checks/resource/gcp/example_CloudSqlMajorVersion/main.tf
tests/terraform/checks/resource/gcp/test_CloudSqlMajorVersion.py

major version test for SQL servers

---

checkov/terraform/checks/resource/gcp/CloudPubSubEncryptedWithCMK.py
tests/terraform/checks/resource/gcp/example_CloudPubSubEncryptedWithCMK/main.tf
tests/terraform/checks/resource/gcp/test_CloudPubSubEncryptedWithCMK.py

Ensure Pub sub topics are encrypted with a CMK

---

checkov/terraform/checks/resource/gcp/ArtifactRegsitryEncryptedWithCMK.py
tests/terraform/checks/resource/gcp/example_ArtifactRegistryEncryptedWithCMK/main.tf
tests/terraform/checks/resource/gcp/test_ArtifactRegistryEncryptedWithCMK.py

Artifact repos encrypted

---

checkov/terraform/checks/resource/gcp/BigTableInstanceEncryptedWithCMK.py
tests/terraform/checks/resource/gcp/example_BigTableInstanceEncryptedWithCMK/main.tf
tests/terraform/checks/resource/gcp/test_BigTableInstanceEncryptedWithCMK.py

Big table Instances encrypted with CMK

---

checkov/terraform/checks/resource/base_resource_check.py
checkov/terraform/checks/resource/base_resource_value_check.py
checkov/terraform/checks/resource/github/SecretsEncrypted.py
tests/terraform/checks/resource/github/example_SecretsEncrypted/main.tf
tests/terraform/checks/resource/github/test_SecretsEncrypted.py
tests/terraform/checks/test_base_resource_check.py

Fixes #2374 
added a prefix list to check for possible dependable resources and adjusted the CKV_GIT_4 to leverage it.

adjust CKV_GIT_4 to only check for hardcoded values

---

checkov/cloudformation/checks/resource/aws/ECRPolicy.py
checkov/common/util/json_utils.py
tests/cloudformation/runner/test_runner.py

handle complex numbers in custom deserializer, handle variable expression or malformed ECR policy

Handle complex custom serializer and malformed/variable dependent ECR policy  

---

checkov/common/models/consts.py
checkov/kubernetes/checks/resource/k8s/ImageTagFixed.py

fix `DOCKER_IMAGE_REGEX` and handle edge case of ImageTagFixed check

fix in ImageTagFixed check

---

checkov/terraform/checks/resource/gcp/CloudBuildWorkersArePrivate.py
tests/terraform/checks/resource/gcp/example_CloudBuildWorkersArePrivate/main.tf
tests/terraform/checks/resource/gcp/test_CloudBuildWorkerArePrivate.py

Cloud Build Workers should be private

---

checkov/terraform/checks/resource/alicloud/OSSBucketPublic.py
checkov/terraform/checks/resource/alicloud/__init__.py
tests/terraform/checks/resource/alicloud/example_OSSBucketPublic/main.tf
tests/terraform/checks/resource/alicloud/test_OSSBucketPublic

New Policy ID: CKV_ALI_1
Policy Name: Ensure Alibaba Cloud OSS bucket is not accessible to public
IaC Type: Terraform
Provider: alicloud
Docs: https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/oss_bucket#acl

Add first AliCloud check

---

checkov/terraform/checks/resource/aws/LaunchConfigurationEBSEncryption.py
tests/terraform/checks/resource/aws/example_LaunchConfigurationEBSEncryption/main.tf
tests/terraform/checks/resource/aws/test_LaunchConfigurationEBSEncryption.py

Refactored as Launch config test never tested

---

checkov/terraform/checks/resource/gcp/DataFusionPrivateInstance.py
tests/terraform/checks/resource/gcp/example_DataFusionPrivateInstance/main.tf
tests/terraform/checks/resource/gcp/test_DataFusionPrivateInstance.py

Ensure data fusion instances are private

---

checkov/common/graph/graph_builder/graph_components/blocks.py
checkov/terraform/checks/resource/gcp/DataflowJobEncryptedWithCMK.py

Add resource type to data nodes

---

checkov/terraform/checks/resource/gcp/DataprocClusterEncryptedWithCMK.py
tests/terraform/checks/resource/gcp/example_DataprocClusterEncryptedWithCMK/main.tf
tests/terraform/checks/resource/gcp/test_DataprocClusterEncryptedWithCMK.py

Ensure Dataproc uses KMS

---

checkov/terraform/checks/resource/gcp/SpannerDatabaseEncryptedWithCMK.py
tests/terraform/checks/resource/gcp/example_SpannerDatabaseEncryptedWithCMK/main.tf
tests/terraform/checks/resource/gcp/test_SpannerDatabaseEncryptedWithCMK.py

Spanner is encrypted with CMK

---

checkov/cloudformation/graph_builder/local_graph.py
checkov/cloudformation/graph_builder/variable_rendering/renderer.py
checkov/secrets/runner.py

1. Avoid scanning for secrets over large files - over 6 MB of text.
2. Handle bad CFN and SAM template keys - non-existent global key, bad properties, bad if condition structure.

Handle multiple errors gracefully

---

checkov/terraform/checks/resource/gcp/VertexAIMetadataStoreEncryptedWithCMK.py
tests/terraform/checks/resource/gcp/example_VertexAIMetadataStoreEncryptedWithCMK/main.tf
tests/terraform/checks/resource/gcp/test_VertexAIMetadataStoreEncryptedWithCMK.py

Ensure vertex_ai_metadata_store Encrypted with CMK

---

checkov/terraform/module_loading/module_finder.py
tests/terraform/module_loading/data/tf_module_downloader/main.tf
tests/terraform/module_loading/test_tf_module_finder.py

Ignores the "source" line if it's commented out.

ignore if source line starts with #

---

checkov/terraform/checks/resource/azure/AKSDashboardDisabled.py
tests/terraform/checks/resource/azure/example_AKSDashboardDisabled/main.tf
tests/terraform/checks/resource/azure/test_AKSDashboardDisabled.py

For clarity and use new test method

---

checkov/terraform/checks/resource/aws/CloudfrontDistributionEnabled.py
tests/terraform/checks/resource/aws/example_CloudfrontDistributionEnabled/main.tf
tests/terraform/checks/resource/aws/test_CloudfrontDistributionEnabled.py

Enable cloudfront

---

checkov/terraform/checks/resource/aws/APIGatewayDeploymentCreateBeforeDestroy.py
tests/terraform/checks/resource/aws/example_APIGatewayDeploymentCreateBeforeDestroy/main.tf
tests/terraform/checks/resource/aws/test_APIGatewayDeploymentCreateBeforeDestroy.py

Api Gateway deployments - create before destroy

---

checkov/terraform/checks/resource/aws/CloudsearchDomainTLS.py
tests/terraform/checks/resource/aws/example_CloudsearchDomainTLS/main.tf
tests/terraform/checks/resource/aws/test_CloudsearchDomainTLS.py

cloudsearch ensure latest TLS policy

---

checkov/terraform/checks/resource/aws/CodePipelineArtifactsEncrypted.py
tests/terraform/checks/resource/aws/example_CodePipelineArtifactsEncrypted/main.tf
tests/terraform/checks/resource/aws/test_CodePipelineArtifactsEncrypted.py

Codepipeline KMS for artifacts store

---

checkov/terraform/checks/resource/azure/FunctionAppHttpVersionLatest.py
tests/terraform/checks/resource/azure/example_AppServiceHttps20Enabled/main.tf
tests/terraform/checks/resource/azure/example_FunctionAppHttpVersionLatest/main.tf
tests/terraform/checks/resource/azure/test_AppServiceHttps20Enabled.py
tests/terraform/checks/resource/azure/test_FunctionAppHttpVersionLatest.py

updater http2 test with slots for functionapps

---

checkov/common/output/report.py
checkov/common/runners/runner_registry.py
checkov/main.py

Add support for outputting results to file

---

checkov/terraform/checks/resource/aws/CloudsearchDomainEnforceHttps.py
tests/terraform/checks/resource/aws/example_CloudsearchDomainEnforceHttps/main.tf
tests/terraform/checks/resource/aws/test_CloudsearchDomainEnforceHttps.py

cloudsearch domain - and enforce https

---

checkov/terraform/checks/resource/aws/CodeArtifactDomainEncryptedWithCMK.py
tests/terraform/checks/resource/aws/example_CodeArtifactDomainEncryptedWithCMK/main.tf
tests/terraform/checks/resource/aws/test_CodeArtifactDomainEncryptedWithCMK.py

CMK for code artifact domain

---

checkov/terraform/checks/resource/aws/ECSClusterLoggingEnabled.py
tests/terraform/checks/resource/aws/example_ECSClusterLoggingEnabled/main.tf

ensure ecs cluster is logging

---

checkov/terraform/checks/resource/aws/APIGatewayMethodSettingsCacheEnabled.py
tests/terraform/checks/resource/aws/example_APIGatewayMethodSettingsCacheEnabled/main.tf
tests/terraform/checks/resource/aws/test_APIGatewayMethodSettingsCacheEnabled.py
tests/terraform/graph/checks/resources/GCPLogBucketsConfiguredUsingLock/main.tf

API gateway methods setting cache enabled

---

checkov/common/runners/runner_registry.py

Fixes an issue where some branches in print_reports did not use the custom JSON serializer

use custom JSON encoder

---

checkov/common/output/report.py
tests/common/output/test_junit_report.py

fix handling of missing severties

---

checkov/sca_image/runner.py
checkov/sca_package/runner.py

Clean up twistcli after running image scan locally

---

checkov/terraform/checks/resource/panos/NetworkIPsecAlgorithms.py
tests/terraform/checks/resource/panos/example_NetworkIPsecAlgorithms/main.tf
tests/terraform/checks/resource/panos/test_NetworkIPsecAlgorithms.py

A resource check for PAN-OS Terraform provider to ensure use of secure algorithms for IPsec VPNs. It can be configured in two different resource types, both are covered by this check.

PAN-OS resource check for IPsec algorithms

---

integration_tests/prepare_data.sh
integration_tests/test_checkov_cyclonedx_report.py
integration_tests/test_checkov_sarif_report.py

add cyclonedx and sarif integration tests

---

checkov/terraform/checks/resource/aws/ACMCertCreateBeforeDestroy.py
tests/terraform/checks/resource/aws/example_ACMCertCreateBeforeDestroy/main.tf
tests/terraform/checks/resource/aws/test_ACMCertCreateBeforeDestroy.py

Create Certs before you destroy them

---

checkov/terraform/checks/resource/gcp/DataFusionStackdriverLogs.py
tests/terraform/checks/resource/gcp/example_DataFusionStackdriverLogs/main.tf
tests/terraform/checks/resource/gcp/test_DataFusionStackdriverLogs.py

Datafusion instances - You'll be needing logging

---

checkov/dockerfile/checks/RunUsingAPT.py
tests/dockerfile/checks/example_RunUsingAPT/failure/Dockerfile
tests/dockerfile/checks/example_RunUsingAPT/success/Dockerfile
tests/dockerfile/checks/test_RunUsingAPT.py

Docker: prefer apt-get over apt

---

checkov/terraform/checks/resource/aws/ACMCertSetLoggingPreference.py
tests/terraform/checks/resource/aws/example_ACMCertSetLoggingPreference/main.tf
tests/terraform/checks/resource/aws/test_ACMCertSetLoggingPreference.py

logging ACM certificate lookups

---

checkov/dockerfile/checks/WorkdirIsAbsolute.py
tests/dockerfile/checks/example_WorkdirIsAbsolute/failure/Dockerfile
tests/dockerfile/checks/example_WorkdirIsAbsolute/success/Dockerfile
tests/dockerfile/checks/test_WorkdirIsAbsolute.py

Workdir should be absolute path

---

checkov/terraform/checks/resource/aws/AMICopyUsesCMK.py
tests/terraform/checks/resource/aws/example_AMICopyUsesCMK/main.tf
tests/terraform/checks/resource/aws/test_AMICopyUsesCMK.py

ami should be copied and encrypted with a CMK

---

checkov/common/graph/graph_builder/graph_components/blocks.py
tests/terraform/graph/graph_builder/test_graph_builder.py
tests/terraform/graph/resources/s3_bucket_grant/main.tf

I did a mistake in my last PR, which will be fixed with this one, also added a test to prevent someone else for doing the same mistake 🙈

fix single item list attribute flattening

---

checkov/dockerfile/checks/AliasIsUnique.py
tests/dockerfile/checks/example_AliasIsUnique/failure/Dockerfile
tests/dockerfile/checks/example_AliasIsUnique/success/Dockerfile
tests/dockerfile/checks/test_AliasIsUnique.py

Avoid clashing alias in multistage builds

---

.cfnlintrc
checkov/cloudformation/checks/resource/aws/LambdaEnvironmentCredentials.py
tests/cloudformation/checks/resource/aws/example_LambdaEnvironmentCredentials/sam.yaml
tests/cloudformation/checks/resource/aws/test_LambdaEnvironmentCredentials.py

check if CFN Properties is a dict

---

checkov/terraform/checks/resource/aws/APIGatewayCreateBeforeDestroy.py
tests/terraform/checks/resource/aws/example_APIGatewayCreateBeforeDestroy/main.tf
tests/terraform/checks/resource/aws/test_APIGatewayCreateBeforeDestroy.py

preserve api gateway in service - create before destroy

---

checkov/terraform/checks/resource/kubernetes/PrivilegedContainerPSP.py
tests/terraform/checks/resource/kubernetes/example_PrivilegedContainersPSP/main.tf
tests/terraform/checks/resource/kubernetes/test_PrivilegedContainersPSP.py

k8s: tf: Dont use privileged containers

---

checkov/terraform/checks/resource/kubernetes/AllowPrivilegeEscalationPSP.py
tests/terraform/checks/resource/kubernetes/example_AllowPrivilegeEscalationPSP/main.tf
tests/terraform/checks/resource/kubernetes/test_AllowPrivilegeEscalationPSP.py

Implements CKV_K8S_5 for K8s tf

---

checkov/terraform/checks/resource/kubernetes/PrivilegedContainerPSP.py
tests/terraform/checks/resource/kubernetes/example_PrivilegedContainersPSP/main.tf

Fix/ckv k8_s_2 dict if using legacy provider

---

checkov/arm/context_parser.py
checkov/arm/parser/__init__.py
checkov/bitbucket/dal.py
checkov/cloudformation/cfn_utils.py
checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py
checkov/common/bridgecrew/integration_features/features/fixes_integration.py
checkov/common/bridgecrew/integration_features/features/policy_metadata_integration.py
checkov/common/bridgecrew/integration_features/features/repo_config_integration.py
checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
checkov/common/bridgecrew/platform_integration.py
checkov/common/bridgecrew/vulnerability_scanning/image_scanner.py
checkov/common/bridgecrew/wrapper.py
checkov/common/checks/base_check.py
checkov/common/graph/graph_builder/utils.py
checkov/common/output/baseline.py
checkov/common/output/report.py
checkov/common/runners/runner_registry.py
checkov/common/util/ext_argument_parser.py
checkov/common/vcs/base_vcs_dal.py
checkov/common/vcs/vcs_schema.py
checkov/helm/runner.py
checkov/kubernetes/kubernetes_utils.py
checkov/kustomize/runner.py
checkov/sca_image/runner.py
checkov/sca_package/scanner.py
checkov/secrets/runner.py
checkov/serverless/parsers/parser.py

- adjusted the error logging to leverage `exc_info`
- adjusted some type hints
- removed some unused imports

change error logging to leverage exc_info

---

checkov/common/bridgecrew/platform_integration.py
docs/9.Level up/Level up.md

fix: https://github.com/bridgecrewio/checkov/issues/2284

add level up/down docs

---

checkov/terraform/checks/resource/kubernetes/RootContainerPSP.py
tests/terraform/checks/resource/kubernetes/example_RootContainerPSP/main.tf
tests/terraform/checks/resource/kubernetes/test_RootContainerPSP.py

Implement CKV_K8S_6 in tf for Kubernetes

---

checkov/terraform/checks/resource/kubernetes/DropCapabilitiesPSP.py
tests/terraform/checks/resource/kubernetes/example_DropCapabilitiesPSP/main.tf
tests/terraform/checks/resource/kubernetes/test_DropCapabilitiesPSP.py

Implement CKV_K8S_7 for terraform

---

checkov/terraform/checks/resource/kubernetes/LivenessProbe.py
tests/terraform/checks/resource/kubernetes/example_LivenessProbe/main.tf
tests/terraform/checks/resource/kubernetes/test_LivenessProbe.py

Implement CKV_K8S_8 for tf

---

checkov/terraform/checks/resource/kubernetes/MemoryLimits.py
checkov/terraform/checks/resource/kubernetes/MemoryRequests.py
tests/terraform/checks/resource/kubernetes/example_MemoryLimits/main.tf
tests/terraform/checks/resource/kubernetes/example_MemoryRequests/main.tf
tests/terraform/checks/resource/kubernetes/test_MemoryLimits.py
tests/terraform/checks/resource/kubernetes/test_MemoryRequests.py

adding CKV_K8S_12 and CKV_K8S_13 for memory requests and limits for k8s tf

---

checkov/terraform/checks/resource/kubernetes/CPULimits.py
checkov/terraform/checks/resource/kubernetes/CPURequests.py
tests/terraform/checks/resource/kubernetes/example_CPULimits/main.tf
tests/terraform/checks/resource/kubernetes/example_CPURequests/main.tf
tests/terraform/checks/resource/kubernetes/test_CPULimits.py
tests/terraform/checks/resource/kubernetes/test_CPURequests.py

CKV_K8S_10 for terraform kubernetes - cpu limits set and cpu requests

---

Pipfile
Pipfile.lock
checkov/bicep/parser.py
checkov/bicep/runner.py
setup.py
tests/bicep/test_runner.py

- added severities
- added parsing errors
- upgrade to latest `pycep` release to support additional functions

add severities and parsing errors to bicep runner

---

checkov/terraform/checks/resource/azure/FrontDoorWAFACLCVE202144228.py

Fix CKV_AZURE_133 - verify managed_rule can be validated

---

checkov/terraform/checks/resource/kubernetes/ReadonlyRootFilesystem.py
tests/terraform/checks/resource/kubernetes/example_ReadonlyRootFilesystem/main.tf
tests/terraform/checks/resource/kubernetes/test_ReadonlyRootFilesystem.py

CKV_K8S_22 for terraform - read only filesystems for root volumes

---

checkov/sca_package/runner.py

If -f was passed, leverage the original file path as the path of the results, no relative paths

Fix -f support for SCA scanning

---

checkov/common/output/report.py
checkov/common/runners/runner_registry.py

Adds some logging for a customer who is getting unexplained exit codes

Add exit code logging

---

checkov/cloudformation/checks/resource/aws/ECRPolicy.py
checkov/terraform/checks/resource/aws/MQBrokerVersion.py

Handle missing attributes in ECRPolicy and MQBrokerVersion

---

checkov/terraform/checks/resource/kubernetes/AllowedCapabilitiesPSP.py
tests/terraform/checks/resource/kubernetes/example_AllowedCapabilitiesPSP/main.tf
tests/terraform/checks/resource/kubernetes/test_AllowedCapabilitiesPSP.py

implements CKV_K8S_24 for terraform

k8s pod security policy for terraform - allowed capabilities -arent CKV_K8S_24

---

checkov/common/checks_infra/solvers/connections_solvers/connection_exists_solver.py
checkov/common/output/record.py
checkov/terraform/runner.py
tests/terraform/graph/checks/test_yaml_connected_nodes.py

Add connected node data to graph check record, to be able create remediation for graph checks violations

Add connected node data to graph check record

---

checkov/terraform/checks/resource/azure/SynapseWorkspaceEnablesDataExfilProtection.py
tests/terraform/checks/resource/azure/example_SynapseWorkspaceEnablesDataExfilProtection/main.tf
tests/terraform/checks/resource/azure/test_SynapseWorkspaceEnablesDataExfilProtection.py

Ensure that Synapse workspace has data_exfiltration_protection_enabled

---

bin/checkov.cmd

We werent getting errors thrown on windows correctly, this fixes that. Needs some deployment testing.

Windows not failing

---

checkov/arm/checks/resource/SQLServerAuditingEnabled.py
checkov/bicep/checks/resource/azure/SQLServerAuditingEnabled.py
checkov/bicep/checks/resource/azure/StorageAccountAzureServicesAccessEnabled.py
checkov/bicep/checks/resource/azure/StorageAccountDefaultNetworkAccessDeny.py
checkov/bicep/checks/resource/azure/StorageAccountsTransportEncryption.py
checkov/bicep/checks/resource/base_resource_value_check.py
tests/arm/checks/resource/example_SQLServerAuditingEnabled/sqlServerAuditingEnabled-PASSED.json
tests/arm/checks/resource/example_SQLServerAuditingEnabled/sqlServerAuditingEnabled-TDE-FAILED.json
tests/arm/checks/resource/example_SQLServerAuditingEnabled/sqlServerDatabaseAuditingEnabled-PASSED.json
tests/arm/checks/resource/test_SQLServerAuditingEnabled.py
tests/bicep/checks/resource/azure/example_SQLServerAuditingEnabled/main.bicep
tests/bicep/checks/resource/azure/test_SQLServerAuditingEnabled.py

Relates to #2632 but it can't be completely fixed without adding support for graph checks to ARM and Bicep 😢 
Also added a `BaseResourceValueCheck` class to the Bicep runner 🚀

add CKV_AZURE_23 to bicep

---

checkov/terraform/checks/resource/azure/DatabricksWorkspaceIsNotPublic.py
tests/terraform/checks/resource/azure/example_DatabricksWorkspaceIsNotPublic/main.tf
tests/terraform/checks/resource/azure/test_DatabricksWorkspaceIsNotPublic.py

Ensure that databricks workspace has no public ip

---

bin/checkov.cmd

fix for cmd on windows

---

checkov/terraform/checks/resource/aws/APIGatewayMethodSettingsCacheEnabled.py
tests/terraform/checks/resource/aws/example_APIGatewayMethodSettingsCacheEnabled/main.tf

fix attribute CKV_AWS_225

---

checkov/terraform/checks/resource/kubernetes/PodSecurityContext.py
tests/terraform/checks/resource/kubernetes/example_PodSecurityContext/main.tf
tests/terraform/checks/resource/kubernetes/test_PodSecurityContext.py

check for security context CKV_K8S_29 for terraform k8s

---

checkov/terraform/checks/resource/kubernetes/DropCapabilities.py
tests/terraform/checks/resource/kubernetes/example_DropCapabilities/main.tf
tests/terraform/checks/resource/kubernetes/test_DropCapabilities.py

check for drop of NET_RAW or ALL - CKV_k8s_28 for terraform

---

checkov/terraform/checks/resource/aws/MWAASchedulerLogsEnabled.py
tests/terraform/checks/resource/aws/example_MWAASchedulerLogsEnabled/main.tf
tests/terraform/checks/resource/aws/test_MWAASchedulerLogsEnabled.py

Add check MWAA for validating scheduler logs are enabled.

Add MWAA scheduler logs check

---

checkov/terraform/checks/resource/kubernetes/SeccompPSP.py
tests/terraform/checks/resource/kubernetes/example_SeccompPSP/main.tf
tests/terraform/checks/resource/kubernetes/test_SeccompPSP.py

CKV_K8S_32 in tf:check annotations for seccomp profile

---

checkov/terraform/checks/resource/kubernetes/WildcardRoles.py
tests/terraform/checks/resource/kubernetes/example_WildcardRoles/main.tf
tests/terraform/checks/resource/kubernetes/test_WildcardRoles.py

Dont add wildcardrole definitions tf: CKV_K8S_49

---

checkov/terraform/checks/resource/kubernetes/ImagePullPolicyAlways.py
tests/terraform/checks/resource/kubernetes/example_ImagePullPolicyAlways/main.tf
tests/terraform/checks/resource/kubernetes/test_ImagePullPolicyAlways.py

implements CKV_K8S_15 in terraform

---

checkov/terraform/checks/resource/kubernetes/MinimiseCapabilitiesPSP.py
tests/terraform/checks/resource/kubernetes/example_MinimiseCapabilitiesPSP/main.tf
tests/terraform/checks/resource/kubernetes/test_MinimiseCapabilitiesPSP.py

check that required_drop_capabilities is set tf:CKV_k8s_36 

---

checkov/terraform/checks/resource/kubernetes/DefaultServiceAccount.py
tests/terraform/checks/resource/kubernetes/example_DefaultServiceAccount/main.tf
tests/terraform/checks/resource/kubernetes/test_DefaultServiceAccount.py

Check for default service account tf:CKV_K8S_41

---

checkov/terraform/checks/resource/kubernetes/DefaultServiceAccountBinding.py
tests/terraform/checks/resource/kubernetes/example_DefaultServiceAccountBinding/main.tf
tests/terraform/checks/resource/kubernetes/test_DefaultServiceAccountBinding.py

dont use the default service account tf:CKV_K8S_42

---

checkov/kubernetes/checks/resource/k8s/RootContainers.py
checkov/terraform/checks/resource/kubernetes/ContainerSecurityContext.py
tests/terraform/checks/resource/kubernetes/example_ContainerSecurityContext/main.tf
tests/terraform/checks/resource/kubernetes/test_ContainerSecurityContext.py

k8s:terraform: CKV_K8S_30 Check for security context

---

checkov/terraform/checks/resource/kubernetes/Secrets.py
tests/terraform/checks/resource/kubernetes/example_Secrets/main.tf
tests/terraform/checks/resource/kubernetes/test_Secrets.py

tf:k8s: CKV_K8S_35 check for secrets

---

checkov/terraform/checks/resource/kubernetes/AllowedCapabilitiesSysAdmin.py
tests/terraform/checks/resource/kubernetes/example_AllowedCapabilitiesSysAdmin/main.tf
tests/terraform/checks/resource/kubernetes/test_AllowedCapabilitiesSysAdmin.py

tf:k8s: CKV_K8S_39 Do not use the CAP_SYS_ADMIN linux capability

---

tests/terraform/runner/test_plan_runner.py

fix tf4 ut

---

checkov/terraform/graph_builder/graph_components/module.py
checkov/terraform/parser.py
tests/terraform/graph/graph_builder/test_graph_builder.py
tests/terraform/graph/resources/terraform_block/main.tf

Parse terraform blocks into tf definition

---

checkov/terraform/runner.py

fix none connected_entity_context

---

checkov/bicep/graph_builder/local_graph.py
checkov/bicep/graph_manager.py
checkov/bicep/runner.py
checkov/common/runners/base_runner.py

I think that `parsing_errors: dict[str, Exception]` should be `parsing_errors: list[str]` but need to verify in a later PR, because this would result in some code changes in the other runners code.

fix mypy issues

---

checkov/bicep/runner.py
checkov/terraform/runner.py

fix save graph for tf graph scanner

---

checkov/cloudformation/checks/resource/aws/ALBListenerHTTPS.py
checkov/cloudformation/checks/resource/aws/ALBListenerTLS12.py
tests/cloudformation/checks/resource/aws/example_ALBListener/ALBListenerHTTPS-PASSED-TCP.yaml
tests/cloudformation/checks/resource/aws/example_ALBListenerTLS12/ALBListenerTLS1.2-PASSED.yaml
tests/cloudformation/checks/resource/aws/test_ALBListenerHTTPS.py
tests/cloudformation/checks/resource/aws/test_ALBListenerTLS12.py

Handle cases where intrinsic functions could not be evaluated, marking the check result as UNKNOWN

ALB listeners CFN intrinsic functions cases

---

checkov/terraform/runner.py
tests/terraform/graph/runner/test_graph_builder.py

revert save graph

---

checkov/terraform/checks/resource/kubernetes/MinimiseCapabilities.py
tests/terraform/checks/resource/kubernetes/example_MinimiseCapabilities/main.tf
tests/terraform/checks/resource/kubernetes/test_MinimiseCapabilities.py

tf:k8s CKV_K8S_37:Minimise the admission of containers with capabilities assigned

---

checkov/terraform/checks/resource/kubernetes/TillerService.py
tests/terraform/checks/resource/kubernetes/example_TillerService/main.tf
tests/terraform/checks/resource/kubernetes/test_TillerService.py

tf:k8s:CKV_K8S_44 ensure theres no tiller service

---

checkov/terraform/checks/resource/kubernetes/ImageDigest.py
tests/terraform/checks/resource/kubernetes/example_ImageDigest/main.tf
tests/terraform/checks/resource/kubernetes/test_ImageDigest.py

tf:k8s:CKV_K8S_43 Images digest use @

---

checkov/terraform/checks/graph_checks/aws/S3BucketEncryption.yaml
checkov/terraform/checks/graph_checks/aws/S3BucketVersioning.yaml
checkov/terraform/checks/graph_checks/aws/S3PublicACLRead.yaml
checkov/terraform/checks/graph_checks/aws/S3PublicACLWrite.yaml
tests/terraform/graph/checks/resources/S3BucketEncryption/expected.yaml
tests/terraform/graph/checks/resources/S3BucketEncryption/main.tf
tests/terraform/graph/checks/resources/S3BucketVersioning/expected.yaml
tests/terraform/graph/checks/resources/S3BucketVersioning/main.tf
tests/terraform/graph/checks/resources/S3PublicACLRead/expected.yaml
tests/terraform/graph/checks/resources/S3PublicACLRead/main.tf
tests/terraform/graph/checks/resources/S3PublicACLWrite/expected.yaml
tests/terraform/graph/checks/resources/S3PublicACLWrite/main.tf
tests/terraform/graph/checks/test_yaml_connected_nodes.py

fix tf v4 checks

---

checkov/terraform/parser.py
checkov/terraform/runner.py
tests/terraform/runner/resources/hidden_dir/.dir/.example1.tf
tests/terraform/runner/resources/hidden_dir/.example2.tf
tests/terraform/runner/resources/hidden_dir/dir1/.example1.tf
tests/terraform/runner/resources/hidden_dir/dir1/example.tf
tests/terraform/runner/resources/hidden_dir/example.tf
tests/terraform/runner/test_runner.py

Fixed hidden files/dirs issue.
Added tests for CKV_IGNORE_HIDDEN_DIRECTORIES and CKV_IGNORED_DIRECTORIES environment variables. 
Closes #2548

Fixed hidden files/dirs issue.

---

checkov/terraform/checks/resource/alicloud/ActionTrailLogAllEvents.py
checkov/terraform/checks/resource/alicloud/ActionTrailLogAllRegions.py
tests/terraform/checks/resource/alicloud/example_ActionTrailLogAllEvents/main.tf
tests/terraform/checks/resource/alicloud/example_ActionTrailLogAllRegions/main.tf
tests/terraform/checks/resource/alicloud/test_ActionTrailLogAllEvents.py
tests/terraform/checks/resource/alicloud/test_ActionTrailLogAllRegions.py

ALICloud Trail event checks - all events - all regions CKV_ALI_4&5

---

checkov/terraform/checks/resource/kubernetes/Tiller.py
tests/terraform/checks/resource/kubernetes/example_Tiller/main.tf
tests/terraform/checks/resource/kubernetes/test_Tiller.py

CKV_K8S_34 in terraform - Ensure that Tiller (Helm v2) is not deployed

---

checkov/terraform/checks/resource/alicloud/DiskEncryptedWithCMK.py
checkov/terraform/checks/resource/alicloud/DiskIsEncrypted.py
tests/terraform/checks/resource/alicloud/example_DiskEncryptedWithCMK/main.tf
tests/terraform/checks/resource/alicloud/example_DiskIsEncrypted/main.tf
tests/terraform/checks/resource/alicloud/test_DiskEncryptedWithCMK.py
tests/terraform/checks/resource/alicloud/test_DiskIsEncrypted.py

ALI cloud check for cloud disk encryption

---

checkov/terraform/runner.py

Cache non-existing referrers

---

checkov/terraform/checks/resource/gcp/GKEClientCertificateDisabled.py
tests/terraform/checks/resource/gcp/test_GKEClientCertificateDisabled.py

Disable GKE client certificate authentication (CKV_GCP_13)

---

checkov/terraform/checks/resource/gcp/GKEClientCertificateDisabled.py
tests/terraform/runner/test_plan_runner.py

fix check 145 tests

---

checkov/cloudformation/runner.py

Return Cloudformation graph checks results for only resources

---

checkov/terraform/checks/resource/alicloud/OSSBucketVersioning.py
tests/terraform/checks/resource/alicloud/example_OSSBucketVersioning/main.tf
tests/terraform/checks/resource/alicloud/test_OSSBucketVersioning.py

Alicloud Enable bucket versioning

---

checkov/terraform/checks/resource/alicloud/RDSInstanceSSL.py
tests/terraform/checks/resource/alicloud/example_DiskEncryptedWithCMK/main.tf
tests/terraform/checks/resource/alicloud/example_DiskIsEncrypted/main.tf
tests/terraform/checks/resource/alicloud/example_RDSInstanceSSL/main.tf
tests/terraform/checks/resource/alicloud/test_RDSInstanceSSL.py

Alicloud Ensure RDS uses SSL

---

checkov/arm/checks/resource/AzureInstancePassword.py
tests/arm/checks/resource/example_AzureInstancePassword/UNKNOWN_1.json
tests/arm/checks/resource/test_AzureInstancePassword.py

Add check for microsoft as a publisher

---

checkov/terraform/checks/resource/alicloud/PasswordPolicyExpiration.py
checkov/terraform/checks/resource/alicloud/PasswordPolicyLength.py
checkov/terraform/checks/resource/alicloud/PasswordPolicyLowercaseLetter.py
checkov/terraform/checks/resource/alicloud/PasswordPolicyNumber.py
checkov/terraform/checks/resource/alicloud/PasswordPolicyReuse.py
checkov/terraform/checks/resource/alicloud/PasswordPolicySymbol.py
checkov/terraform/checks/resource/alicloud/PasswordPolicyUppcaseLetter.py
tests/terraform/checks/resource/alicloud/example_PasswordPolicyExpiration/main.tf
tests/terraform/checks/resource/alicloud/example_PasswordPolicyLength/main.tf
tests/terraform/checks/resource/alicloud/example_PasswordPolicyLowercaseLetter/main.tf
tests/terraform/checks/resource/alicloud/example_PasswordPolicyNumber/main.tf
tests/terraform/checks/resource/alicloud/example_PasswordPolicyReuse/main.tf
tests/terraform/checks/resource/alicloud/example_PasswordPolicySymbol/main.tf
tests/terraform/checks/resource/alicloud/example_PasswordPolicyUppcaseLetter/main.tf
tests/terraform/checks/resource/alicloud/test_PasswordPolicyExpiration.py
tests/terraform/checks/resource/alicloud/test_PasswordPolicyLength.py
tests/terraform/checks/resource/alicloud/test_PasswordPolicyLowercaseLetter.py
tests/terraform/checks/resource/alicloud/test_PasswordPolicyNumber.py
tests/terraform/checks/resource/alicloud/test_PasswordPolicyReuse.py
tests/terraform/checks/resource/alicloud/test_PasswordPolicySymbol.py
tests/terraform/checks/resource/alicloud/test_PasswordPolicyUppcaseLetter.py

ALI cloud Password policy

---

checkov/terraform/checks/resource/azure/AzureFrontDoorEnablesWAF.py
tests/terraform/checks/resource/azure/example_AzureFrontDoorEnablesWAF/main.tf
tests/terraform/checks/resource/azure/test_AzureFrontDoorEnablesWAF.py

Handle nested WAF
