checkov/example_runner/__init__.py, checkov/example_runner/checks/__init__.py, checkov/example_runner/checks/base_example_runner_check.py, checkov/example_runner/checks/base_example_runner_job_check.py, checkov/example_runner/checks/job/ExampleCheckTrueFalse.py, checkov/example_runner/checks/job/__init__.py, checkov/example_runner/checks/job_registry.py, checkov/example_runner/runner.py
This is meant to be a cut and paste example, following the inline comments and the contributor guide.  It's a head start to creating a runner based on the existing yaml and json templated runners.
=> first draft of example IaC runner code

checkov/bitbucket/dal.py, docs/7.Scan Examples/Bitbucket.md
This PR makes the username a variable and updates the docs for making bitbucket_configuration scans work.
=> update docs and add username variable

checkov/terraform/checks/resource/alicloud/RDSTransparentDataEncryptionEnabled.py, tests/terraform/checks/resource/alicloud/example_RDSInstanceSSL/main.tf, tests/terraform/checks/resource/alicloud/example_RDSTransparentDataEncryptionEnabled/main.tf, tests/terraform/checks/resource/alicloud/test_RDSTransparentDataEncryption.py
=> Alicoud RDS Check for TDE

checkov/terraform/checks/resource/alicloud/PasswordPolicyMaxLogin.py, tests/terraform/checks/resource/alicloud/example_PasswordPolicyMaxLogin/main.tf, tests/terraform/checks/resource/alicloud/test_PasswordPolicyMaxLogin.py
=> alicloud RAM Set max login attempts

checkov/common/parsers/yaml/parser.py, checkov/common/runners/object_runner.py, checkov/example_runner/__init__.py, checkov/example_runner/checks/__init__.py, checkov/example_runner/checks/base_example_runner_check.py, checkov/example_runner/checks/base_example_runner_job_check.py, checkov/example_runner/checks/job/ExampleCheckTrueFalse.py, checkov/example_runner/runner.py, checkov/yaml_doc/runner.py
Added type hints and fixed some code parts, because a return statement was missing.
=> fix mypy issues in example runner

checkov/terraform/checks/resource/alicloud/PasswordPolicyMaxAge.py, tests/terraform/checks/resource/alicloud/example_PasswordPolicyMaxAge/main.tf, tests/terraform/checks/resource/alicloud/test_PasswordPolicyMaxAge.py
=> alicloud max password age is 90 days

checkov/terraform/checks/resource/alicloud/RDSRetention.py, tests/terraform/checks/resource/alicloud/example_RDSRetention/main.tf, tests/terraform/checks/resource/alicloud/test_RDSRetention.py
=> alicloud: rds retain sql logs

checkov/common/checks/base_check.py, checkov/common/runners/object_runner.py, checkov/common/typing.py, checkov/example_runner/runner.py, checkov/json_doc/base_json_check.py, checkov/json_doc/base_registry.py, checkov/json_doc/runner.py, checkov/sca_package/runner.py, checkov/yaml_doc/base_registry.py, checkov/yaml_doc/base_yaml_check.py, checkov/yaml_doc/runner.py, mypy.ini
=> Fix mypy issues for json runner and yaml runner

checkov/terraform/checks/resource/alicloud/PasswordPolicyMaxLogin.py, tests/terraform/checks/resource/alicloud/example_PasswordPolicyMaxLogin/main.tf
fix edge-case in PasswordPolicyMaxLogin check return UNKNOWN if max_login_attempts is variable.
add a resource to tests for unknown result
=> Fix in PasswordPolicyMaxLogin check

checkov/common/runners/object_runner.py, tests/openapi/checks/resource/v2/test_SecurityDefinitions.py
=> Fix relative path in openapi runner result records 

checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py
Handle exceptions while parsing platform custom policies.
=> handle custom policy parsing exception

checkov/common/checks/object_registry.py, checkov/common/runners/object_runner.py, checkov/common/util/docs_generator.py, checkov/openapi/__init__.py, checkov/openapi/checks/base_registry.py, checkov/openapi/checks/resource/__init__.py, checkov/openapi/checks/resource/v2/SecurityDefinitions.py, checkov/openapi/checks/resource/v2/__init__.py, checkov/openapi/runner.py, tests/openapi/checks/resource/v2/example_SecurityDefinitions/fail2.yaml, tests/openapi/checks/resource/v2/test_SecurityDefinitions.py, tests/terraform/util/test_doc_generator.py
Fixed __init__ issue
Fixed relative path issue
=> openapi fix issues

integration_tests/test_checkov_cyclonedx_report.py
=> fix cyclone DX int test

checkov/cloudformation/checks/resource/aws/IAMRoleAllowAssumeFromAccount.py, tests/cloudformation/checks/resource/aws/example_IAMRoleAllowAssumeFromAccount/example_IAMRoleAllowAssumeFromAccount-PASSED.yml, tests/cloudformation/checks/resource/aws/test_IAMRoleAllowAssumeFromAccount.py
Handle cases where assume role policy document is composed of Fn::Sub with variable mapping
=> IAMRoleAllowAssumeFromAccount variable substitute mapping policies document

checkov/terraform/checks/resource/aws/RDSInstanceAutoBackupEncryptionWithCMK.py, tests/terraform/checks/resource/aws/example_RDSInstanceAutoBackupEncryptionWithCMK/main.tf, tests/terraform/checks/resource/aws/test_RDSInstanceAutoBackupEncryptionWithCMK.py
=> AWS tf ensure replicated backups are encrypted with CMK

checkov/terraform/checks/resource/aws/RDSClusterActivityStreamEncryptedWithCMK.py, tests/terraform/checks/resource/aws/example_RDSClusterActivityStreamEncryptedWithCMK/main.tf, tests/terraform/checks/resource/aws/test_RDSClusterActivityStreamEncryptedWithCMK.py
=> AWS tf:RDS Cluster Activity stream encryption with CMK

checkov/terraform/checks/resource/aws/ElasticsearchDomainEnforceHTTPS.py, checkov/terraform/checks/resource/aws/ElasticsearchEncryption.py, tests/terraform/checks/resource/aws/example_ElasticsearchDomainEnforceHTTPS/main.tf, tests/terraform/checks/resource/aws/example_ElasticsearchDomainEnforceHTTPS/opensearch.tf, tests/terraform/checks/resource/aws/example_ElasticsearchEncryption/main.tf, tests/terraform/checks/resource/aws/example_ElasticsearchEncryption/opensearch.tf, tests/terraform/checks/resource/aws/test_ElasticsearchDomainEnforceHTTPS.py, tests/terraform/checks/resource/aws/test_ElasticsearchEncryption.py
=> TF AWS:Add support for opensearch to elastic search checks

checkov/terraform/checks/resource/aws/ElasticsearchDomainLogging.py, tests/terraform/checks/resource/aws/example_ElasticsearchDomainLogging/main.tf, tests/terraform/checks/resource/aws/example_ElasticsearchDomainLogging/opensearch.tf, tests/terraform/checks/resource/aws/test_ElasticsearchDomainLogging.py
=> AWS TF: add opensearch cases and update check to look at enabled

checkov/terraform/checks/resource/aws/ElasticsearchInVPC.py, checkov/terraform/checks/resource/aws/ElasticsearchNodeToNodeEncryption.py, checkov/terraform/checks/resource/aws/ElasticsearchTLSPolicy.py, tests/terraform/checks/resource/aws/example_ElasticsearchInVPC/main.tf, tests/terraform/checks/resource/aws/example_ElasticsearchInVPC/opensearch.tf, tests/terraform/checks/resource/aws/example_ElasticsearchNodeToNodeEncryption/opensearch.tf, tests/terraform/checks/resource/aws/example_ElasticsearchTLSPolicy/opensearch.tf, tests/terraform/checks/resource/aws/test_ElasticsearchInVPC.py, tests/terraform/checks/resource/aws/test_ElasticsearchNodeToNodeEncryption.py, tests/terraform/checks/resource/aws/test_ElasticsearchTLSPolicy.py
=> AWS tf:Extend ES checks to opensearch

checkov/terraform/checks/resource/aws/ElasticsearchDefaultSG.py, tests/terraform/checks/resource/aws/example_ElasticsearchDefaultSG/main.tf, tests/terraform/checks/resource/aws/example_ElasticsearchDefaultSG/opensearch.tf, tests/terraform/checks/resource/aws/test_ElasticsearchDefaultSG.py
=> AWS:tf: Elasticsearch Check that an SG is specified

checkov/terraform/checks/resource/aws/ECSTaskDefinitionRoleCheck.py, tests/terraform/checks/resource/aws/example_ECSTaskDefinitionRoleCheck/main.tf, tests/terraform/checks/resource/aws/test_ECSTaskDefinitionRoleCheck.py
New check as discussed in #2602
=> Add TF check for Task Def having different Execution and Task roles

checkov/common/checks_infra/solvers/attribute_solvers/regex_match_attribute_solver.py
=> added try catch for regex_match_attribute_solver

checkov/common/output/report.py, checkov/main.py, checkov/openapi/checks/resource/__init__.py, checkov/openapi/checks/resource/generic/SecurityOperations.py, checkov/openapi/checks/resource/v3/CleartextOverUnencryptedChannel.py, checkov/openapi/checks/resource/v3/__init__.py, tests/openapi/runner/resources/v2/example.json, tests/openapi/runner/resources/v2/example.yaml, tests/openapi/runner/resources/v2/example.yml, tests/openapi/runner/resources/v2/example1.json, tests/openapi/runner/resources/v3/example.json, tests/openapi/runner/resources/v3/example.yaml, tests/openapi/runner/resources/v3/example1.json, tests/openapi/runner/resources/v3/example1.yaml, tests/openapi/runner/test_runner.py
=> Openapi unit tests

checkov/common/runners/base_runner.py, checkov/kubernetes/runner.py, checkov/kustomize/runner.py
refactor `report_mutator_data` to be class attribute in kustomize runner
=> report_mutator_data refactor

checkov/common/runners/base_runner.py
=> fix set external data

checkov/common/output/record.py
limit the lines of the printed output
=> Added output limitation

checkov/terraform/checks/resource/alicloud/K8sEnableNetworkPolicies.py, checkov/terraform/checks/resource/alicloud/RDSRetention.py, tests/terraform/checks/resource/alicloud/example_DiskIsEncrypted/main.tf, tests/terraform/checks/resource/alicloud/example_K8sEnableNetworkPolicies/main.tf, tests/terraform/checks/resource/alicloud/test_K8sEnableNetworkPolicies.py
=> Alicloud k8s Ensure that network plugin for k8s policy support is installed

checkov/kustomize/runner.py
=> kustomize check type

checkov/bicep/runner.py, checkov/common/parsers/yaml/parser.py, checkov/common/runners/object_runner.py, checkov/example_runner/runner.py, checkov/github/dal.py, checkov/json_doc/runner.py, checkov/yaml_doc/runner.py
- adjusted some type hints and return values
- added a skip, if the data from the GitHub request returns nothing
=> skip json checks for non json files

Pipfile, Pipfile.lock, setup.py
Fixes #2808 
@domroutley thanks for the great work on the parser 🚀
=> upgrade hcl2

docs/1.Welcome/Feature Descriptions.md
=> fix URL and reference for Gitlab

checkov/kubernetes/checks/resource/k8s/RbacBindRoleBindings.py, checkov/kubernetes/checks/resource/k8s/RbacEscalateRoles.py, tests/kubernetes/checks/example_RbacBindRoleBindings/clusterrole-failed-1.yaml, tests/kubernetes/checks/example_RbacBindRoleBindings/clusterrole-passed-1.yaml, tests/kubernetes/checks/example_RbacBindRoleBindings/role-failed-2.yaml, tests/kubernetes/checks/example_RbacBindRoleBindings/role-passed-2.yaml, tests/kubernetes/checks/example_RbacEscalateRoles/clusterrole-failed-1.yaml, tests/kubernetes/checks/example_RbacEscalateRoles/clusterrole-passed-1.yaml, tests/kubernetes/checks/example_RbacEscalateRoles/role-failed-2.yaml, tests/kubernetes/checks/example_RbacEscalateRoles/role-passed-2.yaml, tests/kubernetes/checks/test_RbacBindRoleBindings.py, tests/kubernetes/checks/test_RbacEscalateRoles.py
- **CKV_K8S_157**: Minimize Roles and ClusterRoles that grant permissions to bind RoleBindings or ClusterRoleBindings
- **CKV_K8S_158**: Minimize Roles and ClusterRoles that grant permissions to escalate Roles or ClusterRole
=> Add 2 new RBAC checks for k8s

checkov/bicep/graph_builder/graph_components/block_types.py, checkov/bicep/graph_builder/graph_to_tf_definitions.py, checkov/bicep/graph_builder/local_graph.py, checkov/bicep/graph_builder/variable_rendering/renderer.py, checkov/bicep/graph_manager.py, checkov/bicep/runner.py, checkov/common/graph/graph_builder/utils.py, checkov/terraform/graph_builder/local_graph.py, checkov/terraform/graph_builder/utils.py, mypy.ini, tests/bicep/graph/graph_builder/examples/parameter/main.bicep, tests/bicep/graph/graph_builder/test_renderer.py, tests/bicep/test_graph_manager.py
General setup for supporting variable rendering for Bicep. As initial step added rendering for `param` elements and support for property accessor (`someObject.name`), if possible. Also added a env var `CHECKOV_CREATE_GRAPH` to disable the creation of a graph, if needed.
=> add variable rendering for Bicep params

checkov/common/bridgecrew/severities.py, tests/common/test_runner_filter.py, tests/sca_package/test_output.py
=> Handle Moderate and Important severities without crashing

checkov/sca_package/runner.py, tests/sca_package/test_runner.py
=> Exclude file by names in SCA package runner

admissioncontroller/whorf.py
Fix to broken config file name
=> fixed config file name

checkov/common/runners/runner_registry.py
My first PR missed a helpful logging message.
=> add log message for framework filter by file type

checkov/kustomize/runner.py
=> Kustomize runner safe get type from metadata

checkov/terraform/checks/resource/gcp/DataFusionStackdriverMonitoring.py, tests/terraform/checks/resource/gcp/example_DataFusionStackdriverMonitoring/main.tf, tests/terraform/checks/resource/gcp/test_DataFusionStackdriverMonitoring.py
=> Add tf gcp check stack driver monitoring is enabled

checkov/common/bridgecrew/platform_integration.py, checkov/common/bridgecrew/vulnerability_scanning/image_scanner.py, checkov/common/bridgecrew/vulnerability_scanning/integrations/twistcli.py, checkov/common/util/file_utils.py, checkov/sca_image/runner.py, checkov/sca_package/runner.py, checkov/sca_package/scanner.py, tests/common/bridgecrew/vulnerability_scanning/integrations/test_docker_image_scanning.py, tests/sca_package/conftest.py, tests/sca_package/test_runner.py, tests/sca_package/test_scanner.py
Reverts bridgecrewio/checkov#2867
=> Leverage twistlock api in checkov - WIP II

checkov/kustomize/runner.py
=> fix kustomize init

checkov/sca_package/runner.py, tests/sca_package/test_output_reports.py, tests/sca_package/test_runner.py
removing the feature flag around sca package scanning
=> Remove package scanning feature flag

checkov/terraform/checks/resource/aws/CloudtrailEnableLogging.py, tests/terraform/checks/resource/aws/example_CloudtrailEnableLogging/main.tf, tests/terraform/checks/resource/aws/test_CloudtrailEnableLogging.py
=> CKV_AWS_251 Ensure logging for cloudtrail

checkov/sca_package/scanner.py
=> Replace iomultiprocess with simpler asyncio

checkov/terraform/checks/resource/aws/MSKClusterLogging.py, tests/terraform/checks/resource/aws/test_MSKClusterLogging.py
=> Handle empty cloudwatch_logs in aws_msk_cluster

checkov/terraform/checks/resource/oci/AbsSecurityGroupUnrestrictedIngress.py, tests/terraform/checks/resource/oci/example_SecurityGroupUnrestrictedIngress22/main.tf, tests/terraform/checks/resource/oci/test_SecurityGroupUnrestrictedIngress22.py
=> Support missing source_port_range in oci_core_network_security_group_security_rule

checkov/terraform/checks/resource/aws/CloudtrailDefinesSNSTopic.py, tests/terraform/checks/resource/aws/example_CloudtrailDefinesSNSTopic/main.tf, tests/terraform/checks/resource/aws/test_CloudtrailDefinesSNSTopic.py
=> Ensure SNS topic is defined for a cloud trail

checkov/terraform/checks/resource/aws/DLMScheduleCrossRegionEncryption.py, tests/terraform/checks/resource/aws/example_DLMScheduleCrossRegionEncryption/main.tf, tests/terraform/checks/resource/aws/test_DLMScheduleCrossRegionEncryption.py
=> DLM encrypt scheduled cross region copies

checkov/bicep/graph_builder/context_definitions.py, tests/bicep/graph/definitions_context/resources/definitions_example1.bicep, tests/bicep/graph/definitions_context/resources/definitions_example2.bicep, tests/bicep/graph/definitions_context/test_definitions_context.py
=> Created bicep graph definition context

checkov/common/bridgecrew/platform_integration.py
=> leverage S3 acceleration endpoint

checkov/terraform/graph_manager.py, checkov/terraform/parser.py, checkov/terraform/runner.py
and the last one of the graphs. Now it is possible to disable graph creation for all runners, which support graphs.
=> add possibility to disable TF graph creation

checkov/kubernetes/checks/resource/k8s/RootContainers.py, checkov/terraform/checks/resource/azure/StorageAccountLoggingQueueServiceEnabled.py, checkov/terraform/checks/resource/kubernetes/AllowPrivilegeEscalation.py, checkov/terraform/checks/resource/oci/AbsSecurityListUnrestrictedIngress.py, checkov/terraform/runner.py, tests/kubernetes/checks/example_RootContainers/rootContainersFAILED_2.yaml, tests/kubernetes/checks/test_RootContainers.py, tests/terraform/checks/resource/azure/test_StorageAccountLoggingQueueServiceEnabled.py, tests/terraform/checks/resource/kubernetes/example_AllowPrivilegeEscalation/main.tf, tests/terraform/checks/resource/oci/example_SecurityListUnrestrictedIngress22/main.tf, tests/terraform/checks/resource/oci/test_SecurityListUnrestrictedIngress22.py
=> Fix some checks validations

checkov/arm/base_resource_check.py, checkov/bicep/checks/resource/base_resource_check.py, checkov/main.py, tests/bicep/examples/existing.bicep, tests/bicep/test_graph_manager.py, tests/bicep/test_runner.py
Fixes #2870 
Looks like I just forgot to add the skip part to the Bicep checks 😄 I also removed a change I accidentally added to the `main.py` which I quite often use for timing measure 🙈
=> skip existing bicep resource

docs/7.Scan Examples/CDK.md
example for community for AWS CDK skip python
=> example for community for AWS CDK skip python

checkov/terraform/checks/resource/github/BranchProtectionReviewNumTwo.py, tests/terraform/checks/resource/github/example_BranchProtectionReviewNumTwo/main.tf, tests/terraform/checks/resource/github/test_BranchProtectionReviewNumTwo.py
=> github review count >= 2  #2902

checkov/terraform/checks/graph_checks/azuredevops/ADORepositoryHasMinTwoReviewers.yaml, tests/terraform/graph/checks/resources/ADORepositoryHasMinTwoReviewers/expected.yaml, tests/terraform/graph/checks/resources/ADORepositoryHasMinTwoReviewers/main.tf, tests/terraform/graph/checks/test_yaml_policies.py
=> CKV2_ADO_1 AzureDevops Min 2 approving reviews for a PR

checkov/terraform/checks/graph_checks/aws/CodecommitApprovalRulesAttached.yaml, tests/terraform/graph/checks/resources/CodecommitApprovalRulesAttached/expected.yaml, tests/terraform/graph/checks/resources/CodecommitApprovalRulesAttached/main.tf, tests/terraform/graph/checks/test_yaml_policies.py
=> Ensure codecommit repo attaches at least 1 approval rule template

checkov/terraform/checks/resource/aws/CodecommitApprovalsRulesRequireMin2.py, tests/terraform/checks/resource/aws/example_CodecommitApprovalsRulesRequireMin2/main.tf, tests/terraform/checks/resource/aws/test_CodecommitApprovalRulesRequireMin2.py
=> Require 2 approvers for codecommit

checkov/terraform/checks/resource/gitlab/ForcePushDisabled.py, tests/terraform/checks/resource/gitlab/example_ForcePushDisabled/main.tf, tests/terraform/checks/resource/gitlab/test_ForcePushDisabled.py
=> gitlab force push disabled

checkov/terraform/checks/resource/gitlab/RejectUnsignedCommits.py, tests/terraform/checks/resource/gitlab/example_RejectUnsignedCommits/main.tf, tests/terraform/checks/resource/gitlab/test_RejectUnsignedCommits.py
=> gitlab Reject unsigned commits

checkov/dockerfile/checks/UpdateNotAlone.py, checkov/dockerfile/runner.py, tests/dockerfile/checks/example_UpdateNotAlone/failure/Dockerfile, tests/dockerfile/checks/example_UpdateNotAlone/failure/Dockerfile.simple, tests/dockerfile/checks/test_UpdateNotAlone.py
Fix for #2817 Provide multiple results for a failed test
=> Show multiple failures for UpdateNotAlone check

checkov/openapi/checks/resource/v2/Oauth2SecurityRequirement.py, tests/openapi/checks/resource/v2/example_Oauth2SecurityRequirement/fail2.yaml
=> openapi checks were crashing as failed to check type

checkov/bicep/runner.py, checkov/kustomize/runner.py
- inject runner-specific data to bicep and kustomize runners
- added definitions context to bicep runner
=> Kustomize and bicep custom properties

checkov/github_actions/checks/job/ReverseShellNetcat.py, checkov/github_actions/checks/job/SuspectCurlInScript.py, tests/github_actions/resources/.github/workflows/netcatreverseshell.yaml, tests/github_actions/resources/.github/workflows/suspectcurl.yaml, tests/github_actions/test_runner.py
Added checks and test yaml for malicious looking curl and for netcat in GHA
=> Added check for curl and netcat for GHA

checkov/bicep/parser.py
=> added create_definitions for bicep

integration_tests/run_integration_tests.sh
Added script that runs integration tests locally.
=> Added run_integration_test.sh script

checkov/common/parallelizer/parallel_runner.py, checkov/secrets/runner.py
=> Allow overriding running secrets in multi processing

checkov/common/parallelizer/parallel_runner.py
=> Fix multiprocessing condition for windows

checkov/cloudformation/parser/cfn_yaml.py
=> Handle malformed template in CFN YAML parser

checkov/arm/checks/resource/AppServiceAuthentication.py, checkov/arm/checks/resource/AzureManagedDiscEncryption.py, checkov/arm/checks/resource/MonitorLogProfileCategories.py, checkov/arm/checks/resource/MonitorLogProfileRetentionDays.py, tests/arm/checks/resource/example_AzureManagedDiscEncryption/azureManagedDiscEncryption-FAILED.json, tests/arm/checks/resource/example_AzureManagedDiscEncryption/azureManagedDiscEncryption-PASSED_2.json, tests/arm/checks/resource/example_MonitorLogProfileCategories/monitorLogProfileCategories-FAILED.json, tests/arm/checks/resource/example_MonitorLogProfileCategories/monitorLogProfileCategories-PASSED.json, tests/arm/checks/resource/example_MonitorLogProfileRetentionDays/monitorLogProfileRetentionDays-FAILED.json, tests/arm/checks/resource/example_MonitorLogProfileRetentionDays/monitorLogProfileRetentionDays-FAILED2.json, tests/arm/checks/resource/example_MonitorLogProfileRetentionDays/monitorLogProfileRetentionDays-PASSED.json, tests/arm/checks/resource/test_AzureManagedDiscEncryption.py, tests/arm/checks/resource/test_MonitorLogProfileCategories.py, tests/arm/checks/resource/test_MonitorLogRetentionDays.py, tests/bicep/checks/resource/azure/example_AzureManagedDiscEncryption/main.bicep, tests/bicep/checks/resource/azure/example_MonitorLogProfileCategories/main.bicep, tests/bicep/checks/resource/azure/example_MonitorLogProfileRetentionDays/main.bicep, tests/bicep/checks/resource/azure/test_AzureManagedDiscEncryption.py, tests/bicep/checks/resource/azure/test_MonitorLogProfileCategories.py, tests/bicep/checks/resource/azure/test_MonitorLogProfileRetentionDays.py
Fixed couple of ARM checks, which probably never worked and an other one just supported the old api version. Also added Bicep tests for those checks to make sure they work for both ARM and Bicep.
=> fix ARM checks and add Bicep tests

checkov/helm/runner.py, tests/helm/runner/resources/pwnchart/Chart.yaml, tests/helm/runner/resources/pwnchart/templates/_helpers.tpl, tests/helm/runner/resources/pwnchart/templates/clusterrole.yaml, tests/helm/runner/resources/pwnchart/templates/clusterrolebinding.yaml, tests/helm/runner/resources/pwnchart/values.yaml, tests/helm/test_runner.py
Added test for helm runner.
Changed the paths in the helm runner report to be without the temp dir prefix.
=> add UT to helm runner and fix report paths

checkov/dockerfile/utils.py, tests/helm/test_runner.py
Adjusted the helm test to only run, if helm exists 🙂
=> skip helm test, if not installed

checkov/helm/runner.py
fix target dir and the returning statement. 
add debug log and remove redundant function.
=> Fixes in helm runner

checkov/cloudformation/checks/resource/BaseCloudsplainingIAMCheck.py
Cached `PolicyDocument` result to avoid slow calculation begin done repeatedly.
=> Created class level cache for policies in CFN BaseCloudsplainingIAMCheck

checkov/openapi/checks/resource/v2/Oauth2SecurityRequirement.py, checkov/openapi/checks/resource/v2/SecurityDefinitions.py, checkov/openapi/checks/resource/v2/SecurityRequirement.py, checkov/openapi/checks/resource/v3/BaseOpenapiCheckV3.py, checkov/openapi/checks/resource/v3/CleartextOverUnencryptedChannel.py, docs/6.Contribution/Contribute New OpenAPI Policies.md, tests/openapi/runner/test_runner.py
=> Enforce OpenApi v3 checks to check first the version of the file

checkov/kubernetes/checks/resource/base_container_check.py, tests/kubernetes/checks/example_AllowPrivilegeEscalation/pod-runas1000-malformed-PASSED.yaml, tests/kubernetes/checks/test_AllowProvilegeEscalation.py
=> Handle non-list containers in base_container_check

tests/terraform/module_loading/test_registry.py
=> reset module cache for tests

.cfnlintrc, checkov/cloudformation/checks/resource/aws/LambdaEnvironmentCredentials.py, checkov/cloudformation/checks/resource/aws/SecurityGroupRuleDescription.py, checkov/kubernetes/checks/resource/base_root_container_check.py, checkov/kubernetes/checks/resource/k8s/AllowPrivilegeEscalation.py, checkov/serverless/checks/function/aws/AdminPolicyDocument.py, checkov/terraform/checks/resource/aws/ECSClusterLoggingEncryptedWithCMK.py, tests/cloudformation/checks/resource/aws/example_LambdaEnvironmentCredentials/PASS.yaml, tests/cloudformation/checks/resource/aws/example_SecurityGroupRuleDescription/SecurityGroupRuleDescription-PASSED-4.yaml, tests/cloudformation/checks/resource/aws/test_LambdaEnvironmentCredentials.py, tests/cloudformation/checks/resource/aws/test_SecurityGroupRuleDescription.py, tests/serverless/checks/aws/example_AdminPolicyDocument/AdminPolicyDocument-PASSED/serverless.yml, tests/serverless/checks/aws/test_AdminPolicyDocument.py
=> fix multiple checks edge cases

tests/terraform/module_loading/test_registry.py
=> use different base paths for module loading tests

checkov/cloudformation/checks/resource/aws/IAMRoleAllowAssumeFromAccount.py, checkov/terraform/checks/resource/aws/IAMRoleAllowAssumeFromAccount.py
Change name of policy to match Docs (https://docs.bridgecrew.io/docs/bc_aws_iam_45)
Fixes #3001
=> update title of check to match BC docs

checkov/common/bridgecrew/platform_integration.py, checkov/common/bridgecrew/run_metadata/__init__.py, checkov/common/bridgecrew/run_metadata/abstract_run_metadata_extractor.py, checkov/common/bridgecrew/run_metadata/ci_variables.py, checkov/common/bridgecrew/run_metadata/extractors/__init__.py, checkov/common/bridgecrew/run_metadata/extractors/bitbucket.py, checkov/common/bridgecrew/run_metadata/extractors/github_actions.py, checkov/common/bridgecrew/run_metadata/extractors/gitlab_ci.py, checkov/common/bridgecrew/run_metadata/extractors/jenkins.py, checkov/common/bridgecrew/run_metadata/registry.py, docs/6.Contribution/Implementing CI Metadata Extractor.md
The goal is to automatically extract CI metadata when checkov runs in that context
=> add metadata extractors

checkov/cloudformation/parser/cfn_yaml.py
Check for the OS before parsing a CFN YAML template.
=> Fix windows CFN YAML encoding

checkov/common/runners/object_runner.py, checkov/common/typing.py, checkov/common/util/suppression.py, checkov/yaml_doc/base_registry.py, tests/cloudformation/utils/test_cfn_utils.py, tests/generic_yaml/resources/object/skip/skip.yaml, tests/generic_yaml/test_runner.py
Supporting skipping via comment for all yaml runners
Fixes [# (2986)](https://github.com/bridgecrewio/checkov/issues/2986)
* with this addition yaml runners (Gitlab CI included) will support inline comment skips
=> Support skip comment in yaml runners

checkov/cloudformation/parser/cfn_yaml.py
Catch un-hashable types errors in `cfn_yaml`.
=> Handle un-hashable types in CFN parser

checkov/cloudformation/graph_builder/variable_rendering/renderer.py, tests/cloudformation/runner/resources/skip_sub_dict.json, tests/cloudformation/runner/test_runner.py, tests/cloudformation/test_graph_manager.py
This PR prevents crashing when processing Cloudformation templates with Sub functions containing dicts (currently similar to lists). 
Fixes #3068
=> add exception for dicts when evaluating sub in Cloudformation

checkov/common/models/consts.py, checkov/sca_package/runner.py
Adds all the SCA files to the list that can get uploaded to the platform
=> add SCA files to supported files for upload

checkov/common/checks_infra/solvers/attribute_solvers/any_attribute_solver.py, checkov/openapi/checks/resource/generic/SecurityOperations.py, checkov/openapi/checks/resource/v2/BaseOpenapiCheckV2.py, checkov/openapi/checks/resource/v2/Oauth2SecurityRequirement.py, checkov/openapi/checks/resource/v2/SecurityRequirement.py, checkov/openapi/checks/resource/v3/BaseOpenapiCheckV3.py, checkov/openapi/checks/resource/v3/CleartextOverUnencryptedChannel.py
=> OpenAPI checks type and none values safeguards

checkov/helm/runner.py, checkov/kustomize/runner.py
define find_kustomize_directories and find_chart_directories outside the runners' classes
=> refactor find_chart_directories and find_kustomize_directories

github_action_resources/entrypoint.sh
=> support multiple check flag in gha

README.md
=> docs: correct the homebrew install note

checkov/terraform/checks/resource/azure/NetworkWatcherFlowLogPeriod.py, checkov/terraform/graph_builder/local_graph.py, tests/terraform/checks/resource/azure/test_NetworkWatcherFlowLogPeriod.py
fix edge-case of no `retention_policy` in NetworkWatcherFlowLogPeriod check 
fix terraform graph edge-case of finding an edge for module without a valid source
=> fix in NetworkWatcherFlowLogPeriod check and terraform graph edge-case

checkov/dockerfile/checks/WorkdirIsAbsolute.py, tests/dockerfile/checks/example_WorkdirIsAbsolute/failure/Dockerfile, tests/dockerfile/checks/example_WorkdirIsAbsolute/failure/Dockerfile.simple, tests/dockerfile/checks/test_WorkdirIsAbsolute.py
- instead of reporting just the first incomplaint `WORKDIR` it will gather all and report them
Fixes #2964
=> support multiple error returns in CKV_DOCKER_10

checkov/common/checks_infra/solvers/attribute_solvers/ending_with_attribute_solver.py, checkov/common/checks_infra/solvers/attribute_solvers/starting_with_attribute_solver.py, checkov/common/util/var_utils.py, checkov/terraform/checks/graph_checks/aws/S3BucketEncryption.yaml, checkov/terraform/checks/graph_checks/aws/S3BucketReplicationConfiguration.yaml, checkov/terraform/checks/graph_checks/aws/S3BucketVersioning.yaml, checkov/terraform/checks/graph_checks/aws/S3KMSEncryptedByDefault.yaml, checkov/terraform/checks/graph_checks/aws/S3PublicACLRead.yaml, checkov/terraform/checks/graph_checks/aws/S3PublicACLWrite.yaml, tests/terraform/graph/checks_infra/attribute_solvers/ending_with_solver/UnrenderedVar.yaml, tests/terraform/graph/checks_infra/attribute_solvers/ending_with_solver/test_solver.py, tests/terraform/graph/checks_infra/attribute_solvers/starting_with_solver/UnrenderedVar.yaml, tests/terraform/graph/checks_infra/attribute_solvers/starting_with_solver/test_solver.py
Following PR #3088 I also added the dependent logic to `starting_with` and `endoing_with`, so I could reduce the configuration for the S3 YAML checks
=> add dependent logic to starting/ending with

checkov/common/bridgecrew/vulnerability_scanning/integrations/twistcli.py, tests/common/bridgecrew/vulnerability_scanning/integrations/test_docker_image_scanning.py, tests/common/bridgecrew/vulnerability_scanning/integrations/test_package_scanning.py
=> adding retry when trying to report results to server

checkov/kubernetes/checks/resource/base_container_check.py, tests/kubernetes/checks/example_AllowedCapabilities/cronjob-UNKOWN.yaml
Added support in empty spec in base_container_check
=> Added support in empty spec in base_container_check

checkov/openapi/checks/resource/v2/SecurityRequirement.py, tests/openapi/checks/resource/v2/example_SecurityRequirement/fail3.json, tests/openapi/checks/resource/v2/test_SecurityRequirement.py
Handle malformed security entry in SecurityRequirement OpenAPI check
=> Handle malformed security entry in SecurityRequirement OpenAPI check

Dockerfile, admissioncontroller/Dockerfile, checkov/common/util/tqdm_utils.py, kubernetes/Dockerfile, tests/common/utils/test_tqdm_utils.py
- add an env var to each Dockerfile and disable the progress bar, if set to `True`
=> add RUN_IN_DOCKER env

checkov/terraform/parser.py
Do not to log bad terraform client code as error. log it as warning and continue
=> Add block failed warning

checkov/common/output/baseline.py, tests/common/output/fixtures/main_2.tf, tests/common/output/fixtures/main_copy.tf, tests/common/output/test_baseline.py
The output is now sorted by file path and for each file by resource.
Fixes #3119
=> sort baseline output by file and resource

checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py, docs/3.Custom Policies/Examples.md, tests/terraform/graph/checks_infra/connection_solvers/connection_exist_solver/S3BucketPolicyDataSource.yaml, tests/terraform/graph/checks_infra/connection_solvers/connection_exist_solver/test_solver.py, tests/terraform/graph/resources/s3_bucket_policy/main.tf
I started to create a much bigger solution, but then I realized I can make it work much simpler and almost everything was there, except for the attribute checks 😄 
Fixes #3109
=> support TF data blocks in graph checks

checkov/helm/runner.py
Run helm convert chart to k8s in parallel
=> helm optimization

checkov/arm/base_parameter_check.py, checkov/arm/checks/parameter/SecureStringParameterNoHardcodedValue.py, checkov/arm/runner.py, checkov/bicep/checks/param/azure/SecureStringParameterNoHardcodedValue.py, checkov/bicep/checks/param/base_param_check.py, checkov/bicep/runner.py, checkov/cloudformation/checks/resource/aws/EC2Credentials.py, checkov/cloudformation/checks/resource/aws/LambdaEnvironmentCredentials.py, checkov/cloudformation/runner.py, checkov/common/util/secrets.py, checkov/secrets/runner.py, checkov/serverless/checks/function/aws/AWSCredentials.py, checkov/serverless/runner.py, checkov/terraform/checks/provider/aws/credentials.py, checkov/terraform/checks/provider/bridgecrew/credentials.py, checkov/terraform/checks/provider/linode/credentials.py, checkov/terraform/checks/provider/oci/credentials.py, checkov/terraform/checks/provider/openstack/credentials.py, checkov/terraform/checks/provider/panos/credentials.py, checkov/terraform/checks/resource/aws/EC2Credentials.py, checkov/terraform/checks/resource/aws/LambdaEnvironmentCredentials.py, checkov/terraform/checks/resource/azure/VMCredsInCustomData.py, checkov/terraform/checks/resource/openstack/ComputeInstanceAdminPassword.py, checkov/terraform/runner.py, tests/bicep/checks/param/azure/test_SecureStringParameterNoHardcodedValue.py, tests/secrets/test_runner.py, tests/unit/test_secrets.py
Omitting secret value from secrets scanning report
=> Omitting secret value from report

checkov/sca_package/scanner.py
Fixing progress bar on sca scanner, in case pbar is None, creating a turned off ProgressBar
=> Fixing pbar on sca scanner

checkov/cloudformation/checks/resource/aws/IAMRoleAllowAssumeFromAccount.py, checkov/cloudformation/checks/resource/aws/IAMRoleAllowsPublicAssume.py, checkov/common/checks_infra/solvers/attribute_solvers/regex_match_attribute_solver.py, checkov/openapi/checks/resource/v3/CleartextOverUnencryptedChannel.py, checkov/terraform/checks/resource/azure/NSGRulePortAccessRestricted.py, checkov/terraform/checks/resource/gcp/AbsGoogleComputeFirewallUnrestrictedIngress.py
1) Fix IAMRoleAllowAssumeFromAccount `assume_role_policy_doc` file reference
2) Fix IAMRoleAllowsPublicAssume `assume_role_policy_doc` file reference and str `statement`
3) Fix RegexMatchAttributeSolver invalid regex log
4) Fix CleartextCredsOverUnencryptedChannel empty `path`
5) Fix AbsGoogleComputeFirewallUnrestrictedIngress  `source_ranges_list` empty list 
6) Fix NSGRulePortAccessRestricted `source_address_prefixes` not list
=> Fix checks edge cases

checkov/yaml_doc/base_registry.py, tests/generic_yaml/test_runner.py, tests/gitlab_ci/resources/two/.gitlab-ci.yml, tests/gitlab_ci/test_runner.py
* if I have two violating examples it only reports on the last one
* fix the id of results in yaml runner list objects
=> fix yaml runner id

checkov/bicep/runner.py, checkov/common/output/extra_resource.py, checkov/common/output/report.py, tests/bicep/test_runner.py
- add non checked resources to report for further usage
=> add extra resources to report

Pipfile, Pipfile.lock, setup.py
=> update hcl2 parser

checkov/helm/runner.py
Unhandled parsing failures cause the whole scan to fail, need to ignore failed parsing
https://redlock.atlassian.net/browse/BCE-7210
=> handle helm parsing failures

checkov/terraform/checks/resource/aws/SQSQueueEncryption.py
add ```sqs_managed_sse_enabled``` key to Checkov SQS encryption check validation 
=> add sqs_managed_sse_enabled to check

.github/workflows/pr-test.yml, Pipfile, Pipfile.lock, setup.py
Leverage Pyston-lite to speed up checkov
improving performance by leverage pytston-lite which is a JIT for python 3.8. 
for more about pytson-lite [here](https://blog.pyston.org/)
=> Leverage Pyston-lite 

checkov/openapi/checks/resource/generic/SecurityOperations.py
added type validation for SecurityOperations check to prevent runner failure
=> added type validation

checkov/github_actions/runner.py, integration_tests/prepare_data.sh, integration_tests/run_integration_tests.sh, tests/github_actions/test_runner.py
- nice to have a runner, which actually never scans the files 😉
=> actually enable GitHub Actions runner

Pipfile, Pipfile.lock, setup.py
Fixed pyston-lite package condition, installing on 3.8 python version  and (sys_platform=='linux' or sys_platform=='darwin')
=> Fixed pyston-lite package condition

checkov/terraform/checks/resource/alicloud/AbsSecurityGroupUnrestrictedIngress.py
Catch exception for unexpected input for check AbsSecurityGroupUnrestrictedIngress
=> Handle unexpected input for check AbsSecurityGroupUnrestrictedIngress

checkov/terraform/checks/resource/azure/NSGRulePortAccessRestricted.py
handled unexpected input for check NSGRulePortAccessRestricted
=> Fix unexpected input for check nsg rule port access restricted

checkov/helm/runner.py
=> add log for helm errors in helm runner

checkov/arm/runner.py, checkov/cloudformation/runner.py, checkov/common/output/csv.py, checkov/common/runners/runner_registry.py, checkov/terraform/runner.py, tests/common/runner_registry/test_runner_registry.py
add extra_resources to arm, cloudformation and terraform #3161
=> add extra_resources to arm, cloudformation and terraform and csv file output

checkov/terraform/checks/resource/alicloud/K8sNodePoolAutoRepair.py, tests/terraform/checks/resource/alicloud/example_K8sNodePoolAutoRepair/main.tf, tests/terraform/checks/resource/alicloud/test_K8sNodePoolAutoRepair.py
Ensure that nodepools are set to auto repair (true) - defaults to false
=> alicloud ensure nodepools are set to auto repair

checkov/terraform/checks/resource/alicloud/ALBACLIsUnrestricted.py, tests/terraform/checks/resource/alicloud/example_ALBACLIsUnrestricted/main.tf, tests/terraform/checks/resource/alicloud/test_ALBACLIsUnrestricted.py
ACL can define 0.0.0.0/0 so heres a check for that, effectively make the acl pointless
=> ALIcloud ACL should not allow 0.0.0.0/0

checkov/terraform/checks/resource/alicloud/KMSKeyIsEnabled.py, checkov/terraform/checks/resource/alicloud/KMSKeyRotationIsEnabled.py, tests/terraform/checks/resource/alicloud/example_KMSKeyIsEnabled/main.tf, tests/terraform/checks/resource/alicloud/example_KMSKeyRotationIsEnabled/main.tf, tests/terraform/checks/resource/alicloud/test_KMSKeyIsEnabled.py, tests/terraform/checks/resource/alicloud/test_KMSKeyRotationIsEnabled.py
A check for KMS keys status - is enabled
and
A check to ensure kms rotation is enabled
=> ALICloud: Check KMS enabled and rotated

Manifest.in, setup.py
=> add cfn graph check folder to package

.github/workflows/build.yml, Dockerfile, Dockerfile.pyston, admissioncontroller/Dockerfile, kubernetes/Dockerfile
- Changed base image of all Dockerfiles to 3.8-slim
- Created a new Docker image, which is based on the official Pyston image and it will be pushed to `bridgecrew/checkov:pyston` and also `bridgecrew/checkov:[checkov version]-pyston`
=> Create pyston container

checkov/bitbucket/dal.py, checkov/common/vcs/base_vcs_dal.py, checkov/github/base_github_branch_security.py, checkov/github/dal.py, checkov/github/schemas/no_branch_protection.py, checkov/gitlab/dal.py, tests/github/resources/github_conf/repo_no_rules/branch_protection_rules.json, tests/github/test_runner.py
Enable github configuration rules on non "github enterprise organization". 
AKA enable verifying branch protection rules on individual accounts. 
Fixes # BCD-239
=> Make branch protection check work on non enterprise

checkov/terraform/checks/resource/alicloud/LaunchTemplateDisksAreEncrypted.py, tests/terraform/checks/resource/alicloud/example_LaunchTemplateDisksAreEncrypted/main.tf, tests/terraform/checks/resource/alicloud/test_LaunchTemplateDiskAreEncrypted.py
*check ensures that only encrypted data disk are used.
=> Alicloud launch template: data disks are encrypted right?

checkov/terraform/checks/resource/aws/APIGatewayAuthorization.py
Check if `http_method` exists before accessing it
=> API Gateway authorization check fix

checkov/terraform/checks/resource/aws/LBTargetGroupsDefinesHealthcheck.py, tests/terraform/checks/resource/aws/example_LBTargetGroupDefinesHealthcheck/main.tf, tests/terraform/checks/resource/aws/test_LBTargetGroupDefinesHealthCheck.py
Ensure LB target group defines a healthcheck (for http and https)
=> AWS:define healthcheck for target group

checkov/terraform/checks/resource/alicloud/RDSInstanceAutoUpgrade.py, tests/terraform/checks/resource/alicloud/example_RDSInstanceAutoUpgrade/main.tf, tests/terraform/checks/resource/alicloud/test_RDSInstanceAutoUpgrade.py
Check that we opts into the minor db updates
=> ALicloud rds allow minor updates

checkov/common/output/cyclonedx.py, checkov/common/runners/runner_registry.py, docs/8.Outputs/CycloneDX BOM.md, integration_tests/test_checkov_cyclonedx_report.py, tests/common/output/test_cyclonedx_report.py
- updated the CycloneDX output
- the components are created on our own and use as type `application`
=> Update cyclone output

checkov/common/bridgecrew/wrapper.py
added GHA metadata to check_metadata_keys
=> Expose GHA metadata 

checkov/terraform/checks/resource/aws/LBTargetGroupsDefinesHealthcheck.py, tests/terraform/checks/resource/aws/example_LBTargetGroupDefinesHealthcheck/main.tf, tests/terraform/checks/resource/aws/test_LBTargetGroupDefinesHealthCheck.py
fix edge case in LBTargetGroupDefinesHealthCheck
=> fix edge case in LBTargetGroupDefinesHealthCheck

checkov/kustomize/runner.py
in case of a file that isn't in kustomizeFileMappings log a warning and continue the loop to avoid exception
=> fix edge-case in kustomize runner

checkov/common/output/cyclonedx.py, checkov/common/output/extra_resource.py, checkov/common/runners/runner_registry.py, checkov/sca_image/runner.py, checkov/sca_package/runner.py, docs/8.Outputs/CycloneDX BOM.md, tests/common/output/test_cyclonedx_report.py
- added support for extra resources/packages for SCA package reports
- added support for SCA package components and CVE vulnerabilities in CycloneDX output
=> support SCA packages in CycloneDX output

Pipfile, Pipfile.lock, checkov/common/bridgecrew/bc_source.py, checkov/common/bridgecrew/platform_integration.py, checkov/common/bridgecrew/run_metadata/abstract_run_metadata_extractor.py, checkov/common/bridgecrew/run_metadata/extractors/bitbucket.py, checkov/common/bridgecrew/run_metadata/extractors/default_extractor.py, checkov/common/bridgecrew/run_metadata/extractors/github_actions.py, checkov/common/bridgecrew/run_metadata/extractors/gitlab_ci.py, checkov/common/bridgecrew/run_metadata/extractors/jenkins.py, checkov/common/bridgecrew/run_metadata/registry.py, checkov/common/bridgecrew/severities.py, checkov/common/bridgecrew/vulnerability_scanning/image_scanner.py, checkov/common/bridgecrew/vulnerability_scanning/integrations/docker_image_scanning.py, checkov/common/bridgecrew/vulnerability_scanning/integrations/package_scanning.py, checkov/common/bridgecrew/vulnerability_scanning/integrations/twistcli.py, checkov/common/bridgecrew/wrapper.py, checkov/common/multi_signature.py, checkov/common/parallelizer/parallel_runner.py, checkov/common/parsers/json/decoder.py, checkov/common/typing.py, checkov/common/util/http_utils.py, checkov/common/util/tqdm_utils.py, flake8_plugins/flake8_class_attributes_plugin/flake8_class_attributes/class_members_errors.py, flake8_plugins/flake8_class_attributes_plugin/tests/test_files/typing_class_skip.py, flake8_plugins/flake8_class_attributes_plugin/tests/test_handler.py, mypy.ini
- added types to anything under `common.bridgecrew` except `integration_features` to not make the PR to big
- fix couple of flake8 issues under `common.bridgecrew`
- adjust our flake8 plugin to skip typing classes
=> improve typing under common.bridgecrew

checkov/github_actions/checks/job/CosignArtifacts.py, checkov/github_actions/checks/job/CosignSBOM.py, tests/github_actions/resources/.github/workflows/docker-slsa.yaml, tests/github_actions/resources/.github/workflows/slsa-gen.yaml
Addition to the github_actions runner to look for use of cosign to determine SLSA compliance
None
Use of cosign sign for generated artifacts
Use of cosign attest or cosign sign --sbom
Github workflows without any sign of cosign use.  
Ideal use case would be to place production build workflows into a SLSA folder
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [  ] I have made corresponding changes to the documentation
=> first commit for SLSA checks

checkov/terraform/checks/resource/aws/CodecommitApprovalsRulesRequireMin2.py, checkov/terraform/checks/resource/azure/AKSDashboardDisabled.py, checkov/terraform/checks/resource/azure/AKSUsesAzurePoliciesAddon.py, checkov/terraform/checks/resource/kubernetes/CPULimits.py, checkov/terraform/checks/resource/kubernetes/CPURequests.py, checkov/terraform/checks/resource/kubernetes/MemoryLimits.py, checkov/terraform/checks/resource/kubernetes/MemoryRequests.py, checkov/terraform/checks/resource/kubernetes/Tiller.py, checkov/terraform/graph_builder/local_graph.py, tests/terraform/checks/resource/kubernetes/example_CPURequests/main2.tf, tests/terraform/checks/resource/kubernetes/example_MemoryLimits/main2.tf, tests/terraform/checks/resource/kubernetes/example_MemoryRequests/main2.tf, tests/terraform/checks/resource/kubernetes/test_CPURequests.py, tests/terraform/checks/resource/kubernetes/test_MemoryLimits.py, tests/terraform/checks/resource/kubernetes/test_MemoryRequests.py
Several minor type validations to prevent scans from failing on unexpected data
=> Fix failing checks for Azure, K8s, and TF local graph

checkov/terraform/plan_parser.py, checkov/terraform/plan_utils.py, docs/3.Custom Policies/Examples.md, docs/3.Custom Policies/YAML Custom Policies.md, docs/7.Scan Examples/Terraform Plan Scanning.md, tests/terraform/runner/extra_tf_plan_checks/secret_not_deleted.py, tests/terraform/runner/extra_tf_plan_checks/secret_not_deleted.yaml, tests/terraform/runner/resources/plan_with_deleted_resources/tfplan.json, tests/terraform/runner/test_plan_runner.py
- added the change actions value to the resource block of a Terraform plan resource
- added a Python and YAML check example in the docs and as a test
Fixes #3148
=> add possibility to check for Terraform plan change actions

.github/workflows/build.yml, .github/workflows/pr-test.yml
it looks like the maintainers of the GitHub Action could fix the bug, after I enabled debug logging and gave them more info on what actually was failing, they pinpointed the problem and rolled out a new version. Let's hope for the best 🤞 I also changed it use the commit hash, which is in general the recommend way of using GitHub Actions and will step by step roll it out to the the other actions too 🐄 🐄
=> upgrade helm setup action to v3 and use commit hash

checkov/common/output/cyclonedx.py
In case the URL of a vulnerability was missing, checkov crashed. Now we are just not creating the VulnerabilitySource object in case it doesn't exist
=> Fix CycloneDX output for SCA Packages

checkov/terraform/module_loading/module_finder.py
add optional modules_to_load parameter in load_tf_modules function
=> add optional modules_to_load parameter in load_tf_modules function

README.md
=> Minor sentence improvements to README.md

checkov/terraform/checks/resource/aws/GlacierVaultAnyPrincipal.py, tests/terraform/checks/resource/aws/example_GlacierVaultAnyPrincipal/main.tf
Fix bug with invalid glacier json file
=> try load glacier json

checkov/common/runners/runner_registry.py, tests/common/output/test_bom_report.py
Return a dict with iac bom reports to caller
=> Return-BOM-iac-result-files

checkov/common/output/csv.py, tests/common/output/test_bom_report.py, tests/common/runner_registry/test_runner_registry.py
=> licenses added to csv report 

checkov/cloudformation/checks/resource/aws/ECRPolicy.py, checkov/terraform/checks/resource/aws/ECRPolicy.py, tests/cloudformation/checks/resource/aws/example_ECRPolicy/ECRPolicy-FAILED.yaml, tests/cloudformation/checks/resource/aws/example_ECRPolicy/ECRPolicy-PASSED-2.yaml, tests/cloudformation/checks/resource/aws/example_ECRPolicy/ECRPolicy-PASSED.yaml, tests/cloudformation/checks/resource/aws/test_ECRPolicy.py, tests/terraform/checks/resource/aws/example_ECRPolicy/main.tf, tests/terraform/checks/resource/aws/test_ECRPolicy.py
- Added more condition keys, which can be used in combination with `aws:PrincipalOrgID`
=> add more condition keys to CKV_AWS_32

checkov/common/output/csv.py, checkov/common/output/cyclonedx.py, checkov/common/output/record.py, checkov/common/output/report.py, checkov/sca_package/output.py, checkov/sca_package/runner.py, tests/sca_package/conftest.py, tests/sca_package/test_output.py, tests/sca_package/test_runner.py
I sill have to handle to "to-do"s i added, will be after discussion with product
* adding licenses-statuses-records to the report
* skipping licenses-statuses-records when creating the next outputs: junit_xml-report, sarif-json-report, cvs-report, cyclondx-report, cli-output
* adjust the UTs
=> add licenses-records to report

checkov/common/output/cyclonedx.py, tests/common/output/test_cyclonedx_report.py
import issue fixed on cyclonedx and sca packages tests added 
=> fix import issue and tests added - cyclonedx - sca packages

checkov/terraform/checks/graph_checks/gcp/GCPAuditLogsConfiguredForAllServicesAndUsers.yaml, tests/terraform/graph/checks/resources/GCPAuditLogsConfiguredForAllServicesAndUsers/expected.yaml, tests/terraform/graph/checks/resources/GCPAuditLogsConfiguredForAllServicesAndUsers/main.tf
=> CKV2_GCP_5 fails in a plan scan but passes in the directory scan

checkov/common/output/common.py, checkov/common/output/cyclonedx.py, checkov/common/output/cyclonedx_consts.py, checkov/common/util/json_utils.py, checkov/sca_image/runner.py, checkov/sca_package/output.py, checkov/sca_package/runner.py, tests/common/output/test_cyclonedx_report.py
- fixed the integration tests, due to a JSOn encoding error
- had to move `ImageDetails` to more centralized place
- [] I have made corresponding changes to the documentation
=> transform ImageDetails to a dict when outputting to json

checkov/terraform/checks/resource/azure/SpringCloudAPIPortalHTTPSOnly.py, checkov/terraform/checks/resource/azure/SpringCloudAPIPortalPublicAccessIsDisabled.py, tests/terraform/checks/resource/azure/example_SpringCloudAPIPortalHTTPSOnly/main.tf, tests/terraform/checks/resource/azure/example_SpringCloudAPIPortalPublicAccessIsDisabled/main.tf, tests/terraform/checks/resource/azure/test_SpringCloudAPIPortalHTTPSOnly.py, tests/terraform/checks/resource/azure/test_SpringCloudAPIPortalPublicAccessIsDisabled.py
2 new checks for azurerm_spring_cloud_api_portal.
- ensure that its not public
- ensure that it uses only https
=> Azure:azurerm_spring_cloud_api_portal checks for HTTPs and public access

checkov/terraform/checks/graph_checks/aws/SGAttachedToResource.yaml, tests/terraform/graph/checks/resources/SGAttachedToResource/expected.yaml, tests/terraform/graph/checks/resources/SGAttachedToResource/main.tf
Fix for CKV2_AWS_5 check so that it will support SG attached to an `aws_memorydb_cluster` resource 
Fixes  https://github.com/bridgecrewio/checkov/issues/3305
=> fix CKV2_AWS_5: support memorydb_cluster resource

checkov/sca_package/output.py, tests/sca_package/test_output.py
splitting for each package with lines
=> splitting for each package with lines 

checkov/terraform/checks/resource/aws/SQSQueuePolicyAnyPrincipal.py, tests/terraform/checks/resource/aws/example_SQSQueuePolicyAnyPrincipal/main.tf
Catch exception when trying to evaluate policies.
`terraform/CKV_AWS_168`
=> Handle unexpected policy value in SQSQueuePolicyAnyPrincipal

checkov/terraform/plan_parser.py, tests/terraform/runner/resources/plan_nested_child_modules_with_connections/tfplan.json, tests/terraform/runner/test_plan_runner.py
- added the evaluation for connections coming from inside modules for Terraform plans
Fixes #2391
Fixes #3278
Fixes #3277
=> add missing resource connections inside modules for terraform plans

checkov/github_actions/checks/job/CosignArtifacts.py, checkov/github_actions/checks/job/CosignSBOM.py, checkov/yaml_doc/base_registry.py, tests/github_actions/resources/.github/workflows/empty_jobs.yaml, tests/github_actions/test_runner.py
fix gha checks because of empty jobs block
added UT
=> Fix GHA checks

checkov/common/runners/object_runner.py, checkov/github_actions/checks/job/AllowUnsecureCommandsOnJob.py, checkov/github_actions/checks/job/CosignArtifacts.py, checkov/github_actions/checks/job/CosignSBOM.py, checkov/github_actions/checks/job/EmptyWorkflowDispatch.py, checkov/github_actions/checks/job/ReverseShellNetcat.py, checkov/github_actions/checks/job/ShellInjection.py, checkov/github_actions/checks/job/SuspectCurlInScript.py, checkov/yaml_doc/runner.py, tests/github_actions/resources/.github/workflows/different_jobs_format.yaml, tests/github_actions/test_runner.py
Fix GHA checks to skip non-dict configurations.
See added resource as an example - [ 'ubuntu-latest' ] was given as a job.
=> Fix GHA checks to skip non-dict configurations

checkov/sca_package/scanner.py
Fixes
- SCA fails on scan result
=> fix(SCA): change result parsing

checkov/sca_package/scanner.py
We are checking for the existence of an attribute which doesn't always exist.
=> Safely check packages attribute

checkov/arm/checks/resource/StorageAccountAzureServicesAccessEnabled.py, tests/arm/checks/resource/example_StorageAccountAzureServicesAccessEnabled/storageAccountAzureServicesAccessEnabled-UNKNOWN.json
Add a condition to ensure the resource is valid.
=> Fix for azure StorageAccountAzureServicesAccessEnabled check

checkov/common/output/csv.py, checkov/common/util/http_utils.py, checkov/sca_image/runner.py, tests/common/output/test_bom_report.py, tests/sca_image/test_runner.py
* printing unknown in bom-report for unknown licenses (rather than empty string)
=> printing unknown in bom-report for unknown licenses (rather than empty string)

checkov/common/bridgecrew/vulnerability_scanning/integrations/docker_image_scanning.py, checkov/common/bridgecrew/vulnerability_scanning/integrations/twistcli.py, checkov/common/bridgecrew/vulnerability_scanning/report.py, checkov/common/output/report.py, checkov/common/sca/commons.py, checkov/common/sca/output.py, checkov/sca_image/runner.py, checkov/sca_package/output.py, checkov/sca_package/runner.py, tests/common/output/test_cyclonedx_report.py, tests/sca_package/test_output.py
- splitted my previous PR #3332 to just include the existing code moving to make reviewing easier and allowing others to work on the new code place
=> move common sca code to the common folder

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yaml, .github/workflows/pipenv-update.yml, .github/workflows/pr-test.yml, checkov/terraform/checks/resource/kubernetes/AllowPrivilegeEscalation.py, tests/cloudformation/checks/resource/aws/example_RDSMultiAZEnabled/RDSMultiAZEnabled-FAILED-2.yaml, tests/cloudformation/checks/resource/aws/example_RDSMultiAZEnabled/RDSMultiAZEnabled-FAILED.yaml, tests/cloudformation/checks/resource/aws/example_RDSMultiAZEnabled/RDSMultiAZEnabled-PASSED.yaml
Add a condition to skip invalid resources.
=> Fix in AllowPrivilegeEscalation check

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yaml, .github/workflows/pipenv-update.yml, .github/workflows/pr-test.yml
* pinning pipenv version for avoiding 2 bads version
=> pinning pipenv version for avoiding 2 bads version

checkov/common/util/http_utils.py
when we report back to platform we don't have informative error log to understand why it happen. also when we try to understand via the logs of the GW, we can't find it because we have too much similar error.
this PR should give us more informative logs when the request fail, and also provide us identity of the request.
=> Add logs for http errors

checkov/arm/checks/resource/StorageAccountDefaultNetworkAccessDeny.py, tests/arm/checks/resource/example_StorageAccountDefaultNetworkAccessDeny/storageAccountDefaultNetworkAccessDeny-UNKNOWN.json
Added a validation to ensure the resource is valid
=> Fix in StorageAccountDefaultNetworkAccessDeny check

checkov/common/output/cyclonedx.py, tests/common/output/test_cyclonedx_report.py
fix error on packages without "_" in its name
=> Bug fix package_name

.swm/creating-a-solver.gm0ti.sw.md, .swm/swimm.json
:link: Link to Swimm doc: [Creating a Solver](https://app.swimm.io/workspaces/POQrB5YpB8pIaYm7bqiH/repos/Z2l0aHViJTNBJTNBY2hlY2tvdiUzQSUzQWJyaWRnZWNyZXdpbw==/branch/creating-a-solver-swimm-doc-k2bkk/docs/gm0ti).
---
Have any questions? Check out [Swimm docs](https://docs.swimm.io/) and [join our Slack Community](https://swimm.io/slack).
=> Creating a Solver

checkov/kubernetes/checks/resource/k8s/DockerSocketVolume.py, tests/kubernetes/checks/example_DockerSocketVolume/CronJob-pass.yaml, tests/kubernetes/checks/test_DockerSocketVolume.py
handle edge case of null spec in jobTemplate
=> fix in DockerSocketVolume check

Dockerfile
=> Add `openssh-client` to the container image

.github/PULL_REQUEST_TEMPLATE.md, .github/pr-title-checker-config.json, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yaml, .github/workflows/nightly.yml, .github/workflows/pipenv-update.yml, .github/workflows/pr-test.yml, .github/workflows/pr-title.yaml, .github/workflows/security.yaml
- added a nightly job to automatically create a release and update the `CHANGELOG.md`
- added a PR title checker + additional info about it to the PR template
- reduced permissions of most of the GHA workflows
- changed tag usage to commit hashes for most of the GHA
=> feat(general): Add automatic changelog creation

checkov/common/output/csv.py, tests/common/output/test_bom_report.py
[//]: # "
ex.
"
*Please include a summary of the …
=> fix(sca): Remove commas between licenses in CSV reports

.github/PULL_REQUEST_TEMPLATE.md, .github/pr-title-checker-config.json, .github/workflows/nightly.yml, .github/workflows/pr-title.yaml
[//]: # "
ex.
"
- set the wrong branch name for the …
=> chore: change PR title branch to master

checkov/terraform/checks/resource/azure/AppGatewayWAFACLCVE202144228.py, tests/terraform/checks/resource/azure/example_AppGatewayWAFACLCVE202144228/main.tf
[//]: # "
ex.
"
- looks like `rule_override` in a TF …
=> fix(terraform): adjust CKV_AZURE_135 to work with TF plan

checkov/terraform/checks/resource/aws/BatchJobIsNotPrivileged.py, tests/terraform/checks/resource/aws/example_BatchJobIsNotPrivileged/main.tf, tests/terraform/checks/resource/aws/test_BatchJobIsNotPrivileged.py
[//]: # "
ex.
"
- I made the check more resilient to …
=> fix(terraform): adjust CKV_AWS_210 to work in terraform plans

checkov/common/output/cyclonedx.py, tests/common/output/test_cyclonedx_report.py
[//]: # "
ex.
"
- Added the licenses to the actual …
=> fix(sca): add missing licenses to cyclonedx components

checkov/common/output/csv.py, tests/common/output/test_bom_report.py
=> fix(sca): CSV reports with packages name with commas 

checkov/helm/runner.py, checkov/kustomize/runner.py, checkov/runner_filter.py
Reverts bridgecrewio/checkov#3390
=> chore: Revert "chore: Helm and Kustomize refactor"

checkov/common/runners/object_runner.py, checkov/github_actions/checks/job/CosignArtifacts.py, checkov/github_actions/checks/job/CosignSBOM.py, checkov/github_actions/runner.py, checkov/github_actions/schema_validator.py, tests/github_actions/resources/.github/workflows/include_none_steps.yml, tests/github_actions/test_runner.py
=> fix: Fixing GHA edge cases 

checkov/common/bridgecrew/platform_integration.py, checkov/common/bridgecrew/wrapper.py, checkov/common/multi_signature.py, checkov/common/output/report.py
=> platform(general): Improve scan persist

checkov/terraform/checks/resource/kubernetes/CPULimits.py, tests/terraform/checks/resource/kubernetes/example_CPULimits/main.tf, tests/terraform/checks/resource/kubernetes/test_CPULimits.py
fix in CPULimits check - catch the edge case of resources without containers
=> fix: fix in CPULimits check

checkov/terraform/graph_builder/utils.py, checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py, checkov/terraform/graph_builder/variable_rendering/renderer.py
change skip rendering log to debug
=> fix: change skip rendering log to debug

checkov/main.py
No integration works with image runner because post-runners works only on the runner registry, and the image runner is not part of it
[//]: # "
Additionally we encourage adding a …
=> feat(sca): Add Integrations' post-runner for image scan runner

checkov/common/bridgecrew/integration_features/features/suppressions_integration.py, tests/common/integration_features/test_suppressions_integration.py
=> platform(sca): CvesAccounts suppressions for packages and images

checkov/terraform/checks/resource/kubernetes/CPURequests.py, checkov/terraform/checks/resource/kubernetes/HostPort.py, checkov/terraform/checks/resource/kubernetes/ImageDigest.py, checkov/terraform/checks/resource/kubernetes/ImagePullPolicyAlways.py, checkov/terraform/checks/resource/kubernetes/LivenessProbe.py, checkov/terraform/checks/resource/kubernetes/MemoryLimits.py, checkov/terraform/checks/resource/kubernetes/MemoryRequests.py, checkov/terraform/checks/resource/kubernetes/ReadinessProbe.py, tests/terraform/checks/resource/kubernetes/example_CPURequests/main3.tf, tests/terraform/checks/resource/kubernetes/example_HostPort/main3.tf, tests/terraform/checks/resource/kubernetes/example_ImageDigest/main3.tf, tests/terraform/checks/resource/kubernetes/example_ImagePullPolicyAlways/main3.tf, tests/terraform/checks/resource/kubernetes/example_LivenessProbe/main3.tf, tests/terraform/checks/resource/kubernetes/example_MemoryLimits/main3.tf, tests/terraform/checks/resource/kubernetes/example_MemoryRequests/main3.tf, tests/terraform/checks/resource/kubernetes/example_ReadinessProbe/main3.tf
=> fix(terraform): fix tf k8s pods resources with no containers

checkov/sca_image/runner.py
=> fix(sca): Update image referencer file content

checkov/github/checks/webhooks_https_orgs.py, checkov/github/checks/webhooks_https_repos.py, tests/github/test_runner.py
=> break(github): Split CKV_GITHUB_7

.github/workflows/build.yml, .github/workflows/pr-test.yml, Pipfile, Pipfile.lock, checkov/sca_package/output.py, checkov/terraform/checks/resource/kubernetes/HostPort.py, checkov/terraform/checks/resource/kubernetes/MemoryRequests.py, setup.py
=> chore: update dependencies

checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py
=> fix(graph): cache jsonpath attributes parser results

README.md
=> docs: Update README with more examples

checkov/terraform/checks/resource/github/BranchProtectionRequireSignedCommits.py, checkov/terraform/checks/resource/github/BranchProtectionReviewNumTwo.py, checkov/terraform/checks/resource/github/PrivateRepo.py, checkov/terraform/checks/resource/github/SecretsEncrypted.py, checkov/terraform/checks/resource/github/WebhookInsecureSsl.py, checkov/terraform/checks/resource/gitlab/ForcePushDisabled.py, checkov/terraform/checks/resource/gitlab/PreventSecretsEnabled.py, checkov/terraform/checks/resource/gitlab/RejectUnsignedCommits.py, checkov/terraform/checks/resource/gitlab/RequireTwoApprovalsToMerge.py
=> fix: Add VCS to check title

tests/sca_image/test_output_reports.py, tests/sca_package/test_output_reports.py
=> chore: commenting out bad tests

checkov/common/output/report.py
=> chore: Improve performance of dedupe records in report

.flake8, checkov/helm/runner.py, checkov/kubernetes/parser/k8_json.py, checkov/kubernetes/parser/k8_yaml.py, checkov/terraform/checks/resource/aws/AbsSecurityGroupUnrestrictedIngress.py, checkov/terraform/checks/resource/aws/ComprehendEntityRecognizerVolumeUsesCMK.py, checkov/terraform/checks/resource/aws/ConnectInstanceS3StorageConfigUsesCMK.py, checkov/terraform/checks/resource/aws/DBInstanceBackupRetentionPeriod.py, checkov/terraform/checks/resource/aws/IAMAdminPolicyDocument.py, checkov/terraform/checks/resource/aws/IAMStarActionPolicyDocument.py, checkov/terraform/checks/resource/aws/LBTargetGroupsDefinesHealthcheck.py, checkov/terraform/checks/resource/aws/LambdaEnvironmentEncryptionSettings.py, checkov/terraform/checks/resource/aws/MQBrokerAuditLogging.py, checkov/terraform/checks/resource/azure/ACRAdminAccountDisabled.py, checkov/terraform/checks/resource/azure/ACRPublicNetworkAccessDisabled.py, checkov/terraform/checks/resource/oci/AbsSecurityGroupUnrestrictedIngress.py, checkov/terraform/checks/resource/oci/FileSystemEncryption.py, checkov/terraform/checks/resource/oci/ObjectStorageEncryption.py, checkov/terraform/checks/resource/oci/ObjectStoragePublic.py, checkov/terraform/checks/resource/yandexcloud/IAMCloudElevatedMembers.py, checkov/terraform/checks/resource/yandexcloud/IAMFolderElevatedMembers.py, checkov/terraform/checks/resource/yandexcloud/IAMOrganizationElevatedMembers.py, checkov/terraform/checks/resource/yandexcloud/K8SEtcdKMSEncryption.py, checkov/terraform/graph_builder/utils.py, checkov/terraform/graph_builder/variable_rendering/safe_eval_functions.py
=> chore: enable flake8 for helm and finish terraform

checkov/cloudformation/parser/__init__.py
=> fix(cloudformation): fix bug in cfn parser

.github/PULL_REQUEST_TEMPLATE.md, .github/pr-title-checker-config.json, .github/workflows/nightly.yml
=> chore: Fix nightly workflow

.github/release-changelog-config.json, .github/workflows/build.yml, .github/workflows/nightly.yml, CHANGELOG.md
=> chore: adjust changelog creation

checkov/helm/runner.py
=> fix(helm): add try catch to helm cmd run

checkov/cloudformation/image_referencer/base_provider.py, checkov/cloudformation/image_referencer/manager.py, checkov/cloudformation/image_referencer/provider/aws.py, checkov/cloudformation/runner.py, checkov/terraform/runner.py, tests/cloudformation/image_referencer/conftest.py, tests/cloudformation/image_referencer/provider/test_aws.py, tests/cloudformation/image_referencer/resources/aws/apprunner.yaml, tests/cloudformation/image_referencer/resources/aws/batch.yaml, tests/cloudformation/image_referencer/resources/aws/codebuild.yaml, tests/cloudformation/image_referencer/resources/aws/ecs.yaml, tests/cloudformation/image_referencer/resources/aws/lightsail.yaml, tests/cloudformation/image_referencer/test_manager.py, tests/cloudformation/image_referencer/test_runner_aws_resources.py
=> feat(sca): add Image Referencer for CloudFormation

tests/common/output/test_sarif_report.py
=> chore: fix sarif test

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yaml, .github/workflows/pipenv-update.yml, .github/workflows/pr-test.yml, .pre-commit-config.yaml, Pipfile, Pipfile.lock, setup.py
=> chore: Upgrade deps

Manifest.in
=> fix(github): add missing schema files to distribution package

checkov/terraform/checks/resource/gcp/CloudFunctionsShouldNotBePublic.py, tests/terraform/checks/resource/gcp/example_CloudFunctionsShouldNotBePublic/main.tf, tests/terraform/checks/resource/gcp/test_CloudFunctionsShouldNotbePublic.py
Since any cloud function now needs to define access, then ensure that that access is not global -set to allUsers
[//]: # "
Additionally we encourage adding a scope to the prefix, …
=> feat(terraform): GCP Cloud functions should not be public

checkov/kubernetes/runner.py
=> fix(helm): fix helm signal abort handler

checkov/cloudformation/checks/resource/aws/MQBrokerAuditLogging.py, tests/cloudformation/checks/resource/aws/example_MQBrokerAuditLogging/FAIL.yaml, tests/cloudformation/checks/resource/aws/example_MQBrokerAuditLogging/PASS.yaml, tests/cloudformation/checks/resource/aws/example_MQBrokerAuditLogging/UNKNOWN.yaml, tests/cloudformation/checks/resource/aws/test_MQBrokerAuditLogging.py
=> feat(cloudformation): add CKV_AWS_197 for CFN

checkov/kubernetes/graph_builder/graph_components/blocks.py, checkov/kubernetes/graph_builder/local_graph.py, checkov/kubernetes/kubernetes_utils.py, tests/kubernetes/graph/resources/nested_resource.yaml, tests/kubernetes/graph/test_local_graph.py
=> feat(kubernetes): create complex k8s vertices

docs/3.Custom Policies/Python Custom Policies.md
Fix TOC rendering issue on checkov.io
Rendering doesn't like 4 layers of markdown titles on our current stylesheets
=> docs(general): Fix TOC rendering issue on checkov.io

checkov/terraform/checks/graph_checks/aws/Route53ZoneEnableDNSSECSigning.yaml, checkov/terraform/checks/graph_checks/aws/Route53ZoneHasMatchingQueryLog.yaml, checkov/terraform/plan_parser.py, tests/terraform/runner/resources/plan_root_module_resources_no_values/tfplan_route53.json, tests/terraform/runner/test_plan_runner.py
=> feat(terraform): allow resources without values in TF plan

checkov/bitbucket/base_bitbucket_configuration_check.py, checkov/bitbucket/checks/merge_requests_approvals.py, checkov/bitbucket/dal.py, checkov/bitbucket/runner.py, checkov/bitbucket/schemas/branch_restrictions.py, checkov/common/runners/base_runner.py, checkov/common/runners/object_runner.py, checkov/common/runners/runner_registry.py, checkov/common/version_manager.py, checkov/github/runner.py, checkov/github_actions/checks/base_github_action_check.py, checkov/github_actions/checks/job/AllowUnsecureCommandsOnJob.py, checkov/github_actions/checks/job/CosignArtifacts.py, checkov/github_actions/checks/job/CosignSBOM.py, checkov/github_actions/checks/job/EmptyWorkflowDispatch.py, checkov/github_actions/checks/job/ReverseShellNetcat.py, checkov/github_actions/checks/job/ShellInjection.py, checkov/github_actions/checks/job/SuspectCurlInScript.py, checkov/github_actions/runner.py, checkov/gitlab/runner.py, checkov/gitlab_ci/checks/base_gitlab_ci_check.py, checkov/gitlab_ci/checks/job/AvoidDoublePipelines.py, checkov/gitlab_ci/checks/job/SuspectCurlInScript.py, checkov/gitlab_ci/runner.py, checkov/main.py, mypy.ini
=> chore: Enable mypy GHA, GitLab CI and Bitbucket

checkov/kubernetes/graph_builder/graph_components/ResourceKeywordIdentifier.py
Added a class with k8s mapping between resources and their connecting attributes
=> feat(kubernetes): added resources mappings for roles objects

checkov/common/output/cyclonedx.py, tests/sca_image/outputs/results_cyclonedx.xml
=> fix(sca): fix CycloneDX output for Docker images

checkov/openapi/checks/resource/v2/PathSchemeDefineHTTP.py
=> fix(openapi): fix openapi schema bug

checkov/secrets/runner.py
=> fix(secrets): Skip secrets from files encoded with special codecs

checkov/dockerfile/runner.py, checkov/serverless/runner.py, tests/dockerfile/test_runner.py
Added extra resources for serverless and dockerfile for BOM report (will insert resources without violations to the report)
=> feat(serverless): added extra resources for serverless and dockerfile

checkov/cloudformation/checks/resource/aws/LaunchConfigurationEBSEncryption.py, tests/cloudformation/checks/resource/aws/example_LaunchConfigurationEBSEncryption/LaunchConfigurationEBSEncryption-UNKNOWN_2.yml
=> fix(cloudformation): fix lc ebs encryption

checkov/terraform/checks/resource/aws/AbsNACLUnrestrictedIngress.py, tests/terraform/checks/resource/aws/example_NetworkACLUnrestrictedIngress22/main.tf, tests/terraform/checks/resource/aws/test_NetworkACLUnrestrictedIngress22.py
=> fix(terraform): fix port is bool ingress rule

checkov/terraform/checks/resource/gcp/CloudFunctionsShouldNotBePublic.py, tests/terraform/checks/resource/gcp/example_CloudFunctionsShouldNotBePublic/main.tf, tests/terraform/checks/resource/gcp/test_CloudFunctionsShouldNotbePublic.py
Extend `CKV_GCP_107` for `google_cloudfunctions2_function_iam` resource. Same code with more test cases.
=> fix(terraform): extend check for google cloud functions 2nd generation

docs/1.Welcome/What is Checkov.md
=> chore: fix typo in `docs/1.Welcome/What is Checkov` 

checkov/kubernetes/checks/resource/base_container_check.py, checkov/kubernetes/checks/resource/k8s/CPULimits.py, checkov/kubernetes/checks/resource/k8s/Secrets.py, checkov/serverless/parsers/parser.py, tests/helm/test_runner_image_referencer.py, tests/kubernetes/checks/example_Secrets/pod-secretsEnvironment-UNKNOWN.yaml, tests/kubernetes/checks/test_AllowProvilegeEscalation.py, tests/kubernetes/checks/test_AllowedCapabilitiesSysAdmin.py, tests/kubernetes/checks/test_ContainerSecurityContext.py, tests/kubernetes/image_referencer/test_runner_k8s_resources.py, tests/kustomize/test_runner_image_referencer.py
- Handle malformed resources in k8s.
- Minor fix in Serverless parser.
=> fix(kubernetes): Couple of fixes in Checks

checkov/terraform/checks/resource/gcp/CloudArmorWAFACLCVE202144228.py
=> fix(terraform): Fix CloudArmorWAFACLCVE202144228 check

checkov/cloudformation/checks/resource/aws/ALBListenerTLS12.py
=> fix(cloudformation): Fix ALBListenerTLS12 check

checkov/sca_image/runner.py
* using request_wrapper in sca_image.runner
=> chore: using request_wrapper in sca_image.runner

checkov/terraform/checks/resource/gcp/AbsGoogleComputeFirewallUnrestrictedIngress.py, tests/terraform/checks/resource/gcp/example_GoogleComputeFirewallUnrestrictedIngress80/main.tf
=> fix(terraform): Fix TF AbsGoogleComputeFirewallUnrestrictedIngress check

github_action_resources/entrypoint.sh
GitHub has deprecated `set-output` and replaced it with this new format.
Please refer to this blog post for more details: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
[//]: # "
- …
=> chore: Update docker entrypoint: Use GHA GITHUB_OUTPUT

checkov/common/images/image_referencer.py, checkov/dockerfile/base_dockerfile_check.py, checkov/dockerfile/base_registry.py, checkov/dockerfile/checks/AddExists.py, checkov/dockerfile/checks/AliasIsUnique.py, checkov/dockerfile/checks/ExposePort22.py, checkov/dockerfile/checks/HealthcheckExists.py, checkov/dockerfile/checks/MaintainerExists.py, checkov/dockerfile/checks/ReferenceLatestTag.py, checkov/dockerfile/checks/RootUser.py, checkov/dockerfile/checks/RunUsingAPT.py, checkov/dockerfile/checks/UpdateNotAlone.py, checkov/dockerfile/checks/UserExists.py, checkov/dockerfile/checks/WorkdirIsAbsolute.py, checkov/dockerfile/image_referencer/manager.py, checkov/dockerfile/image_referencer/provider.py, checkov/dockerfile/runner.py, checkov/github_actions/runner.py, checkov/gitlab_ci/runner.py, mypy.ini
=> chore: enable mypy for dockerfile

checkov/common/parallelizer/parallel_runner.py, checkov/common/parsers/yaml/loader.py, checkov/common/runners/object_runner.py, checkov/common/runners/runner_registry.py, tests/github_actions/resources/.github/workflows/off_value.yaml, tests/github_actions/test_runner.py, tests/github_actions/test_schema_validation.py
=> fix(github): Fix GHA off value error resulting in checkov hanging

checkov/kubernetes/checks/resource/k8s/ServiceAccountTokens.py, tests/kubernetes/checks/example_ServiceAccountTokens/ServiceAccountTokensUNKNOWN.yaml
handle edge-case of spec is not a dict
=> fix(kubernetes): fix in ServiceAccountTokens check

.github/workflows/pr-test.yml, checkov/bicep/graph_builder/variable_rendering/renderer.py, checkov/cloudformation/graph_builder/variable_rendering/renderer.py, checkov/common/bridgecrew/integration_features/base_integration_feature.py, checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py, checkov/common/bridgecrew/integration_features/features/fixes_integration.py, checkov/common/bridgecrew/integration_features/features/policy_metadata_integration.py, checkov/common/bridgecrew/integration_features/features/repo_config_integration.py, checkov/common/bridgecrew/integration_features/features/suppressions_integration.py, checkov/common/graph/graph_builder/variable_rendering/renderer.py
=> chore: install py package for benchmark tests for now

.github/workflows/build.yml
=> chore(general): Add inputs to allow for custom bumping of version

checkov/azure_pipelines/runner.py
=> fix(azure): Support .yaml extension

checkov/gitlab_ci/checks/job/DetectImagesUsage.py, tests/gitlab_ci/image_referencer/test_runner_gitlab_workflows.py, tests/gitlab_ci/test_runner.py
=> feat(gitlab): Adding image detection check to gitlab ci

checkov/bicep/runner.py, checkov/common/graph/checks_infra/registry.py, checkov/common/runners/base_runner.py, checkov/common/typing.py, checkov/helm/runner.py, checkov/kubernetes/runner.py, checkov/kustomize/runner.py, mypy.ini
=> chore: Enable mypy for helm and kustomize

.github/exclude-patterns.txt
one fix the issue in code and/or in runtime?*
=> fix(secrets): fixed path of secrets tests to exclude

checkov/terraform/graph_builder/variable_rendering/renderer.py, tests/terraform/graph/variable_rendering/test_renderer.py, tests/terraform/graph/variable_rendering/test_resources/dynamic_nested_with_lookup_foreach/aws_iam_role.pipeline.tf, tests/terraform/graph/variable_rendering/test_resources/dynamic_nested_with_lookup_foreach/aws_kms_key.example.tf, tests/terraform/graph/variable_rendering/test_resources/dynamic_nested_with_lookup_foreach/data.aws_region.current.tf, tests/terraform/graph/variable_rendering/test_resources/dynamic_nested_with_lookup_foreach/examplea.auto.tfvars, tests/terraform/graph/variable_rendering/test_resources/dynamic_nested_with_lookup_foreach/locals.tf, tests/terraform/graph/variable_rendering/test_resources/dynamic_nested_with_lookup_foreach/main.tf, tests/terraform/graph/variable_rendering/test_resources/dynamic_nested_with_lookup_foreach/module.codepipeline.tf, tests/terraform/graph/variable_rendering/test_resources/dynamic_nested_with_lookup_foreach/variables.tf
=> feat(terraform): Wrap render dynamic blocks flow with try except

checkov/openapi/checks/resource/v2/SecurityRequirement.py, tests/openapi/checks/resource/v2/example_SecurityRequirement/fail3.yaml, tests/openapi/checks/resource/v2/test_SecurityRequirement.py
fixed a failing check on TypeError for invalid unexpected openapi template
=> fix(openapi): fixed error in invalid openapi template

checkov/common/graph/graph_builder/graph_components/blocks.py, checkov/terraform/graph_builder/graph_components/blocks.py, tests/terraform/graph/variable_rendering/test_renderer.py
=> fix(terraform): Fix dynamic attributes override each other

checkov/terraform/graph_builder/variable_rendering/renderer.py, tests/terraform/graph/variable_rendering/test_renderer.py, tests/terraform/graph/variable_rendering/test_resources/dynamic_block_nesting_attribute/main.tf, tests/terraform/graph/variable_rendering/test_resources/dynamic_block_nesting_attribute/variables.tf
=> feat(terraform): Support dynamic blocks with nested attributes

checkov/common/bridgecrew/platform_integration.py, checkov/common/output/report.py, checkov/common/sca/output.py, checkov/sca_package_2/output.py, checkov/sca_package_2/runner.py, checkov/sca_package_2/scanner.py
=> platform(sca): Poll sca scan results using Polling API

checkov/common/bridgecrew/platform_integration.py
=> platform(general): Support s3 client config for govcloud

checkov/common/bridgecrew/platform_integration.py
add src from Platform side instead of adding it from Checkov side
=> platform(sca): remove src from repo path

checkov/common/typing.py
=> platform(sca): add scaCliScanId parameter

checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py
=> chore: add debug error message for jsonpath expression errors

.github/workflows/build.yml
=> chore: load correct image tag and simplify image build

checkov/terraform/graph_builder/local_graph.py
=> fix(terraform): Remove cross variables edges duplications

checkov/circleci_pipelines/checks/DetectImagesUsage.py, tests/circleci_pipelines/image_referencer/test_runner.py, tests/circleci_pipelines/resources/.circleci/config.yml, tests/circleci_pipelines/test_runner.py
=> feat(circleci): add check for detecting images without check resource

checkov/terraform/checks/resource/azure/ACRContainerScanEnabled.py, tests/terraform/checks/resource/azure/example_ACRContainerScanEnabled/main.tf, tests/terraform/checks/resource/azure/test_ACRContainerScanEnabled.py
=> feat(terraform): ACR container scanning

checkov/helm/runner.py
=> fix(kubernetes): Handle invalid helm chart meta

checkov/terraform/checks/resource/azure/MLPublicAccess.py, tests/terraform/checks/resource/azure/example_MLPublicAccess/MLPublicAccess.tf, tests/terraform/checks/resource/azure/test_MLPublicAccess.py
=> fix(terraform): CKV_AZURE_144 passes on defaults

checkov/terraform/checks/resource/azure/ACREnableImageQuarantine.py, tests/terraform/checks/resource/azure/example_ACREnableImageQuarantine/main.tf, tests/terraform/checks/resource/azure/test_ACREnableImageQuarantine.py
=> feat(terraform): Azure ACR Enable Image Quarantine

checkov/terraform/checks/resource/azure/ACRGeoreplicated.py, tests/terraform/checks/resource/azure/example_ACRGeoreplicated/main.tf, tests/terraform/checks/resource/azure/test_ACRGeoreplicated.py
=> feat(terraform): Azure ACR check for replication

checkov/common/runners/runner_registry.py, tests/common/runner_registry/plan_with_external_tf_modules_for_enrichment/log_group_external/main.tf, tests/common/runner_registry/plan_with_external_tf_modules_for_enrichment/log_group_external/outputs.tf, tests/common/runner_registry/plan_with_external_tf_modules_for_enrichment/log_group_external/variables.tf, tests/common/runner_registry/plan_with_external_tf_modules_for_enrichment/log_group_external/versions.tf, tests/common/runner_registry/plan_with_external_tf_modules_for_enrichment/main.tf, tests/common/runner_registry/plan_with_external_tf_modules_for_enrichment/providers.tf, tests/common/runner_registry/plan_with_external_tf_modules_for_enrichment/tfplan.json, tests/common/runner_registry/test_runner_registry.py, tests/common/runner_registry/test_runner_registry_plan_enrichment.py
=> fix(terraform): download external modules with enrichment

.github/exclude-patterns.txt
=> chore: exclude all files under tests/secrets from secret scanning

checkov/terraform/checks/resource/azure/ACRGeoreplicated.py, tests/terraform/checks/resource/azure/example_ACRGeoreplicated/main.tf, tests/terraform/checks/resource/azure/test_ACRGeoreplicated.py
=> chore: merge Azure ACR check for replication to main

checkov/terraform/parser.py
=> fix next level

docs/7.Scan Examples/Terraform Plan Scanning.md, docs/7.Scan Examples/Terraform.md
=> docs(terraform): update Terraform modules docs

.github/pr-title-checker-config.json, checkov/terraform/checks/resource/kubernetes/AllowedCapabilities.py, checkov/terraform/checks/resource/kubernetes/AllowedCapabilitiesSysAdmin.py, checkov/terraform/checks/resource/kubernetes/DockerSocketVolume.py, checkov/terraform/checks/resource/kubernetes/DropCapabilities.py, checkov/terraform/checks/resource/kubernetes/MinimiseCapabilities.py, tests/terraform/checks/resource/kubernetes/test_AllowedCapabilities.py, tests/terraform/checks/resource/kubernetes/test_AllowedCapabilitiesSysAdmin.py, tests/terraform/checks/resource/kubernetes/test_DockerSocketVolume.py, tests/terraform/checks/resource/kubernetes/test_DropCapabilities.py, tests/terraform/checks/resource/kubernetes/test_MinimiseCapabilities.py
=> fix(terraform_plan): Fix k8s checks edgecases for terraform plan

checkov/common/util/docs_generator.py
=> fix(general): fix doc links on windows

checkov/kubernetes/kubernetes_utils.py, tests/kubernetes/graph/test_kubernetes_utils.py, tests/kubernetes/graph/test_local_graph.py
- create Pod resource id by concatenating labels
- enable k8s graph features using env vars
=> feat(kubernetes): create simple resources id for pods; allow enabling k8s graph features using env vars

checkov/secrets/runner.py
=> fix(secrets): fix_Record_code_block_secrets

checkov/terraform/checks/resource/azure/DataExplorerUsesDiskEncryption.py, tests/terraform/checks/resource/azure/example_DataExplorerUsesDiskEncryption/main.tf, tests/terraform/checks/resource/azure/test_DataExplorerUsesDiskEncryption.py
=> fix(terraform): azurerm kusto cluster encryption - wrong attribute tested for

checkov/common/output/record.py, checkov/terraform/checks/resource/kubernetes/AllowedCapabilities.py, checkov/terraform/checks/resource/kubernetes/AllowedCapabilitiesSysAdmin.py, checkov/terraform/checks/resource/kubernetes/CPULimits.py, checkov/terraform/checks/resource/kubernetes/CPURequests.py, checkov/terraform/checks/resource/kubernetes/ContainerSecurityContext.py, checkov/terraform/checks/resource/kubernetes/DockerSocketVolume.py, checkov/terraform/checks/resource/kubernetes/DropCapabilities.py, checkov/terraform/checks/resource/kubernetes/DropCapabilitiesPSP.py, checkov/terraform/checks/resource/kubernetes/ImageDigest.py, checkov/terraform/checks/resource/kubernetes/MemoryLimits.py, checkov/terraform/checks/resource/kubernetes/MemoryRequests.py, checkov/terraform/checks/resource/kubernetes/MinimiseCapabilities.py, checkov/terraform/checks/resource/kubernetes/MinimiseCapabilitiesPSP.py, checkov/terraform/checks/resource/kubernetes/PodSecurityContext.py, checkov/terraform/checks/resource/kubernetes/PrivilegedContainer.py, checkov/terraform/checks/resource/kubernetes/PrivilegedContainerPSP.py, checkov/terraform/checks/resource/kubernetes/ReadinessProbe.py, checkov/terraform/checks/resource/kubernetes/ReadonlyRootFilesystem.py, checkov/terraform/checks/resource/kubernetes/Secrets.py, checkov/terraform/checks/resource/kubernetes/Tiller.py, checkov/terraform/checks/resource/kubernetes/TillerService.py
=> fix(terraform): Fix TF checks crashes

checkov/terraform/checks/resource/azure/AKSMaxPodsMinimum.py, tests/terraform/checks/resource/azure/example_AKSMaxPodsMinimum/main.tf, tests/terraform/checks/resource/azure/test_AKSMaxPodsMinimum.py
=> fix(terraform): Fix CKV_AZURE_168 check

checkov/terraform/graph_builder/variable_rendering/renderer.py
Fix an issue in dynamic blocks.
=> fix(terraform): Fix an issue in dynamic blocks

checkov/common/runners/runner_registry.py, checkov/common/util/secrets_omitter.py, tests/common/secrets_omitter/test_secrets_omitter.py
Reverts bridgecrewio/checkov#4014
=> feat(secrets): Omit secrets from reports based on secrets reports

checkov/terraform/graph_builder/local_graph.py
=> fix(terraform): fix resource block address

checkov/common/bridgecrew/integration_features/features/suppressions_integration.py, checkov/main.py, checkov/runner_filter.py, tests/common/integration_features/test_suppressions_integration.py
=> feat(general): Apply policy-level suppressions as skipped checks

checkov/secrets/plugins/custom_regex_detector.py, tests/secrets/test_custom_regex_detector.py
=> fix(secrets): custom secret add support for value str and not only list

tests/kubernetes/graph/checks/resources/RoleBindingPE/Failing1/FailingClusterRole.yaml, tests/kubernetes/graph/checks/resources/RoleBindingPE/Failing2/FailingClusterRole.yaml, tests/kubernetes/graph/checks/resources/RoleBindingPE/Failing3/FailingRole.yaml, tests/kubernetes/graph/checks/resources/RoleBindingPE/Passing1/PassingClusterRole.yaml, tests/kubernetes/graph/checks/resources/RoleBindingPE/Passing2/PassingClusterRole.yaml
=> fix(kubernetes): Corrected list format for yaml files in new k8s graph check tests

checkov/terraform/graph_builder/variable_rendering/renderer.py
=> fix(terraform): Fix in dot separator in the dynamic argument

checkov/terraform/graph_builder/variable_rendering/renderer.py
Fix some errors in Dynamic Blocks rendering.
=> fix(terraform): Fix some errors in Dynamic Blocks rendering

checkov/common/runners/runner_registry.py, checkov/common/util/secrets_omitter.py, checkov/main.py
=> feat(secrets): Inject secrets omitter to runner registry

checkov/terraform/checks/data/aws/IAMPublichActionsPolicy.py, tests/terraform/checks/data/aws/example_IAMPublichActionsPolicy/public_actions.tf, tests/terraform/checks/data/aws/test_IAMPublicActionsPolicy.py
fixed unexpected data type in TF file for IAMPublicActionsPolicy
=> fix(terraform): fixed unexpected data for IAMPublicActionsPolicy

checkov/terraform/checks/resource/azure/AzureContainerGroupDeployedIntoVirtualNetwork.py, tests/terraform/checks/resource/azure/example_AzureContainerGroupDeployedIntoVirtualNetwork/main.tf, tests/terraform/checks/resource/azure/test_AzureContainerGroupDeployedIntoVirtualNetwork.py
=> fix(terraform): checkov fix as resource container_group modified

checkov/terraform/checks/resource/azure/MonitorLogProfileRetentionDays.py, tests/terraform/checks/resource/azure/test_MonitorLogProfileRetentionDays.py
fixed unexpected data type in TF file for MonitorLogProfileRetentionDays
=> fix(terraform): fixed unexpected data for MonitorLogProfileRetentionDays

Manifest.in, setup.py
=> feat(kubernetes): Add kubernetes YAML checks to checkov packaging

checkov/terraform/checks/resource/azure/StorageAccountName.py, tests/terraform/checks/resource/azure/example_StorageAccountName/azurecaf.tf, tests/terraform/checks/resource/azure/example_StorageAccountName/main.tf, tests/terraform/checks/resource/azure/test_StorageAccountName.py
=> fix(terraform): CKV_AZURE_43 add new test case

tests/common/graph/checks/test_policy_packaging.py
=> chore: add missing __init__.py files to package graph checks correctly

checkov/main.py
=> fix(general): change env var name for no-fail-on-crash flag

Pipfile, Pipfile.lock, checkov/bitbucket_pipelines/runner.py, checkov/circleci_pipelines/image_referencer/provider.py, checkov/yaml_doc/base_registry.py, setup.py
=> chore: update bc-detect-secrets version to 1.4.6

checkov/common/util/parser_utils.py, checkov/terraform/graph_builder/graph_to_tf_definitions.py, checkov/terraform/graph_builder/local_graph.py, checkov/terraform/parser.py, checkov/terraform/runner.py
add the previous get_tf_definition_key function for support in the platform
=> platform(terraform): add previous get_tf_definition_key function

checkov/sca_package/runner.py
fixing broekn integration tests
=> fix(sca): fixing integration tests

checkov/common/bridgecrew/integration_features/features/licensing_integration.py, tests/common/integration_features/test_licensing_integration.py
=> chore(general): Remove usage of billing plan from platform

checkov/main.py
=> feat(general): add the stack trace to the error message when caught by main.py

checkov/terraform/image_referencer/manager.py, checkov/terraform/image_referencer/provider/gcp.py, tests/terraform/image_referencer/provider/test_gcp.py, tests/terraform/image_referencer/resources/gcp/cloud_run.tf, tests/terraform/image_referencer/resources/gcp/cloud_run_v2.tf, tests/terraform/image_referencer/resources/gcp/cloudbuild.tf, tests/terraform/image_referencer/test_manager.py, tests/terraform/image_referencer/test_runner_gcp_resources.py
=> feat(sca): add GCP Terraform resources for Image Referencer

checkov/terraform/checks/resource/azure/VnetLocalDNS.py, tests/terraform/checks/resource/azure/example_VnetLocalDNS/main.tf, tests/terraform/checks/resource/azure/test_VnetLocalDNS.py
=> fix(terraform): fix azure network address invalid value

.github/PULL_REQUEST_TEMPLATE.md
=> fix(general): Reformat PR template

checkov/terraform/checks/resource/azure/VnetLocalDNS.py, tests/terraform/checks/resource/azure/example_VnetLocalDNS/main.tf
fix edge-case in CKV_AZURE_183 check
=> fix(terraform): fix edge-case in CKV_AZURE_183 check

.github/exclude-patterns.txt
add test path to exclude patterns to avoid detect-secret failure
=> fix(terraform): add test path to exclude-patterns

checkov/terraform/checks/resource/azure/MonitorLogProfileRetentionDays.py, tests/terraform/checks/resource/azure/test_MonitorLogProfileRetentionDays.py
fix edge-case in CKV_AZURE_37 check
=> fix(terraform): fix edge-case in CKV_AZURE_37 check

bin/checkov, bin/checkov.cmd, checkov/common/bridgecrew/check_type.py, checkov/common/util/ext_argument_parser.py, checkov/main.py, tests/config/TestConfigFile.py, tests/test_main.py
=> chore: split main run function and move to a dedicated class

checkov/common/checks_infra/solvers/connections_solvers/complex_connection_solver.py
=> fix(terraform): fix graph checks nested modules

checkov/json_doc/base_registry.py, tests/generic_json/test_runner.py
=> fix(github): Handle entity configurations of type list

checkov/common/bridgecrew/vulnerability_scanning/integrations/docker_image_scanning.py, checkov/common/bridgecrew/vulnerability_scanning/integrations/twistcli.py
remove test report_results from checkov, as it is not used at all
=> feat(sca): remove test report_results from checkov, as it is not used at all

checkov/common/bridgecrew/integration_features/features/licensing_integration.py
=> fix(general): fix f-string log message

checkov/terraform/checks/resource/azure/KeyVaultDisablesPublicNetworkAccess.py, tests/terraform/checks/resource/azure/example_KeyVaultDisablesPublicNetworkAccess/main.tf, tests/terraform/checks/resource/azure/test_KeyVaultDisablesPublicNetworkAccess.py
=> fix(terraform): out of range error by checking if list is empty

checkov/kubernetes/runner.py
=> fix(kubernetes): remove unneeded context check

checkov/common/bridgecrew/platform_integration.py, checkov/contributor_metrics.py
=> chore: os api use v2

.github/exclude-patterns.txt
=> fix(general): Update exclude-patterns.txt

checkov/common/util/consts.py, tests/sca_package/test_output_reports.py, tests/sca_package_2/test_output_reports.py
=> feat(sca): enable CHECKOV_RUN_SCA_PACKAGE_SCAN_V2 env var

checkov/secrets/runner.py, tests/secrets/conftest.py, tests/secrets/test_secrets_verification.py
=> fix(secrets): Fix api key condition in verify_secrets

checkov/secrets/plugins/custom_regex_detector.py
=> fix(secrets): Remove raw string modifier from re.compile

checkov/dockerfile/checks/graph_checks/RunUnsafeCurl.yaml, tests/dockerfile/graph_builder/checks/resources/RunUnsafeCurl/expected.yaml, tests/dockerfile/graph_builder/checks/resources/RunUnsafeCurl/fail/Dockerfile.combo, tests/dockerfile/graph_builder/checks/resources/RunUnsafeCurl/fail/Dockerfile.long, tests/dockerfile/graph_builder/checks/resources/RunUnsafeCurl/fail/Dockerfile.multiline, tests/dockerfile/graph_builder/checks/resources/RunUnsafeCurl/fail/Dockerfile.shell, tests/dockerfile/graph_builder/checks/resources/RunUnsafeCurl/fail/Dockerfile.short, tests/dockerfile/graph_builder/checks/resources/RunUnsafeCurl/pass/Dockerfile, tests/dockerfile/graph_builder/checks/test_yaml_policies.py, tests/dockerfile/image_referencer/test_runner_dockerfile_resources.py
=> feat(dockerfile): Add check for unsafe curl usages

checkov/secrets/runner.py, tests/secrets/test_coordinator.py
=> fix(secrets): fix relative file path in secrets saved to coordinator

checkov/common/bridgecrew/wrapper.py, tests/common/bridgecrew/conftest.py, tests/common/bridgecrew/test_wrapper.py
=> feat(secrets): Add secret validation status to reduced report

checkov/secrets/runner.py, tests/secrets/conftest.py, tests/secrets/test_runner.py, tests/secrets/test_secrets_verification.py
=> fix(secrets): Change verify secrets key to include relative path

.flake8
=> chore: exclude flake8 code B028

checkov/common/output/record.py, checkov/common/output/secrets_record.py, checkov/secrets/consts.py, checkov/secrets/runner.py
Reverts bridgecrewio/checkov#4238
=> fix(secrets): Revert "fix(secrets): Change secret validation status message"

.github/workflows/build.yml
=> chore(gha): add container builds for m1 mac

.github/workflows/build.yml
=> chore: fix multi arch Docker build

checkov/common/bridgecrew/vulnerability_scanning/image_scanner.py
=> fix(terraform): fix Exception in image ref

checkov/common/bridgecrew/vulnerability_scanning/image_scanner.py, checkov/common/images/image_referencer.py
=> feat(general): add logs for async license and image retrieval 

checkov/ansible/graph_builder/local_graph.py, checkov/github_actions/graph_builder/local_graph.py
=> chore: lower log level

checkov/kubernetes/graph_builder/local_graph.py, tests/kubernetes/graph/resources/custom_resource.yaml, tests/kubernetes/graph/test_local_graph.py
skip extracting pods for custom resources
=> fix(kubernetes): skip extracting pods for custom resources

Pipfile, Pipfile.lock, setup.py
=> fix(sca): require requests 2.27.0

checkov/terraform/graph_builder/local_graph.py, tests/terraform/graph/graph_builder/test_local_graph.py, tests/terraform/graph/resources/reset_edges/main.tf, tests/terraform/graph/resources/reset_edges/variables.tf
add reset edges function to terraform local graph
=> feat(terraform): add reset edges function to terraform local graph

checkov/terraform/checks/resource/aws/IAMPrivilegeEscalation.py, checkov/terraform/checks/resource/base_cloudsplaining_resource_iam_check.py, tests/terraform/checks/resource/aws/example_IAMPrivilegeEscalation/main.tf, tests/terraform/checks/resource/aws/test_IAMPrivilegeEscalation.py
=> feat(terraform): Added basic check with test for tf resource with IAM privilege escalation

checkov/terraform/checks/resource/azure/LinuxVMUsesSSH.py
=> fix(terraform): simple check naming fix

.github/workflows/build.yml
=> chore: add labels to docker images

.github/workflows/build.yml
=> chore: fix docker/meta-action config

.github/workflows/build.yml, .github/workflows/pr-test.yml, checkov/common/runners/runner_registry.py, tests/common/runner_registry/test_runner_registry.py
=> fix(general): fix compact json output

checkov/cloudformation/checks/resource/aws/RDSMultiAZEnabled.py
=> chore: fix flake8 issue

Pipfile, Pipfile.lock, tests/github/checks/test_python_policies.py
=> chore: leverage freezegun to freeze time for a test

checkov/openapi/checks/resource/v2/PathSchemeDefineHTTP.py, checkov/terraform/checks/resource/aws/ECRPolicy.py, checkov/terraform/checks/resource/gcp/GoogleKMSKeyIsPublic.py, tests/openapi/checks/resource/v2/example_PathSchemeDefineHTTP/expected.yaml, tests/openapi/checks/resource/v2/example_PathSchemeDefineHTTP/pass2.yaml, tests/terraform/checks/resource/aws/example_ECRPolicy/main.tf, tests/terraform/checks/resource/aws/test_ECRPolicy.py, tests/terraform/checks/resource/gcp/example_GoogleKMSKeyIsPublic/main.tf, tests/terraform/checks/resource/gcp/test_GoogleKMSKeyIsPublic.py
=> fix(general): Checks edge-cases fixes in terraform and openapi

checkov/terraform/checks/resource/aws/SQSQueueEncryption.py, tests/terraform/checks/resource/aws/example_SQSQueueEncryption/main.tf, tests/terraform/checks/resource/aws/test_SQSQueueEncryption.py
=> fix(terraform): SQS check was all types of wrong

checkov/ansible/checks/base_ansible_task_check.py, checkov/ansible/checks/graph_checks/BlockErrorHandling.yaml, checkov/ansible/graph_builder/graph_components/resource_types.py, checkov/ansible/graph_builder/local_graph.py, checkov/ansible/runner.py, checkov/common/graph/graph_builder/consts.py, docs/3.Custom Policies/YAML Custom Policies.md, tests/ansible/checks/graph_checks/resources/BlockErrorHandling/expected.yaml, tests/ansible/checks/graph_checks/resources/BlockErrorHandling/fail.yaml, tests/ansible/checks/graph_checks/resources/BlockErrorHandling/pass.yaml, tests/ansible/checks/graph_checks/test_yaml_policies.py, tests/ansible/examples/blocks.yml, tests/ansible/test_runner.py
=> feat(ansible): add support for Ansible blocks

.github/workflows/build.yml, checkov/common/checks_infra/registry.py, checkov/common/util/docs_generator.py, tests/common/utils/test_docs_generator.py
=> docs(general): fix graph check link in docs

checkov/common/graph/db_connectors/igraph/igraph_db_connector.py
Added iGraph initialization when parsing local graph to iGraph in `IgraphConnector` for same platform usage as in `NetworkxConnector`
=> fix(graph): added graph init to igraph db connector

checkov/common/runners/object_runner.py, tests/github_actions/test_runner_auxiliary.py
=> fix(gha): fix GHA _get_jobs edge case (string step)

checkov/kustomize/runner.py, tests/kustomize/test_runner.py
=> fix(kustomize): fix kustomize file path cli

tests/terraform/graph/checks_infra/attribute_solvers/not_exists_solver/SecureTransportExist.yaml, tests/terraform/graph/checks_infra/attribute_solvers/not_exists_solver/resources/main.tf, tests/terraform/graph/checks_infra/attribute_solvers/not_exists_solver/test_solver.py
=> feat(graph): Add UT as an example of not-exists for the nested list.

checkov/terraform/checks/resource/aws/MSKClusterNodesArePrivate.py, tests/terraform/checks/resource/aws/example_MSKClusterNodesArePrivate/main.tf, tests/terraform/checks/resource/aws/test_MSKClusterNodesArePrivate.py
=> feat(terraform): check msk nodes are private

docs/2.Basics/Installing Checkov.md
=> docs(general): update installation on Alpine docs

checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py
=> fix(terraform): Fix an str split edge case in function

checkov/common/output/csv.py, checkov/common/output/cyclonedx.py, checkov/common/util/consts.py
*adding registry-url to the cyclonedx output report
=> feat(sca): adding registry-url to the cyclonedx output report

checkov/secrets/scan_git_history.py
Failed to initialize: Bad git executable
=> fix(secrets):  import git

checkov/terraform/checks/graph_checks/aws/CloudFrontHasResponseHeadersPolicy.yaml, tests/terraform/graph/checks/resources/CloudFrontHasResponseHeadersPolicy/expected.yaml, tests/terraform/graph/checks/resources/CloudFrontHasResponseHeadersPolicy/main.tf
=> fix(terraform): add datasource option for headers check

checkov/common/output/cyclonedx.py, checkov/common/sca/output.py, tests/common/output/test_cyclonedx_report.py, tests/common/output/test_gitlab_sast_report.py, tests/sca_package/test_output.py, tests/sca_package_2/test_output.py
*adding is_registry_url and printing in the cyclonedx only private registries urls
=> feat(sca): adding is_registry_url and printing in the cyclonedx only private registries urls

checkov/common/sca/commons.py, checkov/common/sca/output.py
* support also the key "registryUrl" when extracting registry_url for the report
=> feat(sca): support also the key "registryUrl" when extracting registry_url for the report

checkov/terraform/graph_builder/utils.py
=> fix(terraform): Optional module content path

Manifest.in, checkov/arm/checks/graph_checks/AzureSpringCloudConfigWithVnet.yaml, checkov/arm/graph_builder/graph_components/block_types.py, checkov/arm/graph_builder/graph_components/blocks.py, checkov/arm/graph_builder/local_graph.py, checkov/arm/graph_manager.py, checkov/arm/parser/cfn_yaml.py, checkov/arm/runner.py, checkov/arm/utils.py, checkov/common/graph/graph_builder/consts.py, checkov/common/util/docs_generator.py, docs/3.Custom Policies/YAML Custom Policies.md, setup.py, tests/arm/examples/container_instance.json, tests/arm/graph_builder/checks/resources/AzureSpringCloudConfigWithVnet/expected.yaml, tests/arm/graph_builder/checks/resources/AzureSpringCloudConfigWithVnet/fail.json, tests/arm/graph_builder/checks/resources/AzureSpringCloudConfigWithVnet/pass.json, tests/arm/graph_builder/checks/test_yaml_policies.py, tests/arm/graph_builder/test_local_graph.py, tests/arm/test_graph_manager.py
=> feat(arm): add graph capabilities to ARM framework

Pipfile.lock, checkov/common/util/stopit/__init__.py, checkov/common/util/stopit/utils.py
=> chore: remove unneeded version check

checkov/ansible/runner.py, checkov/azure_pipelines/runner.py, checkov/circleci_pipelines/runner.py, checkov/common/runners/object_runner.py, checkov/github_actions/runner.py, checkov/gitlab_ci/runner.py, checkov/openapi/runner.py, tests/github_actions/checks/test_extra_checks.py, tests/github_actions/test_runner_resource_names.py
=> fix(gha): Align GHA resource ids (Graph vs Python checks)

checkov/terraform/graph_builder/variable_rendering/renderer.py
remove dynamic warning exc_info
=> fix(terraform): remove dynamic warning exc_info

Pipfile, Pipfile.lock, setup.py
=> chore: update bc-detect-secrets version to 1.4.13

checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py, checkov/common/bridgecrew/integration_features/features/fixes_integration.py, checkov/common/bridgecrew/integration_features/features/suppressions_integration.py, checkov/common/bridgecrew/platform_integration.py
=> chore(general): Enable BC API URL dynamic loading

checkov/terraform/graph_builder/foreach_handler.py
=> fix(terraform): TF foreach - Avoid rendering in static statements

checkov/common/bridgecrew/bc_source.py, checkov/common/bridgecrew/platform_integration.py, checkov/main.py, checkov/sca_package_2/runner.py, tests/sca_package_2/conftest.py
=> fix(sca): Set prisma token and scan packages by v2 for IDE scans

checkov/common/graph/graph_builder/graph_components/blocks.py, checkov/terraform/graph_builder/foreach_handler.py, checkov/terraform/graph_builder/graph_components/blocks.py, tests/terraform/graph/variable_rendering/expected_data_foreach.json, tests/terraform/graph/variable_rendering/test_foreach_renderer.py
=> feat(terraform): Set foreach_attrs directly under the block

checkov/common/graph/graph_builder/graph_components/attribute_names.py, checkov/common/graph/graph_builder/graph_components/blocks.py
=> feat(terraform): Add foreach_attrs in saved graph

.github/workflows/build.yml
=> docs(ansible): add Ansible policy docs generation

checkov/github_actions/runner.py
=> fix(gha): skip schema validity check if parsing returned None

checkov/common/bridgecrew/integration_features/features/fixes_integration.py
=> fix(general): do not stop getting fixes if one attempt results in a 403

checkov/sca_image/runner.py
When Twistcli fails, we're having hard time finding the error logs. This PR will make sure we have a specific log message we can use before a failure to search for
[//]: # " …
=> fix(sca): Added an error log for Twistcli failures

checkov/terraform/checks/resource/aws/CloudtrailEventDataStoreUsesCMK.py, tests/terraform/checks/resource/aws/example_CloudtrailEventDataStoreUsesCMK/main.tf, tests/terraform/checks/resource/aws/test_CloudtrailEventDataStoreUsesCMK.py
=> feat(terraform): CloudtrailEventDataStoreUsesCMK 

.github/PULL_REQUEST_TEMPLATE.md, .github/pr-title-checker-config.json, README.md, checkov/common/bridgecrew/check_type.py, checkov/common/bridgecrew/code_categories.py, checkov/common/parsers/json/__init__.py, checkov/main.py, checkov/terraform/graph_builder/graph_components/module.py, checkov/terraform/runner.py, checkov/terraform_json/parser.py, checkov/terraform_json/runner.py, checkov/terraform_json/utils.py, dogfood_tests/test_checkov_dogfood.py, tests/ansible/graph_builder/test_local_graph.py, tests/common/integration_features/test_licensing_integration.py, tests/common/test_runner_filter.py, tests/terraform_json/examples/cdk.tf.json, tests/terraform_json/test_graph_manager.py, tests/terraform_json/test_parser.py, tests/terraform_json/test_runner.py, tests/test_main.py, tests/test_runner_filter.py
=> feat(general): add Terraform JSON support

checkov/arm/graph_builder/local_graph.py, checkov/arm/runner.py, tests/arm/runner/resources/no_resource.json, tests/arm/runner/test_runner.py
=> fix(arm): ignore incomplete resource in ARM templates

checkov/common/bridgecrew/platform_integration.py
=> platform(general): skip uploading repo for VSCode source

checkov/common/runners/runner_registry.py, checkov/main.py, kubernetes/Dockerfile, tests/test_main.py
=> chore: allow to set tool name at the main level

checkov/terraform/graph_builder/variable_rendering/renderer.py
Fix for foreach subgraph rendering - validation for multiple edges.
=> feat(terraform): Fix for foreach subgraph rendering

checkov/arm/checks/resource/SQLServerAuditingRetention90Days.py
=> fix(arm): Fix resource type check in SQLServerAuditingRetention90Days

checkov/gitlab_ci/common/resource_id_utils.py
=> fix(gitlab): index_out_of_range

checkov/terraform/checks/resource/aws/DBSnapshotsArePrivate.py, tests/terraform/checks/resource/aws/example_DBSnapshotsArePrivate/main.tf, tests/terraform/checks/resource/aws/test_DBSnapshotsArePrivate.py
=> feat(terraform): ensure DB snapshots arent public

checkov/terraform/checks/resource/aws/CloudfrontDistributionDefaultRoot.py, tests/terraform/checks/resource/aws/example_CloudfrontDistributionDefaultRoot/main.tf, tests/terraform/checks/resource/aws/test_CloudfrontDistributionDefaultRoot.py
=> feat(terraform): AWS Ensure cloudfront has a default root

checkov/common/graph/graph_builder/graph_components/block_types.py, checkov/terraform/graph_builder/foreach_handler.py, checkov/terraform/graph_builder/graph_components/blocks.py, checkov/terraform/graph_builder/local_graph.py, tests/terraform/graph/variable_rendering/expected_foreach_modules_tf_definitions.json, tests/terraform/graph/variable_rendering/resources/foreach_module/main.tf, tests/terraform/graph/variable_rendering/resources/foreach_module/module/main.tf, tests/terraform/graph/variable_rendering/resources/foreach_module/module/module2/main.tf, tests/terraform/graph/variable_rendering/resources/foreach_module_and_resource/main.tf, tests/terraform/graph/variable_rendering/resources/foreach_module_and_resource/module/main.tf, tests/terraform/graph/variable_rendering/resources/foreach_module_dup_foreach/main.tf, tests/terraform/graph/variable_rendering/resources/foreach_module_dup_foreach/module/main.tf, tests/terraform/graph/variable_rendering/resources/foreach_module_dup_foreach/module/module2/main.tf, tests/terraform/graph/variable_rendering/resources/foreach_module_dup_foreach/variable.tf, tests/terraform/graph/variable_rendering/resources/foreach_module_with_more_than_two_resources/main.tf, tests/terraform/graph/variable_rendering/resources/foreach_module_with_more_than_two_resources/module/main.tf, tests/terraform/graph/variable_rendering/resources/foreach_module_with_more_than_two_resources/module/module2/main.tf, tests/terraform/graph/variable_rendering/test_foreach_renderer.py, tests/terraform/parser/resources/parser_dup_nested/main.tf, tests/terraform/parser/resources/parser_dup_nested/variable.tf, tests/terraform/parser/test_new_parser_modules.py
=> feat(terraform): Duplicate module vertices with subgraph in case of foreach/count on module

Pipfile, Pipfile.lock, checkov/common/bridgecrew/platform_integration.py, checkov/common/bridgecrew/wrapper.py
=> chore: add boto3 stubs

checkov/terraform/checks/resource/aws/SagemakerNotebookInCustomVPC.py, tests/terraform/checks/resource/aws/example_SagemakerNotebookInCustomVPC/main.tf, tests/terraform/checks/resource/aws/test_SagemakerNotebookInCustomVPC.py
=> feat(terraform): Sagemaker Notebook In Custom VPC

tests/secrets/test_secret_git_history.py
=> chore: lower timeout of secret test

checkov/terraform/checks/resource/aws/CloudfrontDistributionOriginFailover.py, tests/terraform/checks/resource/aws/example_CloudfrontDistributionOriginFailover/main.tf, tests/terraform/checks/resource/aws/test_CloudfrontDistributionOriginFailover.py
=> feat(terraform): CloudDistribution set Failover origin

checkov/terraform/checks/resource/aws/CodebuildS3LogsEncrypted.py, tests/terraform/checks/resource/aws/example_CodebuildS3LogsEncrypted/main.tf, tests/terraform/checks/resource/aws/test_CodebuildS3LogsEncrypted.py, tests/terraform/image_referencer/test_plan_runner_aws_resources.py, tests/terraform/image_referencer/test_runner_aws_resources.py
=> feat(terraform): code build s3 logs are encrypted

checkov/terraform/checks/resource/aws/ElasticBeanstalkUseEnhancedHealthChecks.py, tests/terraform/checks/resource/aws/example_ElasticBeanstalkUseEnhancedHealthChecks/main.tf, tests/terraform/checks/resource/aws/test_ElasticBeanstalkUseEnhancedHealthChecks.py
=> feat(terraform): Elasticbeanstalk should use enhanced health reporting

checkov/terraform/checks/resource/aws/RDSClusterCopyTags.py, tests/terraform/checks/resource/aws/example_RDSClusterCopyTags/main.tf, tests/terraform/checks/resource/aws/test_RDSClusterCopyTags.py
=> feat(terraform): RDS cluster copy tags to snapshot

checkov/terraform/graph_builder/foreach/abstract_handler.py
Avoid regex check for an empty list in the statement list.
=> fix(terraform): Foreach - Fix regex on an empty list

checkov/common/util/json_utils.py, checkov/terraform/modules/module_objects.py
=> fix(terraform): Correctly serialize/deserialize TFModule object

checkov/common/parallelizer/parallel_runner.py, checkov/secrets/scan_git_history.py
=> chore(secrets): logging and time measure 

checkov/ansible/checks/graph_checks/PanosPolicyLogForwarding.yaml, checkov/ansible/checks/graph_checks/PanosPolicyLoggingEnabled.yaml, checkov/ansible/checks/graph_checks/PanosZoneProtectionProfile.yaml, checkov/ansible/checks/graph_checks/PanosZoneUserIDIncludeACL.yaml, tests/ansible/checks/graph_checks/resources/PanosPolicyDescription/fail.yaml, tests/ansible/checks/graph_checks/resources/PanosPolicyLogForwarding/expected.yaml, tests/ansible/checks/graph_checks/resources/PanosPolicyLogForwarding/fail.yaml, tests/ansible/checks/graph_checks/resources/PanosPolicyLogForwarding/pass.yaml, tests/ansible/checks/graph_checks/resources/PanosPolicyLoggingEnabled/expected.yaml, tests/ansible/checks/graph_checks/resources/PanosPolicyLoggingEnabled/fail.yaml, tests/ansible/checks/graph_checks/resources/PanosPolicyLoggingEnabled/pass.yaml, tests/ansible/checks/graph_checks/resources/PanosPolicyNoApplicationAny/fail.yaml, tests/ansible/checks/graph_checks/resources/PanosPolicyNoApplicationAny/pass.yaml, tests/ansible/checks/graph_checks/resources/PanosPolicyNoDSRI/fail.yaml, tests/ansible/checks/graph_checks/resources/PanosPolicyNoServiceAny/fail.yaml, tests/ansible/checks/graph_checks/resources/PanosPolicyNoServiceAny/pass.yaml, tests/ansible/checks/graph_checks/resources/PanosPolicyNoSrcAnyDstAny/fail.yaml, tests/ansible/checks/graph_checks/resources/PanosPolicyNoSrcAnyDstAny/pass.yaml, tests/ansible/checks/graph_checks/resources/PanosZoneProtectionProfile/expected.yaml, tests/ansible/checks/graph_checks/resources/PanosZoneProtectionProfile/fail.yaml, tests/ansible/checks/graph_checks/resources/PanosZoneProtectionProfile/pass.yaml, tests/ansible/checks/graph_checks/resources/PanosZoneUserIDIncludeACL/expected.yaml, tests/ansible/checks/graph_checks/resources/PanosZoneUserIDIncludeACL/fail.yaml, tests/ansible/checks/graph_checks/resources/PanosZoneUserIDIncludeACL/pass.yaml, tests/ansible/checks/graph_checks/test_yaml_policies.py
- More Ansible checks for PAN-OS, this PR focuses on checks for policies (logging features) and security zone-related features.
- Also updated unit tests for previous PAN-OS checks that were affected by the new checks (specifically for `log_setting`) in this PR.
Added Ansible to existing Terraform CKV_PAN_9, 10, 14 15
These checks are from the NGFW best practices
N/A
=> feat(ansible): PAN-OS policy and zone checks

checkov/common/bridgecrew/vulnerability_scanning/integrations/docker_image_scanning.py, checkov/common/images/image_referencer.py, checkov/common/sca/output.py, checkov/sca_image/runner.py, tests/common/bridgecrew/vulnerability_scanning/integrations/test_docker_image_scanning.py
=> platform(general): Save error lines in IR records

checkov/terraform/graph_builder/graph_components/module.py
=> fix(terraform): Fix add_to_block condition to support more edge cases  

checkov/secrets/scan_git_history.py
=> fix(secrets): catch errors in middle of process of getting commit diffs

checkov/terraform/checks/resource/aws/RedshiftClusterUseEnhancedVPCRouting.py, tests/terraform/checks/resource/aws/example_RedshiftClusterUseEnhancedVPCRouting/main.tf, tests/terraform/checks/resource/aws/test_RedshiftClusterUseEnhancedVPCRouting.py
=> feat(terraform): Ensure Redshift uses enhanced vpc routing

checkov/terraform/checks/resource/aws/ElasticCacheAutomaticMinorUpgrades.py, tests/terraform/checks/resource/aws/example_ElasticCacheAutomaticMinorUpgrades/main.tf, tests/terraform/checks/resource/aws/test_ElasticCacheAutomaticMinorUpgrades.py
=> feat(terraform): ElasticCache for Redis cluster should automatically take minor updates

checkov/terraform/runner.py
=> fix(terraform): Fix for edge cases in for_each modules

checkov/terraform/checks/resource/azure/AppServiceDotnetFrameworkVersion.py, checkov/terraform/checks/resource/azure/AppServiceJavaVersion.py, checkov/terraform/checks/resource/azure/AppServicePHPVersion.py, checkov/terraform/checks/resource/azure/AppServicePythonVersion.py, tests/terraform/checks/resource/azure/example_AppServiceDotnetFrameworkVersion/main.tf, tests/terraform/checks/resource/azure/example_AppServiceJavaVersion/main.tf, tests/terraform/checks/resource/azure/example_AppServicePHPVersion/main.tf, tests/terraform/checks/resource/azure/example_AppServicePythonVersion/main.tf, tests/terraform/checks/resource/azure/test_AppServiceDotnetFrameworkVersion.py, tests/terraform/checks/resource/azure/test_AppServiceJavaVersion.py, tests/terraform/checks/resource/azure/test_AppServicePHPVersion.py, tests/terraform/checks/resource/azure/test_AppServicePythonVersion.py
=> fix(terraform): Ensure APPService default action is to ignore not fail

checkov/cloudformation/runner.py, tests/cloudformation/runner/resources/suppress_graph_check.yaml, tests/cloudformation/runner/test_runner.py, tests/cloudformation/test_graph_manager.py
=> feat(cloudformation): support inline suppression of CFN graph checks

checkov/terraform/checks/resource/azure/VMAgentIsInstalled.py, tests/terraform/checks/resource/azure/example_VMAgentIsInstalled/main.tf, tests/terraform/checks/resource/azure/test_VMAgentIsInstalled.py
=> fix(terraform): False negative for CKV_AZURE_179

checkov/terraform/checks/resource/azure/WinVMAutomaticUpdates.py, tests/terraform/checks/resource/azure/example_WinVMAutomaticUpdates/main.tf, tests/terraform/checks/resource/azure/test_WinVMAutomaticUpdates.py
=> fix(terraform): default case should pass for auto updates

checkov/terraform/graph_builder/foreach/module_handler.py
=> fix(terraform): Only update config if len is bigger than 0

checkov/main.py, tests/secrets/git_history/test_utils.py, tests/secrets/test_secret_git_history.py
=> chore(secrets): add more tests for partial vs full runs

checkov/terraform/plan_runner.py, tests/terraform/runner/test_plan_runner.py
=> fix(terraform_plan): Handled TFDefinitionKey in plan runner as well

checkov/common/output/ai.py
=> fix(general): catch unexpected errors when querying OpenAI

checkov/common/util/decorators.py
=> fix(secrets): fix error if writing to file when don't have access

checkov/secrets/git_history_store.py
=> fix(secrets): fix None in file name

checkov/terraform/graph_builder/foreach/module_handler.py
=> fix(terraform): fix foreach count is none bug

checkov/secrets/git_history_store.py, checkov/secrets/git_types.py, checkov/secrets/runner.py, checkov/secrets/scan_git_history.py
=> feat(secrets): add more files to ignore list in git history

checkov/terraform/graph_builder/foreach/builder.py, checkov/terraform/graph_builder/foreach/module_handler.py, checkov/terraform/graph_builder/local_graph.py, tests/terraform/graph/variable_rendering/test_foreach_renderer.py
=> fix(terraform): Fix for_each flow conditions

checkov/common/images/image_referencer.py
=> fix(general): fix wrong abs path in IR record

checkov/secrets/scan_git_history.py, tests/secrets/git_history/test_utils.py, tests/secrets/test_secret_git_history.py
=> fix(secrets): timeout in unix to work with signals

docs/7.Scan Examples/Git History.md
=> docs(secrets): Add readme file for Git History

checkov/secrets/scan_git_history.py, tests/secrets/git_history/test_utils.py
Reverts bridgecrewio/checkov#4920
=> fix(secrets): Revert timeout in unix to work with signals

checkov/common/bridgecrew/integration_features/features/policies_3d_integration.py, checkov/common/output/report.py, checkov/policies_3d/checks_infra/base_check.py, checkov/policies_3d/checks_infra/base_parser.py, checkov/policies_3d/checks_parser.py, checkov/policies_3d/record.py, checkov/policies_3d/runner.py, checkov/policies_3d/syntax/cves_syntax.py, checkov/policies_3d/syntax/iac_syntax.py, checkov/policies_3d/syntax/secrets_syntax.py, checkov/policies_3d/syntax/syntax.py, checkov/sca_image/models.py, tests/policies_3d/conftest.py, tests/policies_3d/syntax/cves_syntax/test_cves_syntax.py, tests/policies_3d/syntax/iac_syntax/test_iac_syntax.py, tests/policies_3d/syntax/test_predicament.py, tests/policies_3d/test_parser.py, tests/policies_3d/test_runner.py
=> feat(general): 3D policies syntax refactor

docs/7.Scan Examples/Bitbucket.md
https://github.com/bridgecrewio/checkov/blob/main/checkov/bitbucket/dal.py#L27
[//]: # "
Additionally a scope is needs to be added to the prefix, which indicates the targeted …
=> docs(bitbucket): Update Bitbucket documentation to match the code.

checkov/terraform/graph_builder/local_graph.py, checkov/terraform/graph_builder/utils.py
=> feat(terraform): Used generator instead of list comprehension to improve performance for large graphs

tests/secrets/git_history/test_utils.py, tests/secrets/test_secret_git_history.py
=> chore(secrets): another test

checkov/common/output/csv.py, checkov/common/output/cyclonedx.py, checkov/common/sca/commons.py, tests/sca_image/outputs/results_cyclonedx.xml, tests/sca_package/outputs/results_cyclonedx.xml, tests/sca_package/outputs/results_cyclonedx_with_comma_in_licenses.xml, tests/sca_package_2/outputs/results_cyclonedx.xml
=> feat(sca): fix extract fix version in sbom report

checkov/terraform/checks/graph_checks/aws/S3BucketLifecycle.yaml, tests/terraform/graph/checks/resources/S3BucketLifecycle/expected.yaml, tests/terraform/graph/checks/resources/S3BucketLifecycle/main.tf
=> fix(terraform): support TF provider v3 for lifecycle existence check

checkov/terraform/graph_builder/local_graph.py, tests/terraform/runner/test_runner.py
=> feat(terraform): remove cross varaibles bad list comprehension

checkov/secrets/runner.py
=> fix(secrets): change default value of secret values to empty strings

checkov/terraform/graph_builder/local_graph.py
=> fix(terraform): Added a condition to not override source module object for old parser

checkov/common/bridgecrew/integration_features/features/repo_config_integration.py
=> fix(general): log all returned enforcement rules for debugging

docs/7.Scan Examples/Terraform.md
=> docs(terraform): fix docs formatting

checkov/gitlab_ci/common/resource_id_utils.py, tests/gitlab_ci/resources/two/.gitlab-ci.yml
=> fix(gitlab): fix resource id parsing recursive

setup.py
=> chore: remove tests from package

tests/secrets/test_plugin_multiline_json.py, tests/secrets/test_plugin_multiline_yml.py
=> chore: improve multiline test

checkov/terraform/graph_builder/foreach/abstract_handler.py, checkov/terraform/graph_builder/foreach/module_handler.py
=> feat(terraform): remove redundant foreach deepcopy

Pipfile, Pipfile.lock, setup.py
=> chore: update pycep to version 0.4.0

.github/exclude-patterns.txt
=> chore: exclude test file from secrets check

checkov/common/output/secrets_record.py
=> fix(secrets): change color of invalid secret message

checkov/terraform/graph_builder/local_graph.py, checkov/terraform/graph_builder/utils.py, checkov/terraform/graph_builder/variable_rendering/renderer.py
=> fix(terraform): improve attribute performance

checkov/main.py
=> feat(secrets): open the feature - scan git history

.github/workflows/build.yml
=> chore: trigger bridgecrew-py update

checkov/secrets/runner.py
=> fix(secrets): add filter for suppressed custom secret checks

checkov/common/util/data_structures_utils.py
=> fix(terraform): Handle entity context for for_each resources

checkov/secrets/scan_git_history.py
=> fix(secrets): add handling of unicode error

checkov/arm/checks/resource/SQLServerEmailAlertsToAdminsEnabled.py, tests/arm/checks/resource/example_SQLServerEmailAlertsToAdminsEnabled/sqlServerEmailAlertsToAdminsEnabled-PASSED.json
=> fix(arm): enabled is not true

checkov/common/runners/base_runner.py, checkov/common/runners/object_runner.py, checkov/main.py
=> feat(general): include missing files in save repository

README.md, SECURITY.md, docs/4.Integrations/Kubernetes.md, docs/6.Contribution/Contribution Overview.md, kubernetes/README.md
=> docs(general): Fix some links

checkov/common/bridgecrew/wrapper.py
=> feat(terraform): Added caller_file_path and caller_file_line_range to reduced report

checkov/terraform/checks/resource/aws/NeptuneClusterEncryptedWithCMK.py, tests/terraform/checks/resource/aws/example_NeptuneClusterEncryptedWithCMK/main.tf, tests/terraform/checks/resource/aws/test_NeptuneClusterEncryptedWithCMK.py
=> feat(terraform): Ensure Neptune cluster is encrypted with a CMK CKV_AWS_347

docs/3.Custom Policies/Python Custom Policies.md
=> docs(general): update Python custom checks docs

checkov/terraform/checks/resource/aws/IAMUserRootAccessKeys.py, tests/terraform/checks/resource/aws/example_IAMUserRootAccessKeys/main.tf, tests/terraform/checks/resource/aws/test_IAMUserRootAccessKeys.py
=> feat(terraform): AWS IAM don't generate root credentials 348

checkov/terraform/checks/resource/aws/SQSQueueEncryption.py, tests/terraform/checks/resource/aws/example_SQSQueueEncryption/main.tf, tests/terraform/checks/resource/aws/test_SQSQueueEncryption.py
=> fix(terraform): fix SQS encryption check CKV_AWS_27

checkov/secrets/git_history_store.py
=> fix(secrets): omit the code line

.github/checkov.yaml, .github/workflows/security.yaml, tests/bicep/image_referencer/provider/test_azure.py, tests/bicep/image_referencer/resources/azure/batch.bicep, tests/bicep/image_referencer/test_manager.py, tests/bicep/image_referencer/test_runner_azure_resources.py, tests/cloudformation/checks/resource/aws/example_EC2Credentials/EC2Credentials-FAILED.yaml, tests/cloudformation/checks/resource/aws/example_LambdaEnvironmentCredentials/FAIL.yaml, tests/cloudformation/checks/resource/aws/test_IAMPolicyAttachedToGroupOrRoles.py, tests/terraform/checks/resource/aws/test_DLMEventsCrossRegionEncryptionWithCMK.py, tests/terraform/checks/resource/aws/test_DLMScheduleCrossRegionEncryption.py, tests/terraform/checks/resource/aws/test_DLMScheduleCrossRegionEncryptionWithCMK.py, tests/terraform/checks/resource/aws/test_EBSVolumeEncryptedWithCMK.py, tests/terraform/checks/resource/aws/test_ECSClusterLoggingEncryptedWithCMK.py, tests/terraform/checks/resource/aws/test_FSXOpenZFSFileSystemEncryptedWithCMK.py, tests/terraform/checks/resource/aws/test_FSXWindowsFSEncryptedWithCMK.py, tests/terraform/checks/resource/aws/test_ImagebuilderDistributionConfigurationEncryptedWithCMK.py, tests/terraform/checks/resource/aws/test_LustreFSEncryptedWithCMK.py
=> chore: add skip comments to test secrets

checkov/terraform/runner.py
=> fix(terraform): skip invalid multiple modules names

checkov/dockerfile/runner.py, checkov/dockerfile/utils.py, docs/2.Basics/Suppressing and Skipping Policies.md, tests/dockerfile/resources/expose_port/skip/Dockerfile, tests/dockerfile/test_runner.py, tests/dockerfile/test_utils.py
=> feat(dockerfile): Support docker graph check skips

checkov/secrets/runner.py
=> feat(secrets): add jwt detector to the secret runner

Pipfile.lock, checkov/dockerfile/checks/UpdateNotAlone.py, tests/dockerfile/checks/example_UpdateNotAlone/success/Dockerfile
=> fix(dockerfile): improve update searching in CKV_DOCKER_5

checkov/common/bridgecrew/platform_integration.py, checkov/dockerfile/checks/ReferenceLatestTag.py, checkov/dockerfile/image_referencer/provider.py, tests/dockerfile/checks/test_ReferenceLatestTag.py, tests/dockerfile/image_referencer/test_manager.py, tests/dockerfile/image_referencer/test_provider.py
=> feat(sca): dockerfile image-referencer fixes

checkov/terraform/checks/graph_checks/aws/SGAttachedToResource.yaml, tests/terraform/graph/checks/resources/SGAttachedToResource/expected.yaml, tests/terraform/graph/checks/resources/SGAttachedToResource/main.tf
=> feat(terraform): extend CKV2_AWS_5 with new resources

checkov/terraform/checks/resource/aws/EMRClusterIsEncryptedKMS.py, checkov/terraform/checks/resource/oci/AbsSecurityListUnrestrictedIngress.py, checkov/terraform/checks/resource/oci/SecurityListIngressStateless.py, tests/terraform/checks/resource/oci/test_SecurityListIngressStateless.py, tests/terraform/checks/resource/oci/test_SecurityListIngressStatelessListSyntax.py
=> fix(terraform): Should use UNKNOWN rather than skipped

checkov/terraform/graph_builder/local_graph.py
=> feat(terraform): foreach remove error from info log.

checkov/common/sca/commons.py, checkov/common/sca/output.py, tests/common/output/test_cyclonedx_report.py
adding validation for the file_line_number
=> feat(sca): adding validation for the file_line_number

checkov/terraform/checks/data/aws/ResourcePolicyDocument.py, checkov/terraform/checks/resource/aws/IAMStarResourcePolicyDocument.py, checkov/terraform/checks/resource/base_cloudsplaining_resource_iam_check.py, tests/terraform/checks/data/aws/example_ResourcePolicyDocument/main.tf, tests/terraform/checks/data/aws/test_ResourcePolicyDocument.py, tests/terraform/checks/resource/aws/example_IAMStarResourcePolicyDocument/main.tf, tests/terraform/checks/resource/aws/test_IAMStarResourcePolicyDocument.py, tests/terraform/runner/test_plan_runner.py
=> fix(terraform): exclude unrestrictable actions in CKV_AWS_355 and CKV_AWS_356

tests/terraform/checks/resource/aws/test_IAMStarResourcePolicyDocument.py
=> chore: fix IAM star test for real

checkov/cloudformation/context_parser.py
=> fix(cloudformation): fix evaluate_default_refs func in cfn

checkov/ansible/runner.py, checkov/ansible/utils.py, checkov/common/runners/object_runner.py, tests/ansible/examples/skip.yml, tests/ansible/test_runner.py, tests/ansible/test_utils.py
=> feat(ansible): add support of inline suppression for Ansible graph checks

checkov/terraform/checks/resource/azure/AzureFirewallDefinesPolicy.py, tests/terraform/checks/resource/azure/example_AzureFirewallDefinesPolicy/main.tf, tests/terraform/checks/resource/azure/test_AzureFirewallDefinesPolicy.py
=> feat(terraform): Ensure firewall defines a policy

checkov/terraform/checks/resource/azure/AzureFirewallPolicyIDPSDeny.py, tests/terraform/checks/resource/azure/example_AzureFirewallPolicyIDPSDeny/main.tf, tests/terraform/checks/resource/azure/test_AzureFirewallPolicyIDPSDeny.py
=> feat(terraform): Ensure Firewall policy has IDPS mode as deny

checkov/common/util/parser_utils.py, checkov/terraform/graph_builder/foreach/abstract_handler.py, checkov/terraform/graph_builder/foreach/module_handler.py, checkov/terraform/graph_builder/graph_components/blocks.py, checkov/terraform/graph_builder/graph_components/generic_resource_encryption.py, checkov/terraform/graph_builder/graph_components/module.py, checkov/terraform/graph_builder/graph_to_tf_definitions.py, checkov/terraform/graph_builder/utils.py, mypy.ini
=> chore: enable mypy for part of terraform.graph_builder

checkov/common/runners/runner_registry.py
=> fix(general): Check that the result is not None before extracting vars in cli multiprocess runs

checkov/common/util/var_utils.py, tests/terraform/checks/test_base_resource_check.py
=> feat(terraform): Mark unresolved tf function calls as unresolved

checkov/cloudformation/checks/resource/aws/KMSKeyWildCardPrincipal.py, checkov/cloudformation/checks/resource/base_resource_value_check.py, tests/cloudformation/checks/resource/aws/example_KMSKeyWildCardPrincipal/KMSKeyWildCardPrincipal-FAILED-AWS-Wildcard.yaml, tests/cloudformation/checks/resource/aws/example_KMSKeyWildCardPrincipal/KMSKeyWildCardPrincipal-FAILED-Wildcard.yaml, tests/cloudformation/checks/resource/aws/example_KMSKeyWildCardPrincipal/KMSKeyWildCardPrincipal-PASSED.yaml, tests/cloudformation/checks/resource/aws/test_KMSKeyWildCardPrincipal.py
=> fix(cloudformation): fix CKV_AWS_33 to consider deny statements

docs/4.Integrations/pre-commit.md
=> docs(general): Update pre-commit.md

Pipfile, Pipfile.lock, setup.py
=> chore: update pycep-parser to 4.1.0

checkov/terraform/graph_builder/local_graph.py, checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py, checkov/terraform/graph_builder/variable_rendering/renderer.py, mypy.ini
=> chore: add type hints to terraform.graph_builder.variable_rendering

checkov/common/parallelizer/parallel_runner.py
This PR removes a log from the common/parallel_runner so it doesn't spam the logs
=> feat(general): remove log from parallel common

checkov/common/models/consts.py
=> platform(general): add composer files to supported package files

.github/workflows/build.yml
=> feat(dockerfile): add ARM build for K8s container image

checkov/common/sca/output.py, tests/sca_package_2/test_output.py
=> feat(sca): add fix code and command to cve report

checkov/common/sca/output.py, tests/sca_package_2/test_output.py
=> feat(sca): fix code block array structure 

checkov/terraform/checks/resource/aws/MQBrokerVersion.py, checkov/terraform/checks/resource/base_resource_value_check.py, checkov/terraform/context_parsers/base_parser.py, checkov/terraform/evaluation/base_variable_evaluation.py, checkov/terraform/graph_builder/foreach/abstract_handler.py, checkov/terraform/graph_builder/graph_components/blocks.py, checkov/terraform/graph_builder/utils.py, checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py, checkov/terraform/graph_builder/variable_rendering/safe_eval_functions.py, checkov/terraform/module_loading/loaders/git_loader.py, checkov/terraform/module_loading/loaders/local_path_loader.py, checkov/terraform/module_loading/module_finder.py, checkov/terraform/modules/module_utils.py
=> chore: performance improvements in Terraform graph creation

checkov/common/sca/output.py, tests/sca_package_2/test_output.py
=> feat(sca): add fix command and code for indirect deps

checkov/openapi/checks/resource/generic/NoMaximumNumberItems.py, tests/openapi/checks/resource/generic/example_NoMaximumNumberItems/fail.json, tests/openapi/checks/resource/generic/example_NoMaximumNumberItems/fail.yaml, tests/openapi/checks/resource/generic/example_NoMaximumNumberItems/fail2.json, tests/openapi/checks/resource/generic/example_NoMaximumNumberItems/fail2.yaml, tests/openapi/checks/resource/generic/example_NoMaximumNumberItems/fail3.json, tests/openapi/checks/resource/generic/example_NoMaximumNumberItems/fail3.yaml, tests/openapi/checks/resource/generic/example_NoMaximumNumberItems/pass.json, tests/openapi/checks/resource/generic/example_NoMaximumNumberItems/pass.yaml, tests/openapi/checks/resource/generic/example_NoMaximumNumberItems/pass2.json, tests/openapi/checks/resource/generic/example_NoMaximumNumberItems/pass2.yaml, tests/openapi/checks/resource/generic/example_NoMaximumNumberItems/pass3.json, tests/openapi/checks/resource/generic/example_NoMaximumNumberItems/pass3.yaml, tests/openapi/checks/resource/generic/test_NoMaximumNumberItems.py
=> feat(openapi): Add CKV_OPENAPI_21

checkov/ansible/utils.py, checkov/argo_workflows/runner.py, checkov/circleci_pipelines/checks/ReverseShellNetcat.py, checkov/cloudformation/checks/resource/base_resource_value_check.py, checkov/cloudformation/graph_builder/utils.py, checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py, checkov/common/util/dockerfile.py, checkov/dockerfile/checks/ReferenceLatestTag.py, checkov/dockerfile/checks/UpdateNotAlone.py, checkov/github/base_github_configuration_check.py, checkov/github/checks/webhooks_https_orgs.py, checkov/github/checks/webhooks_https_repos.py, checkov/kubernetes/checks/resource/k8s/ApiServerRequestTimeout.py, checkov/kubernetes/checks/resource/k8s/ApiServerServiceAccountKeyFile.py, checkov/kubernetes/checks/resource/k8s/NginxIngressCVE202125742Lua.py
=> chore: small improvements related to regex

checkov/yaml_doc/base_registry.py, tests/gitlab_ci/resources/rules/.gitlab-ci.yml, tests/gitlab_ci/test_runner.py
=> fix(general): fix inline suppression collection inside lists

checkov/common/util/parser_utils.py
=> fix(terraform): fix get module name - foreach or count

checkov/common/sca/output.py, tests/sca_package_2/conftest.py, tests/sca_package_2/test_output.py
=> feat(sca): fix package line numbers

checkov/common/models/consts.py
=> feat(sca): support composer.json

checkov/terraform/checks/graph_checks/aws/EIPAllocatedToVPCAttachedEC2.yaml, tests/terraform/graph/checks/resources/EIPAllocatedToVPCAttachedEC2/expected.yaml, tests/terraform/graph/checks/resources/EIPAllocatedToVPCAttachedEC2/main.tf
=> fix(terraform): consider new domain attribute in CKV2_AWS_19

checkov/terraform/runner.py, tests/terraform/runner/test_runner.py
=> fix(terraform): add TFDefinitionKey to get_entity_context_and_evaluations

Pipfile, Pipfile.lock, setup.py
=> chore: update bc-detect-secrets version to 1.4.30

dangerfile.ts
=> chore: Danger rule logs fix

checkov/arm/checks/resource/SQLServerAuditingRetention90Days.py
=> fix(arm): improve CKV_AZURE_24 check

Pipfile, Pipfile.lock, checkov/common/output/spdx.py, setup.py, tests/common/output/test_spdx.py
=> feat(sca): update spdx-tools dep to version 0.8.0 and lower bound it

checkov/terraform/runner.py
=> fix(terraform): ensure TFModule is created properly in definition context

checkov/terraform/checks/resource/aws/EKSPlatformVersion.py
I added the 1.27 EKS version to the eks platform version check
=> chore(terraform): Add 1.27 EKS Version

checkov/arm/base_resource_value_check.py, checkov/arm/checks/resource/AzureInstanceExtensions.py, tests/arm/checks/resource/example_AzureInstanceExtensions/fail.json, tests/arm/checks/resource/example_AzureInstanceExtensions/fail2.json, tests/arm/checks/resource/example_AzureInstanceExtensions/pass.json, tests/arm/checks/resource/test_AzureInstanceExtensions.py, tests/terraform/checks/resource/azure/example_AzureInstanceExtensions/main.tf
=> feat(arm): migrate check CKV_AZURE_50 to arm

checkov/dockerfile/checks/ReferenceLatestTag.py, tests/dockerfile/checks/example_ReferenceLatestTag/success_multi_stage_platform/Dockerfile, tests/dockerfile/checks/test_ReferenceLatestTag.py
=> fix(dockerfile): consider platform flag in CKV_DOCKER_7

checkov/arm/checks/resource/AppServiceEnableFailedRequest.py, tests/arm/checks/resource/example_AppServiceEnabledFailedRequest/AppServiceEnableFailedRequest-failed.json, tests/arm/checks/resource/example_AppServiceEnabledFailedRequest/AppServiceEnableFailedRequest-passed.json, tests/arm/checks/resource/test_AppServiceEnabledFailedRequest.py
=> feat(arm): CKV_AZURE_66 implement config logging check for arm

checkov/arm/checks/resource/AppServiceDetailedErrorMessagesEnabled.py, tests/arm/checks/resource/example_AppServiceDetailedErrorMessagesEnabled/AppServiceDetailedErrorMessagesEnabled-failed.json, tests/arm/checks/resource/example_AppServiceDetailedErrorMessagesEnabled/AppServiceDetailedErrorMessagesEnabled-failed2.json, tests/arm/checks/resource/example_AppServiceDetailedErrorMessagesEnabled/AppServiceDetailedErrorMessagesEnabled-passed.json, tests/arm/checks/resource/test_AppServiceDetailedErrorMessagesEnabled.py
=> feat(arm): convert CKV_AZURE_65 to arm

checkov/arm/checks/resource/AppServiceDotnetFrameworkVersion.py, checkov/terraform/checks/resource/azure/AppServiceDotnetFrameworkVersion.py, tests/arm/checks/resource/example_AppServiceDotnetFrameworkVersion/failed.json, tests/arm/checks/resource/example_AppServiceDotnetFrameworkVersion/passed.json, tests/arm/checks/resource/test_AppServiceDotnetFrameworkVersion.py, tests/terraform/checks/resource/azure/example_AppServiceDotnetFrameworkVersion/main.tf, tests/terraform/checks/resource/azure/test_AppServiceDotnetFrameworkVersion.py
=> feat(arm): implement CKV_AZURE_80 in arm

checkov/arm/checks/resource/KeyVaultEnablesFirewallRulesSettings.py, tests/arm/checks/resource/example_KeyVaultEnablesFirewallRulesSettings/KeyVaultEnablesFirewallRulesSettings-FAILED.json, tests/arm/checks/resource/example_KeyVaultEnablesFirewallRulesSettings/KeyVaultEnablesFirewallRulesSettings-PASSED.json, tests/arm/checks/resource/test_KeyVaultEnablesFirewallRulesSettings.py
=> feat(arm): Implement CKV_AZURE_109 in arm

checkov/arm/checks/resource/WinVMEncryptionAtHost.py, tests/arm/checks/resource/example_WinVMEncryptionAtHost/failed.json, tests/arm/checks/resource/example_WinVMEncryptionAtHost/passed.json, tests/arm/checks/resource/test_WinVMEncryptionAtHost.py
=> feat(arm): implement CKV_AZURE_151 for arm

checkov/arm/checks/resource/PostgreSQLEncryptionEnabled.py, tests/arm/checks/resource/example_PostgreSQLEncryptionEnabled/fail.json, tests/arm/checks/resource/example_PostgreSQLEncryptionEnabled/pass.json, tests/arm/checks/resource/test_PostgreSQLEncryptionEnabled.py
=> feat(arm): implement CKV_AZURE_130 for arm

checkov/arm/checks/resource/SecretContentType.py, tests/arm/checks/resource/example_SecretContentType/SecretExpirationDate-FAILED.json, tests/arm/checks/resource/example_SecretContentType/SecretExpirationDate-PASSED.json, tests/arm/checks/resource/test_SecretContentType.py
=> feat(arm): implement CKV_AZURE_114 for arm

checkov/arm/graph_manager.py, checkov/arm/parser/parser.py, checkov/arm/runner.py, checkov/arm/utils.py, dogfood_tests/test_checkov_dogfood.py, tests/arm/graph_builder/test_local_graph.py, tests/arm/parser/examples/json/with_comments.json, tests/arm/parser/test_parser.py, tests/arm/test_graph_manager.py, tests/arm/test_utils.py
=> fix(arm): correctly handle json files with comments and output parsing errors

checkov/terraform/runner.py
=> fix(terraform): fix error type

checkov/arm/checks/resource/KeyBackedByHSM.py, tests/arm/checks/resource/example_KeyBackedByHSM/fail.json, tests/arm/checks/resource/example_KeyBackedByHSM/pass.json, tests/arm/checks/resource/test_KeyBackedByHSM.py
=> feat(arm): implement CKV_AZURE_112 for arm

checkov/arm/checks/resource/MySQLGeoBackupEnabled.py, tests/arm/checks/resource/example_MySQLGeoBackupEnabled/fail.json, tests/arm/checks/resource/example_MySQLGeoBackupEnabled/pass.json, tests/arm/checks/resource/test_MySQLGeoBackupEnabled.py
=> feat(arm): implement CKV_AZURE_94 for arm

checkov/arm/checks/resource/SynapseWorkspaceEnablesManagedVirtualNetworks.py, tests/arm/checks/resource/example_SynapseWorkspaceEnablesManagedVirtualNetworks/fail.json, tests/arm/checks/resource/example_SynapseWorkspaceEnablesManagedVirtualNetworks/pass.json, tests/arm/checks/resource/test_SynapseWorkspaceEnablesManagedVirtualNetworks.py
=> feat(arm): implement CKV_AZURE_58 for ARM

checkov/arm/checks/resource/KeyExpirationDate.py, tests/arm/checks/resource/example_KeyExpirationDate/fail.json, tests/arm/checks/resource/example_KeyExpirationDate/pass.json, tests/arm/checks/resource/test_KeyExpirationDate.py
=> feat(arm): implement CKV_AZURE_40 for ARM

checkov/helm/runner.py
=> fix(helm): Changed error message to failure to better differentiate problems

Pipfile.lock, README.md
=> chore: update dependencies and fix pypi download badge

checkov/arm/checks/resource/SQLServerHasPublicAccessDisabled.py, tests/arm/checks/resource/example_SQLServerHasPublicAccessDisabled/fail.json, tests/arm/checks/resource/example_SQLServerHasPublicAccessDisabled/pass.json, tests/arm/checks/resource/test_SQLServerHasPublicAccessDisabled.py
=> feat(arm): implement CKV_AZURE_113 for ARM

checkov/arm/checks/resource/APIServicesUseVirtualNetwork.py, tests/arm/checks/resource/example_APIServicesUseVirtualNetwork/fail.json, tests/arm/checks/resource/example_APIServicesUseVirtualNetwork/pass.json, tests/arm/checks/resource/test_APIServicesUseVirtualNetwork.py
=> feat(arm): implement CKV_AZURE_107 for arm

checkov/arm/checks/resource/CognitiveServicesDisablesPublicNetwork.py, tests/arm/checks/resource/example_CognitiveServicesDisablesPublicNetwork/fail.json, tests/arm/checks/resource/example_CognitiveServicesDisablesPublicNetwork/fail2.json, tests/arm/checks/resource/example_CognitiveServicesDisablesPublicNetwork/pass.json, tests/arm/checks/resource/test_CognitiveServicesDisablesPublicNetwork.py
=> feat(arm): implement CKV_AZURE_134 for ARM

checkov/arm/checks/resource/NSGRuleHTTPAccessRestricted.py, tests/arm/checks/resource/example_NSGRuleHTTPAccessRestricted/NSGRulePortAccessRestricted-FAILED.json, tests/arm/checks/resource/example_NSGRuleHTTPAccessRestricted/NSGRulePortAccessRestricted-RULE-1Pass-1Fail.json, tests/arm/checks/resource/example_NSGRuleHTTPAccessRestricted/NSGRulePortAccessRestricted-RULE-PASSED.json, tests/arm/checks/resource/test_NSGRuleHTTPAccessRestricted.py
=> feat(arm): implement CKV_AZURE_160 for arm

checkov/arm/checks/resource/RedisCachePublicNetworkAccessEnabled.py, tests/arm/checks/resource/example_RedisCachePublicNetworkAccessEnabled/fail.json, tests/arm/checks/resource/example_RedisCachePublicNetworkAccessEnabled/fail2.json, tests/arm/checks/resource/example_RedisCachePublicNetworkAccessEnabled/pass.json, tests/arm/checks/resource/test_RedisCachePublicNetworkAccessEnabled.py
=> feat(arm): implement CKV_AZURE_89 for ARM

checkov/arm/base_resource_value_check.py, checkov/arm/checks/resource/KeyVaultEnablesSoftDelete.py, tests/arm/checks/resource/example_KeyVaultEnablesSoftDelete/fail.json, tests/arm/checks/resource/example_KeyVaultEnablesSoftDelete/pass.json, tests/arm/checks/resource/example_KeyVaultEnablesSoftDelete/pass2.json, tests/arm/checks/resource/test_KeyVaultEnablesSoftDelete.py
=> feat(arm): Implement CKV_AZURE_111 in ARM

checkov/terraform/checks/resource/aws/NeptuneDBClustersIAMDatabaseAuthenticationEnabled.py, tests/terraform/checks/resource/aws/example_NeptuneDBClustersIAMDatabaseAuthenticationEnabled/NeptuneDBClustersIAMDatabaseAuthenticationEnabled.tf, tests/terraform/checks/resource/aws/test_NeptuneDBClustersIAMDatabaseAuthenticationEnabled.py
…tion enabled
see
Neptune DB clusters should have IAM database authentication enabled
https://docs.aws.amazon.com/securityhub/latest/userguide/neptune-controls.html#neptune-7
=> feat(terraform): add check for Neptune DB clusters  IAM database auth enabled

checkov/terraform/graph_builder/graph_components/module.py
=> fix(terraform): Fix external_modules_source_map serialization

checkov/terraform/graph_builder/graph_components/module.py
=> fix(terraform): Module from_dict func to static func

checkov/common/runners/runner_registry.py
=> fix(general): fix print to encode in windows

checkov/arm/checks/resource/VMDisablePasswordAuthentication.py, tests/arm/checks/resource/example_VMDisablePasswordAuthentication/failed-vm.json, tests/arm/checks/resource/example_VMDisablePasswordAuthentication/failed.json, tests/arm/checks/resource/example_VMDisablePasswordAuthentication/passed-vm.json, tests/arm/checks/resource/example_VMDisablePasswordAuthentication/passed.json, tests/arm/checks/resource/test_VMDisablePasswordAuthentication.py
=> feat(arm): implement CKV_AZURE_149 for ARM

checkov/cloudformation/checks/resource/aws/IMDSv1Disabled.py, checkov/terraform/checks/resource/aws/IMDSv1Disabled.py
=> feat(terraform): simply IMDSv2 checks

checkov/main.py
=> fix(terraform): fix upload resource_subgraph_maps

tests/common/checks/test_graph_check_loading.py
=> chore: fix graph loading test

checkov/main.py
=> fix(dockerfile): fix Docker image scan

checkov/terraform/plan_parser.py
=> fix(terraform_plan): add azurerm_portal_dashboard to jsonify list

checkov/common/graph/db_connectors/rustworkx/rustworkx_db_connector.py
=> feat(general): Added source and target to edge data

checkov/terraform/checks/resource/azure/AKSEncryptionAtHostEnabled.py, checkov/terraform/checks/resource/azure/AKSEphemeralOSDisks.py, tests/terraform/checks/resource/azure/example_AKSEncryptionAtHostEnabled/main.tf, tests/terraform/checks/resource/azure/example_AKSEphemeralOSDisks/main.tf, tests/terraform/checks/resource/azure/test_AKSEncryptionAtHostEnabled.py
Fixes #5611 
For CKV_AZURE_226: 
For CKV_AZURE_227:
=> fix(terraform): Fixing issues with checks CKV_AZURE_226 & CKV_AZURE_227

Pipfile, Pipfile.lock, setup.py
=> chore(general): Bump pydantic version

checkov/arm/checks/resource/MySQLEncryptionEnabled.py, checkov/runner_filter.py
=> chore: fix test

checkov/sast/prisma_models/report.py, checkov/sast/report.py, tests/common/integration_features/test_vulnerabilities_integration.py, tests/sast/test_report.py
=> fix(sast): add cveid to reachability report

.github/workflows/nightly.yml, checkov.spec
=> chore: fix pyinstaller executable and add simple test

Pipfile, Pipfile.lock, checkov/common/checks_infra/solvers/connections_solvers/base_connection_solver.py, checkov/common/checks_infra/solvers/connections_solvers/connection_exists_solver.py, checkov/common/graph/db_connectors/rustworkx/rustworkx_db_connector.py, checkov/common/graph/graph_builder/local_graph.py, checkov/common/images/graph/image_referencer_provider.py, checkov/common/sca/output.py, checkov/common/typing.py, checkov/terraform/graph_builder/local_graph.py, checkov/terraform/tf_parser.py, setup.py, tests/sca_image/outputs/results_cyclonedx.xml, tests/sca_package/outputs/results_cyclonedx.xml, tests/sca_package/outputs/results_cyclonedx_with_comma_in_licenses.xml, tests/sca_package_2/outputs/results_cyclonedx.xml, tests/sca_package_2/outputs/results_cyclonedx_with_comma_in_licenses.xml
- Automatic update of bc-python-hcl2
=> chore: update bc-python-hcl2 version to 0.4.1

checkov/terraform/checks/resource/aws/KeyspacesTableUsesCMK.py, tests/terraform/checks/resource/aws/example_KeyspacesTableUsesCMK/main.tf
=> fix(terraform): fix valid value for aws keyspaces_table encryption_specification type

checkov/common/bridgecrew/platform_integration.py, checkov/sast/runner.py, checkov/sca_package_2/runner.py
=> chore: separate S3 client creation

checkov/terraform/checks/resource/azure/ACREnableZoneRedundancy.py, tests/terraform/checks/resource/azure/example_ACREnableZoneRedundancy/main.tf, tests/terraform/checks/resource/azure/test_ACREnableZoneRedundancy.py
=> feat(terraform): Ensure ACR is zone-redundant

checkov/common/bridgecrew/integration_features/features/policy_metadata_integration.py
load terraform registry checks when using terraform plan
=> fix(terraform_plan): load terraform registry checks when using terraform plan

.github/workflows/pr-test.yml, checkov/terraform/graph_builder/local_graph.py, tests/github_actions/test_runner.py
=> chore: backport - TF plan resources connection fix (#5767)

checkov/common/bridgecrew/integration_features/features/vulnerabilities_integration.py
*  Using alias data from assets.json for giving Package Used indication for aliased packages
*
=> feat(sca): Using alias data from assets.json for giving Package Used indication for aliased packages

checkov/terraform/graph_builder/graph_components/blocks.py
=> fix(terraform): Fixed to_dict of terraform block regarding source_module_object

checkov/sca_package_2/scanner.py
=> fix(sca): Update the log level of specific logs

checkov/common/bridgecrew/platform_integration.py, sast_integration_tests/prepare_data.sh, sast_integration_tests/run_integration_tests.sh, sast_integration_tests/test_checkov_sast_report.py
=> feat(sast): add integration test platform report

sast_integration_tests/run_integration_tests.sh
=> fix(sast): add save local sast report to run integration script

.github/workflows/pr-test.yml
Reverts bridgecrewio/checkov#5859
=> chore(general): Revert - Redefine fail-fast

checkov/terraform/plan_runner.py, tests/terraform/runner/py_check_tf_plan/check_tf_plan.py, tests/terraform/runner/resources/py_graph_check_tf_plan/py_graph_check_paln.json, tests/terraform/runner/test_plan_runner.py
=> feat(terraform_plan): Add PY graph checks for tf plan

checkov/common/typing.py, checkov/sast/engines/prisma_engine.py, checkov/sast/record.py
=> feat(sast): add dataflow to checkov report from sast

checkov/sast/prisma_models/report.py
=> fix(sast): add missing field in MatchMetadata

checkov/cdk/report.py, checkov/common/bridgecrew/platform_integration.py
=> fix(sast): persist empty sast report for cdk

.github/workflows/pr-test.yml, checkov/common/bridgecrew/platform_integration.py, checkov/main.py
=> fix(general): temporary disable runtime config

checkov/common/bridgecrew/platform_integration.py, checkov/main.py
=> fix(sast): fix relative paths in sast cdk reports

checkov/terraform/tf_parser.py
=> fix(terraform): Improved bad performance pathlib check

checkov/common/sast/report_types.py
=> fix(sast): Fix serialize for sast report with taint mode

checkov/common/bridgecrew/platform_integration.py
=> fix(sast): change the path for taint mode match

checkov/common/bridgecrew/integration_features/features/repo_config_integration.py
=> platform(general): handle weaknesses rename

setup.py
=> feat(sast): Add policies to executable

checkov/common/output/report.py, checkov/sast/engines/prisma_engine.py
=> fix(sast): replaced TBD with owasp and removed "sast engine"

checkov/common/output/report.py, checkov/common/runners/runner_registry.py, checkov/sast/report.py
=> fix(sast): summarize errors

.github/workflows/build.yml, .github/workflows/pr-test.yml, checkov/common/typing.py
=> chore(general): fix prisma url

cdk_integration_tests/run_integration_tests.sh, integration_tests/test_checkov_cli_integration_report.py, sast_integration_tests/run_integration_tests.sh
=> chore: set sast+cdk integration tests prisma env variables

checkov/common/bridgecrew/vulnerability_scanning/image_scanner.py
=> chore: Add logs into get_scan_results_from_cache_async

checkov/common/output/record.py, checkov/sast/record.py, tests/sast/test_report.py
=> feat(sast): add dataflow to output

.github/checkov.yaml, .github/exclude-patterns.txt, cdk_integration_tests/utils.py
=> chore(general): fix cdk suppressed checks

checkov/common/sast/report_types.py, dangerfile.ts
=> feat(sast): add danger rule

checkov/common/bridgecrew/platform_integration.py, checkov/common/util/http_utils.py
=> feat(general): Implement authentication retry mechanism 

checkov/common/bridgecrew/platform_integration.py, checkov/common/bridgecrew/wrapper.py, checkov/common/sast/consts.py, checkov/sast/checks_infra/base_registry.py, checkov/sast/engines/prisma_engine.py, checkov/sast/runner.py
=> fix(sast): fix cdk checks path

checkov/terraform/checks/resource/aws/EKSPlatformVersion.py
=> fix(terraform): Add k8s 1.29 to CKV_AWS_339

checkov/common/bridgecrew/integration_features/features/fixes_integration.py, checkov/common/bridgecrew/platform_integration.py
=> chore(general): support custom headers in platform integration

cdk_integration_tests/run_integration_tests.sh
=> chore(sast): remove empty set for env vars 

checkov/terraform/checks/resource/azure/StorageAccountDisablePublicAccess.py, checkov/terraform/checks/resource/azure/StorageBlobRestrictPublicAccess.py
=> fix(terraform): Changed a couple of checks from negative to positive check, behavior is the same

checkov/common/runners/runner_registry.py, checkov/runner_filter.py
=> fix(sast): do not log warning when using skip framework

checkov/common/bridgecrew/platform_integration.py
=> fix(sast): add attribute verification

checkov/terraform/graph_builder/local_graph.py
=> fix(terraform): prevent side effects when updating variable rendering

tests/terraform/image_referencer/resources/gcp/cloudbuild.tf
=> fix(secrets): ignore secret check in test file

checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
=> fix(sca): Fix suppression integration crashing if licenseTypes is missing

checkov/common/bridgecrew/platform_integration.py
=> chore(general): support uploading scan results to jakarta

checkov/sast/engines/prisma_engine.py, tests/sast/test_report.py
save suppress_comment for sast inline suppressions in the report
=> fix(sast): save suppress_comment for sast inline suppressions

checkov/common/sca/output.py, tests/common/sca/test_output.py, tests/sca_image/conftest.py, tests/sca_image/test_runner.py
=> feat(sca): using the new api license/get-licenses-violations instead of packages/get-licenses-violations (which is deprecated)

cdk_integration_tests/src/typescript/ElasticsearchEncryption/fail.ts, cdk_integration_tests/src/typescript/ElasticsearchEncryption/fail2.ts, cdk_integration_tests/src/typescript/ElasticsearchEncryption/pass.ts, cdk_integration_tests/src/typescript/ElasticsearchNodeToNodeEncryption/fail.ts, cdk_integration_tests/src/typescript/ElasticsearchNodeToNodeEncryption/fail2.ts, cdk_integration_tests/src/typescript/ElasticsearchNodeToNodeEncryption/pass.ts, cdk_integration_tests/src/typescript/GlueDataCatalogEncryption/fail.ts, cdk_integration_tests/src/typescript/GlueDataCatalogEncryption/fail2.ts, cdk_integration_tests/src/typescript/GlueDataCatalogEncryption/pass.ts, cdk_integration_tests/src/typescript/GlueSecurityConfiguration/fail.ts, cdk_integration_tests/src/typescript/GlueSecurityConfiguration/fail2.ts, cdk_integration_tests/src/typescript/GlueSecurityConfiguration/pass.ts, cdk_integration_tests/src/typescript/GlueSecurityConfigurationEnabled/fail.ts, cdk_integration_tests/src/typescript/GlueSecurityConfigurationEnabled/fail2.ts, cdk_integration_tests/src/typescript/GlueSecurityConfigurationEnabled/pass.ts, checkov/cdk/checks/typescript/ElasticsearchEncryption.yaml, checkov/cdk/checks/typescript/ElasticsearchNodeToNodeEncryption.yaml, checkov/cdk/checks/typescript/GlueDataCatalogEncryption.yaml, checkov/cdk/checks/typescript/GlueSecurityConfiguration.yaml, checkov/cdk/checks/typescript/GlueSecurityConfigurationEnabled.yaml
=> feat(sast): Add 5 cdk for TS

checkov/common/bridgecrew/platform_integration.py
=> fix(sast): fix skipped_checks paths before upload to the platform

checkov/common/bridgecrew/integration_features/features/policy_metadata_integration.py
=> feat(sca): support licenses custom policies enforcement rules

checkov/bicep/checks/graph_checks/SQLServerAuditingRetention90Days.yaml, tests/bicep/graph/checks/resources/SQLServerAuditingRetention90Days/expected.yaml, tests/bicep/graph/checks/resources/SQLServerAuditingRetention90Days/fail1_less_90.bicep, tests/bicep/graph/checks/resources/SQLServerAuditingRetention90Days/fail2_no_auditsettings.bicep, tests/bicep/graph/checks/resources/SQLServerAuditingRetention90Days/fail3_not_enabled.bicep, tests/bicep/graph/checks/resources/SQLServerAuditingRetention90Days/pass1.bicep, tests/bicep/graph/checks/test_yaml_policies.py
=> feat(bicep): Add bicep version of policy

cdk_integration_tests/src/typescript/APIGatewayAuthorization/fail.ts, cdk_integration_tests/src/typescript/APIGatewayAuthorization/fail__2__.ts, cdk_integration_tests/src/typescript/APIGatewayAuthorization/pass.ts, cdk_integration_tests/src/typescript/APIGatewayAuthorization/pass__2__.ts, cdk_integration_tests/src/typescript/AppSyncFieldLevelLogs/fail.ts, cdk_integration_tests/src/typescript/AppSyncFieldLevelLogs/pass.ts, cdk_integration_tests/src/typescript/AppSyncLogging/fail.ts, cdk_integration_tests/src/typescript/AppSyncLogging/pass.ts, cdk_integration_tests/src/typescript/AthenaWorkgroupConfiguration/fail.ts, cdk_integration_tests/src/typescript/AthenaWorkgroupConfiguration/fail__2__.ts, cdk_integration_tests/src/typescript/AthenaWorkgroupConfiguration/pass.ts, cdk_integration_tests/src/typescript/CloudFrontTLS12/fail.ts, cdk_integration_tests/src/typescript/CloudFrontTLS12/pass.ts, cdk_integration_tests/test_checks_typescript.py, checkov/cdk/checks/python/AppSyncFieldLevelLogs.yaml, checkov/cdk/checks/typescript/APIGatewayAuthorization.yaml, checkov/cdk/checks/typescript/AppSyncFieldLevelLogs.yaml, checkov/cdk/checks/typescript/AppSyncLogging.yaml, checkov/cdk/checks/typescript/AthenaWorkgroupConfiguration.yaml, checkov/cdk/checks/typescript/CloudFrontTLS12.yaml
=> feat(sast): TypeScript cdk policies p7

checkov/common/checks_infra/solvers/attribute_solvers/range_includes_attribute_solver.py, tests/terraform/graph/checks_infra/attribute_solvers/range_includes_solver/JsonPathRangeIncludesList.yaml, tests/terraform/graph/checks_infra/attribute_solvers/range_includes_solver/RangeIncludesList.yaml, tests/terraform/graph/checks_infra/attribute_solvers/range_includes_solver/resources/main.tf, tests/terraform/graph/checks_infra/attribute_solvers/range_includes_solver/test_solver.py, tests/terraform/graph/checks_infra/attribute_solvers/range_not_includes_solver/JsonPathRangeNotIncludesList.yaml, tests/terraform/graph/checks_infra/attribute_solvers/range_not_includes_solver/RangeNotIncludesList.yaml, tests/terraform/graph/checks_infra/attribute_solvers/range_not_includes_solver/resources/main.tf, tests/terraform/graph/checks_infra/attribute_solvers/range_not_includes_solver/test_solver.py
=> feat(general): Update range includes to handle lists of ranges and lists of values

.flake8, .github/workflows/pr-test.yml
=> fix(general): fix integration tests

checkov/terraform/plan_parser.py, tests/terraform/parser/test_plan_parser.py
=> feat(terraform): support provider in tf_plan graph

checkov/arm/checks/resource/StorageAccountMinimumTlsVersion.py
=> chore(azure): updating arm StorageAccountMinimumTlsVersion ckv_id to CKV_AZURE_44

checkov/ansible/utils.py, tests/ansible/test_utils.py
=> platform(ansible): add create_definitions function for ansible framework

.github/workflows/build.yml, tests/github_actions/test_runner.py
=> fix(general): fix integration test in build

dangerfile.ts, integration_tests/test_checkov_cli_integration_report.py
=> fix(general): add print to random test

.github/workflows/build.yml
=> chore(general): run bump version after all integrations tests

.github/workflows/pr-test.yml, cdk_integration_tests/prepare_data.sh, cdk_integration_tests/run_integration_tests.sh, cdk_integration_tests/utils.py, checkov/common/sast/consts.py, checkov/sast/runner.py
=> feat(sast): run all cdk integration test

checkov/ansible/runner.py
=> fix(ansible): fix ansible definitions raw type

checkov/secrets/runner.py
=> fix(secrets): secret_filter_block_list filter by file name and suffixes

checkov/secrets/runner.py
=> fix(secrets): secret_filter_block_list filter by file name and suffixes 2

tests/sast/test_filter_files_manager.py
=> fix(sast): fix random test sast js

checkov/ansible/graph_builder/local_graph.py, checkov/common/runners/object_runner.py
=> fix(ansible): fix ansible resource id in local graph

checkov/secrets/runner.py
=> fix(secrets): fix entropy type

Pipfile, Pipfile.lock, setup.py
Bump detect-secrets to the latest
=> feat(secrets): Bump detect-secrets

.github/workflows/pr-test.yml, cdk_integration_tests/run_integration_tests.sh, checkov/sast/runner.py
=> chore(sast): remove the need of ENABLE_SAST_TYPESCRIPT

checkov/terraform/graph_builder/variable_rendering/renderer.py, checkov/terraform/tf_parser.py, tests/terraform/checks/resource/azure/example_AppGWDefinesSecureProtocols/main.tf, tests/terraform/checks/resource/azure/example_AppGWDefinesSecureProtocols/terraform.auto.tfvars, tests/terraform/checks/resource/azure/example_AppGWDefinesSecureProtocols/variables.tf, tests/terraform/checks/resource/azure/test_AppGWDefinesSecureProtocols.py
=> fix(terraform): Fix an issue for loading tfvars + issue in the dynamic rendering

checkov/cloudformation/checks/graph_checks/SageMakerIAMPolicyOverlyPermissiveToAllTraffic.yaml, checkov/terraform/checks/graph_checks/aws/SageMakerIAMPolicyOverlyPermissiveToAllTraffic.yaml, tests/cloudformation/graph/checks/resources/SageMakerIAMPolicyOverlyPermissiveToAllTraffic/expected.yaml, tests/cloudformation/graph/checks/resources/SageMakerIAMPolicyOverlyPermissiveToAllTraffic/template.yaml, tests/cloudformation/graph/checks/test_yaml_policies.py, tests/terraform/graph/checks/resources/SageMakerIAMPolicyOverlyPermissiveToAllTraffic/expected.yaml, tests/terraform/graph/checks/resources/SageMakerIAMPolicyOverlyPermissiveToAllTraffic/main.tf, tests/terraform/graph/checks/test_yaml_policies.py, tests/terraform/runner/test_runner.py
Added the CKV2_AWS_68 Check for TF and CFN - `SageMakerIAMPolicyOverlyPermissiveToAllTraffic`
=> feat(terraform): Added the CKV2_AWS_68 Check for TF and CFN

checkov/terraform/checks/resource/aws/S3AllowsAnyPrincipal.py, tests/terraform/checks/resource/aws/example_S3AllowsAnyPrincipal/main.tf, tests/terraform/checks/resource/aws/test_S3AllowsAnyPrincipal.py
=> feat(terraform): Add more conditions to CKV_AWS_70

checkov/ansible/graph_builder/local_graph.py, tests/ansible/test_graph_manager.py
=> fix(ansible): set task as ansible vertices config

checkov/arm/checks/resource/CognitiveServicesEnableLocalAuth.py, checkov/terraform/checks/resource/azure/CognitiveServicesEnableLocalAuth.py, tests/arm/checks/resource/example_CognitiveServicesEnableLocalAuth/fail.json, tests/arm/checks/resource/example_CognitiveServicesEnableLocalAuth/fail2.json, tests/arm/checks/resource/example_CognitiveServicesEnableLocalAuth/pass.json, tests/arm/checks/resource/example_CognitiveServicesEnableLocalAuth/pass2.json, tests/arm/checks/resource/test_CognitiveServicesEnableLocalAuth.py, tests/terraform/checks/resource/azure/example_CognitiveServicesEnableLocalAuth/main.tf, tests/terraform/checks/resource/azure/test_CognitiveServicesEnableLocalAuth.py
=> feat(terraform): Ensure that Cognitive Services accounts enable local authentication - new check

checkov/cloudformation/checks/resource/aws/SagemakerNotebookEncryptedWithCMK.py, checkov/terraform/checks/resource/aws/SagemakerDomainEncryptedWithCMK.py, tests/cloudformation/checks/resource/aws/example_SagemakerNotebookEncryptedWithCMK/template.yaml, tests/cloudformation/checks/resource/aws/test_SagemakerNotebookEncryptedWithCMK.py, tests/terraform/checks/resource/aws/example_SagemakerDomainEncryptedWithCMK/aws_sagemaker_notebook_instance.tf, tests/terraform/checks/resource/aws/test_SagemakerDomainEncryptedWithCMK.py
=> feat(terraform): AWS SageMaker notebook instance KMS Key

checkov/cloudformation/checks/resource/aws/SagemakerDataQualityJobDefinitionEncryption.py, checkov/cloudformation/checks/resource/aws/SagemakerDataQualityJobDefinitionTrafficEncryption.py, checkov/cloudformation/checks/resource/aws/SagemakerDataQualityJobDefinitionVolumeEncryption.py, checkov/terraform/checks/resource/aws/SagemakerDataQualityJobDefinitionEncryption.py, checkov/terraform/checks/resource/aws/SagemakerDataQualityJobDefinitionTrafficEncryption.py, checkov/terraform/checks/resource/aws/SagemakerDataQualityJobDefinitionVolumeEncryption.py, tests/cloudformation/checks/resource/aws/example_SagemakerDataQualityJobDefinitionEncryption/SagemakerDataQualityJobDefinitionEncryption-FAILED.yaml, tests/cloudformation/checks/resource/aws/example_SagemakerDataQualityJobDefinitionEncryption/SagemakerDataQualityJobDefinitionEncryption-PASSED.yaml, tests/cloudformation/checks/resource/aws/example_SagemakerDataQualityJobDefinitionTrafficEncryption/SagemakerDataQualityJobDefinitionTrafficEncryption-FAILED.yaml, tests/cloudformation/checks/resource/aws/example_SagemakerDataQualityJobDefinitionTrafficEncryption/SagemakerDataQualityJobDefinitionTrafficEncryption-PASSED.yaml, tests/cloudformation/checks/resource/aws/example_SagemakerDataQualityJobDefinitionVolumeEncryption/SagemakerDataQualityJobDefinitionVolumeEncryption-FAILED.yaml, tests/cloudformation/checks/resource/aws/example_SagemakerDataQualityJobDefinitionVolumeEncryption/SagemakerDataQualityJobDefinitionVolumeEncryption-PASSED.yaml, tests/cloudformation/checks/resource/aws/test_SagemakerDataQualityJobDefinitionEncryption.py, tests/cloudformation/checks/resource/aws/test_SagemakerDataQualityJobDefinitionTrafficEncryption.py, tests/cloudformation/checks/resource/aws/test_SagemakerDataQualityJobDefinitionVolumeEncryption.py, tests/terraform/checks/resource/aws/example_SagemakerDataQualityJobDefinitionEncryption/main.tf, tests/terraform/checks/resource/aws/example_SagemakerDataQualityJobDefinitionTrafficEncryption/main.tf, tests/terraform/checks/resource/aws/example_SagemakerDataQualityJobDefinitionVolumeEncryption/main.tf, tests/terraform/checks/resource/aws/test_SagemakerDataQualityJobDefinitionEncryption.py, tests/terraform/checks/resource/aws/test_SagemakerDataQualityJobDefinitionTrafficEncryption.py, tests/terraform/checks/resource/aws/test_SagemakerDataQualityJobDefinitionVolumeEncryption.py
=> feat(terraform): add 6 policies

checkov/sast/runner.py
=> fix(sast): add log for sast on windows

checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py, checkov/common/checks_infra/solvers/attribute_solvers/not_contains_attribute_solver.py, tests/terraform/runner/resources/list_of_routes/list_of_routes.tf, tests/terraform/runner/test_runner.py
This PR fixes the not_contains solver to take into account lists of values so that all values are checked and not any one of them.
Fixes #6333
=> feat(terraform): add fix for not contains solver

checkov/cloudformation/checks/resource/aws/SagemakerModelWithNetworkIsolation.py, checkov/cloudformation/checks/resource/aws/SagemakerNotebookInstanceAllowsIMDSv2.py, checkov/terraform/checks/resource/aws/SagemakerFlowDefinitionUsesKMS.py, checkov/terraform/checks/resource/aws/SagemakerModelWithNetworkIsolation.py, checkov/terraform/checks/resource/aws/SagemakerNotebookInstanceAllowsIMDSv2.py, tests/cloudformation/checks/resource/aws/example_SagemakerModelWithNetworkIsolation/SagemakerModelWithNetworkIsolation-FAILED.yaml, tests/cloudformation/checks/resource/aws/example_SagemakerModelWithNetworkIsolation/SagemakerModelWithNetworkIsolation-PASSED.yaml, tests/cloudformation/checks/resource/aws/example_SagemakerNotebookInstanceAllowsIMDSv2/SagemakerNotebookInstanceAllowsIMDSv2-FAILED.yaml, tests/cloudformation/checks/resource/aws/example_SagemakerNotebookInstanceAllowsIMDSv2/SagemakerNotebookInstanceAllowsIMDSv2-PASSED.yaml, tests/cloudformation/checks/resource/aws/test_SagemakerDataQualityJobDefinitionEncryption.py, tests/cloudformation/checks/resource/aws/test_SagemakerDataQualityJobDefinitionTrafficEncryption.py, tests/cloudformation/checks/resource/aws/test_SagemakerModelWithNetworkIsolation.py, tests/cloudformation/checks/resource/aws/test_SagemakerNotebookInstanceAllowsIMDSv2.py, tests/terraform/checks/resource/aws/example_SagemakerFlowDefinitionUsesKMS/main.tf, tests/terraform/checks/resource/aws/example_SagemakerModelWithNetworkIsolation/main.tf, tests/terraform/checks/resource/aws/example_SagemakerNotebookInstanceAllowsIMDSv2/main.tf, tests/terraform/checks/resource/aws/test_SagemakerFlowDefinitionUsesKMS.py, tests/terraform/checks/resource/aws/test_SagemakerModelWithNetworkIsolation.py, tests/terraform/checks/resource/aws/test_SagemakerNotebookInstanceAllowsIMDSv2.py
=> feat(terraform): add 5 policies

checkov/ansible/graph_builder/local_graph.py
=> fix(ansible): filter conf if its int or float

checkov/github_actions/runner.py
=> fix(general): add try except gihub_action read file

.github/exclude-patterns.txt, checkov/ansible/graph_builder/local_graph.py, tests/arm/checks/resource/example_PostgreSQLServerPublicAccessDisable/fail1.json, tests/arm/checks/resource/example_PostgreSQLServerPublicAccessDisable/fail2.json, tests/arm/checks/resource/example_PostgreSQLServerPublicAccessDisable/pass.json
=> fix(ansible): add dict check in create_tasks_vertices

Pipfile, Pipfile.lock, setup.py
=> chore(secrets): bump detect secrets version

checkov/common/models/enums.py
=> feat(general): add AI_AND_ML to CheckCategories

tests/terraform/graph/resources/modules_edges_tfplan/tfplan.json, tests/terraform/parser/resources/plan_module_with_connected_resources/tfplan.json, tests/terraform/runner/resources/plan_nested_child_modules_with_connections/tfplan.json
=> fix(general): removed references Putin references

docs/4.Integrations/pre-commit.md
=> docs(general): fix pre-commit link

checkov/terraform/checks/resource/azure/KeyVaultDisablesPublicNetworkAccess.py, tests/terraform/checks/resource/azure/example_KeyVaultDisablesPublicNetworkAccess/main.tf, tests/terraform/checks/resource/azure/test_KeyVaultDisablesPublicNetworkAccess.py
This PR fixes ckv_azure_189 by taking into account the subnet ids of network_acls and not only ip rules.
Fixes #6122
=> feat(azure): fix ckv_azure_189 according to docs

.github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
=> docs(general): Note for feature requests

checkov/arm/checks/resource/AppServiceSlotDebugDisabled.py, tests/arm/checks/resource/example_AppServiceSlotDebugDisabled/fail.json, tests/arm/checks/resource/example_AppServiceSlotDebugDisabled/fail2.json, tests/arm/checks/resource/example_AppServiceSlotDebugDisabled/pass.json, tests/arm/checks/resource/example_AppServiceSlotDebugDisabled/pass2.json, tests/arm/checks/resource/test_AppServiceSlotDebugDisabled.py
=> feat(arm): ARM AppServiceSlotDebugDisabled - CKV_AZURE_155

checkov/cloudformation/checks/resource/aws/LambdaServicePermission.py
=> fix(terraform): remove print from CKV_AWS_364

checkov/secrets/runner.py
=> feat(secrets): dont filter secrets

checkov/arm/checks/resource/CognitiveServicesEnableLocalAuth.py, checkov/terraform/checks/resource/azure/CognitiveServicesEnableLocalAuth.py
=> fix(azure): fix description of CKV_AZURE_236

checkov/common/sca/reachability/package_alias_mapping/nodejs/utils.py
=> fix(general): Mypy issues

checkov/common/util/ext_argument_parser.py, docs/3.Custom Policies/Sharing Custom Policies.md
=> docs(general): Add Python note

Pipfile, Pipfile.lock, setup.py
=> feat(general): update detect secrets package

cdk_integration_tests/test_checks_typescript.py, checkov/cdk/checks/typescript/S3BucketEncryption.yaml, checkov/cdk/checks/typescript/S3BucketKMSEncryption.yaml, checkov/cdk/checks/typescript/S3BucketLogging.yaml, checkov/cdk/checks/typescript/S3BucketPublicAccessBlock.yaml
=> fix(sast): fix cdk policies

checkov/secrets/runner.py
=> fix(secrets): small fix for filtering

checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py, tests/common/integration_features/test_custom_policies_integration.py
=> feat(bicep): support bicep custom policy

checkov/secrets/runner.py, tests/secrets/test_vault_secrets.py
=> fix(secrets): filter secrets that have vault: in them

checkov/cloudformation/checks/resource/aws/DocDBAuditLogs.py
=> feat(cloudformation): Update audit_logs valid values

checkov/terraform/graph_builder/variable_rendering/renderer.py, checkov/terraform/plan_parser.py
=> fix(terraform): TFPlan + TF fixes for google_project_iam_policy + google_iam_policy

checkov/arm/checks/resource/AzureDefenderOnKeyVaults.py, tests/arm/checks/resource/example_AzureDefenderOnKeyVaults/fail.json, tests/arm/checks/resource/example_AzureDefenderOnKeyVaults/pass.json, tests/arm/checks/resource/test_AzureDefenderOnKeyVaults.py
=> feat(arm): add CKV_AZURE_87 to ensure that Azure Defender is set to On for Key Vault

README.md, docs/7.Scan Examples/Git History.md, docs/7.Scan Examples/Sca.md
=> docs(general): add --repo-id to relevant examples with API key

checkov/dockerfile/checks/RunUsingAPT.py, tests/dockerfile/checks/example_RunUsingAPT/success3/Dockerfile, tests/dockerfile/checks/test_RunUsingAPT.py
=> fix(dockerfile): Fix edge case with apt in domain

checkov/secrets/runner.py
=> fix(secrets): fix secrets duplication

sast_integration_tests/test_checkov_sast_report.py
=> feat(sast): Verify that all sast policies are parsed correctly

checkov/secrets/runner.py
Reverts bridgecrewio/checkov#6619
=> fix(secrets): fix secrets duplication - Revert

checkov/secrets/runner.py
=> fix(secrets): remove duplications in secrets

checkov/secrets/runner.py
Reverts bridgecrewio/checkov#6648
=> fix(secrets): revert fixing duplications

checkov/secrets/runner.py
Reverts bridgecrewio/checkov#6655
=> fix(secrets): Revert remove dups 

checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py, checkov/common/checks_infra/registry.py, checkov/common/graph/graph_builder/consts.py, tests/common/integration_features/test_custom_policies_integration.py
This reverts commit c2057777b6cb14665d670c2f50faf8f959333de7.
=> fix(general): revert support multiple frameworks in one custom policy

checkov/secrets/runner.py
=> fix(secrets): change logs form info to debug

checkov/secrets/runner.py
=> fix(secrets): add edge case for policy that looks like uuid

.github/workflows/security-shared.yml
=> feat(general): revert packages read permissions

checkov/secrets/runner.py
=> fix(secrets): fix suppression and duplication

checkov/secrets/runner.py
Reverts bridgecrewio/checkov#6701
=> fix(secrets): Revert suppression and duplication

checkov/secrets/runner.py
=> fix(secrets): fix suppressions and duplications

.github/workflows/pr-test.yml
=> chore: Remove redefine from pr-test flow

docs/3.Custom Policies/YAML Custom Policies.md
=> fix(general): Fix operator docs

checkov/ansible/graph_builder/local_graph.py, checkov/ansible/utils.py, tests/ansible/examples/empty_tasks.yml
=> fix(ansible): handle empty tasks

checkov/common/util/env_vars_config.py, checkov/terraform/tf_parser.py, dogfood_tests/test_checkov_dogfood.py, tests/terraform/parser/resources/hcl_timeout/main.tf, tests/terraform/parser/test_parser_internals.py, tests/terraform/runner/resources/hcl_timeout/main.tf, tests/terraform/runner/test_runner.py
=> fix(terraform): Set timeout for parsing Terraform files with hcl2.

Pipfile, Pipfile.lock, checkov/common/bridgecrew/integration_features/features/fixes_integration.py, checkov/common/bridgecrew/wrapper.py, checkov/common/runners/base_runner.py, checkov/secrets/utils.py, setup.py
---
Dear maintainer, below is a concise technical summary of the changes proposed in this PR:
<p>Update the <code>bc-detect-secrets</code> dependency to version 1.5.17 in both <code>Pipfile</code> and <code>setup.py</code> to ensure compatibility and security. Refactor type annotations in <code>fixes_integration.py</code> and …
=> chore(secrets): update detect secrets to 1.5.17

checkov/common/util/env_vars_config.py, checkov/sca_package_2/scanner.py
=> feat(sca): add enableDotnetCpm env var to sca scan request 

.github/workflows/pr-test.yml
=> fix(general): pipenv==2024.0.3

Pipfile, Pipfile.lock, setup.py
=> chore(secrets): bump detect secrets

checkov/secrets/runner.py
=> feat(secrets): Add npm detector

Pipfile, Pipfile.lock, README.md, setup.py
=> chore(general): Modify README and update detect-secrets

checkov/sast/engines/prisma_engine.py
=> fix(sast): filter unsupported policies

checkov/sast/engines/prisma_engine.py
=> fix(general): fixed mypy issue

checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py, checkov/common/graph/graph_builder/graph_components/attribute_names.py, checkov/terraform/graph_builder/graph_components/module.py, tests/terraform/parser/test_module.py
Reverts bridgecrewio/checkov#6830
---
<p>Revert changes related to the <code>resource_type</code> attribute in the Terraform module. This involves removing the <code>wrap_reserved_attributes</code> function and its usage across several files, including <code>base_attribute_solver.py</code>, <code>attribute_names.py</code>, and <code>module.py</code>. The test case <code>test_module_with_resource_type_attribute</code> is also removed from <code>test_module.py</code>. These changes restore the previous state before the feature was introduced.</p>
<table><tr><th>Topic</th><th>Details</th><tr><td><a href=https://baz.co/changes/bridgecrewio/checkov/6843?tool=ast&topic=Attribute+Handling>Attribute Handling</a> …
=> feat(terraform): support resource_type attribute - revert

checkov/helm/runner.py, checkov/kubernetes/runner.py, checkov/kustomize/runner.py, tests/helm/test_runner_image_referencer.py
=> feat(helm): Made helm + kustomize use the Kubernetes graph registry

checkov/secrets/plugins/custom_regex_detector.py, tests/secrets/test_load_detectors.py
=> fix(secrets): add prerun support for singleline

checkov/arm/graph_builder/local_graph.py
=> fix(arm): Change ARM graph creation log lvl to debug

Pipfile, Pipfile.lock, checkov/secrets/scan_git_history.py, setup.py
=> chore(secrets): bump detect secrets 1.5.27

checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
=> feat(general): add logs for suppression

checkov/terraform/checks/graph_checks/azure/AzureSubnetConfigWithNSG.yaml, tests/terraform/graph/checks/resources/AzureSubnetConfigWithNSG/expected.yaml, tests/terraform/graph/checks/resources/AzureSubnetConfigWithNSG/main.tf
=> fix(terraform): Fix CKV2_AZURE_31

checkov/serverless/graph_builder/local_graph.py, tests/arm/checks/resource/example_TestMySQLPublicAccessDisabled/fail2.json, tests/arm/checks/resource/example_TestMySQLPublicAccessDisabled/pass2.json
=> fix(serverless): Fix serverless check crash

.gitignore, checkov/common/util/oidc_utils.py, checkov/terraform/checks/data/aws/GithubActionsOIDCTrustPolicy.py, checkov/terraform/checks/resource/azure/GithubActionsOIDCTrustPolicy.py, checkov/terraform/checks/resource/gcp/GithubActionsOIDCTrustPolicy.py, checkov/terraform/graph_builder/variable_rendering/renderer.py, tests/terraform/checks/data/aws/example_GithubActionsOIDCTrustPolicy/main.tf, tests/terraform/checks/data/aws/test_GithubActionsOIDCTrustPolicy.py, tests/terraform/checks/resource/azure/example_GithubActionsOIDCTrustPolicy/main.tf, tests/terraform/checks/resource/azure/test_GithubActionsOIDCTrustPolicy.py, tests/terraform/checks/resource/gcp/example_GithubActionsOIDCTrustPolicy/main.tf, tests/terraform/checks/resource/gcp/test_GithubActionsOIDCTrustPolicy.py
[//]: # "
ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sast|sca|secrets|serverless|terraform|general …
=> feat(terraform): Update CKV_AWS_358, add CKV_GCP_125 and CKV_AZURE_249 for OIDC claims analysis for GitHub

checkov/sca_package_2/output.py
=> chore(sca): Fix header revert

checkov/terraform/checks/resource/aws/EKSPlatformVersion.py
=> fix(terraform): CKV_AWS_339 - Add EKS platform version 1.32 to allowed lists of versions

checkov/terraform/checks/resource/gcp/CloudSqlMajorVersion.py, tests/terraform/checks/resource/gcp/example_CloudSqlMajorVersion/main.tf
Add latest stable postgres supported version
[//]: # " …
=> fix(terraform): Postgres latest stable version

checkov/secrets/runner.py
=> fix(secrets): ckv_secret_80 filtering fix

Pipfile, Pipfile.lock, setup.py
=> feat(secrets): Bump detect-secrets to remove more lock files

checkov/serverless/runner.py, checkov/serverless/utils.py, tests/serverless/checks/aws/example_S3PublicACLRead/S3PublicACLRead-FAILED/serverless.yml, tests/serverless/checks/aws/example_S3PublicACLRead/S3PublicACLRead-PASSED/serverless.yml, tests/serverless/checks/aws/test_AWSCredentials.py, tests/serverless/checks/aws/test_AdminPolicyDocument.py, tests/serverless/checks/aws/test_S3PublicACLRead.py, tests/serverless/checks/aws/test_StarActionPolicyDocument.py
This PR adds tags enrichment to serverless records. We enrich resources with their tags only, excluding any global tags that might be applied in runtime.
---
<table><tr><th>Topic</th><th>Details</th><tr><td><a href=https://baz.co/changes/bridgecrewio/checkov/7044?tool=ast&topic=Tags+Enrichment>Tags Enrichment</a>
</td><td>Implements tag extraction and parsing for serverless resources<details><summary>Modified files (2)</summary><ul><li>checkov/serverless/utils.py</li>
<li>checkov/serverless/runner.py</li></ul></details><details><summary>Latest Contributors(2)</summary><table><tr><th>User</th><th>Commit</th><th>Date</th></tr><tr><td>omriyoffe-panw</td><td>feat-serverless-Server...</td><td>December 18, 2024</td></tr> …
=> feat(serverless): add tags enrichment to serverless

cdk_integration_tests/src/typescript/AppSyncFieldLevelLogs/pass.ts, checkov/cdk/checks/typescript/AppSyncFieldLevelLogs.yaml
=> fix(sast): Fix CKV_AWS_194 policy

Pipfile, Pipfile.lock, setup.py
=> fix(secrets): Bump detect-secrets to not flag AZ secrets in plan files

checkov/terraform/checks/graph_checks/gcp/GCPComputeFirewallOverlyPermissiveToAllTraffic.yaml, tests/terraform/graph/checks/resources/GCPComputeFirewallOverlyPermissiveToAllTraffic/expected.yaml, tests/terraform/graph/checks/resources/GCPComputeFirewallOverlyPermissiveToAllTraffic/main.tf, tests/terraform/graph/checks/resources/GCPComputeGlobalForwardingRuleCheck/expected.yaml, tests/terraform/graph/checks/resources/GCPComputeGlobalForwardingRuleCheck/main.tf, tests/terraform/graph/checks/resources/GCPComputeRegionalForwardingRuleCheck/expected.yaml, tests/terraform/graph/checks/resources/GCPComputeRegionalForwardingRuleCheck/main.tf, tests/terraform/graph/checks/test_yaml_policies.py
=> fix(terraform): Fix CKV2_GCP_12 and a few tests

README.md, docs/2.Basics/Installing Checkov.md
=> docs(general): Add install for debian

tests/terraform/checks/resource/azure/example_FunctionAppAccessibleOverHttps_tfplan/example_fua_for_fail_ckv_azure_70.tf
=> fix(terraform): rename test FunctionAppsAccessibleOverHttps 

checkov/arm/checks/resource/StorageAccountName.py, checkov/terraform/checks/graph_checks/aws/Route53ZoneEnableDNSSECSigning.yaml, checkov/terraform/checks/resource/aws/S3AllowsAnyPrincipal.py, tests/arm/checks/resource/example_StorageAccountName/substring.bicep, tests/terraform/checks/resource/aws/example_S3AllowsAnyPrincipal/main.tf, tests/terraform/graph/checks/resources/Route53ZoneEnableDNSSECSigning/expected.yaml, tests/terraform/graph/checks/resources/Route53ZoneEnableDNSSECSigning/main.tf, tests/terraform/graph/checks/test_yaml_policies.py
=> fix(terraform): Fix for multiple checks

checkov/kustomize/runner.py, tests/kustomize/graph/resources/empty_resources/graph_check.yaml, tests/kustomize/graph/resources/empty_resources/kustomization.yaml, tests/kustomize/graph/test_running_graph_checks.py
=> fix(kustomize): handle kustomize file with empty resources section

checkov/kubernetes/checks/graph_checks/ReadAllSecrets.yaml, checkov/terraform/checks/graph_checks/aws/LBWeakCiphers.yaml, tests/kubernetes/graph/checks/resources/ReadAllSecrets/Passing/RoleResourceName.yaml, tests/kubernetes/graph/checks/resources/ReadAllSecrets/expected.yaml, tests/terraform/graph/checks/resources/LBWeakCiphers/expected.yaml, tests/terraform/graph/checks/resources/LBWeakCiphers/main.tf
=> fix(terraform): Fix protocols for CKV2_AWS_74 and fix for CKV2_K8S_5

checkov/secrets/runner.py, checkov/secrets/scan_git_history.py, tests/common/output/test_junit_report.py
=> feat(secrets): git-history allow scan by commits list

checkov/secrets/scan_git_history.py
=> fix(secrets): Fix for git-history scan by commits

checkov/terraform/module_loading/registry.py, tests/terraform/module_loading/test_registry.py
=> fix(general): Fix support for git external module syntax 'git::git@'

CONTRIBUTING.md, checkov/terraform/checks/graph_checks/aws/OpenSearchDomainHasFineGrainedControl.yaml, tests/terraform/graph/checks/resources/OpenSearchDomainHasFineGrainedControl/expected.yaml, tests/terraform/graph/checks/resources/OpenSearchDomainHasFineGrainedControl/main.tf
=> fix(terraform): Multiple fixes

checkov/secrets/runner.py
=> chore(secrets): clean only if not none

checkov/serverless/graph_builder/definition_context.py
=> fix(serverless): check if start and end line in serverless definitions context

checkov/secrets/runner.py
=> chore(secrets): fix githistory relative path

Pipfile, Pipfile.lock, setup.py
=> chore(secrets): Fix dependencies

checkov/secrets/plugins/custom_regex_detector.py, checkov/secrets/runner.py
In case this creates problems, we should revert it and add the following in runner.py:
secret_value = cast(str, sec.secret_value)
if secret_value:
secret_value = secret_value.strip('"\'')  # We should always strip quotes from matches before we search for them in the line (because of this line quoted_mm = f"'{mm}'" in custom_regex_detector.py)
line_text_censored = omit_secret_value_from_line(secret_value, line_text_censored)
instead of:
line_text_censored = omit_secret_value_from_line(cast(str, sec.secret_value), line_text_censored)
[//]: # "
- break:    to indicate a breaking …
=> fix(secrets): fix omit and masking

checkov/secrets/plugins/custom_regex_detector.py, checkov/secrets/runner.py
=> fix(secrets): fix omitting and masking

checkov/helm/runner.py, tests/helm/test_runner.py
=> fix(helm): fix file paths to point to original files and not generated ones

.github/exclude-patterns.txt
=> fix(general): Add exclusion for plan_with_providers test files in security scanning

checkov/common/runners/base_runner.py, checkov/secrets/utils.py, tests/common/runners/test_base_runner.py
Reverts bridgecrewio/checkov#6738
=> Revert "fix(general): escape default ignored directories"
