bridgecrewio/checkov

- checkov/github_actions/checks/job/EmptyWorkflowDispatch.py
- "skip" check CKV_GHA_7, if there is no `workflow_dispatch` to fix the integration test
> fix GHA workflow dispatch check

- checkov/terraform/checks/resource/gcp/GoogleCloudSqlServerNoPublicIP.py
- tests/terraform/checks/resource/gcp/example_CloudSQLServerNoPublicIP/main.tf
- tests/terraform/checks/resource/gcp/test_GoogleCloudSqlServerNoPublicIP.py
Handled an edge case where the `ipv4_enabled` attributes is not parsed in a list, and causes the run to get an exceotion.
`terraform/CKV_GCP_60`
> Handle non-list ipv4_enabled in check GoogleCloudSqlServerNoPublicIP

- checkov/helm/runner.py
Catch UnicodeDecodeError exception when trying to parse helm chart
> Catch UnicodeDecodeError exception when trying to parse helm chart

- checkov/sca_package/runner.py
- tests/sca_package/conftest.py
- tests/sca_package/test_runner.py
* adding the license also for packages without cves
* testing the licenses are added to extra_resource in the sca-package runner
> adding the license also for packages without cves

- checkov/github/schemas/org_security.py
- tests/github/test_dal.py
This PR fixes an issue with checkov github VCS flow.
Github graphql API can return null for some objects (unless they are explicitly defined as non null).
samlIdentityProvider can be null, but since our schema does not take it into account, it fails json validation and ignores the organization. This silent ignore causes this issue to remain hidden.
> change github org schema and add UT

- checkov/kustomize/runner.py
- tests/kustomize/runner/resources/no_type/kustomization.yaml
- tests/kustomize/test_runner.py
Fixing an issue where kustomize runner fails to run when a file type is not determined.
> Safely accessing type of kustomize file

- checkov/common/images/image_referencer.py
- checkov/github_actions/runner.py
- tests/github_actions/test_runner_resource_names.py
Adding correct GHA resource id to Image class
added uts to test that the resource id generated is identical to the resource id generated while running through the checks.
> Pass correct GHA resource id through image details

- checkov/github_actions/checks/job/AllowUnsecureCommandsOnJob.py
This PR fixes an issue with checkov AllowUnsecureCommandsOnJob check. Conf objects can be set with null env, which crashes on access. This fix will prevent that access.
> add check if env var is set on conf with null value

- checkov/kubernetes/checks/resource/k8s/KubeletClientCa.py
- tests/kubernetes/checks/example_KubeletClientCa/KubeletClientCa-FAILED.yaml
- tests/kubernetes/checks/example_KubeletClientCa/KubeletClientCa-PASSED.yaml
- The parameter `--client-ca-file` in the KubeletClientCa.py is not checked, instead `--root-ca-file` is checked. So raising a PR with the correct parameter.
- Kubernetes Check # `CKV_K8S_140`
- `--root-ca-file` to `--client-ca-file`
- Also, updated the examples.
> Update --client-ca-file in KubeletClientCa check (CKV_K8S_140)

- checkov/common/bridgecrew/vulnerability_scanning/image_scanner.py
- checkov/common/sca/output.py
- tests/common/sca/test_output.py
- tests/sca_image/test_runner.py
- instead of raising an exception while trying to interact with our backend for cache hits and licenses, just log it 🙂
> fail license and cache requests silently

- checkov/common/sca/commons.py
- checkov/common/sca/output.py
- tests/common/sca/test_commons.py
- tests/common/sca/test_output.py
* normalize the language name gem to be ruby before performing API call to the platform. as it is what platform expect
* testing the normalization
* testing the full request input
> normalize the language name gem to be ruby

- checkov/github_actions/checks/job/AllowUnsecureCommandsOnJob.py
`env` keyword can also be specified as such
```
env: ${{ matrix.config.env }}
```
which breaks the check since it's parsed as a string
> Fix AllowUnsecureCommandsOnJob check GHA

- checkov/common/output/csv.py
- tests/common/output/test_bom_report.py
This reverts commit 8c48003ae8aa2bbc48d1e5992db883b186478ce4.
[//]: # "
ex.
feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is …
> fix(sca): Revert - Remove commas between licenses in CSV reports (#3391)

- checkov/common/runners/runner_registry.py
CSV BOM report is missing ```git_org``` and ```git_repository``` fields, this PR adds those to the report
> fix: add missing csv bom report fields

- tests/openapi/runner/test_runner.py
temporarily disable test that fails due to multithreading
> fix: temporarily disable test with issues

- checkov/common/runners/runner_registry.py
- tests/common/runner_registry/test_runner_registry.py
CSV BOM report uses account id for ```git_org``` and ```git_repository``` in columns. Some account ids appear to have multiple slashes, which breaks the ```split```  outcome. This fix handle multiple slashes.
> fix: fix git info extraction from account_id in bom report

- checkov/common/output/cyclonedx.py
- tests/common/output/test_cyclonedx_report.py
> feat(general): Add severities to IaC components in CycloneDX report

- checkov/common/runners/object_runner.py
- tests/github_actions/test_runner.py
> fix: Pass empty workflow name as metadata by default

- checkov/common/checks_infra/solvers/attribute_solvers/contains_attribute_solver.py
- tests/terraform/graph/checks_infra/attribute_solvers/contains_solver/NetworkAclsIPs.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/contains_solver/test_solver.py
- tests/terraform/graph/resources/none_contains/main.tf
In case where an attribute value is `null`, the `ContainsAttributeSolver` will attempt to find the value in a `None` attribute, raising an exception.
> fix(terraform): Handle edge case for None attribute value in ContainsAttributeSolver

- checkov/bicep/utils.py
- tests/bicep/test_utils.py
> fix(bicep): only scan files, not folders

- checkov/bicep/runner.py
- checkov/common/runners/runner_registry.py
- checkov/kubernetes/runner.py
- tests/common/output/test_bom_report.py
Files paths for k8s and bicep included absolute path instead of relative path pointing to resources. This PR strips the root folder and leaving only relative paths to the resources.
> fix(general): Fix file paths in k8s and bicep

- checkov/common/bridgecrew/severities.py
- tests/common/test_platform_integration.py
> platform(general): add INFO severity ahead of platform changes

- checkov/common/bridgecrew/wrapper.py
revert dropping metadata field for empty reports since it's causing issues in platform
> platform(general): revert dropping checks metadata for empty reports

- checkov/secrets/runner.py
This PR adds support for injecting custom plugins from the outside. This is part of secret detection capability.
Checkov reads the detector from file and loads it together with its own internal detectors.
> feat: support injection of custom plugins

- checkov/common/checks_infra/checks_parser.py
- tests/common/integration_features/test_custom_policies_integration.py
some custom policies have a single resource in resource-types as an str instead of list and fail the policy loading. this PR forces the resources-types field to be a list
> fix: force list check's resources-types

- README.md
- docs/3.Custom Policies/Python Custom Policies.md
- docs/8.Outputs/JUnit XML.md
> docs(general): adjust example for custom check with guideline

- checkov/common/bridgecrew/platform_integration.py
- checkov/common/util/http_utils.py
- tests/common/utils/test_utils.py
> platform(general): trim API urls

- checkov/cloudformation/parser/__init__.py
- checkov/common/parsers/json/decoder.py
- tests/cloudformation/parser/success_triple_quotes_string.json
- tests/cloudformation/parser/test_cfn_json.py
> feat(cloudformation): json parser support triple quote string

- tests/sca_image/test_output_reports.py
- tests/sca_package/test_output_reports.py
filtering the checkov's version when testing cyclonedx-bom-report - it should be done as it broke the UTs in the "build" action (as checkov's version change each time) and we don't really need to care about the version when testing the entire report
> chore: filtering the checkov's version when testing cyclonedx-bom-report

- checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogCheckpoints.py
- checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogConnection.py
- checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogDisconnection.py
- checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogLockWaits.py
- tests/terraform/checks/resource/gcp/example_CloudPostgreSQLLogDisconnection/main.tf
- tests/terraform/checks/resource/gcp/example_CloudPostgreSqlLogLockWaits/main.tf
- tests/terraform/checks/resource/gcp/example_GoogleCloudPostgreSqlLogCheckpoints/main.tf
- tests/terraform/checks/resource/gcp/example_GoogleCloudPostgreSqlLogConnection/main.tf
- tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogCheckpoints.py
- tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogConnection.py
- tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogDisconnection.py
- tests/terraform/checks/resource/gcp/test_GoogleCloudPostgreSqlLogLockWaits.py
Fix checks when using default (undeclared) settings from GCP.
Fixes #3323 
`CKV_GCP_51`, `CKV_GCP_52`, `CKV_GCP_53` and `CKV_GCP_54`.
When scanning terraform plan with checkov and running infrastructure with something like steampipe, result should match. Here is a list of all available PostgreSQL database flags with their respective default values: https://cloud.google.com/sql/docs/postgres/flags#list-flags-postgres
> fix(terraform): gcp postgresql default values

- checkov/common/models/consts.py
- checkov/common/util/config_utils.py
- checkov/main.py
- checkov/terraform/parser.py
- checkov/terraform/runner.py
- tests/common/utils/test_utils.py
- tests/terraform/runner/test_runner.py
We have been scanning .hcl and .bicep files, but they weren't listed as supported files and .hcl specifically was not scanned.
> fix: Add .hcl and .bicep files to the supported file extensions

- .github/pr-title-checker-config.json
- .github/release-changelog-config.json
- .github/workflows/nightly.yml
- CHANGELOG.md
> chore: change changelog creation to leverage GH releases

- checkov/kubernetes/checks/resource/base_root_container_check.py
- checkov/kubernetes/checks/resource/k8s/DockerSocketVolume.py
- checkov/kubernetes/checks/resource/k8s/PodSecurityContext.py
- checkov/kubernetes/checks/resource/k8s/RootContainers.py
- checkov/kubernetes/checks/resource/k8s/RootContainersHighUID.py
- tests/kubernetes/checks/example_RootContainers/rootContainersFAILED-malformed-spec.yaml
- tests/kubernetes/checks/example_SecurityContexts/pod-container-FAILED_malformed_spec.yaml
- tests/kubernetes/checks/test_ContainerSecurityContext.py
- tests/kubernetes/checks/test_PodSecurityContext.py
- tests/kubernetes/checks/test_RootContainers.py
handled failing checks due to malformed spec objects in k8s template
> fix(kubernetes): Validate k8s spec type

- .flake8
- checkov/arm/parser/cfn_yaml.py
- checkov/bitbucket/runner.py
- checkov/circleci_pipelines/checks/SuspectCurlInScript.py
- checkov/circleci_pipelines/checks/latest_image.py
- checkov/circleci_pipelines/checks/prevent_development_orbs.py
- checkov/circleci_pipelines/checks/prevent_volatile_orbs.py
- checkov/circleci_pipelines/runner.py
- checkov/cloudformation/checks/resource/aws/ALBListenerTLS12.py
- checkov/cloudformation/checks/resource/aws/APIGatewayAuthorization.py
- checkov/cloudformation/checks/resource/aws/AmazonMQBrokerPublicAccess.py
- checkov/cloudformation/checks/resource/aws/EC2PublicIP.py
- checkov/cloudformation/checks/resource/aws/EKSNodeGroupRemoteAccess.py
- checkov/cloudformation/checks/resource/aws/SecurityGroupRuleDescription.py
- checkov/example_runner/checks/base_example_runner_check.py
- checkov/example_runner/checks/job/ExampleCheckTrueFalse.py
- checkov/example_runner/runner.py
- checkov/kubernetes/checks/resource/k8s/AllowPrivilegeEscalationPSP.py
- checkov/kubernetes/checks/resource/k8s/ApiServerAdmissionControlEventRateLimit.py
- checkov/kubernetes/checks/resource/k8s/ApiServerAuthorizationModeNotAlwaysAllow.py
- checkov/kubernetes/checks/resource/k8s/ApiServerAuthorizationModeRBAC.py
- checkov/kubernetes/checks/resource/k8s/WildcardRoles.py
- checkov/kubernetes/runner.py
- checkov/kustomize/runner.py
- checkov/serverless/checks/function/aws/AdminPolicyDocument.py
> chore: enable flake8 for kustomize and add missing type hints

- .github/pr-title-checker-config.json
- checkov/github_actions/checks/job/CosignArtifacts.py
- checkov/github_actions/checks/job/CosignSBOM.py
- tests/github_actions/resources/.github/workflows/nested_jobs.yaml
- tests/github_actions/test_runner.py
Allow GHA checks to gracefully handle bad job definitions.
Also add GHA to the PR title check
> fix(gha): Gracefully handle bad GHA job definitions

- checkov/common/images/image_referencer.py
- checkov/common/sca/commons.py
- checkov/sca_image/runner.py
- checkov/sca_package/runner.py
- tests/sca_image/test_runner.py
- tests/sca_package/test_runner.py
> fix(sca): do not skip the scan if BC_LIC is used with --check

- checkov/terraform/checks/resource/azure/ACRAnonymousPullDisabled.py
- tests/terraform/checks/resource/azure/example_ACRAnonymousPullDisabled/main.tf
- tests/terraform/checks/resource/azure/test_ACRAnonymousPullDisabled.py
ACRAnonymousPullDisabled fails on unexpected data type, this PR handles this case
> fix(arm): unexpected data type in ACRAnonymousPullDisabled

- checkov/common/runners/runner_registry.py
- tests/common/runner_registry/test_runner_registry.py
> fix(general): remove duplicated reports

- checkov/common/output/report.py
- checkov/common/runners/runner_registry.py
- checkov/main.py
- docs/2.Basics/CLI Command Reference.md
> feat(general): add flag for summary position

- checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
- tests/common/integration_features/test_suppressions_integration.py
> fix(sca): skip old CVE suppressions (without 'accountIds')

- checkov/helm/runner.py
- checkov/kubernetes/runner.py
> fix(helm): helm add timeout to dependencies command

- checkov/terraform/checks/resource/alicloud/AbsRDSParameter.py
- tests/terraform/checks/resource/alicloud/example_RDSInstanceLogConnections/main.tf
- tests/terraform/checks/resource/alicloud/example_RDSInstanceLogDisconnections/main.tf
- tests/terraform/checks/resource/alicloud/example_RDSInstanceLogsEnabled/main.tf
- tests/terraform/checks/resource/alicloud/test_RDSInstanceLogConnections.py
- tests/terraform/checks/resource/alicloud/test_RDSInstanceLogDisconnections.py
- tests/terraform/checks/resource/alicloud/test_RDSInstanceLogsEnabled.py
Just made the base class use to lower case.
[//]: # "
ex. …
> fix(terraform):  make test case insensitive for CKV_ALI_35,CKV_ALI_36,CKV_ALI_37

- checkov/common/output/report.py
- tests/common/output/test_sarif_report.py
- tests/sca_image/test_output_reports.py
- tests/sca_package/test_output_reports.py
> feat(general): leverage SARIF helpUri for guideline and SCA link

- checkov/terraform/graph_builder/variable_rendering/renderer.py
- tests/terraform/graph/graph_builder/test_oci_policy.py
- tests/terraform/graph/resources/oci_policies/main.tf
> fix(terraform): do not evaluate OCI policy statements

- checkov/kubernetes/graph_builder/graph_components/K8SEdgeBuilder.py
Added an abstract class for kubernetes edge builder. Concrete edge builders implementations should inherit this base class
> feat(kubernetes): added base class K8SEdgeBuilder

- checkov/common/util/http_utils.py
> fix(sca): send exception log when exceeded retries

- checkov/common/bridgecrew/integration_features/features/fixes_integration.py
- tests/common/integration_features/resources/main.tf
- tests/common/integration_features/test_fixes_integration.py
> fix(general): handle fixes for cloned OOTB policies

- checkov/terraform/checks/resource/aws/APIGatewayAuthorization.py
- tests/terraform/checks/resource/aws/test_APIGatewayAuthorization.py
handle a case where the authorization field is missing in APIGatewayAuthorization check
[//]: # "
Additionally a scope is needs to be added to the prefix, which indicates the targeted …
> fix(terraform): APIGatewayAuthorization check missing authorization

- checkov/kubernetes/checks/resource/k8s/ApiServerProfiling.py
The earlier code was only checking if the `--profiling=true` is not needed.
Optimised `CKV_K8S_90` to check only for `--profiling=false`
> fix(kubernetes): [CKV_K8S_90] Remove unnecessary condition check from ApiServerProfiling.py

- checkov/common/checks_infra/solvers/complex_solvers/base_complex_solver.py
Improve ComplexSolver run time
> feat(general): Improve ComplexSolver run time

- Pipfile
- Pipfile.lock
- setup.py
- tests/secrets/test_runner.py
> fix(secrets): Bump bc-detect-secrets

- checkov/terraform/checks/graph_checks/azure/StorageContainerActivityLogsNotPublic.yaml
- tests/terraform/graph/checks/resources/StorageContainerActivityLogsNotPublic/expected.yaml
- tests/terraform/graph/checks/resources/StorageContainerActivityLogsNotPublic/main.tf
> fix(terraform): fix check CKV2_AZURE_8

- github_action_resources/entrypoint.sh
> fix(general): use current branch name instead of master for the checkov-action 

- checkov/kubernetes/checks/resource/k8s/ApiServerAnonymousAuth.py
The earlier code was only checking if the `--anonymous-auth=true` is not needed.
Optimised `CKV_K8S_68` to check only for `--anonymous-auth=false`
> fix(kubernetes): [CKV_K8S_68] Remove unnecessary condition check from ApiServerAnonymousAuth.py

- checkov/openapi/checks/resource/v2/PathSchemeDefineHTTP.py
- tests/openapi/checks/resource/v2/example_PathSchemeDefineHTTP/fail.json
- tests/openapi/checks/resource/v2/example_PathSchemeDefineHTTP/fail.yaml
- tests/openapi/checks/resource/v2/example_PathSchemeDefineHTTP/pass.json
- tests/openapi/checks/resource/v2/example_PathSchemeDefineHTTP/pass.yaml
- tests/openapi/checks/resource/v2/test_PathSchemeDefineHTTP.py
> feat(openapi): add CKV_OPENAPI_7 to ensure http is not used in path definition

- checkov/terraform/checks/resource/aws/LambdaCodeSigningConfigured.py
- tests/terraform/checks/resource/aws/example_LambdaCodeSigningConfigured/main.tf
- tests/terraform/checks/resource/aws/test_LambdaCodeSigningConfigured.py
> feat(terraform): add CKV_AWS_272 to validate Lambda function code-signing

- checkov/kubernetes/checks/resource/k8s/PeerClientCertAuthTrue.py
- tests/kubernetes/checks/example_PeerClientCertAuthTrue/PeerClientCertAuthTrue-UNKNOWN.yaml
> fix(kubernetes): Handle templates without name for PeerClientCertAuthTrue check

- checkov/main.py
- checkov/runner_filter.py
- checkov/secrets/runner.py
- tests/secrets/test_runner.py
> break(general): switch from black-list to block-list 

- checkov/secrets/plugins/entropy_keyword_combinator.py
- checkov/secrets/runner.py
- tests/secrets/resources/cfn/secret-no-false-positive.yml
- tests/secrets/resources/file_type/test.py
- tests/secrets/test_plugin.py
- tests/secrets/test_runner.py
> fix(secrets): change entropy limit in Combinator plugin

- checkov/terraform/runner.py
- tests/terraform/graph/runner/test_graph_builder.py
fix external module resources ids in the graph report to contain the referrer id (module.[module_name]) as a prefix.
> fix(terraform): fix external modules ids in graph report

- checkov/github/dal.py
- tests/github/test_dal.py
The initialization of the variables in the init of GitHub class is done before the type is set to string (by assigning the "" string). This caused to no checks at all from the GitHub framework (as no repo/account/rtc. are set in the first place)
> fix(github): fix variables initialization

- checkov/common/runners/runner_registry.py
- checkov/main.py
- tests/common/runner_registry/example_bicep_with_empty_resources/playground.bicep
- tests/common/runner_registry/test_runner_registry.py
An enhancement request for removing extra resources (resources without violations) from reports.
This PR allows users running checkov from cli to add argument `--skip-resources-without-violations` that will remove extra resources from output reports
> feat(general): added cli argument for extra resources in report

- checkov/github/schemas/org_security.py
- tests/github/test_dal.py
> fix(github): changed the schema to accept no description for org

- Pipfile
- Pipfile.lock
- setup.py
> chore: update bc-detect-secrets version to 1.3.9

- checkov/common/checks_infra/checks_parser.py
- docs/3.Custom Policies/YAML Custom Policies.md
- tests/terraform/runner/extra_yaml_checks/bucket_versioned_owned.yaml
- tests/terraform/runner/test_runner.py
> feat(graph): add support for guideline field to custom graph checks

- checkov/github/checks/webhooks_https_orgs.py
- checkov/github/checks/webhooks_https_repos.py
- checkov/github/dal.py
- checkov/github/schemas/org_webhooks.py
- checkov/github/schemas/repository_webhooks.py
- checkov/main.py
- docs/6.Contribution/Contribute New GitHub Policies.md
- docs/7.Scan Examples/Github.md
- tests/github/test_dal.py
- tests/github/test_runner.py
Fix of couple bugs in GitHub checks
The bugs:
1. The route for repo under org should be different from that with no org, that is repo under a repo owner.
2. The reply for repo webhooks can be parsed also as an org webhook reply, causing the same webhook to appear under org webhook and repo webhook, which is double in 2 different checks.
3. The github_conf files are created on demand, hence causing leftovers from the previous runs - and mixing check results between different runs.
The fix:
1. Use the `GITHUB_REPO_OWNER` to access webhooks/collaborators for a repo, instead of `GITHUB_ORG`
2. change JSON schema to parse repo webhook reply as only repo webhook reply and same …
> fix(github): bug fixes in CKV_GITHUB_6, CKV_GITHUB_7, CKV_GITHUB_9

- checkov/common/images/image_referencer.py
- checkov/sca_image/runner.py
> feat(sca): Add root path references to shorten file paths in Image Referencer results

- checkov/cloudformation/checks/resource/aws/LaunchConfigurationEBSEncryption.py
Null properties causes the above check to fail because of an unexpected null value for a property, the PR validates the object is not null before parsing it.
No UT for this specific case wasn't added since a CFN YAML with null value is not parsed in checkov (considered as a parsing error)
> fix(cloudformation): Fixed unexpected null properties for LaunchConfigurationEBSEncryption

- checkov/terraform/checks/resource/aws/DBInstanceLogging.py
Handled an unexpected value in DBInstanceLogging check for enabled_cloudwatch_logs_exports.
No UT added for this specific case since I could not reproduce the template that caused this value (empty list).
> fix(terraform): handle unexpected value for enabled_cloudwatch_logs_exports

- checkov/terraform/checks/graph_checks/aws/AutoScallingEnabledELB.yaml
- tests/terraform/graph/checks/resources/AutoScallingEnabledELB/expected.yaml
- tests/terraform/graph/checks/resources/AutoScallingEnabledELB/main.tf
> fix(terraform): extend CKV2_AWS_15 to support aws_lb_target_group

- checkov/kubernetes/checks/resource/k8s/Secrets.py
handled missing field "secretKeyRef" in k8s secrets template.
No UT for this specific case wasn't added since a YAML with null value is not parsed in checkov (considered as a parsing error)
> fix(kubernetes): handled missing field secretKeyRef in template

- .pre-commit-config.yaml
- checkov/kubernetes/checks/resource/base_root_container_check.py
- checkov/kubernetes/checks/resource/k8s/Seccomp.py
handled empty field "spec" in k8s templates.
No UT for this specific case wasn't added since a YAML with null value is not parsed in checkov (considered as a parsing error)
> fix(kubernetes): handled missing key in k8s templates

- .github/pr-title-checker-config.json
- .github/workflows/build.yml
- README.md
- checkov/azure_pipelines/__init__.py
- checkov/azure_pipelines/checks/__init__.py
- checkov/azure_pipelines/checks/base_azure_pipelines_check.py
- checkov/azure_pipelines/checks/job/ContainerDigest.py
- checkov/azure_pipelines/checks/job/ContainerLatestTag.py
- checkov/azure_pipelines/checks/job/SetSecretVariable.py
- checkov/azure_pipelines/checks/job/__init__.py
- checkov/azure_pipelines/checks/registry.py
- checkov/azure_pipelines/runner.py
- checkov/common/bridgecrew/check_type.py
- checkov/common/bridgecrew/code_categories.py
- checkov/common/util/docs_generator.py
- checkov/main.py
- checkov/yaml_doc/base_registry.py
- docs/6.Contribution/Contribute New Azure Pipelines Policies.md
- docs/7.Scan Examples/Argo Workflows.md
- docs/7.Scan Examples/Azure Pipelines.md
- tests/azure_pipelines/checks/jobs/example_ContainerDigest/azure-pipelines.yml
- tests/azure_pipelines/checks/jobs/example_ContainerLatestTag/azure-pipelines.yml
- tests/azure_pipelines/checks/jobs/example_SetSecretVariable/azure-pipelines.yml
- tests/azure_pipelines/checks/jobs/test_ContainerDigest.py
- tests/azure_pipelines/checks/jobs/test_ContainerLatestTag.py
- tests/azure_pipelines/checks/jobs/test_SetSecretVariable.py
- tests/azure_pipelines/examples/azure-pipelines.yml
- tests/azure_pipelines/test_runner.py
- tests/terraform/util/test_doc_generator.py
- tests/test_runner_filter.py
> feat(general): add Azure Pipelines framework

- checkov/kubernetes/checks/resource/base_registry.py
avoid exception when extracting entity type from a k8s template
> fix(kubernetes): minor fix for getting entity type from template

- checkov/argo_workflows/runner.py
- tests/argo_workflows/examples/argo_cd_application.yaml
- tests/argo_workflows/test_runner.py
> fix(argo): only scan Argo Workflows files

- .github/workflows/pr-test.yml
- checkov/kustomize/runner.py
> feat(kustomize): stop kustomize run, if there is nothing to process

- checkov/helm/runner.py
Helm files in checkov report are missing root dir prefix, which is causing issues in producing BOM report
> fix(helm): undo file_abs_path manipulation for helm files

- checkov/terraform/checks/resource/kubernetes/DefaultNamespace.py
- checkov/terraform/checks/resource/kubernetes/DefaultServiceAccount.py
- checkov/terraform/checks/resource/kubernetes/DefaultServiceAccountBinding.py
- checkov/terraform/checks/resource/kubernetes/DockerSocketVolume.py
- checkov/terraform/checks/resource/kubernetes/DropCapabilities.py
- checkov/terraform/checks/resource/kubernetes/HostPort.py
- tests/terraform/checks/resource/kubernetes/example_DefaultNamespace/main.tf
- tests/terraform/checks/resource/kubernetes/example_DefaultServiceAccount/main.tf
- tests/terraform/checks/resource/kubernetes/example_DefaultServiceAccountBinding/main.tf
- tests/terraform/checks/resource/kubernetes/example_DockerSocketVolume/main.tf
- tests/terraform/checks/resource/kubernetes/example_DropCapabilities/main.tf
- tests/terraform/checks/resource/kubernetes/example_HostPort/main.tf
- tests/terraform/checks/resource/kubernetes/example_HostPort/main3.tf
- tests/terraform/checks/resource/kubernetes/test_DefaultNamespace.py
- tests/terraform/checks/resource/kubernetes/test_DefaultServiceAccount.py
- tests/terraform/checks/resource/kubernetes/test_DefaultServiceAccountBinding.py
- tests/terraform/checks/resource/kubernetes/test_DockerSocketVolume.py
- tests/terraform/checks/resource/kubernetes/test_DropCapabilities.py
- tests/terraform/checks/resource/kubernetes/test_HostPort.py
This PR adds add the new resource names to the existing checks. PR 2 of 5.
Fixes #3650
* CKV_K8S_21 
Add resources: kubernetes_pod_v1, kubernetes_deployment_v1, kubernetes_daemon_set_v1, kubernetes_stateful_set_v1, kubernetes_replication_controller_v1, kubernetes_job_v1, kubernetes_cron_job_v1, kubernetes_api_service_v1, kubernetes_secret_v1, kubernetes_service_account_v1, kubernetes_role_binding_v1, kubernetes_config_map_v1, kubernetes_ingress_v1
* CKV_K8S_41
Add resources: kubernetes_service_account_v1
* CKV_K8S_42
Add resources: kubernetes_role_binding_v1, kubernetes_cluster_role_binding_v1
* CKV_K8S_27
Add resources: kubernetes_pod_v1, kubernetes_deployment_v1, …
> feat(terraform): add versioned kubernetes resources to terraform kubernetes checks (2/5)

- checkov/terraform/checks/resource/kubernetes/ImageDigest.py
- checkov/terraform/checks/resource/kubernetes/ImagePullPolicyAlways.py
- checkov/terraform/checks/resource/kubernetes/ImageTagFixed.py
- checkov/terraform/checks/resource/kubernetes/LivenessProbe.py
- checkov/terraform/checks/resource/kubernetes/MemoryLimits.py
- checkov/terraform/checks/resource/kubernetes/MemoryRequests.py
- tests/terraform/checks/resource/kubernetes/example_ImageDigest/main.tf
- tests/terraform/checks/resource/kubernetes/example_ImageDigest/main3.tf
- tests/terraform/checks/resource/kubernetes/example_ImagePullPolicyAlways/main.tf
- tests/terraform/checks/resource/kubernetes/example_ImagePullPolicyAlways/main3.tf
- tests/terraform/checks/resource/kubernetes/example_ImageTagFixed/main.tf
- tests/terraform/checks/resource/kubernetes/example_LivenessProbe/main.tf
- tests/terraform/checks/resource/kubernetes/example_LivenessProbe/main3.tf
- tests/terraform/checks/resource/kubernetes/example_MemoryLimits/main.tf
- tests/terraform/checks/resource/kubernetes/example_MemoryLimits/main2.tf
- tests/terraform/checks/resource/kubernetes/example_MemoryLimits/main3.tf
- tests/terraform/checks/resource/kubernetes/example_MemoryRequests/main.tf
- tests/terraform/checks/resource/kubernetes/example_MemoryRequests/main2.tf
- tests/terraform/checks/resource/kubernetes/example_MemoryRequests/main3.tf
- tests/terraform/checks/resource/kubernetes/test_ImageDigest.py
- tests/terraform/checks/resource/kubernetes/test_ImagePullPolicyAlways.py
- tests/terraform/checks/resource/kubernetes/test_ImageTagFixed.py
- tests/terraform/checks/resource/kubernetes/test_LivenessProbe.py
- tests/terraform/checks/resource/kubernetes/test_MemoryLimits.py
- tests/terraform/checks/resource/kubernetes/test_MemoryRequests.py
This PR adds add the new resource names to the existing checks. PR 3 of 5.
Fixes #3650
* CKV_K8S_43
Add resource: kubernetes_pod_v1
* CKV_K8S_15
Add resource: kubernetes_pod_v1
* CKV_K8S_14
Add resource: kubernetes_pod_v1
* CKV_K8S_8
Add resource: kubernetes_pod_v1
* CKV_K8S_12
Add resource: kubernetes_pod_v1
* CKV_K8S_13
Add resource: kubernetes_pod_v1
> feat(terraform): add versioned kubernetes resources to terraform kubernetes checks (3/5)

- checkov/terraform/checks/resource/kubernetes/MinimiseCapabilities.py
- checkov/terraform/checks/resource/kubernetes/PodSecurityContext.py
- checkov/terraform/checks/resource/kubernetes/PrivilegedContainer.py
- checkov/terraform/checks/resource/kubernetes/ReadinessProbe.py
- checkov/terraform/checks/resource/kubernetes/ReadonlyRootFilesystem.py
- checkov/terraform/checks/resource/kubernetes/Secrets.py
- tests/terraform/checks/resource/kubernetes/example_MinimiseCapabilities/main.tf
- tests/terraform/checks/resource/kubernetes/example_PodSecurityContext/main.tf
- tests/terraform/checks/resource/kubernetes/example_PrivilegedContainers/main.tf
- tests/terraform/checks/resource/kubernetes/example_ReadinessProbe/main.tf
- tests/terraform/checks/resource/kubernetes/example_ReadinessProbe/main3.tf
- tests/terraform/checks/resource/kubernetes/example_ReadonlyRootFilesystem/main.tf
- tests/terraform/checks/resource/kubernetes/example_Secrets/main.tf
- tests/terraform/checks/resource/kubernetes/test_MinimiseCapabilities.py
- tests/terraform/checks/resource/kubernetes/test_PodSecurityContext.py
- tests/terraform/checks/resource/kubernetes/test_PrivilegedContainers.py
- tests/terraform/checks/resource/kubernetes/test_ReadinessProbe.py
- tests/terraform/checks/resource/kubernetes/test_ReadonlyRootFilesystem.py
- tests/terraform/checks/resource/kubernetes/test_Secrets.py
This PR adds add the new resource names to the existing checks. PR 4 of 5.
Fixes #3650
* CKV_K8S_37
Add resource: kubernetes_pod_v1
* CKV_K8S_29
Add resources: kubernetes_pod_v1, kubernetes_deployment_v1, kubernetes_daemon_set_v1
* CKV_K8S_16
Add resource: kubernetes_pod_v1
* CKV_K8S_9
Add resource: kubernetes_pod_v1
* CKV_K8S_22
Add resource: kubernetes_pod_v1
* CKV_K8S_35
Add resource: kubernetes_pod_v1
> feat(terraform): add versioned kubernetes resources to terraform kubernetes checks (4/5)

- checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py
- checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
- checkov/common/bridgecrew/integration_features/integration_feature_registry.py
Let's assume we have an OOTB policy with a suppression rule for it, and a clone of it.
If by any chance Suppression integration is loaded into the list before Custom Policies, the OOTB policy will be suppressed, and then the clone would be as well.
Currently the order ID of these 2 integrations is the same, so we rely on the mercy of the `globs` method to load the files in the right order, in the file `checkov/common/bridgecrew/integration_features/features/__init__.py` 
https://stackoverflow.com/questions/6773584/how-are-glob-globs-return-values-ordered
https://stackoverflow.com/a/6774404
[//]: # "
Be aware that we use the title to create changelog automatically and …
> fix(general): Custom Policies integration must run before Suppresion integration

- checkov/terraform/checks/graph_checks/aws/AppLoadBalancerTLS12.yaml
- tests/terraform/graph/checks/resources/AppLoadBalancerTLS12/expected.yaml
- tests/terraform/graph/checks/resources/AppLoadBalancerTLS12/main.tf
> fix(terraform): Add or condition for TLS 1.3 policy, supporting CKV_AWS_103

- .github/workflows/build.yml
- .github/workflows/nightly.yml
- README.md
> chore: Fix gha deprecations

- checkov/common/vcs/vcs_schema.py
- checkov/gitlab/checks/two_factor_authentication.py
- checkov/gitlab/schemas/groups.py
This PR fixes an issue in vcs gitlab groups retrieval. One part is in schema validation, and the second in the logic of failing checks.
> fix(gitlab): vcs gitlab groups retrieval

- checkov/cloudformation/cfn_utils.py
- checkov/cloudformation/parser/cfn_yaml.py
> fix(terraform): Add debug logs to yaml parsing logic

- github_action_resources/entrypoint.sh
> fix(github): fix GITHUB_OUTPUT and GITHUB_ENV issues of checkov-action

- checkov/common/checks/base_check_registry.py
- checkov/common/runners/object_runner.py
- checkov/gitlab_ci/checks/job/SuspectCurlInScript.py
- checkov/gitlab_ci/common/resource_id_utils.py
- checkov/gitlab_ci/image_referencer/provider.py
- checkov/gitlab_ci/runner.py
- checkov/yaml_doc/base_registry.py
- tests/gitlab_ci/conftest.py
- tests/gitlab_ci/image_referencer/test_gitlab_ci_provider.py
- tests/gitlab_ci/image_referencer/test_manager.py
- tests/gitlab_ci/resources/images/.gitlab-ci.yml
- tests/gitlab_ci/test_resource_names.py
- tests/gitlab_ci/test_runner.py
> fix(gitlab): Modify gitlab ci resource id

- checkov/kubernetes/checks/resource/k8s/CPULimits.py
- checkov/kubernetes/checks/resource/k8s/CPURequests.py
- checkov/kubernetes/checks/resource/k8s/MemoryLimits.py
- checkov/kubernetes/checks/resource/k8s/MemoryRequests.py
- tests/kubernetes/checks/example_Requests_Limits/pod-requests-limits-UNKNOWN.yaml
- tests/kubernetes/checks/test_CPULimits.py
- tests/kubernetes/checks/test_CPURequests.py
handle edge-case of res not a dict
> fix(kubernetes): fix in CPURequests check

- .github/workflows/build.yml
- .github/workflows/pr-test.yml
> chore: pin helm version in GHA to 3.10.1

- checkov/bitbucket/runner.py
- checkov/github/runner.py
- checkov/gitlab/runner.py
- tests/bitbucket/test_runner.py
- tests/github/test_runner.py
- tests/gitlab/test_runner.py
> fix(general): skip scanning VCS configuration if only files are passed in

- checkov/terraform/checks/resource/azure/CosmosDBLocalAuthDisabled.py
- tests/terraform/checks/resource/azure/example_CosmosDBLocalAuthDisabled/CosmosDBLocalAuthDisabled.tf
- tests/terraform/checks/resource/azure/test_CosmosDBLocalAuthDisabled.py
The current check is invalid, only the SQL api of cosmosdb can have this property set, if you try the results on any other type:
`Error: creating Database Account: (Name "pike-cosmos-db" / Resource Group "pike"): creating/updating CosmosDB Account "pike-cosmos-db" (Resource Group "pike"): documentdb.DatabaseAccountsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="DisableLocalAuth is only allowed to be configured for SQL API account.\r\nActivityId: 18c78879-d6e5-465f-90b0-756d721115fa, Microsoft.Azure.Documents.Common/2.14.0"`
Now we check the kind of the db and ignore if not **GlobalDocumentDB**
> fix(terraform): local_authentication_disabled - cosmodb check to look at SQL Api only CKV_AZURE_140

- checkov/terraform/checks/data/aws/IAMManagedAdminPolicy.py
- checkov/terraform/checks/resource/aws/IAMManagedAdminPolicy.py
- tests/terraform/checks/data/aws/example_IAMManagedAdminPolicy/IAMManagedAdminPolicy.tf
- tests/terraform/checks/data/aws/test_IAMManagedAdminPolicy.py
- tests/terraform/checks/resource/aws/example_IAMManagedAdminPolicy/IAMManagedAdminPolicy.tf
- tests/terraform/checks/resource/aws/test_IAMManagedAdminPolicy.py
> feat(terraform): Create checks for aws managed admin policy

- checkov/common/runners/runner_registry.py
> break(github): Change github_failed_only output suffix to .md

- checkov/terraform/checks/resource/base_resource_value_check.py
- checkov/terraform/checks/resource/github/SecretsEncrypted.py
- tests/terraform/checks/resource/azure/test_StorageSyncPublicAccessDisabled.py
- tests/terraform/checks/resource/github/test_SecretsEncrypted.py
- tests/terraform/checks/resource/test_base_resource_value_check.py
> break(terraform): adjust the check result return for dependant variables to unknown in  Python based checks

- docs/4.Integrations/Jenkins.md
> docs(general): Update Jenkins page to use Checkov image

- checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py
- checkov/common/graph/graph_builder/graph_components/blocks.py
- checkov/common/output/report.py
- checkov/terraform/context_parsers/parsers/module_context_parser.py
- checkov/terraform/graph_builder/graph_components/module.py
- checkov/terraform/runner.py
- docs/3.Custom Policies/Examples.md
- tests/terraform/runner/extra_yaml_checks/module_source.yaml
- tests/terraform/runner/resources/module_check/main.tf
- tests/terraform/runner/test_runner.py
> feat(graph): add support for modules in graph checks

- checkov/terraform/checks/graph_checks/aws/S3PublicACLWrite.yaml
- tests/terraform/graph/checks/resources/S3PublicACLWrite/expected.yaml
- tests/terraform/graph/checks/resources/S3PublicACLWrite/main.tf
> fix(terraform): fix false positive for write ACL yaml check

- checkov/terraform/checks/resource/aws/IAMManagedAdminPolicy.py
- tests/terraform/checks/resource/aws/example_IAMManagedAdminPolicy/IAMManagedAdminPolicy.tf
- tests/terraform/checks/resource/aws/test_IAMManagedAdminPolicy.py
> fix(terraform): fix a TF plan issue with CKV_AWS_274

- Pipfile
- Pipfile.lock
- setup.py
> chore: upgrade bc-detect-secrets to 1.3.12

- checkov/arm/parser/__init__.py
- checkov/cloudformation/parser/__init__.py
- checkov/common/parsers/json/__init__.py
- checkov/common/parsers/yaml/loader.py
- checkov/common/parsers/yaml/parser.py
- checkov/json_doc/runner.py
- checkov/openapi/runner.py
- tests/openapi/runner/test_runner.py
> feat(openapi): pre-validate OpenAPI JSON files

- checkov/github/dal.py
This PR splits multiple vcs webhooks into separate files so each one appears as new check violation.
> feat(github): split repo and org webhooks to separate files

- checkov/cloudformation/parser/cfn_yaml.py
- checkov/common/parsers/json/decoder.py
- checkov/common/util/consts.py
- checkov/terraform/context_parsers/tf_plan/__init__.py
- checkov/terraform/graph_builder/local_graph.py
- checkov/terraform/graph_builder/utils.py
- checkov/terraform/plan_parser.py
- tests/terraform/parser/test_plan_parser.py
> fix(terraform): reduce parsing time for large TF plan files

- checkov/terraform/checks/resource/aws/APIGatewayMethodSettingsDataTrace.py
- tests/terraform/checks/resource/aws/example_APIGatewayMethodSettingsDataTrace/main.tf
- tests/terraform/checks/resource/aws/test_APIGatewayMethodSettingsDataTrace.py
> feat(terraform): Add CKV_AWS_276 to ensure that API Gateway Method Settings data_trace_enabled is not set to True

- checkov/common/checks_infra/checks_parser.py
- checkov/common/checks_infra/solvers/attribute_solvers/__init__.py
- checkov/common/checks_infra/solvers/attribute_solvers/range_includes_attribute_solver.py
- checkov/common/checks_infra/solvers/attribute_solvers/range_not_includes_attribute_solver.py
- checkov/common/graph/checks_infra/enums.py
- docs/3.Custom Policies/YAML Custom Policies.md
- tests/terraform/graph/checks_infra/attribute_solvers/range_includes_solver/JsonPathRangeIncludesInt.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/range_includes_solver/JsonPathRangeIncludesString.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/range_includes_solver/RangeIncludesInt.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/range_includes_solver/RangeIncludesString.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/range_includes_solver/resources/main.tf
- tests/terraform/graph/checks_infra/attribute_solvers/range_includes_solver/test_solver.py
- tests/terraform/graph/checks_infra/attribute_solvers/range_not_includes_solver/JsonPathRangeNotIncludesInt.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/range_not_includes_solver/JsonPathRangeNotIncludesString.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/range_not_includes_solver/RangeNotIncludesInt.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/range_not_includes_solver/RangeNotIncludesString.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/range_not_includes_solver/resources/main.tf
- tests/terraform/graph/checks_infra/attribute_solvers/range_not_includes_solver/test_solver.py
> feat(general): add range_includes and inverted operator

- .github/workflows/build.yml
- .github/workflows/pr-test.yml
> chore: remove pip upgrade from GHA which causes issues on Windows + Python 3.11

- checkov/terraform/checks/resource/kubernetes/AllowPrivilegeEscalation.py
- checkov/terraform/checks/resource/kubernetes/AllowedCapabilities.py
- checkov/terraform/checks/resource/kubernetes/AllowedCapabilitiesSysAdmin.py
- checkov/terraform/checks/resource/kubernetes/CPULimits.py
- checkov/terraform/checks/resource/kubernetes/CPURequests.py
- checkov/terraform/checks/resource/kubernetes/ContainerSecurityContext.py
- tests/terraform/checks/resource/kubernetes/example_AllowPrivilegeEscalation/main.tf
- tests/terraform/checks/resource/kubernetes/example_AllowedCapabilities/main.tf
- tests/terraform/checks/resource/kubernetes/example_AllowedCapabilitiesSysAdmin/main.tf
- tests/terraform/checks/resource/kubernetes/example_CPULimits/main.tf
- tests/terraform/checks/resource/kubernetes/example_CPURequests/main.tf
- tests/terraform/checks/resource/kubernetes/example_CPURequests/main2.tf
- tests/terraform/checks/resource/kubernetes/example_CPURequests/main3.tf
- tests/terraform/checks/resource/kubernetes/example_ContainerSecurityContext/main.tf
- tests/terraform/checks/resource/kubernetes/test_AllowPrivilegeEscalation.py
- tests/terraform/checks/resource/kubernetes/test_AllowedCapabilities.py
- tests/terraform/checks/resource/kubernetes/test_AllowedCapabilitiesSysAdmin.py
- tests/terraform/checks/resource/kubernetes/test_CPULimits.py
- tests/terraform/checks/resource/kubernetes/test_CPURequests.py
- tests/terraform/checks/resource/kubernetes/test_ContainerSecurityContext.py
This PR includes pods defined via `kubernetes_deployment` in pod checks . PR 1 of 4.
Fixes #3690
* CKV_K8S_20
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_25
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_39
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_11
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_10
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_30
Add resource: kubernetes_deployment, kubernetes_deployment_v1
> feat(terraform): include pods of kubernetes_deployment in kubernetes_pod checks (1/4)

- checkov/terraform/checks/resource/kubernetes/DropCapabilities.py
- checkov/terraform/checks/resource/kubernetes/HostPort.py
- checkov/terraform/checks/resource/kubernetes/ImageDigest.py
- checkov/terraform/checks/resource/kubernetes/ImagePullPolicyAlways.py
- checkov/terraform/checks/resource/kubernetes/ImageTagFixed.py
- checkov/terraform/checks/resource/kubernetes/LivenessProbe.py
- tests/terraform/checks/resource/kubernetes/example_DropCapabilities/main.tf
- tests/terraform/checks/resource/kubernetes/example_HostPort/main.tf
- tests/terraform/checks/resource/kubernetes/example_ImageDigest/main.tf
- tests/terraform/checks/resource/kubernetes/example_ImagePullPolicyAlways/main.tf
- tests/terraform/checks/resource/kubernetes/example_ImageTagFixed/main.tf
- tests/terraform/checks/resource/kubernetes/example_LivenessProbe/main.tf
- tests/terraform/checks/resource/kubernetes/example_LivenessProbe/main3.tf
- tests/terraform/checks/resource/kubernetes/test_DropCapabilities.py
- tests/terraform/checks/resource/kubernetes/test_HostPort.py
- tests/terraform/checks/resource/kubernetes/test_ImageDigest.py
- tests/terraform/checks/resource/kubernetes/test_ImagePullPolicyAlways.py
- tests/terraform/checks/resource/kubernetes/test_ImageTagFixed.py
- tests/terraform/checks/resource/kubernetes/test_LivenessProbe.py
This PR includes pods defined via `kubernetes_deployment` in pod checks . PR 2 of 4.
Fixes #3690
* CKV_K8S_28
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_26
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_43
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_15
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_14
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_8
Add resource: kubernetes_deployment, kubernetes_deployment_v1
> feat(terraform): include pods of kubernetes_deployment in kubernetes_pod checks (2/4)

- checkov/terraform/checks/resource/kubernetes/MemoryLimits.py
- checkov/terraform/checks/resource/kubernetes/MemoryRequests.py
- checkov/terraform/checks/resource/kubernetes/MinimiseCapabilities.py
- checkov/terraform/checks/resource/kubernetes/PrivilegedContainer.py
- checkov/terraform/checks/resource/kubernetes/ReadinessProbe.py
- checkov/terraform/checks/resource/kubernetes/ReadonlyRootFilesystem.py
- tests/terraform/checks/resource/kubernetes/example_HostPort/main3.tf
- tests/terraform/checks/resource/kubernetes/example_ImageDigest/main3.tf
- tests/terraform/checks/resource/kubernetes/example_ImagePullPolicyAlways/main3.tf
- tests/terraform/checks/resource/kubernetes/example_MemoryLimits/main.tf
- tests/terraform/checks/resource/kubernetes/example_MemoryLimits/main2.tf
- tests/terraform/checks/resource/kubernetes/example_MemoryLimits/main3.tf
- tests/terraform/checks/resource/kubernetes/example_MemoryRequests/main.tf
- tests/terraform/checks/resource/kubernetes/example_MemoryRequests/main2.tf
- tests/terraform/checks/resource/kubernetes/example_MemoryRequests/main3.tf
- tests/terraform/checks/resource/kubernetes/example_MinimiseCapabilities/main.tf
- tests/terraform/checks/resource/kubernetes/example_PrivilegedContainers/main.tf
- tests/terraform/checks/resource/kubernetes/example_ReadinessProbe/main.tf
- tests/terraform/checks/resource/kubernetes/example_ReadinessProbe/main3.tf
- tests/terraform/checks/resource/kubernetes/example_ReadonlyRootFilesystem/main.tf
- tests/terraform/checks/resource/kubernetes/test_MemoryLimits.py
- tests/terraform/checks/resource/kubernetes/test_MemoryRequests.py
- tests/terraform/checks/resource/kubernetes/test_MinimiseCapabilities.py
- tests/terraform/checks/resource/kubernetes/test_PrivilegedContainers.py
- tests/terraform/checks/resource/kubernetes/test_ReadinessProbe.py
- tests/terraform/checks/resource/kubernetes/test_ReadonlyRootFilesystem.py
This PR includes pods defined via `kubernetes_deployment` in pod checks . PR 3 of 4.
Fixes #3690
* CKV_K8S_12
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_13
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_37
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_16
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_9
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_22
Add resource: kubernetes_deployment, kubernetes_deployment_v1
> feat(terraform): include pods of kubernetes_deployment in kubernetes_pod checks (3/4)

- checkov/terraform/checks/resource/kubernetes/Secrets.py
- checkov/terraform/checks/resource/kubernetes/ShareHostIPC.py
- checkov/terraform/checks/resource/kubernetes/ShareHostPID.py
- checkov/terraform/checks/resource/kubernetes/SharedHostNetworkNamespace.py
- checkov/terraform/checks/resource/kubernetes/Tiller.py
- tests/terraform/checks/resource/kubernetes/example_Secrets/main.tf
- tests/terraform/checks/resource/kubernetes/example_ShareHostIPC/main.tf
- tests/terraform/checks/resource/kubernetes/example_ShareHostPID/main.tf
- tests/terraform/checks/resource/kubernetes/example_SharedHostNetworkNamespace/main.tf
- tests/terraform/checks/resource/kubernetes/example_Tiller/main.tf
- tests/terraform/checks/resource/kubernetes/test_Secrets.py
- tests/terraform/checks/resource/kubernetes/test_ShareHostIPC.py
- tests/terraform/checks/resource/kubernetes/test_ShareHostNetworkNamespace.py
- tests/terraform/checks/resource/kubernetes/test_ShareHostPID.py
- tests/terraform/checks/resource/kubernetes/test_Tiller.py
This PR includes pods defined via `kubernetes_deployment` in pod checks . PR 4 of 4.
Fixes #3690
* CKV_K8S_35
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_18
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_17
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_19
Add resource: kubernetes_deployment, kubernetes_deployment_v1
* CKV_K8S_34
Add resource: kubernetes_deployment, kubernetes_deployment_v1
> feat(terraform): include pods of kubernetes_deployment in kubernetes_pod checks (4/4)

- checkov/terraform/checks/resource/gcp/GoogleComputeDefaultServiceAccountFullAccess.py
- checkov/terraform/checks/resource/gcp/GoogleComputeIPForward.py
- tests/terraform/checks/resource/gcp/test_GoogleComputeDefaultServiceAccountFullAccess.py
> fix(terraform): fix gke resource name not string

- checkov/terraform/checks/resource/aws/ElasticsearchNodeToNodeEncryption.py
- checkov/terraform/graph_builder/variable_rendering/renderer.py
- tests/terraform/graph/variable_rendering/test_renderer.py
- tests/terraform/graph/variable_rendering/test_resources/dynamic_blocks_map/main.tf
- tests/terraform/graph/variable_rendering/test_resources/dynamic_blocks_map/variables.tf
- tests/terraform/graph/variable_rendering/test_resources/dynamic_blocks_map_brackets/main.tf
- tests/terraform/graph/variable_rendering/test_resources/dynamic_blocks_map_brackets/variables.tf
Added support for dynamic modules from map variables, for example:
(Full example in the tests folder)
```
dynamic "ingress" {
for_each = var.http_headers
content {
rule_no    = ingress.value.num  # or ["num"]
protocol   = ingress.value.protoc  # or ["protoc"]
action     = "allow"
cidr_block = ingress.value.values  # or ["values"]
from_port  = 22
to_port    = 22
}
}
```
> feat(terraform): Dynamic Modules Support map type

- checkov/arm/checks/resource/NSGRulePortAccessRestricted.py
- tests/arm/checks/resource/example_NSGRuleRDPAccessRestricted/NSGRulePortAccessRestricted-FAILED.json
- tests/arm/checks/resource/example_NSGRuleSSHAccessRestricted/NSGRulePortAccessRestricted-FAILED.json
- tests/arm/checks/resource/test_NSGRuleRDPAccessRestricted.py
- tests/arm/checks/resource/test_NSGRuleSSHAccessRestricted.py
> fix(arm): CKV_AZURE_9 & CKV_AZURE_10 - Scan fails if protocol value is a wildcard

- checkov/common/bridgecrew/platform_integration.py
- checkov/main.py
> platform(general): rationalize policy metadata error handling behavior

- checkov/terraform/checks/graph_checks/aws/EC2InstanceHasIAMRoleAttached.yaml
- checkov/terraform/checks/graph_checks/gcp/CloudFunctionSecureHTTPTrigger.yaml
- checkov/terraform/checks/graph_checks/gcp/GCRContainerVulnerabilityScanningEnabled.yaml
- tests/terraform/graph/checks/resources/CloudFunctionSecureHTTPTrigger/expected.yaml
- tests/terraform/graph/checks/resources/CloudFunctionSecureHTTPTrigger/main.tf
- tests/terraform/graph/checks/resources/EC2InstanceHasIAMRoleAttached/expected.yaml
- tests/terraform/graph/checks/resources/EC2InstanceHasIAMRoleAttached/main.tf
- tests/terraform/graph/checks/resources/GCRContainerVulnerabilityScanningEnabled/expected.yaml
- tests/terraform/graph/checks/resources/GCRContainerVulnerabilityScanningEnabled/main.tf
- tests/terraform/graph/checks/test_yaml_policies.py
This PR has 3 Yaml - based checks with detailed description below
**Checkov Title:** Ensure an IAM role is attached to EC2 instance
PC Title - AWS EC2 Instance IAM Role not enabled
PC Policy ID - 8f2a2ff7-b484-463d-95df-aecd038f62b0
Compliance Standard - ACSC Information Security Manual (ISM)-ISM-1566, API Auto Clone of PIPEDA-4.7.3, APRA (CPS 234) Information Security-CPS234-14, APRA (CPS 234) Information Security-CPS234-23, APRA (CPS 234) Information Security-CPS234-27, APRA (CPS 234) Information Security-CPS234-34, Australian Cyber Security Centre (ACSC) Essential Eight-Restrict administrative privileges, Australian Energy Sector Cyber Security Framework (AESCSF)-IAM-2D, …
> feat(terraform): PC Policy Team Yaml Policies Check-in

- checkov/kubernetes/checks/resource/k8s/CPURequests.py
- checkov/kubernetes/checks/resource/k8s/MemoryRequests.py
- tests/kubernetes/checks/example_Requests_Limits/pod-requests-limits-UNKNOWN2.yaml
- tests/kubernetes/checks/test_CPULimits.py
- tests/kubernetes/checks/test_MemoryLimits.py
fixed a case when `requests` object in template is a list instead of a dict
> fix(kubernetes): fixed unexpected list object

- checkov/cloudformation/cfn_utils.py
- tests/cloudformation/runner/test_runner.py
> fix(cloudformation): only parse valid tag key-pairs in CloudFormation

- checkov/arm/base_resource_check.py
- checkov/arm/checks/resource/AKSApiServerAuthorizedIpRanges.py
- checkov/arm/checks/resource/AKSDashboardDisabled.py
- checkov/arm/checks/resource/AKSNetworkPolicy.py
- checkov/arm/checks/resource/AKSRbacEnabled.py
- tests/bicep/checks/resource/azure/example_AKSApiServerAuthorizedIpRanges/main.bicep
- tests/bicep/checks/resource/azure/example_AKSDashboardDisabled/main.bicep
- tests/bicep/checks/resource/azure/example_AKSLoggingEnabled/main.bicep
- tests/bicep/checks/resource/azure/example_AKSNetworkPolicy/main.bicep
- tests/bicep/checks/resource/azure/example_AKSRbacEnabled/main.bicep
- tests/bicep/checks/resource/azure/test_AKSApiServerAuthorizedIpRanges.py
- tests/bicep/checks/resource/azure/test_AKSDashboardDisabled.py
- tests/bicep/checks/resource/azure/test_AKSLoggingEnabled.py
- tests/bicep/checks/resource/azure/test_AKSNetworkPolicy.py
- tests/bicep/checks/resource/azure/test_AKSRbacEnabled.py
> fix(bicep): make ARM AKS checks compatible with Bicep

- checkov/terraform/parser_functions.py
- tests/terraform/graph/resources/dynamic_lambda_function/lambda.tf
- tests/terraform/graph/runner/test_runner.py
> fix(terraform): fix an issue with dynamics replacing a whole block

- checkov/terraform/checks/resource/azure/NSGRulePortAccessRestricted.py
- tests/terraform/checks/resource/azure/example_NSGRuleRDPAccessRestricted/main.tf
- tests/terraform/checks/resource/azure/test_NSGRuleRDPAccessRestricted.py
> feat(terraform): NSGRulePortAccessRestricted - Remove the condition for dynamic blocks

- checkov/kubernetes/checks/resource/base_root_container_check.py
- checkov/kubernetes/checks/resource/base_spec_check.py
- checkov/kubernetes/checks/resource/k8s/Seccomp.py
handle failing checks due to unexpected empty spec object.
no UT for this specific case wasn't added since a YAML with null value is not parsed in checkov (considered as a parsing error)
> fix(kubernetes): handle empty spec object in k8s templates

- checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py
- tests/terraform/runner/resources/unrendered_vars/bucket_equals.yaml
- tests/terraform/runner/resources/unrendered_vars/bucket_exists.yaml
- tests/terraform/runner/resources/unrendered_vars/component_equals.yaml
- tests/terraform/runner/resources/unrendered_vars/component_exists.yaml
- tests/terraform/runner/resources/unrendered_vars/nested.tf
- tests/terraform/runner/resources/unrendered_vars/simple.tf
- tests/terraform/runner/test_runner.py
> fix(terraform): Handled nested unrendered vars

- .github/exclude-patterns.txt
> chore: exclude NCP provider test from secrets check

- checkov/contributor_metrics.py
- checkov/main.py
This PR removes env var protection from running contributor metrics report and adds debug logs.
> feat(general): remove env var for running contributor metrics report and add logs

- checkov/common/typing.py
- checkov/common/util/secrets.py
- checkov/terraform/plan_runner.py
- tests/common/utils/conftest.py
- tests/common/utils/test_secrets_utils.py
> feat(terraform): Mask secret values in Terraform plan file reports by resource

- checkov/common/output/common.py
- checkov/common/output/csv.py
- checkov/common/output/cyclonedx.py
- checkov/common/sca/output.py
- tests/sca_image/test_output_reports.py
- tests/sca_package/conftest.py
- tests/sca_package/outputs/results_cyclonedx_with_comma_in_licenses.xml
- tests/sca_package/test_output_reports.py
- tests/sca_package/test_runner.py
> platform(sca): Fix bom report

- checkov/terraform/checks/resource/aws/WAFACLCVE202144228.py
- checkov/terraform/graph_builder/variable_rendering/renderer.py
- tests/terraform/graph/variable_rendering/test_renderer.py
- tests/terraform/graph/variable_rendering/test_resources/dynamic_blocks_map/variables.tf
- tests/terraform/graph/variable_rendering/test_resources/dynamic_blocks_map_brackets/variables.tf
> fix(terraform): Fixing some broke flow in dynamic blocks rendering

- checkov/terraform/checks/resource/aws/SecurityGroupUnrestrictedIngressAny.py
- tests/terraform/checks/resource/aws/example_SecurityGroupUnrestrictedIngressAny/main.tf
- tests/terraform/checks/resource/aws/test_SecurityGroupUnrestrictedIngressAny.py
-1 on a port represents any port in TF, disallow that with this check.
[//]: # "
ex.
feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual …
> feat(terraform): test checks for any port access

- checkov/terraform/graph_builder/variable_rendering/renderer.py
- tests/terraform/graph/variable_rendering/test_renderer.py
Fix dynamic blocks nested module, and uncomment the UT.
> fix(terraform): Fix dynamic blocks nested module

- checkov/terraform/checks/resource/aws/EKSControlPlaneLogging.py
- tests/terraform/checks/resource/aws/test_EKSControlPlaneLogging.py
handle empty enabled_cluster_log_types list for check EKSControlPlaneLogging
> fix(terraform): handle empty enabled_cluster_log_types list

- checkov/terraform/graph_builder/local_graph.py
- tests/terraform/graph/graph_builder/test_graph_builder.py
- tests/terraform/graph/resources/cross_variables/main.tf
- tests/terraform/graph/resources/cross_variables2/main/main.tf
- tests/terraform/graph/resources/cross_variables2/module/main.tf
- tests/terraform/graph/resources/cross_variables2/module/variables.tf
> feat(terraform): create cross-variable edges between resources from the same module

- checkov/common/util/secrets.py
- checkov/terraform/plan_runner.py
- tests/common/utils/conftest.py
- tests/common/utils/test_secrets_utils.py
> feat(terraform): Censor secrets from tfplan graph

- checkov/common/bridgecrew/platform_integration.py
- tests/common/test_platform_integration.py
Removes validation of prisma metadata filter values since https://prisma.pan.dev/api/cloud/cspm/policy#operation/get-policy-filters-and-options only returns recently used values. 
Fixes #3475
> fix(general): remove filter value validation

- checkov/common/models/enums.py
- checkov/common/sca/output.py
- checkov/sca_package_2/runner.py
- tests/sca_package/test_output.py
> platform(sca): added dependency tree format 

- checkov/terraform/checks/resource/alicloud/AbsRDSParameter.py
- tests/terraform/checks/resource/alicloud/example_RDSInstanceLogConnections/main.tf
> fix(terraform): Fix an edge case in AbsRDSParameter check 

- checkov/contributor_metrics.py
- checkov/main.py
- tests/test_contributor_metrics.py
This PR adds source to contributor metrics report in order for the persistence to differentiate between repositories under different sources.
> feat(general): add source to contributor metrics report

- .github/workflows/build.yml
- docs/4.Integrations/Docker.md
> feat(general): sign and push checkov image to GitHub registry

- checkov/terraform/checks/resource/aws/RedshiftServerlessNamespaceKMSKey.py
- tests/terraform/checks/resource/aws/example_RedshiftServerlessNamespaceKMSKey/main.tf
- tests/terraform/checks/resource/aws/test_RedshiftServerlessNamespaceKMSKey.py
> feat(terraform): add CKV_AWS_282 to ensure that Redshift Serverless namespace is encrypted by KMS

- checkov/kubernetes/checks/resource/k8s/ContainerSecurityContext.py
- checkov/terraform/checks/resource/kubernetes/PodSecurityContext.py
> fix(terraform): better check names to avoid confusion - addresses #3912

- checkov/common/images/image_referencer.py
- checkov/helm/runner.py
- checkov/kustomize/runner.py
- tests/helm/test_runner_image_referencer.py
- tests/kustomize/test_runner_image_referencer.py
> fix(sca): fix related resource id for helm and kustomize

- checkov/common/bridgecrew/wrapper.py
> fix(general): update checks_metadata structure

- checkov/bicep/checks/resource/azure/StorageAccountAzureServicesAccessEnabled.py
- checkov/bicep/checks/resource/azure/StorageAccountsTransportEncryption.py
- tests/bicep/checks/resource/azure/example_StorageAccountAzureServicesAccessEnabled/main.bicep
- tests/bicep/checks/resource/azure/example_StorageAccountsTransportEncryption/main.bicep
- tests/bicep/checks/resource/azure/test_StorageAccountAzureServicesAccessEnabled.py
- tests/bicep/checks/resource/azure/test_StorageAccountsTransportEncryption.py
> fix(bicep): ignore unresolvable properties for Bicep storage account checks

- checkov/circleci_pipelines/image_referencer/provider.py
- checkov/circleci_pipelines/runner.py
- checkov/github_actions/runner.py
- checkov/yaml_doc/runner.py
- tests/github_actions/conftest.py
- tests/github_actions/test_runner_resource_names.py
> fix(gha): added test for step with no step name

- Manifest.in
- checkov/common/util/docs_generator.py
- checkov/dockerfile/checks/graph_checks/RunUsingSudo.yaml
- checkov/dockerfile/graph_builder/graph_components/resource_types.py
- checkov/dockerfile/graph_builder/local_graph.py
- checkov/dockerfile/graph_manager.py
- checkov/dockerfile/runner.py
- checkov/dockerfile/utils.py
- docs/3.Custom Policies/YAML Custom Policies.md
- setup.py
- tests/dockerfile/graph_builder/checks/resources/RunUsingSudo/expected.yaml
- tests/dockerfile/graph_builder/checks/resources/RunUsingSudo/fail/Dockerfile
- tests/dockerfile/graph_builder/checks/resources/RunUsingSudo/fail_multiline/Dockerfile
- tests/dockerfile/graph_builder/checks/resources/RunUsingSudo/pass/Dockerfile
- tests/dockerfile/graph_builder/checks/test_yaml_policies.py
- tests/dockerfile/graph_builder/test_local_graph.py
- tests/dockerfile/image_referencer/test_runner_dockerfile_resources.py
- tests/dockerfile/test_graph_manager.py
> feat(dockerfile): add graph to Dockerfile

- checkov/terraform/checks/resource/oci/AbsSecurityGroupUnrestrictedIngress.py
- tests/terraform/checks/resource/oci/example_SecurityGroupUnrestrictedIngress22/main.tf
AbsSecurtiGroupUnrestictedIngress  is comparing "source_port_range"  instead of   "destination_port_range" which is not a true way to control access policy. 
Fixes #3932
> fix(terraform): OCI Security Group Control Problem

- checkov/common/checks/base_check_registry.py
> chore(general): Don't fail if specific check throws exception

- checkov/secrets/plugins/custom_regex_detector.py
fix https://github.com/bridgecrewio/checkov/issues/3971
> fix(secrets): fix Issue with 'NoneType' error in the custom detectors load_detectors

- checkov/terraform/graph_builder/local_graph.py
> platform(terraform): remove redundant exc_info for module without source

- Pipfile
- Pipfile.lock
- checkov/common/output/cyclonedx.py
- setup.py
> chore: update bc-detect-secrets version to 1.4.4

- checkov/dockerfile/base_registry.py
- tests/dockerfile/resources/expose_port/skip/Dockerfile
- tests/dockerfile/test_runner.py
> fix(dockerfile): fix Dockerfile inline skip handling

- checkov/terraform/checks/resource/azure/APIManagementMinTLS12.py
- tests/terraform/checks/resource/azure/example_APIManagementMinTLS12/main.tf
- tests/terraform/checks/resource/azure/test_APIManagementMinTLS12.py
> feat(terraform): check for insecure protocols

- checkov/terraform/checks/data/aws/IAMPublichActionsPolicy.py
- tests/terraform/checks/data/aws/example_IAMPublichActionsPolicy/public_actions.tf
- tests/terraform/checks/data/aws/test_IAMPublicActionsPolicy.py
> fix(terraform): fix CKV_AWS_283 check

- checkov/common/runners/runner_registry.py
- checkov/common/util/secrets_omitter.py
- tests/common/secrets_omitter/test_secrets_omitter.py
> feat(secrets): Omit secrets from reports based on secrets reports

- checkov/kubernetes/checks/graph_checks/ReadAllSecrets.yaml
- tests/kubernetes/graph/checks/resources/ReadAllSecrets/Failing/ClusterRole.yaml
- tests/kubernetes/graph/checks/resources/ReadAllSecrets/Failing/ClusterRoleBinding.yaml
- tests/kubernetes/graph/checks/resources/ReadAllSecrets/Passing/ClusterRole.yaml
- tests/kubernetes/graph/checks/resources/ReadAllSecrets/Passing/ClusterRoleBinding.yaml
- tests/kubernetes/graph/checks/resources/ReadAllSecrets/expected.yaml
- tests/kubernetes/graph/checks/test_yaml_policies.py
> feat(kubernetes): Added CKV2_K8S_5 check that no service account or node can read all secrets

- checkov/github_actions/utils.py
- tests/github_actions/gha/.github/workflows/failed.yaml
- tests/github_actions/test_graph_manager.py
This PR adds graph utils methods to GHA so that it will be used when constructing and deconstructing a graph.
> feat(gha): add infra for gha graphs

- tests/kubernetes/graph/checks/resources/PodIsPubliclyAccessibleExample/Failing/Pod.yaml
- tests/kubernetes/graph/checks/resources/PodIsPubliclyAccessibleExample/Failing/Service.yaml
- tests/kubernetes/graph/checks/resources/PodIsPubliclyAccessibleExample/Passing/Pod.yaml
- tests/kubernetes/graph/checks/resources/PodIsPubliclyAccessibleExample/Passing/Service.yaml
- tests/kubernetes/graph/checks/resources/PodIsPubliclyAccessibleExample/expected.yaml
- tests/kubernetes/graph/checks/test_checks/PodIsPubliclyAccessibleExample.yaml
- tests/kubernetes/graph/checks/test_yaml_policies.py
> feat(kubernetes): added CKV2_K8S_EXAMPLE_1 only in tests as an example for k8s graph check for pod which is publicly accessible

- checkov/common/packaging/version.py
> fix(sca): invoke packaging.Version instead of parse

- checkov/common/util/secrets.py
- tests/unit/test_secrets.py
> fix(secrets): fix error when secret is None

- Pipfile
- Pipfile.lock
- setup.py
- tests/terraform/parser/test_hcl2_load_assumptions.py
> chore: update python-hcl2 and jsonpath-ng

- checkov/common/util/secrets.py
- tests/unit/test_secrets.py
> fix(secrets): fix secrets crash when secret is non string

- checkov/terraform/context_parsers/base_parser.py
- checkov/terraform/context_parsers/parsers/provider_context_parser.py
- checkov/terraform/graph_builder/local_graph.py
- tests/terraform/graph/graph_builder/test_graph_builder.py
- tests/terraform/graph/resources/nested_modules_address/main.tf
> fix(terraform): add a method for get the entity definition path from the entity itself

- checkov/kubernetes/graph_manager.py
- tests/kubernetes/graph/test_graph_manager.py
Allow setting K8S FFs as instance vars instead of a constructor arguments. This will allow a unified call to `graph_manager.build_graph_from_source_directory()` for all frameworks
> feat(kubernetes): inject k8s FF flags to instance instead of constructor

- checkov/terraform/runner.py
- tests/terraform/runner/resources/resource_ids_nested_modules/main.tf
- tests/terraform/runner/resources/resource_ids_nested_modules/module/main.tf
- tests/terraform/runner/resources/resource_ids_nested_modules/module/module2/main.tf
- tests/terraform/runner/resources/resource_ids_nested_modules/module/module2/variable.tf
- tests/terraform/runner/resources/resource_ids_nested_modules/module/variable.tf
- tests/terraform/runner/test_runner.py
fix terraform resources ids in the report
after fixing the `__address__` attribute for modules, the nested module resources ids in the report didn't contain the 'module' prefix.
> fix(terraform): fix nested module resources ids in the report

- checkov/main.py
> feat(general): Use --no-fail-on-crash to gracefully exit commit_repository and setup_bridgecrew_credentials

- checkov/github_actions/image_referencer/provider.py
- tests/github_actions/image_referencer/conftest.py
- tests/github_actions/image_referencer/test_github_action_provider.py
> fix(github): Fix GHA IR resource names in case of 2 identical images

- checkov/terraform/plan_runner.py
- tests/terraform/runner/extra_tf_plan_checks/secret_not_deleted.py
- tests/terraform/runner/test_plan_runner.py
> feat(terraform_plan): add check details to TF plan scan results

- checkov/dockerfile/runner.py
- checkov/dockerfile/utils.py
- tests/dockerfile/test_runner.py
> fix(dockerfile): adjust the file abs path for Dockerfile graph results

- checkov/kubernetes/checks/resource/base_container_check.py
remove obsolete error logging while parsing templates since the parsing strategy has changed
> fix(kubernetes): removed obsolete error logging

- checkov/kubernetes/runner.py
> fix(kubernetes): move Kubernetes context error message

- .github/PULL_REQUEST_TEMPLATE.md
> chore(general): Add allowed prefixes to PR template

- checkov/circleci_pipelines/checks/DetectImagesUsage.py
- tests/circleci_pipelines/image_referencer/test_runner.py
- tests/circleci_pipelines/test_runner.py
Images can be found in `executors` or `jobs` in circleci.
originally, `jobs...` entity was not included `supported_entities` in the in the entities.
This check should have all the resources that have IR findings, even if they exist in some other check.
> fix(circleci): add resource to ir

- checkov/secrets/coordinator.py
- checkov/secrets/runner.py
- tests/secrets/test_coordinator.py
added a class to save secrets data for further validation.
> feat(secrets): Keep original secrets data in runtime for further validation

- checkov/terraform/runner.py
- tests/terraform/runner/resources/get_graph_resource_entity_config/main.tf
- tests/terraform/runner/resources/get_graph_resource_entity_config/variables.tf
- tests/terraform/runner/test_runner.py
fix getting graph entity config in terraform runner, in some block types (`provider` for example) the entity config is not under the `definition_path` of the entity.
> fix(terraform): fix getting graph entity config in terraform runner

- docs/6.Contribution/Contribute YAML-based Policies.md
> docs(general): fix reference link in Contributing docs page

- checkov/bicep/graph_builder/variable_rendering/renderer.py
- checkov/cloudformation/checks/utils/iam_cloudformation_document_to_policy_converter.py
- checkov/cloudformation/graph_builder/graph_components/blocks.py
- checkov/cloudformation/graph_builder/graph_components/generic_resource_encryption.py
- checkov/cloudformation/graph_builder/graph_to_definitions.py
- checkov/cloudformation/graph_builder/local_graph.py
- checkov/cloudformation/graph_builder/variable_rendering/renderer.py
- checkov/cloudformation/graph_builder/variable_rendering/vertex_reference.py
- checkov/cloudformation/runner.py
- checkov/common/graph/graph_builder/graph_components/blocks.py
- checkov/common/graph/graph_builder/local_graph.py
- checkov/common/graph/graph_builder/variable_rendering/breadcrumb_metadata.py
- checkov/common/graph/graph_builder/variable_rendering/renderer.py
- checkov/common/graph/graph_builder/variable_rendering/vertex_reference.py
- checkov/common/util/data_structures_utils.py
- checkov/terraform/graph_builder/variable_rendering/vertex_reference.py
- mypy.ini
> chore: add missing type hints under cloudformation

- checkov/terraform/checks/resource/aws/IAMManagedAdminPolicy.py
- tests/terraform/checks/resource/aws/example_IAMManagedAdminPolicy/IAMManagedAdminPolicy.tf
- tests/terraform/checks/resource/aws/test_IAMManagedAdminPolicy.py
> feat(terraform): added aws_ssoadmin_managed_policy_attachment resource to CKV_AWS_274

- CONTRIBUTING.md
- docs/2.Basics/Scanning Credentials and Secrets.md
- docs/3.Custom Policies/Python Custom Policies.md
- docs/6.Contribution/Contribute YAML-based Policies.md
- docs/6.Contribution/Contribution New IaC Runner.md
> docs(general): fix links in contributing docs

- checkov/github/checks/repository_collaborators.py
- tests/github/test_runner.py
This PR prevents failure of vcs repo collabs check when the payload is empty.
This is a possible scenario in some cases.
> feat(general): add logic to vcs scanning to prevent empty repo collabs failing check

- checkov/common/runners/runner_registry.py
- tests/common/runner_registry/test_runner_registry.py
> fix(general): fix incorrect billing message when frameworks are removed from --framework list

- checkov/common/output/record.py
- checkov/secrets/runner.py
- tests/secrets/conftest.py
- tests/secrets/test_secrets_verification.py
…if not CKV_VALIDATE_SECRETS
[//]: # " …
> fix(secrets): Disable verify secrets if skip_download is specified

- checkov/secrets/plugins/entropy_keyword_combinator.py
- tests/secrets/test_entropy_source_files/db-conn.js
- tests/secrets/test_runner.py
> feat(secrets): Implement lower entropy threshold on a line with keyword

- checkov/kubernetes/checks/resource/base_registry.py
- tests/kubernetes/test_base_registry.py
> fix(kubernetes): allow filtering of custom with built-in Kubernetes check IDs

- checkov/common/graph/graph_builder/graph_components/attribute_names.py
- checkov/terraform/plan_parser.py
- tests/terraform/runner/extra_tf_plan_checks/nsg_rule_connection.yaml
- tests/terraform/runner/resources/plan_with_resource_reference/tfplan_extra_ref.json
- tests/terraform/runner/test_plan_runner.py
- tests/terraform/runner/test_runner.py
> feat(terraform_plan): support multiple references in one resource

- .github/workflows/build.yml
- .github/workflows/pr-test.yml
> chore: add pipenv cache

- checkov/terraform/graph_builder/local_graph.py
when adding a new edge, check if a new cross_variable_edge is exist in the origin out_edges instead of all edges
Relates #4230
> fix(terraform): improve cross-variable edges performance

- checkov/circleci_pipelines/image_referencer/provider.py
- tests/circleci_pipelines/image_referencer/test_manager.py
This PR fixes a case in circleCI IR which crashes when unable to find image resource.
We need to find a long term solution in which we find nested images which are not aligned according to start/end lines.
> feat(general): fix circleci crash when cannot find image

- checkov/terraform/checks/resource/azure/AKSRbacEnabled.py
- tests/terraform/checks/resource/azure/test_AKSRbacEnabled.py
The check CKV_AZURE_5 should succeed if the `role_based_access_control_enabled` property is not set in resource `azurerm_kubernetes_cluster` as its default value is `true`.
Fixes #4227
> fix(terraform): default value for CKV_AZURE_5

- Pipfile.lock
- tests/bicep/graph/checks/test_yaml_policies.py
- tests/cloudformation/graph/checks/test_yaml_policies.py
- tests/cloudformation/graph/graph_builder/test_render.py
- tests/common/bridgecrew/vulnerability_scanning/integrations/test_docker_image_scanning.py
- tests/common/output/test_get_exit_code.py
- tests/dockerfile/graph_builder/checks/test_yaml_policies.py
- tests/github_actions/checks/graph_checks/test_yaml_policies.py
- tests/sca_package/conftest.py
- tests/sca_package_2/conftest.py
- tests/serverless/checks/aws/test_AdminPolicyDocument.py
- tests/terraform/graph/checks/test_yaml_connected_nodes.py
- tests/terraform/graph/checks/test_yaml_policies.py
- tests/terraform/graph/variable_rendering/test_render_scenario.py
- tests/terraform/graph/variable_rendering/test_renderer.py
> chore: use mock.patch for setting env vars

- checkov/github_actions/image_referencer/provider.py
- tests/github_actions/image_referencer/conftest.py
- tests/github_actions/image_referencer/test_github_action_provider.py
This PR adds a safeguard for image retrieval in GHA IR and also adjusts the index of the image.
> feat(gha): fix failing image retrieval in GHA IR

- checkov/cloudformation/checks/resource/base_resource_value_check.py
- tests/cloudformation/checks/resource/aws/example_RDSEnhancedMonitorEnabled/PASS.yaml
- tests/cloudformation/checks/resource/aws/test_RDSEnhancedMonitorEnabled.py
> fix(cloudformation): fix CloudFormation checks related to number values

- checkov/terraform/runner.py
files without `definition_blocks_types` don't save in the definition context.
> fix(terraform): fix error for push_skipped_checks_down with definition that not in the definition context

- checkov/secrets/runner.py
- tests/secrets/test_secrets_verification.py
> fix(secrets): change default secret validation status to unavailable

- Dockerfile.pyston
> chore: add cmake for building igraph

- checkov/terraform/plan_runner.py
- tests/terraform/runner/resources/plan_and_tf_combine_graph/source/module2/main.tf
An exception was raised when we got graph check results on the terraform files because they aren't saved in the definitions_context. 
Thus results are filtered out anyway so we can return None for the context.
Add terraform resource that has graph check result for the plan_and_tf_combine_graph test
> fix(terraform_plan): fix in deep analysis

- .github/codeql-config.yml
- .github/workflows/codeql-analysis.yml
> chore: exclude tests folder for CodeQL scan

- checkov/terraform/checks/resource/gcp/GKEBasicAuth.py
- tests/terraform/checks/resource/gcp/example_GKEBasicAuth/main.tf
- tests/terraform/checks/resource/gcp/test_GKEBasicAuth.py
> fix(terraform): fix default behaviour of CKV_GCP_19

- checkov/common/bridgecrew/platform_integration.py
> fix(general): In case of a non-JSON response, log the response

- checkov/kubernetes/graph_builder/local_graph.py
- checkov/kubernetes/kubernetes_utils.py
- tests/kubernetes/graph/resources/faulty_resources/deployment_missing_metadata.yaml
- tests/kubernetes/graph/test_local_graph.py
When `Deployment` resource is missing metadata object it can't be associated to the nested pod (anyway this is required so the resource is not valid when it's missing). Skipping the extraction of the nested in this case
> fix(kubernetes): handle k8s resource with missing required data

- checkov/azure_pipelines/checks/job/DetectImagesUsage.py
- tests/azure_pipelines/image_referencer/test_runner.py
This PR changes DetectImageUsage to iterate over the job of the azure pipelines workflow file.
Since extracted images have the job as their resource(without container/pool/.. suffix) we must make sure the DetectImageUsage runs over the jobs.
> feat(azure): change detect image source

- checkov/common/util/docs_generator.py
- checkov/main.py
- integration_tests/test_checkov_platform_only_policies.py
> fix(general): ignore repo_id setting when list flag is set

- checkov/terraform/image_referencer/provider/aws.py
skip extracting images from containers definitions with unexpected type
> fix(terraform): handle unexpected container definition type

- checkov/kubernetes/graph_builder/local_graph.py
K8s Pods are extracted even if the parent type is not supported. This fix extracts Pods only for supported parents types
> fix(kubernetes): extract pods only for supported resources

- README.md
Fix env var name from `IGNORE_HIDDEN_DIRECTORY_ENV` to `CKV_IGNORE_HIDDEN_DIRECTORIES`.
The current one is the name of the internal variable which will be set by reading the env var.
[//]: # "
- platform: to indicate a change needed for the …
> docs(general): fix env var name to `CKV_IGNORE_HIDDEN_DIRECTORIES`

- checkov/common/bridgecrew/vulnerability_scanning/image_scanner.py
- checkov/common/images/image_referencer.py
- tests/common/images/test_base_image_referencer.py
> fix(sca): Fix multiple issues related to IR

- checkov/common/runners/runner_registry.py
> chore: revert OUTPUT_CHOICES type to list

- checkov/common/output/gitlab_sast.py
- tests/common/output/test_gitlab_sast_report.py
> fix(sca): support BC_VUL_X IDs in GitLab SAST output

- checkov/sca_package/runner.py
currently if we have yarn.lock file and package.json, we build a DT for yarn.lock and scan package.json.
> feat(sca): ignore package.json file when yarn.lock exists

- checkov/cloudformation/graph_builder/graph_components/blocks.py
- checkov/cloudformation/graph_builder/local_graph.py
> fix(cloudformation): Skip SAM Global Tags propagation

- checkov/common/runners/object_runner.py
- tests/github_actions/test_runner.py
This PR reconstructs GHA permissions block lines on the report.
We are referencing the definitions_raw struct to extract the lines.
> feat(gha): add gha permissions lines

- checkov/terraform/checks/resource/gcp/GoogleStoragePublicAccessPrevention.py
- tests/terraform/checks/resource/gcp/example_GoogleStoragePublicAccessPrevention/main.tf
- tests/terraform/checks/resource/gcp/test_GoogleStoragePublicAccessPrevention.py
> feat(terraform): add CKV_GCP_114 to ensure that Public Access Prevention is enforced on GoogleCloudStorage bucket.

- checkov/terraform/checks/resource/aws/IAMCredentialsExposure.py
- checkov/terraform/checks/resource/aws/IAMDataExfiltration.py
- checkov/terraform/checks/resource/aws/IAMPermissionsManagement.py
- checkov/terraform/checks/resource/aws/IAMWriteAccess.py
- tests/terraform/checks/resource/aws/example_IAMCredentialsExposure/main.tf
- tests/terraform/checks/resource/aws/example_IAMDataExfiltration/main.tf
- tests/terraform/checks/resource/aws/example_IAMPermissionsManagement/main.tf
- tests/terraform/checks/resource/aws/example_IAMWriteAccess/main.tf
- tests/terraform/checks/resource/aws/test_IAMCredentialsExposure.py
- tests/terraform/checks/resource/aws/test_IAMDataExfiltration.py
- tests/terraform/checks/resource/aws/test_IAMPermissionsManagement.py
- tests/terraform/checks/resource/aws/test_IAMWriteAccess.py
> feat(terraform): Add cloudsplaining checks to tf aws_iam_policy CKV_AWS_287-290

- checkov/common/runners/runner_registry.py
- tests/common/runner_registry/test_runner_registry.py
when we have package file without any vulnerabilities -> the bom report will be empty
> feat(sca): create bom report when extra_resources is not empty

- .github/workflows/build.yml
- checkov/common/output/gitlab_sast.py
- tests/common/output/test_gitlab_sast_report.py
> fix(general): Remove empty links from GitLab SAST output

- checkov/secrets/plugins/detector_utils.py
- checkov/secrets/plugins/entropy_keyword_combinator.py
This PR extracts utils from entropy keyword combinator so we can use them for other probability-based detectors and plugins. We are deleting a few methods from entropy keyword combinator and adding them to detector_utils.
> feat(secrets): extract new detector_utils file from entropy keyword combinator

- .github/workflows/build.yml
- .github/workflows/pr-test.yml
- checkov/kustomize/runner.py
- checkov/kustomize/utils.py
- tests/kustomize/test_utils.py
> feat(kustomize): support kustomize v5

- .github/workflows/build.yml
- .github/workflows/coverage.yaml
- .github/workflows/pr-test.yml
> chore: add GH token to setup-kustomize action

- checkov/terraform/runner.py
- tests/terraform/runner/resources/nested_modules_caller_file/main.tf
- tests/terraform/runner/resources/nested_modules_caller_file/module/module.tf
- tests/terraform/runner/test_runner.py
fix finding caller module for a resource named 'module'
> fix(terraform): fix getting the module for resource named 'module'

- checkov/common/output/record.py
- checkov/common/output/secrets_record.py
This PR utilizes the secrets record and provides it with its own to_string method so it can leverage the generic record to_string and also enrich with its own info.
> feat(secrets): remove secrets dependency in generic record

- checkov/kustomize/runner.py
log error of 'Context for Kustomize runner was not set' only if the context is None and not if it's empty
> fix(kustomize): remove redundant error in kustomize runner

- checkov/common/checks/base_check.py
- checkov/common/checks/base_check_registry.py
- checkov/common/graph/graph_builder/variable_rendering/renderer.py
- checkov/common/models/enums.py
- tests/common/checks/test_base_check.py
> feat(general): Control check failure logging level

- Pipfile
- Pipfile.lock
- checkov/cloudformation/parser/cfn_yaml.py
- checkov/common/multi_signature.py
- checkov/common/output/baseline.py
- checkov/common/parsers/json/decoder.py
- setup.py
- Automatic update of bc-jsonpath-ng
> chore: update bc-jsonpath-ng version to 1.5.9

- checkov/secrets/plugins/custom_regex_detector.py
- tests/secrets/test_load_detectors.py
> fix(secrets): Comment out checkob multiline regex detectors

- checkov/github_actions/graph_builder/local_graph.py
- docs/3.Custom Policies/YAML Custom Policies.md
- tests/github_actions/checks/extra_yaml_checks/OnPush.yaml
- tests/github_actions/checks/test_extra_checks.py
> break(gha): adjust the attribute reference for GitHub Actions graph checks

- checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py
- checkov/terraform/checks/resource/aws/EMRClusterIsEncryptedKMS.py
- checkov/terraform/checks/resource/aws/SSMSessionManagerDocumentEncryption.py
- checkov/terraform/checks/resource/aws/SSMSessionManagerDocumentLogging.py
- checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py
- tests/terraform/graph/checks/custom_policies/CustomAwsEMRSecurityConfiguration.yaml
- tests/terraform/graph/checks/resources/CustomAwsEMRSecurityConfiguration/expected.yaml
- tests/terraform/graph/checks/resources/CustomAwsEMRSecurityConfiguration/main.tf
- tests/terraform/graph/checks/test_custom_yaml_policies.py
> feat(terraform): support more json encoded objects as part of terraform resource and fix evaluation of true/false in json

- checkov/cloudformation/checks/resource/aws/KMSRotation.py
- checkov/terraform/checks/resource/aws/KMSRotation.py
- tests/cloudformation/checks/resource/aws/example_KMSRotation/KMSRotation-PASSED-Asymmetric.yml
- tests/cloudformation/checks/resource/aws/example_KMSRotation/KMSRotation-PASSED-Symmetric.yml
- tests/cloudformation/checks/resource/aws/test_KMSRotation.py
- tests/terraform/checks/resource/aws/example_KMSRotation/main.tf
- tests/terraform/checks/resource/aws/test_KMSRotation.py
> fix(cloudformation): Updated AWS_CKV_7 to not require rotation on asymmetric keys

- checkov/terraform/checks/resource/aws/DocDBGlobalClusterEncryption.py
- tests/terraform/checks/resource/aws/example_DocDBGlobalClusterEncryption/main.tf
- tests/terraform/checks/resource/aws/test_DocDBGlobalClusterEncryption.py
> feat(terraform): AWS:check global DocDB cluster is encrypted

- checkov/ansible/checks/base_ansible_task_check.py
- checkov/ansible/graph_builder/local_graph.py
- checkov/ansible/runner.py
- tests/ansible/examples/nested_blocks.yml
- tests/ansible/examples/site.yml
- tests/ansible/graph_builder/test_local_graph.py
- tests/ansible/test_graph_manager.py
- tests/ansible/test_runner.py
> fix(ansible): support nested blocks and empty module values

- checkov/secrets/runner.py
This PR adds capability to secrets runner to log potential uuid secrets so we can get an idea on the frequency of findings.
The filtering of UUIDs still takes effect, but a little later in the flow.
> feat(secrets): log and filter potential uuid case

- checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py
- tests/terraform/graph/variable_rendering/test_string_evaluation.py
> fix(terraform): Handle type error in `_handle_for_loop_in_dict`

- checkov/terraform/parser.py
- tests/terraform/runner/resources/resource_ids_nested_modules/main.tf
skip loading modules with the current dir as the source.
when the source of a module is `./` we got into an endless recursive loop in the parser phase while loading the modules.
add a recursive module in a test.
> fix(terraform): skip loading module that calls to the same dir

- checkov/ansible/graph_builder/local_graph.py
- tests/ansible/examples/no_tasks.yml
- tests/ansible/test_runner.py
> fix(ansible): skip unsupported Ansible resources

- checkov/terraform/graph_builder/foreach_handler.py
- tests/terraform/checks/resource/aws/test_EC2PublicIP.py
- tests/terraform/graph/variable_rendering/expected_data_foreach.json
- tests/terraform/graph/variable_rendering/resources/foreach_examples/depend_resources/main.tf
- tests/terraform/graph/variable_rendering/test_foreach_renderer.py
> feat(terraform): Used parentheses in key for foreach attributes but not count

- github_action_resources/entrypoint.sh
> fix(gha): fix output flag for usage in checkov-action

- checkov/common/runners/object_runner.py
- checkov/yaml_doc/runner.py
- tests/gitlab_ci/resources/alternative/.gitlab-ci.yml
- tests/gitlab_ci/test_runner.py
This PR handles cases in which __startline__/__endline__ is not present in the file representation we build for gitlab-ci.yaml. 
We skip those cases for now, and future work needs to be done to ensure we build a representation which correctly reflects the yaml structure of the file.
> feat(gitlab): fix gitlab ci yaml file processing

- checkov/terraform/modules/module_utils.py
- checkov/terraform/parser.py
> fix(terraform): Move get_module back to parser

- checkov/common/checks/base_check.py
- checkov/common/checks/object_registry.py
- checkov/common/typing.py
- checkov/yaml_doc/base_registry.py
- tests/ansible/examples/skip.yml
- tests/ansible/test_runner.py
> fix(ansible): support skip check for Ansible Python-based checks

- checkov/main.py
- tests/test_main.py
> chore: add warning when using severity filter without API key

- checkov/ansible/checks/graph_checks/DnfDisableGpgCheck.yaml
- checkov/ansible/checks/graph_checks/DnfSslVerify.yaml
- checkov/ansible/checks/graph_checks/DnfValidateCerts.yaml
- tests/ansible/checks/graph_checks/resources/DnfDisableGpgCheck/expected.yaml
- tests/ansible/checks/graph_checks/resources/DnfDisableGpgCheck/fail.yaml
- tests/ansible/checks/graph_checks/resources/DnfDisableGpgCheck/pass.yaml
- tests/ansible/checks/graph_checks/resources/DnfSslVerify/expected.yaml
- tests/ansible/checks/graph_checks/resources/DnfSslVerify/fail.yaml
- tests/ansible/checks/graph_checks/resources/DnfSslVerify/pass.yaml
- tests/ansible/checks/graph_checks/resources/DnfValidateCerts/expected.yaml
- tests/ansible/checks/graph_checks/resources/DnfValidateCerts/fail.yaml
- tests/ansible/checks/graph_checks/resources/DnfValidateCerts/pass.yaml
- tests/ansible/checks/graph_checks/test_yaml_policies.py
- tests/ansible/checks/task/builtin/AptAllowUnauthenticated/fail.yaml
> feat(ansible): Add checks for the ansible builtin dnf module

- checkov/terraform/checks/resource/aws/AbsSecurityGroupUnrestrictedIngress.py
- tests/terraform/checks/resource/aws/example_SecurityGroupUnrestrictedIngressAny/main.tf
- tests/terraform/checks/resource/aws/test_SecurityGroupUnrestrictedIngressAny.py
> feat(terraform): Support the -1 protocol on SG checks

- checkov/arm/checks/resource/AKSLoggingEnabled.py
- tests/bicep/checks/resource/azure/example_AKSLoggingEnabled/main.bicep
- tests/bicep/checks/resource/azure/test_AKSLoggingEnabled.py
> fix(bicep): extend CKV_AZURE_4 to consider omsAgent to be written in camelCase

- checkov/common/checks/base_check_registry.py
- tests/arm/runner/resources/invalid.json
- tests/arm/runner/test_runner.py
> fix(general): skip scanning invalid resources

- checkov/terraform/graph_builder/variable_rendering/safe_eval_functions.py
- tests/terraform/graph/variable_rendering/test_renderer.py
- tests/terraform/graph/variable_rendering/test_resources/skip_renderer/ellipsis.tf
> fix(terraform): stop evaluating a string ... to the Ellipsis object

- checkov/dockerfile/checks/graph_checks/RunYumNoGpgCheck.yaml
- tests/dockerfile/graph_builder/checks/resources/RunYumNoGpgCheck/expected.yaml
- tests/dockerfile/graph_builder/checks/resources/RunYumNoGpgCheck/fail/Dockerfile.tdnf
- tests/dockerfile/graph_builder/checks/resources/RunYumNoGpgCheck/fail/Dockerfile.wilderness
- tests/dockerfile/graph_builder/checks/resources/RunYumNoGpgCheck/pass/Dockerfile
> feat(dockerfile): Add tdnf support for CKV2_DOCKER_9

- README.md
- checkov/common/images/image_referencer.py
- checkov/sca_image/runner.py
- docs/6.Contribution/Implementing ImageReferencer.md
- integration_tests/prepare_data.sh
- integration_tests/run_integration_tests.sh
> chore: remove Image Referencer experimental flag

- checkov/cloudformation/checks/resource/aws/KMSKeyWildCardPrincipal.py
- tests/cloudformation/checks/resource/aws/example_KMSKeyWildCardPrincipal/KMSKeyWildCardPrincipal-FAILED-AWS-Wildcard.yaml
- tests/cloudformation/checks/resource/aws/test_KMSKeyWildCardPrincipal.py
My company just found a case of a dev using a wildcard inside of an AWS principal list to evade this rule.  Since the `principal_value` in this code could be either a string or a list, checking for membership as well as equality would prevent the circumnavigation of the rule.
[//]: # "
- chore:    to indicate …
> fix(cloudformation): KMSKeyWildCardPrincipal modification - Check for wildcards inside of lists

- checkov/terraform/graph_builder/graph_components/blocks.py
- tests/terraform/graph/graph_builder/test_graph_builder.py
- tests/terraform/graph/resources/for_each/main.tf
This commit fixes an issue where Checkov crashes when a resource has the following fields:
* A `for_each` with at least one variable like `for_each = toset([var.bar])`
* A dynamic block
Check the test resource file `main.tf` that comes with the commit if you want more detail.
Checkov crashes with the following error:
```python
Error
Traceback (most recent call last):
File "/home/antoine.rouaze/src/github.com/bridgecrewio/checkov/tests/terraform/graph/graph_builder/test_graph_builder.py", line 332, in test_build_graph_for_each_with_variables_and_dynamic_not_crash
graph_manager.build_graph_from_source_directory(resources_dir)
File "/home/antoine.rouaze/src/github.com/bridgecrewio/checkov/checkov/terraform/graph_manager.py", line 48, in build_graph_from_source_directory …
```
> fix(terraform): stop handle resource `for_each` as dynamic attribute

- checkov/gitlab_ci/common/resource_id_utils.py
- tests/gitlab_ci/image_referencer/test_gitlab_ci_provider.py
- tests/gitlab_ci/image_referencer/test_manager.py
- tests/gitlab_ci/image_referencer/test_runner_gitlab_workflows.py
> fix(gitlab): Modify GitLab CI resource ids

- checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py
- checkov/terraform/graph_builder/variable_rendering/renderer.py
- tests/terraform/checks/provider/panos/resources/api_key/fail1.tf
- tests/terraform/checks/provider/panos/resources/api_key/variables.tf
- tests/terraform/graph/variable_rendering/test_renderer.py
- tests/terraform/graph/variable_rendering/test_resources/default_map_value/main.tf
- tests/terraform/graph/variable_rendering/test_string_evaluation.py
> feat(terraform): support variable rendering for default objects in vars

- checkov/common/util/http_utils.py
- checkov/sca_package_2/scanner.py
*skipping finding IsPrivateFixVersion  by default
> feat(sca): skipping finding IsPrivateFixVersion by default

- checkov/common/bridgecrew/vulnerability_scanning/integrations/twistcli.py
> feat(sca): filter twistcli results with empty package name and version

- checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py
- tests/common/integration_features/test_custom_policies_integration.py
> fix(general): Custom policies integration correct check IDs filtering

- checkov/sca_package_2/runner.py
- tests/sca_package_2/test_runner.py
> fix(sca): return empty result when using BC API key in IDE

- checkov/common/goget/github/get_git.py
- checkov/common/util/contextmanagers.py
- checkov/terraform/module_loading/loaders/git_loader.py
- github_action_resources/entrypoint.sh
- tests/common/utils/test_contextmanagers.py
> fix(terraform): add extra handling around private GitHub Terraform modules

- checkov/terraform/checks/resource/aws/SSMDocumentsArePrivate.py
- tests/terraform/checks/resource/aws/example_SSMDocumentsArePrivate/main.tf
- tests/terraform/checks/resource/aws/test_SSMDocumentsArePrivate.py
> feat(terraform): ensure SSM docs are private

- checkov/secrets/runner.py
- tests/secrets/test_secrets_verification.py
- tests/secrets/test_secrets_verification_suppressions.py
> feat(secrets): Override secrets validation flag with tenant config

- checkov/ansible/checks/graph_checks/PanosInterfaceMgmtProfileNoHTTP.yaml
- checkov/ansible/checks/graph_checks/PanosInterfaceMgmtProfileNoTelnet.yaml
- tests/ansible/checks/graph_checks/resources/PanosInterfaceMgmtProfileNoHTTP/expected.yaml
- tests/ansible/checks/graph_checks/resources/PanosInterfaceMgmtProfileNoHTTP/fail.yaml
- tests/ansible/checks/graph_checks/resources/PanosInterfaceMgmtProfileNoHTTP/pass.yaml
- tests/ansible/checks/graph_checks/resources/PanosInterfaceMgmtProfileNoTelnet/expected.yaml
- tests/ansible/checks/graph_checks/resources/PanosInterfaceMgmtProfileNoTelnet/fail.yaml
- tests/ansible/checks/graph_checks/resources/PanosInterfaceMgmtProfileNoTelnet/pass.yaml
- tests/ansible/checks/graph_checks/test_yaml_policies.py
> feat(ansible): Ansible panos int mgmt checks

- checkov/gitlab_ci/common/resource_id_utils.py
- tests/gitlab_ci/resources/resource_images/.gitlab-ci.yml
> fix(gitlab):  fixing include scope that predominant all others

- checkov/terraform/checks/resource/aws/SagemakerNotebookRoot.py
- tests/terraform/checks/resource/aws/example_SagemakerNotebookRoot/main.tf
- tests/terraform/checks/resource/aws/test_SagemakerNotebookRoot.py
> feat(terraform): AWS ensure Sagemaker Notebook users are not Root

- checkov/logging_init.py
> fix(general): fix default log levels for support stream

- checkov/terraform/module_loading/loaders/git_loader.py
> platform(terraform): external module from git fail - log warning

- checkov/terraform/checks/resource/aws/APIGatewayV2RouteDefinesAuthorizationType.py
- tests/terraform/checks/resource/aws/example_APIGatewayV2RouteDefinesAuthorizationType/main.tf
- tests/terraform/checks/resource/aws/test_APIGatewayV2RouteDefinesAuthorizationType.py
> feat(terraform): check routes are authorised

- checkov/common/util/secrets_omitter.py
- tests/common/secrets_omitter/test_secrets_omitter.py
> fix(secrets): Compare abs paths in SecretsOmitter

- checkov/terraform/checks/resource/aws/S3AbortIncompleteUploads.py
- tests/terraform/checks/resource/aws/example_S3AbortIncompleteUploads/main.tf
- tests/terraform/checks/resource/aws/test_S3AbortIncompleteUploads.py
> fix(terraform): refine S3 lifecycle check CKV_AWS_300

- checkov/terraform/checks/resource/aws/IAMRoleAllowAssumeFromAccount.py
- tests/terraform/checks/resource/aws/example_IAMRoleAllowAssumeFromAccount/main.tf
- tests/terraform/checks/resource/aws/test_IAMRoleAllowAssumeFromAccount.py
> fix(terraform): refine IAM assume role check CKV_AWS_61

- docs/7.Scan Examples/Terraform.md
> docs(terraform): Document no private registry

- Pipfile
- Pipfile.lock
- setup.py
> chore: update bc-detect-secrets version to 1.4.16

- checkov/terraform/graph_builder/foreach/abstract_handler.py
- tests/terraform/graph/variable_rendering/test_foreach_renderer.py
> fix(terraform): Fix nested statements in _is_static_foreach_statement

- checkov/main.py
> chore(kubernetes): Allow injecting source_type for whorf reporting

- checkov/terraform/checks/resource/aws/CloudWatchAlarmsEnabled.py
- tests/terraform/checks/resource/aws/example_CloudWatchAlarmsEnabled/main.tf
- tests/terraform/checks/resource/aws/test_CloudWatchAlarmsEnabled.py
> feat(terraform): Ensure that cloudwatch alarms are set on

- checkov/common/checks_infra/solvers/attribute_solvers/length_equals_attribute_solver.py
- checkov/common/checks_infra/solvers/attribute_solvers/length_greater_than_attribute_solver.py
- checkov/common/checks_infra/solvers/attribute_solvers/length_greater_than_or_equal_attribute_solver.py
- checkov/common/checks_infra/solvers/attribute_solvers/length_less_than_attribute_solver.py
- checkov/common/checks_infra/solvers/attribute_solvers/length_less_than_or_equal_attribute_solver.py
- tests/terraform/graph/checks_infra/attribute_solvers/length_equals_solver/DictLength.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/length_equals_solver/test_solver.py
- tests/terraform/graph/checks_infra/attribute_solvers/length_greater_than_or_equal_solver/DictLength.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/length_greater_than_or_equal_solver/test_solver.py
- tests/terraform/graph/checks_infra/attribute_solvers/length_greater_than_solver/DictLength.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/length_greater_than_solver/test_solver.py
- tests/terraform/graph/checks_infra/attribute_solvers/length_less_than_or_equal_solver/DictLength.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/length_less_than_or_equal_solver/test_solver.py
- tests/terraform/graph/checks_infra/attribute_solvers/length_less_than_solver/DictLength.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/length_less_than_solver/test_solver.py
- tests/terraform/graph/checks_infra/attribute_solvers/length_not_equals_solver/DictLengthNotEquals.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/length_not_equals_solver/test_solver.py
- tests/terraform/graph/resources/lengths/main.tf
See https://github.com/bridgecrewio/checkov/issues/4751
[//]: # "
Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose …
> fix(terraform): Length resolvers evaluate length of `dict` as 1.

- checkov/common/checks_infra/checks_parser.py
- tests/terraform/graph/checks/custom_policies/CustomPolicy2.yaml
- tests/terraform/graph/checks/resources/CustomPolicy2/expected.yaml
- tests/terraform/graph/checks/resources/CustomPolicy2/main.tf
- tests/terraform/graph/checks/test_custom_yaml_policies.py
> fix(graph): support string values for resource_types in graph checks properly

- checkov/kubernetes/parser/k8_json.py
- checkov/kubernetes/parser/k8_yaml.py
- tests/kubernetes/parser/examples/yaml/busybox_utf8_bom.yaml
- tests/kubernetes/parser/test_k8_yaml.py
> feat(kubernetes): support non-utf-8 encoded Kubernetes manifest files

- checkov/kubernetes/checks/resource/k8s/ImagePullPolicyAlways.py
- checkov/terraform/checks/resource/kubernetes/ImagePullPolicyAlways.py
- tests/kubernetes/checks/example_ImagePullPolicy/imageWithDigest-DefaultPullPolicy-PASSED.yaml
- tests/kubernetes/checks/test_ImagePullPolicyAlways.py
- tests/terraform/checks/resource/kubernetes/example_ImagePullPolicyAlways/main.tf
- tests/terraform/checks/resource/kubernetes/test_ImagePullPolicyAlways.py
> fix(kubernetes): Don't require ImagePullPolicy when digest (#4776)

- checkov/terraform/checks/graph_checks/gcp/GCPMySQLdbInstancePoint_In_TimeRecoveryBackupIsEnabled.yaml
- tests/terraform/graph/checks/resources/GCPMySQLdbInstancePoint_In_TimeRecoveryBackupIsEnabled/expected.yaml
- tests/terraform/graph/checks/resources/GCPMySQLdbInstancePoint_In_TimeRecoveryBackupIsEnabled/main.tf
CKV2_GCP_20 fails for any non-MySQL instance because of how the conditions are set up. This PR fixes this issue and brings it more in line with conditions used in similar checks.
```
id: "CKV2_GCP_20"
name: "Ensure MySQL DB instance has point-in-time recovery backup configured"
category: "BACKUP_AND_RECOVERY"
```
Name suggests this policy should only apply to MySQL instances, but because of how the conditions are set up, it also fails for any PostgreSQL instance (even if it has point-in-time recovery enabled).
Changed the condition from failing if the instance is not of type MYSQL, to succeeding if it is not. This seems to be more consistent with how it is implemented in …
> fix(terraform): fix false positive CKV2_GCP_20 (fails for any non-MySQL instance)

- checkov/common/output/ai.py
- checkov/common/output/sarif.py
- checkov/common/util/http_utils.py
- tests/common/output/test_sarif_report.py
- tests/common/utils/test_http_utils.py
> fix(general): don't add an invalid URL to helpUri field in SARIF output

- checkov/common/checks/object_registry.py
- checkov/common/output/report.py
> fix(general): be more forgiving of skipped checks without comment

- checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py
- tests/terraform/graph/checks_infra/test_base.py
- tests/terraform/graph/checks_infra/test_base_attribute_solver.py
> chore: move the jsonpath cache to class level

- checkov/terraform/checks/resource/aws/RDSClusterEncryptedWithCMK.py
- tests/terraform/checks/resource/aws/example_RDSClusterEncryptedWithCMK/main.tf
- tests/terraform/checks/resource/aws/test_RDSClusterEncryptedWithCMK.py
> feat(terraform): Ensure that RDS clusters are encrypted using a CMK

- tests/cloudformation/checks/resource/aws/example_NeptuneClusterStorageEncrypted/NeptuneClusterStorageEncrypted-FAILED.yml
- tests/cloudformation/checks/resource/aws/example_NeptuneClusterStorageEncrypted/NeptuneClusterStorageEncrypted-PASSED.yml
> chore: fix cfn-lint issue with Neptune Cluster

- checkov/terraform/checks/resource/gcp/GoogleKMSRotationPeriod.py
- tests/terraform/checks/resource/gcp/example_GoogleKMSRotationPeriod/main.tf
- tests/terraform/checks/resource/gcp/test_GoogleKMSKeyRotationPeriod.py
> fix(terraform): exclude GCP asymmetric keys from key rotation

- checkov/common/runners/runner_registry.py
> fix(general): fix duplicate sarif output

- checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py
- tests/terraform/checks/resource/aws/example_EC2PublicIP/main.tf
- tests/terraform/checks/resource/aws/test_EC2PublicIP.py
- tests/terraform/graph/variable_rendering/test_string_evaluation.py
> feat(terraform): add support for list of dicts in for loop

- checkov/terraform/checks/resource/aws/RDSClusterAuditLogging.py
- tests/terraform/checks/resource/aws/example_RDSClusterAuditLogging/main.tf
- tests/terraform/checks/resource/aws/test_RDSClusterAuditLogging.py
> fix(terraform): limit RDS cluster audit logging to MySQL engine

- checkov/terraform/graph_builder/local_graph.py
- checkov/terraform/graph_manager.py
- tests/terraform/graph/variable_rendering/test_foreach_renderer.py
> fix(terraform): remove duplicate call to convert graph vertices

- checkov/arm/base_resource_negative_value_check.py
- checkov/arm/checks/resource/StorageAccountDisablePublicAccess.py
- tests/arm/checks/resource/example_StorageAccountDisablePublicAccess/FAILED.json
- tests/arm/checks/resource/example_StorageAccountDisablePublicAccess/PASSED.json
- tests/arm/checks/resource/example_StorageAccountDisablePublicAccess/PASSED_2.json
- tests/arm/checks/resource/test_StorageAccountDisablePublicAccess.py
> feat(arm): add Storage accounts disallow public access check for ARM

- checkov/terraform/checks/resource/kubernetes/DockerSocketVolume.py
- tests/terraform/checks/resource/kubernetes/example_DockerSocketVolume/main.tf
> fix(terraform): make sure K8s volume is a dict

- checkov/gitlab_ci/image_referencer/provider.py
…(&run_create_badges_template and *run_create_badges_template)
> fix(general): Dedup results contain multiple identical images if using template syntax

- checkov/secrets/runner.py
- checkov/secrets/utils.py
- tests/secrets/test_utils.py
> feat(secrets): support scanning of secrets in hidden paths

- checkov/common/images/graph/image_referencer_provider.py
- checkov/common/runners/base_runner.py
- checkov/terraform/graph_builder/local_graph.py
- checkov/terraform/graph_builder/utils.py
- tests/terraform/graph/checks/test_yaml_connected_nodes.py
- tests/terraform/graph/checks_infra/connection_solvers/connection_exist_solver/test_solver.py
- tests/terraform/graph/resources/modules/linked_modules/external_modules/terraform-aws-modules/s3-bucket/examples/notification/main.tf
- tests/terraform/graph/resources/output_example/main.tf
> fix(terraform): remove invalid Terraform module reference support

- checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py
- tests/terraform/graph/variable_rendering/test_string_evaluation.py
> fix(terraform): support null values in list of dicts

- Pipfile
- Pipfile.lock
- checkov/common/packaging/version.py
- setup.py
> chore: update bc-detect-secrets version to 1.4.21

- docs/2.Basics/Suppressing and Skipping Policies.md
> docs(sca): Add more ways to skip CVEs

- checkov/terraform/checks/resource/aws/ECSClusterLoggingEncryptedWithCMK.py
- tests/terraform/checks/resource/aws/example_ECSClusterLoggingEncryptedWithCMK/main.tf
- tests/terraform/checks/resource/aws/test_ECSClusterLoggingEncryptedWithCMK.py
> fix(terraform): make the ECS cluster logging check more resilient

- checkov/terraform/graph_builder/local_graph.py
> feat(terraform): cross variable performance improvement

- .github/workflows/build.yml
> chore: publish pypi package via trusted publisher

- checkov/common/output/gitlab_sast.py
- tests/common/output/test_gitlab_sast_report.py
> fix(general): remove invalid URLs in GitLab SAST output

- Pipfile
- Pipfile.lock
- checkov/common/output/cyclonedx.py
- setup.py
> chore: update bc-detect-secrets version to 1.4.24

- checkov/secrets/scan_git_history.py
- tests/secrets/git_history/test_utils.py
- tests/secrets/test_secret_git_history.py
> fix(secrets): fix missing history results when history store is used

- checkov/terraform/checks/resource/aws/EC2Credentials.py
- tests/terraform/checks/resource/aws/example_EC2Credentials/main.tf
- tests/terraform/checks/resource/aws/test_EC2Credentials.py
> fix(terraform): secret- also check user data in launch config and template

- checkov/kubernetes/kubernetes_utils.py
- tests/kubernetes/test_kubernetes_utils.py
> feat(kubernetes): support suppressing custom K8s policies

- Pipfile
- Pipfile.lock
- setup.py
> chore: update bc-detect-secrets version to 1.4.26

- checkov/terraform/checks/resource/aws/CloudWatchLogGroupRetentionYear.py
- tests/terraform/checks/resource/aws/example_CloudWatchLogGroupRetentionYear/main.tf
- tests/terraform/checks/resource/aws/test_CloudWatchLogGroupRetentionYear.py
> fix(terraform): Update CKV_AWS_338 message and retention check for 0

- checkov/terraform/graph_builder/foreach/abstract_handler.py
- tests/terraform/graph/variable_rendering/resources/foreach_examples/foreach_lookup/main.tf
- tests/terraform/graph/variable_rendering/test_foreach_renderer.py
> fix(terraform): fix foreach render value for lookup

- checkov/terraform/checks/resource/azure/StorageAccountName.py
> feat(terraform): Update CKV_AZURE_43 StorageAccountName.py VARIABLE_REFS

- Pipfile
- Pipfile.lock
- checkov/secrets/plugins/custom_regex_detector.py
- checkov/secrets/runner.py
- setup.py
> chore: update bc-detect-secrets version to 1.4.27

- checkov/kustomize/runner.py
- tests/kustomize/graph/resources/example_checks/graph_check.yaml
- tests/kustomize/graph/resources/example_checks/kustomization.yaml
- tests/kustomize/graph/test_running_graph_checks.py
> feat(kustomize): Support inline skips for Kubernetes graph checks

- checkov/main.py
> fix(sca): only run image referencer with sca_image framework

- checkov/common/checks_infra/solvers/connections_solvers/connection_exists_solver.py
- checkov/common/runners/base_runner.py
> chore: make networkx import truly optional

- checkov/kubernetes/graph_builder/graph_components/ResourceKeywordIdentifier.py
- checkov/kubernetes/graph_builder/graph_components/edge_builders/KeywordEdgeBuilder.py
- checkov/kubernetes/graph_builder/graph_components/edge_builders/ServiceAccountEdgeBuilder.py
- checkov/kubernetes/graph_builder/local_graph.py
- tests/kubernetes/graph/test_local_graph.py
> feat(kubernetes): seperate service acoount builder to improve performance

- Pipfile
- Pipfile.lock
- setup.py
> chore: update bc-detect-secrets version to 1.4.28

- checkov/common/util/parser_utils.py
- checkov/terraform/module_loading/content.py
- checkov/terraform/module_loading/loader.py
- checkov/terraform/module_loading/loaders/bitbucket_access_token_loader.py
- checkov/terraform/module_loading/loaders/bitbucket_loader.py
- checkov/terraform/module_loading/loaders/git_loader.py
- checkov/terraform/module_loading/loaders/github_access_token_loader.py
- checkov/terraform/module_loading/loaders/github_loader.py
- checkov/terraform/module_loading/loaders/local_path_loader.py
- checkov/terraform/module_loading/loaders/registry_loader.py
- checkov/terraform/module_loading/loaders/versions_parser.py
- checkov/terraform/module_loading/module_finder.py
- checkov/terraform/module_loading/registry.py
- checkov/terraform/modules/module_objects.py
- checkov/terraform/modules/module_utils.py
- checkov/terraform/tf_parser.py
- mypy.ini
> chore: add type hints to tf modules and module_loading

- .pre-commit-hooks.yaml
> feat(secrets): Add new pre-commit hook for secrets

- checkov/terraform/graph_builder/local_graph.py
- tests/terraform/graph/variable_rendering/expected_foreach_modules_tf_definitions.json
- tests/terraform/graph/variable_rendering/test_renderer.py
- tests/terraform/graph/variable_rendering/test_resources/provider_alias/main.tf
> fix(terraform): fix terraform variable rendering for provider alias

- checkov/kustomize/runner.py
- tests/kustomize/runner/resources/example/overlays/empty/kustomization.yaml
> fix(kustomize): fix empty kustomize file crash

- .github/workflows/security.yaml
> chore: disable checkov-secrets GHA job

- docs/3.Custom Policies/YAML Custom Policies.md
> docs(general): Update operators with examples

- Pipfile
- Pipfile.lock
- setup.py
> chore: update bc-detect-secrets version to 1.4.29

- checkov/common/output/sarif.py
- tests/sca_image/test_output_reports.py
- tests/sca_package/test_output_reports.py
- tests/sca_package_2/test_output_reports.py
> fix(general): fix SARIF output related to security-severity field

- checkov/terraform/checks/resource/gcp/CloudSqlMajorVersion.py
- tests/terraform/checks/resource/gcp/example_CloudPostgreSQLLogDisconnection/main.tf
- tests/terraform/checks/resource/gcp/example_CloudPostgreSQLLogTemp/main.tf
- tests/terraform/checks/resource/gcp/example_CloudPostgreSqlLogStatement/main.tf
- tests/terraform/checks/resource/gcp/example_CloudSqlMajorVersion/main.tf
- tests/terraform/checks/resource/gcp/example_GoogleCloudPostgreSqlEnablePgaudit/main.tf
- tests/terraform/checks/resource/gcp/example_GoogleCloudPostgreSqlLogHostname/main.tf
- tests/terraform/checks/resource/gcp/example_GoogleCloudPostgreSqlLogMinErrorStatement/main.tf
- tests/terraform/graph/checks/resources/GCPMySQLdbInstancePoint_In_TimeRecoveryBackupIsEnabled/main.tf
- tests/terraform/graph/checks/resources/GCPPostgreSQLDatabaseFlaglog_durationIsSetToON/main.tf
- tests/terraform/graph/checks/resources/GCPPostgreSQLDatabaseFlaglog_executor_statsIsSetToOFF/main.tf
- tests/terraform/graph/checks/resources/GCPPostgreSQLDatabaseFlaglog_parser_statsIsSetToOFF/main.tf
- tests/terraform/graph/checks/resources/GCPPostgreSQLDatabaseFlaglog_planner_statsIsSetToOFF/main.tf
- tests/terraform/graph/checks/resources/GCPPostgreSQLDatabaseFlaglog_statement_statsIsSetToOFF/main.tf
> fix(terraform): update latest major version of Postgres to v15

- checkov/common/goget/registry/get_registry.py
- checkov/common/util/file_utils.py
- checkov/terraform/module_loading/loaders/registry_loader.py
- tests/terraform/module_loading/loaders/test_registry_loader.py
> fix(terraform): Unable to download Terraform modules from JFrog Artifactory

- checkov/dockerfile/checks/AliasIsUnique.py
- tests/dockerfile/checks/example_AliasIsUnique/success_platform/Dockerfile
- tests/dockerfile/checks/test_AliasIsUnique.py
> fix(dockerfile): support platform flag in CKV_DOCKER_11

- checkov/terraform/checks/utils/iam_terraform_document_to_policy_converter.py
- tests/terraform/checks/data/aws/example_ResourcePolicyDocument/main.tf
- tests/terraform/checks/data/aws/test_ResourcePolicyDocument.py
- tests/terraform/util/test_iam_converter.py
> fix(terraform): support condition in IAM policy data blocks

- .github/workflows/jekyll-gh-pages.yml
> chore: move GitHub pages flow to hosted runners

- checkov/common/runners/runner_registry.py
> fix(general): Correctly handle cli graphs in case we run with multiprocessing

- checkov/terraform/checks/resource/azure/AKSApiServerAuthorizedIpRanges.py
- tests/terraform/checks/resource/azure/example_AKSApiServerAuthorizedIpRanges/main.tf
- tests/terraform/checks/resource/azure/test_AKSApiServerAuthorizedIpRanges.py
> fix(terraform): adjust CKV_AZURE_6 to comply with new provider version

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/coverage.yaml
- .github/workflows/nightly.yml
- .github/workflows/pipenv-update.yml
- .github/workflows/pr-test.yml
- .github/workflows/pr-title.yml
> chore: change base permission of GHA workflows to contents read

- .pre-commit-hooks.yaml
- checkov/common/util/ext_argument_parser.py
- checkov/main.py
> feat(general): add checkov_diff pre-commit hook for scanning all changed files

- checkov/arm/checks/resource/SQLServerAuditingRetention90Days.py
- tests/arm/checks/resource/example_SQLServerAuditingRetention90Days/sqlServerAuditingRetention90Days-PASSED2.json
- tests/arm/checks/resource/test_SQLServerAuditingRetention90Days.py
> feat(arm): Handle another structure for SQL retention policy

- .github/workflows/build.yml
> chore: leverage GHA reusable workflow to build container images

- docs/3.Custom Policies/Examples.md
> docs(graph): add jsonpath custom policy example

- checkov/terraform/checks/resource/github/SecretsEncrypted.py
- tests/terraform/checks/resource/github/example_SecretsEncrypted/main.tf
- tests/terraform/checks/resource/github/test_SecretsEncrypted.py
> fix(terraform): fix empty value issue for CKV_GIT_4

- checkov/common/bridgecrew/wrapper.py
> chore: make networkx import optional for graph upload

- checkov/common/bridgecrew/platform_integration.py
- checkov/common/util/dockerfile.py
- checkov/dockerfile/runner.py
- checkov/dockerfile/utils.py
- checkov/sca_image/runner.py
- checkov/secrets/runner.py
- tests/dockerfile/test_utils.py
This updated regex pattern includes a negative lookbehind assertion (?<!\.dockerignore) at the end.
Fixes #5218 
Also refactors the term `docker_file` to the more conventional `dockerfile`.
* Not altered, as it would add noise
* Please help me verify.
* Update: Github search `org:bridgecrewio is_docker_file` suggests indeed only used by `checkov3` which uses self-reference.
> fix(dockerfile): negative `is_dockerfile()` lookup on `.dockerignore` suffix

- checkov/terraform/checks/graph_checks/aws/KmsKeyPolicyIsDefined.yaml
- tests/terraform/graph/checks/resources/KmsKeyPolicyIsDefined/expected.yaml
- tests/terraform/graph/checks/resources/KmsKeyPolicyIsDefined/main.tf
- tests/terraform/graph/checks/resources/VPCHasRestrictedSG/main.tf
- tests/terraform/graph/checks/test_yaml_policies.py
> feat(terraform): ensure kms key policy is defined

- checkov/sca_image/runner.py
> fix(sca): fix wrongly invoked Image Referencer scanning when scanning a single file

- checkov/common/bridgecrew/platform_integration.py
> platform(general): Fix local repo generated name if ends with /

- checkov/terraform/checks/resource/aws/RDSCACertIsRecent.py
- tests/terraform/checks/resource/aws/example_RDSCACertIsRecent/main.tf
- tests/terraform/checks/resource/aws/test_RDSCACertIsRecent.py
> fix(terraform): add missing AWS RDS CA certificate identifiers for aws_db_instance resource

- checkov/arm/base_resource_check.py
- checkov/arm/checks/resource/AzureManagedDiscEncryption.py
- tests/arm/checks/resource/example_AzureManagedDiscEncryption/azureManagedDiscEncryption-PASSED_3.json
- tests/arm/checks/resource/test_AzureManagedDiscEncryption.py
- tests/bicep/examples/loop.bicep
- tests/bicep/test_graph_manager.py
- tests/bicep/test_runner.py
> fix(arm): consider encryption property in CKV_AZURE_2

- checkov/common/util/secrets.py
- tests/common/utils/test_secrets_utils.py
> fix(secrets): fix secrets omit crash when value is not string

- checkov/common/models/consts.py
Reverts bridgecrewio/checkov#5263
> fix(general): revert add composer files to supported package files

- checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py
- checkov/common/checks_infra/solvers/complex_solvers/base_complex_solver.py
- checkov/common/checks_infra/solvers/connections_solvers/complex_connection_solver.py
- checkov/common/checks_infra/solvers/connections_solvers/connection_exists_solver.py
- checkov/common/checks_infra/solvers/connections_solvers/connection_not_exists_solver.py
- checkov/common/checks_infra/solvers/connections_solvers/connection_one_exists_solver.py
- checkov/common/graph/checks_infra/debug.py
- checkov/common/graph/checks_infra/registry.py
- checkov/common/util/env_vars_config.py
- tests/common/checks_infra/test_debug.py
> feat(graph): add experimental debug output for graph check evaluation

- checkov/openapi/checks/resource/generic/ClearTextAPIKey.py
- tests/openapi/checks/resource/generic/example_ClearTextAPIKey/fail3.json
- tests/openapi/checks/resource/generic/example_ClearTextAPIKey/fail3.yaml
- tests/openapi/checks/resource/generic/example_ClearTextAPIKey/fail4.json
- tests/openapi/checks/resource/generic/example_ClearTextAPIKey/fail4.yaml
- tests/openapi/checks/resource/generic/example_ClearTextAPIKey/pass3.json
- tests/openapi/checks/resource/generic/example_ClearTextAPIKey/pass3.yaml
- tests/openapi/checks/resource/generic/example_ClearTextAPIKey/pass4.json
- tests/openapi/checks/resource/generic/example_ClearTextAPIKey/pass4.yaml
- tests/openapi/checks/resource/generic/test_ClearTextAPIKey.py
> fix(openapi): Fix CKV_OpenAPI_20

- checkov/terraform/checks/resource/aws/SecretManagerSecret90days.py
- tests/terraform/checks/resource/aws/example_SecretManagerSecret90days/main.tf
- tests/terraform/checks/resource/aws/test_SecretManagerSecret90days.py
> fix(terraform): fix invalid value in CKV_AWS_304

- checkov/terraform/checks/graph_checks/aws/GuardDutyIsEnabled.yaml
- tests/terraform/graph/checks/resources/GuardDutyIsEnabled/expected.yaml
- tests/terraform/graph/checks/resources/GuardDutyIsEnabled/main.tf
> fix(terraform): support new field in CKV2_AWS_3

- checkov/common/typing.py
- checkov/common/util/env_vars_config.py
- checkov/kubernetes/kubernetes_utils.py
- checkov/kubernetes/runner.py
- checkov/kustomize/runner.py
- tests/kustomize/test_runner.py
- tests/kustomize/test_runner_image_referencer.py
> feat(kustomize): Add origin annotations to calculate bases of kustomize checks

- .github/workflows/build.yml
- checkov/common/typing.py
- checkov/kubernetes/kubernetes_utils.py
- checkov/kubernetes/runner.py
- checkov/kustomize/runner.py
- tests/kustomize/test_runner.py
- tests/kustomize/test_runner_image_referencer.py
> feat(kustomize): add back reverted kustomize annotations and update build github action to use github runners

- checkov/kustomize/runner.py
> fix(kustomize): Checked for existence of caller_file_path in definitions_raw 

- checkov/kubernetes/graph_builder/local_graph.py
- checkov/kustomize/runner.py
> feat(kustomize): Support child k8s resources inside kustomize origin annotations

- checkov/kustomize/runner.py
> fix(kustomize): Added support for case where no parents are found for the relative fie path

- Pipfile
- Pipfile.lock
- checkov/terraform/graph_builder/variable_rendering/renderer.py
- setup.py
> chore: bound igraph version to 0.10.5 till aarch64 wheels are available

- docs/2.Basics/Suppressing and Skipping Policies.md
> docs(sca): Add SCA skip comments to docs

- README.md
- docs/2.Basics/Installing Checkov.md
> docs(general): update docs about installation guidelines

- checkov/secrets/plugins/custom_regex_detector.py
> fix(secrets): handle regex error in custom secrets gracefully

- checkov/kustomize/runner.py
> fix(kustomize): Avoid index error when calculating file path

- Pipfile
- Pipfile.lock
- setup.py
> chore: update deps and upper bound igraph to lower 0.11.0 to better test it when released

- checkov/terraform/checks/resource/aws/DocDBAuditLogs.py
- tests/terraform/checks/resource/aws/test_DocDBAuditLogs.py
> fix(terraform): Fix CKV_AWS_104 to support new values

- checkov/common/bridgecrew/platform_integration.py
- tests/kustomize/runner/resources/image_referencer/overlays/prod/kustomization.yaml
- tests/kustomize/test_runner_image_referencer.py
> platform(general): remove obsolete run config fallback API call

- docs/4.Integrations/GitHub Actions.md
We need to update the following action because not doing so will result on an error on certain architectures, see error below.
```
`Run actions/setup-python@v1
with:
python-version: 3.8
architecture: x64
Error: Version 3.8 with arch x64 not found
Available versions: `
```
Version 4 of this action fixed the issue for me.
> docs(gha): Update setup-python version in GitHub Actions.md

- checkov/common/util/ext_argument_parser.py
> feat(general): allow `--var-file` to be passed as environment variable

- .pre-commit-config.yaml
- checkov/common/bridgecrew/platform_integration.py
- checkov/common/output/secrets_record.py
- checkov/common/runners/runner_registry.py
- checkov/common/secrets/consts.py
- checkov/common/util/parser_utils.py
- checkov/runner_filter.py
- checkov/secrets/consts.py
- checkov/secrets/git_history_store.py
- checkov/secrets/git_types.py
- checkov/secrets/runner.py
- checkov/secrets/scan_git_history.py
- checkov/terraform/runner.py
- pyproject.toml
- tests/common/output/conftest.py
- tests/secrets/test_secrets_verification.py
> chore: add import-linter to enforce module independency

- checkov/common/bridgecrew/platform_key.py
In Mac, if the credentials file is empty, f.readline() == '' and it crashes the initialization of checkov later on
[//]: # "
Additionally a scope is needs to be added to the prefix, …
> fix(general): Fix empty credentials file issue

- checkov/terraform/graph_builder/local_graph.py
- checkov/terraform/plan_parser.py
> feat(terraform): Add __address__ field on vertices even if render_variables is set to False

- checkov/terraform/checks/data/aws/GithubActionsOIDCTrustPolicy.py
> fix(terraform): fix ordering issue in CKV_AWS_358

- checkov/terraform/graph_builder/foreach/module_handler.py
> fix(terraform): Fix for-each/count updating inner for each index for every child resource

- checkov/terraform/runner.py
> fix(terraform): Replaced / with os.pathsep to support windows better in terraform runner

- checkov/kustomize/runner.py
- checkov/kustomize/utils.py
- tests/kustomize/test_utils.py
> fix(kustomize): support kubectl 1.28+

- checkov/secrets/runner.py
- tests/secrets/test_secret_git_history.py
This PR fixes resource for git history scan by concating commit hash with resource_id.
This is needed since for git history that is the definition of violation resouce.
> feat(secrets): fix resource in git history scan

- checkov/terraform/checks/graph_checks/aws/SGAttachedToResource.yaml
- tests/terraform/graph/checks/resources/SGAttachedToResource/expected.yaml
- tests/terraform/graph/checks/resources/SGAttachedToResource/main.tf
* Add aws_appstream_fleet as connected resource for CKV2_AWS_5
[//]: # "
Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt …
> fix(terraform): extend CKV2_AWS_5 to include aws_appstream_fleet (#5487)

- checkov/terraform_json/parser.py
- checkov/terraform_json/runner.py
- tests/terraform_json/examples/cdk.tf.json
- tests/terraform_json/test_graph_manager.py
> fix(terraform_json): correctly parse data blocks in Terraform JSON

- checkov/terraform/tf_parser.py
- tests/terraform/parser/resources/parse_backtrack_module/example/main.tf
- tests/terraform/parser/resources/parse_backtrack_module/main.tf
- tests/terraform/parser/test_new_parser_modules.py
> fix(terraform): continue processing of TF modules in the same file

- checkov/terraform/checks/resource/azure/AppServicePublicAccessDisabled.py
- checkov/terraform/checks/resource/azure/DataLakeStoreEncryption.py
- checkov/terraform/checks/resource/azure/FunctionAppPublicAccessDisabled.py
- checkov/terraform/checks/resource/azure/RedisCachePublicNetworkAccessEnabled.py
- tests/terraform/checks/resource/azure/example_AppServicePublicAccessDisabled/main.tf
- tests/terraform/checks/resource/azure/example_FunctionAppPublicAccessDisabled/main.tf
- tests/terraform/checks/resource/azure/test_AppServicePublicAccessDisabled.py
- tests/terraform/checks/resource/azure/test_FunctionAppPublicAccessDisabled.py
- tests/terraform/image_referencer/test_runner_azure_resources.py
> feat(terraform): add public network checks for Azure Function and Web Apps

- checkov/terraform/checks/resource/aws/NeptuneDBClustersCopyTagsToSnapshots.py
- tests/terraform/checks/resource/aws/example_NeptuneDBClustersCopyTagsToSnapshots/NeptuneDBClustersCopyTagsToSnapshots.tf
- tests/terraform/checks/resource/aws/test_NeptuneDBClustersCopyTagsToSnapshots.py
> feat(terraform): add check Neptune DB clusters should be configured to copy tags to snapshots

- .github/workflows/build.yml
This PR changes the integ. tests to not run Py3.7 since it is failing on a 3.7 specific issue.
Since we're moving away from 3.7 anyway, we can skip this now.
> feat(general): remove 3.7 integ. test

- .github/workflows/pr-test.yml
- checkov/terraform/module_loading/loaders/git_loader.py
This PR changes the pr_test to remove Py3.7 integ. tests and adds code change to force trigger new tag.
> feat(general): remove line to force code change

- checkov/terraform/base_runner.py
- checkov/terraform/plan_runner.py
- checkov/terraform/plan_utils.py
- checkov/terraform/runner.py
- checkov/terraform_json/runner.py
- mypy.ini
> chore: finish up type hints under terraform folder

- checkov/terraform/graph_builder/foreach/abstract_handler.py
- checkov/terraform/graph_builder/foreach/module_handler.py
- checkov/terraform/modules/module_objects.py
- tests/terraform/graph/variable_rendering/expected_foreach_module_dup_foreach.json
- tests/terraform/graph/variable_rendering/test_foreach_renderer.py
> fix(terraform): Nested source_module_objects with missing foreach key

- checkov/common/bridgecrew/platform_integration.py
- checkov/common/util/http_utils.py
- checkov/common/vcs/base_vcs_dal.py
- docs/2.Basics/Visualizing Checkov Output.md
> platform(general): expose retry and timeout configuration for interaction with the platform

- checkov/terraform/checks/resource/kubernetes/WildcardRoles.py
> fix(terraform): Adding missing null checks

- checkov/terraform/checks/resource/azure/AKSEphemeralOSDisks.py
- tests/terraform/checks/resource/azure/example_AKSEphemeralOSDisks/main.tf
- tests/terraform/checks/resource/azure/test_AKSEphemeralOSDisks.py
Fixes #5583 
Temporary data can contain sensitive data at some points, by using ephemeral disks, we ensure that data written to OS disk is stored on local VM storage and isn't persisted to Azure Storage
Azure automatically replicates data stored in the managed OS disk of a virtual machine to Azure storage to avoid data loss in case the virtual machine needs to be relocated to another host.
Generally speaking, containers are not designed to have local state persisted to the managed OS disk, hence this behavior offers limited value to AKS hosted while providing some drawbacks, including slower node provisioning and higher read/write latency.
Ephemeral disks allow us also to …
> feat(terraform): Ensure ephemeral disks are used for OS disks

- checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
- tests/common/integration_features/test_suppressions_integration.py
> feat(sca): support case where there are no cves suppressions

- checkov/terraform/module_loading/loaders/local_path_loader.py
- checkov/terraform/module_loading/module_finder.py
- checkov/terraform/module_loading/module_params.py
- checkov/terraform/module_loading/registry.py
- docs/7.Scan Examples/Terraform.md
- tests/terraform/module_loading/data/tf_managed_modules/.terraform/modules/log_group/modules/log-group/main.tf
- tests/terraform/module_loading/data/tf_managed_modules/.terraform/modules/log_group/modules/log-group/outputs.tf
- tests/terraform/module_loading/data/tf_managed_modules/.terraform/modules/log_group/modules/log-group/variables.tf
- tests/terraform/module_loading/data/tf_managed_modules/.terraform/modules/log_group/modules/log-group/versions.tf
- tests/terraform/module_loading/data/tf_managed_modules/.terraform/modules/modules.json
- tests/terraform/module_loading/data/tf_managed_modules/main.tf
- tests/terraform/module_loading/test_runner.py
- tests/terraform/module_loading/test_tf_module_finder.py
> feat(terraform): support scanning of Terraform managed modules instead of downloading them

- checkov/cloudformation/checks/resource/aws/LambdaEnvironmentEncryptionSettings.py
- checkov/terraform/checks/resource/aws/EKSPublicAccessCIDR.py
- checkov/terraform/checks/resource/aws/LambdaEnvironmentEncryptionSettings.py
- checkov/terraform/checks/resource/aws/SNSTopicEncryption.py
- checkov/terraform/checks/resource/azure/MariaDBPublicAccessDisabled.py
- checkov/terraform/checks/resource/gcp/GKEClusterLogging.py
> chore: improve various Terraform checks

- checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py
- tests/terraform/graph/checks_infra/attribute_solvers/jsonpath_equals_solver/EcsWithMerge.yaml
- tests/terraform/graph/checks_infra/attribute_solvers/jsonpath_equals_solver/test_solver.py
- tests/terraform/graph/resources/ecs_with_merge/main.tf
> feat(terraform): Support for merge func inside jsondecode

- checkov/terraform/checks/resource/azure/SQLDatabaseZoneRedundant.py
- tests/terraform/checks/resource/azure/example_SQLDatabaseZoneRedundant/main.tf
- tests/terraform/checks/resource/azure/test_SQLDatabaseZoneRedundant.py
> feat(terraform): Ensure that the SQL database is zone-redundant

- checkov/arm/checks/resource/VMEncryptionAtHostEnabled.py
- tests/bicep/checks/resource/azure/example_VMEncryptionAtHostEnabled/main.bicep
- tests/bicep/checks/resource/azure/test_VMEncryptionAtHostEnabled.py
> fix(bicep): enforce encryption flag to be string for CKV_AZURE_97

- checkov/sast/engines/prisma_engine.py
> fix(sast): fix error logs coming from SAST

- checkov/common/bridgecrew/severities.py
- checkov/sast/engines/prisma_engine.py
- checkov/sast/prisma_models/library_input.py
- tests/sast/test_runner.py
> platform(general): Add SAST enforcement rules and check severity thresholds

- checkov/secrets/plugins/detector_utils.py
- tests/secrets/sanity/iac_fp/main.tf
> fix(secrets): fix secret FP of client_secret_setting_name

- checkov/common/bridgecrew/platform_integration.py
- checkov/common/output/report.py
- checkov/common/runners/runner_registry.py
- checkov/common/util/consts.py
- checkov/contributor_metrics.py
- checkov/main.py
- dangerfile.ts
> platform(general): Do not crash the run if S3 integration fails during setup, upload, or finalize

- checkov/sast/engines/prisma_engine.py
> fix(sast): adjust SAST file pattern search

- checkov/terraform/graph_builder/local_graph.py
- checkov/terraform/graph_builder/utils.py
- tests/terraform/graph/graph_builder/test_utils.py
- tests/terraform/graph/variable_rendering/resources/foreach_examples/foreach_tfvars/main.tf
- tests/terraform/graph/variable_rendering/resources/foreach_examples/foreach_tfvars/terraform.tfvars
- tests/terraform/graph/variable_rendering/test_renderer.py
> fix(terraform): fix variable rendering for foreach resources with dot included names

- checkov/common/output/cyclonedx.py
- tests/common/output/test_cyclonedx_report.py
> fix(general): fix duplicate components in CycloneDX report

- checkov/common/bridgecrew/integration_features/features/vulnerabilities_integration.py
- tests/common/integration_features/test_vulnerabilities_integration.py
*  Setting only relevant cves for the extracted reachable-functions with risk factor of ReachableFunction as True
> fix(sca): Setting only relevant cves for the extracted reachable functions with risk factor of ReachableFunction as True

- checkov/terraform/checks/resource/aws/MQBrokerVersion.py
- tests/terraform/checks/resource/aws/example_MQBrokerVersion/main.tf
Apache ActiveMQ support for version5.16 ended on Mar 18, 2023
The change in valid versions, as now 5.17 is the lowest supported version and the newest available.
> fix(terraform): CKV_AWS_208 valid Amazon MQ versions

- checkov/main.py
> fix(general): do not require a repo ID when using an API key and --list

- integration_tests/prepare_data.sh
- integration_tests/run_integration_tests.sh
- integration_tests/test_checkov_cli_integration_report.py
- integration_tests/test_checkov_ext_module_cloning.py
- integration_tests/test_checkov_platform_only_policies.py
> chore: Update integration tests

- checkov/common/bridgecrew/platform_integration.py
- checkov/common/output/report.py
- checkov/common/runners/runner_registry.py
> platform(general): print the log upload location if the --support flag is used

- checkov/ansible/runner.py
- checkov/argo_workflows/runner.py
- checkov/azure_pipelines/runner.py
- checkov/bitbucket_pipelines/runner.py
- checkov/circleci_pipelines/runner.py
- checkov/common/bridgecrew/platform_integration.py
- checkov/common/models/enums.py
- checkov/common/parallelizer/parallel_runner.py
- checkov/common/runners/object_runner.py
- checkov/common/runners/runner_registry.py
- checkov/common/vcs/base_vcs_dal.py
- checkov/example_runner/runner.py
- checkov/github_actions/runner.py
- checkov/gitlab_ci/runner.py
- checkov/helm/runner.py
- checkov/json_doc/runner.py
- checkov/openapi/runner.py
- checkov/sca_package_2/runner.py
- checkov/secrets/runner.py
- checkov/serverless/runner.py
- checkov/terraform/module_loading/module_finder.py
- checkov/terraform/runner.py
- checkov/yaml_doc/runner.py
- tests/terraform/runner/test_runner.py
> feat(general): add possibility to change parallelization type

- checkov/common/bridgecrew/platform_integration.py
- checkov/sast/runner.py
- checkov/sca_package_2/runner.py
> chore: reinitialize platform integration in SAST runner

- checkov/cloudformation/checks/resource/aws/LambdaEnvironmentCredentials.py
- checkov/common/util/secrets.py
- tests/cloudformation/checks/resource/aws/example_LambdaEnvironmentCredentials/PASS.yaml
- tests/cloudformation/checks/resource/aws/test_LambdaEnvironmentCredentials.py
> fix(cloudformation): ignore unresolved references in CKV_AWS_45

- checkov/terraform/checks/resource/azure/FunctionAppMinTLSVersion.py
- tests/terraform/checks/resource/azure/example_FunctionAppMinTLSVersion/main.tf
- tests/terraform/checks/resource/azure/test_FunctionAppMinTLSVersion.py
- tests/terraform/image_referencer/test_runner_azure_resources.py
hi, this closes #5721.
notes:
- deprecation: azurerm_function_app will be replaced in version 4.0 by azurerm_linux_function_app and azurerm_windows_function_app. (same thing for slots) 
- similar: [here](https://github.com/bridgecrewio/checkov/blob/5796faf8523acbe4fb5f5fb340c682a27b7851d8/checkov/terraform/checks/resource/azure/AppServiceMinTLSVersion.py#L9) you can also add slots (azurerm_linux_web_app_slot, azurerm_windows_web_app_slot)
> fix(terraform): check min TLS version also on azure app slots

- checkov/terraform/graph_builder/local_graph.py
For the TF plan, we failed to match the connection between resources when we had two resources with the same name from two different modules, 
Fixed by asserting the address, it is not the same as Terraform that we are checking the path because everything is in the same file.
> fix(terraform_plan): TF plan resources connection fix

- checkov/secrets/runner.py
> fix(secrets): don't reinitialize the upload client without API key usage

- checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py
- checkov/common/bridgecrew/integration_features/features/licensing_integration.py
- checkov/common/bridgecrew/integration_features/features/policies_3d_integration.py
- checkov/common/bridgecrew/integration_features/features/policy_metadata_integration.py
- checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
- checkov/common/bridgecrew/platform_integration.py
- checkov/common/checks/base_check.py
- checkov/common/graph/checks_infra/base_check.py
- checkov/common/parallelizer/parallel_runner.py
- checkov/common/runners/object_runner.py
- checkov/common/typing.py
- checkov/main.py
- checkov/secrets/runner.py
- checkov/serverless/runner.py
- checkov/terraform/module_loading/module_finder.py
- docs/7.Scan Examples/Terraform.md
- tests/secrets/test_plugin_multiline_json.py
- tests/secrets/test_plugin_multiline_yml.py
- tests/terraform/module_loading/test_runner.py
- tests/test_main.py
Reverting commit set default parallelization type to spawn and leverage Terraform downloaded module by default (#5760) due to error `AssertionError: daemonic processes are not allowed to have children`
[//]: # "
- platform: to indicate a …
> fix(general): Revert parallelization commit

- checkov/terraform/checks/resource/azure/FunctionAppsAccessibleOverHttps.py
- tests/terraform/checks/resource/azure/example_FunctionAppAccessibleOverHttps/main.tf
- tests/terraform/checks/resource/azure/test_FunctionAppsAccessibleOverHttps.py
- tests/terraform/image_referencer/test_runner_azure_resources.py
hi, this closes #5720.
*`require_https` was in the `auth_settings_v2` block (not in site_config as mentioned in issue).
> fix(terraform): Ensure HTTPS in Azure Function App and App Slots

- checkov/common/bridgecrew/platform_integration.py
- tests/common/test_platform_integration.py
> platform(general): handle the updated on prem response from the platform

- checkov/terraform/checks/graph_checks/oci/OCI_NSGNotAllowRDP.yaml
- tests/terraform/graph/checks/resources/OCI_NSGNotAllowRDP/expected.yaml
- tests/terraform/graph/checks/resources/OCI_NSGNotAllowRDP/main.tf
> fix(terraform): Fix range issue in OCI RDP check

- checkov/terraform/checks/graph_checks/aws/VPCPeeringRouteTableOverlyPermissive.yaml
- tests/terraform/runner/resources/plan/tfplan.json
- tests/terraform/runner/test_plan_runner.py
This PR fixes the VPCPeeringRouteTableOverlyPermissive check and adds appropriate tests to make sure we do not flag empty vpc_peering_connection_id string as failed.
> feat(terraform): fix for check VPCPeeringRouteTableOverlyPermissive and add tests

- checkov/terraform/tf_parser.py
> feat(terraform): Used parallel run to run all split_graph iterations

- checkov/terraform/checks/resource/azure/AzureDefenderDisabledForResManager.py
- tests/terraform/checks/resource/azure/example_AzureDefenderDisabledForResManager/main.tf
- tests/terraform/checks/resource/azure/test_AzureDefenderDisabledForResManager.py
> fix(terraform): Fix CKV_Azure_234

- checkov/terraform/checks/graph_checks/azure/AzureStorageAccConfigWithoutBlobAnonymousAccess.yaml
- tests/terraform/graph/checks/resources/AzureStorageAccConfigWithoutBlobAnonymousAccess/expected.yaml
- tests/terraform/graph/checks/resources/AzureStorageAccConfigWithoutBlobAnonymousAccess/main.tf
For any organization serious about security, it does not make sense to have the possibility to add anonymous public blob containers at all. Therefore, ensure that allow_nested_public_items (= allow blob anonymous access in web UI) is set to false.
https://learn.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure?tabs=portal
"Warning: When a container is configured for anonymous access, any client can read data in that container. Anonymous access presents a potential security risk, so if your scenario does not require it, we recommend that you remediate …
> feat(terraform): add CKV2_AZURE_47, ensure storage account is configured without blob anonymous access

- checkov/common/bridgecrew/platform_integration.py
> fix(sast): fix sast cdk code location paths

- checkov/terraform/checks/resource/gcp/CloudSqlMajorVersion.py
- tests/terraform/checks/resource/gcp/example_CloudSqlMajorVersion/main.tf
> fix(terraform): CKV_GCP_79  Upgrade CloudSQL SQLSERVER major version to 2022

- tests/terraform/module_loading/test_registry.py
> fix(terraform): Manually fixed test for loading terraform registry to be with commit hash instead of version tag

- checkov/terraform/graph_builder/foreach/abstract_handler.py
- tests/terraform/graph/variable_rendering/test_foreach_renderer.py
> fix(terraform): Correctly relace foreach_value inside _update_attributes for complex cases

- checkov/terraform/checks/graph_checks/azure/AzureAntimalwareIsConfiguredWithAutoUpdatesForVMs.yaml
- docs/3.Custom Policies/YAML Custom Policies.md
Validate that there is only one `azurerm_virtual_machine_extension` connection with type attribute equals `IaaSAntimalware` instead of enforcing all `azurerm_virtual_machine_extension` connections
> fix(terraform): fix check CKV2_AZURE_10

- Pipfile
- Pipfile.lock
- checkov/arm/context_parser.py
- checkov/kubernetes/graph_builder/local_graph.py
- checkov/kubernetes/kubernetes_utils.py
- checkov/kubernetes/runner.py
- setup.py
> fix(general): downgrade botocore dependency

- checkov/terraform/checks/resource/aws/APIGatewayMethodSettingsCacheEncrypted.py
- tests/terraform/checks/resource/aws/example_APIGatewayMethodSettingsCacheEncrypted/main.tf
- tests/terraform/checks/resource/aws/test_APIGatewayMethodSettingCacheEncrypted.py
> fix(terraform): CKV_AWS_308 - checked if caching was enabled and only then check for encryption of cache

- checkov/terraform/graph_builder/variable_rendering/safe_eval_functions.py
- tests/terraform/graph/variable_rendering/test_string_evaluation.py
> feat(terraform): Added support for `try` function in evaluate_terraform

- checkov/common/output/csv.py
- tests/common/output/test_bom_report.py
- tests/common/runner_registry/test_runner_registry.py
> feat(general): add policy name and guidelines to CSV output

- checkov/secrets/plugins/detector_utils.py
- tests/secrets/sanity/iac_fp/main.json
This PR adds a pre-processing phase to the remove_fp_secrets_in_keys method, before we output a detected secret.
In this pre-processing phase we attempt to detect when a potential secret is in the middle of the line, followed by another delimeter (in our case ":") and in this case we treat that secret as the line start, so our FP detection mechanisms will kick in.
> feat(secrets): fix entropy detector FP

- checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py
- checkov/terraform/graph_builder/variable_rendering/safe_eval_functions.py
- tests/terraform/graph/variable_rendering/test_string_evaluation.py
> fix(terraform): Fixed bug in evaluate_conditional_expression and added zipmap support

- checkov/terraform/modules/module_utils.py
- tests/terraform/runner/resources/for_each/main.tf
- tests/terraform/runner/resources/for_each/simple/main.tf
- tests/terraform/runner/test_runner.py
This PR fixes the extraction of module from resource of for_each, preventing correct handling of first resource (index 0) and thus missing any violations for this resource.
> feat(terraform): fix for_each resource handling

- Pipfile
- Pipfile.lock
- setup.py
This PR manually bumps the bc-detect-secrets dependency in Pipfile, Pipfile.lock and setup.py.
> feat(secrets): bump manually bc-detect-secrets

- checkov/terraform/graph_builder/local_graph.py
This PR adds a fix for the _connect_module_provider method, for when tf_def item is a string and we first need to convert it to TFModule and then the flow shall continue as usual.
> feat(terraform): add fix for when tf_def is a string

- checkov/terraform_json/parser.py
> fix(general): remove limitation of resource and provider in tf.json file

- checkov/common/bridgecrew/integration_features/features/policy_metadata_integration.py
- checkov/common/bridgecrew/platform_integration.py
- checkov/common/util/ext_argument_parser.py
- checkov/docs_generator.py
- checkov/main.py
- checkov/runner_filter.py
- tests/common/integration_features/test_policy_metadata_integration.py
- tests/common/test_runner_filter.py
> feat(general): add policy metadata filter exception flag

- .github/workflows/nightly.yml
- checkov/secrets/scan_git_history.py
> feat(general): Update the releases' zip file names to be generic

- checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
- checkov/common/bridgecrew/platform_integration.py
- checkov/common/util/str_utils.py
* enabling suppression in the cli-output for IR-files and dockerfiles
* initing the source_id from in the platform_integration
> fix(sca): enabling suppression in the cli-output for IR-files and dockerfiles

- checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py
- tests/terraform/graph/variable_rendering/test_string_evaluation.py
> fix(terraform): Fix conditional expression evaluation logic with compare

- Pipfile
- setup.py
> fix(secrets): Azure Storage Key detector updates in bc-detect-secrets 1.5.7

- checkov/terraform/checks/resource/gcp/CloudArmorWAFACLCVE202144228.py
- tests/terraform/checks/resource/gcp/example_CloudArmorWAFACLCVE202144228/main.tf
- tests/terraform/checks/resource/gcp/test_CloudArmorWAFACLCVE202144228.py
Either evaluatePreconfiguredExpr('cve-canary') rule can be used or you can configure a rule by using evaluatePreconfiguredWaf()
https://cloud.google.com/armor/docs/waf-rules#cves_and_other_vulnerabilities
[//]: # "
- platform: to indicate a …
> feat(terraform): Update CloudArmorWAFACLCVE202144228.py

- checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py
> chore(sca): When trying to load policies, continue if it's custom

- checkov/terraform/checks/module/generic/RevisionVersionTag.py
- tests/terraform/checks/module/generic/example_RevisionVersionTag/main.tf
- tests/terraform/checks/module/generic/test_RevisionVersionTag.py
- tests/terraform/runner/test_runner.py
> feat(terraform): add check for tf module versioned tag

- checkov/common/util/type_forcers.py
- tests/common/utils/test_type_forcers.py
platform(general): Fix policy.name to use the spaces as specified on CLI.
When adding the flag policy.name with a valid value of a particular policy, only that policy should run and return in the result. 
checkov -f main.tf --skip-results-upload --repo-id ts/test --policy-metadata-filter policy.name="Data exfiltration allowed without resource constraints"
Instead all the policies are returned (and hence run). This is fixed by handling the spaces in the policy names and leading and trailing whitespaces appropriately.
When adding the flag policy.name with a valid value of a particular policy, only that policy should run and return in the result. Instead all …
> platform(general): Fix policy.name to use the spaces as specified on CLI.

- checkov/arm/checks/resource/StorageSyncPublicAccessDisabled.py
- tests/arm/checks/resource/example_StorageSyncPublicAccessDisabled/fail1.json
- tests/arm/checks/resource/example_StorageSyncPublicAccessDisabled/fail2.json
- tests/arm/checks/resource/example_StorageSyncPublicAccessDisabled/pass.json
- tests/arm/checks/resource/test_StorageSyncPublicAccessDisabled.py
> feat(arm): StorageSyncPublicAccessDisabled

- checkov/arm/checks/resource/AzureMLWorkspacePrivateEndpoint.py
- tests/arm/checks/resource/example_AzureMLWorkspacePrivateEndpoint/fail.json
- tests/arm/checks/resource/example_AzureMLWorkspacePrivateEndpoint/fail2.json
- tests/arm/checks/resource/example_AzureMLWorkspacePrivateEndpoint/pass.json
- tests/arm/checks/resource/example_AzureMLWorkspacePrivateEndpoint/pass2.json
- tests/arm/checks/resource/test_AzureMLWorkspacePrivateEndpoint.py
> feat(arm): Add check for AzureML workspace not configured with private endpoint

- checkov/secrets/runner.py
- tests/secrets/test_prioritise_secrets.py
> feat(secrets): Add _prioritise_secrets by 3 levels of severity

- checkov/arm/checks/resource/AppServiceDotnetFrameworkVersion.py
- checkov/terraform/checks/resource/azure/AppServiceDotnetFrameworkVersion.py
- tests/arm/checks/resource/example_AppServiceDotnetFrameworkVersion/passed.json
- tests/terraform/checks/resource/azure/example_AppServiceDotnetFrameworkVersion/main.tf
This PR drops support for dotnet v7.0 in our azure checks and switches to v8.0.
Fixes #6343
> feat(azure): drop support for dotnet v7.0

- checkov/terraform/checks/resource/aws/S3AbortIncompleteUploads.py
- tests/terraform/runner/resources/plan/tf_plan_filtered_rule_fail.json
- tests/terraform/runner/resources/plan/tf_plan_filtered_rule_success.json
- tests/terraform/runner/test_plan_runner.py
This PR fixes the CKV_AWS_300 check by taking into account the filterings available for the S3 lifecycle directive.
> feat(terraform): add fix for ckv_aws_300

- integration_tests/test_checkov_cli_integration_report.py
> fix(general): bitbucket integration test failure

- checkov/arm/checks/resource/KeyVaultDisablesPublicNetworkAccess.py
- tests/arm/checks/resource/example_KeyVaultDisablesPublicNetworkAccess/fail1.json
- tests/arm/checks/resource/example_KeyVaultDisablesPublicNetworkAccess/fail2.json
- tests/arm/checks/resource/example_KeyVaultDisablesPublicNetworkAccess/fail3.json
- tests/arm/checks/resource/example_KeyVaultDisablesPublicNetworkAccess/fail4.json
- tests/arm/checks/resource/example_KeyVaultDisablesPublicNetworkAccess/fail5.json
- tests/arm/checks/resource/example_KeyVaultDisablesPublicNetworkAccess/pass1.json
- tests/arm/checks/resource/example_KeyVaultDisablesPublicNetworkAccess/pass2.json
- tests/arm/checks/resource/example_KeyVaultDisablesPublicNetworkAccess/pass3.json
- tests/arm/checks/resource/example_KeyVaultDisablesPublicNetworkAccess/pass4.json
- tests/arm/checks/resource/test_KeyVaultDisablesPublicNetworkAccess.py
> feat(arm): KeyVaultDisablesPublicNetworkAccess

- checkov/arm/checks/resource/ACRContainerScanEnabled.py
- tests/arm/checks/resource/example_ACRContainerScanEnabled/fail.json
- tests/arm/checks/resource/example_ACRContainerScanEnabled/pass.json
- tests/arm/checks/resource/test_ACRContainerScanEnabled.py
> feat(arm): add CKV_AZURE_163  Enable vulnerability scanning for container images

- tests/cloudformation/checks/resource/aws/example_DeprecatedLambdaRuntime/example.yaml
- tests/cloudformation/checks/resource/aws/example_DeprecatedLambdaRuntime/exampleSAM.yaml
> chore: Ignore cfn-lint e2533 for deprected runtime on failed tests for deprecated runtime

- checkov/terraform/checks/graph_checks/aws/S3CMKRegularRotation.yaml
> fix(terraform): Fix name of CKV2_AWS_67 to be more clear

- checkov/terraform/checks/resource/aws/ECSClusterLoggingEncryptedWithCMK.py
> fix(terraform): Update CKV_AWS_224 title

- checkov/dockerfile/checks/RunUsingAPT.py
- tests/dockerfile/checks/example_RunUsingAPT/failure2/Dockerfile
- tests/dockerfile/checks/example_RunUsingAPT/failure3/Dockerfile
- tests/dockerfile/checks/example_RunUsingAPT/success2/Dockerfile
- tests/dockerfile/checks/test_RunUsingAPT.py
> fix(terraform): Fix when apt is in rm statement

- checkov/common/sca/reachability/package_alias_mapping/nodejs/utils.py
- tests/common/sca/reachability/test_alias_mapping_creator.py
> fix(sca): Support parsing json with comments

- .github/workflows/pr-test.yml
- tests/cloudformation/checks/resource/aws/Cloudsplaining_IAMPermissionsManagement/PASSED.yaml
- tests/cloudformation/checks/resource/aws/Cloudsplaining_ManagedPolicy/PASSED.yaml
- tests/cloudformation/checks/resource/aws/example_AuroraEncryption/AuroraEncryption-PASSED.yaml
> chore: Focus cfn-lint on edited files

- checkov/arm/checks/resource/AppServiceSlotHTTPSOnly.py
- tests/arm/checks/resource/example_AppServiceSlotHTTPSOnly/fail.json
- tests/arm/checks/resource/example_AppServiceSlotHTTPSOnly/fail2.json
- tests/arm/checks/resource/example_AppServiceSlotHTTPSOnly/pass.json
- tests/arm/checks/resource/example_AppServiceSlotHTTPSOnly/pass2.json
- tests/arm/checks/resource/test_AppServiceSlotHTTPSOnly.py
> feat(arm): ARM AppServiceSlotHTTPSOnly

- checkov/arm/checks/resource/ACRAdminAccountDisabled.py
- tests/arm/checks/resource/example_ACRAdminAccountDisabled/fail.json
- tests/arm/checks/resource/example_ACRAdminAccountDisabled/pass.json
- tests/arm/checks/resource/test_ACRAdminAccountDisabled.py
> feat(arm): add CKV_AZURE_137 Ensure ACR admin account is disabled

- checkov/arm/checks/resource/ACREnableImageQuarantine.py
- tests/arm/checks/resource/example_ACREnableImageQuarantine/fail.json
- tests/arm/checks/resource/example_ACREnableImageQuarantine/pass.json
- tests/arm/checks/resource/test_ACREnableImageQuarantine.py
> feat(arm): add CKV_AZURE_166 Ensure container image quarantine, scan, and mark images verified

- checkov/kubernetes/checks/resource/k8s/Seccomp.py
- tests/kubernetes/checks/example_Seccomp/cronjob-seccomp-FAILED.yaml
- tests/kubernetes/checks/example_Seccomp/cronjob-seccomp-PASSED2.yaml
- tests/kubernetes/checks/example_Seccomp/cronjob-seccomp-PASSED3.yaml
- tests/kubernetes/checks/test_Seccomp.py
> fix(kubernetes): Fix CKV_K8S_31 for CronJobs

- checkov/common/sca/reachability/package_alias_mapping/nodejs/utils.py
- tests/common/sca/reachability/test_alias_mapping_creator.py
> fix(sca): fix parsing json with comments

- checkov/terraform_json/parser.py
- tests/terraform_json/test_parser.py
> fix(terraform_json): support locals block in CDKTF output

- checkov/arm/checks/resource/AzureSearchSLAQueryUpdates.py
- tests/arm/checks/resource/example_AzureSearchSLAQueryUpdates/fail.json
- tests/arm/checks/resource/example_AzureSearchSLAQueryUpdates/fail2.json
- tests/arm/checks/resource/example_AzureSearchSLAQueryUpdates/pass.json
- tests/arm/checks/resource/test_AzureSearchSLAQueryUpdates.py
> feat(arm): AzureSearchSQLQueryUpdates

- checkov/common/bridgecrew/platform_integration.py
- tests/common/integration_features/test_repo_config_integration.py
- tests/common/test_platform_integration.py
> platform(general): pass repo ID to runconfig

- checkov/arm/checks/resource/FunctionAppsEnableAuthentication.py
- tests/arm/checks/resource/example_FunctionAppsEnableAuthentication/fail.json
- tests/arm/checks/resource/example_FunctionAppsEnableAuthentication/fail2.json
- tests/arm/checks/resource/example_FunctionAppsEnableAuthentication/pass2.json
- tests/arm/checks/resource/test_FunctionAppsEnableAuthentication.py
> fix(arm): CKV_AZURE_56 just for authsettingsV2 name

- checkov/arm/checks/resource/AKSPoolTypeIsScaleSet.py
- tests/arm/checks/resource/example_AKSPoolTypeIsScaleSet/fail.json
- tests/arm/checks/resource/example_AKSPoolTypeIsScaleSet/pass.json
- tests/arm/checks/resource/example_AKSPoolTypeIsScaleSet/pass1.json
- tests/arm/checks/resource/test_AKSPoolTypeIsScaleSet.py
- tests/arm/checks/resource/test_SkipJsonRegexPattern.py
> feat(arm): add CKV_AZURE_169 to ensure that AKS use the Paid Sku for its SLA

- tests/arm/checks/resource/test_SkipJsonRegexPattern.py
*fix the right numbers in TestSkipJsonRegexPattern
> fix(general): fix the right numbers in TestSkipJsonRegexPattern

- checkov/terraform/checks/resource/aws/SSMParameterUsesCMK.py
- tests/terraform/checks/resource/aws/example_SSMParameterUsesCMK/main.tf
- tests/terraform/checks/resource/aws/test_SSMParameterUsesCMK.py
> fix(terraform): Exclude String in CKV_AWS_337

- checkov/secrets/plugins/custom_regex_detector.py
> fix(secrets): fix secrets prerun bug

- checkov/terraform/checks/resource/aws/LaunchConfigurationEBSEncryption.py
- tests/terraform/checks/resource/aws/example_LaunchConfigurationEBSEncryption/main.tf
- tests/terraform/checks/resource/aws/test_LaunchConfigurationEBSEncryption.py
> feat(terraform): Update ckv-aws-8 policy - support unknown statement 

- checkov/arm/checks/resource/AzureMLWorkspacePrivateEndpoint.py
- checkov/terraform/checks/resource/azure/AzureSparkPoolIsolatedComputeEnabled.py
- tests/terraform/checks/resource/azure/example_AzureSparkPoolIsolatedComputeEnabled/main.tf
- tests/terraform/checks/resource/azure/test_AzureSparkPoolIsolatedComputeEnabled.py
> fix(terraform): Fix resource type for CKV_AZURE_242

- checkov/common/bridgecrew/platform_integration.py
- checkov/common/util/ext_argument_parser.py
- checkov/common/util/type_forcers.py
- tests/common/test_platform_integration.py
- tests/common/utils/test_type_forcers.py
> platform(general): handle multiple values for the same metadata filter

- checkov/terraform/checks/resource/aws/WAFACLCVE202144228.py
- checkov/terraform/checks/resource/aws/WAFRuleHasAnyActions.py
- tests/terraform/checks/resource/aws/example_WAFACLCVE202144228/main.tf
- tests/terraform/checks/resource/aws/example_WAFRuleHasAnyActions/main.tf
- tests/terraform/checks/resource/aws/test_WAFRuleHasAnyActions.py
> fix(terraform): catch unknowns with WAF configs

- checkov/terraform/plan_parser.py
- tests/terraform/parser/resources/plan_provisioners/tfplan2.json
- tests/terraform/parser/test_plan_parser.py
> fix(terraform_plan): Fix parsing other types of provisioners

- checkov/ansible/checks/graph_checks/GetUrlHttpsOnly.yaml
- tests/ansible/checks/graph_checks/resources/GetUrlHttpsOnly/expected.yaml
- tests/ansible/checks/graph_checks/resources/GetUrlHttpsOnly/unknown.yaml
> fix(ansible): Fix CKV2_ANSIBLE_2

- checkov/arm/checks/resource/KeyVaultDisablesPublicNetworkAccess.py
- tests/arm/checks/resource/example_KeyVaultDisablesPublicNetworkAccess/pass1.json
> fix(arm): Support upper and lower disabled for CKV_AZURE_189

- checkov/terraform/checks/resource/gcp/GoogleSubnetworkIPV6PrivateGoogleEnabled.py
- tests/terraform/checks/resource/gcp/example_GoogleIPV6PrivateGoogleEnabled/main.tf
> fix(terraform): Handle default for CKV_GCP_76

- checkov/terraform/checks/resource/aws/RDSInstancePerformanceInsights.py
- tests/terraform/checks/resource/aws/example_RDSInstancePerformanceInsights/main.tf
- tests/terraform/runner/test_plan_runner.py
> fix(terraform): add condition for CKV_AWS_353

- checkov/secrets/runner.py
Reverts bridgecrewio/checkov#6665
> fix(secrets): revert duplications suppressions for secrets

- checkov/terraform/checks/resource/aws/CloudFrontGeoRestrictionDisabled.py
- checkov/terraform/checks/resource/azure/StorageLocalUsers.py
- tests/terraform/checks/resource/aws/example_CloudFrontGeoRestrictionDisabled/main.tf
- tests/terraform/checks/resource/aws/test_CloudFrontGeoRestrictionDisabled.py
- tests/terraform/checks/resource/azure/example_StorageLocalUsers/main.tf
- tests/terraform/checks/resource/azure/test_StorageLocalUsers.py
> feat(terraform): Add check for local user in storage

- checkov/common/models/consts.py
> fix(sca): add Pipfile and Pipfile.lock to supported package files list

- checkov/kubernetes/checks/resource/k8s/k8s_check_utils.py
- tests/kubernetes/checks/test_k8s_check_utils.py
> fix(kubernetes): Handle non-sting params in command

- checkov/terraform/plan_parser.py
- tests/terraform/parser/resources/plan_after_unknown/tfplan.json
- tests/terraform/parser/test_plan_parser.py
> feat(terraform_plan): Support after_unknown evaluation of complex attributes

- checkov/terraform/checks/graph_checks/aws/SGAttachedToResource.yaml
- tests/terraform/graph/checks/resources/SGAttachedToResource/expected.yaml
- tests/terraform/graph/checks/resources/SGAttachedToResource/main.tf
> fix(terraform): Add opensearch to CKV2_AWS_5

- checkov/dockerfile/parser.py
- tests/dockerfile/resources/multiline_command/Dockerfile
- tests/dockerfile/test_runner.py
> fix(dockerfile): Handle heredoc

- checkov/cloudformation/graph_builder/variable_rendering/renderer.py
- checkov/cloudformation/parser/cfn_keywords.py
- tests/cloudformation/graph/graph_builder/resources/variable_rendering/render_sub/json/test.json
- tests/cloudformation/graph/graph_builder/resources/variable_rendering/render_sub/yaml/test.yaml
- tests/cloudformation/graph/graph_builder/test_render.py
- tests/cloudformation/graph/graph_runner/external_graph_checks/jsonpath_policy.yaml
- tests/cloudformation/graph/graph_runner/resources/jsonpath_policy/fail_dict.json
- tests/cloudformation/graph/graph_runner/resources/jsonpath_policy/fail_str.json
- tests/cloudformation/graph/graph_runner/resources/jsonpath_policy/pass_str.json
- tests/cloudformation/graph/graph_runner/test_running_graph_checks.py
> feat(cloudformation): Support Fn::Sub in cases of using a pseudo parameter

- checkov/secrets/plugins/custom_regex_detector.py
---
<p>Implement a fix in <code>CustomRegexDetector</code> to skip processing empty matches during regex analysis, enhancing performance and accuracy.</p>
<table><tr><th>Topic</th><th>Details</th><tr><td><a href=https://baz.co/changes/bridgecrewio/checkov/6849?tool=ast …
> fix(secrets): skip empty match

- checkov/terraform/checks/resource/aws/AWSCodeGuruHasCMK.py
- tests/terraform/checks/resource/aws/example_AWSCodeGuruHasCMK/AWSCodeGuruHasCMK.tf
- tests/terraform/checks/resource/aws/test_AWSCodeGuruHasCMK.py
> feat(terraform): Add check - ensure AWS CodeGuru resource contains CMK

- checkov/secrets/plugins/custom_regex_detector.py
- tests/secrets/multiline_finding/Dockerfile.mine
- tests/secrets/test_multiline_finding_line_number.py
> fix(secrets): multiline matches show the secret and not the first line

- checkov/cloudformation/graph_builder/variable_rendering/renderer.py
- tests/cloudformation/graph/graph_runner/external_graph_checks/simple_graph_check.yaml
- tests/cloudformation/graph/graph_runner/resources/template_with_parameters_names_identical_to_default_values/example.yaml
- tests/cloudformation/graph/graph_runner/test_running_graph_checks.py
> fix(cloudformation): Fixed issue where Ref was not rendered correctly if the parameter name was identical to the default value

- checkov/secrets/plugins/custom_regex_detector.py
---
<p>Refactor the <code>CustomRegexDetector</code> class to improve the accuracy of line number detection for potential secrets. Introduce error handling in the <code>find_line_number</code> function to ensure robustness against unexpected input.</p> …
> fix(secrets): fix find line

- checkov/arm/graph_builder/variable_rendering/renderer.py
- tests/arm/graph_builder/checks/test_yaml_policies.py
> fix(general): fix_memory error with adding new env

- checkov/common/comment/enum.py
- checkov/terraform/context_parsers/base_parser.py
- tests/terraform/context_parsers/mock_tf_files/inline_suppression.tf
- tests/terraform/context_parsers/test_base_parser.py
> feat(terraform): Add multi skip inline suppression

- checkov/arm/checks/resource/FunctionAppMinTLSVersion.py
- checkov/arm/checks/resource/MySQLPublicAccessDisabled.py
- checkov/terraform/checks/graph_checks/azure/AzureSQLserverNotOverlyPermissive.yaml
- checkov/terraform/checks/graph_checks/azure/VAisEnabledInStorageAccount.yaml
- checkov/terraform/checks/resource/azure/AKSEncryptionAtHostEnabled.py
- checkov/terraform/checks/resource/azure/AKSNodePublicIpDisabled.py
- checkov/terraform/checks/resource/azure/FunctionAppMinTLSVersion.py
- checkov/terraform/checks/resource/azure/SQLServerNoPublicAccess.py
- tests/arm/checks/resource/example_FunctionAppMinTLSVersion/pass4.json
- tests/arm/checks/resource/example_TestMySQLPublicAccessDisabled/fail2.json
- tests/arm/checks/resource/example_TestMySQLPublicAccessDisabled/pass2.json
- tests/arm/checks/resource/test_MySQLPublicAccessDisabled.py
- tests/terraform/checks/resource/azure/example_AKSEncryptionAtHostEnabled/main.tf
- tests/terraform/checks/resource/azure/example_AKSNodePublicIpDisabled/main.tf
- tests/terraform/checks/resource/azure/example_FunctionAppMinTLSVersion/main.tf
- tests/terraform/checks/resource/azure/example_SQLServerNoPublicAccess/main.tf
- tests/terraform/checks/resource/azure/test_AKSEncryptionAtHostEnabled.py
- tests/terraform/checks/resource/azure/test_AKSNodePublicIpDisabled.py
- tests/terraform/checks/resource/azure/test_SQLServerNoPublicAccess.py
- tests/terraform/graph/checks/resources/AzureSQLserverNotOverlyPermissive/expected.yaml
- tests/terraform/graph/checks/resources/AzureSQLserverNotOverlyPermissive/main.tf
- tests/terraform/graph/checks/resources/VAisEnabledInStorageAccount/expected.yaml
- tests/terraform/graph/checks/resources/VAisEnabledInStorageAccount/main.tf
> fix(terraform): Fix CKV_AZURE_227 for Azure V4

- checkov/common/comment/enum.py
- checkov/terraform/context_parsers/base_parser.py
- tests/common/utils/test_utils.py
> feat(general): add cortex:skip for suppressions

- Pipfile
- Pipfile.lock
- setup.py
Bump detect secrets
---
<p>Updates the version of bc-detect-secrets from 1.5.27 to 1.5.33 in both the Pipfile and setup.py. This change also updates several other dependencies in the Pipfile.lock, including aiohappyeyeballs, argcomplete, attrs, and botocore. The update to bc-detect-secrets is likely to include bug fixes, performance improvements, or new features related to detecting secrets in code.</p>
<table><tr><th>Topic</th><th>Details</th><tr><td><a href=https://baz.co/changes/bridgecrewio/checkov/6914?tool=ast&topic=Dependency+Update>Dependency Update</a>
</td><td>Updates bc-detect-secrets and other dependencies to newer versions<details><summary>Modified files (3)</summary><ul><li>Pipfile.lock</li> …
> chore(secrets): bump detect-secrets

- checkov/terraform/checks/terraform/terraform/StateLock.py
- tests/terraform/checks/terraform/terraform/resources/lock/fail.cdk.tf.json
- tests/terraform/checks/terraform/terraform/resources/lock/pass.cdk.tf.json
- tests/terraform/checks/terraform/terraform/test_StateLock.py
> fix(terraform_json): support CDKTF output in CKV_TF_3

- checkov/terraform/checks/resource/azure/StorageLocalUsers.py
- checkov/terraform/checks/terraform/terraform/StateLock.py
- tests/terraform/checks/resource/azure/example_StorageLocalUsers/main.tf
- tests/terraform/checks/resource/azure/test_StorageLocalUsers.py
- tests/terraform/checks/terraform/terraform/resources/lock/unknown_partialconfig.tf
> fix(terraform): Fix for multiple checks

- checkov/terraform/plan_utils.py
> fix(terraform): Skip tsconfig in terraform plan

- checkov/arm/graph_manager.py
- checkov/bicep/graph_manager.py
- checkov/cloudformation/graph_manager.py
- checkov/common/graph/graph_manager.py
- checkov/common/runners/graph_manager.py
- checkov/dockerfile/graph_manager.py
- checkov/kubernetes/graph_manager.py
- checkov/serverless/graph_manager.py
- checkov/terraform/graph_manager.py
- checkov/terraform/runner.py
> feat(terraform): add option to add external_modules_content_cache to terraform build_graph

- checkov/common/bridgecrew/integration_features/features/suppressions_integration.py
- tests/common/integration_features/test_suppressions_integration.py
> fix(general): Support CVE suppressions with the root file in repo

- .github/workflows/pr-test.yml
- checkov/arm/checks/resource/AzureMLWorkspacePrivateEndpoint.py
> chore(general): Add a job to ensure evaluated keys are added to new resource checks

- Pipfile
> chore(general): Restore python version to 3.8 to fix nightly run

- checkov/bicep/checks/graph_checks/SQLServerThreatDetectionTypes.yaml
- tests/bicep/graph/checks/resources/SQLServerThreatDetectionTypes/expected.yaml
- tests/bicep/graph/checks/resources/SQLServerThreatDetectionTypes/main.bicep
- tests/bicep/graph/checks/test_yaml_policies.py
> fix(bicep): Add bicep specific for CKV_AZURE_25 since ARM implementation fails

- checkov/common/util/oidc_utils.py
- checkov/terraform/checks/data/aws/GithubActionsOIDCTrustPolicy.py
- tests/terraform/checks/data/aws/example_GithubActionsOIDCTrustPolicy/main.tf
- tests/terraform/checks/data/aws/test_GithubActionsOIDCTrustPolicy.py
- tests/terraform/checks/resource/azure/example_GithubActionsOIDCTrustPolicy/main.tf
- tests/terraform/checks/resource/azure/test_GithubActionsOIDCTrustPolicy.py
[//]: # "
ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sast|sca|secrets|serverless|terraform|general …
> fix(terraform): CKV_AZURE_249 & CKV_AWS_358 - better support for OIDC 'repo' detection regex and conditions order

- checkov/common/goget/github/get_git.py
- checkov/common/proxy/proxy_client.py
- checkov/common/util/env_vars_config.py
- checkov/terraform/module_loading/loader.py
- checkov/terraform/module_loading/loaders/git_loader.py
- checkov/terraform/module_loading/loaders/registry_loader.py
- checkov/terraform/module_loading/registry.py
This PR intends to fix issues in checkov proxy capabilities. It sets correct proxy attributes for git and tf registry destinations.
---
---
<p>Enhances proxy capabilities for git and registry loaders. Modifies environment variable handling, improves logging, and refactors HTTP requests to support proxy usage. Updates the <code>ProxyClient</code> class and adjusts module loading processes in various loaders.</p>
<table><tr><th>Topic</th><th>Details</th><tr><td><a href=https://baz.co/changes/bridgecrewio/checkov/6992?tool=ast&topic=Proxy+Enhancement>Proxy Enhancement</a>
</td><td>Improves proxy support for git cloning and registry loading operations<details><summary>Modified files …
> feat(general): fix proxy access from git and registry loader

- checkov/terraform/checks/graph_checks/gcp/GCPMySQLdbInstancePoint_In_TimeRecoveryBackupIsEnabled.yaml
- checkov/terraform/checks/resource/aws/AutoScalingLaunchTemplate.py
- checkov/terraform/checks/resource/aws/RDSInstancePerfInsightsEncryptionWithCMK.py
- checkov/terraform/checks/resource/aws/SecretManagerSecret90days.py
- tests/terraform/checks/resource/aws/example_AutoScalingLaunchTemplate/main.tf
- tests/terraform/checks/resource/aws/example_RDSInstancePerfInsightsEncryptionWithCMK/main.tf
- tests/terraform/checks/resource/aws/example_SecretManagerSecret90days/main.tf
- tests/terraform/checks/resource/aws/test_AutoScalingLaunchTemplate.py
- tests/terraform/checks/resource/aws/test_RDSInstancePerfInsightsEncryptionWithCMK.py
- tests/terraform/checks/resource/aws/test_SecretManagerSecret90days.py
- tests/terraform/graph/checks/resources/GCPMySQLdbInstancePoint_In_TimeRecoveryBackupIsEnabled/expected.yaml
- tests/terraform/graph/checks/resources/GCPMySQLdbInstancePoint_In_TimeRecoveryBackupIsEnabled/main.tf
- tests/terraform/runner/test_plan_runner.py
> fix(terraform): Multiple check fixes

- cdk_integration_tests/src/python/ECSClusterContainerInsights/fail__1__.py
- cdk_integration_tests/src/python/ECSClusterContainerInsights/pass.py
- cdk_integration_tests/src/typescript/ECSClusterContainerInsights/fail.ts
- cdk_integration_tests/src/typescript/ECSClusterContainerInsights/pass.ts
- checkov/cdk/checks/python/ECSClusterContainerInsights.yaml
- checkov/cdk/checks/typescript/ECSClusterContainerInsights.yaml
- checkov/cloudformation/checks/resource/aws/ECSClusterContainerInsights.py
- checkov/terraform/checks/resource/aws/ECSClusterContainerInsights.py
- tests/cloudformation/checks/resource/aws/example_ECSClusterContainerInsights/ECSClusterContainerInsights-PASSED2.yaml
- tests/cloudformation/checks/resource/aws/test_ECSClusterContainerInsights.py
- tests/terraform/checks/resource/aws/test_ECSClusterContainerInsights.py
> fix(general): Handle ECS enhanced container insights

- checkov/cloudformation/checks/resource/aws/ParameterStoreCredentials.py
- tests/cloudformation/checks/resource/aws/example_ParameterStoreCredentials/no_crash.yaml
- tests/cloudformation/checks/resource/aws/test_ParameterStoreCredentials.py
> fix(cloudformation): Handle subs in CKV_AWS_384

- checkov/terraform/checks/resource/gcp/CloudArmorWAFACLCVE202144228.py
- tests/terraform/checks/resource/gcp/example_CloudArmorWAFACLCVE202144228/main.tf
- tests/terraform/checks/resource/gcp/test_CloudArmorWAFACLCVE202144228.py
> fix(terraform): Handle new resource type for CKV_GCP_73

- checkov/terraform/checks/graph_checks/azure/AzureMySQLFlexibleServerConfigPrivEndpt.yaml
- checkov/terraform/checks/graph_checks/azure/AzurePostgreSQLFlexibleServerConfigPrivEndpt.yaml
- tests/terraform/graph/checks/resources/AzureMySQLFlexibleServerConfigPrivEndpt/expected.yaml
- tests/terraform/graph/checks/resources/AzureMySQLFlexibleServerConfigPrivEndpt/main.tf
- tests/terraform/graph/checks/resources/AzurePostgreSQLFlexibleServerConfigPrivEndpt/expected.yaml
- tests/terraform/graph/checks/resources/AzurePostgreSQLFlexibleServerConfigPrivEndpt/main.tf
- tests/terraform/graph/checks/test_yaml_policies.py
> feat(terraform): Add azure DB checks for flexible server private endpoints

- checkov/serverless/graph_builder/definition_context.py
- tests/serverless/checks/aws/example_AWSCredentials/AWSCredentials-FAILED-provider_level/serverless.yml
This PR fixes a bug in serverless definitions context building where empty resources were not taken into account.
> feat(serverless): add check for empty resource attributes

- Pipfile
- Pipfile.lock
- checkov/common/bridgecrew/wrapper.py
- setup.py
> chore(general): Update rustworkx

- Pipfile
- Pipfile.lock
- setup.py
> chore(secrets): Bump detect-secrets to remove reported FPs

- Pipfile
- Pipfile.lock
- setup.py
> chore(secrets): Bump detect-secrets to find the right line for private keys

- checkov/terraform/checks/graph_checks/aws/LBWeakCiphers.yaml
- checkov/terraform/checks/resource/aws/ELBPolicyUsesSecureProtocols.py
- tests/terraform/graph/checks/resources/LBWeakCiphers/expected.yaml
- tests/terraform/graph/checks/resources/LBWeakCiphers/main.tf
- tests/terraform/graph/checks/test_yaml_policies.py
> feat(terraform): Add new check and update old around cipher suites

- checkov/common/runners/base_runner.py
In case the repo has been checked out to a path that inadvertently matches one of the excluded directory patterns (i.e. .git), we should check for it, and escape the pattern via ``re.escape()`` instead of just escaping the leading '.' in '.terraform'.
Otherwise, this causes some tests to fail if the repo is checked out to ``~/git/checkov``, as this would match the '.git' excluded directory by virtue of the leading '.' not being escaped.
> fix(general): base_runner: Properly escape excluded directories that begin with '.'

- checkov/secrets/runner.py
- tests/secrets/test_masking_secrets.py
I've observed a race between two unit tests, as shown below. This seems to be a race between the time the runner enumerates the files in the directory, and the time that ``_safe_scan`` gets called to scan them. The exception is from ``os.path.getsize()``, as the runner assumes that the file exists. The path given in the exception is used by ``tests/secrets/test_masking_secrets.py`` and, just so happens to remove its 'tmp' path, which is under the same path being scanned by ``test_same_resources_in_report_and_coordinator``, hence the race.
Therefore, I've put the ``os.path.getsize()`` call within the try block in ``_safe_scan`` so that a warning can be emitted in this …
> fix(secrets): Fix test directory tree race

- checkov/terraform/plan_parser.py
- tests/terraform/parser/test_plan_parser.py
- tests/terraform/runner/resources/plan_with_providers/main.tf
- tests/terraform/runner/resources/plan_with_providers/tfplan.json
- tests/terraform/runner/test_plan_runner.py
Fix matching of `supported_provider` values.
Use the provider name (not the key from the plan which can contain the provider alias) in the provider_map data structure, since this is what `supported_provider` is compared against. Otherwise, some provider checks will only run against providers without an alias.
Fixes #7118
> fix(terraform_plan): use provider name not resource address to fix supported_provider matching

- checkov/common/output/report.py
- tests/common/output/test_junit_report.py
> fix(general): Skip bc_api_key in output

- checkov/terraform/graph_builder/local_graph.py
- tests/terraform/graph/variable_rendering/test_renderer.py
- tests/terraform/graph/variable_rendering/test_resources/list_entry_module_var/module/main.tf
There was an inner bug in our variable rendering process for terraform when trying to evaluate a variable inside a list of len > 1. This fixes the crash, but still lacks variable rendering for the inner values of the list, which should be fixed in a future PR.
> fix(terraform): Fixed crash when using variable rendering inside a list of len > 1

- checkov/terraform/plan_parser.py
- tests/terraform/parser/test_plan_parser.py
- tests/terraform_json/test_parser.py
> fix(terraform_plan): Support count in terraform plan files

- .gitignore
- checkov/terraform/graph_builder/graph_to_tf_definitions.py
- checkov/terraform/graph_builder/local_graph.py
- checkov/terraform/graph_builder/variable_rendering/renderer.py
- checkov/terraform/tf_parser.py
- tests/terraform/graph/variable_rendering/test_render_scenario.py
- tests/terraform/parser/resources/parser_scenarios/tfvars_outside_dir/expected.json
- tests/terraform/parser/resources/parser_scenarios/tfvars_outside_dir/main.tf
- tests/terraform/parser/test_new_parser_modules.py
* Allow for ``--var-file`` arguments outside of the tf dir to be handled correctly
* Use a dict to enforce tfvars precedence, grouping vars by the directory for which they were defined, reducing the number of tfvar nodes added to the graph for a given directory.
* Create variable -> tfvars edges based on the directory for which the var was defined.
* Have _load_files take a list of str instead of os.DirEntry.
* Changed a usage of printf() to logging.debug()
Fixes #4321
> fix(terraform): Handle explicitly-specified tfvars explicitly

- checkov/common/util/env_vars_config.py
- checkov/terraform/module_loading/module_finder.py
- checkov/terraform/module_loading/registry.py
- tests/terraform/module_loading/data/tf_managed_submodules/.terraform/modules/a.b/main.tf
- tests/terraform/module_loading/data/tf_managed_submodules/.terraform/modules/a/main.tf
- tests/terraform/module_loading/data/tf_managed_submodules/.terraform/modules/modules.json
- tests/terraform/module_loading/data/tf_managed_submodules/main.tf
- tests/terraform/module_loading/test_registry.py
- tests/terraform/module_loading/test_runner.py
- tests/terraform/module_loading/test_tf_module_finder.py
If we have managed modules, the output from terraform should be authoratative. This also allows checkov to scan terraform which only pulls in a module, which pulls in submodules, from the root module.
> fix(terraform): Better utilization of managed modules (if enabled)

- checkov/common/util/oidc_utils.py
- checkov/terraform/checks/data/aws/GithubActionsOIDCTrustPolicy.py
- tests/terraform/checks/data/aws/example_GithubActionsOIDCTrustPolicy/main.tf
- tests/terraform/checks/data/aws/test_GithubActionsOIDCTrustPolicy.py
> fix(terraform): Added support in restricting to a specific GitHub organization for GithubActionsOIDCTrustPolicy

- checkov/kustomize/runner.py
- checkov/terraform/module_loading/module_finder.py
- checkov/terraform/parser_utils.py
- checkov/terraform/tf_parser.py
- tests/kustomize/test_runner_image_referencer.py
- tests/terraform/module_loading/data/nested_modules/main.tf
- tests/terraform/module_loading/test_tf_module_finder.py
> fix(terraform): fix issue 7216 module version parsing issue

- checkov/terraform/module_loading/loaders/git_loader.py
- checkov/terraform/module_loading/loaders/github_loader.py
- checkov/terraform/module_loading/registry.py
- tests/terraform/module_loading/test_registry.py
> fix(terraform): fix cloning external modules from private regsitries

- Pipfile
- Pipfile.lock
- setup.py
- tests/terraform/parser/test_hcl2_load_assumptions.py
This PR updates `bc-python-hcl2` to version 0.4.3 which added support for the parsing of terraform provider functions.
Note this fixes an issue where the parsing of a terraform file failed and checkov couldn't run on the file, however it doesn't add support for the calculation of said provider function.
> feat(terraform): Support parsing of provider functions

- checkov/common/graph/graph_builder/variable_rendering/renderer.py
this method perf can be optimized by introducing caching: `for edge in edges_to_render` can go over the same edge multiple times.
also - refactor the entire render_variables_from_edges method - split to multiple private methods.
[//]: # "
- …
> chore(terraform): VariableRenderer - add caching for _update_end_vertices_indexes

- checkov/terraform/graph_builder/variable_rendering/safe_eval_functions.py
- tests/terraform/graph/variable_rendering/test_string_evaluation.py
When parsing "continue" using `asteval` we evaluated as the saved word "continue" in python, however that can be a regular default string in terraform
> fix(terraform): Parse continue as a string rather as a python object

- checkov/terraform/checks/resource/azure/FunctionAppsAccessibleOverHttps.py
Crash with policy CKV_AZURE_70 #6492
[//]: # " …
> fix(terraform): Update FunctionAppsAccessibleOverHttps

- checkov/common/util/http_utils.py
- checkov/terraform/module_loading/loaders/git_loader.py
- tests/terraform/module_loading/loaders/test_git_loader.py
Handled git external module loading with sub-directory but without protocol, specifically when using `git::git` rather than `git::https://...` (or any other protocol instead of https).
This makes sure we correctly parse the sub-directory inside the source url.
> fix(terraform): Handled git external module loading with sub-directory but without protocol

- Pipfile
- Pipfile.lock
- setup.py
> chore(secrets): bump detect secrets to 1.5.45

- checkov/terraform/graph_builder/foreach/module_handler.py
- tests/terraform/runner/resources/for_each/main.tf
- tests/terraform/runner/resources/for_each/simple/alerts.tf
- tests/terraform/runner/resources/for_each/simple/main.tf
- tests/terraform/runner/resources/for_each/simple/outputs.tf
- tests/terraform/runner/test_runner.py
This PR fixes handling of for_each modules where only the first instance used to be populated with the updated for_each attributes. Now we iterate over the entire list.
> feat(terraform): fix foreach module handling
